### ISSUE TITLE
Publishing assets via Composer

### ISSUE THREAD

**Issue by kamilsk** [almasaeed2010/AdminLTE#1010]
Hi! Thanks for awesome Admin control panel theme!

I wrote little [script](https://github.com/kamilsk/Common/blob/master/src/Composer/Script/AdminLte/Publisher.php) for publishing assets via Composer https://github.com/kamilsk/Common/blob/master/docs/TipsAndTricks.md#adminlte-assets-publishing. @almasaeed2010, can I integrate the script in this repository? Or can you add a link to it?

**Comment by Tjoosten** [comment]
404 the link is not found.

**Comment by kamilsk** [comment]
@Tjoosten, sorry about that, I moved it to the wiki: https://github.com/kamilsk/Common/wiki/Tips-and-tricks#adminlte-assets-publishing

**Comment by kamilsk** [comment]
and refactored for PHP 7 version https://github.com/kamilsk/Common/blob/3.x/src/Composer/Script/AdminLte/Publisher.php

**Comment by kamilsk** [comment]
example of usage is located here https://github.com/kamilsk/TinkoffCurrencyAnalyst
