### ISSUE TITLE
Decouple assets

### ISSUE THREAD

**Issue by madalinignisca** [almasaeed2010/AdminLTE#1013]
I suggest that we decouple all other libraries and make install them by using bower.

Anybody in for it?

**Comment by kressly** [comment]
Not everybody using bower

**Comment by madalinignisca** [comment]
Can you give any example of what you use to manage dependencies and updates easier?

**Comment by climaa** [comment]
Directly from github, that's my case. :)

**Comment by madalinignisca** [comment]
Ok. Nevermind. I found a fork that went on my idea and a bit ahead even. We
should close this.  
  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On abr. 16 2016, at 6:58 pm, Carlos &lt;notifications@github.com&gt; wrote:  

> Directly from github, that's my case. :)

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/almasae
ed2010/AdminLTE/issues/1013#issuecomment-210866868)![](https://github.com/noti
fications/beacon/AAl0KfGc7tiwX6UthkHm9cmqQMy0FSGHks5p4SNfgaJpZM4IIWmN.gif)

**Comment by kressly** [comment]
So please close the tread.tks
