### ISSUE TITLE
Template is not rebuilding

### ISSUE THREAD

**Issue by tionsys** [almasaeed2010/AdminLTE#1019]
Hey,

when injecting HTML-elements via Javascript the Template isn't rebuilding properly. Is there any way to revoke a rebuild?
The red area was injected, the blue area moves wrong.

Cheers,

Tion
(I already forgot my name here)

![13064038_518009691705513_889605184_o png](https://cloud.githubusercontent.com/assets/8399783/14716682/5c04123c-07ee-11e6-941b-a865b32ff533.jpg)

**Comment by lenamtl** [comment]
It's look like a div issue, maybe one div is missing or a closing div is missing.
Make sure  the content 1 is in a div.
