### ISSUE TITLE
How to stop element from menu from disappering in noconflict mode

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#1024]
Hello Everybody. 
I am using AdminLte in noconflict mode and everything so far so good except the fact that some part of the menu disappears after i click on it. I was able to solve part of it with the following code

```
<script>


 jQuery( document ).ready(function( $ ) {
// Code that uses jQuery's $ can follow here.


///////////////////////////////////////////////////////////////////////////////
 
(function() {
    var isBootstrapEvent = false;
    if (window.jQuery) {
        var all = jQuery('*');
        jQuery.each(['hide.bs.dropdown', 
            'hide.bs.collapse', 
            'hide.bs.modal', 
            'hide.bs.tooltip',
            'hide.bs.popover'], function(index, eventName) {
            all.on(eventName, function( event ) {
                isBootstrapEvent = true;
            });
        });
    }
    var originalHide = Element.hide;
    Element.addMethods({
        hide: function(element) {
            if(isBootstrapEvent) {
                isBootstrapEvent = false;
                return element;
            }
            return originalHide(element);
        }
    });
})();
		

 		
///////////////////////////////////////////////////////////////////////////////

}); 
</script>

```
But I have realized that the above code only works for Jquery, and prototype and bootstrap but it does not work for Jquery Ui as you can see in the image below

 [Imgur](http://i.imgur.com/89kBVCB.png)

You can check a live preview by visiting 

http://usefaith.voiedusucces.net/adminlte/ 

and then click on the whell at the top right and click on any icon.

@almasaeed2010 please help me out with this and after that i will publish and show people how to use adminlte in noconflict mode

**Comment by kressly** [comment]
@lenamtl can you please help me out 
@almasaeed2010 are you there ?

**Comment by lenamtl** [comment]
Hi, I see the problem, it's happening when we click on the tab item of the right side menu.

When opening the right side menu
I can see this error:
http://usefaith.voiedusucces.net/js/maxjohn_prototype_fonctions.js Failed to load resource: the server responded with a status of 404 (Not Found)

Try to fix this to see if this solve the problem

**Comment by kressly** [comment]
Thanks a lot @lenamtl 
I have done that but the problem persists. Any further help will be much appreciated. And by the way i miss you welcome back

**Comment by lenamtl** [comment]
This issue occured with all your tabs, even those that appear on the dashboard...
So when we click a new tab the previous one disappear.

**Comment by kressly** [comment]
Thanks a lot best friend programmer  @lenamtl .

I have solved most of it 

http://usefaith.voiedusucces.net/adminlte/

by changing the codes positions

I added the following code down the pages

```
<script>


 
   

////// Check for tooltip of jquery ui
jQuery.noConflict();
if (Prototype.BrowserFeatures.ElementExtensions) {
  var pluginsToDisable = ['tab', 'collapse', 'dropdown', 'modal', 'tooltip', 'popover'];
  var disablePrototypeJS = function (method, pluginsToDisable) {
    var handler = function (event) {
      event.target[method] = undefined;
      setTimeout(function () {
        delete event.target[method];
      }, 0);
    };
    pluginsToDisable.each(function (plugin) {
      jQuery(window).on(method + '.bs.' + plugin, handler);
    });
  };


  disablePrototypeJS('show', pluginsToDisable);
  disablePrototypeJS('hide', pluginsToDisable);
}
//////////////////////////////////////




 jQuery( document ).ready(function( $ ) {
// Code that uses jQuery's $ can follow here.


///////////////////////////////////////////////////////////////////////////////
 
(function() {
    var isBootstrapEvent = false;
    if (window.jQuery) {
        var all = jQuery('*');
        jQuery.each(['hide.bs.dropdown', 
            'hide.bs.collapse', 
            'hide.bs.modal', 
            'hide.bs.tooltip',
            'hide.bs.popover'], function(index, eventName) {
            all.on(eventName, function( event ) {
                isBootstrapEvent = true;
            });
        });
    }
    var originalHide = Element.hide;
    Element.addMethods({
        hide: function(element) {
            if(isBootstrapEvent) {
                isBootstrapEvent = false;
                return element;
            }
            return originalHide(element);
        }
    });
})();
		
 
 		
///////////////////////////////////////////////////////////////////////////////

});

   
 
</script>

```
Everything works perfectly now except when i click on the button close to the calendar, and i do not choose any action, it disappears.

![adminlte 1](https://cloud.githubusercontent.com/assets/925132/15077963/7a76382c-13a0-11e6-89cd-d2eb8400f903.png)

**Comment by lenamtl** [comment]
When closing any widget it disappear from the dashboard, this is normal..
And the widget will reappear only page refresh. I added a refresh button for my users.

You can add some validation on the close button if you want to make sure an action is performed or saved before closing the widget.

**Comment by kressly** [comment]
Tks a lot @lenamtl .
However it is not the close button that I clicked on but the calendar button where we select the date. When I select the date it works perfectly but when I click on it and do not select the date, the button for the calendar disappears

**Comment by lenamtl** [comment]
ok sorry I have misread...

which calendar are you talking exactly?
(which page or code)?

**Comment by kressly** [comment]
This page
http://usefaith.voiedusucces.net/adminlte/


![adminlte 1](https://cloud.githubusercontent.com/assets/925132/15178015/b0ca06cc-1762-11e6-8b7e-03f1eddeb495.png)

So everything works perfectly but when you select the calendar button and you do not select anything and click somewhere else, it disappears. 

@lenamtl please do you have any solution for that ?

Thanks a lot for everything

**Comment by lenamtl** [comment]
Hi, it's look like you have fixed it...

**Comment by kressly** [comment]
No it has not yet been fixed. Please click twice on it without selecting anything and you will see that it will disapear

**Comment by lenamtl** [comment]
Ok I see now, 
I cannot catch any error related to it.
But I got this error 
`bootstrap3-wysihtml5.all.min.js:3 Discontiguous selection is not supported.(anonymous function) @ bootstrap3-wysihtml5.all.min.js:3(anonymous function) @ bootstrap3-wysihtml5.all.min.js:3(anonymous function) @ bootstrap3-wysihtml5.all.min.js:2n.init @ bootstrap3-wysihtml5.all.min.js:2l @ bootstrap3-wysihtml5.all.min.js:2v @ bootstrap3-wysihtml5.all.min.js:2`

**Comment by kressly** [comment]
Thanks a lot @lenamtl . You're the best friend i have in here. 
Sorry my internet was slow lately and that has been the reason for my late answer. Tks
