### ISSUE TITLE
AdminLTE app.js seems conflict with highcharts bar chart

### ISSUE THREAD

**Issue by playniuniu** [almasaeed2010/AdminLTE#105]
Hi All

I have used AdminLTE with highcharts js, it works so fine with all kind of highcharts chart type except the bar chart type. When I remove the adminlte app.js, and highcharts bar chart type can work

The highcharts bar chart demo I used is this  http://www.highcharts.com/demo/bar-stacked

Does anyone know what's the problem here?

P.S  

My chrome log is show that "Uncaught TypeError: Cannot read property 'defaultView' of undefined " when adminlte app.js work with highchart bar chart type

**Comment by omerOksuzlerTEAM6** [comment]
I only copied the parts from app.js to the particular file where highcharts was conflicting with so that not all pages are affected due to the change on app.js.

**Comment by RubenDjOn** [comment]
Same problem here. Solved commenting the `jQuery resize event - v1.1 - 3/14/2010` related code on `AdminLTE/app.js`, as @StefanoF suggested above.

**Comment by Wisit** [comment]
Could you please specific portion of  app.js code issue?

**Comment by RubenDjOn** [comment]
This is the portion of code I commented out to avoid the `Uncaught TypeError: Cannot read property 'defaultView' of undefined` error.
```javascript
/*
 * jQuery resize event - v1.1 - 3/14/2010
 * http://benalman.com/projects/jquery-resize-plugin/
 * 
 * Copyright (c) 2010 "Cowboy" Ben Alman
 * Dual licensed under the MIT and GPL licenses.
 * http://benalman.com/about/license/
 */
(function($, h, c) {
    var a = $([]), e = $.resize = $.extend($.resize, {}), i, k = "setTimeout", j = "resize", d = j + "-special-event", b = "delay", f = "throttleWindow";
    e[b] = 250;
    e[f] = true;
    $.event.special[j] = {setup: function() {
            if (!e[f] && this[k]) {
                return false;
            }
            var l = $(this);
            a = a.add(l);
            $.data(this, d, {w: l.width(), h: l.height()});
            if (a.length === 1) {
                g();
            }
        }, teardown: function() {
            if (!e[f] && this[k]) {
                return false
            }
            var l = $(this);
            a = a.not(l);
            l.removeData(d);
            if (!a.length) {
                clearTimeout(i);
            }
        }, add: function(l) {
            if (!e[f] && this[k]) {
                return false
            }
            var n;
            function m(s, o, p) {
                var q = $(this), r = $.data(this, d);
                r.w = o !== c ? o : q.width();
                r.h = p !== c ? p : q.height();
                n.apply(this, arguments)
            }
            if ($.isFunction(l)) {
                n = l;
                return m
            } else {
                n = l.handler;
                l.handler = m
            }
        }};
    function g() {
        i = h[k](function() {
            a.each(function() {
                var n = $(this), m = n.width(), l = n.height(), o = $.data(this, d);
                if (m !== o.w || l !== o.h) {
                    n.trigger(j, [o.w = m, o.h = l])
                }
            });
            g()
        }, e[b])
    }}
)(jQuery, this);
```

The version of AdminLTE I'm using is `Date: 4 Jan 2014`.

**Comment by Wisit** [comment]
my step solv this problem 
I use inspection element of firefox to debug problem 
1. make sure check highcharts.js load in view page 
2. at the console inspection i found app.js (or app.min.js) error at line number 186 about tooltip function, comment out and try reload view page again. if chart can display so tooltip may be conflict with highcharts widget.
3. in my project not found bootstrap-tooltip.js so I copy file from another project (or download from internet also) and paste into my project  after that register tooltip in AppAsset 
4. revert comment out from choice 2 and try to reload view page again, if everything was to be you suspect chart can display with again 
![fb_img_1442800364063](https://cloud.githubusercontent.com/assets/1933011/9984260/8bbbb0d2-603e-11e5-9521-853dba112b14.jpg)
![fb_img_1442800373428](https://cloud.githubusercontent.com/assets/1933011/9984263/8df8157a-603e-11e5-926f-1e3527b8e07d.jpg)
![fb_img_1442800381779](https://cloud.githubusercontent.com/assets/1933011/9984264/9036e398-603e-11e5-9ecb-21adebf3a0d1.jpg)
