### ISSUE TITLE
Window resize fixes layout - bottom of the page has initially big white blank space

### ISSUE THREAD

**Issue by huovnn** [almasaeed2010/AdminLTE#1057]
Well, the topic pretty much covers the issue. Initially my page has white blank space on the bottom of screen, but if I resize the window it fixes itself. I pretty much copy pasted the starter page, dunno why the starter page is working just fine tho...

**Comment by huovnn** [comment]
https://github.com/almasaeed2010/AdminLTE/issues/1033

Excactly the same issue here, but I'm just using Angular 1.5. Any suggestions?

**Comment by almasaeed2010** [comment]
Thanks for sharing your solution. I am sure this will be beneficial to others.

**Comment by divinoro** [comment]
I'm not using Angular, just plain AdminLTE - getting very same problem and solution above does not work at all.

**Comment by marcosPerezRubio** [comment]
Using Angular 1.5, the solution provided doesn't work all the times. In fact, the first time I load the webpage is working okai, but if i refresh it stops working.

Any idea? 

Thanks!

**Comment by divinoro** [comment]
..anyway, if you can point me to the JS methods od AdminLTE, I can give more tries.. but I'm struggling to find them.
