### ISSUE TITLE
Improve GitHub search

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#1058]
Hey there!

When searching for **admin template** here in GitHub, the most stared result is a template with 5k stars. Which means AdminLTE missed this simple search.

The AdminLTE readme has this text: "AdminLTE -- is a fully responsive **admin template**"

So, even with this headline, this template misses the search I said above.

Is there a way to improve GitHub search for this template, so it would get even more stars/users?

Thanks!

**Comment by Tjoosten** [comment]
I think it is in the algorithm form github.
