### ISSUE TITLE
Non-ASCII character is not supported in Profile Icon

### ISSUE THREAD

**Issue by luronumen** [almasaeed2010/AdminLTE#1060]
LÚCÌÃNÔ is displayed like this in the Profile Icon:
![image](https://cloud.githubusercontent.com/assets/8019466/15487269/43bc25d2-2122-11e6-9bc0-26c2a6736544.png)

**Comment by nyedidikeke** [comment]
@luronumen: Non-ASCII characters are supported; just tried on a fresh AdminLTE download.

**Comment by luronumen** [comment]
It was a issue from my SW side. Sorry for that! :(

Best Regards,
Luciano
