### ISSUE TITLE
Sidebar intermediate menu

### ISSUE THREAD

**Issue by adrianomedeirossantos** [almasaeed2010/AdminLTE#1062]
Hello, folks.

First of all, I would like to congrat all contributors of this amazing project. To whom is terrible with CSS, this project is a source of knowledge and "magic tricks". Some others bootstrap theme such as [Gentelella](https://colorlib.com/polygon/gentelella/) offer an intermediary size menu, it is pretty much like the sidebar-mini but the title does not disappear. 

Any chance to add this type of sidebar?

Best regards,

**Comment by almasaeed2010** [comment]
Thanks for the compliments and sorry for the delayed reply. I'll consider this a suggestion and add it to the list. Thanks!

**Comment by adrianomedeirossantos** [comment]
Great! 
Thanks!

**Comment by almasaeed2010** [comment]
I don't believe we will be able to add support for this since our menus are built differently. Sorry!

(closing because the issue has been inactive for a long time)
