### ISSUE TITLE
Admin LTE 2 and it's own namespace

### ISSUE THREAD

**Issue by StiiCeva** [almasaeed2010/AdminLTE#1063]
Hi @almasaeed2010 !
Is there a way to create a namespace for Admin LTE 2? 

I'm trying to use it in an old site and it conflicts with the old style sheets. 

Can you please offer some guidance in this matter!  I have trying to build it from source after I modified it but it seems I'm missing something. 

Thanks in advance!

**Comment by almasaeed2010** [comment]
Unfortunately, this is not easily possible. Unless you want to do it manually via search and replace, there isn't really any other way.

We will consider this in the next version. Thanks!
