### ISSUE TITLE
Javascript Save Box Widget State

### ISSUE THREAD

**Issue by BlueTeck** [almasaeed2010/AdminLTE#1064]
Hi all,

I wanted so save the collapse state of a box, so when I open the page again, it is still collapsed/open.
I wrote some javascript, but maybe this is not the way and somebody could improve it, or somebody want to use it too.

Normal box widget, with an additional _data-name_ tag.
```html
    <div class="box" data-name="tasks">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            This is the content
        </div>
    </div>
```
Javascript that saves state in localstorage and load it from there on page load:
```javascript
    $($.AdminLTE.options.boxWidgetOptions.boxWidgetSelectors.collapse).click(function () {
        var box = this.closest('.box');
        var boxname = $(box).data('name');
        if(boxname !== undefined){
            var boxstates = localStorage.box_state;
            if(!boxstates){
                boxstates = [];
            } else {
                boxstates = JSON.parse(boxstates);
            }
            boxstates = $.grep(boxstates, function(n) {
                return n.boxname != boxname;
            });
            boxstates.push({'boxname': boxname, 'state': $(box).hasClass('collapsed-box') ? 1 : 0});
            localStorage.box_state = JSON.stringify(boxstates);
        }
    });
    //load states
    var boxstates = localStorage.box_state;
    if(!boxstates){
        boxstates = [];
    } else {
        boxstates = JSON.parse(boxstates);
    }
    boxstates.forEach(function(box) {
        if(box.state == 0){
            //collapse/click box
            $('.box[data-name="'+box.boxname+'"]').find($.AdminLTE.options.boxWidgetOptions.boxWidgetSelectors.collapse).trigger( "click" );
        }
    });
```
Localstorage:
![image](https://cloud.githubusercontent.com/assets/1961634/15722264/2b9548ae-283d-11e6-9407-42b52e39b23a.png)

Maybe someone has an improvement or could use it,
regards,
Timo

**Comment by almasaeed2010** [comment]
Hello,

In my opinion, this should be handled in the server side. This is the only way you can guarantee the persistence of the state throughout all devices used by a single account.

Thanks!

**Comment by lenamtl** [comment]
Hi @BlueTeck  just to let you know there is a case that it is not working 
this s when the box is collapsed by default with collapsed-box class
`<div class="box box-primary collapsed-box" id="filters" data-name="filters">`
