### ISSUE TITLE
Cannot install from Visual Studio Bower Package Manager

### ISSUE THREAD

**Issue by anuith** [almasaeed2010/AdminLTE#1068]
Hi,
I am trying to install the package via Visual Studio Bower Package Manager. But the bower output says `ENOTFOUND Package AdminLTE not found` but version selection and package description seems to work fine.

I think there is a problem with bower package repository or something. But my knowledge about bower is little. I don't know where the VS PM searches for packages. And I don't know where to investigate more.

I have manually added `admin-lte` to the `bower.json` and it installed fine. I am trying to use it.

**Comment by laravelish** [comment]
bower install admin-lte
