### ISSUE TITLE
How can I disable a link in the sidebar using jquery?

### ISSUE THREAD

**Issue by bilalhussain69** [almasaeed2010/AdminLTE#1069]
I am trying to disable a link in the sidebar treemenu so that if some particular conditions are true then the link in sidebar should b disabled and it should neither be expanded like it does now when clicked.
any idea how can I do this ?
I have tried to disable the click event listeners of sidebar li items by giving them a class and using the below code, but still it gets opened/expanded on click

```
   $(".do-not-open").on("click", function (e) {

    alert("Please select fields first");
// $(this).unbind("click")
    $(this).off("click")

        return;

})
```

**Comment by ObaidAshraf** [comment]
Did you try the "pointer-events" property of CSS ??? i might help you ..
Consider this link for help: https://css-tricks.com/almanac/properties/p/pointer-events/

**Comment by bulabula001** [comment]
add css and js below:
`<style type="text/css">
    .gxt_li_disabled{
    pointer-events:none; 
    }
</style>`

`    $(".disabled").click(function (event) {
       event.preventDefault();        
    });`
