### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by HelaSk** [almasaeed2010/AdminLTE#1071]
I see that french language is not supported can you add it?

**Comment by lenamtl** [comment]
Hi, it is supported you need to use UTF-8 without BOM when you save the page (notepad++) & UTF-8 for MySQL DB.

And don't remove `<meta charset="utf-8">` from the head

**Comment by memento** [comment]
I have the same issue but I didn't edit any of the files.

```
??error.title_fr_FR??
??error.subtitle_fr_FR??

??error.status_fr_FR?? Not Found (Not Found)
??error.message_fr_FR?? Not Found
```

**Comment by lenamtl** [comment]
You have to edit the file, follow my instructions, it's working ok I'm using it in french environment.

**Comment by kressly** [comment]
Try what lenamtl said word by word because she speaks French . And she is very good at a lot of IT stuff. She is a senior Admilte user lol

**Comment by memento** [comment]
Hi, Thanks for your help. Do you have the list of files that I should re-edit, by any chance. What file would have trigger this error ?
I've tried to batch edit and save in UTF8 the whole project with a notepad++ macro, but I still have the same problem. I think I need to do do it in a ___surgical strike___ way.

Are we looking at a css file, html file, typescript file, ..., ? You name it

Thanks for your time.
Merci d'avance ! :)

**Comment by lenamtl** [comment]
First let do a quick test

Just do a test using one of the html page provided into the examples 
**one page that you have not edited yet.

Open the page using Notepad++
Top menu -- Click Encoding select UTF-8 
Now enter some french letter into the text area **éèôç** then save the page
View the page for better result use a web server like (wampserver).

Now does the letters displayed ok  éèôç ?
Please let me know the result so we can help you.
