### ISSUE TITLE
Fixed the position of header

### ISSUE THREAD

**Issue by timusiiit123** [almasaeed2010/AdminLTE#1072]
How can I fixed the header of this template not loosing responsiveness as I do the toggle button for the left sidebar?Please help me to solve it, it is very important to me.

**Comment by ObaidAshraf** [comment]
Can you upload the picture of the issue you are facing??

**Comment by timusiiit123** [comment]
When I used within span tag with the position:fixed then - 
![screenshot 9](https://cloud.githubusercontent.com/assets/19756818/15983590/a8b6c7ba-2f61-11e6-9eed-381f314e5e8a.png)

When I used the position:fixed in the header tag then - 
![screenshot 10](https://cloud.githubusercontent.com/assets/19756818/15983594/ce1d5b86-2f61-11e6-9deb-d44f74061ba8.png)

**Comment by ObaidAshraf** [comment]
Please close the issue now.
