### ISSUE TITLE
AdminLTE Dark theme [Suggestion]

### ISSUE THREAD

**Issue by andreaspalmer** [almasaeed2010/AdminLTE#1074]
Hey there,

Will there be a dark theme available for the Admin LTE template? 
For example you could add "inverse" or "dark" to the body tag, like the different themes and have a dark theme? That would be an awesome add-on, specially when working at night!

**Comment by almasaeed2010** [comment]
We'll keep that in mind when developing the next version. 

Thank you!

**Comment by almasaeed2010** [comment]
Unfortunately we don't have the means to convert the entire template to support a dark implementation since that requires converting a lot of the existing code to support this feature. I apologize for the inconvenience :(
