### ISSUE TITLE
Browser becoming very slow

### ISSUE THREAD

**Issue by javedofhumber** [almasaeed2010/AdminLTE#1075]
HI,
whenever i run the application using this theme, the browser and the speed of the computer is affected. It becomes very slow. And I have a i7 processor with 16 gb ram. Please advise what to do. Thanks. Great job with the template

**Comment by arianmaykon** [comment]
Are you sure this is caused due to the theme? Can you check you computer processes, or better, the Google Chrome process manager?

**Comment by fschaeffer** [comment]
There were sone issues regarding chrome css animations in Bootstrap Progressbar... maybe this could cause the slowdown
