### ISSUE TITLE
Calendar Print view

### ISSUE THREAD

**Issue by DawoudIO** [almasaeed2010/AdminLTE#1078]
Hi All, 

If you try to print the following page https://almsaeedstudio.com/themes/AdminLTE/pages/calendar.html you will see the google link showing up as 
```
Click for Google
(http://google.com/
```
vs
```
Click for Google
```

Also if there a way to hide the nav bar during printing

**Comment by Phiph** [comment]
Hi @DawoudIO,

Bootstrap has a CSS class for hiding elements for printing.

` hidden-print`


Have a play around and find the best solution, there is also a stock overflow here that asks the same question :) 

http://stackoverflow.com/questions/7301989/need-to-remove-href-values-when-printing-in-chrome
 
Happy coding!
