### ISSUE TITLE
Sidebar menu, highlighting currently selected menu

### ISSUE THREAD

**Issue by samoei** [almasaeed2010/AdminLTE#108]
It seems there is something am not getting right with the sidebar-menu. I can not get it to assign the active css class to the currently selected menu (or treeview menu in the case of tree). The dashboard menu is always active. I have gone through your app.js especially SIDEBAR MENU function (around line 555) but i cant see where your are assigning the currently selected menu a css active class. Kindly clarify for me. Thanks

**Comment by blah73** [comment]
I've seen this done automatically with Jquery on standard bootstrap navbar items.  Loop through the hrefs and if the link matches the current page then add the active class.

http://stackoverflow.com/questions/11533542/twitter-bootstrap-add-active-class-to-li

**Comment by alpacin0** [comment]
In Laravel I do like this:
**Route:**
```
Route::group(['prefix' => 'person'], function(){
Route::get('{id}/Personal','UsersController@personal')->name('personal');
});
```

**Sidebar-menu**
```
 <ul class="sidebar-menu">
          <li class="treeview {!! Request::is('person/*/Personal') ? 'active' : '' !!}">
                <a href="{!!route('personal', $user)!!}">
                    <i class="fa fa-briefcase"></i>&nbsp;<span>Persona Example</span>
                </a>
        </li>
</ul>
```

**Comment by coscho** [comment]
here is my solution:

```
//Enable sidebar dinamic menu
$.AdminLTE.dinamicMenu();
```
```
/* DinamicMenu()
     * dinamic activate menu
     */
    $.AdminLTE.dinamicMenu = function() {
        var url = window.location;
        // Will only work if string in href matches with location
        $('.treeview-menu li a[href="' + url + '"]').parent().addClass('active');
        // Will also work for relative and absolute hrefs
        $('.treeview-menu li a').filter(function() {
            return this.href == url;
        }).parent().parent().parent().addClass('active');
    };
```

**Comment by TintinFr** [comment]
I change one line to the previous script

`/* DinamicMenu()
     * dinamic activate menu
     */
$.AdminLTE.dinamicMenu = function () {
    var url = $(location).attr('href');
    var path = $(location).attr('pathname');
    // Will only work if string in href matches with location
    $('.treeview-menu li a[href="' + path + '"]').parent().addClass('active');
    // Will also work for relative and absolute hrefs
    $('.treeview-menu li a').filter(function () {
        return this.href == url;
    }).parent().parent().parent().addClass('active');
};`

**Comment by ecmascriptguru** [comment]
Hi,

I use this template in Vue.js and want to know how to mark left side menu item an active depending on route.

**Comment by lenamtl** [comment]
Hi, you can see my solution with JS and adapt it.
#1482

**Comment by syarifuddinahmads** [comment]
@coscho Thanks very much
 its work for me

**Comment by Iqbal487** [comment]
hi , i am using this Theme in my project , but when the page is load it shows the menu item for the first time .
When i clicked  the dashboard item , it is not opened later .

After Reload the page for the first time
![after reload](https://user-images.githubusercontent.com/15795139/46548011-a1acde80-c8ef-11e8-998e-7003a8edd3fd.PNG)
when i clicked the pull container right option it is clicked but menu  dashboard item is not shown --
![image](https://user-images.githubusercontent.com/15795139/46548085-da4cb800-c8ef-11e8-9513-266be9b87a96.png)

here is my code --
 <li class="active treeview menu-open">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class=" active treeview-menu">
            <li class="active"><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
            <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
          </ul>
        </li>
please help me to solve this problem

**Comment by dineshsuthar92** [comment]
> In Laravel I do like this:
> **Route:**
> 
> ```
> Route::group(['prefix' => 'person'], function(){
> Route::get('{id}/Personal','UsersController@personal')->name('personal');
> });
> ```
> **Sidebar-menu**
> 
> ```
>  <ul class="sidebar-menu">
>           <li class="treeview {!! Request::is('person/*/Personal') ? 'active' : '' !!}">
>                 <a href="{!!route('personal', $user)!!}">
>                     <i class="fa fa-briefcase"></i>&nbsp;<span>Persona Example</span>
>                 </a>
>         </li>
> </ul>
> ```

Thanks buddy :smiley:

**Comment by neoacevedo** [comment]
For laravel, I don't play with blade, I use jQuery, just like this comment: https://github.com/almasaeed2010/AdminLTE/issues/1482#issuecomment-349304120 that worked to me.

**Comment by manikandanjmk** [comment]
This code will helpful to multiple multilevel in side menu...
$(document).ready(function(){
                /** add active class and stay opened when selected */
                var url = window.location;
                // for sidebar menu entirely but not cover treeview
                $('ul.sidebar-menu a').filter(function() {
                     return this.href == url;
                }).parent().addClass('active');

                // for treeview
                $('ul.treeview-menu a').filter(function() {
                     return this.href == url;
                }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
            });

**Comment by Love9056** [comment]
>  $.AdminLTE.dinamicMenu = function() {
>         var url = window.location;
>         // Will only work if string in href matches with location
>         $('.treeview-menu li a[href="' + url + '"]').parent().addClass('active');
>         // Will also work for relative and absolute hrefs
>         $('.treeview-menu li a').filter(function() {
>             return this.href == url;
>         }).parent().parent().parent().addClass('active');
>     };

not working i have added this to my js file still not worked let me know how to apply this

**Comment by DEVRam86** [comment]
> This code will helpful to multiple multilevel in side menu...
> 
> ```
> $(document).ready(function(){
>                 /** add active class and stay opened when selected */
>                 var url = window.location;
>                 // for sidebar menu entirely but not cover treeview
>                 $('ul.sidebar-menu a').filter(function() {
>                      return this.href == url;
>                 }).parent().addClass('active');
> 
>                 // for treeview
>                 $('ul.treeview-menu a').filter(function() {
>                      return this.href == url;
>                 }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
>             });
> ```

Where to apply this. Kindly help. I am using this template as masterpage in asp.net web forms.

**Comment by muhammad-fahd** [comment]
In my case, none of the above was not working.

This is what I have done to set the multilevel menu selected'

`    var pageUrl = window.location.pathname;
    var menu = $(`.sidebar .sidebar-menu li a[href="${pageUrl}"]`).parent('li');
    menu.addClass('active');

    var treeLi = menu.parent().parent(); 
    if (treeLi.hasClass('treeview'))
        treeLi.addClass('active');`
