### ISSUE TITLE
<li> lost the "active" class after Collapsing parent menu

### ISSUE THREAD

**Issue by whahuzhihao** [almasaeed2010/AdminLTE#1080]
In sidebar area, when you expand treeview-menu after collapsing it , the child <li> element will lose the active class.

**Comment by ObaidAshraf** [comment]
Check and apply Pull request #1073 ..

**Comment by cyrilchapon** [comment]
in addition, any sibling menu item (same level) also loose .active

https://github.com/almasaeed2010/AdminLTE/issues/1209

**Comment by cyrilchapon** [comment]
- Pulling last release (v2.3.6) doesn't fix
- Neither does current master (1a89a2feabad28fa53fc1bc994788721e46f16a2)
- Only @maxolasersquad version [https://github.com/Captiveyes/AdminLTE/commit/2a22f7c72fc24accfcc3c66606b3d186114a6ec5] fixes

**Comment by Leodime** [comment]
Actually removing this line:
**_parent.find('li.active').removeClass('active');_**
 doesn't fix it. It just set every parent element to **_active_**.

Doing this instead worked for me: 
**parent.find('.treeview.active').removeClass('active');**

I hope it works for you too.
