### ISSUE TITLE
.content-wrapper click event not fire on mobile browser?

### ISSUE THREAD

**Issue by postgetme** [almasaeed2010/AdminLTE#1081]
I find sidebar can't hide when click content-wrapper area in mobile browser(it works in desktop browser), and I find this issue is related to the code below which in the Adminlte initial file. anyone can tell something? 
```
$(".content-wrapper").click(function () {
    //Enable hide menu when clicking on the content-wrapper on small screens
    if ($(window).width() <= (screenSizes.sm - 1) && $("body").hasClass("sidebar-open")) {
        $("body").removeClass('sidebar-open');
    }
});
```

**Comment by almasaeed2010** [comment]
Please specify the device and the browser. I tested on iPhone 6s Safari and it works.

Thanks!
