### ISSUE TITLE
Changing SideBar Width

### ISSUE THREAD

**Issue by hMounir** [almasaeed2010/AdminLTE#1083]
Hello, I'm a novice in CSS and bootstrap, I need to change the sidebar-menu width because I have multi level menu with long texts, so what are the changes needed to be done ?

**Comment by almasaeed2010** [comment]
Hello,

The best and fastest way to do that is through the LESS variables. In ```build/less/variables.less```, find the variable ```@sidebar-width``` and change to the desired value. Then recompile the less by running ```grunt``` or by using this tool: http://winless.org/

Thanks.

**Comment by gamesover** [comment]
Actually, the more appropriate way is adminlte provide a config file or interface, so user could easily change those widths.
