### ISSUE TITLE
sidebar mini dynamic issue

### ISSUE THREAD

**Issue by akshay12345vin** [almasaeed2010/AdminLTE#1085]
![issue](https://cloud.githubusercontent.com/assets/10510889/16371072/cc009d7e-3c61-11e6-818c-03e56c9a53c9.png)

this is happend when i collpse the sidebar. its normal when its static but when its came to dynamic 
this is the result is anyone have the same issue pls help

**Comment by almasaeed2010** [comment]
Hello,

You want to try to run ```$.AdminLTE.tree('.sidebar');``` after you generate a new link dynamically.

Thanks.

**Comment by akshay12345vin** [comment]
after everylink or after every treeview?

**Comment by almasaeed2010** [comment]
I'd try after every link. Let me know if it works.
