### ISSUE TITLE
Read If Your Issue Has Been Closed Without a Response

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#1086]
Hello everyone,

Recently, I wasn't able to work on AdminLTE and somewhat neglected it. Therefore, many issues remained unresolved or stayed open when they should've been closed. Due to the massive number of issues that were open, I had to close all issues that are older than a month. If your issue has been closed but not resolved, then by all means repost your issue for reconsideration. We will do our best to be more active and help you out. You could also tell me to reopen your issue if you'd like and I will.

Thanks for your understanding and we apologize for any inconvenience!

**Comment by kspearrin** [comment]
Can you just reopen this issue? There is some good dialog and detail there that I would rather not just re-type up. It is still a problem.

https://github.com/almasaeed2010/AdminLTE/issues/683

**Comment by almasaeed2010** [comment]
No problem
