### ISSUE TITLE
Clicking on jQuery Knob Tron Style fires onClick event and changes skin

### ISSUE THREAD

**Issue by blz-ea** [almasaeed2010/AdminLTE#1091]
I noticed when you click on a tron styled knob it triggers `$("[data-skin]").on('click')` event in demo.js and changes skin completely.

![screenshot from 2016-06-29 10 00 41](https://cloud.githubusercontent.com/assets/19339605/16441044/60a4138c-3de0-11e6-82ae-8fa1e80e5d58.png)

This issue is related to data-skin attribute
` <input type="text" class="knob" value="80" **data-skin="tron"** data-thickness="0.2" data-width="90" data-height="90" data-fgColor="#3c8dbc" data-readonly="true">`
and to the line (1078) in inline.html:
`if (this.$.data('skin') == 'tron') {`

**Comment by almasaeed2010** [comment]
Fixed in master. This next minor release will contain the fix (2.3.4).

Thanks!
