### ISSUE TITLE
Bug pieChart graph

### ISSUE THREAD

**Issue by Fukotaku** [almasaeed2010/AdminLTE#1092]
Hi, i'm a problem for the pieChart.
I must necessarily add this chart html code :

```
<div class="chart">
  <!-- Sales Chart Canvas -->
  <canvas id="salesChart"></canvas>
</div>
```

with my graphic (Chart) that I want to use on the file html

```
<div class="chart chart-responsive">
  <canvas id="pieChart" style="height: 150px;"></canvas>
</div>
```

for that my pieChart runs.
Please help, I'm not an expert in js.

**Comment by almasaeed2010** [comment]
Hello @Fukotaku,

I am not sure what the problem is. Could you give an example? A screenshot perhaps?

Thanks
