### ISSUE TITLE
Should not force .navbar to be direct child of .main-header

### ISSUE THREAD

**Issue by qtuan** [almasaeed2010/AdminLTE#1093]
Several times I have a use case that the main `.navbar` cannot be a direct child of `.main-header` because it is encapsulated in a custom component. So the HTML structure is rather like: 
`.main-header > nav-bar-element > .navbar`

That cause a bit problem with styling because `AdminLTE.css` have several `.main-header>.navbar`. Currently I can fix it by an overriding CSS, but could you consider to lift this restriction? Thanks!

**Comment by almasaeed2010** [comment]
Hello @qtuan,

Interesting issue. I wonder though, why can't you encapsulate the whole ```.main-header``` instead of the ```.navbar```?

Thanks!

**Comment by almasaeed2010** [comment]
Fixed in master. We also noticed an inconsistency with the definition of the rule so we made it consistent by removing the ```>``` completely.

Thanks for pointing that out.

**Comment by qtuan** [comment]
hello @almasaeed2010,

> why can't you encapsulate the whole .main-header instead of the .navbar?

Just due to our modularization logic. We think that `header` can contain other elements.

Thanks for your quick response and fix!
