### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by badams** [almasaeed2010/AdminLTE#1098]
The 2.3.4 / 2.3.5 releases have broken BC in some places, causing issues in downstream packages like my own https://github.com/webtoolsnz/yii2-admin-lte

Following SemVer would have mitigated this issue and any others that haven't been noticed yet.

Please consider switching to this versioning scheme.

**Comment by almasaeed2010** [comment]
Could you please let us know what became broken so that we create backwards compatibility?

Thank!

**Comment by badams** [comment]
I'm not aware of all breaking changes, but 2.3.4 includes a big set of changes, so its likely there are more and under [SemVer](http://semver.org/) that would mean a Major version number increase (eg 3.0.0). I believe that this project would benefit greatly from switch to that versioning scheme as package managers like composer & npm somewhat rely on it.

Anyway the issue that I ran into is the markup of the sidebar navigation has changed slightly to accommodate support for multiple labels (which is great), but the CSS selectors no longer support the old markup.

https://github.com/almasaeed2010/AdminLTE/pull/1006

This means that when expanding a treeview-menu the chevron icon no longer rotates.

**Comment by rokasmi** [comment]
Chevron icon is not the only problem with navbar.
Using firefox, the whole navbar is unaligned and broken (attaching screenshot).
Chrome view: [http://imgur.com/gCMnWZj](http://imgur.com/gCMnWZj)
Firefox view: [http://imgur.com/UPTsMqu](http://imgur.com/UPTsMqu)

The problems appears with 2.3.4 version and later. Using 2.3.3 everything looks fine.

**Comment by jgoclawski** [comment]
We've also just run into issues when updating a PATCH level version of AdminLTE from 2.3.2 to 2.3.5. It turns out that all our date and time pickers stopped working. 
When investigating further, we've found that in 2.3.4 there was a huge bump of `daterangepicker` from 1.3.21 to 2.1.19. Which obviously changed a lot.
What's even worse, is that there's no clear notice of such huge upgrade in the changelog, only "Update Date Range Picker" :(

Please use semantic versioning and make clear notice of major dependency bumps.

**Comment by almasaeed2010** [comment]
Thank you for pointing that out. We obviously missed a few things. We will review the details and update accordingly.

**Comment by badams** [comment]
@almasaeed2010 Thanks for fixing these CSS issues! 

I really love the AdminLTE theme, but your patch, and subsequent release don't address the real issue here; it should be 3.0.0. 

As @jgoclawski pointed out; there have been major version increases on a lot of dependencies, so there's no way to guarantee BC. The easiest option is to increment the version number so downstream users that depend on this package know that.

**Comment by rokasmi** [comment]
Thanks for fixes! :+1:  :)
Btw, chevron icon in menu still doesnt rotate...

**Comment by arysom** [comment]
I have fa fa-angle-left pull-right and it rotates, maybe chevron doesnt :)

**Comment by rokasmi** [comment]
Ooops, my mistake, forgot to rebuild :laughing: 
everything is fine

**Comment by almasaeed2010** [comment]
Hello @badams,

I understand that we made a major mistake upgrading dependencies without paying attention to their version information and we will make sure that future releases put this into consideration. In fact, we are working on version 2.4.0 which will use Bower to manage dependencies and, at the same time, keep the plugins folder for BC. We will discuss this further in a different post when 2.4.0 Alpha gets released.

Thank you for your patience and continuous contributions!

**Comment by arysom** [comment]
Update to 2.3.6 and my fa fa-angle-left also stopped rotating, in 2.3.5 it's ok.
