### ISSUE TITLE
Blank vertical scroll using datatables

### ISSUE THREAD

**Issue by manuelcassianic** [almasaeed2010/AdminLTE#1099]
Hi
I have a problem using a datatables
im getting a blank space below table proportional to the number of records that have the table
![image](https://cloud.githubusercontent.com/assets/20286668/16567307/a532fa8a-41e2-11e6-861d-785d4563e3d3.png)

**Comment by almasaeed2010** [comment]
Hello @manuelcassianic 

You should verify that your HTML is correct. Also make sure that you have included all the necessary files (JS and CSS) that datatables needs to work.

Thanks!

**Comment by manuelcassianic** [comment]
this is my html code 

`<html>
  <head>
    <meta charset="UTF-8">
    <title>Mail | Admin</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    
    <link href="plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
    
    <link href="dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    
    <link href="dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />

    
    
    
  </head>
  <body class="skin-blue">
    <div class="wrapper">
      
      <header class="main-header">
        
        <a href="index2.php" class="logo"><b>Mail</b>Admin</a>
        
        <nav class="navbar navbar-static-top" role="navigation">
          
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              
              
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="images/<?php echo $_SESSION['imagen']?>" class="user-image" alt="User Image"/>
                  <span class="hidden-xs"><?php echo $_SESSION['nombre']?></span>
                </a>
                <ul class="dropdown-menu">
                  
                  <li class="user-header">
                    <img src="images/<?php echo $_SESSION['imagen']?>" class="img-circle" alt="User Image" />
                    <p>
                      <?php echo $_SESSION['nombre']?>
                    </p>
                  </li>
                  
                  <li class="user-footer">
                    <div class="pull-right">
                      <a href="procesos_usuario.php?proceso=2" class="btn btn-default btn-flat">Cerrar sesión</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      
      <aside class="main-sidebar">
        
        <section class="sidebar">
          
          <div class="user-panel">
            <div class="pull-left image">
              <img src="images/<?php echo $_SESSION['imagen']?>" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
              <p><?php echo $_SESSION['nombre']?></p>
              
            </div>
          </div>
          
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Buscar..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          
          
          <ul class="sidebar-menu">
            <li class="header">MENU</li>
            <li class="treeview">
              <a href="index2.php">
                <i class="fa fa-dashboard"></i> <span>Panel de control</span>
              </a>
            </li>
			<?php $cuenta_clave = array_search($_SESSION['id'], $cuenta_id);?>
            <li class="active treeview">
              <a href="#">
                <i class="fa fa-suitcase"></i>
                <span>Cuentas</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              <?php if($_SESSION['tipo']==2 || $_SESSION['tipo']==4){?>
              	<?php if(in_array($_SESSION['id'], $cuenta_id)){?><li><a href="index2.php"><i class="fa fa-bed"></i> <?php echo $cuenta_nombre[$cuenta_clave]?></a></li><li><a href="encuestas.php?h1=<?php echo $cuenta_id[$cuenta_clave]?>&h2=<?php echo $cuenta_id[$cuenta_clave]?>"><i class="fa fa-pie-chart"></i> Encuestas</a></li><?php } ?>
                <?php if($_SESSION['id']==14){?><li><a href="contactos.php?id=14"><i class="fa fa-book"></i> Contactos</a></li><?php } ?>
              <?php }else{
				for($c=0;$c<count($cuenta_id);$c++){  
			  ?> 	         
              <li class="treeview">
                  <a href="#">
                    <i class="fa fa-bed"></i>
                    <span><?php echo $cuenta_nombre[$c]?></span>
                    <i class="fa fa-angle-left pull-right"></i>
                  </a>
                  <ul class="treeview-menu">
                    <li><a href="hoteles.php?id=<?php echo $cuenta_id[$c]?>"><i class="fa fa-bed"></i> Suscriptores</a></li>
                    <li><a href="encuestas.php?h1=<?php echo $cuenta_id[$c]?>&h2=<?php echo $cuenta_id[$c]?>"><i class="fa fa-pie-chart"></i> Encuestas</a></li>
                  </ul>
                </li>
                
				<?php } ?>
			  <?php }?>
              </ul>
            </li>
            <?php if($_SESSION['tipo']==1  || $_SESSION['tipo']==3){?>
            <li class="active treeview">
              <a href="enviar_mails.php">
                <i class="fa fa-envelope"></i> <span>Enviar Mails</span>
              </a>
            </li>
			<li class="treeview">
              <a href="campanas.php">
                <i class="fa fa-send"></i> <span>Campañas</span>
              </a>
            </li>
			<li class="treeview">
              <a href="listas.php">
                <i class="fa fa-list-ol"></i> <span>Listas</span>
              </a>
            </li>
			<li class="treeview">
              <a href="agregar_suscriptores.php">
                <i class="fa fa-user"></i> <span>+ Suscriptores</span>
              </a>
            </li>
			<li class="treeview">
              <a href="tutoriales.php">
                <i class="fa fa-youtube-play"></i> <span>Tutoriales</span>
              </a>
            </li>
            <?php }?>
          </ul>
        </section>
        
      </aside>

      
      <div class="content-wrapper">
        
        <section class="content-header">
          <h1>
            Suscriptores
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Hoteles</a></li>
            <li class="active"><?php echo $nombre_hotel?></li>
          </ol>
        </section>
		
        
        <section class="content">
          <div class="row">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title"><?php echo $nombre_hotel?></h3>
                </div>
                <div class="box-body">
                  <table id="example" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Trat.</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <?php if($tipo_hotel == 2){?>
                        	<th>Checkout</th>
                        <?php }?>
                        <?php if($tipo_hotel == 3){?>
                        	<th>Fecha cierre Evento</th>
                        <?php }?>
                        <th>Email</th>
                        <th>Cumpleaños</th>
                        <th>Idioma</th>
                        <th>Fecha suscripcion</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					  if ($row = mysql_fetch_array($suscriptores)){ 
						   do{
							  $salida = explode('-', $row["salida"]); 
							  $fecha_suscripcion = explode('-', $row["fecha_registro"]);?>	 
                      <tr>
                        <td><h5><?php echo $row["tratamiento"]?></h5></td>
                        <td><h5><?php echo $row["nombres"]?></h5></td>
                        <td><h5><?php echo $row["apellidos"]?></h5></td>
                        <td><h5><?php echo $salida[2].'/'.$salida[1].'/'.$salida[0]?></h5></td>
                        <td><h5><?php echo $row["email"]?></h5></td>
                        <td><h5><?php echo $row["dia"].'/'.$row["mes"]?></h5></td>
                        <td><h5><?php echo idioma($row["idioma"])?></h5></td>
                        <td><h5><?php echo $fecha_suscripcion[2].'/'.$fecha_suscripcion[1].'/'.$fecha_suscripcion[0]?></h5></td>
                      </tr>
                      <?php }while ($row = mysql_fetch_array($suscriptores));} ?>
                    </tbody>
                  </table>
                </div>
              </div>
          </div>
          <?php if($_SESSION['tipo']==1){ ?>
		  <div class="row">
          <div class="col-md-2">
          <a href="#" class="btn btn-primary btn-block btn-flat" onClick="$('#example').tableExport({type:'excel',escape:'false'});">Descargar</a>
          </div></div>
		  <?php } ?>
        </section>
      </div>
       <footer class="main-footer">
        <div class="pull-right hidden-xs">
        </div>
        <strong>Copyright &copy; 2015-2016 <a href="http://www.aguacateweb.com">Aguacateweb</a>.</strong> All rights reserved.
      </footer>
    </div>

    
    <script src="plugins/jQuery/jQuery-2.1.3.min.js"></script>
    
    <script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    
    <script src="plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
    <script src="plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript" src="vortex/tableExport.js"></script>
	<script type="text/javascript" src="vortex/jquery.base64.js"></script>
    
    <script src="plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    
    <script src="plugins/fastclick/fastclick.min.js"></script>
    
    <script src="dist/js/app.min.js" type="text/javascript"></script>
    
    
    <script type="text/javascript">
      $(function () {
        $("#example").dataTable();
      });
    </script>

  </body>
</html>

<?php 
function idioma($idioma){
	switch ($idioma) {
    	case 1: return "Español"; break;
    	case 2: return "Ingles"; break;
		case 3: return "Frances"; break;
		case 4: return "Italiano"; break;
		case 5: return "Aleman"; break;
	}
}
?>
`

**Comment by manuelcassianic** [comment]
All necessary files are included

**Comment by lenamtl** [comment]
what are your datables settings?

**Comment by manuelcassianic** [comment]
<table id="example" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Trat.</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Fecha cierre Evento</th>
                        <th>Email</th>
                        <th>Cumpleaños</th>
                        <th>Idioma</th>
                        <th>Fecha suscripcion</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
					  if ($row = mysql_fetch_array($suscriptores)){ 
						   do{
							  $salida = explode('-', $row["salida"]); 
							  $fecha_suscripcion = explode('-', $row["fecha_registro"]);?>	 
                      <tr>
                        <td><h5><?php echo $row["tratamiento"]?></h5></td>
                        <td><h5><?php echo $row["nombres"]?></h5></td>
                        <td><h5><?php echo $row["apellidos"]?></h5></td>
                        <td><h5><?php echo $salida[2].'/'.$salida[1].'/'.$salida[0]?></h5></td>
                        <td><h5><?php echo $row["email"]?></h5></td>
                        <td><h5><?php echo $row["dia"].'/'.$row["mes"]?></h5></td>
                        <td><h5><?php echo idioma($row["idioma"])?></h5></td>
                        <td><h5><?php echo $fecha_suscripcion[2].'/'.$fecha_suscripcion[1].'/'.$fecha_suscripcion[0]?></h5></td>
                      </tr>
                      <?php }while ($row = mysql_fetch_array($suscriptores));} ?>
                    </tbody>
                  </table>



<script type="text/javascript">
      $(function () {
        $("#example").dataTable();
      });
    </script>
