### ISSUE TITLE
Request: Markdown Editor

### ISSUE THREAD

**Issue by AlexBaker-** [almasaeed2010/AdminLTE#1100]
I tried my best with both [Bootstrap Markdown](http://www.codingdrama.com/bootstrap-markdown/) and the [Inacho Bootstrap Markdown Editor](https://github.com/inacho/bootstrap-markdown-editor), but could get neither to work.  They render the markdown editor UI ok, but it's extremely buggy and the Markdown preview (e.g. using [marked](https://github.com/chjj/marked)) doesn't render.

Any suggestions?

Thanks!

**Comment by almasaeed2010** [comment]
Hello,

Sorry for the delay. I think this question would yield more results on a developers forum instead of here. But, I used [SimpleMDE](https://simplemde.com/) several times. You might want to try it.

Thanks!

**Comment by AlexBaker-** [comment]
I tried with SimpleMDE per your suggestion, but I'm having similar issues as well.  I'm not exactly a frontend developer, so I'm not really sure what developers forum to ask on.

If possible, can I request a Markdown editor be included in an upcoming version, please?  Thanks for the help.
