### ISSUE TITLE
Collapse Menu Save State

### ISSUE THREAD

**Issue by adyoi** [almasaeed2010/AdminLTE#1102]
Even I found issues of **Collapse Menu Save State** i found this sollution of my code

```
		<script type="text/javascript">
		if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
			$("body").removeClass('sidebar-collapse');
			sessionStorage.setItem("sidebar-toggle-collapsed", "1");
		}else{
			$("body").addClass('sidebar-collapse');
			sessionStorage.setItem("sidebar-toggle-collapsed", "");
		}

		$('.sidebar-toggle').click(function() {
			event.preventDefault();
			if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
				sessionStorage.setItem("sidebar-toggle-collapsed", "");
			}else{
				sessionStorage.setItem("sidebar-toggle-collapsed", "1");
			}
		});
		</script>
```

My question what is  sessionStorage as support most browser. thanks.

**Comment by almasaeed2010** [comment]
As discussed multiple times, this solution causes an issue in loading on IE10|11 where the sidebar would show on load and hide immediately. The best solution to this is to implement a server side state mechanism to store the current status of the sidebar.

Thanks!
