### ISSUE TITLE
cat I use it with angularjs?

### ISSUE THREAD

**Issue by lanegg** [almasaeed2010/AdminLTE#1110]
bootstrap is dependency jquery, but I want to use angularjs to instead jquery?

help me ~~~~

**Comment by Tjoosten** [comment]
Have u searched on google?

**Comment by foday** [comment]
Also check out www.Udemy.com they might have a free course video on what you are looking for.
Let me know how it works out for you.

**Comment by albertozizzi** [comment]
Yes you can, i've made some directives for page routing and stuff liek that, i use it with angular since 1 year !

**Comment by DiomedesDominguez** [comment]
As @albertozizzi says, you can used. Right now there is a minor bug in the footer if you are planning to use jquery's latest version
