### ISSUE TITLE
Update Chart JS to the 2.0 version

### ISSUE THREAD

**Issue by jcornide** [almasaeed2010/AdminLTE#1112]
It would be great to have the ChartJS 2.0 available instead of 1.1, there are a lot of new features on the 2.0 version
https://github.com/chartjs/Chart.js/releases/tag/v2.0.0

**Comment by devinmatte** [comment]
Are there any plans to make this transition?

**Comment by almasaeed2010** [comment]
Done in V3-alpha.

Thanks!
