### ISSUE TITLE
How do I change the theme?

### ISSUE THREAD

**Issue by fcpauldiaz** [almasaeed2010/AdminLTE#1122]
I tried to to change the css to skin-green.min.css but the page went white. How do I properly change theme?

**Comment by Tjoosten** [comment]
include the base css with the theming css file.

**Comment by fcpauldiaz** [comment]
Do you mean this one AdminLTE.min.css? It is already included.

**Comment by Tjoosten** [comment]
hmm strange. Is there nothing in the docs...

**Comment by fcpauldiaz** [comment]
I forgot I had to change the class.
