### ISSUE TITLE
TypeError: $(...).tooltip is not a function

### ISSUE THREAD

**Issue by xralphack** [almasaeed2010/AdminLTE#1128]
I didn't not use tooltip, but error appeared.

jQuery.Deferred exception: $(...).tooltip is not a function
TypeError: $(...).tooltip is not a function

**Comment by almasaeed2010** [comment]
Did you make sure to add ```bootstrap.min.js``` before ```app.js```?

Also, verify you have ```jquery.min.js``` loaded before ```bootstrap.min.js```

**Comment by xralphack** [comment]
thanks a lot, I did not import bootstrap.min.js
