### ISSUE TITLE
AdminLTE integration with Yii2 framework (Dropdown doesn't work)

### ISSUE THREAD

**Issue by kaissbouali** [almasaeed2010/AdminLTE#1129]
Hello,
I was following a very nice tutorial of the Yii2 framework and a couple of those videos talk about its integration to AdminLTE (or integrating AdminLTE to Yii to be more specific). I followed his steps point by point but when I click on the header bar (notifications or messages or the profile) the dropdown menu doesn't work. It shows the click on that area but nothing comes down. I did exactly the same thing as the guy in the tutorials and I used exactly the same .js and .css files and nothing seems to work.

I've attached 3 pictures:

- html-version.png : when I open the adminLTE folder that I downloaded: **works fine**
![html-version](https://cloud.githubusercontent.com/assets/20075828/17030176/3fbc75be-4f66-11e6-9469-d5ce0b11b72c.png)

- before.png: when I integrated AdminLTE into my Yii2 framework: **before I click**
![before](https://cloud.githubusercontent.com/assets/20075828/17030183/48ec1644-4f66-11e6-8429-f7e0e7afe677.png)

- after.png: when I integrated AdminLTE into my Yii2 framework: **after I click**
![after](https://cloud.githubusercontent.com/assets/20075828/17030188/4d3f86cc-4f66-11e6-93de-71b1e8f39612.png)
_notice the darker blue on the profile icon in the header (top right)_

Here is the tutorial: https://www.youtube.com/watch?v=OnauNk0eeOM&index=37&list=PLRd0zhQj3CBmusDbBzFgg3H20VxLx2mkF

Please help me. Thank you in advance.

**Comment by victorhwtan** [comment]
The only thing that could explain why the dropdown is not working for you because you do not include the js script properly.

**Comment by kaissbouali** [comment]
I have included all js files of AdminLTE. But anyways I fixed the  
problem. Instead of integrating it manually, I used composer and a  
bundle made by someone else on GitHub that integrates AdminLTE to Yii2  
directly using composer on linux terminal. It was a great method, I  
recommend.

Best,

Quoting victorhwtan <notifications@github.com>:
