### ISSUE TITLE
Template Preview Outdated

### ISSUE THREAD

**Issue by AlexBaker-** [almasaeed2010/AdminLTE#1137]
The [template preview](https://almsaeedstudio.com/preview) is out of date and running 2.3.3, while the latest version has been 2.3.5 for nearly a month.

**Comment by mhulse** [comment]
Is `index2.html` that is recommended if you want to have all the examples?

https://github.com/almasaeed2010/AdminLTE/blob/e499f26f76c39028321292b4be824cdd68d00265/index2.html

How can you tell if it's outdated?

**Comment by REJack** [comment]
If you check the CSS file https://almsaeedstudio.com/themes/AdminLTE/dist/css/AdminLTE.min.css
thats v2.3.7 but latest is v2.3.8

**Comment by mhulse** [comment]
> If you check the CSS file https://almsaeedstudio.com/themes/AdminLTE/dist/css/AdminLTE.min.css
> thats v2.3.7 but latest is v2.3.8

Ah, thank you!
