### ISSUE TITLE
Sidebar links don't show as active after clicking link [Laravel 5.2]

### ISSUE THREAD

**Issue by nwmille** [almasaeed2010/AdminLTE#1150]
Currently working with a Laravel 5.2 application. The only issue I have is that the links on the sidebar will not show as "active" after having been clicked and the page loaded. 

I downloaded the tutorial, https://almsaeedstudio.com/blog/integrate-adminlte-with-laravel, and added the files to my project. I made sure all files were being loaded in without errors. The only thing I changed was the href="#" to a href with a named route like href"/users/show" on the sidebar links. The page loads as expected and looks good but the link will not show as "active" on the sidebar.

**Comment by tannakartikey** [comment]
Hi @nwmille 

You need to set it the `class=active` when your route is /users/show as shown below:

`<li class="treeview {{ (Request::is('*users*show*')) ? 'active':'' }}">`

It will keep the menu highlighted when you are on that route. 

You can find some more info on [this link](https://laracasts.com/discuss/channels/general-discussion/requestis-active-links-woes).

**Comment by nwmille** [comment]
Nice, that appears to work for a single `<li>` but treeview is usually a drop down list of several `<li>` elements. In that case I need to make both the main `<li class="treeview">` active, as well as the `<li>` that is under that. Like this....


`<li class="treeview active">`  <--- Need to make this active when I  have a `<li>` in the dropdown active
`        <a href="#"><span>Multilevel</span> <i class=" pull-right"></i></a>`
`        <ul class="treeview-menu">`
`          <li class="active"><a href="#">Link in level 1</a></li>`
`          <li><a href="#">Link in level 2</a></li>`
`        </ul>`
`</li>`

**Comment by tannakartikey** [comment]
You have to use the same logic twice. For menu in Level1 and Level2 also.

```
<li class="treeview {{ (Request::is('*level1*link*')) ? 'active' : '' }} {{ (Request::is('*level2*link*')) ? 'active' : '' }}" >
<a href="#"><span>Multilevel</span> <i class=" pull-right"></i></a>
<ul class="treeview-menu">
<li class="{{ ( Request::is('*level1*link*') ? 'active' : '' ) }}"><a href="#">Link in level 1</a></li>
<li class="{{ ( Request::is('*level2*link*') ? 'active' : '' ) }}"><a href="#">Link in level 2</a></li>
</ul>
</li>
```
But sometimes wildcard may highlight multiple things. 

e.g. Level1 link is: myapp.com/admin/users
Level2 link is: mysqpp.com/admin/users/create

So if you use wildcards, menu in Level1 will be always highlighted. Below is the solution:

```
<li class="treeview {{ (Request::is('*admin*users*')) ? 'active':'' }}">
						<a href="#"><i class="fa fa-fw fa-users"></i> <span>Users &nbsp;<span class="icon tip" title="Manage Site Users ( Trainers and Trainee )">
							<i class="glyphicon glyphicon-question-sign"></i>
						</span></span> <i class="fa fa-angle-left pull-right"></i></a>
						<ul class="treeview-menu">
							<li  class="{{ (Request::is('*admin/users')) ? 'active' : '' }}">
							<a href="{{ route('users') }}">Manage Users &nbsp;<span class="icon tip" title="Manage Site Users ( Trainer or Trainee ) - Create,Edit,Active/Inactive or View User Profile and Wallet">
								<i class="glyphicon glyphicon-question-sign"></i>
							</span></a></li>
							<li  class="{{ (Request::is('*users*create*')) ? 'active' : ''}}">
							<a href="{{ route('create/user') }}">Add User &nbsp;<span class="icon tip" title="Create new User">
								<i class="glyphicon glyphicon-question-sign"></i>
							</span></a></li>
						</ul>
					</li>
```


Please go through the following code. It will help you understand:
```
<li class="treeview {{ (Request::is('*admin*cancellation-slabs*')) ? 'active':'' }} {{ (Request::is('*admin*activities*')) ? 'active':'' }} {{ (Request::is('*admin*badge*')) ? 'active' : '' }}">
						<a href="#">
							<i class="fa fa-cogs"></i> <span>Management &nbsp;<span class="icon tip" title="Manage Cencellation Slabs and Activity Loogs">
								<i class="glyphicon glyphicon-question-sign"></i>
							</span></span>
							<i class="fa fa-angle-left pull-right"></i>
						</a>
						<ul class="treeview-menu">
							<li class="{{ (Request::is('*admin*badge*')) ? 'active':'' }}">
								<a href="{{ route('admin.badge.index') }}">
									<i class="fa fa-certificate"></i> Badges &nbsp;<span class="icon tip" title="Manage Badges for Tranier">
										<i class="glyphicon glyphicon-question-sign"></i>
									</span>
								</a>
							</li>
							<li class="{{ (Request::is('*admin*cancellation-slabs*')) ? 'active':'' }}">
								<a href="{{ route('admin.cancellation-slabs.index') }}">
									<i class="fa fa-close"></i> Penalties Trainers &nbsp;<span class="icon tip" title="Manage Training Cancellation Slabs">
										<i class="glyphicon glyphicon-question-sign"></i>
									</span>
								</a>
							</li>
							<li class="{{ (Request::is('*admin*activities*')) ? 'active':'' }}">
								<a href="{{ route('admin.activities.index') }}">
									<i class="fa fa-eye"></i> Activities &nbsp;<span class="icon tip" title="View All the Activity Logs">
										<i class="glyphicon glyphicon-question-sign"></i>
									</span>
								</a>
							</li>
						</ul>
					</li>
```
