### ISSUE TITLE
The ability to minimize all or certian boxes based off screen size (ie. mobile devices)

### ISSUE THREAD

**Issue by nexus9988** [almasaeed2010/AdminLTE#1155]
This isn't so much of an issue rather a feature request. On mobile, pages with lots of boxes tend to get really cramped when they're all open so I created an on load script that will verify the pages size and minimize all boxes.

Just add the class ".mobile-load-collapse" to where your ".box" class is

> ```
>  $(window).on("load",function(e){
>       if ($(document).width() < 767 ) {
>           if (!$('.mobile-load-collapse').hasClass('collapsed-box')){
>               $('.mobile-load-collapse').addClass('collapsed-box');
>               $('.mobile-load-collapse > .box-body').css('display','none');
>               $('.mobile-load-collapse > .box-header .fa.fa-minus').removeClass('fa-minus').addClass('fa-plus');
>           }
>       }
>   });
> ```

This can also be modified to for tablets and desktop sizes.
Tested on safari and chrome for iphone

**Comment by lenamtl** [comment]
This can be a good idea to keep the first one opened....

**Comment by almasaeed2010** [comment]
I feel like this can be implemented via CSS to keep the implementation responsive the same way the rest of theme is. If you submit a PR for v3 that uses css (sass) to implement this we will accept it.

Thanks and sorry for the years of inactivity!
