### ISSUE TITLE
lastchild hover should have border-radius

### ISSUE THREAD

**Issue by harrytang** [almasaeed2010/AdminLTE#1157]
![adminlte](https://cloud.githubusercontent.com/assets/792413/17544959/84ebcd4e-5f04-11e6-9ab0-9dfbb2ec60a5.jpg)

**Comment by marhyorh** [comment]
It is surrounded by a box and .box has a border radius of 3px. Check your styles..

**Comment by FlickTheManual** [comment]
Not sure that he says.
But I think you should make up the px on :hover li in the list-inline for
having the bordered box, like the no hover style...

like

.box ul.gnagnagna-style li::last-child, .box ul.gnagnagna-style
li:last-child:hover{
 border-radius: your supa dupa pixel size;
}

or else

best regards

*Matthieu GURAK*
tel: 06 92 491 170
@: matthieu.gurak@gmail.com

2016-08-21 18:24 GMT+04:00 Adegbuyi Ademola <notifications@github.com>:

**Comment by FlickTheManual** [comment]
Not sure that he says. But I think you should make up the px on :hover li
in the list-inline for having the bordered box, like the no hover style...
like .box ul.gnagnagna-style li::last-child, .box ul.gnagnagna-style
li:last-child:hover{ border-radius: your supa dupa pixel size; }

or else

wich this help you

best regards
