### ISSUE TITLE
AdminLTE 2.3.6 treeview menu problem

### ISSUE THREAD

**Issue by aocneanu** [almasaeed2010/AdminLTE#1158]
This is how it looks on https://almsaeedstudio.com/preview

![screen shot 2016-08-10 at 12 02 39](https://cloud.githubusercontent.com/assets/16073274/17547999/7fa4d946-5ef2-11e6-8658-f4e368170bcc.png)

This is how it looks after I download 2.3.6 locally

![screen shot 2016-08-10 at 12 02 22](https://cloud.githubusercontent.com/assets/16073274/17548011/907b9c5a-5ef2-11e6-90ed-c8a28d5810cc.png)

**Comment by antoniocambados** [comment]
This bug was introduced in https://github.com/almasaeed2010/AdminLTE/commit/1bffa9fd44ed1478f83c9425660195cdd01e0ec0.

I've just left a comment there. I think it's just a missing comma... at least that's how I solved it in a recent project.

**Comment by wandersonwhcr** [comment]
+1

**Comment by adriangrantdotorg** [comment]
Tried adding the comma to the end of line 124 as @antoniocambados  [recommended here](https://github.com/almasaeed2010/AdminLTE/pull/1160/files) but the problem still occurs.

**Comment by antoniocambados** [comment]
:confused: Well that's strange... Based on the feedback, this seems to have worked for 3 other users so far. Be aware that I didn't submit any compiled distribution-ready CSS changes. ¿Could that be your issue?

**Comment by adriangrantdotorg** [comment]
Whoops you're right, it's working now. 

--
Mobile: 917 342 2353
Linkedin: https://www.linkedin.com/in/adriangrant3
Twitter: https://twitter.com/adriangrant




On Thu, Aug 25, 2016 at 2:18 AM -0400, "Antonio Cambados" <notifications@github.com> wrote:












😕 Well that's strange... Based on the feedback, this seems to have worked for 3 other users so far. Be aware that I didn't submit any compiled distribution-ready CSS changes. ¿Could that be your issue?
