### ISSUE TITLE
How to change the sidebar color?

### ISSUE THREAD

**Issue by nilotpalkalita** [almasaeed2010/AdminLTE#1164]
I want to change to different color than that of the given skins. When i try to change the colour fro the applied skin css file, it doesn't change?

**Comment by marhyorh** [comment]
It will change if you add `!important` like: `.main-sidebar { background-color: #333 !important }`.

**Comment by nilotpalkalita** [comment]
Thank you. It worked.

**Comment by desad1212** [comment]
Hello

I also want to do the same.
What is the file that is modified?

**Comment by ooade** [comment]
@desad1212 You don't have to modify the file directly, just include `.main-sidebar { background-color: $your-color !important }` anywhere. And you can as well change the file, search for main-sidebar within those stylesheets

**Comment by threear15** [comment]
i want to change the color of the header. tell me how to do that

**Comment by Senninseyi** [comment]
@threear15  header or navbar

**Comment by mnszaidi** [comment]
Hi i want to remove some options from { layout Options } Side bar i want yo remove Fixed layout, Boxed Layout, Toggle left Sidebar, Sidebar Expand on Hover, Toggle Right Sidebar Skin, plz tell me which file to delete these options

**Comment by malFuckingFurion** [comment]
You need to edit demo.js file.

**Comment by gopalakrishnanmadhesan** [comment]
how to change background color while expanding the of menu. It looks like animation

**Comment by nagpals** [comment]
> how to change background color while expanding the of menu. It looks like animation

You can change the style class of body to change colors. e.g : 

`<body class="sidebar-mini skin-green" data-gr-c-s-loaded="true" style="height: auto; min-height: 100%;">`

`<body class="sidebar-mini skin-green-light" data-gr-c-s-loaded="true" style="height: auto; min-height: 100%;">`

and so on.
