### ISSUE TITLE
Fieldset enable/disable with radio button

### ISSUE THREAD

**Issue by caiohab** [almasaeed2010/AdminLTE#1168]
Enable want to hum entry field activated by a radio button. Exemple
http://www.bootply.com/120507
I can not implement the AdminLTE , why ?

**Comment by caiohab** [comment]
What I discovered the problem and with a class radio button 
`"class="minimal-red""`
Does anyone know how to solve?

**Comment by almasaeed2010** [comment]
Please review the iCheck plugin documentation: http://icheck.fronteed.com/

Thanks!
