### ISSUE TITLE
Support with charts usage

### ISSUE THREAD

**Issue by Sermed92** [almasaeed2010/AdminLTE#1169]
Hi, i'm not pretty sure if this is the right place to post this issue.
For beginning, thanks for this awesome template, you rock :+1: 

I'm customizing AdminLTE to personal porpuse, but i'll need to use some charts and i don't get very well how to use it. I review the chart's examples in the left bar and tried to use the charts in the various same ways you provide us, but i don't get lucky here... Don't understand very well its usage
Thank you very much :)

**Comment by almasaeed2010** [comment]
Hello,

First of all, thanks for the compliments and sorry for the delayed response. 

To get started with any of the charts, you may want to review their full documentation. ChartJS, for example, provides its own documentation here: http://www.chartjs.org/

Other charts also have their own documentation. You can find documentation for all of the plugins that AdminLTE uses here: https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#plugins

Thanks!

**Comment by stevekama** [comment]
Hi, 

I've been using adminLte for different projects. Can i transform it to desktop based application using electron and still maintain functionalities?
