### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by radaniba** [almasaeed2010/AdminLTE#117]
Hi,

Just wanted to let you know that the layout is broken in your git repo, something is wrong in the code when you clone and open index.html you'll figure out this 

(it is supposed to open like the demo but it is not)

**Comment by citrusfizz** [comment]
the issue is that the file it is trying to load is jQuery-2.1.4.min.js
however the file in the plugins/jQuery  is jquery-2.1.4.min.js
notice the uppercase Q
it seems like this would either need a case insensitive Apache module.  or simply rename the file with the uppercase Q
