### ISSUE TITLE
bug when using `data-tagert="collapse"` in box header

### ISSUE THREAD

**Issue by CallMeXYZ** [almasaeed2010/AdminLTE#1171]
``` javascript
        <div class="box box-solid">
            <div class="box-header with-border" data-widget="collapse">
              <h3 class="box-title">Title</h3>
            </div>
            <div class="box-body">
              Start creating your amazing application!
            </div><!-- /.box-body -->
            <div class="box-footer">
              Footer
            </div><!-- /.box-footer-->
          </div>
```

when the box header is clicked the box got collapsed, but the box header got a new class named `fa-plus`  or `fa-minus` which showed as a blank rectangular before the box title.

**Comment by almasaeed2010** [comment]
The ```data-widget``` attribute must be used with font awesome's ```fa-plus``` or ```fa-minus```.  Unfortunately, we currently don't provide support for other implementations. However, you may want to check the accordion component  found here: https://almsaeedstudio.com/themes/AdminLTE/pages/UI/general.html

Thanks
