### ISSUE TITLE
With Bootstrap v3.3.7 this theme hase some view bugs

### ISSUE THREAD

**Issue by DariusJu** [almasaeed2010/AdminLTE#1173]
navbar has 2px more height and it differs from logo height so it broke the navbar line. And also all menu items and everything that uses fontawesome changes height.

to fix this, need change  .main-header .sidebar-toggle css

from this:
`padding: 15px 15px;`

to this:
`padding: 14px 15px;`

**Comment by almasaeed2010** [comment]
The newest release of AdminLTE (v2.3.8) uses Bootstrap 3.3.7. There are no discrepancies on our end. If the issue persists, please let us know. Thanks for reporting!

**Comment by ashleyhood** [comment]
This is still an issue.  I'm not sure why you are not seeing this as I am using Bootstrap v3.3.7 and AdminLTE v2.3.11 and it is showing in both Firefox and Chrome. 

To solve this I changed the .logo `height` to `min-height` in `header.less` file.
