### ISSUE TITLE
Left side BAR and Top Side Bar 

### ISSUE THREAD

**Issue by posillipo** [almasaeed2010/AdminLTE#1179]
good morning to all, 
I need to start the portal with the invisible sidebars Left and Top, is it possibile?
tanks very mutch

**Comment by zburk** [comment]
For the left sidebar, add the class `sidebar-collapse` to your body tag and you'll get an appearance as below and click the toggle at the top to make it reappear. Not sure about the top sidebar though
<img width="1037" alt="screen shot 2016-09-08 at 11 43 19 am" src="https://cloud.githubusercontent.com/assets/5782327/18356117/7437ed2c-75b9-11e6-87f1-14cf32aa9081.png">
