### ISSUE TITLE
bg- disabled not working on some element

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#1180]
Hi,

I can use bg-orange with well 
well well-sm bg-orange 
but I can use bg-orange **disabled**

Maybe disabled color class should be renamed 

Any clue?

**Comment by zburk** [comment]
Make sure you add the `btn` class to it. As shown below:
`<button class="btn well well-sm bg-orange disabled">Test</button>`
I did it first without the `btn` class the `disabled` class did not work and adding `btn` to it worked.

**Comment by lenamtl** [comment]
In my case I'm using Bootstrap **well** element, so I don't want to use btn class for this.
I guess the color pallet was more for button than other Bootstrap elements.
I have created new class for the disabled color with specific color and I'm not using disabled attribute.

This may be a suggestion for future update.

**Comment by zburk** [comment]
So in what case would you need a well disabled?

**Comment by lenamtl** [comment]
Oh, it was just for a  background color of a well.
It is ok to use the disabled attribute on button, but not really for other element.
But we may like to use the lighter color for other background element.

**Comment by zburk** [comment]
If you're trying to set the color of a well, doing it through CSS would be your better option than adding a disabled class since the class will also affect the colors of everything inside the well and not just the background.

**Comment by lenamtl** [comment]
This what I have done.
My suggestion is this will be nice to have a complete pallet color that we can reuse in other element without using attribute like disabled.

**Comment by zburk** [comment]
Maybe rather than having a complete pallet color, there could be `.light` and `.dark` which would adjust the opacities or overlay a white or black over it? Not sure how this can be proposed as a new feature.

That way it would allow for more colors on the palette without needing to add 10+ more color classes.

**Comment by lenamtl** [comment]
Sound good to me
