### ISSUE TITLE
[Help] Set the search box in top navbar

### ISSUE THREAD

**Issue by jigsshah** [almasaeed2010/AdminLTE#1181]
Hello guys,

I am new to this work and I want to set up the search box in top bar with sidebar so i want both a search box in top bar and sidebar for navigation. So please can any one help me out with this and i want the site to responsive too. 

Thanks and Regards
Jigar

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE uses Bootstrap, which provides a method to add a search box in the navbar. Please refer to the documentation for more details: http://getbootstrap.com/components/#navbar

Thanks!
