### ISSUE TITLE
Problem and suggestion about icheck

### ISSUE THREAD

**Issue by bantikyan** [almasaeed2010/AdminLTE#1183]
Hello, I use this great template, but icheck plugin is problematic. So I wrote pure css bootstrap checkboxes   to use in my project, later I have published it, and can suggest you to consider it for checkboxes  and radios. You can check it out at: [icheck-bootstrap](https://github.com/bantikyan/icheck-bootstrap)

**Comment by Tjoosten** [comment]
and what is the question?

**Comment by almasaeed2010** [comment]
Thanks for the suggestion. We'll keep it in mind.
