### ISSUE TITLE
Left Sidebar or Menu bar

### ISSUE THREAD

**Issue by timusiiit123** [almasaeed2010/AdminLTE#1187]
How to do position:fixed with overflow-y:scroll in left aside bar.
I am not doing it very well.
Please help me!!!

**Comment by almasaeed2010** [comment]
Did you try using the fixed layout option?

**Comment by timusiiit123** [comment]
No, but I have seen just now then it may be possible to use the scrollbar because it had not scrollbar.

**Comment by timusiiit123** [comment]
But I don't want fixed layout for my project so how can I do that?

**Comment by almasaeed2010** [comment]
Unfortunately, AdminLTE does not provide that feature. Please refer to StackOverflow or similar forums for more help regarding css positioning and scrolling. 

We apologize for the inconvenience.

**Comment by marcelogarbin** [comment]
@timusiiit123 Did you find any solutions?

**Comment by timusiiit123** [comment]
> @timusiiit123 Did you find any solutions?

I did that by JavaScript Code dynamically after loading the page.
