### ISSUE TITLE
Menu Support Scroll up and down

### ISSUE THREAD

**Issue by ghd258** [almasaeed2010/AdminLTE#1189]
Menu Support Scroll up and down    （SIDEBAR MENU）
![default](https://cloud.githubusercontent.com/assets/4811375/18612368/7cef2a7e-7d8a-11e6-858a-a1a1c8b94859.png)

**Comment by kressly** [comment]
What exactly is the question ?

**Comment by ghd258** [comment]
Support Scroll up and down

**Comment by fschaeffer** [comment]
If you include the provided slimscroll JS files (as in all examples) the menu scrolls perfectly :)
