### ISSUE TITLE
ajax file upload

### ISSUE THREAD

**Issue by creativesprite** [almasaeed2010/AdminLTE#119]
Hi all, not really an issue, more a question. Anyone using a plugin for ajax file upload which uses the progress bar to show upload progress ?

thanks :)

**Comment by winfan** [comment]
thanks almasaeed2010 for help me

**Comment by winfan** [comment]
http://blueimp.github.io/jQuery-File-Upload/    I like it !!!! thanks

**Comment by kressly** [comment]
Yeah and that is why almasaeed is getting a lot of people around the project : he answers questions as much as he can. :+1:
