### ISSUE TITLE
use iframe

### ISSUE THREAD

**Issue by dianxiaopao** [almasaeed2010/AdminLTE#1190]
Iframe embedded in the right side of the page, click on the menu on the left, the right iframe load a different page, but not width height adaptation, I would like to know, in this position, please use iframe

**Comment by almasaeed2010** [comment]
You may want to add ```style="width: 100%;"``` to the iframe to make it adapt to the width of its parent element. The height, however, is a little more complicated and you will need javascript to fix that issue. Please refer to StackOverflow or similar forums for more help.

Thanks and sorry that we can't help you here <3
