### ISSUE TITLE
"Black flash" when recalculate body height

### ISSUE THREAD

**Issue by githubjeka** [almasaeed2010/AdminLTE#1191]
https://github.com/dmstr/yii2-adminlte-asset/issues/98#issuecomment-248370578

**Comment by jgtb** [comment]
How do i fix it? is there a solution available for this issue?

**Comment by almasaeed2010** [comment]
Please provide a full description of the issue including the version of AdminLTE that you are using and browser information.

Thanks!

**Comment by jgtb** [comment]
Version: AdminLTE v2.3.6

Example of issue: https://sendvid.com/5kkxitsp

**Comment by almasaeed2010** [comment]
I tried this version in a Mac using Chrome and FF but I couldn't replicate the issue. Could you provide the HTML produced by your page? I need to verify that all of the files are loaded properly and that the markup is complete.

Thanks!

**Comment by jgtb** [comment]
I'm currently using this extension https://github.com/dmstr/yii2-adminlte-asset with Yii 2.0

HTML: http://pastebin.com/v3bKJyEh

**Comment by almasaeed2010** [comment]
I created a quick fix in the master repository. You could try it now if you'd like by downloading the master repo.

Thanks for reporting the issue!
