### ISSUE TITLE
Select2 tags input are bordered

### ISSUE THREAD

**Issue by nettunodev** [almasaeed2010/AdminLTE#1192]
I updated AdminLTE from version 2.1.2 to 2.3.6 and I'm using Select2 version 4.0.0. When I use tags now, every time I select a tag from the list or I had a new one, it shows a rectangle input bordered in blue, while before there was just the cursor.
I also tried updating to Select2 version 4.0.3 but the issue is still there.
I think it is something in the css... How can I fix this?
Thanks

![before](https://cloud.githubusercontent.com/assets/22340421/18702307/66008ae8-7fe1-11e6-97c0-9f28b1850b23.png)
![now](https://cloud.githubusercontent.com/assets/22340421/18702308/66394b4e-7fe1-11e6-8ffe-f8e0e48f7d91.png)

**Comment by cjmling** [comment]
@nettunodev 
Override the CSS using this code if you wish not to have that blue color border.

```
.select2-search--inline .select2-search__field:focus {
    border: none;
}
```

**Comment by nettunodev** [comment]
Great! That worked.
Many thanks!!
