### ISSUE TITLE
Active menu item has no visual cue under light themes

### ISSUE THREAD

**Issue by cloudmu** [almasaeed2010/AdminLTE#1194]
- With dark themes, the active menu on the sidebar has a vertical bar as visual cue (see the blue bar in front of `Dashboard` menu):
  ![image](https://cloud.githubusercontent.com/assets/3992029/18733101/26ceb43a-8036-11e6-9393-350236c4dd17.png)
- However with light themes, the active menu on the sidebar loses the vertical bar as visual cue:
  ![image](https://cloud.githubusercontent.com/assets/3992029/18733041/cc317bac-8035-11e6-9481-cb4cdc850ba7.png)

It would be nice to show the vertical bar in front of active menu under light themes too.

**Comment by cjmling** [comment]
Not sure because they are intended to be light or not. Could submit a PR but depend on the author. You could personally override it by.

.skin-black-light .sidebar-menu>li.active>a {
    border-left-color: #000;
}

NOTE : change `.skin-black-light` to any active theme class and choose the desired color.

**Comment by cloudmu** [comment]
@cjmling  Thanks!
