### ISSUE TITLE
Can't Remove Collapsing Sidebar Animation

### ISSUE THREAD

**Issue by kevinfaguiar** [almasaeed2010/AdminLTE#1195]
Hello, I want to store the state of the sidebar on a LocalStorage object of the browser. It's already working, but everytime a page loads (if the state of the sidebar is collapsed) it opens uncollapsed and then it does the animation of collapsing.
How can I remove this animation of the sidebar collapsing? There is a class or something I can take off to remove the animation?

**Comment by dhandarbeit-tk** [comment]
See this, might help: https://github.com/almasaeed2010/AdminLTE/issues/1020
