### ISSUE TITLE
Dynamic notification menu.

### ISSUE THREAD

**Issue by Tjoosten** [almasaeed2010/AdminLTE#1198]
![image](https://cloud.githubusercontent.com/assets/5157609/18934732/aa095562-85db-11e6-87d7-af9a92a87310.png)

QUestion. If i have 1 unread notification. There is a huge whitespace. How can i fix this?

**Comment by skyzero110** [comment]
in souce code ,
 <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height:auto;">
<ul class="menu" style="overflow: hidden; width: 100%; height: 200px;">
----------------------------------------
modify height:auto !Imporant;

**Comment by Tjoosten** [comment]
???

**Comment by Tjoosten** [comment]
Adding that css code wont't help.

**Comment by REJack** [comment]
I am think he means that you need to modify both the `div` & the `ul` like this:
```html
<div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: auto;">
<ul class="menu" style="overflow: hidden; width: 100%; height: auto;">
```

**Comment by Tjoosten** [comment]
What div??

**Comment by kressly** [comment]
The div where the message list expands

**Comment by almasaeed2010** [comment]
Please update your AdminLTE version. In v2.3.8, this is how it looks like:
<img width="200" alt="screen shot 2016-11-04 at 11 10 22 am" src="https://cloud.githubusercontent.com/assets/1512664/20010649/59aae278-a27f-11e6-8fc3-59fc7865b95c.png">

**Comment by Tjoosten** [comment]
@almasaeed2010 no success after update

**Comment by almasaeed2010** [comment]
It turns out, this is a slimscroll limitation. You can turnoff slimscroll for the navbar menus by using the following AdminLTE options:

```js
// Add this line before loading app.min.js
var AdminLTEOptions = {
    navbarMenuSlimscroll: false
}
```

This will allow the browser to use its own scroll implementation. That's all we can do at this point, unfortunately.

**Comment by ajcastro** [comment]
is this fixed in latest version?
