### ISSUE TITLE
Premium themes with shiny dashboard

### ISSUE THREAD

**Issue by victor-geere** [almasaeed2010/AdminLTE#1199]
Is it possible to use a premium theme e.g. SmartAdmin with the shiny-dashboard implementation of AdminLTE?

https://rstudio.github.io/shinydashboard/appearance.html
http://wrapbootstrap.com/preview/WB0573SK0

**Comment by REJack** [comment]
I would ask this to @rstudio the creator of shinydashboard.

https://github.com/rstudio/shinydashboard
