### ISSUE TITLE
black layout, but user menu on the top background is blue.

### ISSUE THREAD

**Issue by thearabbit** [almasaeed2010/AdminLTE#120]
When i change background layout to `black`, i think that it should change all.
But user menu on the top is still `blue`.
where i should change it to black?

**Comment by hendimarcos** [comment]
I'm having the same blue color problem when using ngx-admin-lte
the black skin looks like this:
black and black-light

```
    > .logo {
      .logo-variant(#fff; #333);
      border-right: 1px solid @gray-lte;
      @media (max-width: @screen-header-collapse) {
        .logo-variant(#222; #fff);
        border-right: none;
      }
    }
```

and all others like this (without the '>' ):

```
    //Logo
    .logo {
      .logo-variant(darken(@<color>, 5%));
    }
```
