### ISSUE TITLE
Left Slide toggle not working

### ISSUE THREAD

**Issue by nicktan147** [almasaeed2010/AdminLTE#1200]
I'm not sure why is it not working, when I click on the toggle nothing happen. However, on my console log I received this error:-

`VM1273:27 Error: the fixed layout requires the slimscroll plugin!`

In my body, I uses this:-

`<body class="hold-transition skin-blue sidebar-collapse sidebar-mini fixed">`

Am I missing something? I'm installing YII2

**Comment by lenamtl** [comment]
make sure you have the js link on your page
<script src="plugins/slimScroll/jquery.slimscroll.min.js"></script>

**Comment by almasaeed2010** [comment]
As @lenamtl mentioned, you need to include the slimscroll plugin in your page.

Thanks!
