### ISSUE TITLE
Code flashing out from left side bar

### ISSUE THREAD

**Issue by icezkiwi** [almasaeed2010/AdminLTE#1206]
Hi, I am facing code flashing out from left side bar when i press any item in my page **every time** when the page is loaded, but the code only flash out Once until the next time the page refresh.  

Am i only the one who is facing this issue?

Kindly refer to gif image for better understanding. 

Thanks.

![bug](https://cloud.githubusercontent.com/assets/22582644/19026408/251ef6e2-8958-11e6-8f79-236c3db72cca.gif)

**Comment by lenamtl** [comment]
Use Chrome dev tool right click Inspect
and check you probably have some js errors

**Comment by icezkiwi** [comment]
Dear Almasaeed,

 

OK, Thanks for your reply, I will try this method.  

 

Million thanks!



Best Regards,

 

Arthur Liew,

 

arthurliew@inter-application.com

**Comment by icezkiwi** [comment]
Hi, you are right.

I trace using chrome dev tools and the issue was from dashboard2.js.

Comment the code out and it work like charm now.

Thanks!
