### ISSUE TITLE
(CHARTS) Use Charts to generate all the missing libraries

### ISSUE THREAD

**Issue by ConsoleTVs** [almasaeed2010/AdminLTE#1208]
Use https://github.com/ConsoleTVs/Charts to generate all the missing libraries you have ^^

**Comment by rubyframework** [comment]
Would be there a way to use Charts without php?

**Comment by ConsoleTVs** [comment]
Charts is a PHP package, you'll need to use the library you wish to use independently, it's javascript and css after all ^^

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE only concerns itself with front-end technologies. We apologize for the inconvenience! and thanks for the suggestion <3
