### ISSUE TITLE
fa-angle-left is not update to fa-angle-down when the menu option is clicked

### ISSUE THREAD

**Issue by luronumen** [almasaeed2010/AdminLTE#1212]
**fa-angle-left** is not update to **fa-angle-down** when the menu option is clicked in the **AdminLTE 2.3.6**.

Note that this issue was not happening on **AdminLTE 2.3.5**

![adminlte-2 3 5](https://cloud.githubusercontent.com/assets/8019466/19168206/6cb3f8a6-8be5-11e6-90b8-ad224087dc9c.png)

![adminlte-2 3 6](https://cloud.githubusercontent.com/assets/8019466/19168208/6fa621c4-8be5-11e6-8781-ff92b457c6ad.png)

**Comment by jakezatecky** [comment]
This was fixed in 30f991680289b36f5db200ac6057250c96400454. For now, you have to v2.3.5 until that fix is applied in a new release.

@almasaeed2010 when can we expect a new release?

**Comment by luronumen** [comment]
Thank you for your reply @jakezatecky !
I will wait for the next point release to update my system ;)

Best Regards,
Luciano

**Comment by gauurof** [comment]
the version of AdminLTE2 in github repository and in https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html have the same versions name but nevertheless they are different. The version in Github works well with the dropdown. But if you download the version from the site https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html then you will have that dropdown problem. I tested it myself today ...So i recommend that you download it direct from github

**Comment by luronumen** [comment]
Hi @gauurof 

I downloaded **AdminLTE v2.3.6** from the [github released page ](https://github.com/almasaeed2010/AdminLTE/releases).
Probably, if you are not seem the issue you downladed any version after the fixed in [30f9916](https://github.com/almasaeed2010/AdminLTE/commit/30f991680289b36f5db200ac6057250c96400454) that is not yet considered as an stable release version.

Best Regards,
Luciano

**Comment by almasaeed2010** [comment]
I will release v2.3.6 soon. Sorry for the long delay!
