### ISSUE TITLE
Taiwan is a part of China.

### ISSUE THREAD

**Issue by renjunchi** [almasaeed2010/AdminLTE#1213]
The map is marked wrong.Taiwan is a part of China.Please correct！

**Comment by renjunchi** [comment]
Visitors Report中把台湾独立出去了。台湾是中国的领土。请更正！！！

**Comment by phpyii** [comment]
6666

**Comment by almasaeed2010** [comment]
Hello @renjunchi ,

This is an issue with jVector map. Please report it to them https://github.com/bjornd/jvectormap/issues

Sorry for the inconvenience.

Thanks!
