### ISSUE TITLE
Viewing data table on mobile

### ISSUE THREAD

**Issue by TotallyNerdy** [almasaeed2010/AdminLTE#1217]
When viewing the data tables from a mobile device, it cuts off the tables. 
![image](https://cloud.githubusercontent.com/assets/8138625/19332943/832f06d6-90b6-11e6-8cf0-3f0f97eb973c.png)

**Comment by REJack** [comment]
thats a default behavior from bootstrap.

try to add a div with `class="table-responsive"` around your table.
[Bootstrap Responsive tables](http://getbootstrap.com/css/#tables-responsive)

**Comment by almasaeed2010** [comment]
You could use the DataTables Responsive plugin if @REJack's suggestion didn't work: https://datatables.net/extensions/responsive/

Thanks!
