### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by hamozo86** [almasaeed2010/AdminLTE#1219]
Hi! I have adminLTE 2.3.3.
I would like to update to 2.3.5 but i don't know what is the changes?
Could you help me to write it, what should i change to update?

**Comment by REJack** [comment]
I would check the changelog.

**Comment by almasaeed2010** [comment]
The changelog can be found here: https://github.com/almasaeed2010/AdminLTE/blob/master/changelog.md

Thanks!
