### ISSUE TITLE
LTE Ecosystem

### ISSUE THREAD

**Issue by fthamura** [almasaeed2010/AdminLTE#1220]
why we have a admin lte ecosystem, like example that work very nicely, that more than current default, contribute by anyone

like better form data entry for purchase order, invoice, shipping, or any thin

work with balsamiq may be will bring more better ecosystem, or another mockup apps

**Comment by almasaeed2010** [comment]
Hello @fthamura,

AdminLTE is a simple HTML template. Unfortunately, we don't have the time to create a complete solution or integrate it with anything on that scale. Sorry for the inconvenience.

Thanks!
