### ISSUE TITLE
Leff side menu backgroud color

### ISSUE THREAD

**Issue by csotomon** [almasaeed2010/AdminLTE#1223]
Hi, I'm creating an angular2 version of AdminLTE.

when the content of the page is larger than the left side menu, the background color is not repeated, how you can see in the picture.

What could I have forgotten?

![captura de pantalla 2016-10-17 a las 9 17 10 p m](https://cloud.githubusercontent.com/assets/9087039/19462258/196d20a8-94b1-11e6-8b3e-5265292f7cc2.png)

**Comment by almasaeed2010** [comment]
Please check your console and verify that you have loaded all the needed resources. You most likely didn't include app.js after jquery.js and bootstrap.js.

Thanks!
