### ISSUE TITLE
Misplaced title attribute

### ISSUE THREAD

**Issue by fandii** [almasaeed2010/AdminLTE#1227]
First, I use Tinymce editor and when I hovering on its textarea then show some text like this : 

![capture-20161023-013907](https://cloud.githubusercontent.com/assets/19692828/19621879/37ccc8a0-98c6-11e6-9fa6-3d2005e870c6.png)

I find the source where it come from : 

![capture-20161023-014459](https://cloud.githubusercontent.com/assets/19692828/19621896/879023be-98c6-11e6-80cf-c014ee2bfc47.png)

I was like "Ok, fine!" and add some code 
````
        window.onload = function()
    	{
    		$('iframe#editor1_ifr').removeAttr('title');
    	}`
```

But then I realize this happen not for Tinymce only, but for elements that contains title attribute.
Hover on image : 
![capture-20161023-015112](https://cloud.githubusercontent.com/assets/19692828/19621913/02233864-98c7-11e6-8e65-59c62fdc0823.png)

Hover on anchor : 
![capture-20161023-020628](https://cloud.githubusercontent.com/assets/19692828/19621916/21a875be-98c7-11e6-9870-99d4eb86c7b5.png)

Is anyone know what happen? and how to fix this?
Note: I use the latest version

**Comment by almasaeed2010** [comment]
This seems like a bootstrap tooltip issue. AdminLTE activates tooltips automatically in the app.js file. However, in our demo, tooltips work fine. Try disabling tooltips by adding the following line before you load app.js:

```html
<script>
  AdminLTEOptions = { enableBSToppltip: false };
</script>
```

If that solves the problem, then there is some library related to bootstrap missing in your implementation.

**Comment by fandii** [comment]
Thank you that solve this problem by adding `enableBSToppltip: false` before load app.js
