### ISSUE TITLE
Vue JS 2

### ISSUE THREAD

**Issue by juppdes** [almasaeed2010/AdminLTE#1229]
Any plans for integration with Vue.js 2 ?

**Comment by donPuerto** [comment]
good idea ;)

**Comment by arcanedev-maroc** [comment]
Yeah great idea, this also may help: https://github.com/yuche/vue-strap

**Comment by almasaeed2010** [comment]
We are considering Vue for v3. Thanks for the suggestion!

@arcanedev-maroc good to know that! It will for sure be helpful.

**Comment by xeoshow** [comment]
And new update for this issue?
How about below project which seems related?
https://github.com/misterGF/CoPilot

**Comment by ajcastro** [comment]
Cool! Vue in Version 3!

**Comment by nguyentranchung** [comment]
I'm waiting...

**Comment by Sakthi002** [comment]
Me to...........
