### ISSUE TITLE
facing problem to deploy ADMINLTE , exceed limits of subfolders created node_modules (bower)

### ISSUE THREAD

**Issue by deepaksaini143** [almasaeed2010/AdminLTE#1230]
i am using AdminLTE-2 ADMIN dashboard template, and i like it and planning to buy this template,
but there is problem in that template .. that template using node.js bower ..that is create so many sub folders and i am unable to deploy application due to windows limitations of sub folder..

Please give me solutions how to fix it.

![adminlte](https://cloud.githubusercontent.com/assets/9442533/19713296/d6e1b824-9b55-11e6-84fe-a8ebe151370e.png)

**Comment by deepaksaini143** [comment]
i dont know how to fix it

**Comment by REJack** [comment]
I would use Bower instead of NPM/NodeJS

**Comment by almasaeed2010** [comment]
I am not sure how to fix this either. You could probably ask the NPM community.

Thanks
