### ISSUE TITLE
What exactly is AdminLTE used for?

### ISSUE THREAD

**Issue by Sum-Guy** [almasaeed2010/AdminLTE#1231]
Can you explain what AdminLTE is used for?

What sort of internet business or activity is someone performing while using AdminLTE?

**Comment by PolyPik** [comment]
AdminLTE is a frontend template used for building websites and web apps.

By itself it does nothing. It merely provides the components and frameworks that allow one to present data and information in a sensible and eye-please manner.

**Comment by kressly** [comment]
In simple English Adminlte is the design that u can use for ur web applications either before the log into ur website of after they have logged in or both.
