### ISSUE TITLE
full screen nav / box

### ISSUE THREAD

**Issue by t0n1zz** [almasaeed2010/AdminLTE#1232]
hi, i just wondering is it possible like if i have a nav-tabs or box and i can just maximize it into fill entire screen so i can get more space to work with in that place? hmmm let me give a picture to explain it more better
![bkculv5 local-admins-perkembangancu-index_periode-2015-12-31](https://cloud.githubusercontent.com/assets/6964548/19749474/75a0b8ee-9c13-11e6-9d9a-99e372580f01.jpg)

so is it possible to do that?

**Comment by almasaeed2010** [comment]
Hello,

You could use a plugin such as this one: https://github.com/kayahr/jquery-fullscreen-plugin

Unfortuantely, we can't add this feature to the current version of AdminLTE at this point. We stopped adding features for v2 since we are working on v3.

Thanks!
