### ISSUE TITLE
Allow collapsed (but togglable) sidebar in fixed mode. Allow turning off sidebarExpandOnHover.

### ISSUE THREAD

**Issue by huksley** [almasaeed2010/AdminLTE#1234]
There is such cases when sidebar menu will have fairly limited number of menu items, but content will have a lot of content.

For such cases having collapsed menu in fixed menu is very usefull.

```
This option is forced to true if both the fixed layout and sidebar mini
are used together
```

**Comment by almasaeed2010** [comment]
Unfortunately, mixing the fixed layout and sidebar mini can't work because of the SlimScroll plugin. It prevents the sidebar elements from showing up on hover since it required the "overflow: hidden" rule on its container. Please see #451

**Comment by pda-code** [comment]
Quick fix:
- In sidebar-collapse just disable slimscroll like this

         $.AdminLTE.layout.fixSidebar: function () {

>     
>             if ($("body").hasClass("sidebar-collapse")) {
>                 if (typeof $.fn.slimScroll != 'undefined') {
>                     $(".sidebar").slimScroll({destroy: true}).height("auto").css('overflow', 'initial');
>                 }
>                 return;
>             }
> 

and just call $.AdminLTE.layout.fixSidebar every time on $.AdminLTE.pushMenu

**Comment by zachpainter77** [comment]
I noticed that this is only an issue when the application starts with the "fixed" class on the body tag.  If you wait until after admin lte initiates and then add the fixed class. You can have sidebar mini with fixed layout and no **expandOnHover**.  I am using the skinning feature for my application and what I do is store the user's preference in cookies and then set the appropriate classes to my body tag when building the razor view.  Not sure if people still use this or not, but I was able to find a solution that isn't too hacky. :)
