### ISSUE TITLE
Offcanvas can not be adaptive

### ISSUE THREAD

**Issue by dianxiaopao** [almasaeed2010/AdminLTE#1236]
```<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">```
When I click on this link, this is the case, the right side of the use of iframe
![qq 20161031222920](https://cloud.githubusercontent.com/assets/6711606/19857682/8cf36768-9fb9-11e6-9841-26a54b35ab9d.png)
![qq 20161031222929](https://cloud.githubusercontent.com/assets/6711606/19857683/8d19f072-9fb9-11e6-971c-ac14b71f565d.png)

**Comment by mirkochan** [comment]
Row 47:
`<span class="logo-mini"><b>A</b>LT</span>`

Here change or delete the text inside `<span>`

**Comment by almasaeed2010** [comment]
It seems like you are missing some tags. Could you provide your HTML?

**Comment by eruvierda** [comment]
I have similar error, inmy case the sidebar didnt collapsed when the button pressed @almasaeed2010 
my HTML
`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="icon" href="<?php echo base_url('assets/temaalus/image/mini.png'); ?>" type="image/gif" sizes="20x20">
  <title>Bank Sampah</title>
  
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/bootstrap/css/bootstrap.min.css">
  
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/dist/fontawesome/css/font-awesome.min.css">
  
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/dist/ionicons/css/ionicons.min.css">
  
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/plugins/datatables/dataTables.bootstrap.css">
  
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/dist/css/AdminLTE.min.css">
  
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/dist/css/skins/_all-skins.css">
  <link rel="stylesheet" href="<?php echo base_url(); ?>assets/temaalus/dist/css/toasty.css">

  


  
  
  
  
  <script src="<?php echo base_url(); ?>assets/temaalus/plugins/jQuery/jquery-2.2.3.min.js"></script>
  
  <script src="<?php echo base_url(); ?>assets/temaalus/bootstrap/js/bootstrap.min.js"></script>
  
  <script src="<?php echo base_url(); ?>assets/temaalus/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="<?php echo base_url(); ?>assets/temaalus/plugins/datatables/dataTables.bootstrap.min.js"></script>
  
  <script src="<?php echo base_url(); ?>assets/temaalus/dist/js/toasty.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
    $('.navbar a.dropdown-toggle').on('click', function(e) {
        var $el = $(this);
        var $parent = $(this).offsetParent(".dropdown-menu");
        $(this).parent("li").toggleClass('open');

        if(!$parent.parent().hasClass('nav')) {
            $el.next().css({"top": $el[0].offsetTop, "left": $parent.outerWidth() - 4});
        }

        $('.nav li.open').not($(this).parents("li")).removeClass("open");

        return false;
    });
});

  </script>

<script type="text/javascript">
$(document).on('click', '.sidebar a', function (e) {
  if($(this).attr('href') != '#') {
    $("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');
  }
});
</script>


</head>

<div class="skin-blue layout-top-nav fixed">
  <header class="main-header">
  
    <nav class="navbar navbar-static-top">
    <div class="navbar-header">
          <a href="<?php echo base_url('dashboard');?>" class="logo">
          <span></span><b>Bank</b> Sampah</a>
        </div> 
      <div class="container-fluid">
        
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            
          
            <li class="dropdown user user-menu">
              
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                
                <img src="<?php echo base_url('assets/avatar/avatar_default.png');?>" class="user-image" alt="User Image">
                
                <span class="hidden-xs"><?php echo $this->session->userdata('fullname');?></span>
              </a>
              <ul class="dropdown-menu">
                
                <li class="user-header">
                  <img src="<?php echo base_url('assets/avatar/avatar_default.png');?>" class="img-circle" alt="User Image">

                  <p>
                    <small><?php echo $this->session->userdata('fullname');?></small>
                  </p>
                </li>
                
               
                
                <li class="user-footer">
                  <div class="pull-right">
                    <a href="<?php echo base_url(); ?>Auth/logout" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        
      </div>
      
    </nav>
  </header>
</div>
  <aside class="main-sidebar">
    
    <section class="sidebar" style="height: auto;">
      
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo base_url('assets/avatar/avatar_default.png');?>" class="user-image" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php echo $this->session->userdata('fullname')?></p>
        </div>
      </div>
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active"><a href="<?php echo base_url('Dashboard');?>" target="" ><i class="fa fa-home fa-fw" aria-hidden="true"></i>   Dashboard</a></li>  
        <li><a href="<?php echo base_url('Input_barang');?>" target="" ><i class="fa fa-home fa-fw" aria-hidden="true"></i>Input Data</a></li>
        <li><a href="<?php echo base_url('Nasabah');?>" target="" ><i class="fa fa-home fa-fw" aria-hidden="true"></i> Data Nasabah</a></li>
      </ul>
    </section>
  </aside>
<body class="hold-transition skin-blue" style="padding-top: 50px;">
`

**Comment by eruvierda** [comment]
solved

I forgot to call app.js
