### ISSUE TITLE
AdminLTEOptions colors property not working

### ISSUE THREAD

**Issue by Adrienb16** [almasaeed2010/AdminLTE#1241]
Hello,

I try to modify the skins of AdminLTE with the custom file "AdminLTEOptions.js" before app.js.
I seen this solution on the official document : 
https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html

But when i modify the **colors** property, i don't see the result in my browser.

My AdminLTEOptions.js

```
var AdminLTEOptions = {
    //Enable sidebar expand on hover effect for sidebar mini
    //This option is forced to true if both the fixed layout and sidebar mini
    //are used together
    sidebarExpandOnHover: true,
    //BoxRefresh Plugin
    enableBoxRefresh: true,
    //Bootstrap.js tooltip
    enableBSToppltip: true,
    //Define the set of colors to use globally around the website
    colors: {
        lightBlue: "#23AEBB",
        red: "#f56954",
        green: "#00a65a",
        aqua: "#00c0ef",
        yellow: "#f39c12",
        blue: "#0073b7",
        navy: "#001F3F",
        teal: "#39CCCC",
        olive: "#3D9970",
        lime: "#01FF70",
        orange: "#FF851B",
        fuchsia: "#F012BE",
        purple: "#8E24AA",
        maroon: "#D81B60",
        black: "#222222",
        gray: "#d2d6de"
    }
};
```

I want to use this solution because I do not want to use the grunt for build custom variables.less file.

Thank you :)

**Comment by REJack** [comment]
I dont know it right, but i have looked over the code and it seems that the colors not used at the moment.

I'll tried this feature too and it doesn't worked, but it would be awesome for fast color changes on layout with customers.

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE uses LESS to be completely customizable. The JS colors is there as a reference. If we used JS to control the theme, it would cause so many issues such as flickering on every page load and a broken color scheme with CSS elements.

Sorry for the inconvenience.

**Comment by doabil** [comment]
Thanks for help. I change skins on web panel :)
