### ISSUE TITLE
DataTable & Mobile

### ISSUE THREAD

**Issue by veggia** [almasaeed2010/AdminLTE#1243]
Hello
I trying use AdminLTE with a mobile phone. I see an issue: the datatables of this page https://almsaeedstudio.com/themes/AdminLTE/pages/tables/data.html are not correctly contained in the window size phone. Are there any methods to fix this? (hiding columns, with a horizontal scroll bar?)
Thanks

Matteo

**Comment by REJack** [comment]
Look at #1217 

regards REJack

**Comment by armano2** [comment]
you should use this plugin for datatables
https://datatables.net/extensions/responsive/
