### ISSUE TITLE
Angular 2 version

### ISSUE THREAD

**Issue by csotomon** [almasaeed2010/AdminLTE#1244]
Hi, I'm coding an angular2 version of this theme.

If you are interested in this project, U can colaborate:

[Angular2-AdminLTE](https://github.com/csotomon/Angular2-AdminLTE)

**Comment by raulgomis** [comment]
+1

**Comment by jPaliwal88** [comment]
+1

**Comment by almasaeed2010** [comment]
I am glad people are showing interest. Good luck!
