### ISSUE TITLE
Delay sidebar-mini State On Hover

### ISSUE THREAD

**Issue by midobona** [almasaeed2010/AdminLTE#1248]
السﻻم عليكم ورحمة الله وبركاته 
فى البدايه انا عارف ان حضرتك عربى علشان كده كتبتلك باللغه العربيه بصراحه لوحة التحكم جميله جدا لكن عندى مشكله بسيطه لما بيمر الماوس على القائمه بتظهر بدون اى مشاكل ولما بيبعد بتختى بسرعه عايز ازد مدة الاختفاء بحيث انه لو بعد عن القائمه بالكامل ياخد ثانيتين مثلا علشان تختفى القائمه اما لو كان الهوفر على عنصر تانى تختفى عادى حاولت اكتر من مره انما بدون اى فائده وشاكر جدا لحضرتك واتمنالك كل التوفيق

 i need set timeout hover menu-mini when mouse out side menu @almasaeed2010

**Comment by almasaeed2010** [comment]
Alaykom Alsalam,

Could you please provide more information on the issue? Are you using the ExpandOnHover option? Or are you using the ```fixed``` layout?

Thanks.

**Comment by midobona** [comment]
No 
When Mouse Hover In sidebar Will Show same this image
 `<img src="http://store1.up-00.com/2017-01/1484669116381.png"></img>`
But When Mouse Out Sidebar he is fast Hide I want set timeout X seconds Before Hide 

Sorry For English ..

**Comment by midobona** [comment]
@almasaeed2010
