### ISSUE TITLE
AdminLTE does not show responsive on smartphone

### ISSUE THREAD

**Issue by Wouter-ddict** [almasaeed2010/AdminLTE#1249]
Hi, 

When i try to scale my browser (Chrome) to a mobile size the dashboard succesfully switches to responsive view.

However, when i try to look at the site with my smartphone or change to the device simulator on the browser, the site stays the same as the desktop but all very small.

Ive been searching for a while now and cant seem to find any solution.

little help plz :) TY

**Comment by REJack** [comment]
I think you forgot
```html
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
```

**Comment by Wouter-ddict** [comment]
at first in thought so as well, but when i copy the complete original index.php or index2.php from this repos i have the same problem...

**Comment by almasaeed2010** [comment]
Hello @Wouter-ddict 

Please provide more information on the device you are using. The chrome responsive inspector shows this:

![screen shot 2016-11-22 at 8 18 47 am](https://cloud.githubusercontent.com/assets/1512664/20604838/7faa2ce2-b236-11e6-825f-be740ab716aa.png)

Thanks!
