### ISSUE TITLE
Scaling from small to big view

### ISSUE THREAD

**Issue by cdecker15** [almasaeed2010/AdminLTE#1250]
When I scale my browser's width (making it say 400px wide or so) and then maximize the window again the footer gains a white bar underneath the actual footer. What might be causing this? Is it a bug or something I am missing? See picture. Keep in mind this white bar isn't shown when you just load the page, its when it scales from small(mobile) to large. 

[http://i.imgur.com/ofaIC55.png](http://i.imgur.com/ofaIC55.png)

**Comment by REJack** [comment]
I think you forgot the slimScroll Plugin before `app(.min).js`

The Blank Layout variant contains only this JS files in the footer and i got not the bug with this:
```html
<script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<script src="/plugins/fastclick/fastclick.js"></script>
<script src="/dist/js/app.min.js"></script>
<script src="/dist/js/demo.js"></script>
```

**Comment by cdecker15** [comment]
I actually had the slimScroll after the the app.min.js call, moving it before the call did not fix the issue. It still occurs.

**Comment by REJack** [comment]
I would check for console log errors/warnings maybe it say whats missing.

**Comment by cdecker15** [comment]
No console errors/warnings:(

**Comment by REJack** [comment]
Uff an other question do use use your HTML files locally or over a online page?

I have often problems with JS if i look over a backuped HTML page locally.

**Comment by cdecker15** [comment]
It is online.

**Comment by REJack** [comment]
thats really strange, i can only reproduce this if slimScroll is not loaded before app.js

**Comment by cdecker15** [comment]
Super weird... Happens on all of my pages. Super annoying

**Comment by REJack** [comment]
can you give me a online page from you with this failure, if they are not super secret :P?

**Comment by cdecker15** [comment]
Emailed!

**Comment by REJack** [comment]
You can close this issue 😄
