### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by philc000** [almasaeed2010/AdminLTE#1255]
how can i install it? Only Linux  or For windows too

**Comment by Tjoosten** [comment]
Both the only thing u need is some webserver. Further i advise u to read the readme.md and or the documentation.

**Comment by philc000** [comment]
I read it but I don't know how to install it and how can how can I make users and so

**Comment by Tjoosten** [comment]
it's only the front-end all the backend technology you need to write yourself.
