### ISSUE TITLE
Btn ccolor in box

### ISSUE THREAD

**Issue by loveorigami** [almasaeed2010/AdminLTE#1269]
I am create dropdown btn in box solid header and don't see dropdown menu. Because menu color is white
![001](https://cloud.githubusercontent.com/assets/98164/20999676/7de80586-bd27-11e6-9b49-dac325aa9b0e.png)

**Comment by almasaeed2010** [comment]
I am not sure why this is happening. As you can see below, the problem doesn't happen on the demo. Could you provide your HTML code please?

<img width="484" alt="screen shot 2016-12-11 at 1 47 26 pm" src="https://cloud.githubusercontent.com/assets/1512664/21082385/72f29be0-bfa8-11e6-87e3-5728dd6e7658.png">

Thanks!

**Comment by loveorigami** [comment]
```css
<div class="box box-success box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">My Title</h3>
              <div class="box-tools pull-right">
                <div class="btn-group open">
<button class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog"></i> <span class="caret"></span></button>

<ul class="dropdown-menu">
<li><a href="#" title="edit"><i class="fa fa-pencil"></i> Edit</a></li>
</ul>
</div>
              </div>
              <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              The body of the box
            </div>
            <!-- /.box-body -->
          </div>
```
