### ISSUE TITLE
Sidebar collapse on phone

### ISSUE THREAD

**Issue by mmucino1** [almasaeed2010/AdminLTE#1270]
Hi, excelent template, thank you. I'm using the template as a single page app, i.e. I'm not navigating to diferent pages on clickink the left side links, instead I'm replacing the section.conten html. All is OK, but when I'm in a phone if a click a option in the sidebar I want that the sidebar dissapear (toggle off) but not when in a desktop o laptop. Can you give me an advice to reach this functionality. Thnaks in advance.

Marco.

**Comment by almasaeed2010** [comment]
Hello, 

You might want to write some custom JS to achieve that. Here is an example:
```js
$(document).on('click', '.sidebar a', function (e) {
  if($(this).attr('href') != '#') {
    $("body").removeClass('sidebar-open').removeClass('sidebar-collapse').trigger('collapsed.pushMenu');
  }
});
```
Thanks!

**Comment by mmucino1** [comment]
WOW thanks a lot @almasaeed2010 , it works like a charm (although I don't know why it only disaprear on the phone). Again, thanks, excellent work!

**Comment by almasaeed2010** [comment]
@k0pl4xz this seems to be a completely different issue. Please open a new issue for it if you haven't already done so.

Thanks!
