### ISSUE TITLE
Nav dropdown-menu max-height not updating from app.js options

### ISSUE THREAD

**Issue by mojohub** [almasaeed2010/AdminLTE#1274]
If I change the app options navbarMenuHeight to another number such as 250px...

```
$.AdminLTE.options = {
  navbarMenuHeight: "250px", 

```

Then the slimscroll height and `<ul class="menu">` height get updated correctly such as...

```
element.style {
    overflow: hidden;
    width: 100%;
    height: 250px;
}

```

However the max-height property for `<ul class="menu">` keeps the original 200px value and therefore push the footer down.

```
.navbar-nav > .notifications-menu > .dropdown-menu > li .menu, .navbar-nav > .messages-menu > .dropdown-menu > li .menu, .navbar-nav > .tasks-menu > .dropdown-menu > li .menu {
    max-height: 200px;
    margin: 0;
    padding: 0;
    list-style: none;
    overflow-x: hidden;

```

The main reason I want to adjust the height is that once I have 4 or more list items then the bottom list item height is cutoff a little bit hence not consistent.

**Comment by REJack** [comment]
The option `navbarMenuHeight` is used only over the slimScroll plugin through the `app(.min).js`.

**Comment by mojohub** [comment]
so is there anyway to change the actual height of the drop down menu itself?

**Comment by REJack** [comment]
Which drop down menu you mean?

**Comment by mojohub** [comment]
Any of the navbar menus (messages, notifications, tasks). They all have the same issue. I have not been able to find a way to increase the height of the menus as yet so that they drop further down the page.

**Comment by REJack** [comment]
Try to add this css after AdminLTE's css files
```
.navbar-nav > .notifications-menu > .dropdown-menu > li .menu, .navbar-nav > .messages-menu > .dropdown-menu > li .menu, .navbar-nav > .tasks-menu > .dropdown-menu > li .menu {
    max-height: auto;
}
```
