### ISSUE TITLE
Directory Messes up Page

### ISSUE THREAD

**Issue by Zortex04** [almasaeed2010/AdminLTE#1277]
Hello, ive been working on my admin LTE page for some time now but creating pages inside another folder messes it up (i have already set up the directories of plugins the right way, its not that)
this always happends its pretty anoying to have all my pages uncatorized in the root folder
![screenshot_13](https://cloud.githubusercontent.com/assets/16668555/21112878/bfafed52-c0a7-11e6-9bec-15ec398b11eb.png)

**Comment by almasaeed2010** [comment]
Hi,
Please check your console log. 
In chrome go to View -> Developer -> JavaScript Console.

Paste any errors you may find here please.

Thanks!

**Comment by Zortex04** [comment]
There is nothing in the console

**Comment by REJack** [comment]
@Zortex04 Do you run this pages from your Local Envoirment? I get same results only if open any HTML direct on my local Browser, not over an webpage.

**Comment by Zortex04** [comment]
I run this via a Xampp Web server

**Comment by almasaeed2010** [comment]
If there are  no errors in the developer console then this most likely is an HTML tag mismatch error. Verify that your markup is correct. Hope that helps.
