### ISSUE TITLE
Equal height for boxes

### ISSUE THREAD

**Issue by creativesprite** [almasaeed2010/AdminLTE#128]
Hi all,

just wondering if anyone can give me some help here. Ive got 2 columns. Each column has a box in it. How do I set both boxes to be the equal height ?

thanks :)

**Comment by gugahoi** [comment]
Unfortunately this is not that great of a solution for this problem.
Something like the answers here might be more interesting: http://stackoverflow.com/questions/19695784/how-can-i-make-bootstrap-columns-all-the-same-height
