### ISSUE TITLE
Using with React and FlowRouter breaks Control-Sidebar and height bug

### ISSUE THREAD

**Issue by barrydoyle18** [almasaeed2010/AdminLTE#1291]
I've tried implementing `AdminLTE ` with my Meteor + React Project and everything is working perfectly (except one thing - see bottom) using the code below for my MasterPage:

```
import React from 'react'

import { Header } from './masterpage/Header'
import { MainSideBar } from './masterpage/MainSideBar'
import { ControlSideBar } from './masterpage/ControlSideBar'
import { Footer } from './masterpage/Footer'

export const MasterPage = ({content}) =>
    <div className="hold-transition skin-green sidebar-mini">
        <div className="wrapper">
            <Header />
            <MainSideBar />
            {content}
            <Footer />
            <ControlSideBar />
            <div className="control-sidebar-bg"></div>
        </div>
    </div>
```

Here is what happens with my routing:

```
import { FlowRouter } from 'meteor/kadira:flow-router'
import React from 'react'
import { mount } from 'react-mounter'

//Layouts and Pages
import { MasterPage } from '../../ui/layouts/MasterPage'
import { HomePage } from '../../ui/pages/HomePage'

FlowRouter.route('/', {
    name: 'homepage',
    action() {
        mount(MasterPage, {
            content: <HomePage />
        })
    }
})

```

After implementing this everything is great except the Control Sidebar doesn't open upon clicking the 
`<li><a href="#" data-toggle="control-sidebar"><i className="fa fa-gears"></i></a></li>` button.

I've tried opening it via CSS and that seems to work fine. Another issue I have is that now it doesn't stretch the full width of the window. There is a ton of whitespace at the bottom that's just gone un used and it doesn't look good.

All these issues began the moment I implemented FlowRouting (it worked great before that).  Am I implementing FlowRouter incorrectly? If so, what should I do?

Any help would be much appreciated!
Kind Regards,

Barry

**Comment by almasaeed2010** [comment]
Hello @barrydoyle18,

Unfortunately I am not a ReactJS expert so I can't help with the issue. Since the issue has been open for a few days without response, I would suggest that you try posting on StackOverflow for additional help.

Thanks!

**Comment by jensysantana** [comment]
hi, barrymichaeldoyle i have same issue like you had, if you solved it please tell me how to do it.
