### ISSUE TITLE
Inconsistent main-header color for Black and Black Light skins

### ISSUE THREAD

**Issue by luronumen** [almasaeed2010/AdminLTE#1293]
For all of the rest of the skin colors, **Blue**, **Purple**, **Green**, **Red** and **Yellow**, the main-header color is displayed in acordance with the skin name: **Blue**, **Purple**, **Green**, **Red** and **Yellow** respectively
But for the **Black** skins, **Black** and **Black Light**, the main-header color is displayed in **White** color.

![black](https://cloud.githubusercontent.com/assets/8019466/21484270/a7f0bb48-cb6e-11e6-9161-427d48f5f322.png)

Please fix this issue to display main-header color in **Black** when the **Black** or **Black Light** skin is selected and also create **White** and **White Light** skins for displaying the main-header in **White**.

**Comment by almasaeed2010** [comment]
Hello @luronumen,

We have addressed this issue before and came to the resolution of leaving that for v3 since many implementations of AdminLTE expect "black" to be "white". We appreciate the suggestion and it will be fixed in v3.

Thanks!

**Comment by cornernote** [comment]
Perhaps the addition of a black dark theme?

**Comment by cornernote** [comment]
Or make a white theme with a black header! I don't really mind what it's called, just wanted to have a black header.

**Comment by edujunque** [comment]
i just made some changes on this skin-black css. Now the header and aside menu are black and with text and hover more "darker".
If it helps...
[_all-skins.zip](https://github.com/almasaeed2010/AdminLTE/files/1315858/_all-skins.zip)

**Comment by luronumen** [comment]
Thank you very much @edujunque for providing a fix for this issue!
Is there any possibility to integrate this fix for the next point release the of this project?

**Comment by edujunque** [comment]
@luronumen i guess they will integrate this fix on the v3. 
But you can get it on my fork at: [My fork](https://github.com/edujunque/AdminLTE)
New skin calls skin-black-darker
