### ISSUE TITLE
Datatables not responsive when in a tab.

### ISSUE THREAD

**Issue by xDowwdeen** [almasaeed2010/AdminLTE#1295]
Hi,

I am having a problem when it comes to getting the Datatables to be responsive when in a Tab. As soon as like i put my phone landscape and the portrait it is fine but when the page first loads it doesn't resize the datatable to the size of the screen. See images below. 

<img width="686" alt="screenshot at dec 28 19-24-43" src="https://cloud.githubusercontent.com/assets/12575041/21529721/6c104604-cd33-11e6-9509-e31e631a8f19.png">
<img width="866" alt="screenshot at dec 28 19-25-10" src="https://cloud.githubusercontent.com/assets/12575041/21529722/6c28dcc8-cd33-11e6-9a94-e6d3803d5416.png">
<img width="628" alt="screenshot at dec 28 19-25-28" src="https://cloud.githubusercontent.com/assets/12575041/21529723/6c2bd86a-cd33-11e6-9235-9a02f7d27e13.png">

Anyone have any ideas on how to fix this? have been going around in circles with it for ages.

It is fine if i place a Datatable in a normal 'div' box.

<img width="685" alt="screenshot at dec 28 19-27-20" src="https://cloud.githubusercontent.com/assets/12575041/21529755/b56d7c18-cd33-11e6-8227-91c930858918.png">

Thanks

**Comment by rafgugi** [comment]
hey. can I see the code?

**Comment by xDowwdeen** [comment]
Yeah sure.

Added onto pasteBin. 

https://pastebin.com/UVxXp67Z

**Comment by rafgugi** [comment]
I myself use 
```html
<div class="table-responsive">
  <table id="applicationList" class="table table-bordered table-striped">
  ...
```
from [bootstrap](http://getbootstrap.com/css/#tables-responsive)

**Comment by REJack** [comment]
That would work on @xDowwdeen tables too, in the pastbin code you doesn't execute DataTable JS function, 
if you want to use DataTables instead of Boostraps Tables use [DataTable's Responsive extension](https://datatables.net/extensions/responsive/) for this problem.

**Comment by xDowwdeen** [comment]
@REJack I do use the Datatables extension and the JS functions are at the bottom of the page. The Responsive extension is working but when i load the page it doesn't but as soon as i rotate the device to landscape and then back to portrait its fine.

**Comment by fschaeffer** [comment]
If you are using a dataTable in a hidden tab (meaning it is not shown on page load) you'll have to take care yourself on resizing the columns on first page load.
```javascript
$(document).ready(function() {
    $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
        $.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
    } );
    ...
```
This is also mentioned in dataTables documentation: https://datatables.net/examples/api/tabs_and_scrolling.html

**Comment by xDowwdeen** [comment]
Perfect that had fixed it. Thanks all for your help :)

**Comment by zhoudaqing** [comment]
hi @xDowwdeen ，What design software do you use?

**Comment by xDowwdeen** [comment]
i use coda on Mac OS
