### ISSUE TITLE
Angular2, side navigation bar does not hide

### ISSUE THREAD

**Issue by piaDev** [almasaeed2010/AdminLTE#1298]
I'm using AdminLte in angular2. i have attached all the js files in index.html but in other components some of the js files are not seems to be working. i don't know how to fix this and i'm new to angular2. please help. here is the preview of my output and the index.html 

![screenshot 165](https://cloud.githubusercontent.com/assets/19823344/21585058/be6fc1a0-d0de-11e6-9183-ecddef8d3143.png)
![screenshot 166](https://cloud.githubusercontent.com/assets/19823344/21585059/bea70250-d0de-11e6-9dd8-63aa2335693d.png)

**Comment by codehakase** [comment]
@piaDev did you check your console to see if there were errors?

**Comment by piaDev** [comment]
@codehakase thanku for the rply. yes i did. but there is no errors. it just doesn't work.

**Comment by ppedrycz** [comment]
@piaDev I have got the same problem using React. Look at app.js, line 142. There is a "$" function (document.ready), which should be called programmatically every time the sidebar is rendered. However I cannot manage this. We need some global "refresh()" function.
