### ISSUE TITLE
Mouse hover effect sidebar

### ISSUE THREAD

**Issue by mpissolato** [almasaeed2010/AdminLTE#1299]
Hello guys, I need your help. 

I have a problem with the sidebar. When that collapsed, the mouse hover effect doesn't show the title of some itens of the menu. Someone know how can I fix this?

Thank you so much

![sem titulo](https://cloud.githubusercontent.com/assets/16958106/21599053/a5ccc9a8-d14d-11e6-91cd-a9237b92831b.png)

```
<li class="treeview active">
   <a href="#">
   <i class="fa fa-laptop"></i>
   <span>UI Elements</span>
   <span class="pull-right-container">
   <i class="fa fa-angle-left pull-right"></i>
   </span>
   </a>
   <ul class="treeview-menu menu-open" style="display: block;">
      <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
      <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
      <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
      <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
      <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
      <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
   </ul>
</li>
```
thanks

**Comment by almasaeed2010** [comment]
Hello @mpissolato 

Could you please provide more information such as the version of AdminLTE you are using and the browser?

Thanks!

**Comment by mpissolato** [comment]
Hello @almasaeed2010 

Thanks for replying, I found the error. What I'm doing wrong is to add scroll on the sidebar-menu, because I do not want the page to create scrollbar.
Is it possible to have a scrollbar on the sidebar-menu or is there already a native scroll bar for the sidebar-menu?

AdminLTE-2.3.6

```
.sidebar-menu {
    max-height: 510px ! important;
}

.scroll {
   overflow: scroll;
   overflow-x: hidden;
}

.scroll::-webkit-scrollbar-thumb {
   -webkit-box-shadow: inset 0 0 6px rgba(162, 55, 185, 0.5);
}

.scroll::-webkit-scrollbar {
   width: 6px;
   height: 3px;
}

.scroll::-webkit-scrollbar-thumb {
   background-color: #a237b9;
   border: 1px solid #a237b9;
}
```

Thanks

**Comment by almasaeed2010** [comment]
Hi,

If you are trying to use the sidebar with a fixed sidebar position, then unfortunately, the current implementation does not make that easy. However, you may remove sidebar-mini and use the fixed layout. The Layout section in the documentation may provide some insight into your issue: https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#layout

Thanks!
