### ISSUE TITLE
Error in the labels.

### ISSUE THREAD

**Issue by Tjoosten** [almasaeed2010/AdminLTE#1300]
**VERSION:** 2.3.7
**Browser:** Safari 10.0.1

if i hide the navigation bar on my macbook (13 inch. Late 2013). Then the label hover over the icons. 
<img width="1140" alt="schermafbeelding 2017-01-03 om 12 01 28" src="https://cloud.githubusercontent.com/assets/5157609/21605965/b790766c-d1ac-11e6-8d07-552c173fb57c.png">

**Comment by almasaeed2010** [comment]
Confirmed on Safari. Will fix soon. Thanks for reporting!
