### ISSUE TITLE
SlimScroll issue

### ISSUE THREAD

**Issue by ouatataz** [almasaeed2010/AdminLTE#1307]
Hi there !

There is an issue with the SlimScroll plugin which do not prevent the entire page to be scrolled when used on any div.

Does anybody know how to prevent the entire page to be scrooled when using slimscroll ?

Many thanks

**Comment by REJack** [comment]
SlimScroll in sidebar?

If yes, the SlimScroll plugin is only used in fixed layout or in navbar dropdowns.

**Comment by ouatataz** [comment]
not in sidebar but in navbar dropdowns. check it on the live preview https://almsaeedstudio.com/themes/AdminLTE/index2.html, in the "message dropdown", if you scroll the message list, the whole page is also scrolling but should not...

**Comment by REJack** [comment]
If i'm scroll in the dropdown the whole page doesn't move. (FF v50) 
With which browser you have that issue?

**Comment by ouatataz** [comment]
Also FF50, but I'm on MacOSX. I've never tested it on windows. Are you on windows ?

**Comment by REJack** [comment]
Yep Windows 10, but wait i test it on macOS Sierra

**Comment by REJack** [comment]
I doesn't have this issue on macOS Sierra with FF50 or Safari 10

**Comment by REJack** [comment]
It stay on position even if im on end of the scroll content

**Comment by ouatataz** [comment]
I'm still on yosemite. Maybe a yosemite issue. Just tested on chrome on my system and no problem... strange

**Comment by REJack** [comment]
yep thats strange, other question do you get some console errors?

**Comment by ouatataz** [comment]
no, absolutely no error. don't know how to fix it...

**Comment by ouatataz** [comment]
maybe i'll close this issue that appears to be related to my environment.

**Comment by ouatataz** [comment]
@REJack 
If you have any idea on how to fix this, please just let me know
