### ISSUE TITLE
how to render a tree in AdminLTE

### ISSUE THREAD

**Issue by weituotian** [almasaeed2010/AdminLTE#1308]
For some reason,i need to render a tree to show the data. now i had a problem that what should i did in AdminLTE.
![1444617407382356](https://cloud.githubusercontent.com/assets/7270968/21769319/0af17c5a-d6b9-11e6-84d7-c9cdceb6a430.gif)

**Comment by REJack** [comment]
Please provide code for example.

**Comment by weituotian** [comment]
`[{
                    "text": "Same but with checkboxes",
                    "children": [{
                        "text": "initially selected",
                        "state": {
                            "selected": true
                        }
                    }, {
                        "text": "custom icon",
                        "icon": "fa fa-warning icon-state-danger"
                    }, {
                        "text": "initially open",
                        "icon": "fa fa-folder icon-state-default",
                        "state": {
                            "opened": true
                        },
                        "children": ["Another node"]
                    }, {
                        "text": "custom icon",
                        "icon": "fa fa-warning icon-state-warning"
                    }, {
                        "text": "disabled node",
                        "icon": "fa fa-check icon-state-success",
                        "state": {
                            "disabled": true
                        }
                    }]
                },
                    "And wholerow selection"
                ]
`

i want to tranlaste the json data for view just like this:
![q -20170109223910](https://cloud.githubusercontent.com/assets/7270968/21770039/7c13a176-d6bc-11e6-82b5-6162d42cfc56.png)

superUI does this for us!
http://www.supermgr.cn/components/ui_tree.html

but i want the best way to do this in AdminLTE! Could this job be accepted?

![u 1615939549 2060279394 fm 116 gp 0](https://cloud.githubusercontent.com/assets/7270968/21770121/d5071132-d6bc-11e6-9f7a-a149fcc9aa59.jpg)

**Comment by REJack** [comment]
AdminLTE has no Tree View UI like SuperUI, but they use a free script for this named [jsTree](https://www.jstree.com/) you can add this by hand to AdminLTE if you want it.

regards REJack

**Comment by weituotian** [comment]
thanks! But does [jsTree](https://www.jstree.com/) ' css compatible with AdminLTE style?
![0066d6a4jw1fbkhymspksj30c80c8aa4](https://cloud.githubusercontent.com/assets/7270968/21808166/ff998464-d77c-11e6-9ccc-111d9a6b88ed.jpg)

**Comment by REJack** [comment]
Puhh i dont know, you need to test it, but you can copy the style from superUI 😄

**Comment by eruvierda** [comment]
Basically AdminLTE runs on CI, so Js based on CI will run in AdminLTE (logically speaking LOL)
You may try this tutorial @weituotian 
 [http://webeasystep.com/blog/view_article/Build_dynamic_tree_nodes_with_jstree_and_codeigniter](url)
or this one 
[http://phpflow.com/php/dynamic-tree-with-jstree-php-and-mysql/](url)

and customize the style as you like

**Comment by almasaeed2010** [comment]
Although AdminLTE provides a treeview for its sidebar, the custom plugin is not generic enough to create a tree menu like the one you requested. However, as everyone here mentioned, you could easily use other implementations like the one used in SuperUI. 

Hopefully in v3, the script we wrote can be very customizable and be used in more ways than the sidebar.

Thanks!
