### ISSUE TITLE
thank you my friend, do you have a plan support bootsrap v4 ?

### ISSUE THREAD

**Issue by iloveyo123u1** [almasaeed2010/AdminLTE#1310]
:)

**Comment by novasdream** [comment]
https://github.com/almasaeed2010/AdminLTE/issues/710


Em qua, 11 de jan de 2017 às 01:59, iloveyo123u1 <notifications@github.com>
escreveu:

**Comment by almasaeed2010** [comment]
As @novasdream pointed out, we are currently working on it. Thanks!
