### ISSUE TITLE
Search: add button dropdown won't display dropdown contents

### ISSUE THREAD

**Issue by jrlooney** [almasaeed2010/AdminLTE#1312]
In the search form, I've converted it to have a button dropdown so user can choose different type of search to perform. However, on clicking the button, the dropdown does not display (though I can see the "open" class being added to the unordered list). So I'm guessing there's something about the CSS on the form that is keeping the dropdown from appearing?

&lt;form action="#" method="get" class="sidebar-form"&gt;
&lt;div class="input-group"&gt;
	&lt;input type="text" name="q" class="form-control" placeholder="Search Courses..."&gt;
	&lt;div class="input-group-btn"&gt;
		&lt;button type="button" class="btn btn-flat dropdown-toggle" data-toggle="dropdown" data-target="#searchType"&gt;
				&lt;i class="fa fa-search"&gt;&lt;/i&gt;&lt;span class="caret"&gt;&lt;/span&gt;
		&lt;/button&gt;
		&lt;ul class="dropdown-menu dropdown-menu-right" id="searchType"&gt;
				&lt;li&gt;&lt;a href="#"&gt;Courses&lt;/a&gt;&lt;/li&gt;
				&lt;li&gt;&lt;a href="#"&gt;Curriculum&lt;/a&gt;&lt;/li&gt;
		&lt;/ul&gt;
	&lt;/div&gt;
&lt;/div&gt;
&lt;/form&gt;

**Comment by REJack** [comment]
If found it. 😄 
First with your html code i doesn't get the dropdown, i needed to remove ` data-target="#searchType"` from the button and then this lil css fixes the problem.

```css
.sidebar-form{
  overflow: visible;
}
```

I hope this helps.


Example HTML: 
```html
<form action="#" method="get" class="sidebar-form">
  <div class="input-group">
    <input type="text" name="q" class="form-control" placeholder="Search Courses...">
    <div class="input-group-btn">
      <button type="button" class="btn btn-flat dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-search"></i> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="#">Courses</a></li>
        <li><a href="#">Curriculum</a></li>
      </ul>
    </div>
  </div>
</form>
```

**Comment by jrlooney** [comment]
Bingo! Thanks for your help!

**Comment by REJack** [comment]
no problem 😃
