### ISSUE TITLE
content-wrapper flickers when loading additional javascripts

### ISSUE THREAD

**Issue by Baldoius** [almasaeed2010/AdminLTE#1316]
Hello!

I'm trying to inject other js resources. 
As soon I implement the `<script src="somefile.js">` code, the `div.content-wrapper`  respectively the `footer` flickers on page load

Does https://github.com/almasaeed2010/AdminLTE/pull/997 fix that?

**Comment by almasaeed2010** [comment]
Hello @Baldoius,

Unfortunately, we didn't get to test the solution suggested in #997. Up to this point, I am not sure what a solution for this issue could be other than reimplementing the layout in a different way. In AdminLTE 3, flexbox will resolve that issue.

Thanks!

**Comment by Baldoius** [comment]
Hi!

Will AdminLTE 3 have the same html structure?

**Comment by almasaeed2010** [comment]
Unfortunately, the HTML will have to change a little to utilize Bootstrap 4 components.
