### ISSUE TITLE
Bootstrap 4 has changed the Nav structure to Flexbox

### ISSUE THREAD

**Issue by rlightner** [almasaeed2010/AdminLTE#1317]
This causes the header Nav to be totally wonky.

https://v4-alpha.getbootstrap.com/components/navbar/

**Comment by almasaeed2010** [comment]
Currently, the stable version of AdminLTE uses BS3. But, AdminLTE v3, which is in a very early stage, integrates BS4. During the development version of both AdminLTE 3 and Bootstrap 4, I am sure we will encounter multiple hurdles like the one you mention here. 

We appreciate your contribution to our active development. Thanks!
