### ISSUE TITLE
Control sidebar does not open

### ISSUE THREAD

**Issue by crkjl** [almasaeed2010/AdminLTE#1318]
Thank you Almasaeed for your great theme!!!
I've a little issue with control sidebar. It doesn't open.
No errors in console. I've followed run with chrome developer tools, initializing of control sidebar is run, but the problem is that btn.on click event is never called.

For you info, I'm working my application with angular 1.5. May be this the cause? Any idea?

Left sidebar and dropdowns works like a charm.
Regards

**Comment by crkjl** [comment]
Hi, I've solved the issue just adding with ng-click function the class to the element.
Sorry to disturb.
regards

**Comment by DarioN1** [comment]
Hi man, can you post the code please?
