### ISSUE TITLE
Installation and configuration of AdminLTE for altcoin platform

### ISSUE THREAD

**Issue by solarflareproject** [almasaeed2010/AdminLTE#1319]
Hello, we are here to request support for an upcoming platform that integrate altcoin and renewable energy under the form of an investor-based game.
After a long reserach we found this Admin Theme and we are wondering if that's can fit what we would to do.
We are working to the launch of our coin through an Initial Coin Offering and we would to create a page like this, to be more specific:
https://s27.postimg.org/6374yzowz/ico.png
where future investors can buy their stake paying with BTC while on the same page they can see the price of or coin, how many fund are raised at the moment of their deposit and other useful info.
We basically need that investors that go to this page, after login, are able to see a page like that attached.
After installing the theme, what we are missing or need to create and populate fields as in the image attached? We need to linka  database or what?
Our site have a wordpress template, we have created a dedicated page where admin theme should be installed and running.
Can someone give us needed support on this, or point us on where to find helpful docs?
Thanks for any kind answer, keep up the good work!
solarflarecoin@gmail.com

**Comment by almasaeed2010** [comment]
Hello @solarflareproject,

AdminLTE is merely an HTML template that provides a set of components and layout options to build a friendly user interface for your visitors. It does not, however, provide any backend integrations and that is to make as general as possible for any backend integration.

In your case, you need to implement the functionality using PHP and Wordpress. For that type of support, you may want to visit the [Wordpress forums](https://wordpress.org/support/) or hire a Wordpress professional to create your app.

Thank you for your interest in AdminLTE!

**Comment by solarflareproject** [comment]
Thanks for getting in touch, i will go through the wordpress forum.
Best regards!


2017-01-17 15:46 GMT+01:00 Abdullah Almsaeed <notifications@github.com>:
