### ISSUE TITLE
IE11 {document.dispatchEvent(new CustomEvent('o.DOMContentLoaded'))}

### ISSUE THREAD

**Issue by marcobranco1975** [almasaeed2010/AdminLTE#1322]
Hi!

I have this error on IE11:

**Object doesn't support this action**

in fastclick.min.js on this line 

{document.dispatchEvent(new CustomEvent('o.DOMContentLoaded'))}

What can i do to solve this issue?

Thank's in advance

**Comment by eruvierda** [comment]
maybe you could look at this discussion at fastclick repository first @marcobranco1975 
[https://github.com/ftlabs/fastclick/issues/405](url)

**Comment by almasaeed2010** [comment]
Hello @marcobranco1975, 

I agree with @eruvierda, this seems like an issue that should be reported at the [FastClick repository](https://github.com/ftlabs/fastclick/issues).

You should know, however, that FastClick is not a required script and that you could remove it from your implementation without affecting much of the functionality.

Thanks!
