### ISSUE TITLE
Version number update

### ISSUE THREAD

**Issue by ppjuarez** [almasaeed2010/AdminLTE#1323]
The version in AdminLTE/dist/js/app.js still says 2.3.8 even though the newest release is 2.3.11

**Comment by kjdion84** [comment]
+1

**Comment by almasaeed2010** [comment]
I keep forgetting to do that before releasing a version (sigh...). Fortunately, in v3, there is a script that creates the version header. We will have to release v2.3.12 to fix this mistake. Hopefully by the end of this week after testing the new additions to the themes.

Thanks!
