### ISSUE TITLE
navigation header having display issue when there is too many item and make it multiline on display

### ISSUE THREAD

**Issue by yuyenkan** [almasaeed2010/AdminLTE#1324]
When the navigation header with too many item or high zoom ratio which make it show in multiline, 
the side bar will be affected, 
the top position is not follow with last line of navigation header,
and the footer also affected to show 1 more line of blank content below footer.

![image](https://cloud.githubusercontent.com/assets/22000244/22012168/b5672ddc-dccd-11e6-8499-bbace0a02f71.png)

**Comment by almasaeed2010** [comment]
Hello @yuyenkan, 

AdminLTE supports window widths from 320px and above. The 320px breakpoint is the most common responsive design limit. If, however, you need to support smaller devices, you may need to resort to hiding elements to accommodate the size of the screen. The ```hidden-xs`` is a class that is available at your convenience to hide elements in small screen screens.

Thanks!
