### ISSUE TITLE
jump page

### ISSUE THREAD

**Issue by jinji-hanbin** [almasaeed2010/AdminLTE#1331]
When a large number of tabular forms, there is no jump to the specified page style, for example, I would like to jump to 100 pages, 200 pages.
![image](https://cloud.githubusercontent.com/assets/18417846/22060007/1d72e0d8-ddaa-11e6-889c-9113f6b79ced.png)

**Comment by lenamtl** [comment]
This is custom code 
depending which table code you are using and if you use server side language or not.
 
If you are using datatables 
https://datatables.net/plug-ins/pagination/

**Comment by REJack** [comment]
Try https://datatables.net/plug-ins/pagination/input

**Comment by jinji-hanbin** [comment]
For developers to shoot, design is the most difficult, a beautiful design will give people the feeling of shines, so I need a demo
