### ISSUE TITLE
Update "Data Table_Info" dynamically

### ISSUE THREAD

**Issue by WNBraulio** [almasaeed2010/AdminLTE#1332]
How do I do to change the info (that shows amount of records at table bottom and its pagination) of a dynamic data table?
I am using AdminLTE Version 2.3.7.

In the following picture, this table was filled at beginning of process with 4 entries, and was cleaned in middle of processing but its status remains like original.
![change_info](https://cloud.githubusercontent.com/assets/25206865/22077154/2000a750-dd9a-11e6-8602-a79019b87d45.jpg)

**Comment by REJack** [comment]
Hi @WNBraulio,

check out https://datatables.net/reference/option/info & https://datatables.net/examples/basic_init/language.html

**Comment by WNBraulio** [comment]
Hi @REJack,
Thanks but not solved yet.

I want these objects (info and pagination) be updated automatically: like attached object shows must be "Showing 0 to 0 of 0 entries", or when table body has 20 lines it shows "Showing 1 to 10 of 20 entries" and so on.

I will try remove and recreate table by each XML request but I don't know if it would be a good solution.

**Comment by REJack** [comment]
I append my datatables with a simple ajax script, the info and pagination are updated automaticly.

Here my add entries script:
```js
  var table = $('#example1').DataTable();
  function add_entries(){
    var counter = 1;
    //CLEAN TABLE BEFORE NEW ENTRIES
    table.clear().draw();
    //ADD NEW ENTRIES
    $.post("http://example.com/get_data", function(data){
      $.each($.parseJSON(data), function(key, itm){
        table.row.add( [
            itm.field1,
            itm.field2,
            itm.field3,
            itm.field4,
            itm.field5
        ] ).draw();

        counter++;
      });
    });
  }
```

**Comment by WNBraulio** [comment]
Hi @REJack,
Thank you very much!

I was using "replaceWith()".
I fix my code with your example and now it works!
