### ISSUE TITLE
can top navigation 2.0 with sidebar?

### ISSUE THREAD

**Issue by yuyenkan** [almasaeed2010/AdminLTE#1337]
there is 2 examples of top navigation, can they combine?

**Comment by REJack** [comment]
Yep it works, 
you need to add the whole `<aside class="main-sidebar">` content from a other layout, place the sidebar-toggle where you want it and i would add sidebar-collapse to the body tag.

Here is my created example to test it: [index2_top.zip](https://github.com/almasaeed2010/AdminLTE/files/730476/index2_top.zip)

regards REJack
