### ISSUE TITLE
Widget width not adjusting

### ISSUE THREAD

**Issue by mkandut** [almasaeed2010/AdminLTE#1339]
Hello,

I am using the version 1 https://almsaeedstudio.com/themes/AdminLTE/index.html.

The problem is that if you drag the widget (SALES) to the right column which has a different sizes, the graph inside will remain on the same dimensions. This means for the Sales graph, loosing half of the information.

If I change the size of the browser window the error gets fixed automatically.

Maybe this code block is the reason for it?

.chart svg, .chart canvas {
    width: 100% !important;
}

I would appreciate a push for this fix. thanks.

**Comment by REJack** [comment]
Its not so hard to fix,
i changed the sortable function in `dashboard.js` to:
```js
  $(".connectedSortable").sortable({
    placeholder: "sort-highlight",
    connectWith: ".connectedSortable",
    handle: ".box-header, .nav-tabs",
    forcePlaceholderSize: true,
    zIndex: 999999,
    update: function (event, ui) {
      area.redraw();
      donut.redraw();
      line.redraw();
    }
  });
```
