### ISSUE TITLE
AdminLTE with .NET Core`

### ISSUE THREAD

**Issue by rodriguezfa** [almasaeed2010/AdminLTE#1340]
Hello All,
  I'm implementing AdminLTE with .NET Core.  I hope someone can review it.

 https://github.com/rodriguezfa/AdminLTE.NETCore

Thanks!
Francisco

**Comment by gldraphael** [comment]
That's a 404

**Comment by rodriguezfa** [comment]
It looks like the link above was pointing to a different location..
https://github.com/rodriguezfa/AdminLTE.NETCore

Here is a demo site that I may have up for a couple of months.
https://frodriguez.xyz/

**Comment by gldraphael** [comment]
Nice.

Looks like you've used ajax to load partial views. TBH if that's what I'm after, I'd rather go with something like vuejs or react. That way I can have my ASP.NET app to just expose APIs for the webapp would consume.

What I'd actually be interested in would be tag helpers for the different controls. And a few layouts to get started. This would be of great help if I'm trying to get something up in really little time. You could probably publish it as a nuget package. This in my opinion will have more use-cases and you might hopefully manage to get contributions too.

**Comment by rodriguezfa** [comment]
I will have to take a look at vuejs and react.  Thanks!

**Comment by ChangePlaces** [comment]
Is there an ASP bootstrap tag helper library that could be bastardised?
