### ISSUE TITLE
React Components

### ISSUE THREAD

**Issue by falmar** [almasaeed2010/AdminLTE#1341]
Hello there.

I been using `AdminLTE` for almost half year now in the traditional way using JQuery plugins and so on...

Few months ago I started a side project on building [React Components](https://github.com/falmar/react-adminlte) or bindings for `AdminLTE`. Sort of personal use but since its open-source I wanted to know if I am able to do / continue with it or is there any problem?

It does not import anything from `AdminLTE` since it is all JavaScript/JSX  it mostly uses just the html elements and the css classes.

**Comment by almasaeed2010** [comment]
Hi,

It is fine to use AdminLTE in open source, personal or commercial projects.

If you do complete this project, you can add it to the [implementations section of AdminLTE's Documentation](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#implementations).

Sorry for the delay. Thanks!
