### ISSUE TITLE
Sliders page not loading correctly

### ISSUE THREAD

**Issue by rodriguezfa** [almasaeed2010/AdminLTE#1342]
Hi all,
  I noticed that the sliders are not showing correctly.  Updating to version 2.1.6 appears to fix the issue.
![image](https://cloud.githubusercontent.com/assets/14892045/22184601/bbe16866-e089-11e6-9ca3-897417bad4a5.png)

https://almsaeedstudio.com/themes/AdminLTE/pages/UI/sliders.html

**Comment by REJack** [comment]
It can be fixed too with a simple change 
```js
    $("#range_2").ionRangeSlider();
```
to
```js
    $("#range_2").ionRangeSlider({});
```

**Comment by almasaeed2010** [comment]
Thanks for reporting this! I will add the fix in master.
