### ISSUE TITLE
element>element css selector on styles

### ISSUE THREAD

**Issue by wen96** [almasaeed2010/AdminLTE#1344]
Hey, thank you in advance for your work.

I was working for a couple of months with AdminLTE and AngularJS. I use to create AngularJS directives wrapping AdminLTE components and the styles for components use to use `element>element` `css` selector, which AngularJS directives breaks the style when you use `replace: false`. Why is the point of this? Why not to use `.class .anotherClass` selector?

Example code:

```
<ul class="timeline">
    <li>
         <i class="fa fa-envelope bg-blue"></i>
    </li>
</ul>
```
The selector for style is `.timeline>li>.fa` and my HTML after componentize the icon could be:

```
<ul class="timeline">
    <li>
         <my-happy-icon class="bg-blue">enevelope</my-happy-icon>
    </li>
</ul>
``` 

Which will be transclude to:

```
<ul class="timeline">
    <li>
         <my-happy-icon>
            <i class="fa fa-envelope bg-blue"></i>
        </my-happy-icon>
    </li>
</ul>
```

So, the selectors is not getting it and I have to re-write the selector to `.timeline li .fa`.

**Comment by almasaeed2010** [comment]
Hello,

The ```>``` selector is used to pick first level elements only. Unfortunately, we might have use that in components that don't necessarily need it. We apologize for the inconvenience but it would very time consuming to track down and fix every selector at this point. We are hoping for much better CSS and JS in AdminLTE v3.

Thanks!
