### ISSUE TITLE
Save box state, for default collapsed and expanded boxes.

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#1345]
Hi,

I'm using this solution from @BlueTeck for saving box state with localstorage
https://github.com/almasaeed2010/AdminLTE/issues/1064

It's working great as long as all the boxes on a page have the same default state, all collapsed or all expanded.
I'm wondering if anyone have modified it to use it 
when the box is collapsed by default with collapsed-box class and expanded box.
<div class="box box-primary collapsed-box" id="filters" data-name="filters">

If boxes are all collapsed on the  page
I can use
if(box.state == 1)
instead of
if(box.state == 0)

I also tried this with no luck

```
if(box.state == 0){
$('.box[data-name="'+box.boxname+'"]').find($.AdminLTE.options.boxWidgetOptions.boxWidgetSelectors.collapse).trigger( "click" );
}                         
else {
  $('.box[data-name="'+box.boxname+'"]').removeClass("collapsed-box");
	} 
```

Any solution is welcome
Thanks

**Comment by REJack** [comment]
try this
```js
      if(box.state == 0){
          $('.box[data-name="'+box.boxname+'"]').addClass('collapsed-box');
          $('.box[data-name="'+box.boxname+'"]').find('.btn-box-tool[data-widget="collapse"] i').removeClass('fa-minus').addClass('fa-plus');

      }else if(box.state == 1){
          $('.box[data-name="'+box.boxname+'"]').removeClass('collapsed-box');
          $('.box[data-name="'+box.boxname+'"]').find('.btn-box-tool[data-widget="collapse"] i').removeClass('fa-plus').addClass('fa-minus');
      }
```

**Comment by lenamtl** [comment]
Ok I have tried your solution it's almost correct, only issue with the icons:

For the box that have default state collapsed:
when I click to expand, the box expand, the icon turn Minus
if I refresh the page the box stay expanded, the icon turn to Plus this is no good the icon should stay Minus. Localstorage value is 1.

For the box that have the default state expanded:
when I click to collapse, the box collapse, the icon turn to Plus
if I refresh the page the box stay collapsed, the icon turn to Minus this is no good the icon should stay Plus. Localstorage value is 0.

**Comment by REJack** [comment]
Strange, i have not this issues with the icons.
I had this before and then i switched the `$('.box[data-name="'+box.boxname+'"]').find('.btn-box-tool[data-widget="collapse"...` from the if's (before i posted it here)

**Comment by lenamtl** [comment]
I have 2 boxes on my page one is collapsed and the other one is expanded
one of the box have the class **collapsed-box**
`<div class="box box-primary collapsed-box" id="contacts_filters" data-name="contacts_filters">`

and the other box is expanded
`<div class="box box-primary" id="contacts_filters2" data-name="contacts_filters2">`

**Comment by REJack** [comment]
it should work. 
i have 2 default collapsed and 2 expanded and it works normal.

**Comment by lenamtl** [comment]
and you refresh the page after clicking on the box

**Comment by REJack** [comment]
sure

**Comment by REJack** [comment]
idk but try to replace my full code with yours maybe its diffent

**Comment by lenamtl** [comment]
exactly the same code.
 I have cleared all temporary files the started with empty values in localstorage just to make sure
I did the same test and the icon is no good.
I put back the boxes to default state now it's displaying the icons correctly.

Here is my button in case something is different
`<button type="button" class="btn btn-sm btn-default" data-widget="collapse" data-toggle="tooltip" title="" data-original-title=""><i class="fa fa-minus"></i></button> `

**Comment by REJack** [comment]
Your button miss the `btn-box-tool` class, but you can change the script to catch only `.btn` instead of `.btn-box-tool`.

That's my button code like [the preview](https://almsaeedstudio.com/themes/AdminLTE/index2.html) from almasaeed2010.
```html
<button class="btn btn-box-tool" type="button" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
<i class="fa fa-minus"></i>
</button>
```

**Comment by lenamtl** [comment]
Ha! that was the problem, thanks for your patience :)
