### ISSUE TITLE
attach an event to the menu open button

### ISSUE THREAD

**Issue by TheILPlace** [almasaeed2010/AdminLTE#1346]
hi, need some help, how to attach a click event to the button that open/closes the left panel. i see that its in CSS (not my strongest thing)..
i need this, in order to react in another place in the page, to fix grid colunm widths

thanks

**Comment by REJack** [comment]
It's quite simple, place this JS code after `app(.min).js`:
```js
$(document).on('collapsed.pushMenu expanded.pushMenu', function(){
	//PUT YOUR CODE HERE
});
```

**Comment by TheILPlace** [comment]
thanks for your reply.. but i want to attach angular2 code to the click event (which will call a method on a service)

**Comment by wen96** [comment]
@TheILPlace `(click)` directive does not work? If not, you can use jquery on your Angular2 code as @REJack sais, can't you? Anyway, this is more a Stackoverflow question than an issue, isn't it?

**Comment by TheILPlace** [comment]
thanks!
found the place to put it:


    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button" (click)="hamburgerClicked()">

**Comment by ZivHsu** [comment]
Hi @REJack 

if i want to run my script in  main-sidebar close or open after,

how to do it ?

I has try to run my script in here
`$(document).on('collapsed.pushMenu expanded.pushMenu', function(){
	//PUT YOUR CODE HERE
});`
but it will running main-sidebar close or open before...

**Comment by REJack** [comment]
@ZivHsu Do you mean that you want to run your code before the animation is started? If yes, you need to modify app(.min).js there are only the trigger after menu is closed/opened not before animation starts :/

**Comment by wen96** [comment]
Hey guys, I don't want to be creepy, but for this kind of discussion, you think could be better to create a question on stackoverflow or similar?

**Comment by ZivHsu** [comment]
Hi @REJack 

I try to modify the app.min.js but it same to main-sidebar close or open before...

`$.AdminLTE.pushMenu = {
        activate: function (e) {
            var i = $.AdminLTE.options.screenSizes;
            $(document).on("click", e, function (e) {
                e.preventDefault(), $(window).width() > i.sm - 1 ? $("body").hasClass("sidebar-collapse") ? $("body").removeClass("sidebar-collapse").trigger("expanded.pushMenu") : $("body").addClass("sidebar-collapse").trigger("collapsed.pushMenu") : $("body").hasClass("sidebar-open") ? $("body").removeClass("sidebar-open").removeClass("sidebar-collapse").trigger("collapsed.pushMenu") : $("body").addClass("sidebar-open").trigger("expanded.pushMenu");
                **/*my script to resize charts*/**
            }),
            $(".content-wrapper").click(function () {
                $(window).width() <= i.sm - 1 && $("body").hasClass("sidebar-open") && $("body").removeClass("sidebar-open")
            }),
            ($.AdminLTE.options.sidebarExpandOnHover || $("body").hasClass("fixed") && $("body").hasClass("sidebar-mini")) && this.expandOnHover()
        },
        expandOnHover: function () {
            var e = this,
                i = $.AdminLTE.options.screenSizes.sm - 1;
            $(".main-sidebar").hover(function () {
                $("body").hasClass("sidebar-mini") && $("body").hasClass("sidebar-collapse") && $(window).width() > i && e.expand()
            }, function () {
                $("body").hasClass("sidebar-mini") && $("body").hasClass("sidebar-expanded-on-hover") && $(window).width() > i && e.collapse()
            })
        },
        expand: function () {
            $("body").removeClass("sidebar-collapse").addClass("sidebar-expanded-on-hover")
        },
        collapse: function () {
            $("body").hasClass("sidebar-expanded-on-hover") && $("body").removeClass("sidebar-expanded-on-hover").addClass("sidebar-collapse")
        }
    }`

is anything I miss?

**Comment by REJack** [comment]
@ZivHsu 
1. put large codes into ``` (triple) not in a single ` 
2. Do you mean that your resize function should only start after the transition is done? Because you get a .3s delay from the sliding effect through a CSS3-Transition.

If you want to run your code after the transition try this out, no modification needed (place after app(.min).js):
```js
<script>
  $(document).on('collapsed.pushMenu expanded.pushMenu', function(){
    var timeoutID;
    function delayedStart() {
      timeoutID = window.setTimeout(resizeAction, 350);
    }

    function resizeAction() {
      // YOUR RESIZE FUNCTION HERE
      alert("Sidebar is collapsed or expanded!")
      window.clearTimeout(timeoutID);
    }

    delayedStart();
  });
</script>
```

@wen96 Sure but nobody follow stackoverflow for the tag `adminlte` or something 😄
@almasaeed2010 Please create a forum for this on your Page (https://almsaeedstudio.com/)

**Comment by mvbn** [comment]
To just resize the chart, is possible to use:
```
$('.content').on('resize', function () {
    // Update your chart here
});
```
where .content is the class of the section:
`<section class="content">`
