### ISSUE TITLE
Radio Buttons not Styling as they are in the Demo

### ISSUE THREAD

**Issue by Connor2hd** [almasaeed2010/AdminLTE#1349]
Hello,

I am trying to style my radio buttons but they are not appearing as they do in the demo.  I attach various classes such as "flat-red" but yet I am left with default radio buttons.

Any help is appreciated.

Thanks.

**Comment by almasaeed2010** [comment]
Hello,

Please review the documentation for [iCheck](http://icheck.fronteed.com/).

Thanks!
