### ISSUE TITLE
Programatically expand/collapse a box

### ISSUE THREAD

**Issue by cstapetrei** [almasaeed2010/AdminLTE#1351]
Hi,

More of a question than an issue: 

 I'm trying to open or close a box from js after an ajax is complete.
It seems that bootstrap's .collapse() doesn't do anything :)

Is there another method i should be calling on the box object ?

Thanks.

**Comment by BrstDev123** [comment]
I have the same problem in my sidebar-menu and on dashboard widgets.
sidebar menu collapse on first click and work fine on further clicks. On dashboard widgets on minimise the widget it starts toggle.

**Comment by cstapetrei** [comment]
As a quick and dirty workaround you can just hide(or not) the 

<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>

and trigger it's click event when you need it.

var box = $('.box');
box.find('.box-header button').trigger('click')

// or plain js
var box = document.querySelector('.box');
if (box){
  btn = box.querySelector('.box-header button');
  if (btn){ 
    btn.dispatchEvent(new Event('click'));
  }
} // the ifs are optional if you know the elements are actually there
// querySelector returns null if nothing's found


I was just curious of a more direct way :)

**Comment by BrstDev123** [comment]
I have resolved my problem with removal of required.js file which was located in /dist/js/ folder.

Thank you !

**Comment by almasaeed2010** [comment]
You can use these helper functions:

```js
$("#box-widget").activateBox();
$("#box-widget").toggleBox(); // expand/collapse
$("#box-widget").removeBox();
```

**Comment by shiennymendeline** [comment]
$("#mybox").boxWidget('collapse');

https://adminlte.io/docs/2.4/js-box-widget
