### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by alexkleinubing** [almasaeed2010/AdminLTE#136]
Hi, I downloaded AdminLTE, but the tooltip dont show correctly.
I no modify nothing, only open.
I dont see the tooltip baloon, only the content of tooltip in footer of page:

<div role="log" aria-live="assertive" aria-relevant="additions" class="ui-helper-hidden-accessible"><div style="display: none;">Remove</div><div style="display: none;">Remove</div></div>

Or other button mouse hovered...
Whats happen?

**Comment by IneniousDeveloper** [comment]
tooltips color not showing, When append span

**Comment by IneniousDeveloper** [comment]
And its working properly, When add tooltips
![tooltips1](https://user-images.githubusercontent.com/50582693/57622570-856ecf80-75ab-11e9-81ec-b1705281df92.png)
 directly.

**Comment by IneniousDeveloper** [comment]
Here is my code
![tooltips2](https://user-images.githubusercontent.com/50582693/57622707-cebf1f00-75ab-11e9-8ba4-b6298c417ffb.PNG)
