### ISSUE TITLE
Using the alert message on Admin LTE

### ISSUE THREAD

**Issue by celorza** [almasaeed2010/AdminLTE#1364]
Hi, I am new in developing ASP.net with bootstrap and Admin LTE. I am trying to work with the alert but I am not able to solve the issue.

I placer the html code as follows.
```html
<div class="box-body">
 <div class="alert alert-info alert-dismissible">
 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h4><i class="icon fa fa-info"></i>Info!</h4>
   Data is Saved
  </div>
  <div class="form-group">
  <asp:Label class="col-sm-2 control-label" runat="server" Text="Codigo"></asp:Label>
  <div class="col-sm-10">
  <asp:TextBox ID="TxtCodigo" class="form-control" runat="server" AutoPostBack="true" OnTextChanged="Validar"></asp:TextBox>
  </div>
 </div>
```
I want the alert box to be hidden, and display when the information is saved with a code behind.

```
 Protected Sub BtnGrabar_Click(sender As Object, e As EventArgs) Handles BtnGrabar.Click
        Tabla = "Terceros"
        Campos = "(Identificacion, Nombre, Direccion, Ciudad, Telefono1, Email)"
        Camposfrm = "('" + TxtCodigo.Text + "','" + TxtNombre.Text + "','" + TxtDireccion.Text + "','" + TxtCiudad.Text + "','" + TxtTelefono.Text + "','" + TxTEmail.Text + "')"
        Consulta = "Identificacion='" + TxtCodigo.Text + "'"
        Try
            conexion.ValidarExiste(Tabla, Consulta)
            If conexion.ds.Tables(0).Rows.Count = 0 Then
                conexion.Insertar(Tabla, Campos, Camposfrm)

                "display the alert with a text (Information is saved)"
            Else
                 "display the alert with a text (Information is not saved)"

            End If
        Catch ex As Exception
        End Try
    End Sub
```

Thanks for your help.

Celorza

**Comment by equisgroup** [comment]
I think you need to improve the issue presentation since it isn't clear. HTML code can't be seen correctly.

The best option here is to use a javascript function to call ajax, use a webmethod on your page and based on the respond show the box. 

By the way your issue is more about how to use bootstrap than about AdminTemplate so i recommend to close the incident.

**Comment by almasaeed2010** [comment]
Hello,

Since I am not an ASP.NET developer, I am afraid I can't be of much help. I would suggest trying StackOverflow to post this issue since you might find a wider variety of developers there.

Thanks!
