### ISSUE TITLE
Left sidebar toggle not working in my angular 2 project

### ISSUE THREAD

**Issue by yogeshnikam33** [almasaeed2010/AdminLTE#1365]
I have created angular2 project and added AdminLTE template in that all css are applied but left sidebar toggle is not working.

**Comment by almasaeed2010** [comment]
Please make sure that you have all the necessary JS files loaded in the correct order. Also, make sure the sidebar toggle button has this attribute ```data-toggle="offcanvas"```.

Thanks!

**Comment by nankathi** [comment]
Hi Almasaeed,
First of all thank you very much for the great work.I am able to use the AdminLTE for a Asp.Net Core and Angular 2 application but unable to get a workaround for sidebar when using the angular 2 routing. When i click on the toggle button it just refreshes the page with the default route set.
 Any idea or suggestions on how to overcome this issue.

Regards,
Raj

**Comment by nankathi** [comment]
@yogeshnikam33 : is it working for you?

**Comment by idalvarez** [comment]
I have the same problem, somebody can resolve it?

**Comment by celery94** [comment]
This problem still exist for all of the hyperlink such as <a href="#">Some</a>.

**Comment by viethoanganh79** [comment]
@rjankathi I have same problem like u, and i solve it. u can try modyfi 'href' attr of <a> tag
`@Directive({
  selector : '[href]',
  host : {
    '(click)' : 'doNothing($event)'
  }
})
export class LinkDirective {
  @Input() href: string;

  doNothing(event) {
    if(this.href.length === 0 || this.href === '#') {
      event.preventDefault();
    }
  }
}`

**Comment by viethoanganh79** [comment]
@almasaeed2010 i try `data-toggle="offcanvas"` and role button in the <a> tag
`<li class="treeview" *ngIf="userRoles['ASBD']" [routerLinkActive]="['active']">
          <a href="#" data-toggle="offcanvas" role="button">
            <i class="fa fa-envelope"></i>
            <span>An sinh bưu điện</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>`
but it dont working right in final product build with angular2-cli
also it working right in local host in test version of product
can u help me fix it?

**Comment by viethoanganh79** [comment]
OMG, 
i missing include app.js
after I include app.js
it's working...

**Comment by gauravtyagi77** [comment]
I am also facing this as well, does anyone found any permanent solution for it.
@viethoanganh79 nice solution but in case of tab click it is not working.
@almasaeed2010  this issue occurs when you go to ADMIN LTE dashboard page from login page via "this.router.navigate" or "window.location.assign" only.
