### ISSUE TITLE
Colapsed Sidebar - Expands on Mouseover

### ISSUE THREAD

**Issue by jogibear9988** [almasaeed2010/AdminLTE#1369]
I've added the  sidebar-collapse to my body tag, but my sidebar expands on mouseover, and does not popup on click as in the sample

**Comment by almasaeed2010** [comment]
Are you using the fixed layout?

**Comment by jogibear9988** [comment]
yes, it's not possible to use both?

**Comment by jogibear9988** [comment]
if not, will it work in adminlte 3?

**Comment by almasaeed2010** [comment]
The problem is with using ```sidebar-mini``` with ```fixed```. Slimscroll, a required plugin with the fixed layout, prevents the links from showing on hover. V3 might have support for sidebar mini + fixed but I can't make any promises at this time.

Thanks.
