### ISSUE TITLE
hide sidebar by default

### ISSUE THREAD

**Issue by annomartano** [almasaeed2010/AdminLTE#137]
Assalamua'alaikum..
I'm beginner and still learn. it a fantastic theme, i've try it for practice. 
how to hide left side bar on start without clicking the toggle navigation first.
I'm sorry for this dumb question. thank you so much..

**Comment by vsuryakala** [comment]
how to copy your code @almasaeed2010

**Comment by REJack** [comment]
@vsuryakala If you use AdminLTE v2.3.x then you need only to add `sidebar-collapse` to body class
