### ISSUE TITLE
AdminLTE.css imports css from a public site

### ISSUE THREAD

**Issue by mudij** [almasaeed2010/AdminLTE#1370]
I recently added the Admin LTE template to a project and noticed that the AdminLTE.css imports fonts from a googleapis url.

`@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);`

I was wondering that this will be an issue for applications deployed in a private network with no access to the internet. Would it not be better to include the stylesheet and update it if required.

**Comment by ikhsan017** [comment]
You can actually download the font, and point the css style to use the local font

**Comment by mudij** [comment]
I can download it but I will have to modify the AdminLTE.css file each time there is an update to AdminLTE.

**Comment by ikhsan017** [comment]
you can create your own css to override adminLTE.css
