### ISSUE TITLE
Dynamically adding 'fixed' class to navbar causes incorrect content-wrapper height

### ISSUE THREAD

**Issue by kmielski** [almasaeed2010/AdminLTE#1381]
Whenever you dynamically add the .fixed class to the body (for a fixed navbar), the content-wrapper height is incorrectly calculated (min-height attribute). It seems the layout.fix routine (in app.js) is fired _before_ the fixed-class is actually added.

After dynamically adding the fixed class, triggering the resize-event seems to be a quick fix (executing the AdminLTE.layout.fix/fixSidebar() init procedures).

**Comment by almasaeed2010** [comment]
Unfortunately, AdminLTE does not deal with dynamically added classes (maybe it should though). The current solution, however, is to trigger the layout.fix function after you dynamically add the class.

Thanks and sorry for the delay!
