### ISSUE TITLE
Cannot npm install without numerous errors

### ISSUE THREAD

**Issue by Sefton419** [almasaeed2010/AdminLTE#1383]
Is anyone else not able to npm install without running into several depreciated/missing dependencies? How do you get this to work properly?

**Comment by REJack** [comment]
How you used npm install?
1. Inside of AdminLTE's root folder (beside the package.json)?
2. or did you run `npm install admin-lte`?

I think the package.json is for the compiling that almasaeed2010 does on every release.

PS: I get no errors on `npm install` with node v6.9.5 and npm v3.10.10 on Win10 x64
