### ISSUE TITLE
Issue #430 has reappeared

### ISSUE THREAD

**Issue by wryates** [almasaeed2010/AdminLTE#1384]
I have a .net core application and used bower to import adminlte version 2.3.11 (visual studios 2015).

At first i thought i was just doing something wrong, but then i noticed the example pages didn't work correctly either.

I run it and go straight to the example pages and view for example the 404.html, if you click a menu item, the whole page start to slide again on the load. 

How can we get the sliding to stop and work correctly like the preview?

**Comment by almasaeed2010** [comment]
Do you have class `hold-transition` in the body?

**Comment by wryates** [comment]
I found the problem, I was using the latest version of JQuery which bootstrap doesn't support! Sorry about that!
