### ISSUE TITLE
Page length is wrong after v2.3.7

### ISSUE THREAD

**Issue by FrozenFighter** [almasaeed2010/AdminLTE#1387]
First, I want to sorry for my bad English but please continue to read.
I have used this template for long time, but today I decide to update to latest version.
I have some problems with page length as display in photo below.
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/9080908/23464495/cbf590c2-fec7-11e6-96b0-6747ab6f693f.png">

So I try to check older version manually in github.
I found that lastest version that work great is v2.3.7.

You can try to see error by yourself at Demo page
https://almsaeedstudio.com/themes/AdminLTE/pages/examples/lockscreen.html
https://almsaeedstudio.com/themes/AdminLTE/pages/examples/login.html
https://almsaeedstudio.com/themes/AdminLTE/pages/examples/register.html

Thanks

**Comment by ssunbob** [comment]
Yes,Just same as my issue. Maybe some important css code was left.

**Comment by FrozenFighter** [comment]
@ssunbob Sorry, I didn't see your issue. I will close this issue since it duplicate.
