### ISSUE TITLE
not working on server

### ISSUE THREAD

**Issue by BgR8** [almasaeed2010/AdminLTE#1388]
Dropdown menus, data-toggle="tooltip",  bootstrap data-toggle="modal",  Tabs, icheck scripts, and data-spy="scroll" which have found in documentation page  ( arrow link which takes from footer to top)  are not working on the server but anything i say work on localhost and the index.html or other html page of the theme while i open without server its working again.

**Comment by REJack** [comment]
Check your console on your server and check the order of the javascript files.

default javascript order:
1. jquery-2.X.min.js & jquery-ui
2. bootstrap.min.js
3. icheck & other custom scripts
4. AdminLTE's app.min.js
5. Page specific scripts (like dashboard.js, demo.js)

Like it's in [Dashboard v1](https://github.com/almasaeed2010/AdminLTE/blob/master/index.html#L1221)

**Comment by BgR8** [comment]
The order is ok. Before this theme the dropdown menu and animated popup is working

**Comment by REJack** [comment]
Please provide your html & js code to help you better.

**Comment by BgR8** [comment]
İm connectin' from mobile right  know if you wanna see the code is here [atolyemde.com](url)

**Comment by REJack** [comment]
jQuery-2.2.3.min.js is missing

**Comment by BgR8** [comment]
Thank you. Errors for jquery whats the others i cant see

**Comment by REJack** [comment]
Yep only jQuery errors 😄 Upload jQuery-2.2.3.min.js then it should work.

My console gives this erros.
```
Error: Bootstrap's JavaScript requires jQuery  bootstrap.min.js:11:37
ReferenceError: jQuery is not defined[Weitere Informationen]  jquery.slimscroll.min.js:16:1
Error: AdminLTE requires jQuery  app.min.js:13:5510
ReferenceError: jQuery is not defined[Weitere Informationen]  demo.js:340:1
```

**Comment by BgR8** [comment]
Thank you for your helps

**Comment by REJack** [comment]
no problem ^^
