### ISSUE TITLE
any easy way to use dark color theme called Slate ?

### ISSUE THREAD

**Issue by paul3333** [almasaeed2010/AdminLTE#1389]
i google a dark color theme called Slate
here is the link: [http://bootswatch.com/](url)
scroll down can see a theme called Slate, there provide 6 files:
bootstrap.min.css
bootstrap.css
variables.less
bootswatch.less
_variables.scss
_bootswatch.scss

but any method to combine Slate into AdminLTE ?
so we can use AdminLTE all the nice functions such as sidebar, control siderbar,...etc with dark color

**Comment by REJack** [comment]
Create a new skin for this, its the easiest way.

Copy https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/skins/skin-black.css and recreate the skin on Bootswatch's Slate.

**Comment by ajuhost** [comment]
We need a dark theme from this incredible panel, you can launch a paid version. I'll be the first to buy.
