### ISSUE TITLE
Bad link to google-code-prettify in documentation/index.html

### ISSUE THREAD

**Issue by dbenaben** [almasaeed2010/AdminLTE#1391]
Hello,

I noted a bad link to google-code-prettify in AdminLTE-2.3.11/documentation/index.html  and AdminLTE-2.3.11/documentation/build/index.html :
`<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>`

Should be (https://github.com/google/code-prettify): 
`<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>`

I tried quickly a pull request without success so I create this issue... sorry.
Thanks for this very good template..

Best regards,

**Comment by almasaeed2010** [comment]
Documentation has been completely rewritten for v2.4. Thank you for the contribution!
