### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by REJack** [almasaeed2010/AdminLTE#1393]
Hey @almasaeed2010,

you pushed some v2.3.12 changes but you haven't created a release for this, 
could you create a v2.3.12 release?

regards REJack

**Comment by almasaeed2010** [comment]
We are releasing 2.4 soon 👍 I wasn't planning on releasing 2.3.12 since I am focusing on 2.4.

Thanks @REJack. We appreciate your contributions!

**Comment by REJack** [comment]
@almasaeed2010 No problem 👍 I can't wait for v2.4 (not as alpha)
