### ISSUE TITLE
Update changelog.md to 2.3.12

### ISSUE THREAD

**Issue by keserwang** [almasaeed2010/AdminLTE#1400]
The content of **changelog.md** is stoped at 2.3.7.
Please update it to 2.3.12.

**Comment by almasaeed2010** [comment]
You can find release notes for every release at the releases section. The cangelog will be removed in v2.4.

Thanks!

**Comment by almasaeed2010** [comment]
Link to releases: https://github.com/almasaeed2010/AdminLTE/releases
