### ISSUE TITLE
Close mobile sidebar by clicking on a menu item

### ISSUE THREAD

**Issue by juancol88** [almasaeed2010/AdminLTE#1402]
regards,

Thank you for your great work with this template.

I have a question, on a mobile device the side menu when it is clicked on a link of the menu does not close automatically and must go to click on the toggle button to close the side menu, there is a way to close this automatically When clicking.

**Comment by SebaSOFT** [comment]
The main problem is to distinguish the 'a' tags that are actually changing states in a single page application. For Angular 1.x I have all state links with the ui-sref attribute so I select using that:

`<script type="text/javascript" charset="utf-8" async defer>
$(function() { 
    $(document).on('click','.sidebar-menu li a[ui-sref]',function(e) {
        $($.AdminLTE.options.sidebarToggleSelector).click();        
    });
});
</script>`

**Comment by satmsc** [comment]
$("li.active").click(function() { 
  $($.AdminLTE.options.sidebarToggleSelector).click(); 
  
});
