### ISSUE TITLE
Issue on add more info to user panel sidebar

### ISSUE THREAD

**Issue by csmtcy** [almasaeed2010/AdminLTE#1404]
I have set the fix size for it to fit the content. Do you guys have better way to achieve this and prevent the issues i get? Thanks. 

![q1](https://cloud.githubusercontent.com/assets/4466554/23815169/d6320cb2-0621-11e7-86ff-28a41a2f8c0a.PNG)
![q2](https://cloud.githubusercontent.com/assets/4466554/23815170/d6323ba6-0621-11e7-9ebc-c652f7aca87c.PNG)

**Comment by REJack** [comment]
I would hide the infos on collapse like it in the preview.

Take the extra infos into the `.info` div inside of `.user-panel`.
````html
<div class="user-panel">
  <div class="pull-left image">
    <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
  </div>
  <div class="pull-left info">
    <p>Alexander Pierce</p>
    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
  </div>
</div>

```

**Comment by csmtcy** [comment]
Thanks a lot, it works perfectly ! :+1:
