### ISSUE TITLE
Increase the width of the container in layout top-nav

### ISSUE THREAD

**Issue by tzevgit** [almasaeed2010/AdminLTE#1405]
How can I increase the width of container in the top-nav layout? The default is 1170px.

I tried to add in a custom css:

.container
{
width: 1400px;
}

It worked but then it wasn't responsive. 

PS. I use adminLTE in laravel 5.4

**Comment by REJack** [comment]
There are 2 way for this:
1.  you can use the fluid-container, switch the class `container` with `container-fluid`
2. change the CSS with a media query like this:
```
@media (min-width: 1200px) {
  .container {
    width: 1400px;
  }
}
```

regards REJack

**Comment by tzevgit** [comment]
Thank you!

It worked with container-fluid.
