### ISSUE TITLE
Sidebar multilevel menu - possible to keep multiple open

### ISSUE THREAD

**Issue by jagyossarian** [almasaeed2010/AdminLTE#1406]
Hi,

The default functionality for the sidebar multi-level menus is to collapse automatically when another menu is clicked. Is it possible to keep multiple menus open and only close a menu if you click on that same menu again? What I have in mind is something like what's at the link below.

http://www.bootply.com/90JfjI2Q7n

Thanks for any help/suggestions you can provide

**Comment by jagyossarian** [comment]
Bump...anyone have any ideas?
Thanks

**Comment by lenamtl** [comment]
Hi, the first menu version was like that so maybe you can check older version and try to adapt.
I may need this feature too I'll let you know if I found out how.

**Comment by REJack** [comment]
Guys do you talk about the `.treeview`? If yes, check out #1476 i've added a modded `app(.min).js` for this.

**Comment by lenamtl** [comment]
What I'm looking for is concurrent opened treeview, I don't wan't all treeview always opened.
Like it was on the first menu version (AdminLte v1)

**Comment by REJack** [comment]
OMG I'm a idiot 😅 I miss unterstood @zivhsu but my modded javascript files should work for you, you can open multiple treeview and close them 😄, i rewrite now the inline JS in my post for @zivhsu 


You can donwload a modded v2.3.11 `app.js` or `app.min.js` from my [Dropbox](https://www.dropbox.com/sh/jio1vuk015rysve/AAAwTszc9Fy1-mzgkbytE-THa?dl=0).

**Comment by jagyossarian** [comment]
REJack, thanks man. That works beautifully and is exactly what I was looking for. Much appreciated.

**Comment by REJack** [comment]
No problem 😃 
i'll create a config-option for this and then i create PR for the next release (v2.4)

**Comment by almasaeed2010** [comment]
I am glad you found a solution! Thanks for the help @REJack. I do want to point out that this is already possible in v2.4-alpha. Also, it would be of great help if we can get reviews and testing startedfor v2.4. 

Thanks to all contributors!
