### ISSUE TITLE
the CSS link on the web don't work after downloaded

### ISSUE THREAD

**Issue by vedream** [almasaeed2010/AdminLTE#1408]
"href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">".this one ,i just want to  download it on my computer but it doesn't work ,only can be used by the link,how can i download it?I have try to downlad  font-awesome.min.css 4.7.0,but it still can't work

**Comment by REJack** [comment]
You need the font-files too you only copied the CSS file, 
download the fontawesome Font from http://fontawesome.io.

**Comment by vedream** [comment]
do work
