### ISSUE TITLE
side menu popup UI

### ISSUE THREAD

**Issue by BrendanDcruze** [almasaeed2010/AdminLTE#1413]
Hi, 
In the side menu popup list 
For some screen resolutions there is a gap between the list name and the list items.
You can zoom in or out while hovering over a side menu item to reproduce this issue.
Please check the below image.
![adminlte-err](https://cloud.githubusercontent.com/assets/25320723/24069096/bc884304-0bc5-11e7-9c38-a5d1b1cee61a.png)

**Comment by almasaeed2010** [comment]
I believe this issue is solved in v2.3.11 and v2.4.

Thanks for reporting!
