### ISSUE TITLE
How to use AdminLTE

### ISSUE THREAD

**Issue by hugoren** [almasaeed2010/AdminLTE#1431]
npn install 
grunt
but i can't visit web?
how and why?
thanks

**Comment by REJack** [comment]
@hugoren npm install & grunt is only for generate docs & etc before a new release.

Use one of these commands:
 - Bower: `bower install admin-lte`
 - npm: `npm install --save admin-lte`
 - Composer: `composer require "almasaeed2010/adminlte=~2.0"`

**Comment by hugoren** [comment]
@REJack 
     Thanks!
      I haved got adminlte through the git clone 
      My question is “How to run AdminLte”

**Comment by REJack** [comment]
There are serval HTML files in the repo they are you can run/open in a browser, but still remember AdminLTE is not an Application its a Control Panel Theme.

**Comment by hugoren** [comment]
Thank you!

**Comment by REJack** [comment]
Please close this issue if it's done 😄

**Comment by NikosEfthias** [comment]
are you supposed to both npm install and git clone the repo ? I cant figure out how to get it to run 
I tried parcel index.html to see errors of missing files
