### ISSUE TITLE
Overflow Problem (Design Issue)

### ISSUE THREAD

**Issue by humayoun007** [almasaeed2010/AdminLTE#1435]
I have been using AdminLTE for my small rest based java project. I don't know what went wrong even i don't change anything to AdminLTE.min.css but my dashboard page looks like in this  picture . any suggestion will highly appreciated. 
![problem](https://cloud.githubusercontent.com/assets/26954587/24814809/f2c46c92-1bf4-11e7-9581-fee9f1483c3e.jpg)

**Comment by ezra-obiwale** [comment]
Yeah, I noticed the same issue when using it. One little hack that seem to fix it is to resize the window programmatically on load.

For me, this solved it:

```js
$(document).ready(function(){
    $(window).resize();
});
```

**Comment by REJack** [comment]
This is happen if the app.js/app.min.js, bootstrap.min.js or jquery.js is not loaded in right order.

**Comment by humayoun007** [comment]
Thanks ezra-obiwale and REJack for important feedback. I have loaded js files like this order , first jquery , then bootstrap , after that angularjs and so on and finally app.min. I think this order is correct as per REJack comments. But i have seen , if my contents height is small like lower than 200-250px then this problems is still consists and more interestingly "content-wrapper" class "min-height" property is auto adjusted like 178px something like that. but when contents height is much above that then this problem disappears. also when debugging with chrome or firebug then this problem is gone. but without these it happens.

**Comment by almasaeed2010** [comment]
If this is still an issue, you may want to upgrade to v2.4 and test again. I am not sure if it'll solve the problem, but it is definitly worth upgrading if you are using AngularJS. 

If you are interested, upgrade guide can be found here https://adminlte.io/docs/2.4/upgrade-guide

Thanks!
