### ISSUE TITLE
Issue of Dashboard page on chrome

### ISSUE THREAD

**Issue by harryho** [almasaeed2010/AdminLTE#1437]
![image](https://cloud.githubusercontent.com/assets/2114456/24830035/13aa6386-1cc1-11e7-9791-b4c515cc5f24.png)

It is a very wired issue of Dashboard page on chrome. It only happens when I use two fingers to scroll the page on the touch pad. 

Comparing with normal UI below, we can see the setting panel (right side, Layout options) on above screenshot pushes the main content page to left, which squeezes the side bar ( left side ).

![adminlte 2 dashboard - google chrome_010](https://cloud.githubusercontent.com/assets/2114456/24941103/2a576daa-1f8b-11e7-9428-bcb6572c72f6.png)

**Comment by ezra-obiwale** [comment]
A little bit more information on the issue, aside the picture (which doesn't exactly say anything), would be nice.
