### ISSUE TITLE
how control-sidebar activate on startup and slide: false

### ISSUE THREAD

**Issue by asadiqbalse** [almasaeed2010/AdminLTE#1450]
I am trying to make control-sidebar activate on start-up. its working fine when i use control-sidebar-open.

the problem is, slide: false is not working when i use control-sidebar-open

I want to activate on page load with these two options.
1. control-sidebar activate
2. slide: false

**Comment by almasaeed2010** [comment]
Try adding the .control-sidebar-open class to the control sidebar itself instead of the body.
