### ISSUE TITLE
Content-Wrapper min-height

### ISSUE THREAD

**Issue by mattigins** [almasaeed2010/AdminLTE#1451]
It seems the Content-Wrapper min-height is calculated wrong for some pages.

It sometimes leaves an excess at the bottom of the page. How can i resolve this?

![Example](http://i.imgur.com/XxPeHr4.jpg)

**Comment by REJack** [comment]
Check your Browser console for errors.

**Comment by NestorAcevedo** [comment]
Good, I have the same issue and no errors are shown on browser console.

**Comment by annemacena** [comment]
Me too.

**Comment by p01ymath** [comment]
@MotionMagicRD , I tried your solution. It doesn't work. I tried all the solutions on the internet. Nothing seems to work for me :( .
