### ISSUE TITLE
How to hide the layout section completely 

### ISSUE THREAD

**Issue by rashidbilgrami** [almasaeed2010/AdminLTE#1456]
Hi, 
I have disabled the demo.js but still the layoutbar other option are disable check out the screenshot 

![image](https://cloud.githubusercontent.com/assets/1667625/25120809/3220157c-2428-11e7-9019-09866ff3b221.png)

**Comment by REJack** [comment]
You need to remove the whole `<aside class="control-sidebar control-sidebar-dark">` & `<div class="control-sidebar-bg"></div>` after the aside.

regards REJack

**Comment by almasaeed2010** [comment]
Hello @rashidbilgrami have you resolved your issue?

**Comment by rashidbilgrami** [comment]
Yes i resolved the issue by changes done in the CSS i think you can implement the REJack comments may be it will sort you issue
