### ISSUE TITLE
how to show sidebar in desktop, and layout-top-nav mode in mobile view?

### ISSUE THREAD

**Issue by edwinhuish** [almasaeed2010/AdminLTE#1460]
***How to show the sidebar mode in desktop browser as below:***
![image](https://cloud.githubusercontent.com/assets/5207925/25180566/0fce4948-2541-11e7-85fd-6399e278638e.png)

***And if it's mobile browser in the view like below?***
![image](https://cloud.githubusercontent.com/assets/5207925/25180613/44410602-2541-11e7-971f-2676595e7019.png)

**Comment by almasaeed2010** [comment]
Hello @edwinhuish 

Sorry for the very late response!

Unfortunately this is not supported at this time. We may implement this in the future, after releasing v3.

Thanks!

**Comment by edwinhuish** [comment]
I think it's no more choice, unless apply two different pages for mobile and desktop, or wait for the V3 version.
