### ISSUE TITLE
Problem with sidebar menu

### ISSUE THREAD

**Issue by tainanseneda** [almasaeed2010/AdminLTE#1461]
Hi. I noticed a possible problem when opening the sidebar menu on several levels. When I click to expand a second or third level, the menu closes automatically. The problem occurs only with Chrome.
I tried to record error playback, but the same does not repeat when we are in screen capture mode
Thank you. Sorry my bad english.

**Comment by tainanseneda** [comment]
Someone?

**Comment by REJack** [comment]
Does it happens on the [Preview](https://almsaeedstudio.com/themes/AdminLTE/index2.html) too?

**Comment by tainanseneda** [comment]
Yes.

**Comment by tainanseneda** [comment]
Yes.

**Comment by almasaeed2010** [comment]
It doesn't seem to happen on my browser (chrome). Could you please elaborate or provide screenshots of the issue?

**Comment by tainanseneda** [comment]
Yes, I'm going to shoot with my cell phone. One minute

**Comment by tainanseneda** [comment]
http://imgur.com/OZMps2j

**Comment by REJack** [comment]
I can't reproduce this with my fresh installed Chrome v58 , which version of Chrome you use?
Maybe some addons/plugins create this behavior try safe-mode too.

**Comment by tainanseneda** [comment]
Thanks, but I've tried it in safe mode and disable addons/plugins. My version is 57.0.2987.133, 64 bits.

**Comment by tainanseneda** [comment]
I updated my chrome (v58) and continued with the same problem

**Comment by almasaeed2010** [comment]
That is odd because it is not happening on any of my browsers. This could mean a cache issue, which I have encountered several times. Could you clear the cache and try again?

**Comment by tainanseneda** [comment]
The problem does not occur in FF, EDGE, OPERA NEON.. 
I cleared my cache and continued with the same problem. Both on my desktop and on my notebook and the other computers I'm on now.
I can not understand why. I already reported it to Google too

**Comment by almasaeed2010** [comment]
Unfortunately, we can't fix an issue that we can't reproduce. Have you managed to get this working on your browser?

**Comment by tainanseneda** [comment]
Sorry, i don't.

**Comment by lenamtl** [comment]
Hi, 
Could you post the code of this part of the menu..
