### ISSUE TITLE
Data table is not responsive 

### ISSUE THREAD

**Issue by vanduy95** [almasaeed2010/AdminLTE#1465]
Responsive Bootstrap Datatable not collapsing columns at the correct point
This is desktop browser
![image](https://cloud.githubusercontent.com/assets/22407434/25270156/c3e0d4b4-26a9-11e7-8fc5-e5ad30e7a927.png)
this is smartphone size 
![image](https://cloud.githubusercontent.com/assets/22407434/25270264/2cfdd6a4-26aa-11e7-8a73-d95eec033404.png)

**Comment by REJack** [comment]
You need to use https://datatables.net/extensions/responsive/
