### ISSUE TITLE
Treeview menus do not collapse when a user clicks on a non-tree view menu item

### ISSUE THREAD

**Issue by mailok** [almasaeed2010/AdminLTE#1468]
1-Click to expand a tree view menu on the side bar.
2-Click a menu item that is not a tree view (such as a regular menu item).

My application is single page. So when a user visits a link only the content area of the page is refreshed. This differs from your multi-page example. The difference is the links on your pages actually cause page refreshes / reloads whereas my app only alters what's inside the content area. The bug doesn't exist in your preview because new requests are sent and the entire menu is reloaded whereas my menu just continues to exist.
development my application in angular 4, please, some help!!

**Comment by lenamtl** [comment]
Hi,
Do you use the menu link with anchors div id ?
Could you check using chrome dev tool  right click + inspect and check the console if there is an error.
Do you have a live link?

**Comment by mailok** [comment]
sorry, I do not have a live link. but this is my code, in the attached
![captura](https://cloud.githubusercontent.com/assets/3769277/25448727/6f76fc46-2a87-11e7-8fe3-2e88bf71ea56.PNG)
:


in this example, of course, made in Angular, dynamically build menu, I have access to an array
that containing a model which have information about the menu, there are some that contain a treeview-menu and other is a simple

**Comment by almasaeed2010** [comment]
Are you saying that menus are collapsing when they shouldn't after a click?

**Comment by mailok** [comment]
I mean when I click on a <li> tag, which is not a treeview, the others treeview do not collapse. do you understand?

**Comment by almasaeed2010** [comment]
That's intended behavior. Only li tags with `treeview` class are listened to. Otherwise, they are not considered part of the treeview menu. To fix your issue, simply add the treeview class to the li element.

Thanks!
