### ISSUE TITLE
Hide in listing but show in View Row?

### ISSUE THREAD

**Issue by sjking85** [almasaeed2010/AdminLTE#1469]
Hi, I wonder if it's a bug or a mod I can make to the script...

Essentially I have a lot of columns in one table that I don't necessarily need to see on the "Overview" page, but I'd like to see them on the "View Row" page.

Is it possible to make a change to the code so I can do this?

**Comment by lenamtl** [comment]
Hi I'm not sure what you need... but you can use datatables for your tables and there is a plenty of settings and plugins to play with https://datatables.net/

**Comment by sjking85** [comment]
Basically, I want all fields to return on the "View Row" page, regardless of what is selected as "Hide in listing".

**Comment by lenamtl** [comment]
Hi could you point me the view row page you are referencing?
