### ISSUE TITLE
What built files do I need?

### ISSUE THREAD

**Issue by mhulse** [almasaeed2010/AdminLTE#1472]
I would just like to use the compiled assets.

I can't seem to find info that says "You will need file X and Y".

If I were to make an educated guess (using `starter.html`):

```text
AdminLTE-2.3.11/
- plugins/*
- dist/js/app.js
- img/icons.png
- css/AdminLTE.css
```

And a skin of your choosing.

Did I miss anything?

**Comment by almasaeed2010** [comment]
@mhulse you also need jQuery and Bootstrap:

```shell
# stylesheets
bootstrap.css
adminlte.css
adminlte-skin.css

#scripts
jquery.js
bootstrap.js
app.js
# any other plugins
```

**Comment by mhulse** [comment]
Thank you! I really appreciate it.
