### ISSUE TITLE
关于.content-wrapper高度的问题

### ISSUE THREAD

**Issue by woaiwhr001** [almasaeed2010/AdminLTE#1473]
首先，非常感谢这个项目，感谢作者以及贡献的人。
我怕翻译的不准确所以直接用中文来写，希望不要介意。
我在使用的过程中发现在缩小浏览器后再最大化浏览器会出现.content-wrapper高度不准确的问题，在fixed模式下没有问题，但是普通模式下（starter.html）会有问题，所以提出来希望给有疑惑的人一些帮助。
![qq 20170429164502](https://cloud.githubusercontent.com/assets/20886053/25554298/287164ea-2cfc-11e7-9af7-5a5d7d20f461.png)
我在源码发现
首先
$.AdminLTE.layout.activate()中
$(window, ".wrapper")，或许jquery只能监听到window的resize而不能监听到html元素的resize，这里不知道算不算是一个错误。
其次这个高度的bug可能是由于动画没有执行完毕而先获得了高度造成的，所以，我的解决办法是在
$.AdminLTE.layout.activate()函数的末尾加上
$('.navbar-static-top').on('bsTransitionEnd', function () {
    _this.fix();
    _this.fixSidebar();
});
希望能给一些人带来帮助，再次感谢这个项目。

**Comment by almasaeed2010** [comment]
Although I don't understand Chinese, my guess is that the issue is with the excess under the footer. Hopefully, this issue will be fixed in v2.4.

You can test the newer version by downloading the Alpa from here: https://github.com/almasaeed2010/AdminLTE/releases/tag/v2.4.0-alpha
