### ISSUE TITLE
Vertical Scrolling Box

### ISSUE THREAD

**Issue by superciccio14** [almasaeed2010/AdminLTE#1474]
Hello,

is there a way to make a box (https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#component-box) vertically scrollable with a fixed height?

**Comment by REJack** [comment]
Sure that's not hard 😃

the easiest way (css only) is give the `box-body` a id and create a declaration or add inline style with:
`height: 600px; overflow-y: scroll;` (change 600px to your desired height).
If you want to hide the scrollbars replace `overflow-y: scroll;` with `overflow: hidden;`.

regards REJack

**Comment by boedyirh** [comment]
Thanks. it does work.
When I scroll the table, the table header also scroll respectively. Is it possible to make the table header fixed-position?
