### ISSUE TITLE
how to do to treeview-menu always open?

### ISSUE THREAD

**Issue by ZivHsu** [almasaeed2010/AdminLTE#1476]
I want to my treeview-menu always open,

![1493881608383](https://cloud.githubusercontent.com/assets/19678859/25693955/a466b47a-30de-11e7-841f-b672b768ddfe.jpg)

But when user click it will close or open once and does not affect other  treeview-menu

like this

![1493881586487](https://cloud.githubusercontent.com/assets/19678859/25693958/a9a83fd0-30de-11e7-9298-bc2a15942cc0.jpg)

How to do it?

**Comment by REJack** [comment]
For this you need to modify the app(.min).js.

**Comment by ZivHsu** [comment]
Hi @REJack  

I try to modify the app(.min).js

But i just no have idea where is remove other treeview-menu when it open?

**Comment by REJack** [comment]
It should look like this:

```js
  $.AdminLTE.tree = function (menu) {
    var _this = this;
    var animationSpeed = $.AdminLTE.options.animationSpeed;
    $(document).off('click', menu + ' li a')
      .on('click', menu + ' li a', function (e) {
        //Get the clicked link and the next element
        var $this = $(this);
        var checkElement = $this.next();

        //Check if the next element is a menu and is visible
        if ((checkElement.is('.treeview-menu')) && (checkElement.is(':visible')) && (!$('body').hasClass('sidebar-collapse'))) {
          //Close the menu
          checkElement.slideUp(animationSpeed, function () {
            checkElement.removeClass('menu-open');
            //Fix the layout in case the sidebar stretches over the height of the window
            //_this.layout.fix();
          });
          checkElement.parent("li").removeClass("active");
        }
        //If the menu is not visible
        else if ((checkElement.is('.treeview-menu')) && (!checkElement.is(':visible'))) {
          //Get the parent menu
          var parent = $this.parents('ul').first();
          //Get the parent li
          var parent_li = $this.parent("li");

          //Open the target menu and add the menu-open class
          checkElement.slideDown(animationSpeed, function () {
            //Add the class active to the parent li
            checkElement.addClass('menu-open');
            parent_li.addClass('active');
            //Fix the layout in case the sidebar stretches over the height of the window
            _this.layout.fix();
          });
        }
        //if this isn't a link, prevent the page from being redirected
        if (checkElement.is('.treeview-menu')) {
          e.preventDefault();
        }
      });
  };
```

This is the code form the `app.js` not `app.min.js`

You can donwload a modded v2.3.11 `app.js` or `app.min.js` from my [Dropbox](https://www.dropbox.com/sh/jio1vuk015rysve/AAAwTszc9Fy1-mzgkbytE-THa?dl=0).

**Comment by REJack** [comment]
Sorry miss i understood you before :/ but now it should work for you 😄 

```js
  $.AdminLTE.tree = function (menu) {
    var _this = this;
    var animationSpeed = $.AdminLTE.options.animationSpeed;
    $(document).off('click', menu + ' li a')
      .on('click', menu + ' li a', function (e) {
        //Get the clicked link and the next element
        var $this = $(this);
        var checkElement = $this.next();

        //If the menu is not visible open it
        if ((checkElement.is('.treeview-menu')) && (!checkElement.is(':visible'))) {
          //Get the parent menu
          var parent = $this.parents('ul').first();
          //Get the parent li
          var parent_li = $this.parent("li");

          //Open the target menu and add the menu-open class
          checkElement.slideDown(animationSpeed, function () {
            //Add the class active to the parent li
            checkElement.addClass('menu-open');
            parent_li.addClass('active');
            //Fix the layout in case the sidebar stretches over the height of the window
            _this.layout.fix();
          });
        }
        //if this isn't a link, prevent the page from being redirected
        if (checkElement.is('.treeview-menu')) {
          e.preventDefault();
        }
      });
  };
```

This is the code form the `app.js` not `app.min.js`, you need to replace the whole AdminLTE.tree function.

**Comment by ZivHsu** [comment]
Hi @REJack 

still can not work

**Comment by ZivHsu** [comment]
Hi @REJack 

It's work in your dropbox.

Thank you very much~

**Comment by ZivHsu** [comment]
Hi @REJack 

I found the wrong...

when I use mobile view it will no response....

**Comment by ZivHsu** [comment]
Hi @REJack 

![Uploading 1494227262302.jpg…]()

when I use mobile view the first time the will no response in treeview-menu

but when i close and open again it was work...

did you have any idea?

**Comment by almasaeed2010** [comment]
This is feature is now supported (needs testing) in AdminLTE v2.4. You may upgrade by following this guide: https://adminlte.io/docs/2.4/upgrade-guide

If the issue persists or if you find different problems, please open a new issue. 

Thanks!

**Comment by yjarosz** [comment]
Following the upgrade guide + adding `data-api="tree" data-accordion=0` to my sidebar menu worked perfectly =>  [doc](https://adminlte.io/docs/2.4/js-tree).

**Comment by arnuschky** [comment]
Weird - doesn't work for me. I upgraded to v2.4 following the upgrade doc. This is my code:

```html
          <ul class="sidebar-menu" data-widget="tree" data-api="tree" data-accordion=0>
            <li class="treeview">
              <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
                <span class="pull-right-container">
                   <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#">Link in level 2</a></li>
                <li><a href="#">Link in level 2</a></li>
              </ul>
            </li>
          </ul>
```

What works fine is that I can open multiple submenus at once. However, I want to have this menu open on pageload. Any idea how I can do that?

**Comment by namvvo** [comment]
actually, all you need to do is just adjust the adminlte-2.x.css a bit.

.sidebar-menu .treeview-menu {
        /*display: none;*/     // will show all sub menus
        list-style: none;
        padding: 0;
        margin: 0;
        padding-left: 5px;
    }

**Comment by arnuschky** [comment]
Thanks! This worked.

I couldn't find this section in the adminlte css file, so I simply added `style="display: block"` to my html element/custom css. This is a nicer fix in any case, as I can configure this per element.

**Comment by deshario** [comment]
I am using in yii2 ... how to open it always ?

>  [
                            'label' => 'Tools',
                            'icon' => 'cog',
                            'url' => '#',
                            'items' => [
                                ['label' => 'Verifications', 'icon' => 'qrcode', 'url' => ['donation-verified/index'],],
                                ['label' => 'Profile', 'icon' => 'user-o', 'url' => ['user/profile'] ],
                                ['label' => 'Decryption', 'icon' => 'user-o', 'url' => ['user/hashing'] ],
                                ['label' => 'Logout', 'url' => ['site/logout'], 'template' => '<a href="{url}" data-method="post"><i class="fa fa-sign-out"></i>{label}</a>'],
                            ],
                        ]

**Comment by oesah** [comment]
You can also just use  `<li class="treeview active">` and it will be open by default.

**Comment by takuro-kira** [comment]
helpful #2080
dist/js/adminlte.js:300
now accordion default is true
The latest version is 3.2 or 4β, but my environment is limited.
This worked in 3.0.

```
<ul class="nav nav-pills nav-sidebar nav-child-indent flex-column" data-widget="treeview" role="menu" data-accordion=false>
```
become keeping open.

This setting very important but I couldn't find any documentation.

When I tried to modify 'menu-open' from outside without this setting, it got weird and I had a hard time.

In order to preserve data during transitions, use localstorage, etc. is required.

**Comment by takuro-kira** [comment]
localStorage sample
```
<script>
$('li.has-treeview').each((i, el) => {
    const jqo = $(el)
    jqo.children('a').on('click', (ev) => {
        const open = jqo.hasClass('menu-open')
        const openMenusSt = localStorage.getItem('openMenus') ?? '[]'
        let openMenus = JSON.parse(openMenusSt)
        if (open) {
            openMenus = openMenus.filter(i => i != jqo.attr('id'))
        } else {
            openMenus.push(jqo.attr('id'))
        }
        localStorage.setItem('openMenus', JSON.stringify(openMenus))
    })
})
const openMenu = () => {
    const openMenusSt = localStorage.getItem('openMenus') ?? '[]'
    const openMenus = JSON.parse(openMenusSt)
    openMenus.forEach(e => {
        $(`#${e}`).addClass('menu-open')
    })
}
$(() => {
    openMenu()
})
</script>
```
