### ISSUE TITLE
Advanced Datatables - slow rendering

### ISSUE THREAD

**Issue by Zolky88** [almasaeed2010/AdminLTE#1477]
Hi,

I use advanced Datatables with MySQL database with more than 6000 records. Everything works but the problem is with rendering. It's very slow because all rows are loaded and rendered at once and the pagination is loaded after.

Any ideas for solution?

Thank you.

**Comment by vasylenkomykola** [comment]
Hi,

You can load part of data only for one page. For make this solution you need changing API and update JS code if your table doesn't support it. I do it this way.

For request: 
a) limit - number row in page
b) offset - number row for skip (limit * current page)
c) order - column name for order (Example: for ASC is order=prcie or for DESC is order=-price)
d) plus other params for filtering.

For response:
a) count - count row in table (Example: SELECT count(*) FROM some_table WHERE /* + filter if necessary*/;)
b) rows - array of rows (Example: SELECT * FROM some_table WHERE /* + the same filter if exist */ ORDER BY some_column ASC|DESC LIMIT $limit OFFSET $offset)

For pagination:
a) Set count page to bootspap pagination
b) Set current page if necessary

P.S.
Sorry about my English

**Comment by REJack** [comment]
Check out [this](https://datatables.net/examples/data_sources/server_side.html), DataTables work much faster with serverside processing.

**Comment by fraktal12** [comment]
Hi,
I had this problem also. It come from the fact that you render table after each row added to the table. You need to render the table once after all rows are added.
Here is the solution:
http://stackoverflow.com/questions/16923784/performance-issues-with-rendering-in-datatables

**Comment by zomby22** [comment]
I coded datatable using server side processing with ajax, in two different version, even try the aspjson code, and the speed is still an issue for me. If I limit my query data to 1000 entries, its fairly quick, takes about 5second, but at only 8,000 entries, it takes a full 2 minutes to load. This is too long of a wait.  If I refresh the page say 10 times, I might get an ajax error once. Not sure why is does that cause 95% of the time, it works, except its just slow. My table is use to load data (that contains English and French characters, html tags, etc..), pagination, searching, filters. I could never get it to render it faster. Any tips would be appreciated:

`<table id="thedatatable" class="table table-hover table-stripped wb-tables small" data-wb-tables='{"processing": true,
                "serverside": true,
                "deferRender": true,
                "ajax": {
                	"url": "loadata.asp"
                },
                "columnDefs": [ {"targets": 0, "searchable": true, "orderable": true, "width": "3%"},
                {"targets": 1, "searchable": true, "orderable": true, "width": "40%", "orderDataType": "dom-text"},
                {"targets": 2, "searchable": true, "orderable": true, "width": "3%"},
                {"targets": 3, "searchable": true, "orderable": true, "width": "40%", "orderDataType": "dom-text"},
                {"targets": 4, "searchable": false, "orderable": true, "width": "6%", "className": "nowrap"},
                {"targets": 5, "searchable": false, "orderable": false, "width": "2%", "className": "nowrap"},
                {"targets": 6, "searchable": false, "orderable": false, "width": "1%", "className": "center"}],
                "bProcessing": false,
                "bStateSave": false,
                "bSortClasses": false,
                "order": [[1, "asc"]],
                "iDisplayLength": 100,
                "scroller": false, 
                "oLanguage": {
                    "sLoadingRecords": "Please wait - loading...",
                    "sSearch": "Search:",
                    "sZeroRecords": "No records to display"
                    }}'>`
