### ISSUE TITLE
Something about direct chat

### ISSUE THREAD

**Issue by dcy** [almasaeed2010/AdminLTE#1481]
Hi!
How can i use direct chat like [CHAT PAGE](https://wrappixel.com/ampleadmin/ampleadmin-html/ampleadmin-minimal/chat.html)?

**Comment by REJack** [comment]
Look at the [preview](https://almsaeedstudio.com/themes/AdminLTE/index2.html) there is one under `Visitors Report`.

**Comment by almasaeed2010** [comment]
Hi @dcy 

You are gonna need to do multiple customizations to achieve. Unfortunately, we will not be able to implement this feature at this time since we are working on advancing to AdminLTE v3.

Thanks for the suggestion! We'll keep it in mind for a future version.
