### ISSUE TITLE
Active menu item with multi level submenus

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#1482]
Hi, I'm using this code to add active class depending of the page.

This is working ok except for multi level submenus any clue how to fix this

```

/** add active class and stay opened when selected */
var url = window.location;

// for sidebar menu entirely but not cover treeview
$('ul.sidebar-menu a').filter(function() {
	 return this.href == url;
}).parent().addClass('active');

// for treeview
$('ul.treeview-menu a').filter(function() {
	 return this.href == url;
}).closest('.treeview').addClass('active');

```
 
```

<li class="treeview">
	<a href="#">
	      <i class="fa fa-gears"></i>
	      <span>Settings</span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
		<ul class="treeview-menu">
			<li>
				<a href="#">
				      <i class="fa fa-bars"></i>
					Specials Settings
				</a>
				<ul class="treeview-menu">
					<li><a href="setting1.php">Setting 1</a></li>
				</ul>
			</li>
		</ul>
</li>
```

**Comment by lenamtl** [comment]
I have  fixed it by replacing the latest line.
I have not test all possibles case so if there is an issue with a case let me know

/** add active class and stay opened when selected */
var url = window.location;

// for sidebar menu entirely but not cover treeview
$('ul.sidebar-menu a').filter(function() {
	 return this.href == url;
}).parent().addClass('active');

// for treeview
$('ul.treeview-menu a').filter(function() {
	 return this.href == url;
.parentsUntil( $( "ul.level-1" ) ).addClass('active');

**Comment by REJack** [comment]
1. nice script but it is not valid 
2. where you took the class `ul.level-1` from? 😄 AdminLTE doesn't use something like this. 

i fixed it to get it work on AdminLTE
```js
/** add active class and stay opened when selected */
var url = window.location;

// for sidebar menu entirely but not cover treeview
$('ul.sidebar-menu a').filter(function() {
	 return this.href == url;
}).parent().addClass('active');

// for treeview
$('ul.treeview-menu a').filter(function() {
	 return this.href == url;
}).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
```

i tested all variations till level 3 (all items) 😃

**Comment by lenamtl** [comment]
Thanks, I didn't realized as it was working ... :)

**Comment by lenamtl** [comment]
Note:
The only problem with this solution is that only one page per menu / submenu item will work  which is espected but I have a case that a page is opened by a click of a button on a page (not from the menu)
when this occurred I loose active on the menu which is espected.
So I will need to use a PHP solution instead of JS solution to add active to the menu depending of the URL so I can check more than one url... 

This is maybe possible with JS too I will do some test and let you know.

**Comment by REJack** [comment]
It's not hard JS, you can use hash for this.

**Comment by amsharma9** [comment]
Thanks for sharing this code @lenamtl. The modified code by @REJack works well. There are two issues though:
1. There is flicker when I click on a new sub-menu. I think it closes & reopens the whole sub-menu.
2. How can I keep the left sidebar menu in its current state all the time (sub-menu open and active highlighted) till the user clicks something else on the menu. The moment I  click something in the content area, the menu collapses. Were you able to get it working when a page is opened using a button etc @lenamtl.

Thanks

**Comment by legreco** [comment]
@amsharma9 Same problem here. The flicker is visually annoying
I have noticed that there is no flicker on official website so i suppose they find a way to manage that
https://adminlte.io/themes/AdminLTE/

**Comment by amsharma9** [comment]
I think the reason official Live Preview website & document website doesn't have this issue is that it is made of HTML & Javascript. The left sidebar HTML code doesn't get refreshed. I use a MVC based PHP framework, that probably refreshes the whole page. I could be wrong in my understanding. I requested @almasaeed2010 to share the code of the website in #1661 but they haven't yet. He just pointed me to AdminLTE code, which I obviously have. I studied the website code using page sources of official website but didn't find any javascript to avoid the flicker.

**Comment by legreco** [comment]
I think they managed it in the backend see
https://github.com/almasaeed2010/AdminLTE/issues/315

almasaeed2010 commented ;
Hello,
Although this might sound like a front-end job but it isn't. This should be implement as a back-end mechanism. This is because when the user loads a new page, the default setting will be applied and javascript will deal with the saved state after the page loads. Thus, causing unwanted transitions and animations (i.e., the sidebar would appear in its regular state for a moment before javascript applies the collapsed mode). This could be a front-end job if we were using Ajax or AngularJS since the only change is in the content page not the sidebar nor the navbar

**Comment by lenamtl** [comment]
Hi @amsharma9 

1- I'm using a older version with PHP and lot of custom code, so maybe this is the reason I don't have the flicker issue.

2- Yes because the code is looking for the page url
`var url = window.location;`
 this is a problem if the page is not in the menu or submenu link
 (that can be a edit page for example) we loose the menu active class when this occurred.

The only way I have found to fix this is to use PHP check page then add the active class to a menu,
this way you can have a menu active it for any page (different pages can set a menu active not only one)... 

If there is another way using Javascript I will be happy to test it...

**Comment by apexcipher** [comment]
#### I have fixed it now it will show only matching url as active rest as inactive

 #####  add active class and stay opened when selected 

            var url = window.location;
            // for sidebar menu entirely but not cover treeview
            $('ul.sidebar-menu a').filter(function() {
                return this.href != url;
            }).parent().removeClass('active');

            // for sidebar menu entirely but not cover treeview
            $('ul.sidebar-menu a').filter(function() {
                return this.href == url;
            }).parent().addClass('active');

            // for treeview
            $('ul.treeview-menu a').filter(function() {
                return this.href == url;
            }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');

**Comment by jackthailand** [comment]
Thank you REJack.

**Comment by lenamtl** [comment]
Hi, 

I just test your code modification and I don't see any difference, on my install it's acting the same ....
Anyhow the important is that you have fixed your problem :)

**Comment by ashikjs** [comment]
**I was face same issue and i solve it by this solution**  

```
      $('#mainMenu ul li').find('a').each(function () {
            if (document.location.href == $(this).attr('href')) {
                $(this).parents().addClass("active");
                $(this).addClass("active");
                // add class as you need ul or li or a 
            }
        });
```

**Comment by NGjata** [comment]
To make it perfect you need to add:  $(this).parents('li').addClass('menu-open'); as last line ;)

**Comment by NGjata** [comment]
I resolved it like this: 


```
$('.sidebar-menu ul li').find('a').each(function () {
            var link = new RegExp($(this).attr('href')); //Check if some menu compares inside your the browsers link
            if (link.test(document.location.href)) {
                if(!$(this).parents().hasClass('active')){
                    $(this).parents('li').addClass('menu-open');
                    $(this).parents().addClass("active");
                    $(this).addClass("active"); //Add this too
                }
            }
        });
```

**Comment by SumonT2** [comment]
Hope following code will help. 
Please someone do further improvement.

      var url = window.location;
        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
            return this.href != url;
        }).parent().removeClass('active');

        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
            return this.href == url;
        }).parent().addClass('active');

        // for treeview
        $('ul.treeview-menu a').filter(function() {
            return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');

        // for sub-menu hidden fix. 
        $('li.treeview.active').click(function(){

        $('ul>li').css('display','block');
    });

**Comment by SumonT2** [comment]
Hope this will solve everyone's problem. I think it could be better. Please someone make this more bug-less.
 
     var url = window.location;
        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
            return this.href != url;
        }).parent().removeClass('active');

        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
            return this.href == url;
        }).parent().addClass('active');

        // for treeview
        $('ul.treeview-menu a').filter(function() {
            return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');

        // for sub-menu hidden fix.
        $('li.treeview.active').click(function(){
        	$(this).find('ul.treeview-menu.active>li.treeview.active').css('display','block');
    });

**Comment by SumonT2** [comment]
Use `adminlte.js` and comment line no `1077`
use following code at the end....

<pre>var url = window.location;
        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
            return this.href == url;
        }).parent().addClass('active');

        // for treeview
        $('ul.treeview-menu a').filter(function() {
            return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');

        // for  hidden sub-menu fix
            $('li.treeview.active').click(function(){
          $(this).find('ul.treeview-menu.active>li.treeview.active').removeAttr('style');
    });
</pre>

**Comment by SumonT2** [comment]
Use `adminlte.js` and comment line no `1077`
![Image of Commented Code](https://techsflow.com/Alte/Capture.PNG)

After that,
use following code at the end....

```javascript
var url = window.location;
        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
            return this.href == url;
        }).parent().addClass('active');

        // for treeview
        $('ul.treeview-menu a').filter(function() {
            return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');

        // for  hidden sub-menu fix
            $('li.treeview.active').click(function(){
          $(this).find('ul.treeview-menu.active>li.treeview.active').removeAttr('style');
    });
```

__Don't forget to use  `adminlte.js` in your html__

**Comment by cikal** [comment]
@NGjata .. your script not work in single menu, than i add more line for works in bot single menu and multiple menu. With this i resolved my menu..

```javascript
// ----------------------------------------------------------------
var a = window.location.pathname;
$('.sidebar-menu > li > a[href="http://localhost' + a + '"').parent().addClass("active");
// ----------------------------------------------------------------

$('.sidebar-menu ul li').find('a').each(function () {
            var link = new RegExp($(this).attr('href')); //Check if some menu compares inside your the browsers link
            if (link.test(document.location.href)) {
                if(!$(this).parents().hasClass('active')){
                    $(this).parents('li').addClass('menu-open');
                    $(this).parents().addClass("active");
                    $(this).addClass("active"); //Add this too
                }
            }
        });
```

**Comment by lenamtl** [comment]
Hi @cikal could you explain your script please

**Comment by Agimovel** [comment]
How about sidebar and topbar? (In case you put most used itens at top):

This code is just an complement from a previous solution in this page

```
/** add active class and stay opened when selected */
  var url = window.location;

  // for sidebar menu entirely but not cover treeview
  $('ul.sidebar-menu a').filter(function() {
     return this.href == url;
  }).parent().addClass('active');
  //Top bar
  $('ul.navbar-nav a').filter(function() {
     return this.href == url;
  }).parent().addClass('active');

  // for treeview
  $('ul.treeview-menu a').filter(function() {
     return this.href == url;
  }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
```

**Comment by AlifAbhiesa** [comment]
Thank you @Agimovel your code is workly perfect !

**Comment by ashikjs** [comment]
@Ali12K  You can follow my solution

**Comment by NasirHussainAbbasi** [comment]
hello
![Screenshot_1](https://user-images.githubusercontent.com/54266172/63652994-725dc500-c780-11e9-9fe4-a5c6e4c1bf56.png)
 their i ma facing this issue please help me how can i handle this solution.
the issue is when the first time page load the bottom menu still active

**Comment by NGjata** [comment]
Can you post the code?

**Comment by NasirHussainAbbasi** [comment]
<script>
        var url = window.location;

       
        $('ul.main-navigation-menu a').filter(function() {
            return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
    </script>

**Comment by NasirHussainAbbasi** [comment]
just parentsUntill menu working on my navigation 
my navigation code is
 <ul class="main-navigation-menu perfect-scrollbar ps ps--active-y" style="height:375px"id="myTable" >
                <li class="active">
                    <a href="@Url.Action("index", "home", new { @area = "" })">
                        <div class="item-content">
                            <div class="item-media"><i class="ti-home"></i></div>
                            <div class="item-inner"><span class="title">Home</span></div>
                        </div>
                    </a>
                </li>

                @{
                    //for 3 levels
                    int? grandParentId = 0, parentId = 0;
                    //var moduleID = Convert.ToInt32(Session["MODULEID"]);

                    //var menus = Common.GetMenus(Convert.ToInt32(Session["USERID"])).Where(m => m.ModuleID == moduleID).ToList();
                    var menus = Common.GetMenus(Convert.ToInt32(Session["USERID"])).ToList();

                    var grandParentMenu = menus.Where(m => m.ParentMenuID == null).ToList();
                    foreach (var grandParentRow in grandParentMenu)
                    {
                        grandParentId = grandParentRow.MenuID;
                        var parentMenu = menus.Where(m => m.ParentMenuID == grandParentId).ToList();

                        <li>
                            <a href="javascript:void(0)">
                                <div class="item-content">
                                    <div class="item-media"><i class="@grandParentRow.Icon"></i></div>
                                    <div class="item-inner"><span class="title">@grandParentRow.MenuName </span><i class="icon-arrow"></i></div>
                                </div>
                            </a>
                            <ul class="sub-menu">
                                @foreach (var parentRow in parentMenu)
                                {
                                    parentId = parentRow.MenuID;
                                    var menu = menus.Where(m => m.ParentMenuID == parentId).ToList();


                                    if (menu.Count() == 0)
                                    {
                                        <li><a href="@Url.Action(parentRow.Action, parentRow.Controller, new { @area = parentRow.Area })"><span class="title">@parentRow.MenuName</span></a></li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a href="javascript:void(0);"><span>@parentRow.MenuName</span> <i class="icon-arrow"></i></a>
                                            <ul class="sub-menu ">
                                                @foreach (var mnu in menu)
                                                {
                                                    @*<li><a href="@Url.Action(mnu.Action, mnu.Controller, new { @area = mnu.Area })">@mnu.MenuName</a></li>*@
                                                    <li><a href="/@mnu.Area/@mnu.Controller/@mnu.Action">@mnu.MenuName</a></li>
                                                }
                                            </ul>
                                        </li>
                                    }
                                }
                            </ul>
                        </li>
                    }
                }
              
            </ul>

**Comment by Ecstacies** [comment]
Your code helped a lot @apexcipher  !!!!

**Comment by gmkhussain** [comment]
**NOTE:** This code for new **AdminLTE 3** dev with bootstrap 4


```js
var url = window.location;
const allLinks = document.querySelectorAll('.nav-item a');
const currentLink = [...allLinks].filter(e => {
  return e.href == url;
});

currentLink[0].classList.add("active")
currentLink[0].closest(".nav-treeview").style.display="block";
currentLink[0].closest(".has-treeview").classList.add("active");
```

**Comment by SumonT2** [comment]
I have added `menu-open` class to @apexcipher 's solution
use following for better result. (not for **AdminLTE 3**)

```javascript
var url = window.location;
// for sidebar menu entirely but not cover treeview
$('ul.sidebar-menu a').filter(function() {
      return this.href != url;
}).parent().removeClass('active');

// for sidebar menu entirely but not cover treeview
$('ul.sidebar-menu a').filter(function() {
      return this.href == url;
}).parent().addClass('active');

// for treeview
$('ul.treeview-menu a').filter(function() {
      return this.href == url;
}).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active menu-open');
```

**Comment by devideots** [comment]
> **NOTE:** This code for new **AdminLTE 3** dev with bootstrap 4
> 
> ```js
> var url = window.location;
> const allLinks = document.querySelectorAll('.nav-item a');
> const currentLink = [...allLinks].filter(e => {
>   return e.href == url;
> });
> 
> currentLink[0].classList.add("active")
> currentLink[0].closest(".nav-treeview").style.display="block";
> currentLink[0].closest(".has-treeview").classList.add("active");
> ```

AdminLTE-3.0.1
there is a slight modification of @gmkhussain  to make all add class active work in my project thanks you


`var url = window.location;`
`const allLinks = document.querySelectorAll('.nav-item a');`
`const currentLink = [...allLinks].filter(e => {`
`return e.href == url;`
`});`

`currentLink[0].classList.add("active");`
`currentLink[0].closest(".nav-treeview").style.display = "block ";`
`currentLink[0].closest(".has-treeview").classList.add("menu-open");`
`$('.menu-open').find('a').each(function() {`
`    if (!$(this).parents().hasClass('active')) {`
`        $(this).parents().addClass("active");`
`        $(this).addClass("active");`
`    }`
`});`

![image](https://user-images.githubusercontent.com/44359409/70866712-96e3e400-1f9f-11ea-9d50-543159496613.png)

**Comment by devideots** [comment]
```
var url = window.location;
const allLinks = document.querySelectorAll('.nav-item a');
const currentLink = [...allLinks].filter(e => {
    return e.href == url;
});

currentLink[0].classList.add("active");
currentLink[0].closest(".nav-treeview").style.display = "block ";
currentLink[0].closest(".has-treeview").classList.add("menu-open");
$('.menu-open').find('a').each(function() {
    if (!$(this).parents().hasClass('active')) {
        $(this).parents().addClass("active");
        $(this).addClass("active");
    }
});
```

**Comment by abasina333** [comment]
> ![image](https://user-images.githubusercontent.com/44359409/70884933-f1198f00-2009-11ea-91e4-2bf9a68dd152.png)
> 
> ```
> var url = window.location;
> const allLinks = document.querySelectorAll('.nav-item a');
> const currentLink = [...allLinks].filter(e => {
>     return e.href == url;
> });
> 
> currentLink[0].classList.add("active");
> currentLink[0].closest(".nav-treeview").style.display = "block ";
> currentLink[0].closest(".has-treeview").classList.add("menu-open");
> $('.menu-open').find('a').each(function() {
>     if (!$(this).parents().hasClass('active')) {
>         $(this).parents().addClass("active");
>         $(this).addClass("active");
>     }
> });
> ```

its work for me but its remove my css from the menu

**Comment by ilyas5** [comment]
> I have added `menu-open` class to @apexcipher 's solution
> use following for better result. (not for **AdminLTE 3**)
> 
> ```js
> var url = window.location;
> // for sidebar menu entirely but not cover treeview
> $('ul.sidebar-menu a').filter(function() {
>       return this.href != url;
> }).parent().removeClass('active');
> 
> // for sidebar menu entirely but not cover treeview
> $('ul.sidebar-menu a').filter(function() {
>       return this.href == url;
> }).parent().addClass('active');
> 
> // for treeview
> $('ul.treeview-menu a').filter(function() {
>       return this.href == url;
> }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active menu-open');
> ```

it is not working when URL contains Query String like e.g https://github.com/ColorlibHQ/AdminLTE/issues/?id=2058

--Need help to resolve this

**Comment by ashrafulgit** [comment]
> > ![image](https://user-images.githubusercontent.com/44359409/70884933-f1198f00-2009-11ea-91e4-2bf9a68dd152.png)
> > ```
> > var url = window.location;
> > const allLinks = document.querySelectorAll('.nav-item a');
> > const currentLink = [...allLinks].filter(e => {
> >     return e.href == url;
> > });
> > 
> > currentLink[0].classList.add("active");
> > currentLink[0].closest(".nav-treeview").style.display = "block ";
> > currentLink[0].closest(".has-treeview").classList.add("menu-open");
> > $('.menu-open').find('a').each(function() {
> >     if (!$(this).parents().hasClass('active')) {
> >         $(this).parents().addClass("active");
> >         $(this).addClass("active");
> >     }
> > });
> > ```
> 
> its work for me but it removes my CSS from the menu

I  have updated the above code


var url = window.location;
const allLinks = document.querySelectorAll('.nav-item a');
const currentLink = [...allLinks].filter(e => {
    return e.href == url;
});

currentLink[0].classList.add("active");
currentLink[0].closest(".nav-treeview").style.display = "block ";
currentLink[0].closest("ul.nav-treeview").closest('li').classList.add('menu-open');
$('.menu-open').find('a').each(function() {
    if (!$(this).parents().hasClass('active')) {        
        $(this).parents().addClass("active");
        $(this).addClass("active");
    }
});

**Comment by paulodiogo** [comment]
```
$(linkAtivo).addClass('active');

if ($(linkAtivo).closest(".nav-treeview").is(":hidden")) {
    $(linkAtivo).closest(".nav-treeview").show()
    $(linkAtivo).closest(".nav-treeview").parent(".nav-item").addClass("menu-is-opening menu-open");
}
```

**Comment by ayro06** [comment]
How do I get it working for my page? I've tried the above suggestions, but can't seem to get it working for me. I'm using a template I found [here](https://codyhouse.co/gem/css-multi-level-accordion-menu). 
I'd like to able to preserve the state of the sidebar when a user navigates to one of the links.

**Comment by devideots** [comment]
> > I have added `menu-open` class to @apexcipher 's solution
> > use following for better result. (not for **AdminLTE 3**)
> > ```js
> > var url = window.location;
> > // for sidebar menu entirely but not cover treeview
> > $('ul.sidebar-menu a').filter(function() {
> >       return this.href != url;
> > }).parent().removeClass('active');
> > 
> > // for sidebar menu entirely but not cover treeview
> > $('ul.sidebar-menu a').filter(function() {
> >       return this.href == url;
> > }).parent().addClass('active');
> > 
> > // for treeview
> > $('ul.treeview-menu a').filter(function() {
> >       return this.href == url;
> > }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active menu-open');
> > ```
> 
> it is not working when URL contains Query String like e.g localhost:10001/Payroll/PayrollRecord?id=2058
> 
> --Need help to resolve this

change 

`var url = window.location.origin+window.location.pathname;`
