### ISSUE TITLE
Some thoughts on the concept of a 'framework'

### ISSUE THREAD

**Issue by xo-chris** [almasaeed2010/AdminLTE#1484]
I am a dev with 20 years experience, mainly in the middle tier and db.  My front end skills aren't that great, which is why I turn to solutions like AdminLTE :-)

I'd like to see Admin LTE 3.0 have the ability to honor a plain vanilla bootstrap site, and give the developer the ability to extend what bootstrap provides by providing some cool components that work seamlessly with your chosen flavor of bootstrap skin.

See for example http://bootswatch.com   I can do a bootstrap website, use one of their free themes and change the whole theme of my site (e.g. for a client) simply by downloading a new css file and linking to that - I can be confident nothing breaks as the themes are 'plug and play'

I'd like to see AdminLTE take a similar route, offering the ability to honor a given bootstrap 'look and feel' but able to offer some extended functionality e.g. calendars, sliders, example forms etc etc

I'd be more than happy to expand on what I mean if you think this concept would fit with your development plans

Cheers

Chris Lennon

**Comment by almasaeed2010** [comment]
Hello @xo-chris ,

This is actually the goal of AdminLTE v3. We are trying our best to make all Bootstrap components and plugins integrate seemlessly without direct changes to AdminLTE. So far, we are honoring all variables that Bootstrap provides. Therefore, bootswatch themes should work with AdminLTE without problems if you use SASS files.

However, v3 is going to take some time to be production ready and that depends greatly on when Bootstrap 4 gets officially released. 

Thanks for the suggestions!
