### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by yoyo837** [almasaeed2010/AdminLTE#1489]
How can I stop “Property 'AdminLTE' does not exist on type 'JQueryStatic'.” syntax errors when using Typescript?

Thanks!

**Comment by almasaeed2010** [comment]
Hello @yoyo837 

In the new AdminLTE 2.4, we have rewritten all of our JS code. Your best bet to make this  work is to upgrade to v2.4 by following this guide: https://adminlte.io/docs/2.4/upgrade-guide

Please open a new issue if the problem persists in v2.4

We greatly appreciate your contribution. Thanks!
