### ISSUE TITLE
Tab Disabled Css

### ISSUE THREAD

**Issue by sviluppo** [almasaeed2010/AdminLTE#1490]
When you create a tab with the class **disabled** this css:

`.nav-tabs-custom > .nav-tabs > li > a {
    color: #444;
    border-radius: 0;
}`

override the bootstrap css

`.nav > li.disabled > a {
    color: #777;
}`

Fast fix
`.nav-tabs-custom > .nav-tabs > li.disabled > a {
    color: #777;
}`

**Comment by lenamtl** [comment]
+1

**Comment by almasaeed2010** [comment]
Fixed in master (v2.4)
