### ISSUE TITLE
CSS bug when sidebar is collapsed

### ISSUE THREAD

**Issue by GeiliCode** [almasaeed2010/AdminLTE#1494]
<img width="225" alt="2" src="https://cloud.githubusercontent.com/assets/1515224/26089657/234a41ba-3a32-11e7-980a-d625864f56df.png">
<img width="233" alt="1" src="https://cloud.githubusercontent.com/assets/1515224/26089661/2a59608a-3a32-11e7-9ec4-6d50ce141ede.png">

It only display one item in the pull-right-container when the sidebar is collapsed.

I found the bug from the official [demo](https://almsaeedstudio.com/themes/AdminLTE/index2.html)

**Comment by almasaeed2010** [comment]
@GeiliCode this is intentional because displaying multiple labels and icons causes multiple issues with the sidebar at this point. We are working on making the sidebar better, but probably this rule won't change until v3 is released.

Thanks and sorry for the inconvenience!
