### ISSUE TITLE
how to set the sidebar in right of screen?

### ISSUE THREAD

**Issue by MostafaSh** [almasaeed2010/AdminLTE#1497]
hi!

thanks a lot for your great work! I'm really thanks full because you did the best ! thanks a lot again!

I have a simple question!

is there anyway that I can make a right handed sidebar? 

if not, would you edit this bootstrap for me as to I could have the sidebar in right and not left?

thanks!

**Comment by almasaeed2010** [comment]
Hello @MostafaSh 

We don't officially support RTL at this point. However, there are attempts to implement RTL in different forks. The latest of which can be found here #1480.

Thanks for the compliments! We apologize for not being able to assist any further.
