### ISSUE TITLE
about sidebar tree data-options

### ISSUE THREAD

**Issue by woaiwhr001** [almasaeed2010/AdminLTE#1500]
![qq 20170519020534](https://cloud.githubusercontent.com/assets/20886053/26216753/cc6d956a-3c37-11e7-802d-4ac6e65f2b71.png)
$.data() ，the obejct‘s prop always lowercase 
data-animationSpeed=“xxx” not work

**Comment by almasaeed2010** [comment]
it would be data-animation-speed="". This goes for all data options. That's just how jQuery parses it.

Thanks!

**Comment by woaiwhr001** [comment]
it working ,Thanks!
