### ISSUE TITLE
Python collectstatic fails on locating boxed-bg.jpg (fix included)

### ISSUE THREAD

**Issue by lizkepner** [almasaeed2010/AdminLTE#1512]
In both the _AdminLTE-without-plugins.css_ and _AdminLTE-without-plugins.min.css_ files, the `python manage.py collectstatic` command fails stating that the file boxed-bg.jpg does not exist. 

Currently, the file is being searched for in an `img` folder inside of the `css` folder, but there isn't one - it should be pointing to the `img` folder that is up one level.

To fix the error:
The url in both files should be changed to the following, in order to pull from the correct location:
`background: url('../../img/boxed-bg.jpg')`

It can be found in line 50 of _AdminLTE-without-plugins.css_, and towards the beginning of line 7 in _AdminLTE-without-plugins.min.css files_

**Comment by simonsmiley** [comment]
@almasaeed2010 I just ran into the same issue. There appears to be a merge request fixing it #1526

**Comment by almasaeed2010** [comment]
Thanks! Fixed in master. Will be available in v2.4

**Comment by JohnnySparkles** [comment]
Has this regressed with commit https://github.com/almasaeed2010/AdminLTE/commit/cc4654239ba749c9066e437abcd94c143c4309c5#diff-6de2bcab2c9ba7812e5158ba5e725dc0?
