### ISSUE TITLE
Delay sidebar-mini State On Hover

### ISSUE THREAD

**Issue by fraktal12** [almasaeed2010/AdminLTE#1516]
Hi,
 I saw this issue on forum but I did not found an answer.
I use sidebar collapse and fixed layout.
I want to delay the expand on hover feature with 1 sec, let's say, because some of my content elements are closed to the left bar and triggering unintentionally menu expansion is not optimal for user. 
How can this be achieved?

I tried this code but it does not work - i think the event is not correctly mapped:

`var delay=1000, setTimeoutConst;
    $('.sidebar').on('hover', function() {
         setTimeoutConst = setTimeout(function(){
                //do something
         }, delay);
    }, function(){
         clearTimeout(setTimeoutConst );
      });`

Additionally i tried something found here, which works but is not the event I need:

`$(document).on('collapsed.pushMenu expanded.pushMenu', function(){
    var timeoutID;
    function delayedStart() {
      timeoutID = window.setTimeout(resizeAction, 350);
    }
    function resizeAction() {
      // YOUR RESIZE FUNCTION HERE
      console.log("Sidebar is collapsed or expanded!");
      window.clearTimeout(timeoutID);
    }
    delayedStart();
  });`

Thank you!

**Comment by REJack** [comment]
Hover from sidebar menu items?

**Comment by fraktal12** [comment]
Mmm, not sure I understand your question.
Normally left side bar with menu items it's collapsed. If you hover - will expand. I want the expansion not to trigger immediately if you just quickly hover it and return the mouse to the page content.

**Comment by REJack** [comment]
Oh ok for this you need to modify the function expandOnHover in `app(.min).js`.

**Comment by fraktal12** [comment]
Thanks a lot Jack! 
I'll give it a try.

**Comment by fraktal12** [comment]
Works as expected. Is useful, on the left side you usually place some important controls and the immediate trigger on accidental mouseover is annoying sometimes.

This was the solution (combined with ReJack pointing of location):
https://stackoverflow.com/questions/15575993/how-to-add-delay-to-jquery-mouseover
