### ISSUE TITLE
No smooth animation on left sidebar menu arrows

### ISSUE THREAD

**Issue by jb-reynaud** [almasaeed2010/AdminLTE#1517]
![image](https://cloud.githubusercontent.com/assets/390431/26494732/745f220a-4220-11e7-9c0a-e4be2ffdcdbf.png)

When I expand an item on the left sidebar menu, I see the 90° rotation but it isn't smooth as it should be, regardless the demo https://adminlte.io/themes/AdminLTE/pages/examples/blank.html. I pass directly from `>` to `v`.

I just install last version of AdminLTE, I'm on version 2.3.11.

Am I missing something?

**Comment by REJack** [comment]
it sound like your browser doesn't support browser transition's

**Comment by jibe84** [comment]
but if the live demo is working, mine should work on the same browser, no?

**Comment by REJack** [comment]
Sure it should work, then it could be that you missed some css classes in the html.

It's need the `pull-right-container`-class for the transition.

Check your code with this 😄 from the demo 
```html
<li class="treeview active menu-open">
          <a href="#">
            <i class="fa fa-folder"></i> <span>Examples</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu" style="">
            ****
          </ul>
        </li>
```

**Comment by jibe84** [comment]
thanks again for your reply, but no, still nothing... I'm gonna start with a new fresh install to see what is going on.

**Comment by kabutotx** [comment]
Transition css (lines 547-549 in AdminLTE.css) was added to 2.4

**Comment by lucascbeyeler** [comment]
I have the same problem... Someone can help me? My treeview:

```
<li class="treeview">
    <a href="#">
        <i class="fa fa-envelope-o"></i>
        <span>Notificações</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
</li>
```

I'm using the version 2.3.11.

**Comment by almasaeed2010** [comment]
The rotation transition of the arrow was added to version 2.4 which is the version in the demo. V2.4 is currently in Beta, feel free to to upgrade by following this guide:

**Comment by jb-reynaud** [comment]
I cl

**Comment by jb-reynaud** [comment]
Closed as the solution is to update.

Thank you everyone ;)
