### ISSUE TITLE
fix layout-top-nav drop down menu in small screen.

### ISSUE THREAD

**Issue by edwinhuish** [almasaeed2010/AdminLTE#1523]
Please add the following css to fix the BUG.
```
.layout-top-nav .main-header {
    max-height: inherit;
}
```

## Before:
![image](https://cloud.githubusercontent.com/assets/5207925/26751528/51a26ba6-486e-11e7-9e23-0b7d0e363acd.png)

## After:
![image](https://cloud.githubusercontent.com/assets/5207925/26751531/5fe1487c-486e-11e7-9fbf-0438fe3475c9.png)

**Comment by dojo1017** [comment]
You know how git works, right? 

You can always change the code in your own fork yourself and then send a pull request. 

The maintainers then only have to accept the change or deny it. Simple as that.

**Comment by edwinhuish** [comment]
@dojo1017 yes, but I don't know how to use less..

**Comment by REJack** [comment]
I wouldn't change it, a additional class is better.
