### ISSUE TITLE
Dependencies management

### ISSUE THREAD

**Issue by martinRenou** [almasaeed2010/AdminLTE#1532]
Hi,
I think that it's a bad idea to put your dependencies like that in the source code under "plugins". jQuery and Bootstrap are not plugins of AdminLTE, they are dependencies. You should install your dependencies with bower/npm:
`bower install --save bootstrap jquery`
or
`npm install --save bootstrap jquery`
and use a specific version (if you really want a specific version) by saying it on your bower.json/package.json file.
Once installed, those dependencies are under bower_components/node_modules directory and this directory should NOT be part of your git repository.

This is a bad practice to do what you're doing right now because you possibly have a buggy version of jQuery until you update your version of jQuery on your repository (which is normally automatic when installing via npm, it install the last fixed version).

Also, you have specific version of jQueryUI right now, and it's unclear which version it is, if it was installed via npm/bower, the version would be specified in the package.json/bower.json.

An other problem (mentioned here #1430) is that if someone install admin-lte trough npm or bower, he could have redundant repositories in node_modules and the amount of files would increase drastically for big projects. Nobody wants to play with three different jQuery versions at the same time...

Hope this can be fixed :)

**Comment by almasaeed2010** [comment]
Hello @martinRenou,
We are implementing support for Bower and NPM. The feature will be available in v2.4.

Thanks for the detailed report! We will keep this open until the dependencies manager is implemented.

**Comment by almasaeed2010** [comment]
Some plugins don't provide a fully compiled version when downloaded via a package manager but we managed to use NPM and Bower for the majority of packages.
