### ISSUE TITLE
I bought a script that use adminlte

### ISSUE THREAD

**Issue by MixRadu** [almasaeed2010/AdminLTE#1533]
Hello, i bought a script that use adminlite, after i bought a premium template for adminlte but i dont know how to install it.
Please help! :)

**Comment by REJack** [comment]
Contact the Author where you buyed the script or premium template

**Comment by MixRadu** [comment]
The theme is this http://www.themeon.net/nifty/v2.6/index.html 
I have just to replace the files? Can you help me? I will pay

**Comment by almasaeed2010** [comment]
Hello @MixRadu,

Nifty is not related to AdminLTE. They are separate admin themes. Please contact the author if you need help using it. 

Thanks!
