### ISSUE TITLE
Are you using infolink ads on the demo site?

### ISSUE THREAD

**Issue by sama55** [almasaeed2010/AdminLTE#1534]
Thank you for your excellent theme.
By the way, I saw demo site. And, many pop-up ads were shown in there.
There seems to be infolink code in js file below.
https://adminlte.io/themes/AdminLTE/dist/js/adminlte.min.js

Is this the intended ad? I felt that demo site has been cracked.
This is just a confirmation.
Thanks again.

**Comment by almasaeed2010** [comment]
Yeah we are. Unfortunately, we enabled the in-text ads by mistake. We didn't mean to add annoying ads like those 👎 . We changed the settings to be a bit less in your face ads lol.

Thanks for the concern. We appreciate it!
