### ISSUE TITLE
ListDay not functional in FullCalendar

### ISSUE THREAD

**Issue by Aurore77** [almasaeed2010/AdminLTE#1535]
Hello, AdminLTE is using an old version of fullCalendar so when !i try to use 'listDay' (https://fullcalendar.io/docs/list_view/intro/) view it is not implemented in the code so it doesn't work.
I tried to use the last version of fullcalendar but it breaks everything in my code. Once repaired, if it works I will share it

**Comment by almasaeed2010** [comment]
@Aurore77 thanks for reporting the issue! We are working on upgrading all the plugins to the newest version and using Bower and NPM to manage dependencies. This should be available in version 2.4.

Thanks!
