### ISSUE TITLE
Callback/hook for after everything has loaded?

### ISSUE THREAD

**Issue by mhulse** [almasaeed2010/AdminLTE#1538]
Hi,

Just curious if there is a hook for after all AdminLTE JavaScript has finished loading?

I would like to experiment with an overlay with a "loading" graphic (mainly to avoid seeing jumps in UI components).

Has anyone played with this? Any code or tips?

Thanks!

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE doesn't provide a hook for complete loading but I would suggest trying `window.onLoad`

https://stackoverflow.com/questions/15564029/adding-to-window-onload-event

Thanks!

**Comment by mhulse** [comment]
Thanks!
