### ISSUE TITLE
Could i run angularjs with AdminLTE

### ISSUE THREAD

**Issue by estem** [almasaeed2010/AdminLTE#1539]
I'm trying to integrate angularjs with AdminLTE...is there a chance to go on or i will get stuck in the futur..?

**Comment by almasaeed2010** [comment]
There are multiple successful cases where AdminLTE was used in conjunction with AngularJS. 
Examples:
https://github.com/ahmadalibaloch/Angular-AdminLTE
https://github.com/silverbux/laravel-angular-admin
