### ISSUE TITLE
Outdated bootstrap .less files

### ISSUE THREAD

**Issue by bmino** [almasaeed2010/AdminLTE#1543]
While the css files were updated to bootstrap version 3.3.7 the less files are still at version 3.3.5. Users who build AdminLTE will be using outdated bootstrap files.

**Comment by almasaeed2010** [comment]
At this point, AdminLTE only uses the variables and mixins LESS files for reference. The Bootsrap CSS files are provided separately. Therefore, the LESS files do not affect the produced CSS files.

Thanks!
