### ISSUE TITLE
Fixed header and footer with scrolling middle content

### ISSUE THREAD

**Issue by Zyles** [almasaeed2010/AdminLTE#1546]
I am making an app with this amazing theme but running into a problem.

I am trying to do this: https://jsfiddle.net/rmeoeyyh/1/

Where I can scroll the middle content of the app with a fixed header and footer. The problem is the scrollbar will end up under the header/footer and not between them.

Is there an easy fix for this?

Thanks.

**Comment by almasaeed2010** [comment]
Hello @Zyles 
Did you try the [Fixed Layout](https://adminlte.io/themes/AdminLTE/pages/layout/fixed.html)? You can get this layout by adding the `fixed` class to the `<body>` tag.

Thanks!

**Comment by Zyles** [comment]
Yes of course.

Problem still there.

**Comment by softman20** [comment]
use class fixed-top to header

**Comment by kahovn** [comment]
Fixed: 
<body class="hold-transition skin-black fixed sidebar-mini">

**Comment by kahovn** [comment]
hold-transition skin-black fixed sidebar-mini

**Comment by Zyles** [comment]
Nope. The sidebar is still left of the footer.
