### ISSUE TITLE
select2 input:focus border

### ISSUE THREAD

**Issue by ajcastro** [almasaeed2010/AdminLTE#1549]
Duplicate of #756. Since it was already closed, I will open a new issue for this. @almasaeed2010 

It is because of the width set to the element. Maybe there is a jquery code that add the width to 519px. 

![image](https://user-images.githubusercontent.com/4918318/27462267-16f98910-57f2-11e7-89fa-b4c7c1597bac.png)

If you uncheck the width css, it is fine:

![image](https://user-images.githubusercontent.com/4918318/27462342-b66ce546-57f2-11e7-9073-845031da4c67.png)

**Comment by ajcastro** [comment]
Possible css fix, via chrome dev tools only to give you hints. @almasaeed2010 

![image](https://user-images.githubusercontent.com/4918318/27462410-47a11fa0-57f3-11e7-84a7-0300b9a39e3b.png)

![image](https://user-images.githubusercontent.com/4918318/27462451-8b0b84f6-57f3-11e7-8e39-bf9bf40ee96e.png)

**Comment by ajcastro** [comment]
But the css above has also a problem. When it is applied, the input element will be always on the next line.
Maybe it is better if we remove the border on the input element.

![image](https://user-images.githubusercontent.com/4918318/27462837-10fa4fd2-57f6-11e7-9533-2994094c4502.png)

**Comment by almasaeed2010** [comment]
Fixed in master (v2.4)

Thanks for detailed report and help @ajcastro!!

**Comment by ajcastro** [comment]
You're Welcome! Happy to contribute. 😊

**Comment by almasaeed2010** [comment]
Here is how it looks now 
<img width="642" alt="screen shot 2017-06-24 at 11 09 57 am" src="https://user-images.githubusercontent.com/1512664/27509548-b4dec63c-58cd-11e7-9789-390ec99a161c.png">

Please let me know if that's not how you see it in your browser

**Comment by ajcastro** [comment]
I visited https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html and it looks like this.

![image](https://user-images.githubusercontent.com/4918318/27512688-4432dfb8-597c-11e7-952d-ef078fc3af9b.png)

**Comment by almasaeed2010** [comment]
@ajcastro please try clearing your browser cache and test again because it looks fine in my browser. 
The only difference is that you are using chrome on Windows and I am using Mac so that might be causing the difference. Lastly, the width is apparently calculated via select2's JS. So, if the issue persists, please try upgrading to the latest select2 plugin (which we are planning to do for v2.4-beta-2).

Thanks!

**Comment by ajcastro** [comment]
Yeah, it's now perfect! :wine_glass:

**Comment by AiltonOcchi** [comment]
I add this code in AdminLte.css 
.select2-selection--single:focus
{border: 1px solid #3c8dbc;}
