### ISSUE TITLE
Using Admin LTE in Symfony2

### ISSUE THREAD

**Issue by junrikson** [almasaeed2010/AdminLTE#155]
Hello there, I'm trying to use this template for my internal project. It's works fine when I click index.html outside my symfony2 project. But inside my symfony2 project, the left bar drop-down didn't work and top bar have some glitches. I've make sure that all files (css and javascript) loaded. 

I think the problem with "app.js" and "demo.js" doesn't work properly in Symfony2. I've tried to delete and add that 2 files and seems doesn't give any effect to my project. 

Symfony2 is MVC Framework. Is there any one ever try this template in Symfony2 or any MVC framework? Thank you very much for your help.

![admin_lte](https://cloud.githubusercontent.com/assets/5647735/4989522/666ebd26-69ac-11e4-91a5-836062675833.jpg)

**Comment by Mentos93** [comment]
@junrikson You said you tried it with Symfony2? @yajra's template is about Laravel. Did you switch to Laraval? Or continued using Symfony2? If so how did you get it to work with Symfony?
