### ISSUE TITLE
Error Input masks in advanced in pages/forms/advanced.html

### ISSUE THREAD

**Issue by nelsonalleinjunior** [almasaeed2010/AdminLTE#1550]
When used in the CHROME MOBILE browser the DATE mask does not work correctly when deleting with BACKSPACE.

**Comment by almasaeed2010** [comment]
Hello @nelsonalleinjunior,
This issue is related the Input Mask plugin, please raise your issue in their repository https://github.com/RobinHerbots/Inputmask/issues

Thanks!
