### ISSUE TITLE
Uncaught TypeError: $(...).tooltip is not a function

### ISSUE THREAD

**Issue by push32** [almasaeed2010/AdminLTE#1557]
![screen shot 2017-06-30 at 3 14 46 am](https://user-images.githubusercontent.com/24914270/27708202-50b5ccae-5d42-11e7-8cfe-703c53aa110d.png)

The side bar is missing, only white background

**Comment by push32** [comment]
Solve it, some of my php file missing </div>

thank you :)

**Comment by jesoa** [comment]
okay
