### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by lucasmucidas** [almasaeed2010/AdminLTE#1559]
I downloaded the mostly recent version 2.4-beta, moved the files into htdocs folder on XAMPP but it looks kinda messy:

![image](https://user-images.githubusercontent.com/14371178/27765685-cca026c8-5e8e-11e7-970e-2fa45ca49aa0.png)

can you guys please help me?

**Comment by almasaeed2010** [comment]
Hello @lucasmucidas,

AdminLTE 2.4-beta requires bower. You need to run `bower install` for it to work. However, if you don't want to use bower or npm, you can download the master branch since it now supports direct downloads too.

Thanks!
