### ISSUE TITLE
How to replace the tooltip Chrome users in the chart

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#1563]
Hello
I can see a chart in the template and i am able to replace everything except the tooltip that comes on the chart. Please where to edit the tooltip and the chart itself ?
![zz](https://user-images.githubusercontent.com/925132/27883986-17c1b08c-61c2-11e7-88e1-6507de5d8865.png)

**Comment by REJack** [comment]
You can change it in the `js/pages/dashboard2.js`, search for `var PieData`.

**Comment by kressly** [comment]
Thank you very much for your answer but i found 3 challenges. 
1 - It adds the keyword users to it which i do not know where to find it in ` js/pages/dashboard2.js` . 
![za](https://user-images.githubusercontent.com/925132/27895934-20594dce-6206-11e7-87cd-2fe924a4d5a6.png). Where can i find that key word and change it

2 - Having that code in ` js/pages/dashboard2.js` means that i can not change the content dynamically so i tried to override it by copying the code to the index file but it shows a syntax error even though i copied exactly what was in the dashboard . How to fix that ? 
![zaab](https://user-images.githubusercontent.com/925132/27896059-e840275e-6206-11e7-997f-f072a30bd741.png)

@REJack Thank you very much, i really appreciate your fast answer.

**Comment by REJack** [comment]
Which IDE/Editor do you use, it is Dreamweaver? If yes, Dreamweaver recognize some JS syntaxes wrong, it's a False-Positive. DW is crap 😛 and you can't trust the BrowserView from DW, i recommend simple IDE like Sublime Text 2/3 or Atom.io.

I tried your code and it works as inline js in the `index2.html` without the `dashboard2.js`. But if you have more questions about dynamic charts ask the creators of the Plugin 😄  ([Charts.js](https://github.com/chartjs/Chart.js)) but you could load the JSON data trough $.get() or $.post() for a Dynamic Data Loading.

**Comment by kressly** [comment]
@REJack Thank you very much
