### ISSUE TITLE
How to enable Country listing on the new version of the map of adminlte ?

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#1564]
Hello. On the previous version of the map we could see countries by hovering on the map but on the new one no country is seen.
![zaac](https://user-images.githubusercontent.com/925132/27896565-88642c50-620a-11e7-99e8-ccb4da6e238b.png)

Please how to enable that again ?

**Comment by REJack** [comment]
It's a bug inside the new v2.4.0-rc, it's loads the `v1.2.2` js file from plugins folder but `v2.0.4` css file from bower_componets.

If you switch the css back it should work or switch the js file to the new version but this could bring some problems.

**Comment by kressly** [comment]
Thank you very much @REJack . I have copied the content of the jquery-jvectormap css code from the old and replaced with the new one and now it is working perfectly
