### ISSUE TITLE
refreshBox undefined in 2.4.0-rc

### ISSUE THREAD

**Issue by mapbuh** [almasaeed2010/AdminLTE#1567]
I'm getting:
TypeError: $(...).refreshBox is not a function

Seems refreshBox is not migrated from app.js

**Comment by almasaeed2010** [comment]
The plugin's name changed to boxRefresh. But you are also right in that it was not included in adminlte.min.js.

Fixed in master. Will be available in v2.4.

Thanks!

**Comment by ioulai** [comment]
![capture](https://user-images.githubusercontent.com/26062183/37908743-55bdf3d4-3109-11e8-92bc-86de08887d49.PNG)

error with boxRefresh()
