### ISSUE TITLE
Will be available wizard option?

### ISSUE THREAD

**Issue by irfanevrens** [almasaeed2010/AdminLTE#157]
I am a fan of your AdminLTE. I have needed last week a wizard for building a web page. Will you develop wizard codes?

**Comment by akosgei** [comment]
Greetings Almasaeed, first of all commending you the good work done on LTE template. Any prgress with this wizard implementation, or should I ask when's the next release? :)

**Comment by adaniello** [comment]
I've the same question of @akosgei : any news?
Thanks

**Comment by guijoe** [comment]
Hello Almasaeed. I'm a fan of the AdminLTE template. I have the same need for a form wizard. Any progress in the implementation ?

**Comment by PetengDedet** [comment]
+1 for Form wizard

**Comment by almasaeed2010** [comment]
Hello everyone, 

I realize the important need for a form wizard and we are working hard to prepare AdminLTE 3 to have great components. However, it has taken Bootstrap 4 a while to get to Alpha 6. We are still transition AdminLTE 3 from BS3 to BS4. Once that has been done with, we will add new components including a form wizard. You can watch the v3-dev branch to see our progress. 

Thanks!

**Comment by AbdulmatinSanni** [comment]
Hi,

Someone can actually write the codes for the form wizard and send it to almasaeed2010, it'll ease his work, probably.

**Comment by yycelik** [comment]
It can be done by [Jquery Step](http://www.jquery-steps.com/Examples) easily

**Comment by sohilluhar** [comment]
still same question 
Is it available or not? Wizard form
step by step form

**Comment by ak-rocksdev** [comment]
Any update on this form wizard topic?? Good idea for making an example on AdminLTE 3
