### ISSUE TITLE
Highlighting active menu on dropdown menu

### ISSUE THREAD

**Issue by sirBobz** [almasaeed2010/AdminLTE#1585]
I want to highlight the active page on the side bar menu.

I have tried a number of javascript ways to to avail. Kindly anyone help out. Below is the side bar menu.

    <ul class="sidebar-menu" >
      <li class=""><a href="/dashboard"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a> </li>
      <br>
      <li class="treeview">
        <a href=""> <i class="fa fa-cogs"></i> <span> Account Configuarion</span> <i class="fa fa-angle-left pull-right"></i> </a>
        <ul class="treeview-menu">
          <li class="treeview">
            <a href=""> <i class="fa fa-mobile fa-lg"></i> <span>M-PESA C2B</span> <i class="fa fa-angle-left pull-right"></i> </a>
            <ul class="treeview-menu">
              <li class=""><a href="/c2b"><i class="fa fa-arrow-circle-right"></i>C2B Settings</a></li>
              <li class=""><a href="/online-checkout"><i class="fa fa-arrow-circle-right"></i> Online CheckOut</a></li>
              <li class=""><a href="/stk-push"><i class="fa fa-arrow-circle-right"></i> STK Push</a></li>
            </ul>
          </li>
          <li class="treeview">
            <a href=""> <i class="fa fa-mobile fa-lg"></i> <span>M-PESA B2C</span> <i class="fa fa-angle-left pull-right"></i> </a>
            <ul class="treeview-menu">
              <li><a href="b2c-documentation"><i class="fa fa-arrow-circle-right"></i>  B2C Settings</a></li>
            </ul>
          </li>
          <li class="treeview">
            <a href=""> <i class="fa fa-send"></i> <span>SMS</span> <i class="fa fa-angle-left pull-right"></i> </a>
            <ul class="treeview-menu">
              <li class=""><a href="/sms-setting"><i class="fa fa-arrow-circle-right"></i>SMS Settings</a></li>
              <li class=""><a href="/subscription"><i class="fa fa-arrow-circle-right"></i>Subscription SMS Settings</a></li>
            </ul>
          </li>
        </ul>
      </li>
      
      <li class="treeview ">
        <a href="#"> <i class="fa fa-cogs"></i> <span>Account Info</span> <i class="fa fa-angle-left pull-right"></i> </a>
        <ul class="treeview-menu">
          <li class=""><a href="buy-units"><i class="fa fa-arrow-circle-right"></i> Buy Units</a></li>
          <li class=""><a href="/account-details"><i class="fa fa-arrow-circle-right"></i>Account Details</a></li>
          <li class=""><a href="/users"><i class="fa fa-arrow-circle-right"></i>Account Users</a></li>
        </ul>
      </li>
    </ul>

I tried with this javascript code but ends up opening all the dropdowns. All the same, it does highlight the current item. But I would want the other items remain closed and only active remains open.

    <script>
        $(document).ready(function() {
            var url = window.location; 
            var element = $('ul.sidebar-menu a').filter(function() {
            return this.href == url || url.href.indexOf(this.href) == 0; }).parent().addClass('active');
            if (element.is('li')) { 
                 element.addClass('active').parent().parent('li').addClass('active')
             }
        });
        </script>

**Comment by sirBobz** [comment]
Solved;

Finally I figured it out!

I included the script below;
        `<script type="text/javascript">
        /** add active class and stay opened when selected */
        var url = window.location;
        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function() {
        return this.href == url;
        }).parent().addClass('active');
        // for treeview
        $('ul.treeview-menu a').filter(function() {
        return this.href == url;
        }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
        </script>`

Then included `<a href="#"> </a>` on all `<ul class="treeview-menu">` I believe this prevented the lists from opening unless clicked.

This ultimately sorted everything.

**Comment by vanthinhit310** [comment]
### 

> [`_****_`]([url](

- 

- [ ] @ #url

))
