### ISSUE TITLE
Different versions on npm, bower and cdnjs

### ISSUE THREAD

**Issue by apetitpa** [almasaeed2010/AdminLTE#1612]
Hi,

Package version is 2.4.0-rc on composer while it's still 2.3.11 on other platforms, would it be possible to have the same version everywhere please ? I'd like to use the 2.4.0-rc version but since I manage frontend dependencies with yarn, it's currently impossible.

Thanks

**Comment by PascalHonegger** [comment]
We require some 2.4.0 features in our project, but since there's no prerelease on NPM we had to temporarily download and reference 2.4.0-rc manually. Our project would also appreciate a new release or the option to use a prerelease.

**Comment by apetitpa** [comment]
ping @almasaeed2010

**Comment by almasaeed2010** [comment]
V2.4 has been published few days ago.
