### ISSUE TITLE
Modal is not working in live version Angular2

### ISSUE THREAD

**Issue by ashishsurana** [almasaeed2010/AdminLTE#1613]
While using modal in angular2 in the live version, It is throwing an error in console.
The link I'm using is: [http://webapplayers.com/inspinia_admin-v2.7.1/Angular/#/miscellaneous/modal_window](http://webapplayers.com/inspinia_admin-v2.7.1/Angular/#/miscellaneous/modal_window) 
Please provide an example to use modal as a component with angular2
Thanks in advance

**Comment by REJack** [comment]
This issue is not related to adminlte, contact webapplayers.com (creators of inspinia).
