### ISSUE TITLE
Question about floating menu / always visible while scrolling

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#1620]
Hi,

I need a floating menu that always visible while scrolling 
when clicking on a this menu it show the appropriate DIV id on the page.
I need this because the page is very long so this will improve the navigation of that page

Anyone have implemented something like this?
Affix and scrollspy seems not working well with adminlte...

**Comment by REJack** [comment]
You mean scrollspy insides the sidebar or with a sperate/new menu?

**Comment by lenamtl** [comment]
For a separate menu, one page is very long with several boxes so I'd like to add a way to navigate between the area rapidly.
What I was thinking is to have a menu that is always visible (this can be a floating menu) not necessarily a top menu.

**Comment by lenamtl** [comment]
I end up using btn-group with affix and it's working fine...
