### ISSUE TITLE
How to troubleshoot not working treeview

### ISSUE THREAD

**Issue by hkarakose** [almasaeed2010/AdminLTE#1625]
I have integrated AdminLTE into my Angular project. Treeview does not work in my angular project. How can I troubleshoot this issue? I have looked at following documentation about treeview but it didn't have. I already have working code. But appearantly, I am missing some javascript file?

https://adminlte.io/docs/2.4/js-tree

**Comment by almasaeed2010** [comment]
If you followed the documentation in the link you mentioned above, please make sure you are using AdminLTE v2.4 rather than v2.3 and under.

Thanks!

**Comment by darrinsimmons** [comment]
I am integrating AdminLTE 2.4.2 into a meanjs (v0.6.0) project and the sideview (treeview) is not working as well.  

When I click on a treeview item, it does not display the treeview-menu items.  When the sideview is minimized and I hover over the treeview icon image, the treeview-menu is displayed and it works fine.  What was your issue and were you able to resolve it?  As my project is just starting, I can share a private repo if you would like to take a look and troubleshoot.  

To troubleshoot, I have even copied the sidebar treeview from the 2.4.2 index.html into my sidebar.client.view.html file with the same results.

**Comment by hkarakose** [comment]
I am sorry, I don't remember what I have done about the issue.

**Comment by Starcodex** [comment]
Add <ul> like link below
https://adminlte.io/docs/2.4/js-tree

**Comment by MelhaouiAsmaa** [comment]
I had the same problem, I solved it by adding this "node_modules/jquery-ui-dist/jquery-ui.min.js", in scripts array in angular.json
