### ISSUE TITLE
navbar change color

### ISSUE THREAD

**Issue by Karador1995** [almasaeed2010/AdminLTE#1628]
Hello everyone, I tried to change the color of the navbar (header and menu) however, although I modify the _all-skins.min.css does not work. change the following:

.skin-blue .main-header .navbar {
     background-color: # 054a71;
}

Even so it did not work ... What should I do?

(I apologize if you do not understand me very well, my English is not very good and I support with google)

**Comment by Reconix** [comment]
.skin-[skinname] .main-header .navbar {
    background-color: #054a71;
}
Is correct, 
make sure you have the skin class in the body and obviously also load the css corresponding to that.

Lastly, number one culprit for everything can be cache, disable it or just clear it when editing.

**Comment by Karador1995** [comment]
It was just that, thank you

**Comment by Reconix** [comment]
Glad you got things sorted, don't forget to close your issue.

**Comment by Athul-The-Dev** [comment]
Add class on body. For example, if you are using skin-purple, add "**skin-purple**" class in body.
It works fine for me . . .

**Comment by ShohanurRahman077** [comment]
Can you guys please tell me in detail?? Like in which file i need to change and with file location please?
