### ISSUE TITLE
When use augular.js  ng-include add child view, The main footer is disorder. 

### ISSUE THREAD

**Issue by spursy** [almasaeed2010/AdminLTE#1632]
### The follow is my code:

**index.html**
```
<div class="wrapper">
    <div ng-include="'views/main-header.html'"></div>
    <div ng-include="'views/main-sidebar.html'"></div>
    <div ng-include="'views/calltree/calltree-list.html'"></div>
</div>
```
**The followed is calltree-list.html**

```
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Fixed Layout
            <small>Blank example to the fixed layout</small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="callout callout-info">
            <h4>Tip!</h4>           
        </div>

    </section>

</div>
<div ng-include="'views/main-footer.html'"></div>
```

The followed is my project screen picture

![demo](https://user-images.githubusercontent.com/11460991/30057237-87381498-9268-11e7-9d47-3eca410c9428.PNG)

**Just as reminder, If I write  calltree-list.html into index.html, the layout is ok.**

**Comment by akanat** [comment]
I have same problem with Angular 4. When angular redirects from login page with router to main AdminLte template, it becomes 392px of height. If I resize window it returns to normal view. Here is problematic page view

![image](https://user-images.githubusercontent.com/1744668/30243428-b14e066a-95ca-11e7-96f8-137e9fe9416b.png)

**Comment by almasaeed2010** [comment]
You should attempt using `$.AdminLTE.layout.fix()` after every page change.
