### ISSUE TITLE
fixed layout and menu scroll?

### ISSUE THREAD

**Issue by fraktal12** [almasaeed2010/AdminLTE#1634]
Hi,
I have a fixed and collapsed sidebar layout. I cannot make work the scrolling without a mouse - ex 2 fingers scrolling or edge scrolling that works on other pages.
I have version 2.3.11 and also tested on the demo deployment.

**Comment by almasaeed2010** [comment]
Hello @fraktal12 

Could you please specify which browser are you using because the scrolling works on Chrome: https://adminlte.io/themes/AdminLTE/pages/layout/fixed.html

Thanks!

**Comment by fraktal12** [comment]
Hi Ahmed, 
sorry for the late reply. Just saw your question...
Meh, to me on Chrome does not work, but it does on IE and Firefox. So maybe is local. I will test it on other colleagues, but for now it seems local. Thanks a lot.
