### ISSUE TITLE
fix overload layout

### ISSUE THREAD

**Issue by goddelose** [almasaeed2010/AdminLTE#1641]
how to fix content-wrapper overload issue, when first load
![untitled](https://user-images.githubusercontent.com/22434041/30248995-475a9c2c-965c-11e7-8f4c-6920f42cb9e6.png)

but when i click "inspect element" and then close it, that layout its fixed

**Comment by csharpengineer** [comment]
Try calling
`$(window).resize();`
or 
`$.AdminLTE.layout.fix()`
after everything is loaded.
