### ISSUE TITLE
php code will not be executed

### ISSUE THREAD

**Issue by crestAT** [almasaeed2010/AdminLTE#1643]
Hello, I'm new to this great AdminLTE. 

My problem: I want to insert data from a database with PHP calls and write it to a table in the content area. But every PHP code looks commented out somehow in the Code Inspector and therefore I don't get an output. Not even a simple PHP test code is working => <?php echo("Test"); ?> shows nothing.

So the question is, is itpossible to run PHP code inside AdminLTE or how can I retrieve data from an MySQL database and put it in a table?

I use AdminLTE Version 2.4.0-rc

Best regards

**Comment by lenamtl** [comment]
Adminlte is only a template not a php application script.

You should create your php application like usual then use the CSS and code syntax for the template.

Make sure you have a webserver up and running on your computer Wampserver for example.
Then in localhost create a folder with all  your script and create a DB and connexion for the DB...
If you don't know yet how to code PHP you should start to learn and then add the template later...

**Comment by Fatih90** [comment]
pfuhahaha ezuifjkleviejrvn
