### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by nasirkhan** [almasaeed2010/AdminLTE#1646]
Do you have any plan to create a new release based on Bootstrap 4?

**Comment by PascalHonegger** [comment]
See issue #710 which mentions some plans for AdminLTE 3.0, which uses Bootstrap 4.

**Comment by nasirkhan** [comment]
@PascalHonegger thanks for mentioning. I think nothing is happening on that project. do you have any update?

**Comment by PascalHonegger** [comment]
@nasirkhan I for myself am still waiting for a NPM release of version 2.4, of which the first alpha was released 6 months ago! It currently seems like @almasaeed2010 is working on other projects, as there hasn't been any feedback lately (for example a lot of untouched Issues). But that's just speculation as I don't have any more information than you do.

**Comment by jmerle** [comment]
@PascalHonegger I recently had the same problem when trying to fetch 2.4 from npm. It is however possible to install a package from a git repository instead, so `npm install almasaeed2010/AdminLTE` loads version 2.4.

**Comment by almasaeed2010** [comment]
Hello everyone,

I am always trying to find the time to work on AdminLTE and bring it up to date with all the new plugins but unfortunately I get really busy lately. However, I still plan to finish up AdminLTE 2.4 and start on 3.0 asap. Thank you for your patience and hopefully it will pay off :)

To answer the original question, yes I plan to upgrade to BS4 in AdminLTE 3.0. I can't promise a specific time line but I'll start on it as soon as possible.

Thanks!
