### ISSUE TITLE
Scrollbar in sidebar

### ISSUE THREAD

**Issue by rexdarel** [almasaeed2010/AdminLTE#1654]
How to add a scrollbar in sidebar? like the perfectscrollbar.. I want the sidebar to have it's own scrollbar

**Comment by jreklund** [comment]
AdminLTE ships with slimscroll, if you activate the [Fixed layout](https://adminlte.io/themes/AdminLTE/pages/layout/fixed.html).

**Comment by marcelogarbin** [comment]
@jreklund Here it is fixed, but the scrollbar is not shown, what can it be? In the example fixed.html also does not appear, however in the online version of AdminLTE you passed is shown.

**Comment by rexdarel** [comment]
Ah, okay. I tried the fixed layout before but I did not notice the scrollbar because of the dark color of the sidebar.
