### ISSUE TITLE
About 2.4 documentation issues

### ISSUE THREAD

**Issue by wangyouworld** [almasaeed2010/AdminLTE#1655]
I downloaded the AdminLTE 2.4 found the link to the document, pointing to the https://adminlte.io/docs, and unpacking the **documentation** directory, which is the 2.3.12 version of the document.

How can i download a document to version 2.4?

Because, I intend to AdminLTE 2.4 localized into Chinese, has now completed, 2.3.11 version.

**_From Google Translate_**

**Comment by almasaeed2010** [comment]
Hi

AdminLTE’s documentation has now moved completely online and there isn’t a way to download it at this point.

Sorry for the inconvenience.
