### ISSUE TITLE
Change Font Size Of Whole Template

### ISSUE THREAD

**Issue by DeepGandhi1602** [almasaeed2010/AdminLTE#1656]
Respected  @almasaeed2010,  I Want To Change Font Size Of Whole Template. I Tried As Per Your Instruction On Page Link 'https://adminlte.io/blog/customizing-and-downsizing-adminlte-to-match-your-businsess' But Can't Find Proper Solution. Help Me For That. What Can I Do For Changing The Font Size Of Whole Templete.? Variable @font-size-base is in 'bower_components\bootstrap\less\variables.less' File And Your Link Only Gives Solution For 'build\less\variables.less' file.

Give Me Instruction What To Do?
Thank You.

**Comment by almasaeed2010** [comment]
Hi,

Unfortunately, the only way to do this is to override the css manually. There isn’t an automated solution for font sizes yet.

Thanks

**Comment by DeepGandhi1602** [comment]
Thank You.
But brother manually changes to CSS makes problem in whole template....
Like side bar has some issue and form element's placeholder font size didn't change...

**Comment by yidifanhua** [comment]
i found that the font size between V2 and V3 are variance in Demo Template, seems V3 is much bigger than V2. the only way if i want to change it, is override the css manually ? or V3 can provide the function to change it for whole template ?
