### ISSUE TITLE
Can't Remove Sales Chart???

### ISSUE THREAD

**Issue by moseur** [almasaeed2010/AdminLTE#1658]
Dear All,

I am facing a problem with removing Sales Chart from dashboard. If I remove it then browser console show 
![image](https://user-images.githubusercontent.com/32351568/30950482-fa93ff64-a43e-11e7-97b2-1c4a7cd87481.png)

This error.
Could any body help me to solve this issue.

Thanks in advance .

Moseur Rahman

**Comment by almasaeed2010** [comment]
You need to also remove all references to Morris charts from dashboard.js file
