### ISSUE TITLE
Unable to pull latest code as bower asset

### ISSUE THREAD

**Issue by phena109** [almasaeed2010/AdminLTE#166]
Hi,

I am pretty new to composer and bower, so please forgive me ignorant if I ask stupid questions.

I created a package on packagist and pull in the latest dev (newer than 1.3) as bower asset as follow:

``` javascript
"bower-asset/admin-lte": "dev-master"
```

but it gives me the following when I run `composer update`

``` javascript
  [InvalidArgumentException]                                                                                           
  No driver found to handle Asset VCS repository http://omnipotent.net/jquery.sparkline/2.1.2/jquery.sparkline.min.js 
```

Similar packages (like dmstr/yii2-adminlte-asset) I saw also also gives the same message as long as they ask for the latest dev version rather than 1.3. Reason for choosing dev-master than 1.3 is that you haven't got the datepicker plugin included (which I consider that as a different issue).

Is it possible you can shad some light on this issue?

thanks

**Comment by phpsharma** [comment]
@miazic solution solved my problem. Thanks

Environment: ubuntu 14.04,xampp 1.8.3,
