### ISSUE TITLE
Can I get the full source code of AdminLTE "Live Preview" and/or "Docs"

### ISSUE THREAD

**Issue by amsharma9** [almasaeed2010/AdminLTE#1661]
I would like to recreate some of the features as shown in AdminLTE [Live Preview](https://adminlte.io/preview) and [AdminLTE Docs](https://adminlte.io/docs). Can I possibly get the full source code (including all CSS, JS files etc) of these live websites. If yes, where can I download it.

Thanks
Amal

**Comment by almasaeed2010** [comment]
You can download the latest release from: https://github.com/almasaeed2010/AdminLTE/releases

**Comment by amsharma9** [comment]
@almasaeed2010 That link contains only AdminLTE. I wanted the Full source of the current and live **Live Preview** and the **Docs** websites which exist on your server. I am looking for solution to some of the issues like changing only the content without refreshing the left sidebar menu and **some other issues** which are not present on your live websites.

Thanks
