### ISSUE TITLE
Pro Version

### ISSUE THREAD

**Issue by macfs36** [almasaeed2010/AdminLTE#1663]
AdminLte2 is amazing beautiful and simple, is there a paid version of adminLte2 with more features?
Thank you for this beautiful free template.

**Comment by Reconix** [comment]
I think the real question is what features are you after?
There's already a rather nice foundation for anyone to build upon.

**Comment by macfs36** [comment]
I asked because of the LTE name, I thought it was a light version of another.
I would like a form wizard like this: https://wrappixel.com/ampleadmin/ampleadmin-html/ampleadmin-minimal/form-wizard.html

Thanks

**Comment by macfs36** [comment]
Obrigado.
