### ISSUE TITLE
What to use instead of $.AdminLTE?

### ISSUE THREAD

**Issue by rozhok** [almasaeed2010/AdminLTE#1667]
Hey guys, trying to setup rails with turbolinks + adminLTE 2.4.0 and faced issue with fixing body height. Method just doesn't called because turbolinks prevents it. 
There is solution in #563, but it uses `$.AdminLTE` which is undefined in my setup (as well as on demo page).
What should I use instead of it or how can I manually call height fix code?

Thanks.

**Comment by almasaeed2010** [comment]
The height responds to window resize events so you could trigger the event manually using one of the following methods:

```
# Option 1
$(window).trigger('resize');

# Option 2
if(typeof Event === 'function') {
    window.dispatchEvent(new Event('resize')); // All browsers other than IE
} else {
    // IE support
    var resizeEvent = window.document.createEvent('UIEvents'); 
    resizeEvent .initUIEvent('resize', true, false, window, 0); 
    window.dispatchEvent(resizeEvent);
}
```

Let me know if that doesn't work.

Thanks!

**Comment by rozhok** [comment]
@almasaeed2010 yep, it does work. Thank you!
