### ISSUE TITLE
Some plans to migrate to Bootstrap 4 when it be stable?

### ISSUE THREAD

**Issue by EliuTimana** [almasaeed2010/AdminLTE#1671]
**Bootstrap 4** has a great new features and **Bootstrap 3** will be not maintained and discontinued since the first beta of BS4.
Would you like to migrate this awesome project to the latest version of the framework that it's based?, when it be stable, of course. #

**Comment by Tomirad** [comment]
I join EliuTiman's question.

**Comment by almasaeed2010** [comment]
Glad to see interest in a BS4 version. We do have plans to migrate to BS4 when it is stable. Some work has already started on this.

**Comment by tuotuogeneral** [comment]
Thank you for all the people who have never met, and the value of what you've done is immeasurable. Thank you very much. You are admirable people

**Comment by almasaeed2010** [comment]
AdminLTE 3 dev is now available for testing with Bootstrap 4 support https://github.com/almasaeed2010/AdminLTE/tree/v3-dev

Would love to hear your opinions, issues and comments!
