### ISSUE TITLE
BoxWidget collapse issue when box inside box

### ISSUE THREAD

**Issue by rmgc77** [almasaeed2010/AdminLTE#1681]
When I have a box inside a box, if I colapse the child box, the parent box colapses as well. 
I found this issue only after I upgraded from 2.3 to 2.4

 In adminlte.js, the BoxWidget toggle method is called twice after clicking the collapse button of the child box. Child box triggers the toogle method for itself and also for parent box.
If you click the parent box collapse button, toggle method is only called once, and only the parent box is toogled.

I can't figure out why. It seams a simple fix if you can find the source of the problem.

**Comment by rmgc77** [comment]
Example of the issue on fiddle: https://jsfiddle.net/ayeojg9o/

**Comment by rmgc77** [comment]
I've commited a modification that solves this issue.

**Comment by fatoskurtishi** [comment]
Still having problems with version 2.4.2 ? any issue ?

**Comment by rmgc77** [comment]
Hello, problem solved. I got a branch from another user that solved the issue. Don't remember witch one.

Rui Camarinha,
934921312

________________________________

**Comment by interludic** [comment]
Still seems to be an issue
