### ISSUE TITLE
Datatable of AdminLte Paginate type Change 

### ISSUE THREAD

**Issue by DeepGandhi1602** [almasaeed2010/AdminLTE#1687]
DataTable PaginateType:input not work so that i added cdn from https://cdn.datatables.net/plug-ins/1.10.16/pagination/input.js and then it has css problem help me to solve

**Comment by lenamtl** [comment]
The best way to fix the problem is using Chrome dev tool (right click inspect) to see the CSS class name and the file so you can edit it.
