### ISSUE TITLE
Conflict with prototype js and scriptaculous

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#169]
I have a script working with jquery, and prototype js and scriptaculous but when i import it into the design, prototype js does not work anymore. I have tried most work around. Is there a solution to this ? I have also asked the question many times on http://almsaeedstudio.com/ without answer.

**Comment by sachiaj** [comment]
Sir, I have used AdminLTE template and I am facing same problem of app.js and prototype.js confliction. I want help in this case.
following js are used for modalbox
<script src="pop/prototype.js" type="text/javascript" charset="utf-8"></script> 
  <script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js?load=effects" type="text/javascript" charset="utf-8"></script> 
  <script type="text/javascript" src="pop/modalbox.js"></script> 

plz help me out

**Comment by kressly** [comment]
Hello
It all depends on the kind of conflict you are facing but generally you will have to put jquery in no conflict mode and open app.js and bootstrap.js and other code that uses jquery and put it in noconflict mode with the  second noconflict code
