### ISSUE TITLE
Please remove links to bower_components in select2 and all other plugins

### ISSUE THREAD

**Issue by acacha** [almasaeed2010/AdminLTE#1692]
Change all lines:

```
@import (reference) "../../bower_components/bootstrap/less/mixins";
@import (reference) "../../bower_components/bootstrap/less/variables";
```

To:

@import (reference) "../bootstrap-less/mixins";
@import (reference) "../bootstrap-less/variables";

in all publins files like select2 or fullcalendar as I think this change is also made before in AdminLTE.less file.

**Comment by DroidNinja** [comment]
Changes are not showing in the latest build. Still showing bower_components related paths.

**Comment by JohnCashmore** [comment]
When is this going to be released?
