### ISSUE TITLE
Links including fragments (#id) don't seem to work

### ISSUE THREAD

**Issue by mvelosop** [almasaeed2010/AdminLTE#1696]
Hi, I'm trying yo link to a id in a page including the #id in the url, and so it goes in the begining (checking with the debugger), but then the page always scrolls back to the top.

But I haven't been able to identify where that happens.

Is there something in AdminLTE scripts that do this? is there some way to stop it?

Thanks.

**Comment by bellwood** [comment]
In 2.4 examples, I added `id="comment"` to the box that holds the picture of the chairs.

If i then navigate to that page `widgets.html#comment` it scrolls down and stays.

What version are you using and are you using any custom scripts?

**Comment by mvelosop** [comment]
Thanks @bellwood, I'm sorry for the delay.

That works if you're already on that page, but not if linked from another page.

i.e., in 2.4:

line 500 on index2.html does not work:
`<li><a href="pages/widgets.html#comment"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>`

line 492 on widgets.html does work:
`<li><a href="widgets.html#comment"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>`

I tried this in Chrome on Incognito mode, that disables extensions to avoid interferences.
