### ISSUE TITLE
Fixed Footer (Visible all time)

### ISSUE THREAD

**Issue by vibs2006** [almasaeed2010/AdminLTE#1711]
Is there any class or option by which I can also have a **Fixed Footer** along with a Fixed Header.  I have a requirement where I have to make a dashboard where footer has to display some dynamic and real time information like a clock timer and therefore needs to be **visible at all times**. 

Its working for header perfectly but I need for Footer as client is specifically demanding that only 

CC: @almasaeed2010 please guide if possible

**Comment by almasaeed2010** [comment]
See fixed to bottom navbar from Bootstrap: https://getbootstrap.com/docs/3.3/components/#navbar-fixed-bottom

**Comment by vibs2006** [comment]
@almasaeed2010 Thanks for replying. It was helpful however can u also suggest under which tag shall I put nav bar as it is getting spanned across the whole width of page rather than the **content-wrapper**.

**Comment by bellwood** [comment]
Simply change `<footer class="main-footer">` to `<footer class="main-footer navbar-fixed-bottom">`

Works for me on 2.4

**Comment by vibs2006** [comment]
@bellwood It worked **perfectly**. I'm really grateful to you
