### ISSUE TITLE
Is it possible to store in database the new position of div after drag and drop?

### ISSUE THREAD

**Issue by Matteobikk90** [almasaeed2010/AdminLTE#1717]
Hi,

amazing plugin. :-)

I am working on new dashboard and I really like your plugin so I think I will use it but I couldn't find any explanation of how store the drag and drop div once changed.

After I refresh the page they come back to their previous position.

Thanks for help

**Comment by REJack** [comment]
Duplicate of #1594

**Comment by Matteobikk90** [comment]
Thanks a lot
