### ISSUE TITLE
[question] - Top navbar - How to set width to "auto" for a given DOM element ? 

### ISSUE THREAD

**Issue by cavo789** [almasaeed2010/AdminLTE#1730]
Hi all

Thank you to all contributors for AdminLTE; this template is really great ! 

I've a question about the top nav-bar : I would like to put a search text box with a max-width (f.i. 400px) (I can do this) but, on small screen, I would like to say "width:auto;" but it doesn't work.

My wish is to be able to add icons dynamically (=I don't know how many icons will be displayed) so, on small screens, I would like that the search text box takes the rest (width:auto I think).

Here is my test URL : [https://www.marknotes.fr/](https://www.marknotes.fr/)

What I would like (automatically) (see the top nav, the search box takes as many space it can)
![2017-11-13_09h34_17](https://user-images.githubusercontent.com/355999/32716364-f876276c-c855-11e7-8692-1aa039871bcf.png)

What I 've at this moment (I play with media queries; the search box should be resized automatically)
![2017-11-13_09h34_28](https://user-images.githubusercontent.com/355999/32716373-00e09fea-c856-11e7-950b-0e5be46c9047.png)

Any help would be greatly appreciated !

Thanks !!!

**Comment by almasaeed2010** [comment]
Hello @cavo789 

You may want to use CSS media queries. Please see https://www.w3schools.com/cssref/css3_pr_mediaquery.asp for more information.

Thanks!
