### ISSUE TITLE
Use ajax to load a  box component  ,the 'remove'  Box Tools can not work .

### ISSUE THREAD

**Issue by chernikite** [almasaeed2010/AdminLTE#1732]
### Issue type:
[ ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.2
* Operating System:  windows
* Browser (Version):  All

### Description:
when I use ajax to load a page of box component, the box display ok, but the tool 'remove' can not work,
I  read the code,and find a way to fix this, when the ajax load done, call $(window).trigger("load"); 
my code:
//ajax load
 MySection.load(href, function(response, status, xhr) {
		MySection.trigger("aload");
		 }
//use  a  event named 'aload' to call  $(window).trigger("load");
	                    MySection.bind("aload",function(){
				$(window).trigger("load");//the remove rework 
			    });
//

**Comment by almasaeed2010** [comment]
Hello,

You could use `$('.box').boxWidget();` after loading any new boxes.

Thanks!

**Comment by liuyang19900520** [comment]
thanks very much!
