### ISSUE TITLE
Incorrect version in bundled downloads

### ISSUE THREAD

**Issue by philip** [almasaeed2010/AdminLTE#1733]
The v2.4.2 files refer to v2.4.0. 

To reproduce:
1. Download v2.4.2 from https://github.com/almasaeed2010/AdminLTE/releases (either zip or tar.gz)
2. Open files, such as `dist/js/adminlte.js`, and note `@version 2.4.0`.

I'm not sure if it's only the version tag that's incorrect or if the files themselves are v2.4.0.

**Comment by philip** [comment]
This appears to be a common issue as the `2.3.11` download includes `@version 2.3.8` in the files.

**Comment by almasaeed2010** [comment]
Thanks for letting us know!

In the new versions of AdminLTE this will be automated and therefore lessen the possibility of this happening again.

Thanks!
