### ISSUE TITLE
Imcompatible with Jquery no conflict

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#174]
If you add 
$.noConflict(); to anywhere and even if you don't add any other library the design Bug. The link that scrool stop working and other stuff

**Comment by webdevilopers** [comment]
Is this still an issue? I'm using the current version and get:
```
TypeError: $ is undefined
... new Error("AdminLTE requires jQuery");$.AdminLTE={},$.AdminLTE.options={navbarM...
TypeError: $(...) is null
$("#box-widget").activateBox();
```

My config:
```html
                        <script type="text/javascript" src="/bundles/sonatacore/vendor/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="/bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js"></script>
        <script type="text/javascript">var $j = jQuery.noConflict();</script>

        <!-- admin-lte -->
        <script src="/bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js"></script>
        <link href="/bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css" type="text/css" rel="stylesheet" />
        <link href="/bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css" type="text/css" rel="stylesheet" />
        <!-- /admin-lte -->

        <script type="text/javascript">
        //<!--
        $j(document).ready(function() {
            $j.datepicker.setDefaults($j.datepicker.regional['de']);
        });
        //-->

        </script>
```

Some box widget:
```html
<div class="box box-default collapsed-box">
  <div class="box-header with-border">
    <h3 class="box-title">Expandable</h3>
    <div class="box-tools pull-right">
      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
    </div><!-- /.box-tools -->
  </div><!-- /.box-header -->
  <div class="box-body">

  </div><!-- /.box-body -->
</div><!-- /.box -->

<script>
    $("#box-widget").activateBox();
</script>
```

**Comment by webdevilopers** [comment]
First of all it looks like the `noConflict` mode has to be set after the `app.js`:

```html
<script type="text/javascript" src="/bundles/sonatacore/vendor/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js"></script>

        <!-- admin-lte -->
        <script src="/bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js"></script>
        <link href="/bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css" type="text/css" rel="stylesheet" />
        <link href="/bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css" type="text/css" rel="stylesheet" />
        <!-- /admin-lte -->

<script type="text/javascript">var $j = jQuery.noConflict();</script>
```

Now I get:
```
TypeError: a.AdminLTE.boxWidget is undefined
...se strict";a.fn.activateBox=function(){a.AdminLTE.boxWidget.activate(this)}}(jQu...
	
TypeError: $(...) is null
...92,lg:1200}},$(function(){"use strict";$("body").removeClass("hold-transition"),...
```

Does the `boxWidget` require an extra `js` file?

**Comment by webdevilopers** [comment]
Next I wrapped the widget into the `ready` event:

```javascript
<script type="text/javascript">
//<!--
$j(document).ready(function() {
    $j("#box-widget").activateBox();
});
</script>
```

Currently I get:
```
TypeError: $(...) is null
...92,lg:1200}},$(function(){"use strict";$("body").removeClass("hold-transition"),...
```

**Comment by webdevilopers** [comment]
I just checked the versions, are they fine?

* AdminLTE app.js @version 2.3.0
* jQuery v2.1.4
* jQuery UI - v1.10.4
* Bootstrap v3.3.5

**Comment by webdevilopers** [comment]
I also downgraded to jQuery **1.12.0**:

```
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
```

And adding the option:
```
        <script>
            var AdminLTEOptions = {
                //Box Widget Plugin. Enable this plugin
                //to allow boxes to be collapsed and/or removed
                enableBoxWidget: true
            };
        </script>
        <script src="{{ asset('bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js') }}"></script>
```

Still getting:
```
TypeError: $(...) is null
...92,lg:1200}},$(function(){"use strict";$("body").removeClass("hold-transition"),...
```

**Comment by kressly** [comment]
Will check my config and get back to you. But first what libraries are you using aside of Jquery ? Because so far i see only jquery based code in code. And if you are not using any other library aside of Jquery like prototype js for example, there is no need of jquery no conflict

**Comment by webdevilopers** [comment]
Thanks for having a look at this @kressly . Indeed I missed the prototype lib:

```html        
<script type="text/javascript" src="{{ asset('templates/js/prototype.js') }}"></script>
<script type="text/javascript" src="{{ asset('templates/js/effects.js') }}"></script>
<script type="text/javascript" src="{{ asset('templates/js/builder.js') }}"></script>
<script type="text/javascript" src="{{ asset('templates/js/controls.js') }}"></script>
<script type="text/javascript" src="{{ asset('templates/js/dragdrop.js') }}"></script>
<script type="text/javascript" src="{{ asset('templates/js/popup.js') }}"></script>
```

It is added after this block:
https://github.com/almasaeed2010/AdminLTE/issues/174#issuecomment-202818201

And indeed if I remove these files everything works fine! It is a very old version:
**Prototype JavaScript framework, version 1.6.0**

**Comment by kressly** [comment]
What file did you remove and is everything working now ? What file did you remove ?

**Comment by webdevilopers** [comment]
I removed all the prototype files I added in the last comment.

**Comment by kressly** [comment]
Ok. So are you satisfied now or you need help ? IF you want to keep prototype files, you will have to add the no conflict mode to each jquery file. If you are satisfied let me know and i will close the discussion. If you are not, i will provide you with more details help after i do that with the new design

**Comment by webdevilopers** [comment]
Thanks! This should work fine for me as I will no longer be loading the prototype files in the new module.
Guess it makes no sense to do further research what is actually causing the issue with such an old prototype lib?

**Comment by kressly** [comment]
I have taken my time and downloaded the latest template of Adminlte and i have tried to put it in no conflict but just like you i am facing a couple of challenges: Everythings works perfectly except the fact that the calendar, the visitor and the graph are all broken.

I am using the latest version of prototype js prototype_1_7_3 and the latest version of Jquery. So i think the problem is NOT with prototype js. I think there is something we are missing somewhere

**Comment by webdevilopers** [comment]
Ouch! I'm currently working for a different company now. But if you have anything to test with the `boxWidget` I could recall my code.

**Comment by kressly** [comment]
Yes please show me code. I am facing challenges with some of the codes in the new version when it comes to no conflict mode

**Comment by kressly** [comment]
I have realized that the problem has to do with the jquery ui library. In no conflict mode it is not working. So the question here is how to put jquery ui in no conflict mode

**Comment by webdevilopers** [comment]
I always thought the UI has to be used w/ jQuery itself that's why UI would adapt the noConflict mode.

Maybe this one helps?
https://github.com/twbs/bootstrap/issues/6303#issuecomment-11494897

**Comment by webdevilopers** [comment]
https://github.com/twbs/bootstrap/issues/6303

**Comment by kressly** [comment]
Tks a lot . I was able to put bootstrap in noconflict mode. My problem now is how to effectively put app.js in noconflict mode because in no conflict mode when i click on the menu nothing happens, it no longer reduces or increases.

**Comment by webdevilopers** [comment]
Actually the boxWidget was the only thing I ever tried. The original implementation for other use cases always came from the Sonata Admin bundle.

**Comment by kressly** [comment]
Oh ok otherwise i just solved also the app.js
Now my last challenge on the first page is the fact that on the chart when i click on donut , Area disapears
