### ISSUE TITLE
Dropdown menu not respect area

### ISSUE THREAD

**Issue by IgorDePaula** [almasaeed2010/AdminLTE#1745]
### Issue type:
[ ] Feature request 
[x] Bug report     
[ ] Documentation 

### Environment:
* AdminLTE Version:  
* Operating System:  ubuntu 17.10
* Browser (Version): firefox 57

    BUG REPORTS must include:
        * Steps or URL needed to reproduce the bug/issue
https://adminlte.io/themes/AdminLTE/pages/UI/buttons.html
        * Any relevant error messages (screenshots may also help)

See screenschot

        * A snippet of your markup (where applicable)

    FEATURE REQUESTS must include

### Description:

The dropdown menu not repect area, see image

![selecao_034](https://user-images.githubusercontent.com/2833993/33232485-5c06ecca-d1ee-11e7-9d16-47068c841048.png)

**Comment by almasaeed2010** [comment]
Hello @IgorDePaula 

This is a known issue in Bootstrap 3 where dropdowns don't appear correctly in tables. However, you may attempt using this fix as described on the Bootstrap documentation: https://getbootstrap.com/docs/3.3/components/#btn-groups

>When using tooltips or popovers on elements within a .btn-group, you'll have to specify the option container: 'body' to avoid unwanted side effects (such as the element growing wider and/or losing its rounded corners when the tooltip or popover is triggered).

Thanks!

**Comment by IgorDePaula** [comment]
I used bootstrap and not have this problem

2017-11-26 14:10 GMT-02:00 Abdullah Almsaeed <notifications@github.com>:
