### ISSUE TITLE
Need to bind adminLTE menu dynamically from database in asp.net master page.

### ISSUE THREAD

**Issue by sathishpsy89** [almasaeed2010/AdminLTE#1760]
Hi,

 I like to bind menu dynamically from database in asp.net master page. 
 [Note: Without using asp.net repeater control]

 Because we are facing postback issue in master page.so every time the page is get refreshed.is there any work around to stop post back page refreshing in adminLTE theme in master page.

**Comment by lenamtl** [comment]
This is a template, so unfortunately we cannot help you with your server side code ...
But if you encounter any issue with non server side code we will be happy to help.
