### ISSUE TITLE
js error when use boxRefresh

### ISSUE THREAD

**Issue by dragonflylee** [almasaeed2010/AdminLTE#1767]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.2
* Operating System:  Windows 10 16299 x64
* Browser (Version):  Chrome  63.0.3239.108

### Description:
when i use $.boxRefresh like below
```
<div class="box box-primary" data-source="/manage?action=request" data-type="horizontalBar">
  <div class="box-header with-border">
    <i class="fa fa-bar-chart"></i>
    <h3 class="box-title">Chart</h3>
    <div class="box-tools pull-right">
      <a class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></a>
      <a class="btn btn-box-tool refresh-btn"><i class="fa fa-refresh"></i></a>
    </div>
  </div>
  <div class="box-body">
    <div class="chart-responsive"><canvas></canvas></div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('.box[data-source]').boxRefresh({
    loadInContent: false,
    responseType: 'json',
    onLoadDone: function(data) {
      console.log(data);
    }
  })
 })
</script>
```
i got Uncaught TypeError: b.replace is not a function
    at Function.ga.matchesSelector (jquery.min.js:2)
    at Function.r.filter (jquery.min.js:2)
    at Ka (jquery.min.js:3)
    at r.fn.init.remove (jquery.min.js:3)
    at f._removeOverlay (adminlte.min.js:14)
    at f.<anonymous> (adminlte.min.js:14)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

it seems that Overlay is not work

**Comment by camweir** [comment]
I found the same error. The call to .remove is not correct. I changed the adminlte.js function

`     f.prototype._removeOverlay = function() {
        a(this.element).remove(this.$overlay)
    }
`
to the following:
`  ,
    f.prototype._removeOverlay = function() {
        a(this.$overlay).remove()
   }
`

**Comment by GrayTechnical** [comment]
@camweir 's fix worked here as well.   Many Thanks!!! 👍

**Comment by OldaHorak** [comment]
Hi, I just open new Issue #1976 'cause the error (and more in the same plugin) is not yet repaired in the last version. I hope it can help.

**Comment by OldaHorak** [comment]
Hi! The request #1981 just pulled, this issue should be closed, thanks!
