### ISSUE TITLE
 RTL direction support

### ISSUE THREAD

**Issue by imadhussein** [almasaeed2010/AdminLTE#1780]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by AkramA7med** [comment]
hello
i had did it from while but i didn't have any time to post it 

so i attached files any one now can use it for V 2.4.2
[AdminLTE RTL.zip](https://github.com/almasaeed2010/AdminLTE/files/1653752/AdminLTE.RTL.zip)

in your header

add this 
`<link rel="stylesheet" href="AdminLTE/bower_components/bootstrap/dist/css/bootstrap.rtl.css" />`

after 
`<link rel="stylesheet" href="AdminLTE/bower_components/bootstrap/dist/css/bootstrap.css" />`


and 

`<link rel="stylesheet" href="AdminLTE/dist/css/AdminLTE.rtl.css" />`

after your skin CSS

enjoy

**Comment by twf-nikhila** [comment]
@AkramA7med Fantastic works really good. Thanks for sharing (y)
