### ISSUE TITLE
js dataTables can't work

### ISSUE THREAD

**Issue by wongpenghong** [almasaeed2010/AdminLTE#1783]
why my data table can't pagination ?
i already call css and js
thank you

**Comment by lenamtl** [comment]
I'm using Datatables on all my pages and never encounter any issue.
Check your console right click inspect and check errors.
Datatables have a forum where you can post your question.

**Comment by REJack** [comment]
If you can't see pagination and/or column sort function, check your generated HTML code. DataTables crashs everytime if thead has more/less columns than tbody, both need to be even.
