### ISSUE TITLE
JS Error : Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

### ISSUE THREAD

**Issue by Moranbzh** [almasaeed2010/AdminLTE#1786]
Hi,

I have a Javascript error in the browser console with fullcalendar-3.8.0 and fullcalendar-scheduler-1.9.1 : 

> Uncaught TypeError: Cannot read property 'datepickerLocale' of undefined

![error_fullcalendar](https://user-images.githubusercontent.com/25210066/34786292-077d4086-f634-11e7-875b-268acaa7a91a.png)

I have installed fullcalendar and fullcalendar-scheduler in the drupal libraries folder. I have created a simple JS file with the following code : 

`jQuery(document).ready(function($) {

	$('#calendar').fullCalendar({
		schedulerLicenseKey : 'GPL-My-Project-Is-Open-Source',
		editable : true,
		scrollTime : '00:00',
		defaultDate : '2018-01-02',
		defaultView : 'timelineDay',
		resourceLabelText : 'Rooms',
		resources : [ {
			id : 'R1',
			title : 'Room 1'
		} ],
		events : [ {
			id : '1',
			resourceId : 'R1',
			start : '2018-01-02T02:00:00',
			end : '2018-01-02T07:00:00',
			title : 'First event'
		} ]
	});
});`

It looks like the calendar is not displayed very well too... According to the JS console, the error is located in the locate-all.js file. I tried to configure a locale (like `lang:'fr'` or `locale:'fr'`) in the fullcalendar definition but it doesn't changed anything. I am not able to find which object in the locale-all.js file is undefined. Is it a problem of configuration of fullcalendar (missing property for example) ?

Thank you.

**Comment by JNPSoftware** [comment]
Try to read from cdn:
https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/locale-all.js
put after fullcalendar.js

**Comment by cafefin** [comment]
JNPSoftware tks you, JNPSoftware , it's working
