### ISSUE TITLE
Bootstrap-4 and Material Design for AdminLTE?

### ISSUE THREAD

**Issue by a-patel** [almasaeed2010/AdminLTE#1787]
Any new project or branch for bootstrap-4 AdminLTE?
Any near future planning to upgrade?

**Comment by malenkiki** [comment]
In this post, a v3 for AdminLTE is mentioned at the first paragraph: <https://adminlte.io/blog/adminlte-v2.4-release-notes-and-upgrade-guide>. 

But I don’t know which version of bootstrap it will use…

**Comment by REJack** [comment]
Bootstrap 4 is coming with AdminLTE v3, you can look at #710.

**Comment by a-patel** [comment]
@REJack thanks for your reply.
What about material design?

**Comment by REJack** [comment]
almasaeed2010 said nothing about a whole new skin, etc for AdminLTE in the last year, but for this you can create custom skin(s).

**Comment by almasaeed2010** [comment]
I wish I had the time to implement both Material Design and Bootstrap 4. But for the time being, I am working on Bootstrap 4 version.

Thanks!

**Comment by twf-nikhila** [comment]
@almasaeed2010 Nice job with AdminLTE, really love the theme and use it for many projects.

When can we can some good version with Bootstrap 4 support? Excited to start using it. 

Thanks again for AdminLTE, best ever theme.

**Comment by opensas** [comment]
Any news on admilte3??? BTW, this project really rocks!
