### ISSUE TITLE
dropdown cant drop-down;

### ISSUE THREAD

**Issue by zbkotya** [almasaeed2010/AdminLTE#1788]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
AdminLTE Version:2.40
Operating System：win7
Browser：Google Chrome 63.0.3239.108
it‘s ok starter page loaded，but when some html code injected into content section，like this：$.get("mybalance.html",function(data){ 
		　　　　$("#context").html(data);
		　　}); 
the dorpdown on top right corner can't pull down; the mybalance.html is a complete bootstrap html including datatable plug。

**Comment by almasaeed2010** [comment]
Hello @zbkotya,

You will need to reinitialize the dropdown menu and all other JS events after pulling via AJAX. I wonder if there is a different solution but to fix your problem now, you should use 
`$('[data-toggle="dropdown"').dropdown()`

Thanks!
