### ISSUE TITLE
Contributing to Bootstrap 4

### ISSUE THREAD

**Issue by JThompsonNZ** [almasaeed2010/AdminLTE#1790]
I wanted to start contributing to the Bootstrap 4 branch. I have a couple of questions:

1. What about moving away from bower_components to node_modules ?
2. What components are required to stay
3. What components are required to be removed
4. What components are required to be added / modified
5. If v3 going to take the same shape as v2? E.G: as in the same styles, or perhaps suggest a new theme completely or modify just a little bit
6. Icons: This is my personal preference, but I now often just pull in icons as i go, either from Zondicons.com, or the new Heroicons UI set. Is font-awesome still going to be a standard approach?

**Comment by schmunk42** [comment]
Additional question: Will a v4 version of AdminLTE use https://getbootstrap.com/docs/4.0/examples/dashboard/# as a base implementation?

**Comment by EliuTimana** [comment]
we should start using webpack too 😃

**Comment by JThompsonNZ** [comment]
@schmunk42 @EliuTimana I've written some notes of some changes i'm going to make to my own copy

However, review this list and see if this is what you'd like to see in the bs4 version

https://github.com/JThompsonNZ/AdminLTE/blob/master/README.md

**Comment by JThompsonNZ** [comment]
Here's a roadmap that i'm working on for AdminLTE v3. Some of these might not be wanted/required in the V3 version, but i'll do a PR when i'm ready and a decision can be made:

- use webpack
- use official bootstrap 4 stable
- change project structure to be more like bootstrap 4 (e.g: scss as a parent directory instead of within the build directory)
- rename skins to themes (it's more evident to some people of what it is)
- add a card variant for boxes
- remove the use of bower_components. use node_modules and an optional plugins directory for those downloading the repository

- change documentation to something like Jekyll with AdminLTE theme??
- various other changes

**Comment by schmunk42** [comment]
> rename skins to themes (it's more evident to some people of what it is)

I'd keep *skins*, since AdminLTE is a theme, but it's different colors are skins.

Just my 2 cents ;)

**Comment by JThompsonNZ** [comment]
@schmunk42 Yep okay,

What about everything else i've listed? Cool with that? Also, anything else to add in mind?

I think one of the bigger things with bootstrap 4 is the use of utility classes on components (e.g: AdminLTE has a mixin for progress bar for the different colours, but now BS4 makes use of ``.bg-{colour}`` instead).

I figure, keeping everything to the same sort of standard BS4 is would be best, and a bonus of it is it removes a lot of no-longer-needed styles.

**Comment by schmunk42** [comment]
Sorry, haven't reviewed all the other points in detail.

> So stick with webpack, or laravel mix?

If changes to the current build process are required then `webpack`.

**Comment by almasaeed2010** [comment]
Hello @JThompsonNZ 

It's great to see enthusiasm about AdminLTE 3 :D 

You bring up some good points here. I am still in the process of deciding how to structure v3 and what tools to use. I plan on opening a discussion "issue" soon to address the compiling process and other things like the upgrade process and what it entails.

As to contributing to building v3, I think it's best to do that when we have an agreed upon base to build from. Once that's in place, I'd appreciate all the help I can get to upgrade pages to use Bootstrap 4 and AdminLTE 3 elements.

Here is what I think regarding Laravel-mix vs WebPack. I love Laravel Mix and really wish I could use it here but as you mentioned it's somewhat of an overkill and not necessary for many projects. I started implementing a WebPack solution for v3 already that I will push to v3-dev branch soon.

Thanks! Let's continue this discussion once we have a good base for v3.
