### ISSUE TITLE
Is there a Drupal 8 AdminLTE theme available for purchase?

### ISSUE THREAD

**Issue by zigmoo** [almasaeed2010/AdminLTE#1795]
Hello Abdullah,

I’m a big admirer of your work!

I am reaching out in hopes that you may have a drupal 8 theme version of AdminLTE available for purchase?

Thanks in advance for any reply,

Jason

**Comment by almasaeed2010** [comment]
Hello @zigmoo 

Unfortunately, I am not aware of any Drupal implementations for AdminLTE.

Thanks!
