### ISSUE TITLE
Hiding menu header when no "sub" li exists.

### ISSUE THREAD

**Issue by tpresing** [almasaeed2010/AdminLTE#1798]
Hi,
 
My question is, how can I hide menu header when no li after header exists. I tried it with php and js and no success :( Is there any solution for that?
Its not a multidimensional array the header is just a string and li's are arrays.

Thx

**Comment by tpresing** [comment]
The only think I can done is this, it works, but I prefer to solve this with php.

`$('.sidebar-menu li.header').each(function(){
			if($(this).nextUntil('.header').length == 0){
				$(this).remove();
			}
		});`

**Comment by REJack** [comment]
AdminLTE doesn't provide PHP examples, but if you post me your code I can take a look over it.
