### ISSUE TITLE
WYSIHTML5 - Page becomes unresponsive when 'Add Link' process is canceled

### ISSUE THREAD

**Issue by reignydeyz** [almasaeed2010/AdminLTE#1799]
Steps to reproduce...

1. From **WYSIHTML5** editor
1. Highlight a text then click the **Add Link** Icon
1. Add a valid link
1. Click **Insert Link**
1. Now select the link
1. Click the **Add Link** Icon again
1. Place some invalid text. eg. "ABC123"
1. Click **Cancel**
1. Page becomes unresponsive

**Comment by reignydeyz** [comment]
I've tested it using Firefox 57 and Chrome 63...
![capture](https://user-images.githubusercontent.com/25072559/35471368-deed972e-0394-11e8-91fa-b1bb44ddf44a.PNG)

**Comment by lenamtl** [comment]
Check errors in browser console (right click inspect).

This seems to be a WYSIHTML5 issues you can try to update the WYSIHTML5 script or check their issue list check https://github.com/xing/wysihtml5
