### ISSUE TITLE
AdminLTEOptions Can not work yet? I set before adminlte.js, but invalid.

### ISSUE THREAD

**Issue by 521daichen** [almasaeed2010/AdminLTE#1800]
Can not work yet? I set before adminlte.js, but invalid.

My options:

```
<script>
    var AdminLTEOptions = {
        //Enable sidebar expand on hover effect for sidebar mini
        //This option is forced to true if both the fixed layout and sidebar mini
        //are used together
        sidebarExpandOnHover: true,
        //BoxRefresh Plugin
        enableBoxRefresh: true,
        //Bootstrap.js tooltip
        enableBSToppltip: true
    };
</script>
```

**Comment by REJack** [comment]
It's not hard, 
1. for sidebarExpandOnHover you need to add `data-expand-on-hover="true"` to a.sidebar-toggle (`data-toggle="push-menu"`)
2. for BoxRefresh look at https://adminlte.io/docs/2.4/js-box-refresh
3. for BSTooltips you need to add `data-toggle="tooltip"` to the element

regards REJack
