### ISSUE TITLE
How to make scroll work independent of other area?

### ISSUE THREAD

**Issue by freechelor** [almasaeed2010/AdminLTE#1804]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.2
* Operating System:  Windows 10
* Browser (Version):   Chrome (Latest) - 63.0.3239.132

### Description:
What I want to do is separate scroll region, 
i.e. side nav bar and contents part, so, when I scroll on side nav bar(left side), side menu scrolls, and when I scroll on main contents(right side), contents will go up and down.

I found that wherever I scroll, both side bar and contents moves together.

![image](https://user-images.githubusercontent.com/5378934/35591608-337c8376-05d0-11e8-95a0-d4c6ca5c0485.png)

Code structures are like the following.
1. layout

> 
<html>
<head>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    @RenderBody()
    @* Bundles assume jquery 2.1.3 and Bootstrap 3 *@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqgrid")
    @RenderSection("scripts", required: false)
</body>
</html>

2. side nav bar

> 
    <aside class="main-sidebar sidebarscroll" style="float:left">
    
    <section class="sidebar">
        
          // some menu list comes here

3. contents 

> <div class="wrapper">
    <div class="content-wrapper">
        <section class="content-header">
         // some information for header comes here
        </section>
        <section class="content">
        </section>
     </div>
</div>

Where could I start to achieve what I want to do?

**Comment by REJack** [comment]
You only need to add `fixed`-class on body, like this `<body class="skin-blue sidebar-mini fixed">`.

**Comment by freechelor** [comment]
@REJack 
Thanks for your reply.
However, when I apply your guide to my code,
scroll works fine for contents area, but when I move mouse to side nav bar area, scroll does not work.
I want to make scroll work for both area, but independent of each other.

**Comment by REJack** [comment]
It sounds like you doesn’t loaded the SlimScoll script before AdminLTE

Mit freundlichen Grüßen
Raphael Jackstadt

Von meinem iPhone gesendet

**Comment by freechelor** [comment]
Great!
With slimscroll applied, it works well.

Very appreciate for your help,
