### ISSUE TITLE
Customize CSS for big detailed form

### ISSUE THREAD

**Issue by DarioN1** [almasaeed2010/AdminLTE#1805]
I'm trying to customize AdminLTE2 in order to implement a form that has to manage lot of informations.

I have to render lot of textboxes, textareas, tabless with lot of rows...

In the starting version of AdminLTE2 all the form controls, font-size, table row etc... Are rendered too big for my needs.

Is there a way to set at high level the size of all the content objects?

I have to resize more or less all the components:

Fonts
Table Row Heigh
Span label
Form controls
Is there a High level class to set or do I have to do it manually?

Thanks to support

**Comment by almasaeed2010** [comment]
Hello @DarioN1 
Unfortunately, I don't think Bootstrap or AdminLTE offers that control for tables. You'll have to use control classes on all the components such `.text-sm` and `.input-sm`.

Thanks!
