### ISSUE TITLE
I am using the template for an email application but when i start sending email it just stops at sending some emails like 40 to 50 emails and stops with a error " Thread was being aborted "

### ISSUE THREAD

**Issue by arefur** [almasaeed2010/AdminLTE#1810]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by shiroamada** [comment]
adminlte just a Front End Framework. Sending Email is your backend engine was doing the work. It should be nothing related with adminlte
