### ISSUE TITLE
Publish 2.4.3 to NPM

### ISSUE THREAD

**Issue by Hornet-Wing** [almasaeed2010/AdminLTE#1816]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.2
* Operating System:  Windows 10
* Browser (Version):  Chrome (Latest)

### Description:
Hi @almasaeed2010 ,
Thanks for this template. Could you please publish the updated (2.4.3) version to NPM?

Thank you!

**Comment by rafakwolf** [comment]
any news about this ?

**Comment by eman1986** [comment]
looks like this was finally done, got saw npm updating my instance of it
