### ISSUE TITLE
Any expected date for Admin LTE with bootstrap 4?

### ISSUE THREAD

**Issue by rishabhack** [almasaeed2010/AdminLTE#1819]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by kohenkatz** [comment]
#710

**Comment by sam123sam123** [comment]
#710 is 2 years old.  So a status update may be in order.

**Comment by almasaeed2010** [comment]
AdminLTE 3 dev is now available https://github.com/almasaeed2010/AdminLTE/tree/v3-dev :D

**Comment by rishabhack** [comment]
thanks for replay i am developing live project by using new AdminLTE 3 dev with bootstrap 4.
Having a few issue but nice.
Having issue with ASP.NET Core while work fine asp.net freamwork

**Comment by fabiopesaju** [comment]
any news, @rishabhack ???

**Comment by eugenevdm** [comment]
I am a bit confused if AdminLTE is Bootstrap 3 or Bootstrap 4. For example, on this page, the title reads:

AdminLTE - Free Premium Admin control Panel Theme Based On **Bootstrap 3.x** https://adminlte.io

https://github.com/almasaeed2010/AdminLTE/tree/v3-dev

Yet the introductory paragraph reads:

AdminLTE is a fully responsive administration template. Based on **Bootstrap 4** framework.

Any ideas?

**Comment by BoraVivek** [comment]
> I am a bit confused if AdminLTE is Bootstrap 3 or Bootstrap 4. For example, on this page, the title reads:
> 
> AdminLTE - Free Premium Admin control Panel Theme Based On **Bootstrap 3.x** https://adminlte.io
> 
> https://github.com/almasaeed2010/AdminLTE/tree/v3-dev
> 
> Yet the introductory paragraph reads:
> 
> AdminLTE is a fully responsive administration template. Based on **Bootstrap 4** framework.
> 
> Any ideas?

https://github.com/almasaeed2010/AdminLTE/tree/v3-dev

This branch is based on Bootstrap 4 , it's description is wrong.

**Comment by xiaozhou0211** [comment]
> > I am a bit confused if AdminLTE is Bootstrap 3 or Bootstrap 4. For example, on this page, the title reads:
> > AdminLTE - Free Premium Admin control Panel Theme Based On **Bootstrap 3.x** https://adminlte.io
> > https://github.com/almasaeed2010/AdminLTE/tree/v3-dev
> > Yet the introductory paragraph reads:
> > AdminLTE is a fully responsive administration template. Based on **Bootstrap 4** framework.
> > Any ideas?
> 
> https://github.com/almasaeed2010/AdminLTE/tree/v3-dev
> 
> This branch is based on Bootstrap 4 , it's description is wrong.

I have download it, and I have checked in: 
C:\Users\userName\Desktop\AdminLTE\bower_components\bootstrap\dist\css\bootstrap.min.css

/*!
 * Bootstrap v3.4.1 (https://getbootstrap.com/)
 * Copyright 2011-2019 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */

It still bootstrap 3 ?

**Comment by bphamous** [comment]
Hi, any update on the release of a BS4 version? Thank you.
