### ISSUE TITLE
Feature request - Error page

### ISSUE THREAD

**Issue by WHK102** [almasaeed2010/AdminLTE#1835]
Please, add a error page, by example: Error 404, 500, etc and generics messages in full area.

**Comment by lenamtl** [comment]
You can use 
https://adminlte.io/themes/AdminLTE/pages/examples/404.html and https://adminlte.io/themes/AdminLTE/pages/examples/500.html

**Comment by WHK102** [comment]
Thanks, it was an error when not finding the error pages of examples.
