### ISSUE TITLE
pass string value to piedata

### ISSUE THREAD

**Issue by kalpesh-jagada** [almasaeed2010/AdminLTE#1838]
Hello,
I am having problem in calling values from a label to piedata for chart. 
 var PieData = [document.getElementById("LblValue").innerHTML]

value of LblValue is - { value: 2, color: '#F074CB', highlight: '#F074CB', label: 'DIRECTOR - Male' }, { value: 1, color: '#5174B5', highlight: '#5174B5', label: 'DIRECTOR - Female' }

when I put value itself in piedata, it works great.

var PieData = [{ value: 2, color: '#F074CB', highlight: '#F074CB', label: 'DIRECTOR - Male' }, { value: 1, color: '#5174B5', highlight: '#5174B5', label: 'DIRECTOR - Female' } ]

I don't know what I am missing.

**Comment by lenamtl** [comment]
Hi,
You can post your question directly on the Chartjs repo https://github.com/chartjs/Chart.js/issues and read the doc at http://www.chartjs.org/
As your question it is not related to the template itsefl.

You can also download the latest Chartjs version as the one that come with the template may be old.
