### ISSUE TITLE
Form Wizard Needed urgent

### ISSUE THREAD

**Issue by mnszaidi** [almasaeed2010/AdminLTE#1840]
Hi, I need for Wizard Urgent for my project, and can you add 360 sliders and Picture Upload too.

**Comment by llaville** [comment]
Hello @mnszaidi 

Do you know or did you think to use this project Symfony [CraueFormFlowBundle](https://github.com/craue/CraueFormFlowBundle). There is a live [demo](http://www.craue.de/symfony-playground/en/CraueFormFlow/) available.
AdminLTE may be used only to add the skin.

Laurent

**Comment by mnszaidi** [comment]
Yes, its Ok but i am creating myself using https://bootsnipp.com/snippets/Dqbb7

**Comment by mnszaidi** [comment]
I have Created this, if anyone need i can provide, HTML, CSS, and JS
https://vidsbay.com/vidsbay-adminlte/item/item-listing.html

**Comment by 100n0m3** [comment]
Use jquery-steps works like charm
http://www.jquery-steps.com/

**Comment by mnszaidi** [comment]
Hi

there is minimal version 
https://vidsbay.com/vidsbay-adminlte/item/item-listing-wizard.html
