### ISSUE TITLE
in demo,$layout.fixSidebar()  $layout==undefined

### ISSUE THREAD

**Issue by jiehanlin** [almasaeed2010/AdminLTE#1842]
### Issue type:
Bug report 

### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  window 7
* Browser (Version):  Chrome (Latest) 

in demo,when set Fixed layout
demo.js:78 Uncaught TypeError: Cannot read property 'fixSidebar' of undefined.

**Comment by almasaeed2010** [comment]
Fixed in master
