### ISSUE TITLE
error AdminLTE

### ISSUE THREAD

**Issue by leobarussi** [almasaeed2010/AdminLTE#1852]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:

Help-me! [https://uploaddeimagens.com.br/imagens/erro-png-3a109a16-a5bd-442f-ba5f-fb722880dddc](url)
I am loading content with jquery (append) coming from a php.
however it is getting like this, and if I put a dynamic element (input for example)
, this doesn `t happen.. help-me!

**Comment by almasaeed2010** [comment]
The url you provided is not working. Please provide more info.

Thanks!

**Comment by itbill** [comment]
Try this:
[https://uploaddeimagens.com.br/imagens/erro-png-3a109a16-a5bd-442f-ba5f-fb722880dddc](https://uploaddeimagens.com.br/imagens/erro-png-3a109a16-a5bd-442f-ba5f-fb722880dddc)

**Comment by almasaeed2010** [comment]
I tried adding content via ajax but couldn't replicate the issue. It could be something wrong with HTML markup, custom css or any number of other issues so it might help if you provide steps to replicate the issue in a way that we can test. Sorry for the long delay! 

Thanks
