### ISSUE TITLE
wrong boxed-bg.jpg path in dist/css/alt/AdminLTE-without-plugins.css

### ISSUE THREAD

**Issue by marshtomp** [almasaeed2010/AdminLTE#1856]
The relative path in `AdminLTE without plugins` is wrong. (It should be `../../img/boxed-bg.jpg`)
https://github.com/almasaeed2010/AdminLTE/blob/79057e15c1f67e8b5101113075145f61264ac65c/dist/css/alt/AdminLTE-without-plugins.css#L49
The `replace` task is not yet applied to the source code.
https://github.com/almasaeed2010/AdminLTE/blob/79057e15c1f67e8b5101113075145f61264ac65c/Gruntfile.js#L162-L184

**Comment by marshtomp** [comment]
Pleace rebuild `AdminLTE-without-plugins.css`,`AdminLTE-without-plugins.min.css` and update the package. Thanks.

**Comment by almasaeed2010** [comment]
The boxed bg caused too much pain so in the new release we are using a simple bg color.

Thanks!
