### ISSUE TITLE
mobile sidebar bug

### ISSUE THREAD

**Issue by jjonline** [almasaeed2010/AdminLTE#1864]
in mobile , sidebar hide and show toggle bug.when Sidebar Collapsed is active.

demo images:

![bug images](http://cdn.xingyun168.cn/upload/resource/201804/3d5e3039233c9c48ed921c0ee93dbb31.png)

online url:
[https://adminlte.io/themes/AdminLTE/pages/layout/collapsed-sidebar.html](https://adminlte.io/themes/AdminLTE/pages/layout/collapsed-sidebar.html)

**Comment by almasaeed2010** [comment]
Hello,
I've tried this on chrome (mac) and couldn't see the same issue. Could you please provide more info such as the browser, the operating system and any other than info that my help?

<img width="430" alt="screen shot 2018-05-05 at 6 02 04 pm" src="https://user-images.githubusercontent.com/1512664/39667910-80eccaa4-508e-11e8-945d-b49e06a76a25.png">


Thanks!

**Comment by jjonline** [comment]
Reappear this bug in chrome(mac) on this step:

## setp1、open testing url https://adminlte.io/themes/AdminLTE/pages/layout/collapsed-sidebar.html on chrome and open debug toolbar,using virture mobile mode.and then click that button.
<img width="507" alt="1" src="https://user-images.githubusercontent.com/2277528/39689934-fa4b1a90-520a-11e8-8efa-f0c3fa604bed.png">

## step2、click min level title 
![3](https://user-images.githubusercontent.com/2277528/39690141-9624ff9e-520b-11e8-9ad4-7d33d70ffa6a.jpeg)

## setp3、click parent title and then the bug appear
![wechatimg55](https://user-images.githubusercontent.com/2277528/39690224-eabc1f10-520b-11e8-9b8e-81d846060160.jpeg)

**Comment by almasaeed2010** [comment]
Fixed in 2.4.8
