### ISSUE TITLE
Release date of version 3.0

### ISSUE THREAD

**Issue by AGhasemzadeh** [almasaeed2010/AdminLTE#1865]
Hello
I want to know planed release date of version 3.0.

**Comment by trollfalgar** [comment]
Yes, would be nice to know.
Thanks.

**Comment by jerry7411** [comment]
me too

**Comment by jizhidemowang** [comment]
me too

**Comment by tradingstratagem** [comment]
same here

**Comment by almasaeed2010** [comment]
Please test the alpha version first to make sure everything works correctly. If you find any issues please report them here (as new issues). Once we confirm by enough testers that it works, we'll release a stable version. I can't wait to get this out there so let's get some testing going and release thing 😃
