### ISSUE TITLE
Manage dependencies with Bower

### ISSUE THREAD

**Issue by edvinasme** [almasaeed2010/AdminLTE#187]
This theme is great! I believe it would be a good idea to manage dependencies with bower. If you (the author) agrees, I could submit a PR for this.

**Comment by forxer** [comment]
In fact there is already a bower branch but is not synchronized with the master. Why the two branches are maintained separately?

**Comment by almasaeed2010** [comment]
There are many people who aren't familiar with Bower (including me, not an expert). So updating that branch is a bit of a pain. However, the next release (2.0) should have a better systematic approach to properly update both branches simultaneously.
