### ISSUE TITLE
DataTables pagination buttons not working

### ISSUE THREAD

**Issue by SmileYzn** [almasaeed2010/AdminLTE#1870]
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  3.0 alpha
* Operating System:  Windows 8.1
* Browser (Version):  Chrome (Latest)

### Description:

Datatble pagination not working, maybe update the plugin :D
Is alpha, very good job anyway :D

**Comment by almasaeed2010** [comment]
Fixed datatables in v3.0.0-alpha.2 by updating the script. Please close the issue if resolved.

**Comment by SmileYzn** [comment]
Thanks :D

**Comment by HarshGundecha** [comment]
fixed here
[https://github.com/almasaeed2010/AdminLTE/pull/1871](url)

**Comment by joe-inz** [comment]
where to find the script @SmileYzn , plz ??

**Comment by SmileYzn** [comment]
@joe-inz what script?

**Comment by leomontenegro6** [comment]
I had the same trouble finding which script to update, but I solved that issue by doing the steps below:

- Entered into the "v3-dev" branch of the repository;
- Clicked on "Clone or Download", and then on "Download ZIP";
- Opened the zipped file, and got into the "plugins/datatables" folder;
- Replaced all jQuery DataTables .js and .css files I was using from the release, with the ones inside that folder.

After doing that, the pagination bug disappeared.

**Comment by irvine48** [comment]
hmm.. beta2 getting same error. any help how to get through this? if i disable plugins/datatables/dataTables.bootstrap4.js and my pagination work.

**Comment by REJack** [comment]
I've updated datatables & added all missing plugins in my PR #2220, but I have no error with datatables even with the beta.2.

@irvine48 Do you get console errors?

**Comment by RishikantSri** [comment]
Hi,
How to limit number of records in pagination.
i want to access pagination click command. i want to run select query on each pagination button jus to limit displaying rows.
