### ISSUE TITLE
v3 alpha 2 from master or v3-dev?

### ISSUE THREAD

**Issue by jugalthakkar** [almasaeed2010/AdminLTE#1883]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v3.0.0-alpha-2
* Operating System:  N/A
* Browser (Version):  N/A

### Description:
- The [v3 alpha 2 release](https://github.com/almasaeed2010/AdminLTE/releases/tag/v3.0.0-alpha.2) seems to be cut from master. It probably should have been from [v3-dev branch](https://github.com/almasaeed2010/AdminLTE/tree/v3-dev)

**Comment by almasaeed2010** [comment]
ugh why do I keep doing this! Thanks for reporting @jugalthakkar 

It's not been fixed!
