### ISSUE TITLE
pieChart not work

### ISSUE THREAD

**Issue by XxYyKk** [almasaeed2010/AdminLTE#1884]
<canvas id="pieChart" height="150"></canvas>

F12 console ：

jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'getContext' of undefined TypeError: Cannot read property 'getContext' of undefined
    at HTMLDocument.<anonymous> 

Uncaught TypeError: Cannot read property 'getContext' of undefined
    at HTMLDocument.<anonymous> (dashboard2.js:15)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)

please  help!~

**Comment by almasaeed2010** [comment]
Looks like you removed the html canvas element that dashboard2.js is looking for. Please review the documentation of ChartJS v1 or v2 as needed to fix.

http://www.chartjs.org/docs/latest/

Thanks!
