### ISSUE TITLE
sidebar mini logo not working

### ISSUE THREAD

**Issue by deded89** [almasaeed2010/AdminLTE#1887]
Hi, i try to use the sidebar mini, but why the mini logo not work
anyone can help me, where is the wrong..
![image](https://user-images.githubusercontent.com/39753035/40696562-eb1a0fc2-63f8-11e8-8d1e-e7cf8dcd2dfb.png)

**Comment by bellwood** [comment]
Theres a span for mobile/collapsed and a span for "normal" view.

Do you have the smaller image (50x50) in the span for smaller devices?

**Comment by almasaeed2010** [comment]
Looks like the image source url is incorrect. Please verify that you have linked the logo correctly.
