### ISSUE TITLE
Cannot find the source code of  Customize AdminLTE in Sidebar

### ISSUE THREAD

**Issue by AO12** [almasaeed2010/AdminLTE#1889]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by AO12** [comment]
Cannot find the source code of  Customize AdminLTE in Sidebar

**Comment by BryantJames** [comment]
Excuse me,
 how do I change the width of the left menu bar? 
Thank you，
Can you speak Chinese?
myEmail: huadaxiano1@163.com
