### ISSUE TITLE
a million records in grid

### ISSUE THREAD

**Issue by bharath539** [almasaeed2010/AdminLTE#1891]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:

Hello,
admin LTE grid is crashing when I tried to retrieve a million records from my db. How i can integrate a pagination query here?
Thanks

**Comment by bharath539** [comment]
Hello,
Anyone there to help me on this?
Thanks

**Comment by MrJmpl3** [comment]
Million records? Really? All browser crash with this data , tried to paginate from the server

**Comment by REJack** [comment]
Try to use DataTables with [Server-side processing](https://datatables.net/examples/data_sources/server_side)
