### ISSUE TITLE
Failed to compile with 1 errors :  version 3.0.0-alpha-2

### ISSUE THREAD

**Issue by samiboukadida** [almasaeed2010/AdminLTE#1892]
ERROR  Failed to compile with 1 errors                                                                                                                                                                                       15:32:06

error  in  jquery-jvectormap-1.2.2.css
Module build failed: Syntax Error 
(22:25) Unknown word

  20 |     -moz-border-radius: 2px;
  21 |     border-radius: 2px;
> 22 |     background: #d2d6de;//rgba(0,0,0,0.4);
                        |                         ^
  23 |     padding: 5px;
  24 |     color: #444;

I thank you a lot if you omit comment here
could you make the commit as soon as possible because i use your package 
I thank you very match

**Comment by almasaeed2010** [comment]
Please see #1914
