### ISSUE TITLE
sidebar collapse not working same on mobile view as on laptop and destop view

### ISSUE THREAD

**Issue by sharmaradha2386** [almasaeed2010/AdminLTE#1894]
mobile view..
i want the view same as on laptop..the mini collapsable sidebar where the complete sidebar is not hidden..u can see the icons after collapse...but i am not getting this on mobile view..i want the same for mobile view..please help

**Comment by arunikayadav42** [comment]
Can I work on this issue?

**Comment by sharmaradha2386** [comment]
yes

**Comment by almasaeed2010** [comment]
This is currently not possible in mobile. Unfortunately we do not plan to support this feature since it'll take a lot of time to develop and maintain.

Sorry for the inconvenience.
