### ISSUE TITLE
treeview-menu nested

### ISSUE THREAD

**Issue by pabloyokese** [almasaeed2010/AdminLTE#1895]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [x] Documentation   

### Environment:
* AdminLTE Version:  AdminLTE 3 Alpha-2
### Description:
 what happen with the class treeview-menu , the tree nested menus are not allowed anymore? 
This is not going to be support in future versions? 
there is any documentation about it ?

**Comment by dcy** [comment]
I want the Multilevel menu too.

**Comment by nunomazer** [comment]
I just made a multilevel menu using a treeview inside another

**Comment by dcy** [comment]
@nunomazer How? Can you write an example?

**Comment by nunomazer** [comment]
Sorry, I wasn't with the example last night. 

This is the piece of code I used to build a multilevel menu. I thinking in change a little the css to nested .has-treeview class to be rendered with a minor font size:

```html
<!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
        data-accordion="false">
            <li class="nav-header">Manutenção</li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fa fa-table"></i>
                    <p>
                        Cadastros
                        <i class="fa fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fa fa-life-ring"></i>
                            <p>
                                Help Desk
                                <i class="fa fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('hd.status.index') }}" class="nav-link">
                                    <i class="nav-icon fa fa-flag"></i>
                                    <p>Status de Tickets</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('block_rule.index') }}" class="nav-link">
                            <i class="nav-icon fa fa-ban"></i>
                            <p>Regras de Bloqueios padrões</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('contact_action_type.index') }}" class="nav-link">
                            <i class="nav-icon fa fa-comments"></i>
                            <p>Tipos de Ação de Contato</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="{{ url('log-viewer') }}" class="nav-link" target="_blank">
                    <i class="nav-icon fa fa-bug"></i>
                    <p>Log Viewer</p>
                </a>
            </li>

    </ul>
</nav>
```

**Comment by almasaeed2010** [comment]
Please see #1908 

Thanks!

**Comment by nelsonlucas** [comment]
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="fa fa-table"></i>
                <p>
                    Nivel 0
                    <i class="fa fa-angle-left right"></i>
                </p>
            </a>

            <ul class="nav nav-treeview">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-life-ring"></i>
                        <p>
                            Nivel 1
                            <i class="fa fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <p style="margin-left: 10px">
                                    <i class="nav-icon fa fa-life-ring"></i>
                                    Nivel 2
                                   
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>                     
            </ul>
        </li>           
    </ul>
</nav>

**Comment by nelsonlucas** [comment]
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">            
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="fa fa-table"></i>
                <p>
                    Nivel 0
                    <i class="fa fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-life-ring"></i>
                        <p>
                            Nivel 1
                            <i class="fa fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <p style="margin-left: 10px">
                                    <i class="nav-icon fa fa-life-ring"></i>
                                    Nivel 2                                   
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>                     
            </ul>
        </li>           
    </ul>
</nav>
