### ISSUE TITLE
how can I update to v3.0 from v2.4.3

### ISSUE THREAD

**Issue by Janus-Xu** [almasaeed2010/AdminLTE#1896]
### Issue type:
- [x] Documentation   

### Environment:
- AdminLTE Version:  2.4.3 

### Description:
I have a project with v2.4.3 in use，how to update to v3.0？the docs has no answer yet

**Comment by bellwood** [comment]
Documentation will likely come once v3 is finalized and released.

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
Man!!
Fuc
How to stop messages

في الأربعاء، ٢٠ يونيو، ٢٠١٨ ١٠،٥٦ م Brian Ellwood <notifications@github.com>
كتب:

**Comment by almasaeed2010** [comment]
Hello @Janus-Xu 

To upgrade you are going to need to familiarize yourself with Bootstrap 4 and [migrate your HTML to use BS4](https://getbootstrap.com/docs/4.0/migration/). There is a lot of changes there! The upgrade process will not be easy, unfortunately. Once you upgrade your infrastructure to use BS4, then you can update AdminLTE to v3. This process is not yet documented but the most major changes are the structural ones:

1. Update your AdminLTE CSS and JS files
1. Update your sidebar to use the new structure
1. Update the main-header component to use the new structure (BS4)
1. Update your control sidebar to the new structure
1. Update your `main content` and `wrapper` to the new structure
1. There are a few JS changes in both AdminLTE and Bootstrap that you'll also need to consider

I understand that the upgrade process will be cumbersome and hard to perform. It might be simpler to rebuild your HTML from scratch if your do not have that many pages yet.

Thanks!
