### ISSUE TITLE
How use CKEditor

### ISSUE THREAD

**Issue by FabianAguilar** [almasaeed2010/AdminLTE#1903]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:

Hello, I have had problems to use the CKEditor plugin, I do not understand how to implement it in this template, any ideas, please? , I'm using laravel 5.6

**Comment by bellwood** [comment]
Have you read the installation documentation:

https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/installation.html
