### ISSUE TITLE
There are compatibility problems with BootstrapDialog

### ISSUE THREAD

**Issue by JvCrystal** [almasaeed2010/AdminLTE#1905]
Problems with the current version were found during the use of BootstrapDialog, and the "content-wrapper" shrinks when a pop-up event is triggered

**Comment by bellwood** [comment]
Can you create a jsfiddle showing this?

**Comment by almasaeed2010** [comment]
We cannot help without more info. Please open a new issue if the problem persists with all the necessary info such as adminlte version, screenshots and code.

Thanks!
