### ISSUE TITLE
Login page issue

### ISSUE THREAD

**Issue by Jigse** [almasaeed2010/AdminLTE#1907]
Hii guys i had issue with login page in bootstrap i am new to website designing so i created a login page but in that login page the login box is not coming in centre it always remain in left side
So please help!!!

**Comment by bellwood** [comment]
Can you create a jsfiddle showing this?

**Comment by almasaeed2010** [comment]
Hello @Jigse 

Your issue does not contain enough info for us to be able to help.

Thanks!
