### ISSUE TITLE
Multilevel for AdminLTE 3

### ISSUE THREAD

**Issue by dcy** [almasaeed2010/AdminLTE#1908]
Hi!
https://adminlte.io/themes/dev/AdminLTE/index3.html Demo not show Multilevel.
Does AdminLTE 3 support Multilevel navigation?

**Comment by almasaeed2010** [comment]
Hello @dcy 

Sorry to disappoint but we won't be able to support multilevel in the new version due to the way the mini sidebar operates. However, we might add it in the future if we support multiple implementations of sidebar-mini.

Thanks!
