### ISSUE TITLE
Css compile issues 

### ISSUE THREAD

**Issue by Kiranyellu** [almasaeed2010/AdminLTE#1912]
I have tried to override css in dist/css/admin.css file when I would write css property in admin.css file then I  run npm run dev or npm run css but it give nothing why so? I couldn't understand please help me out 
Thank you 

### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  Windows and Linux mint 19
* Browser (Version):   Chrome (67)

**Comment by almasaeed2010** [comment]
Please specify the version of AdminLTE you are using.

In any case, you'll need to modify the `*.scss` or `*.less` files then compile.

Thanks!

**Comment by Kiranyellu** [comment]
I got adminlte bootstrap 4 version

**Comment by almasaeed2010** [comment]
Then you need to edit the `build/scss/*.scss` files and run `npm run css` to compile.

I hope that helps!

**Comment by Kiranyellu** [comment]
Thank you I got that

**Comment by Kiranyellu** [comment]
thank you for responding
