### ISSUE TITLE
3.0.0-alpha.2 jquery-jvectormap-1.2.2.css Unknown word NPM build/serve

### ISSUE THREAD

**Issue by iamavieira** [almasaeed2010/AdminLTE#1914]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation  

### Environment:
* AdminLTE Version:  3.0.0-alpha.2
* Operating System:  Ubuntu 16.04
* npm (Version):  6.1.0

### Description:

**Steps to reproduce the bug:**
- npm install admin-lte
- ng build/serve.

**Error:**

ERROR in ./node_modules/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css)
Module build failed: Syntax Error 

(22:25) Unknown word

  20 |     -moz-border-radius: 2px;
  21 |     border-radius: 2px;
> 22 |     background: #d2d6de;//rgba(0,0,0,0.4);
     |                         ^
  23 |     padding: 5px;
  24 |     color: #444;

**What I tried to do to solve:**
I just changed the comment to /**/.
I checked the repo and saw that this error was already fixed at commit 074d1ca. So I guess is just a matter to update the package distribution at npm.

**Comment by almasaeed2010** [comment]
Hello @iamavieira 

Since this is a jvector map error, you'll have to install the newer version. We cannot update from 1.2.2 because of licensing issues. Please see #1616 

Thanks!
