### ISSUE TITLE
jequery UI Autocomplete is not working

### ISSUE THREAD

**Issue by sagarfpi** [almasaeed2010/AdminLTE#1917]
### Issue type:
- [ ] Feature request 
- [ ] Bug report      Jquery UI widget autocomplete is not working proferly. and if i change some css in jquery.ui.cass file it shows. example from top and left value. and also its event methods are not working. 
- [ ] Documentation   

### Environment:
* AdminLTE Version:  AdminLte 3 Aplha2
* Operating System:  Windows7
* Browser (Version):  Mozilla Firefox

**Comment by almasaeed2010** [comment]
Unfortunately, we do not provide support for jQuery UI.

Sorry!
