### ISSUE TITLE
I don't like v3 theme

### ISSUE THREAD

**Issue by iweixubin** [almasaeed2010/AdminLTE#1919]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):  

### Description:
I more like AdminLTE v2 theme, v3 is not beautiful to me
I expect v2 theme + bootstrap4

**Comment by almasaeed2010** [comment]
Sorry you feel that way. Your expectations cannot be met. Sorry.
