### ISSUE TITLE
After Scrolling message box disapears we must click again to reach messages

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#192]
Hello
When i go to messages and scroll down the message, the message drop down disapear and i have to click again before i can click on the message. I dont know if this is because i have updated the script to the latest version of sclimScroll or because i made de scroll bar big... 
For a better understanding please visit 

http://usefaith.voiedusucces.net/standard_a.php?membre=justfortest
and log in by using
 usersame  : justfortest  
password : justfortest

and after you are logged in click on the message icon on the top and scroll the message down and up and you will see that the message drop down will disapear though it will scroll but you will not be able to click. U will have to click on the message box again sometimes before you can click on where you have scrolled to. 

Please how to fix this ? I have update the slimscroll directory to the latest one

**Comment by kressly** [comment]
I really dont know y it is doing that but ....

**Comment by almasaeed2010** [comment]
I tried all browsers including IE9. This isn't happening in any of them.

**Comment by kressly** [comment]
Ok tks a lot. Then it must be from my machine

**Comment by lenamtl** [comment]
There is a setting that you have to mouse-over the div to make scrollbar appear.
(when not mouse-over it disappear).
See the first example on
http://rocha.la/jQuery-slimScroll
