### ISSUE TITLE
Using of jVectorMap under license GPL in a MIT licensed project

### ISSUE THREAD

**Issue by Jitrixis** [almasaeed2010/AdminLTE#1923]
### Issue type:
- [ ] Feature request 
- [ ] Bug report       
- [ ] Documentation   
- [x] License Compliancy

### Environment:
* AdminLTE Version:  All 
* Operating System:  All
* Browser (Version):  All

### Description:

I'm making another project base on AdminLTE and I've audited librairies to make sure that everything meet the MIT license and I've noticed that one of the librairy used in the project is under GPL license which doesn't meet the license of AdminLTE which is under MIT License.

**Comment by almasaeed2010** [comment]
See #1616
