### ISSUE TITLE
black layout, but font logo on the top is blue.

### ISSUE THREAD

**Issue by hendimarcos** [almasaeed2010/AdminLTE#1925]
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  All
* Browser (Version):  All

### Description:
I'm having the blue color problem when using ngx-admin-lte
the black skin looks like this:
black and black-light

```
> .logo {
      .logo-variant(#fff; #333);
      border-right: 1px solid @gray-lte;
      @media (max-width: @screen-header-collapse) {
        .logo-variant(#222; #fff);
        border-right: none;
      }
    }
```

With problem
![image](https://user-images.githubusercontent.com/910965/42423590-0347e1f2-82d3-11e8-9700-df4604c1f24a.png)

and all others like this (without the '>' ):

```
    //Logo
    .logo {
      .logo-variant(darken(@<color>, 5%));
    }
```

No problem
![image](https://user-images.githubusercontent.com/910965/42423625-c7827456-82d3-11e8-9728-8610fd1dbbc1.png)

**Comment by almasaeed2010** [comment]
Merged, will be available in v2.4.6.
