### ISSUE TITLE
Update the librairies version (especially the datatables)

### ISSUE THREAD

**Issue by QuentinCurtet** [almasaeed2010/AdminLTE#1928]
### Issue type:
Feature request

### Environment:
* AdminLTE Version:  2.4.3
* Operating System:  Debian 9
* Browser (Version):  Chrome Canary

### Description:
Is it possible to update the minimal requirements of all the librairies used in adminLTE (for example datatables is now in the 1.10.19 version).

**Comment by almasaeed2010** [comment]
Updated all plugins.

Thanks!
