### ISSUE TITLE
Invoice page noprint still consume space

### ISSUE THREAD

**Issue by msvendsen** [almasaeed2010/AdminLTE#194]
Hi,

I have a funny issue with the invoice page. I use the noprint class to not print out specific divs.
When printing it doesn't print the divs out - but they still somehow consumes space meaning that often half page of text will print out one empty page as well.

Is this something you have seen before? And have a fix?

Example of noprint div that consumes space on printed paper:

<div class="pad margin no-print">
  <div class="alert alert-success" style="margin-bottom: 0!important;">
    <i class="fa fa-info"></i>
    <b>NB:</b> Remember XYZ!
  </div>
</div>

THANKS!

**Comment by lenamtl** [comment]
It's happened to me once.
Are you printing a modal page?
On which div do you have this issue?
Which print code are you using?
Are you using custom javascript with this div?

**Comment by kressly** [comment]
Are u guys programming in php ? If yes, y don't u program a custom print page that will display only what u want ?
The print button will launch ur custom print page and launch the javascript print on page load.

**Comment by msvendsen** [comment]
@lenamtl It's the demo invoice page. If I just add a few extra no-print divs (as the ones from the invoice example) - then I have the issue.

@kressly You are 100% right. I just thought this was a nice way doing it - if it worked :)

**Comment by lenamtl** [comment]
Print CSS  with @media print exist for that case, for me it's easier and faster.

I'm using the no-print class a lot on item like icons and I have no problem.
I just did a test on invoice page that have div .box and hide this box with no problem.
I will provide my print.css file soon as I can.

Try to hide the div directly in the css file 
look for @media print reference in the main css file to find examples (around line 295 and line 2521).

Also keep in mind that printing a web page may give different results depending of the browser, OS and printer settings.

I'm not using PHP for this project and even if I was I don't think I will create a print page for each different page, to my opinion it's like doing the job twice. 
There always several ways to do things so it's may be the solution for you.

**Comment by lenamtl** [comment]
If you have items that have visibility:hidden this probably the culprit.
This will make the item hidden, but these are taking space so this may give empty space on the page or add an empty page at the end when printing depending where the item code is place on the page.
There is no fix for this at the moment, this will happen on any template.

**Comment by msvendsen** [comment]
Hi Guys,
Thanks for your input.

@lenamtl You write that you tested with the invoice page, and didn't have any issues? That's weird. I've just tried downloading a fresh AdminLTE and duplicating the Note-divs. Have a look here:
http://www.nsec.dk/admin/pages/examples/invoice.html

When printing that out - it will give you a blank 2nd page.

If I do a display:none directly on the div's (so they also dissapear from screen) then it will only print one page.

**Comment by lenamtl** [comment]
Hi unfortunately I don't have much time today to help you.

If you remove the note from the code, is this printing ok.
I'm using the note but they are placed on the invoice itself.
You may want to add those note in a row div to see if this fix the problem.

I will post my print.css page this today and some instruction.

**Comment by kressly** [comment]
@lenamtl  sorry to ask this but are you on facebook or is there a way to contact you ? You are good programmer and a problem solver :+1:  I think everybody would like to have you as friend

**Comment by lenamtl** [comment]
@kressly I'd like to stay low profile at the moment.
Github removed their PM system, is there a private way I can send you my email address?

**Comment by kressly** [comment]
No problem bro i respect your privacy. I dont really know another way otherwise you can send me and email : moikressly at gmail or on my facebook profile https://www.facebook.com/kjohnmaxwell

**Comment by lenamtl** [comment]
Done

**Comment by kressly** [comment]
@lenamtl Thanks :+1:
