### ISSUE TITLE
Message drop down not responsive at change on the profile bar if name not long

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#195]
Hi
I have been facing some challenges on the message drop down anytime i change the profile bar.
When the name is not long enough or the icon on the top is changed the message bar is no longer responsive
In the first image below you will see that i have changed where the name is supposed to be on the top bar and replaced it with an icon and because of that the message box is no longer responsive
![1](https://cloud.githubusercontent.com/assets/925132/5659274/7ef39e4c-9707-11e4-81f5-1579c5b67f9b.png)
And on the image below i have added the name and icon and counted the number of characters (8) to be placed there aside of the icon and it works perfectly. But the problem with this is that not everybody addition of first name or surname will give 8 characters in space or .. Max John (with space) gives 8 Character. But what about if somebody is called just Kirk or Akolastemanou ?
![2](https://cloud.githubusercontent.com/assets/925132/5659310/135ca254-9708-11e4-8295-f5239ec827c1.png)

Please check out a demo of both pages online
Username : justfortest
Password : justfortest

The page that does not work correctly because i did not write any name but replaced it with just an icon
http://usefaith.voiedusucces.net/standard_a.php
When you log in, resize the page to the smallest one and click on message and you will see the drop down problem

The page that works well because i had to calculate the length of what i am adding and add it to the icon

http://usefaith.voiedusucces.net/standard_b.php
This one works well only because i did not remove the name and the name and icon are using some space witch enables then to look responsive.

Please your help will be much appreciated. Thanks

**Comment by kressly** [comment]
I have found a fix, a work around but i don't know how to paste a code here. When i paste a code it does not appear. I would like to move this to the commits . Is it possible ? and how do i paste the code so that others may benefit from this too ?

**Comment by lenamtl** [comment]
To add code check markdown https://guides.github.com/features/mastering-markdown/ click on code pills.

` ` `
your code here

` ` `

Just to show you to make it work you need to remove space between ` ` ` 

```
your code here
```

**Comment by almasaeed2010** [comment]
The fix for that is to position the menus as static and add right: 5% and left: auto to their css rules. Needless to say, this must apply only to the appropriate screen widths. I'll push a fix once I get a chance. Probably later today.

**Comment by lenamtl** [comment]
I got some issues with the all dropdown, I don't use them for now.
I even got issue with the Bootstrap one, I need to investigate...
But I will need to add one for language switcher asap.

**Comment by kressly** [comment]
```
Code
```
