### ISSUE TITLE
side bar problem when resize screen

### ISSUE THREAD

**Issue by abumuaaz** [almasaeed2010/AdminLTE#1954]
thanks for you,
when using the arabic version 
[http://mmdsharifi.github.io/AdminLTE-RTL/pages/forms/general.html](http://mmdsharifi.github.io/AdminLTE-RTL/pages/forms/general.html)
and resize windows as mobile device
any click on the page opened side bar which disable writting on the form
pls fix

**Comment by omkartapale** [comment]
Please check your all css called on page exist in place. Because I'm seeing http://mmdsharifi.github.io/AdminLTE-RTL/dist/css/skins/_all-skins.min.css is missing and called on the page. Use browser developer tools for more information.

**Comment by abumuaaz** [comment]
thanks
all css refferences are ok ?
same problem

**Comment by abumuaaz** [comment]
hi
did you find the problem ?
if you download and test in you device you face same problem
if you click any where in page while you in mobile view ( resize browser window) the side bar is open !!!!!

**Comment by heemza** [comment]
You may need to fix sidebar's css in rtl.less file to be like this

<img width="291" alt="mobile fix" src="https://user-images.githubusercontent.com/6562562/43820479-9935c60c-9b10-11e8-91c7-351e0d440f23.png">

I only test in Chrome.

**Comment by abumuaaz** [comment]
thank you
im not use less or any compiler
i just use the css files
please tel me what to do in rtl.css or any other css files

**Comment by heemza** [comment]
From my css above will be complied like this.

<img width="341" alt="complied" src="https://user-images.githubusercontent.com/6562562/43850672-bf51a962-9b62-11e8-9f07-c40ed7b6b261.png">

`@media (max-width: 767px) {
  .main-sidebar,
  .left-side {
    right: -230px;
    -webkit-transform: translate(230px, 0);
    -ms-transform: translate(230px, 0);
    -o-transform: translate(230px, 0);
    transform: translate(230px, 0);
  }
  .sidebar-open .main-sidebar,
  .sidebar-open .left-side {
    -webkit-transform: translate(-230px, 0);
    -ms-transform: translate(-230px, 0);
    -o-transform: translate(-230px, 0);
    transform: translate(-230px, 0);
  }
}`

You may insert in any css file but after main AdminLTE.css file (or in the end of main css file)  to override default css.

**Comment by abumuaaz** [comment]
thanks
it working
