### ISSUE TITLE
Badge issue

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#196]
Hi, 

The badge is not correct the space on the top is less than the bottom.
I have made a test using on Boostrap and there is a difference.
Green one is the adminLTe one located in the sidebar menu, the grey one is Bootstrap one.
This is maybe related to the font I don't know.

![badge](https://cloud.githubusercontent.com/assets/2241324/5667861/100168b6-9739-11e4-9629-6f890fbd2bf3.jpg)

**Comment by kressly** [comment]
Hi
Have you found a solution to this ?

**Comment by lenamtl** [comment]
Not yet ... 
It's maybe relate to the Bootstrap version...
I'm using v3.2.0  
Do you have this issue too?

**Comment by kressly** [comment]
Yes i have a similar issue just that mine is a little bit different but it is related to the badge closed to the message box.
When i load it through ajax call like 
```
<span id= id="nombre_nouveaux_messages">
 <span class="label label-success">4</span>
</span>
```
where the nombre_nouveaux_messages is updated by ajax with 

```

 <span class="label label-success">8</span>

```

The badge does not appear correctly and is not lifted but appear by the side of the icon like in the image below
![1](https://cloud.githubusercontent.com/assets/925132/5681218/6defc208-980e-11e4-84fe-a880be8dd3a2.png)
I dont really know why it is not lifted like normally when my ajax function loads it. Do you have a fix for that ?

**Comment by lenamtl** [comment]
ok you have a different issue.

**Comment by lenamtl** [comment]
I also have this issue with the label :(

**Comment by kressly** [comment]
I think that will be a great idea. I am usin Bootstrap 3.3.1 and i have updated most things to their latest version. Even jquery i am using jquery 2 if the browser is not IE 8 and below and jquery 1. If the browser is IE 8 and below. So yes updating to the latest code i think will be a great idea. I wonder Y @almasaeed2010 has not done that yet in the demo and the file to download

**Comment by lenamtl** [comment]
I have the issue with 3.3.1 too

**Comment by TiagoGoddard** [comment]
Do you have a link where we can see your result?
Pretty hard to guess with just an image

**Comment by lenamtl** [comment]
Ok I just realized that it's ok when the letter is not capslock n and occurred when it is capslock N

**Comment by kressly** [comment]
Oh ok.
