### ISSUE TITLE
After logging in to the jump page, click on the left menu and nothing happens.

### ISSUE THREAD

**Issue by Lisa2015** [almasaeed2010/AdminLTE#1960]
clicked **treeview**  menu Not expand  child Menus
help plz.  Version: 2.3.11. environment: Vuejs  Single Page, Nodejs , npm. Browser: Chrome

**Comment by Chocky99** [comment]
/* Tree()
 * ======
 * Converts a nested list into a multilevel
 * tree view menu.
 *
 * @Usage: $('.my-menu').tree(options)
 *         or add [data-widget="tree"] to the ul element
 *         Pass any option as data-option="value"
 */

**Comment by Lisa2015** [comment]
thx  very much!! But I found a new bug now. which is **Toggle navigation**  clicked nothing happens. what should I do?
