### ISSUE TITLE
npm bootstrap 4

### ISSUE THREAD

**Issue by eduvnsm** [almasaeed2010/AdminLTE#1970]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  
* Operating System:  
* Browser (Version):

**Comment by eduvnsm** [comment]
Is there a way to install AdminLTE 3 (with Bootstrap 4) through npm?

**Comment by evandrogrm** [comment]
I don't know if you solve this.
in package.json  `"admin-lte": "^3.0.0-alpha.2"`
