### ISSUE TITLE
Bagde not accepting span id

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#198]
When i add some span with id to the normal badge like this 
```
<span  id="nombre_nouveaux_messages">
 <span class="label label-success">4</span>
</span>
```

The badge does not appear correctly and is not lifted but appear by the side of the icon like in the image below
![1](https://cloud.githubusercontent.com/assets/925132/5681218/6defc208-980e-11e4-84fe-a880be8dd3a2.png)
I dont really know why it is not lifted like normally but i need to add that span so that i can use the id of that span to do my ajax request. . Do you have a fix for that ?
I am using bootstrap 3.3.1

**Comment by TiagoGoddard** [comment]
By adding that span you broke the selector i believe in the css, making it
not to apply.
I would just add the tag id on the span with the class, that should work.

Att.,
Tiago Goddard

2015-01-09 13:44 GMT-02:00 Max John <notifications@github.com>:

**Comment by kressly** [comment]
So please which line exactly am i supposed to edit ?

**Comment by lenamtl** [comment]
Try
```<span class="label label-success" id="nombre_nouveaux_messages" >4</span>```

**Comment by kressly** [comment]
@lenamtl
Yrs that works but i don't want that because it implies that the member has some message but the fact is that the member may not have any new message. So i would like to place and id before the span of class="label label-success" so that i can call class="label label-success" with ajax if the member has new messages. Do u have any css fix ?

**Comment by TiagoGoddard** [comment]
@kressly Put display:none when it's at 0 with js.

**Comment by kressly** [comment]
Yes yes yes yes yes !!!!!!
Thanks the Css part worked. I prefer the Css. Tks tks tks.
