### ISSUE TITLE
[Solution] Print CSS

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#199]
Hi,

Here are some instructions and code that may help when having printing issue.
This is a light version of my print.css, cause I'm using a lot of javascript that are not in the package.
At least this will help you to start yours.

Notes: This is for version 1
If you have items that have ``` visibility:hidden; ``` class this will print blank space and/or blank page.
If you see scrollbars on print preview you can add  ``` body { overflow: hidden; } ```to the print css.
If you have an item with ``` position: absolute; ``` class this may cause printing problem and other problems in general.
Keep in mind that printing a web page may give different results depending of the browser, OS and printer settings.
I'm using only the invoice page template container with boxes and notes, it's may not work on other pages. Let me know if you found an error or if I forgot something.
This work for my needs, you may need to adapt to your needs.
Please share your working print css so we will end-up with a more complete file.

***First do a full backup of your site, so you can get back if something is wrong with this code.

AdminLTE.css
comment all or remove all @media print class from the adminlte.css around line 295 and line 2521
and don't forget the closing  }

In your page between ```  <head> </head>``` 
add to AdminLTE.css the media="screen"
``` <link href="css/AdminLTE.css" rel="stylesheet" type="text/css" media="screen" />``` 

 
add a print.css link that need to have media="print"
``` 
<!-- print -->
 <link href="css/print.css" rel="stylesheet" type="text/css" media="print"/>
``` 
 
Create a file print.css and place it in the css folder.
 
 print.css
 
 everything need to be place between 
``` 
 @media print { 
 }
``` 
Here is the code for print.css file
``` 
 
/* Enhancement for printing */
 
@media print {

  /* added */ 
 body * { float: none !important; } 

/* original code  */
  .no-print {
    display: none;
  }
 
  .left-side,
  .header,
  .content-header {
    display: none;
  }
  
  .right-side {
    margin: 0;
  }

 
  /* for components */ 
  
  /* Added custom code to prevent page-break in box */ 
   .box {
   display: inline-block; 
   page-break-inside: avoid !important;
   page-break-before: auto; 
  }
    
/* original code */   
  .callout {
   margin: 0 0 20px 0;
   padding: 1px 30px 1px 5px;
   border-left: 2px solid #eee;
  } 

  .invoice {
    width: 100%;
    border: 0;
    margin: 0;
    padding: 0;
  }
  
  .invoice-col {
    float: left;
    width: 33.3333333%;
  }
  
  .table-responsive {
    overflow: auto;
  }
  
  .table-responsive > .table tr th,
  .table-responsive > .table tr td {
    white-space: normal!important;
  }


  
  

}

/* End of media print */
```

**Comment by kressly** [comment]
Thanks a lot. So is this going to enable us to print directly from the page ?

**Comment by lenamtl** [comment]
If  you need to print a timeline, you will have to copy all the timeline css class (that are in the main css)
to the print.css file and adjust the css if needed.
