### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated app.js:342

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#201]
Hi
When i do a jquery.load to load a page with jquery in AdminLte i get the following error for app.js

```Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ app.js:342```

Does someone know how to solve this ?
Thanks

**Comment by kressly** [comment]
app.js has been modified to add the jquery noconflict and so at line 342 this is what my code shows

![1](https://cloud.githubusercontent.com/assets/925132/5694492/af454f54-9956-11e4-8138-f53111cc4dd9.png)

Please does someone know how to solve this ?

Thanks

**Comment by almasaeed2010** [comment]
I wish you were using jQuery.Ajax() which provides the functionality you need in a much simpler syntax, that way I would be able to help. However, try to run the code without the template's app.js or other plugins. If the problem persists then it's in the source code you are using and in the template.

**Comment by kressly** [comment]
@almasaeed2010 
Yes i am using jquery to load the pages but the pages that are loaded have both jquery and prototype and scriptaculous
This is my jquery code that loads the pages with ajax (without refreshing)

```

 jQuery( document ).ready(function( $ ) {
// Code that uses jQuery's $ can follow here.


///////////////////////////////////////////////////////////////////////////////


    


$(document).on('click', 'a[rel*=charger_tout]', function(e) { 

e.preventDefault();
	
	var myId_to_update_here = $(this).data('ajax');
	
	var afficher_chargement = $(this).data('icon');
		
	if(afficher_chargement=='Oui')
	{
		$('#'+myId_to_update_here).html('<img src="images/facebook_style_loader.gif" />');
	}
	//Fin de l'affichage du chargement si le data-icon='Oui'
	
	
	
  $('#'+myId_to_update_here).load($(this).attr('href'), function(responseText, textStatus, XMLHttpRequest) {
            if(textStatus == 'error') {
				
                $('#'+myId_to_update_here).html('<p>Oupps.. There was an error making the AJAX request. Maybe your internet connection is slowing down.</p>');
            }
        });
  
  return false;
});

///////////////////////////////////////////////////////////////////////////////

});

```

So all i have to do later is to add some link like 
`<a href="brouillons.php?membre=<?php echo $membre; ?>" rel="charger_tout" data-ajax="id_du_milieu" data-icon="Oui">charger_tout</a> `

And in the page brouillons.php i just have to make sure all my information that i want to load dynamicaly are insice 

```
<span id='id_du_milieu'> </span>

```
And my pages are loaded without refreshing.
Check a demo at http://usefaith.voiedusucces.net/ and then click on forgot password or create new account or register. All these are loaded from other pages.

**Comment by MarcosSedrez** [comment]
Try to force the async option (it works for me):

$.ajaxPrefilter(function( options, originalOptions, jqXHR ) {
     options.async = true;
});

**Comment by hfhchan** [comment]
There must be a script tag somewhere in the string you passed into jQuery's .html().  jQuery synchronously fetches any scripts inside the string and executes them when inserting HTML into the DOM.

**Comment by Bestcxy** [comment]
when you use ajax , set the async : true, will be ok.
