### ISSUE TITLE
Side bar toogle not working in sping boot

### ISSUE THREAD

**Issue by mattyasyahya** [almasaeed2010/AdminLTE#2016]
Hi All, i create spring boot project with admin lte, and when i add datatable sudenly the toogle side bar not  working

**Comment by venusvavadiya** [comment]
Hi, would you be able to share more details and the code? You might have forgotten to close a div or ul.

**Comment by venusvavadiya** [comment]
No worries bro. Can you close this issue then?

**Comment by venusvavadiya** [comment]
@almasaeed2010 We can close this issue.
