### ISSUE TITLE
AdminLTE v2.3.8. Datatable DateTime column sort

### ISSUE THREAD

**Issue by ryozzo** [almasaeed2010/AdminLTE#2036]
### Issue type:
- [ X] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  v2.3.8
* Operating System:  Any
* Browser (Version):  Any

Consider this code (I use razor ASP.NET C# but it doesn't really matter). 
I'am able to sort all column but the last one is a datetime which is sorted as string. 
I just want to know if it is possible to have a sorting datetime column with AdminLTE datatables, with or without (better) adding plugins.

&lt;div class=&quot;table-responsive&quot;&gt;
          &lt;table id=&quot;tableClienti&quot; class=&quot;table table-bordered table-striped table-hover&quot;&gt;
              &lt;thead&gt;
                  &lt;tr&gt;
                      &lt;th&gt;Zona&lt;/th&gt;
                      &lt;th&gt;Classe&lt;/th&gt;
                      &lt;th&gt;Rag Soc&lt;/th&gt;
                      &lt;th&gt;Indirizzo&lt;/th&gt;
                      &lt;th&gt;Email/Telefono&lt;/th&gt;
                      &lt;th&gt;Contatto&lt;/th&gt;
                      &lt;th&gt;Email/Telefono&lt;/th&gt;
                      &lt;th&gt;Ultimo Pass.&lt;/th&gt;

 </tr>
              </thead>
              <tbody>
                  @{

                      foreach (var r in Model)
                      {
                          <tr>
                              <td>@r.Zona</td>
                              <td>@r.ClasseCliente</td>
                              <td>@r.RagioneSociale</td>
                              <td><b>@r.Citta @r.CAP</b><br /> @r.Indirizzo</td>
                              <td>@r.Email<br /> @r.Telefono</td>
                              <td><b>@r.NomeContatto<br /> @r.CognomeContatto</b></td>
                              <td>@r.EmailContatto<br /> @r.TelefonoContatto</td>
                              <td>@r.DataUltimoPassaggio</td>
                          </tr>
                      }
                  }

              </tbody>
          </table>
      </div>
 $(function () {
        var table = $("#tableClienti").DataTable({
            paging: false,
            "sDom": '<"top"i>rt<"bottom"><"clear">',
            "scrollX": true,
            "scrollY": "45vh",
            "bSort": true
            ]
        });

**Comment by InsanityMeetsHH** [comment]
You can add `data-order` to `td` tag and make a format like "2004-02-12T15:19:21+00:00".
My [example](https://github.com/InsanityMeetsHH/file-sharing/blob/master/templates/user/show-all.html.twig#L22) is written in [Twig](https://twig.symfony.com/) and [PHP date](http://php.net/manual/de/function.date.php).

**Comment by ryozzo** [comment]
Thank you 

> You can add `data-order` to `td` tag and make a format like "2004-02-12T15:19:21+00:00".
> My [example](https://github.com/InsanityMeetsHH/file-sharing/blob/master/templates/user/show-all.html.twig#L22) is written in [Twig](https://twig.symfony.com/) and [PHP date](http://php.net/manual/de/function.date.php).

Thank you for your answer but I cannot understand how to use data-order.
I want to make my datetime column sortable by date manually by clicking on header.
This means that datas are retrivied unsorted on page load and then the user could sort datas by date ascending or descending.

Does your code do this scenario?

**Comment by InsanityMeetsHH** [comment]
Yes, my code is for this scenario.
Here you can find the official docu or this feature.
https://datatables.net/examples/advanced_init/html5-data-attributes.html

**Comment by ryozzo** [comment]
This comment found on the page you linked is the key for me:

> Its important to notethat the data-* attributes with search() will only work if you use this on every COL!!! You can not mix it like:
> 
> <tr><td>Value1</td></tr>
> <tr><td data-search='Value 2 XYZ'>Value2</td></tr>
> It seems the Plugin-Code always check the first row and then use this value for all search operations. Maybe for the future would be very cool if you can mix it ;):
> 
> Best Regards Tom

Previously, I tried to add data-order to < td> only if the "DateTime variable" was not null.
Thanks to this comment I set data-order = "DateTime variable".Ticks when "DateTime variable" is not null and data-order = 0 when "DateTime variable" is null.

So, I changed this piece of code 
`<td>@r.DataUltimoPassaggio</td>`

in this way
` <td>@(r.NumeroPassaggiAnno)</td>
@{
   DateTime data;
   if (DateTime.TryParse(r.DataUltimoPassaggio.ToString(), out data))
   {
      <td data-order="@(data.Ticks)">@(data.ToString())</td>
   }
   else
   {
      <td data-order="0"></td>
   }
}`

Thank you InsanityMeetsHH!
