### ISSUE TITLE
Update to bootstrap 3.4

### ISSUE THREAD

**Issue by QuentinCurtet** [almasaeed2010/AdminLTE#2038]
### Issue type:
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.8
* Operating System:  Debian 9
* Browser (Version):  Chrome (Latest)

### Description:
Bootstrap released a new version for 3.x branch. Is it possible to update to this version because, it fixes some XSS breaches.
https://github.com/twbs/bootstrap/releases/tag/v3.4.0
https://github.com/twbs/bootstrap/tree/v3.4.0

**Comment by kabutotx** [comment]
I just dropped bootstrap 3.4 js and css in my project and it seems to be working fine.

**Comment by Jamesking56** [comment]
I think this needs re-categorising as a Bug Report and an increase in priority since the current Bootstrap version used has security vulnerabilities

@almasaeed2010 can we get this upgraded?

**Comment by QuentinCurtet** [comment]
Update on this ?
It would be nice to update to 3.4.1, because of one new security breach (XSS) => https://github.com/twbs/bootstrap/releases/tag/v3.4.1

**Comment by almasaeed2010** [comment]
See v2.4.9

Thanks and sorry it took that long!

**Comment by tabacitu** [comment]
@almasaeed2010 , I think Packagist no longer auto-updates new releases for this package. I know you needed to re-login to Packagist a few months ago, maybe you didn't do it at the time. 

I've tried to install 2.4.9 using composer and it says that the version doesn't exist. From what I can tell:
- the version _exists_ on Github
- the version _does NOT exist_ on [Packagist](https://packagist.org/packages/almasaeed2010/adminlte)

![screenshot 2019-02-27 at 18 25 43](https://user-images.githubusercontent.com/1032474/53505720-1c53e180-3abd-11e9-9c65-367f014b5996.jpg)

I think **you have to Login with Github on [Packagist](https://packagist.org), and hit "Update" on the package**, so the tag shows up. Can you please try that, so people can get the latest version (with the BS security fix) with ```composer update```?

Thanks for the wonderful work!

**Comment by hli-ng** [comment]
it seems that 2.4.9 release only upgrade bootstrap to v3.4.0 https://github.com/almasaeed2010/AdminLTE/commit/661398920ddac791a91440b6b075091d40ec7ea6 while [bootstrap v3.4.1](https://github.com/twbs/bootstrap/releases/tag/v3.4.1) has the real XSS fix. Is it possible to bootstrap reference to 3.4.1?
