### ISSUE TITLE
AdminLte 1.3.1

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#204]
Hi 
We are so glad that there is a new release. That boost our hope. However in order not to star everything over can we have an idea of the file that have been modified so that we may update from our old version ?
Thanks

**Comment by lenamtl** [comment]
On the release page
you can click on  5b7d35a (left side under the version #)
This will show you the diffs:
https://github.com/almasaeed2010/AdminLTE/commit/5b7d35a2f2c0ee1b8e6cd7acfa235c497f3f616a

**Comment by kressly** [comment]
@lenamtl  Thanks a lot.
When i checked i realise that the files has been updated to their latest version which i had done long ago before this release. I can even contribute for the part related to the jquery version. The latest jquery versions do not work with IE 8 so my php fix is this . If the browser is below or equal to IE 8 i use the old version of jquery else i use the latest one and that has solve a lot of problem compatibility with other version execpt 2 version of ie that i am working on (Ie 8 and IE 10) BUT all the rest are working well when i tested with IeTest
```
<?php

//Si la version de Internet explorer est superieur a 8 alors on affiche le jquery 2
//sinon on affiche une ancienne version de jquery 1.
if(preg_match('/(?i)msie [1-8]/',$_SERVER['HTTP_USER_AGENT']))
{
    // if IE<=8 If it is a very old browser
   ?>
   
   <script type="text/javascript"  src="js/jquery/jquery-1.11.2.min.js"></script>
   <?php
}
else
{
    // if IE>8 or a good browser like firefox or chrome ...
	//On affiche la derniere version de jquery
	?>
     
	 
     <script type="text/javascript"  src="js/jquery/jquery-2.1.3.min.js"></script>
     
     
     
     
    <?php
}	

?>

```
