### ISSUE TITLE
The skin key in /config/adminlte.php doesn’t work when set to black 

### ISSUE THREAD

**Issue by ronlinet** [almasaeed2010/AdminLTE#2047]
### Environment:
* AdminLTE Version:  v1.24.2
* Operating System:  Mac OS 
* Browser (Version):   Chrome (Latest) 

I can’t change the skin key to 'skin' => 'black' or 'skin' => 'black-light' . 
It does work with 'skin' => 'blue' or 'skin' => 'yellow' but no color with 'skin' => 'black'. 

I have also hardcoded the link in views/vendor/adminlte/page.blade.php 
  ` <link rel="stylesheet" href="{{ asset('vendor/adminlte/dist/css/skins/skin-black-light.min.css')}} ">`

The css debugger is showing correctly the skin-black-light in the body header => https://ibb.co/Msd0tZN 

I have cleared the cache and config but as I say all skin work except the black or black-light

**Comment by heemza** [comment]
Your screen shot seems like it showing correctly with the skin-black-light, is't it?
White background color and black text color to main-header and main-sidebar (if exists). 

Correct me if i miss understood your issue.

**Comment by ronlinet** [comment]
Hi @heemza 
I may misunderstood issue skin naming. 
All skins have nav bar background according to the skin name here is a screen shot of the yellow skin => https://ibb.co/Rp931gc we do see yellow background with white font color. 
So for the black-light I would expect black-light background nav-bar with white font colors and not opposite. 
It is the same for the black skin it has a white background https://ibb.co/S5VRRzm . 
I will create my own skin to sort it out but the naming doesn't make much sense. 
Otherwise than that big thx to maintainer for this package!

**Comment by heemza** [comment]
I got it.
Your meaning is skin-black should looks like this right?:
<img width="1275" alt="screen shot 2019-01-11 at 23 32 59" src="https://user-images.githubusercontent.com/6562562/51046753-855cc400-15f9-11e9-9a9b-6a6e19fa17bc.png">

If yes, I think it is about naming doesn't make sense as you mention but it isn't a bug.

I'm not sure that you can do black skin which you want (black background with white font)?

**Comment by ronlinet** [comment]
Yes that's what I want, which skin param should I use? 
I see the available colors: blue, black, purple, yellow, red, and green the only that make sense is black or should I code out my own?

**Comment by heemza** [comment]
If you familiar with less that should be easiest way to crate a new skin (real-black)

by copy file skin-yellow.less (or skin-yellow-light.less) to a new file (eg. skin-real-black.less)
and edit `@yellow` to `@black` (or which color you want)
and edit `.skin-yellow` (or `.skin-yellow-light` ) to your skin name (eg. `.skin-real-black`)

(I did this step to do my above screen shot)

**Comment by ronlinet** [comment]
Thx for you feedback. 
I am closing this, yet the naming should be reviewed.
