### ISSUE TITLE
How to display 2 login box on the same line in a responsive way ?

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#205]
Hi 
I would like to display two login box (one with my login box ) and another one with let's say a register box all on the same line but still responsive. No matter what i do, even when i turn the div into span it does not display 2 login box on the same line but one per line . How can i edit the css to get that done ?
![1](https://cloud.githubusercontent.com/assets/925132/5756314/e663386e-9ca5-11e4-95d1-482fb0106565.png)

Thanks

**Comment by lenamtl** [comment]
Hi,
I don't think it is a good idea, you could use a tab or a different link to register .
Check some login snippets:
http://bootsnipp.com/search?q=login

**Comment by kressly** [comment]
Thanks a lot 
I want something like http://bootsnipp.com/snippets/featured/login-form-in-modal but without putting it in the modal box. 
![1](https://cloud.githubusercontent.com/assets/925132/5761259/3d2780f2-9cd2-11e4-9758-2dc39771b16a.png)

My problem is that i dont know how to put the login box to the left so that i may this play my social login bares close to it in another box that will enable my visitors to either log in using their username and passeword or register clicking on the bars.
![2](https://cloud.githubusercontent.com/assets/925132/5761347/cade30d0-9cd2-11e4-8ebb-eacff2db0642.png)

**Comment by almasaeed2010** [comment]
The login page that's provided with the template will need modification to allow that to happen. However, try to use the bootstrap grid system and create your own customized login box. The layout would llok something like this:

```HTML
<div class='row'>
  <div class='col-md-6'>
    <!-- Login box goes here -->
  </div>
  <div class='col-md-6'>
    <!-- Registration box goes here -->
  </div>
</div><!-- /.row -->
```

**Comment by kressly** [comment]
@almasaeed2010 It did not work maybe because my box is not inside and `<Aside> ` . i guess i have to upgrade my knowledge of css 
![1](https://cloud.githubusercontent.com/assets/925132/5762034/3ca6d970-9cd7-11e4-85a8-c80c5debf877.png)

**Comment by almasaeed2010** [comment]
Where is your html code? Please give us the part that shows the boxes.

**Comment by kressly** [comment]
Wow it worked sorry . My internet was slowing down.
http://usefaith.voiedusucces.net/
@almasaeed2010 , thanks a lot :+1: 
However maybe i should not add that immidiatly as @lenamtl said. Please @everybody take a look and give me your view. Should i add the two or only one ?  
THANKS

**Comment by kressly** [comment]
Wow it worked online but not locally in Mozilla .  And i dont know y localy it is not working in mozilla but in CHrome and online it is.
http://usefaith.voiedusucces.net/
@almasaeed2010 , thanks a lot :+1:  but i still need help to fix the local mozilla bug.
 
My local screen shoot with Mozilla 
![1](https://cloud.githubusercontent.com/assets/925132/5763476/8b9a7644-9ce2-11e4-87d0-7609fdb59cf1.png)
My screen shoot with Chrome
![1](https://cloud.githubusercontent.com/assets/925132/5763533/1c35b7cc-9ce3-11e4-8e39-eb0dada7f8c5.png)

**Comment by lenamtl** [comment]
You could use a tab http://getbootstrap.com/components/#nav-tabs
as a container.

Are these links are to create an account on social site or this is the same as using the round icons to login if it's the same you can keep only the round icons.

**Comment by kressly** [comment]
@lenamtl Thanks a lot. Yes the links are the same i was just doubting whether i had to use the round icon or the long bar because people are most familiar with those bar but i will follow your advice. Thanks a lot

**Comment by lenamtl** [comment]
You could add tooltip on the social icons

**Comment by kressly** [comment]
@lenamtl Thanks. I am still learning bootstrap. Is there a tooltip in AdminLte ? Or i have to use the tooltip provided by Bootstrap ? I really have to make time and read the bootstrap documentation.

**Comment by almasaeed2010** [comment]
All of Bootstrap components including tooltips are available in AdminLTE :+1:

**Comment by kressly** [comment]
@almasaeed2010 
Oh ok but i am not seeing the place where the tooltips are. I have been to every single page in my local demo. Please under which section is it ?

**Comment by almasaeed2010** [comment]
Here is the Bootstrap doc files http://getbootstrap.com/javascript/#tooltips

**Comment by kressly** [comment]
@almasaeed2010 Thanks a lot.

**Comment by almasaeed2010** [comment]
No problem!

**Comment by Jigse** [comment]
Hii guy i had a issue i am new to making websites so i created a login page in that page the login box is not coming in centre of screen i tried everything but not working at all please help!!
