### ISSUE TITLE
Windows live Icon for Login with Microsoft Live OAuth 

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#206]
Hi
I did not find inside the icon a windows live OAuth Icon and i was wondering whether someone was able to find an icon so that we may add a login with windows live Oauth. Windows live is now very popular because of Windows Phone, Windows 8.1 and Tablets.
So please someone know how to get the social Icon with AdminLte, that will be great.

**Comment by lenamtl** [comment]
Hi,
Maybe you can use FontAwesome Windows Icon
http://fortawesome.github.io/Font-Awesome/icons/

**Comment by kressly** [comment]
@lenamtl  Thanks a lot
