### ISSUE TITLE
navbar dropdown message-menus bug in firefox

### ISSUE THREAD

**Issue by JupiterMx** [almasaeed2010/AdminLTE#2066]
### Issue type:
- [ ] Feature request 
- [√ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4.8^  
* Operating System: macOS 10.14.3  
* Browser (Version): Firefox (Latest)  

### Description:
navbar dropdown message-menus not shown, the url:
https://adminlte.io/themes/AdminLTE/pages/UI/buttons.html
screenshot below:
![1551058450671](https://user-images.githubusercontent.com/5134140/53309073-ab57d280-38e0-11e9-991c-772d6975ffb9.jpg)
![1551058486062](https://user-images.githubusercontent.com/5134140/53309074-04276b00-38e1-11e9-9fac-06b52b0d46b3.jpg)

**Comment by phoolto** [comment]
Please include more information in your report. So that others can recreate this error.

**Comment by JupiterMx** [comment]
> Please include more information in your report. So that others can recreate this bug.

I updated the screenshot, you should be able to understand it, thank you

**Comment by JupiterMx** [comment]
> Please include more information in your report. So that others can recreate this bug.

firefox

**Comment by JupiterMx** [comment]
I tested it with the latest version of firefox under win7 x64, which is displayed normally. It may be a bug in firefox under macOS, because it was normal on the old version of firefox under macOS.

**Comment by phoolto** [comment]
Thank you for the info. 

I have it running here on my MacBook as-well and I am not getting the same issue. Please check your environment on extensions that might block the functionality and update to the latest version of Firefox.

**Comment by JupiterMx** [comment]
I uninstalled and reinstalled the latest firefox, now it's normal, thank you
