### ISSUE TITLE
v2.4.9 doesn't contain any pages

### ISSUE THREAD

**Issue by toxpal** [almasaeed2010/AdminLTE#2071]
Is there a reason why 2.4.9 release (I mean downloadable ZIP file - https://github.com/almasaeed2010/AdminLTE/archive/v2.4.9.zip) doesn't contain any of HTML pages, documentation, and other stuff, while all other releases contained these pages?

In other words, 2.4.9 only contains several CSS/JS files, and this is it.

P.S. All JS files in 2.4.9 release say 2.4.8 for some reason too.

**Comment by chaozz2989** [comment]
Yep, there is no any HTML code....

**Comment by sihar** [comment]
It doesn't have folder plugins.
How to use any plugin, for example icheck?

**Comment by toxpal** [comment]
@sihar, you need to download v2.4.8, then download v2.4.9 and manually copy files from 2.4.9 to 2.4.8, so you will have all the HTML/plugins stuff + some JS files from latest (2.4.9) version. Just not sure why @almasaeed2010 didn't include HTML stuff in 2.4.9 by default.

**Comment by sihar** [comment]
@toxpal, thank you for the answer. I am just want to know, how if we develop in laptop and deliver in server, should I do same task again? Usually I do composer update in server that done

**Comment by toxpal** [comment]
Yes, just upload all the new files to server, and you should be done.

**Comment by almasaeed2010** [comment]
Fixed on 2.4.10.

Thanks!
