### ISSUE TITLE
Small boxes without link

### ISSUE THREAD

**Issue by Soullivaneuh** [almasaeed2010/AdminLTE#208]
Hi and thanks for you project.

It would be great if we can adapt small boxes css in order to use it without bottom link.

Actually like this:

![small-box-without-link](https://cloud.githubusercontent.com/assets/1698357/5758843/3a326a28-9cc9-11e4-9fc5-9e500fdda22f.jpg)

It half works but the icon is misplaced.

Thanks.

**Comment by almasaeed2010** [comment]
We are implementing a different kind of small boxes that provide informational stats without links, but we will release them as "info boxes" with AdminLTE 2.0. Here is how they might look
![screen shot 2015-01-15 at 11 43 35 am](https://cloud.githubusercontent.com/assets/1512664/5761809/f0e959a2-9cab-11e4-9908-8be50334c31b.png)

**Comment by lenamtl** [comment]
I have not tested it, you need to try some values
Also check in small device css it's may need some adjustment too.

In CSS find
.small-box .icon

try to change  
```
font-size: 90px;
```
to
```
font-size: 70px;
```
or try to change 
```
top: auto;
```
to 
```
top: 3px;
```

**Comment by Soullivaneuh** [comment]
@almasaeed2010 Ok, this new boxes are also good.

But I think that small-boxes without links can render a third kind of box ever nice and different than the other, don't you think?

@lenamtl Thanks for the tip, I will try it. :+1:

**Comment by kressly** [comment]
@almasaeed2010 We will be expecting the version 2.0 patiently

**Comment by almasaeed2010** [comment]
The small boxes might also get a nice upgrade to their css to accept non-link instances.

@kressly You won't be disappointed :+1:

**Comment by Soullivaneuh** [comment]
Glad to hear that, thanks! :+1:

**Comment by kressly** [comment]
@almasaeed2010   :+1:

**Comment by almasaeed2010** [comment]
Fixed in 2.0
