### ISSUE TITLE
Display form inline for first name and last name

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#211]
Hi
I would like to do something like this when it comes to first name and last name
![1](https://cloud.githubusercontent.com/assets/925132/5791091/f74ea86c-9eb1-11e4-9d59-a7860810751b.png)
I would like to display both the First name and last name on the same line but even when i do
`<div class="form-inline"> ` and add `class="form-control"`  to the input they seems not be on the same line. 
![1](https://cloud.githubusercontent.com/assets/925132/5791097/9d2f5bc8-9eb2-11e4-91e0-dcbf970a2e30.png)

Please how to fix this ?

Thanks

**Comment by almasaeed2010** [comment]
The solution to this is similar to the one for the login box and registration boxes. Something like this:
```html
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <input type="text" placeholder="First name" />
    </div>
  </div><!-- /.col -->
  <div class="col-md-6">
    <div class="form-group">
      <input type="text" placeholder="Last name" />
    </div>
  </div><!-- /.col -->
</div><!-- /.row -->
```
Place this inside your form and you good to go.

I think it will benefit you greatly if you skim the documentation of Bootstrap 3, specially the grid system. http://getbootstrap.com/css/#grid

Good luck!

**Comment by kressly** [comment]
@almasaeed2010 Wow. Thanks. I will make time to read the bootstrap doc. Thanks a lot

**Comment by kressly** [comment]
It worked. thanks
