### ISSUE TITLE
Bug in the Chat in Mozilla

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#214]
In mozilla, you can not type a text in the chat field that is on the dashboad
![1](https://cloud.githubusercontent.com/assets/925132/5794790/b00c124a-9f75-11e4-8a24-7ab96f3acc38.png)

**Comment by kressly** [comment]
Does somebody has a fix for this ?

**Comment by lenamtl** [comment]
This may be related to this
https://github.com/almasaeed2010/AdminLTE/issues/89

**Comment by kressly** [comment]
@lenamtl Really nice meeting you oooo. Thanks a lot. Always with the solution.
