### ISSUE TITLE
TimePicker can not display well when it is down in the page

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#216]
Hi
When you go to the  advanced element page under the Forms page, you will see that when you click in the Timepicker it can not display well. Is there a fix for this or do we have to put some ` <br> <br>` under it  ?

**Comment by lenamtl** [comment]
I don't know the issue you have but you can try to udpate the widget
http://jdewit.github.io/bootstrap-timepicker/

**Comment by kressly** [comment]
Thanks. I went to the page and went to the Github page of that page and realize that the project is no longer maintained.

**Comment by lenamtl** [comment]
There are several time picker widget to choose from
http://tarruda.github.io/bootstrap-datetimepicker
https://github.com/Eonasdan/bootstrap-datetimepicker
https://github.com/weareoutman/clockpicker

**Comment by kressly** [comment]
@lenamtl 
Thanks a lot
