### ISSUE TITLE
How to use the existing slimscroll with chat members box

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#217]
Hi
I saw that slim scroll is already in use in adminlte though i dont really see the file invlude in my source code. How can i add a list of members close to the chat box with slimscroll ? Do i have to include slimscroll js again ? I have used bootstrap grid to devide into two row  already and i have added the chat box to one row. I would like to add a box with the member list with slimscroll

**Comment by lenamtl** [comment]
That's true I don't see where it is included...

The script slimscroll file is under js/plugin/slimscroll
There are javascript function in the app.js file

Unfortunately I don't know much about slimscroll 
http://rocha.la/jQuery-slimScroll

**Comment by kressly** [comment]
@lenamtl thanks. I have gone to the page. And have seen the code. I have also seen it in the directory. What i do not understand is the fact that AdminLte uses it without including the script. So now if i want to use it do i have to include the script or just use it like AdminLte ? I want to create for the chat, the list of people the user is chatting with

**Comment by lenamtl** [comment]
I guess you should include it, and see if it's work....

**Comment by kressly** [comment]
Please somebody help me find out what am i doing wrong here.
I copied and pasted the code from the chat and that code was working well and had some slimscroll but now that i copied it to another file, no more slimscroll
Pleaes take a look at the page that has a bug at
http://usefaith.voiedusucces.net/messages_lire.php
After the login box you will see two chat boxes but they do not have slimscroll 
Now take a look at this page where i just copied the code from yet it is not working on the page i gave first
http://usefaith.voiedusucces.net/admin_lte_master_design_filled.php

What am i missing. I do not want to include slimscroll twice  in order to avoid page load.

**Comment by lenamtl** [comment]
Have you tried to comment the slimscroll code from the app.js
then include the slimscroll.js so it's wont load twice.
You may need to adapt the script later, but it's worth a try.

**Comment by kressly** [comment]
I have found the solution. It was just adding the slimscroll code that i want to use to the app.js and there is no need to add the slimscoll.js itself

```
$(".slimscroll").slimscroll({
        height: "300px",
        alwaysVisible: false,
        size: "10px"
    }).css("width", "100%");

```

From there all i have to do is to add the class slimscroll to any div and it will slimscroll
