### ISSUE TITLE
Live Preview sidebar dashboard item not presenting all options

### ISSUE THREAD

**Issue by MLoureiro** [almasaeed2010/AdminLTE#219]
Hi everyone 

I've attached an image with the issue.
On live preview sidebar under `Main Navigaviton` clicking on `Dashboard` wont show all options.

This might be related with https://github.com/almasaeed2010/AdminLTE/issues/218

![screen shot 2015-01-25 at 00 12 52](https://cloud.githubusercontent.com/assets/3427665/5889592/97afd70c-a427-11e4-9119-fe307d6c063d.png)

**Comment by almasaeed2010** [comment]
This is the wrong version of AdminLTE. By mistake I uploaded a non compatible CSS file. I will fix that now.

**Comment by almasaeed2010** [comment]
It should work now.

**Comment by MLoureiro** [comment]
Yeap, fixed :)

**Comment by MLoureiro** [comment]
Great job!

**Comment by almasaeed2010** [comment]
:+1:
