### ISSUE TITLE
pagination should be surrounded by <nav>

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#222]
I think the template should follow Bootstrap syntax
for example pagination and pager should be surrounded by 
```<nav> </nav>```

refer to other similar bug #65

**Comment by almasaeed2010** [comment]
You can add that to your HTML it won't affect the style. This depends on the implementer's practice.

**Comment by almasaeed2010** [comment]
issue #64 has been corrected in 2.0.
