### ISSUE TITLE
Horizontal scrollbar in tables

### ISSUE THREAD

**Issue by spescina** [almasaeed2010/AdminLTE#225]
I have installed version 1.3.1  
I have horizontal scrollbars in the table boxes. Is it normal?

**Comment by kressly** [comment]
Yes it is. It depends on the platform you are using to view it. If it is on mobile device, u may get and horizontal scroll-bar if the table is larger than the screen. That is why it is called responsive. It can adapt itself to any environment.

**Comment by lenamtl** [comment]
You can use a different responsive table script that allow to hide column depending of the size view, the hidden column with a garage door widget.

Or a table that allow user to select the column they want to display.

**Comment by almasaeed2010** [comment]
@spescina If you remove the ```table-responsive`` class from the div that contains the table, you won't get the scroll bar and the table will fallback to its normal behavior. However, this is not recommended for tables that contain many columns because it will just annoy the user who displays it on a small device.

**Comment by spescina** [comment]
wait, I have scrollbars at full hd resolution...

**Comment by lenamtl** [comment]
How many columns do you have, hong long is the information, I guess this will occur in any resolution if the table is large...
That's why you will need to use a responsive table that have more features there are several responsive scripts like datatable, footable, tablesaw etc..

**Comment by spescina** [comment]
This is what I see on http://almsaeedstudio.com/AdminLTE/pages/tables/data.html
I'm using Chrome at 1280x800 but I have the same issue at 1920x1080 and using my installation instead of the preview site.

![scrollbars](https://cloud.githubusercontent.com/assets/1956604/6077148/3c6625ee-adec-11e4-8475-a04c24e2f4fb.jpg)

**Comment by lenamtl** [comment]
I'm having this also on the demo. This is maybe related to other scrollbar issues...
You can try to add 
overflow-x: hidden!important;
to .box .box-body css
I'm using Footable and I don't have this issue.

**Comment by spescina** [comment]
this seems to work. tnx.

**Comment by Naveed-anwar123** [comment]
How to add horizontal scrollbar on mobile screen?

**Comment by abkiran** [comment]
> How to add horizontal scrollbar on mobile screen?

**Comment by dereuromark** [comment]
Has this been patched into the v2 or v3 series?
