### ISSUE TITLE
footer jumps when the size of sidebar is lower than the top of the website.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [almasaeed2010/AdminLTE#226]
Hi, Excellent theme'm adapting the template to yii2, and had made in the previous version I changed all new classes and works well only the footer jump to reload the website, because the sidebar is smaller than the top of the screen.

Annex pictures:

Footer Jump in reload website:

![admin-lte01](https://cloud.githubusercontent.com/assets/4957021/6047765/dc6d6b76-ac7d-11e4-8575-b6651559e041.jpg)

Footer after reload website is ok:

![admin-lte02](https://cloud.githubusercontent.com/assets/4957021/6047782/f1b22292-ac7d-11e4-84be-a391ce1b181e.jpg)

**Comment by kressly** [comment]
Please which version of AdminLte are u using ? The footer has been fixed in the latest release
You can download it from 
http://almsaeedstudio.com/themes/AdminLTE/AdminLTE2-dist.zip

**Comment by tecnologiaterabyte** [comment]
I install via composer "bower-asset/admin-lte": "dev-master".

**Comment by almasaeed2010** [comment]
If you upgraded to the latest version then you should read the [upgrade guide](http://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade)

**Comment by tecnologiaterabyte** [comment]
thanks for your reply,

My Code Main-Dashboard.php

    <?php
        use yii\helpers\Html;
        use yii\widgets\Breadcrumbs;
        use backend\widgets\Alert;

        /* @var $this \yii\web\View */

    ?>

    <?php $this->beginPage() ?>
        <!DOCTYPE html>
        <html lang="<?= Yii::$app->language ?>">
        <head>
            <meta charset="<?= Yii::$app->charset ?>"/>
            <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
            <?= Html::csrfMetaTags() ?>
            <title><?= Html::encode($this->title) ?></title>
            
            <?php $this->head() ?>
                
                
                
        </head>
        <?php $this->beginBody() ?>
            <?php if (!\Yii::$app->user->isGuest): ?>
                <?php if (Yii::$app->user->can('Administrador')): ?>
                    <body class="skin-blue">
                    
                    <div class="wrapper">
                        
                        <header class="main-header">
                            
                            <?= Html::a('ChecktimeWeb v. 1.0.', \Yii::$app->homeUrl, ['class' => 'logo']) ?>
                            
                            <nav class="navbar navbar-static-top" role="navigation">
                                
                                <?= Html::a('<span class=sr-only>Toggle navigation</span><span class=icon-bar></span><span class=icon-bar></span><span class=icon-bar></span>','#', ['class' => 'sidebar-toggle', 'data-toggle'=>'offcanvas','role'=>'button']) ?>
                                
                               <?= $this->render('_menuser') ?>
                            </nav>
                        </header>
                        
                        <aside class="main-sidebar">
                            
                            <section class="sidebar">
                                
                                <div class="user-panel">
                                    <div class="pull-left image">
                                        <?= html::img(\Yii::$app->session->get('user.avatar30'), $options = ['class' => 'img-rounded'], ['aria-expanded' => 'false']) ?>
                                   </div>
                                    <div class="pull-left info">
                                        <p><?= \Yii::$app->session->get('user.username') ?></p>
                                        <?= Html::a('<i class="fa fa-circle text-success"></i> Online','#') ?>
                                    </div>
                               </div>
                               
                                <?= $this->render('_sidebar') ?>
                            </section>
                            
                        </aside>
                        
                        
                        <div class="content-wrapper">
                            <section class="content-header">
                                
                                <div class="container">
                                    <?= Breadcrumbs::widget([
                                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                                    ]) ?>
                                </div>
                                
                            </section>
                            <section class="content">
                                
                                <?= $content ?>
                                <?= Alert::widget() ?>
                                
                            </section>
                        </div>
                        
                       <?= $this->render('_footer') ?>
                    </div>
                    </body>
                <?php endif; ?>
            <?php endif; ?>
        <?php $this->endBody() ?>
        </html>
    
![adminlte-viewcode](https://cloud.githubusercontent.com/assets/4957021/6052197/1bd23246-aca2-11e4-8545-5db8978bfef6.png)
<?php $this->endPage() ?>

**Comment by almasaeed2010** [comment]
You cannot use a container in the main content because the .content-wrapper creates that by default. Remove the container div and try again.
When in doubt, consult the blank example page.

**Comment by tecnologiaterabyte** [comment]
I removed the <div class = container>, but just keep doing jumping footer, now does it faster I reviewed the example of the blank page and have all parts of the layout correctly, not if be any dependence on jquery or some .js file, jquery'm running v2.1.3, who else could verify and thank you very much, will wait to leave the paid version because it really worth it, and thus also help so that they can produce new themes.

**Comment by tecnologiaterabyte** [comment]
If you check the example of blank page on your website http://almsaeedstudio.com/themes/AdminLTE/pages/examples/blank.html really jumping footer, makes fast but Salta-

**Comment by almasaeed2010** [comment]
I get what you mean now. Unfortunately there isn't a cross browser way to fix that except by adding a min height to the content which can be inconvenient since you will have to add that to every page that doesn't contain much content. Otherwise, you'll have to tolerate the jumping footer for now.

**Comment by tecnologiaterabyte** [comment]
no problem it just wanted you to have it present excellent upgrade to separate the skins, congratulations this being fine, thks.

**Comment by lenamtl** [comment]
You can use a sticky footer instead.

**Comment by marcioferlan** [comment]
Hello, guys!

I don't know if you guys are still facing this issue, but this CSS workaround seems to have worked for me: 
```css
<style>
  html { height: 100% !important; }
  body { height: 100% !important; padding-bottom: 30px; }
  .main-footer { position: fixed; left: 0; right: 0; bottom: 0; }
</style>
```

**Comment by harshapower** [comment]
add <?php include_once('footer.php') ?> at the end of index.php code.
