### ISSUE TITLE
Why use to need overflow-x: hidden!important; ?

### ISSUE THREAD

**Issue by githubjeka** [almasaeed2010/AdminLTE#227]
It closely related with https://github.com/almasaeed2010/AdminLTE/issues/185

I delete this `overflow-x: hidden!important;`, because it pull second y-scroll on page. After this I get scroll to X only, y-scroll removed himself.

Why X-scroll appears? Because `Nav` (AdminLte template) uses not try template from bootstrap:

![image](https://cloud.githubusercontent.com/assets/874234/6055930/a6b61e96-ad19-11e4-9133-675bf14f8e73.png)

Compare:
http://getbootstrap.com/components/#navbar
https://github.com/almasaeed2010/AdminLTE/blob/master/pages/layout/top-nav.html#L30

AdminLTE doesn't use `  <div class="container-fluid">` and `<ul class="nav navbar-nav navbar-right">`.

**Comment by almasaeed2010** [comment]
Hi,

which version of AdminLTE are you using?

**Comment by githubjeka** [comment]
latest 1.3.1

**Comment by almasaeed2010** [comment]
The implementation of the navbar in AdminLTE differs slightly from Bootstrap because of the custom dropdown menus. The ```container-fluid``` class doesn't have to be used because we don't want the templates margined or to use the grid system. However, if you use the navbar component in the content, you can implement it as Bootstrap does. AdminLTE 2.0, solved the scrollbar issue.

**Comment by son2xp2go** [comment]
in yii2. where can i find that  overflow-x: hidden!important;???

**Comment by githubjeka** [comment]
Yii2 `dmstr/yii2-adminlte-asset` using AdminLTE 2.0 in composer for `phundament/app`. But for `advanced` or `basic` html code remained unchanged from AdminLTE 1.0. This problem has been urgent for AdminLTE 1.0. Now it fixed.

**Comment by son2xp2go** [comment]
I only see php files inside adminlte-asset folder. no core.less.. Where exactly do I delete overflow-x: hidden!important;???
