### ISSUE TITLE
Links to implementations?

### ISSUE THREAD

**Issue by schmunk42** [almasaeed2010/AdminLTE#228]
We've created an asset bundle for AdminLTE for Yii 2.0 Framework https://github.com/dmstr/yii2-adminlte-asset
I wonder if you'd like to link to implementations of your theme for different frameworks, etc.. in the docs.

PS: You've done great work!

**Comment by yajra** [comment]
Just in case... Here's my implementation of AdminLTE for Laravel 4.2 https://github.com/yajra/laravel-admin-template. I'm also planning to develop a new starter kit for Laravel 5 using AdminLTE2 ^_^. 

Thanks for a great work!

**Comment by almasaeed2010** [comment]
This is great! I will see if there is an appropriate place for such links in the docs.

**Comment by thePanz** [comment]
Another (not mine) AdminLTE implementation for Symfony2
https://github.com/avanzu/AdminThemeBundle

**Comment by almasaeed2010** [comment]
@nicolas-besnard provided a Gem implementation. I am posting it here for reference until the implementations section in the docs is ready.

https://github.com/nicolas-besnard/adminlte2-rails

**Comment by almasaeed2010** [comment]
Okay, 28 days late but I wanted to say that I am gonna add this in our blog alongside with a few more implementations. Hopefully soon :-z

**Comment by almasaeed2010** [comment]
Done.
