### ISSUE TITLE
To-Do List  Checkbox Issue

### ISSUE THREAD

**Issue by ferman2147** [almasaeed2010/AdminLTE#230]
Hi everyone,
As you all know there is a to-do list box on the homepage. I take that to-do list and make a todolist.html  page (with everything in a folder on desktop) and it work just fine. But when I move everything to my localhost (as in .../wamp/www/... directory) the checkboxes won't be checked. I click on and nothing happens. Even though the dragging works just fine, I can't find why checkboxes don't work. Much appreciated if anyone can help solving this issue.
Thanks in advance.

**Comment by almasaeed2010** [comment]
Make sure you have the iCheck plugin loaded currently with both its JS and css sources

**Comment by ferman2147** [comment]
Thanks! Issue solved!
