### ISSUE TITLE
treview class active no working yii2.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [almasaeed2010/AdminLTE#231]
Good morning I am implementing the template for yii2, and I found the problem that when a menu option is selected treview, this does not change the class active the new option.

My Code:

    <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
            <li class="treeview active">
                <a href="/admin">
                    <i class="fa fa-dashboard"></i> <span>Home</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
            </li>
        <li>
            <a href= "/admin/horarios/index.html">
                <i class="fa fa-th"></i> <span>Horarios</span> <small class="label pull-right bg-green">new</small>
            </a>
        </li>
    </ul>

Example: URL(https://tecnologiaterabyte.com/admin/horarios/index.html).

![error_url_01](https://cloud.githubusercontent.com/assets/4957021/6081416/81cfed50-adeb-11e4-805b-b73a78d7c54d.jpg)

As you can see the working class does not change, that could be causing this error,

Thanks in advance for the help,

**Comment by almasaeed2010** [comment]
Hi,

Are you using ajax to load your content?

**Comment by tecnologiaterabyte** [comment]
No.

**Comment by almasaeed2010** [comment]
The template does not provide an automatic mechanism to change the active element in the menu, you must manually do that. You should view issue #228 and review their Yii implementation.

**Comment by tecnologiaterabyte** [comment]
Ok no problem simple función cudtom js.
