### ISSUE TITLE
AdminLte 2 Chart - Replace Morris.js

### ISSUE THREAD

**Issue by fredrkr** [almasaeed2010/AdminLTE#232]
As stated here https://github.com/morrisjs/morris.js#contributors-wanted, Morris.js is no longer being maintained. Breaking changes in its dependencies (jQuery and Raphael), would therefore render Morris.js broken.

For AdminLTE 2.0, I suggest that Morris.js be replaced by Chart.js (www.chartjs.org), which offers similar functionality and more. Of course, it's also being actively maintained.

**Comment by almasaeed2010** [comment]
That's a great suggestion! This is exactly what we did for [Dashboard v2](http://almsaeedstudio.com/themes/AdminLTE/index2.html). We loved ChartJS once we saw it.

I copied my answer from the previous issue :v:

**Comment by almasaeed2010** [comment]
We won't remove Morris.js from the old dashboard since some implementations depend on it and it doesn't affect the main CSS files.

**Comment by fredrkr** [comment]
I can appreciate maintaining backwards compatibility, but I would suggest that you somehow promote the use of a third-party library that is maintained over one that isn't. You could, for instance, display a mild warning/info alert on your Morris.js-demo page, saying that the library is no longer maintained and that you *recommend* the use of Chart.js instead?

**Comment by almasaeed2010** [comment]
That's a good idea. I will add a callout in the morris charts page. :+1:

**Comment by kressly** [comment]
Thanks @fredrkr  :+1:

**Comment by jkga** [comment]
Any update on this issue ?  Morris has been [reported to be vulnerable in XSS](https://snyk.io/test/npm/admin-lte) and there is **NO FIX** since it is no longer maintained.

**Comment by rkorzeniewski** [comment]
You should switch to ChartJS which is actively maintained.

**Comment by piperone** [comment]
@jkga If you're using Morris.js, you should stop. I hasn't been maintained properly for way too long and there is no indication that's going to change. 

The result from this issue was that a warning notice was placed on the "Charts -> Morris" example-page. Don't think anything else is going to happen.

@rkorzeniewski ChartJS is definitely the way to go (which I also mentioned four(!) years ago in the OP). I can also recommend Highcharts if your project is open-source.

**Comment by jkga** [comment]
@piperone  No I dont, but it might be good to remove it completely from the dependencies

**Comment by Jamesking56** [comment]
@jkga I think it should be at least marked as an optional dependency, does everyone agree?
