### ISSUE TITLE
Validation states won't work on registration and login pages.

### ISSUE THREAD

**Issue by baringji** [almasaeed2010/AdminLTE#234]
http://getbootstrap.com/css/#forms-control-validation
http://almsaeedstudio.com/AdminLTE/pages/examples/register.html

It says in the docs, just put `.has-error`, `.has-success` or `.has-warning` on the parent of the forms and it will apply the validation states. But AdminLTE overrides the border thus it only displays white when applying the states.

**Comment by almasaeed2010** [comment]
Hi

In the demo it's displayed correctly. Please check your implementation.
http://almsaeedstudio.com/themes/AdminLTE/pages/forms/general.html

**Comment by almasaeed2010** [comment]
Sorry I didn't see the page you mentioned. AdminLTE 2.0 solved this issue by completely reimplementing the registration, login and lockscreen pages. You can view [AdminLTE 2.0 here](http://almsaeedstudio.com/themes/AdminLTE/index2.html)
And you can download it by downloading the master repo. I have to warn you though that it is an Alpha release. The production release will be out soon.

**Comment by baringji** [comment]
I will just stick with the latest stable version 1.3.1. But no worries. This is considered fixed in future release.

fixed in v.2.0
