### ISSUE TITLE
Button link wrong rendering on solid box

### ISSUE THREAD

**Issue by Soullivaneuh** [almasaeed2010/AdminLTE#236]
If we want to add a link on a solid box header, the default text color of this button is overridden by adminLTE's CSS.

If I you try with this part of html, inside a solid-box:

```html
<div class="box-header">
    <h4 class="box-title">
        <img src="https://www.gravatar.com/avatar/...">
        John Doe
    </h4>
    <div class="box-tools pull-right">
        <div class="label label-default">6 666,66 €</div>
        <div class="label label-info">2</div>
        <a href="#" class="btn btn-sm btn-primary" title="Fiche client">
            <i class="fa fa-user"></i>
        </a>
        <button class="btn btn-sm btn-primary" data-widget="collapse"><i class="fa fa-plus"></i></button>
    </div>
</div>
```

You will have something like this (the blue one):

![widget_buttons_links](https://cloud.githubusercontent.com/assets/1698357/6144860/1033f2f0-b1dc-11e4-8369-2aaff94f65b2.png)

As you can see, the user icon is not white.

Using AdminLTE v1.2.

Thanks.

**Comment by almasaeed2010** [comment]
Please refer to issue #223. The solution is there.

**Comment by Soullivaneuh** [comment]
Thanks for your help and sorry for duplicate.
