### ISSUE TITLE
Slimscroll doesn't work with IE10

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#237]
I have tested the fixed layout with IE10 and noticed that slimscroll doesn't render correctly. This could be resolved by modifying the script. However, doing so will make it difficult to upgrade the plugin when a new release comes out. Should we use a different plugin? If so, are there any recommendations or preferences?

**Comment by lenamtl** [comment]
Some suggestions
*I have not tested and don't know if they are all responsive:
http://darsa.in/sly/
http://noraesae.github.io/perfect-scrollbar/
https://github.com/malihu/malihu-custom-scrollbar-plugin
http://jscrollpane.kelvinluck.com/
https://github.com/cubiq/iscroll

**Comment by RMK147** [comment]
https://github.com/malihu/malihu-custom-scrollbar-plugin is pretty good

**Comment by kressly** [comment]
I have checked https://github.com/malihu/malihu-custom-scrollbar-plugin and it is not bad. However we need one where they have an active community so that they may answer when we have a question or need something to be corrected. So before choosing let's see which one is still in active development

**Comment by kressly** [comment]
There are a lot of issue about slimscroll. Have you found a replacement ?

**Comment by almasaeed2010** [comment]
I am currently busy and unable to do much work on AdminLTE. Hopefully by the weekend we will have a few updates.

**Comment by kressly** [comment]
But if you find a work around it will be awesome because SlimScroll so far has shown to be useful except some few issues. If there is a workaround to make it work with IE 10 that will be awesome.

**Comment by almasaeed2010** [comment]
I chose SlimScroll because it is lightweight and easily customizable. This is all I could find about the issue in their repository. https://github.com/rochal/jQuery-slimScroll/issues/84

**Comment by kressly** [comment]
Yes and the fact that it is lightweight is VERY important. I am using windows phone 8.1 and it is working on it however i dont know whether my ie on 8.1 is ten or eleven. So have you applied that fix and tested it with IE 10.
I have also found this on [stackoverflow](http://stackoverflow.com/questions/23197250/jquery-slimscroll-not-draggable-in-ie-9-and-ie-10)

**Comment by almasaeed2010** [comment]
Ok so I have finally figured out how to fix this. I have updated the slim scroll plugin to listen to [MS pointer events](https://msdn.microsoft.com/en-us/library/ie/dn433244(v=vs.85).aspx). Since the script doesn't have any other problems with the template, I will keep it and provide limited support for it.

**Comment by lenamtl** [comment]
Good news, thanks

**Comment by lenamtl** [comment]
I saw this one this morning, incase we need another one
https://github.com/inuyaksa/jquery.nicescroll
