### ISSUE TITLE
AdminLTE 1.3.1 Slow to load on apple Machine

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#240]
Hi
I tested AdminLte 1.3.1 on apple but it seems very slow to load . Please do you have a fix for this ?
Tks

**Comment by kressly** [comment]
Has somebody else tested it ?
Can it be fixed for the version 2 ?
Thanks

**Comment by lenamtl** [comment]
Which browser?
Which page 
The online demo page load ok using chrome on Mac

**Comment by almasaeed2010** [comment]
Hello @kressly 
What do you mean by Apple machine? Please list the specifications of the machine such as processor, ram and date of make. I work on a Macbook Pro and haven't noticed any difference in performance from other machines.

**Comment by almasaeed2010** [comment]
You should also keep in mind the speed of internet because some libraries are large and others are loaded from CDNs. Both of which could cause a slight performance hiccup until they are cached in the browser.

**Comment by kasperhartwich** [comment]
The 90s called. They want their bug report back. :smile:

**Comment by kressly** [comment]
It is a Mac Air.

**Comment by kressly** [comment]
It is a Mac Air. 
@lenamtl the login page.

**Comment by almasaeed2010** [comment]
Is it still loading slow? 
I have tested all pages on multiple machines and I haven't had that problem. Are you using chrome?

**Comment by kressly** [comment]
No it is on a friend machine. I have tested it at least 3 times and it loads very slow. But i am not there at the moment. I will close this topic and get back to you the next time i test it

**Comment by lenamtl** [comment]
You should verify using chrome dev tool if there is any 404 error not found ...
