### ISSUE TITLE
Can we start using version 2 ? Concern about version 2

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#244]
Hi
First of all i would like to thank @almasaeed2010 for AdminLte and the whole community of AdminLte. Now can we start using the available version of AdminLte 2 or should we wait 

Also I am planning to use Dashboard 2 for the members and Dashboard one for the administrator. However I do not see the class offline and online for the chat in the dashboard 2 demo. I hope it has not been removed from the system.

Finally, is it possible to replace the color black of the left side of AdminLte 2 with the color of the left side of 1.3 ?

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE 2.0 is not ready yet. There are few know issues, such as dropdown menus in the navbar on small screens don't display links properly. Not everything has been tested on all major browsers. It's safer to use a tested version for now. 

It's exams period so my work is a little slow but I am hoping it will be ready very soon.

**Comment by almasaeed2010** [comment]
The sidebar colors can easily be adjusted using the less variables. Look for @sidebar-dark-* attributes and modify them as you wish. I am planning on adding a light sidebar skin in 2.0.1.

**Comment by kressly** [comment]
Wow. @almasaeed2010 always full of innovation. Tks bro for everything. I am working on a project with AdminLte, when I sell it and make some income out of it, I will "support" ur work. For now good luck with ur exam.
