### ISSUE TITLE
almsaeedstudio.com IS DOWN

### ISSUE THREAD

**Issue by mistermendez** [almasaeed2010/AdminLTE#245]
Bandwidth limit reached.

This is a good problem.

Maybe time for new hosting provider?

**Comment by almasaeed2010** [comment]
Thank you for informing us! Our website is being transferred to a new hosting service. We apologize for the inconvenience.

**Comment by kressly** [comment]
have you ever considered hostgator ? They are very good

**Comment by almasaeed2010** [comment]
Almsaeed Studio is now up and running. 

@kressly my experience with Godaddy's vps was really good before so I transferred to it since it's familiar to me. Thank you for the suggestion!
