### ISSUE TITLE
Hiding logo when hiding sidebar and collapsing sidebar to a vertical bar

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#246]
Greetings for the great work. I know these features can be implemented after downloading the source but I'm wondering if there's a way to achieve them using the settings to avoid rework with future versions:
1. Hide the logo when hiding the sidebar.
2. Collapse the sidebar to a small vertical icon-only bar with badges, instead of totally hiding it. In this case, the above feature will make it better aesthetically.

**Comment by kressly** [comment]
Let hidding the logo be VERY OPTIONAL because not everybody would like to hide their logo. In fact most companies I know wants their logo to be seen

**Comment by almasaeed2010** [comment]
Hello @YasserHassan 

We plan on implementing a mini-sidebar (icon only) in a future release. Make sure when implementing your sidebar to <span> to you links. This will allow you to easily migrate to the new version when it becomes available.

Example:
```html
<ul class="sidebar-menu">
  <li>
    <a href='/home'>
      <i class='fa fa-some-icon'></i><span>A Link</span>
    </a>
  </li>
  ...
</ul>
```

**Comment by YasserHassan** [comment]
@almasaeed2010, this is good news. Any plans for the version and time where the mini-sidebar will be introduced?

@kressly, hiding the logo should be an option in the template of course but whether an actual application option or not should depend on your implementation. I asked for hiding the logo option to minimize its area when the sidebar is hidden which would be aesthetically better in my opinion. But probably replacing this feature by showing an alternate small logo icon version would be better. That will make more sense with the mini-sidebar where it would be better to have one side stripe running from top to bottom with the logo at the top and bar icons below and all having the same width.

While we are at it, with the current implementation, is there a way to refer to an external custom settings file (like colors, ...etc) only if that file exists, so when downloading a new version the developer would drop that file in the template and generate a customized one. My point is to avoid touching the original source after download and preserve the custom settings from version to another.

**Comment by lenamtl** [comment]
+1 for mini side bar

**Comment by irazasyed** [comment]
+1 for mini sidebar, Was looking for something like this before. Would definitely be a good feature.

**Comment by ismailbay** [comment]
+1

**Comment by almasaeed2010** [comment]
Has been added to the [todo list](https://github.com/almasaeed2010/AdminLTE#todo-list).
