### ISSUE TITLE
Adminlte 2 How to keep the modal of 1.3

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#250]
Hi
First of all, @almasaeed2010 Big Up, thank you :+1:  :+100: :100: 
Now i have downloaded the version 2 but i still prefer the old modal of version 1.3 that was at the place where we compose message. Can i still have it in the version 2 ? What am i suppose to copy to have it in version 2 ?

Thanks a lot :+1:

**Comment by almasaeed2010** [comment]
Hello,

To remove any component (including the custom modals), open the build/less/AdminLTE.less file and comment the component that you don't require. Then recompile AdminLTE.less into AdminLTE.css. Are you familiar with LESS?

There are services that automate the compiling of LESS files such [Koala](http://koala-app.com/). Or you can use the attached Gruntfile.js to watch for changes (that is if you are familiar with grunt).

If you must edit the main the css file, then find ```Component: modal``` and remove the CSS rules.

**Comment by kressly** [comment]
Thanks a lot
