### ISSUE TITLE
Adminlte 2 Suggestion by @lukacavic 

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#251]
There is a suggestion by @lukacavic that i find quite interesting. However it would have been better if he had opened a new issue for it

https://github.com/almasaeed2010/AdminLTE/issues/209#issuecomment-75554189

Please @almasaeed2010  can we have that riight panel added to the 2.0  ?

 @lenamtl , you are good with css, can you help with this please ?

![Right panel added](https://cloud.githubusercontent.com/assets/4538071/6329785/bccfc7f0-bb73-11e4-8007-4590ea3e718f.png)

**Comment by lenamtl** [comment]
Hi,
I have almost complete my project with the v1.
I have't found the time to test the v2 yet.
About the right side this is more than just CSS it's need to be a container in the layout.

**Comment by kressly** [comment]
@lenamtl thanks a lotand wow please when u complete the project send me a link to check it out :D. I am still working on mine too and hope to finish it soon. 
 I guess @almasaeed2010 can help with the layou

**Comment by almasaeed2010** [comment]
I will add that to the todo list. I will also publish the todo list on Github soon.

**Comment by almasaeed2010** [comment]
@lenamtl we can certainly create the right sidebar and make it completely optional so that we keep backwards compatibility with v2.0.0.

**Comment by kressly** [comment]
:+1:

**Comment by lenamtl** [comment]
+1

**Comment by lukacavic** [comment]
thanks for adding to todo list :)

**Comment by stevenjlho** [comment]
I want to have a sass version. Can you @almasaeed2010 add this task to the todo list?

**Comment by YasserHassan** [comment]
+1 for the right panel with consideration for working with small screens especially mobile phones. Probably providing the options of making it float over the content from the right edge when expanded, and another to make it a column in the page like the left panel can provide good alternatives that suit different project situations.

**Comment by adaniello** [comment]
+1

**Comment by kressly** [comment]
Let this right side also hold a place of small advertisement like we see on facebook for example. And since many people seems to be interested in this i think i have to re-open this, unless @almasaeed2010 has already added it to the to do list

**Comment by almasaeed2010** [comment]
Hello,

You can view the todo list here https://github.com/almasaeed2010/AdminLTE#todo-list

This sidebar should be available in version 2.1.

**Comment by YasserHassan** [comment]
@almasaeed2010 do you have an expected time version 2.1?

**Comment by almasaeed2010** [comment]
Right now we are working on the main website. The relaunch should be within a couple of days. Then we will start working on 2.1.0 which should have the minisidbar, right sidebar and a light sidebar color option. I can't promise a specific time, but I hope the pre-release will be out soon.

**Comment by YasserHassan** [comment]
You are doing a great work, congratulations.

**Comment by YasserHassan** [comment]
By the way, it would be great if the sidebar has tabs like shown in the above sample. It's a good place to extend the main display with related information and functionality without cluttering it and tabs can help organize this content into separate logical groups for visual clarity.

**Comment by ganthi** [comment]
In my design, id i open more tabs, it show next line.


![untitled1](https://cloud.githubusercontent.com/assets/8499105/6775402/bbe94a7a-d156-11e4-8192-02d873907275.png)

How can i show all the tabs in same line. Is it possible?

Thanks

**Comment by kressly** [comment]
@ganthi Please open a new ticket for this. Thanks
