### ISSUE TITLE
Select boxes missing of "down" arrow (usability issue)

### ISSUE THREAD

**Issue by thePanz** [almasaeed2010/AdminLTE#254]
The Select boxes are missing of the "down" arrow on the side, thus not clearly showing that such elements are selec-boxes!
This is an (important!) usability issue IMHO

**Comment by almasaeed2010** [comment]
Hello,

Please specify the OS and browser you are using. A screenshot could also help a lot.

**Comment by lenamtl** [comment]
On the demo there is NO arrow on select boxes.
I think this should be added for a better user experience and to make a diff between an input box and select box

**Comment by almasaeed2010** [comment]
I see the issue now. I will add that to 2.0.1 soon.

**Comment by almasaeed2010** [comment]
Solved.
