### ISSUE TITLE
Why verstion is 1.2 for v.2 in annotation css file?

### ISSUE THREAD

**Issue by githubjeka** [almasaeed2010/AdminLTE#255]
https://github.com/almasaeed2010/AdminLTE/blob/0223d7b34a5df9153c34e322a2fd7c4721a7a606/build/less/AdminLTE.less#L2

It confuses me.

**Comment by almasaeed2010** [comment]
Hi!

That has been fixed in master. I create a patch release soon.

**Comment by almasaeed2010** [comment]
Solved.
