### ISSUE TITLE
[v2] Pace?

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#256]
Hi, have you removed Pace, cause I don't see it on the demo?

**Comment by almasaeed2010** [comment]
Hello,
Pace is currently optional. Since we didn't implement a custom style for it, we removed it. However, you can download it and place it in your files and it will automatically work.

**Comment by lenamtl** [comment]
Ok thanks

**Comment by kressly** [comment]
Please sorry to ask this but what is Pace ? i have googled it but i did not get a programming result ? For lenamtl to be interested in this, it must be good

**Comment by lenamtl** [comment]
Pace it is the top line animation when loading the page, that was in version 1.
For more information:
http://github.hubspot.com/pace/docs/welcome/

**Comment by kressly** [comment]
Oh ok. Thanks. I use to see it in 1.3 but did not know where it was from. It looked like youtube loader

**Comment by lenamtl** [comment]
Hi,
Pace folder is still in the package v2 but not in the code.
Maybe you can add the info in the documentation or remove it completely, it's up to you.
I'm still using it.

**Comment by almasaeed2010** [comment]
I am planning to create a custom CSS file for it and make it optional. So, I'll keep it there for now.
