### ISSUE TITLE
checkbox out of the box

### ISSUE THREAD

**Issue by adminko-svk** [almasaeed2010/AdminLTE#257]
When you click on "Insert link" (pages/forms/editors.html or pages/mailbox/compose.html) there is a checkbox out of the box.
![admin_bug](https://cloud.githubusercontent.com/assets/11200226/6380046/13d7d776-bd37-11e4-8473-6683192cf13f.png)

**Comment by almasaeed2010** [comment]
I will get to that asap. 

Thanks!

**Comment by almasaeed2010** [comment]
That's actually not an AdminLTE error. The author of the plugin did not use Bootstrap's conventions when he added the checkbox. His code
```html
<label class='checkbox'>
  <input type='checkbox' />
  Open link in new window
</label>
```

It is supposed to be:
```html
<div class='checkbox'
  <label>
    <input type='checkbox' />
    Open link in new window
  </label>
</div>
```

I will see if I can fix that from the js files.

**Comment by almasaeed2010** [comment]
Ok so I added the correct code to the js file. You need to download the plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min and replace it with the one you have in your project.

Otherwise, wait until the next release is out with some patches and bug fixes which will include this one.
