### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by livertonli12** [almasaeed2010/AdminLTE#261]
Does it have any input with autocomplete or does anybody have suggestions of a beautiful one ?

Regards,
Líverton Oliveira.

**Comment by almasaeed2010** [comment]
AdminLTE doesn't have such a plugin. However, I suggest you try bootstrap select2 plugin since it has many amazing functions.

**Comment by livertonli12** [comment]
Thank you very much @almasaeed2010 you've been doing a very nice job.
