### ISSUE TITLE
[Wrong path] Ion RangeSlider skin

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#262]
The path is no good in Ion RangeSlider css files
for example Nice skin

This is pointing to 
```
background: url(../../img/sprite-skin-nice.png) repeat-x;
```
and this should point to 
```
background: url(../../dist/img/sprite-skin-nice.png) repeat-x;
```
Same thing for flat skin

**Comment by almasaeed2010** [comment]
Thank you for letting me know. I meant to seperate images that belong to plugins from the dist folder and put them with their respective plugin as in the case with iCheck.

Fixed in master.
