### ISSUE TITLE
Printing invoice with tables adds blank pages

### ISSUE THREAD

**Issue by gdespaux** [almasaeed2010/AdminLTE#264]
Hi,

I am having a problem printing from the invoice template. It seems that anytime a table appears on a page, it causes an additional blank page to appear after the current one. The problem is fixed by using the float: none setting on the body, but this also causes all of the bootstrap columns to lose their layout. Does anyone else have a fix for this? Thanks!

**Comment by gdespaux** [comment]
![image](https://cloud.githubusercontent.com/assets/7861929/6423670/2191a53a-beaf-11e4-83f1-587ead5ac6b6.png)

**Comment by almasaeed2010** [comment]
Hello,

Are you using a page from the template or your own customized page? If you are using a customized page please share a code sample for us to test. Thanks!

**Comment by gdespaux** [comment]
Hello,

I'm using the Invoice template page. I have kept the page mostly the same,
I have changed the table to only 3 columns and have several tables instead
of only one. I will share the code as soon as I am back to a computer.
Thank you! :)

**Comment by almasaeed2010** [comment]
We are having issues with printing. I am trying my best to fix them. I will get back to you once I get the main issues sorted out. Thanks for your patience.

**Comment by almasaeed2010** [comment]
This issue has been solved in master. Please wait for the next release to come out and test again. Meanwhile, I will close this issue. If the issue persists in the next release please reopen this issue or open a new one. Thank you!

**Comment by gdespaux** [comment]
Just some info for anyone else that may encounter this:

We were using the previous version (v1) of AdminLTE, and the issue was resolved by using the Print CSS from v2 along with removing the div Wrapper class. Thank you almasaeed for the help!
