### ISSUE TITLE
I used Jquery to add box to the html,but the buttons of remove and collapse can not work

### ISSUE THREAD

**Issue by changjiasheng** [almasaeed2010/AdminLTE#265]
I used Jquery to add box(the html code) into the do dom,but I can't use the remove and collapse button,what should i do to active the click event?

**Comment by almasaeed2010** [comment]
You'll need to call 
```js
$.AdminLTE.boxWidget.activate();
```
After you initiate every new box element.

**Comment by changjiasheng** [comment]
Thanks,i find it in your app.js code
