### ISSUE TITLE
Diferences in plugins and bower

### ISSUE THREAD

**Issue by gperdomor** [almasaeed2010/AdminLTE#266]
Thanks for this amazing template.
I will use it on my project using bower for manage dependencies, but the calendar does not look like the live demo because exist differences in the code of adminLTE bootstrap-datepicker.js file and the file downloaded by bower.

The original file was modified by the adminLTE developers?

**Comment by almasaeed2010** [comment]
Hello,

The datepicker is the only file that has been modified in AdminLTE directly. Other plugins are overridden in the main AdminLTE.css files. So, to achieve the effect you want with the datepicker, please use the css file that's provided in this repo. Thanks!
