### ISSUE TITLE
The sidebar does not show all items.

### ISSUE THREAD

**Issue by markcell** [almasaeed2010/AdminLTE#267]
It seems that the sidebar is not with the height it should. But when I resize the window is already well.

**Comment by almasaeed2010** [comment]
Hi,
Please post a screenshot if possible.

**Comment by zhangyz-hd** [comment]
Here's maybe a same problem.
Open the "/pages/mailbox/compose.html" in Chrome, scorll to the bottom of the page.
Then if I click the "Example" tree on the sidebar and scroll to bottom again, the sidebar's bottom and the page do not display correctly.

![2015-03-02 15 23 10](https://cloud.githubusercontent.com/assets/10389889/6436828/c86d696e-c0f0-11e4-9aae-fcc6256fb24a.png)
![2015-03-02 15 23 37](https://cloud.githubusercontent.com/assets/10389889/6436832/d1693f70-c0f0-11e4-8da9-717c5cb34df3.png)

**Comment by yajra** [comment]
Having the same exact issue. Have fixed it on this [PR](https://github.com/almasaeed2010/AdminLTE/pull/259) with this [commit](https://github.com/yajra/AdminLTE/commit/c9586bf09355531fae286c887a3f4300e22f2b54)

**Comment by markcell** [comment]
My problem is another. And it happens only when using the fixed layout.

![bad](https://markcell.github.com/images/1IjSl2G53Y.png)

But when I resize the window is already well. It looks like a problem with the slimscroll because div.slimScrollDiv has a small height on page load.

![good](https://markcell.github.com/images/kugnH14183.png)

**Comment by markcell** [comment]
Already figured out the problem. Had an earlier version of slimscroll plugin. :smile: 

Thanks.

**Comment by yajra** [comment]
Oh.. well my problem is like in your screenshot where the menu's background is white which is basically the footer. Needed to fix the content wrapper height when menu tree view is expanded. But anyways, have fixed it on my fork. Glad you sort your issues too. :+1:
