### ISSUE TITLE
dist/js/AdminLTE.js not found

### ISSUE THREAD

**Issue by adyballa** [almasaeed2010/AdminLTE#270]
is your bower.json right?

**Comment by almasaeed2010** [comment]
AdminLTE.js is now app.js

**Comment by adyballa** [comment]
sry cannot see it right now. Perhaps it takes some time.

**Comment by almasaeed2010** [comment]
What command are you using?

**Comment by adyballa** [comment]
HI,
Im just Webbrowsing and use sonata-admin-bundle, which uses the master-branch

tried bower install https://github.com/almasaeed2010/AdminLTE.git#master

**Comment by almasaeed2010** [comment]
you should only use usable releases since the master branch changes a lot and contains known errors. Use this command instead
```
bower install admin-lte
```

**Comment by adyballa** [comment]
okay thank you,
But isnt master broken, since there is no AdminLTE.js. What do I miss

**Comment by adyballa** [comment]
This installaltion looks good. But a verification over sonata will not be easy. But I will repond then.

**Comment by almasaeed2010** [comment]
AdminLTE.js was available for v1 only. AdminLTE 2.0 uses app.js instead. 
Unfortunately I am not familiar with sonata. What is it?

**Comment by adyballa** [comment]
It's a symfony2 backend. It's okay, it looks good, but its not stable enough in my mind, the documentation isnt deep enough. Known restriction are not obvious and you cant easily research them. A little too big and coupled. But it's new and the community seems very big and busy, in some way you can very easy establish basic CRUD-Actions which are nicly configurable.
Frontend is too modern in my mind - not my cup of tea anymore - especially if its nearly impossible too handle relations deeper as 2 Level in one screen or even wizards. This is the maingoal in my mind and even if it seems simple you dont have to do it. Simplicity vanished in a mud of files. bla bla bla - sry

**Comment by almasaeed2010** [comment]
Thanks for the information! If there is anything else we can assist you with, please let me know. Otherwise, we'd appreciate it if you close the issue. Closing the issue would let us know that your problem has been resolved.

**Comment by adyballa** [comment]
@almasaeed2010 v1.3.1 uses app.js

**Comment by almasaeed2010** [comment]
You are right! My bad.
