### ISSUE TITLE
Sidebar is shown after close when the window has been resized

### ISSUE THREAD

**Issue by ismailbay** [almasaeed2010/AdminLTE#271]
Hello, 

First of all I want to thank you for your great work.

I couldn't find any related issue. 

If I close the sidebar by clicking on the offcanvas button on a big device, e.g. desktop, and afterwards resize the window to a smaller size, e.g. phone, the sidebar is being shown again. 

I am not sure if this is the desired behavior. Imho, the sidebar should remain closed after an intentional close action and resizing afterwards.

**Comment by almasaeed2010** [comment]
Hello,

This issue is being addressed in this pr #259 

Thank you for the compliment.

**Comment by almasaeed2010** [comment]
Fixed in v2.0.3
