### ISSUE TITLE
Problem with Datatable plugin

### ISSUE THREAD

**Issue by marfab** [almasaeed2010/AdminLTE#272]
I've got some problem with method "Server-side processing" of Datatable plugin:
http://datatables.net/examples/server_side/simple.html

After I understand that problem is the plugin. In fact if I use the original "jquery.dataTables" it's ok.. if not, I'm not able to connect to my mysql db!

Maybe I'm wrong something.. If yes, help me where.. If not, I hope my report is helpful..

Congratulations for this excellent work! Regards!

Fabio

PS. If I use the simple method, DOM-HTML,
http://datatables.net/examples/data_sources/dom.html
..it's all right!! But it's too slow for my huge number of records..

**Comment by almasaeed2010** [comment]
Hello,

Unfortunately I can't help you regarding loading from your database. However, I can recommend that you look over the [Server-side processing](http://www.datatables.net/examples/server_side/) part of the datatables documentation. If there is a problem that is by AdminLTE, please report it and we will be more than happy to assist you. Thanks!
