### ISSUE TITLE
Sidebar fails on Opera mini

### ISSUE THREAD

**Issue by Farhan5** [almasaeed2010/AdminLTE#273]
As-Salamu Alaikum,
Opera has a great reputation as a mobile browser. The mini v7.* doesn't seem to fit with Admin Lte's sidebar, its always collapsed. Toggles, dropdowns..etc js things are not working too.

I hope it would be fixed. Bootstrap 3 supports opera mini, why not Admin Lte? Otherwise this is a great theme. I want to use it if it supports the most commonly used browsers.

P.S. Iconic framework v2 css used in the theme via a cdn. Im having trouble to find out the download link of this css and its resources, because I want to host it in my server (don't know about it). Thanks.

**Comment by almasaeed2010** [comment]
Hello,

I have tested AdminLTE on Opera mini on iOS 8a it is working fine. It is possible that the jQuery library didn't load when you were testing from your device. Please test again and let me know.
Test using this [link](http://almsaeedstudio.com/themes/AdminLTE/index2.html) if possible.

Ion Icons v2 can be found here http://ionicons.com/

Thanks!

**Comment by Farhan5** [comment]
I've tested the same resource before..

> http://almsaeedstudio.com/themes/AdminLTE/index2.html

And after you gave..

I'm using Android opera mini v7.* (which is the latest version, updated a few days ago) having Android OS version 4.4.2 kitkat. Also tested with an older version before, but the problem remains.

Here is a screenshot of it..

**Comment by almasaeed2010** [comment]
I managed to test it on Opera Mini on an Android device. Unfortunately, the browser does not support many features. Including basic css3 like border-radius. Frankly, I am not sure if I am able to provide support to this browser. I have, however, tested it on Opera Browser, which is a different app on Android, and it worked fine. So technically, Opera is supported but Opera mini isn't. I will put a notice that Opera mini is not supported in the readme file. Thank you for informing us and we apologize for the inconvenience.

**Comment by kressly** [comment]
I guess that is why it was not working on the android had tested it on before.
