### ISSUE TITLE
The sidebar background and page footer not fit page height

### ISSUE THREAD

**Issue by zhangyz-hd** [almasaeed2010/AdminLTE#275]
Hello
There is a problem that bothers me for several weeks.
Open the "compose.html" with Chrome Browser, and then click the 'Example' menu at sidebar,
then will see the sidebar background is white and the "footer" not fit the page foot.

![snip20150303_1](https://cloud.githubusercontent.com/assets/10389889/6464496/7fe79a4c-c1f5-11e4-85df-894b25243608.png)

**Comment by almasaeed2010** [comment]
Hi,

This issue is being addressed in #259

**Comment by almasaeed2010** [comment]
Fixed in v2.0.3
