### ISSUE TITLE
bower config

### ISSUE THREAD

**Issue by defyjoy** [almasaeed2010/AdminLTE#277]
Your bower main says dist/js/AdminLTE.js . But actually its app.js . Please rename app.js and app.min.js to AdminLTE.js and AdminLTE.min.js. While we pull the changes from bower install due to this no AdminLTE.js is copied to desired location since it depends on bower.json for AdminLTE bower configuration

**Comment by almasaeed2010** [comment]
Fixed in master.

**Comment by defyjoy** [comment]
The issue is fixed in main branch master . But the changes are not pushed into bower repo . Could you please push the changes to bower repo ?

**Comment by almasaeed2010** [comment]
We don't have a bower repo anymore. The master repo is the only available one.

**Comment by almasaeed2010** [comment]
I see what you mean. I need to create a new tag on Github for bower to pickup the changes. Thanks for informing me.
