### ISSUE TITLE
Unmovable Dashboard Boxes

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#282]
I see that the dashboard boxes in Dashboard V2 are no longer movable via drag and drop while they still are in V1 of the same release, is this intentional or there's something missing? If intentional, is there a way to make them movable again. This is a nice feature that's better to keep.

**Comment by almasaeed2010** [comment]
Hello,
This is intentional. You can add the jQueryUI library to your page and activate the plugin using this code:
```js
//Make the dashboard widgets sortable Using jquery UI
$(".connectedSortable").sortable({
  placeholder: "sort-highlight",
  connectWith: ".connectedSortable",
  handle: ".box-header, .nav-tabs",
  forcePlaceholderSize: true,
  zIndex: 999999
});
$(".connectedSortable .box-header, .connectedSortable .nav-tabs-custom").css("cursor", "move");
```

Of course, don't forget to add the class ```connectedSortable``` to the columns you want to make sortable.

**Comment by YasserHassan** [comment]
Thank you.

**Comment by almasaeed2010** [comment]
No problem.

**Comment by YasserHassan** [comment]
It would be good to have this in the documentation if not already is along with other similar tips like the earlier one about the preparation for the mini sidebar using the "sidebar-menu" class.
