### ISSUE TITLE
How to add label on top of each image of the latest member box

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#284]
Hello
I am trying to add the label to the the latest member box on top of each images so that i can put in a number of messages exchanged between that member and the one connected but it is not displaying well. Basically the result i would like to get is like on this picture that i have created
![1](https://cloud.githubusercontent.com/assets/925132/6562149/78062b02-c68e-11e4-9490-f3d269ce28e1.png)

To do that i added 
``<sup class="label label-danger"> 3 </sup>``
But it rather gave me the following result
![2](https://cloud.githubusercontent.com/assets/925132/6562180/c5c477d6-c68e-11e4-80d2-78c19a3d1d06.png)

As you can see the label is not displayed at the top of the image .
How can i display the label at the top of the image ?

Thanks

**Comment by almasaeed2010** [comment]
I'd suggest adding ```position:relative``` of the image container div. Then position the label the you want it using ```position: absolute``` and the top, left properties.

It should look something like this:
```html
<!-- Container for the img -->
<div class='img-container'>
  <!-- The image. Possibly add class='img-responsive' if you want -->
  <img src='/path/to/img' alt='...' />
  <!-- The label -->
  <span class='label label-danger'>3</span>
</div>
```

Then for the css:
```css
.img-container {
  position: relative;
}
.img-container > .label {
  position: absolute;
  top: 5px;
  right: 10px;
}
```

**Comment by kressly** [comment]
One thing I really like about this community is ..Fast answers. I mean very Fast answers. Thanks man !!  Admilte Rocks... :+1: 
It worked

**Comment by lenamtl** [comment]
When you have several layers you can use z-index property
http://www.w3schools.com/cssref/pr_pos_z-index.asp

**Comment by kressly** [comment]
Wow 😲  thanks a lot
