### ISSUE TITLE
Latest commits have unresolved conflicts

### ISSUE THREAD

**Issue by Verhaeg** [almasaeed2010/AdminLTE#285]
Hi there..just to point that latest commits on index.html have unresolved conflicts:

    <<<<<<< HEAD
        <head>
            <meta charset="UTF-8">
            <title>AdminLTE | Dashboard</title>
            <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
            <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
            
            <link href="//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css" rel="stylesheet" type="text/css" />
            
            <link href="css/morris/morris.css" rel="stylesheet" type="text/css" />
            
            <link href="css/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
            
            <link href="css/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
            
            <link href="css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
            
            <link href="css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />
            
            <link href="css/AdminLTE.css" rel="stylesheet" type="text/css" />
    =======
      <head>
        <meta charset="UTF-8">
        <title>AdminLTE 2 | Dashboard</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        
        <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        
        <link href="plugins/morris/morris.css" rel="stylesheet" type="text/css" />
        
        <link href="plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        
        <link href="plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
        
        <link href="plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        
        <link href="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />
        
        <link href="dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        
        <link href="dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link href="plugins/iCheck/flat/blue.css" rel="stylesheet" type="text/css" />
    >>>>>>> 78ac2fe03170625a482b869055c15348edfe8381

Apart from that, I think that the new version looks awesome! great work!

**Comment by almasaeed2010** [comment]
I am not sure what you mean with "resolved conflicts." Could you please explain?

**Comment by Verhaeg** [comment]
ahh never mind.. my mistake here.. I pulled the newest code and got some cache issues with the conflicts...  ;)
