### ISSUE TITLE
IE Effect Problem

### ISSUE THREAD

**Issue by mndeveci** [almasaeed2010/AdminLTE#286]
Hi,

I like your theme very much but there seems a little problem about it. When using IE 11, every page change creates an effect like pulling left side bar back in the page. In Chrome and Firefox its ok but, IE creates problem.

Do you have any opinion about how to fix it? Thanks a lot.

**Comment by kressly** [comment]
Hi
Please can u give us a print screen of what the effect looks like ?

**Comment by mndeveci** [comment]
This is chrome, it is normal as expected :)
[Chrome](http://i.giphy.com/l41lRNoTqekXVC5EY.gif)

But this is IE 11. Somehow, every page load creates effect like opening left menu.
[IE](http://i.giphy.com/3oEduQzvIweBem3SGQ.gif)

**Comment by almasaeed2010** [comment]
I see what you mean. It could be the custom bezier function we are using for the transition. I will test other functions with IE11 and get back to you as soon as possible. I'll need some time since I have a couple of exams this week. Perhaps I'll have an answer by the weekend. Please keep this issue open until it's resolved.

Thank you!

**Comment by mndeveci** [comment]
Thank you, I will be waiting your response. By the way, if I could find any clue, I will write here.

**Comment by YasserHassan** [comment]
By the way, what is the best way to remove the spring effect when hiding or showing the side bar? Is there a way to disable it using a class in the page?

**Comment by almasaeed2010** [comment]
The best way to do that is by changing the variable ```@tansition-fn``` in the variables.less file to whatever function you want. You can make it ```ease-in-out``` or ```linear```. There are a couple of other options. However, to remove the transition completely would require you to remove the css that produces the transition form the core.less and sidebar.less files.

If you are unfamiliar with less, you will have to do that manually using the main AdminLTE.css file.

**Comment by almasaeed2010** [comment]
Just a note:
I chose this function because it significantly reduces performance issues in some browsers. Predefined functions like ```ease``` creates a slow and interrupted effect when the sidebar contains too many links.

**Comment by YasserHassan** [comment]
Good to see that you've considered this issue. Of course it can be manually edited but I'm thinking is that preservable through upgrades? I suggest providing one or more alternative transitions to change to the same way skin is changed. Not every application will have a big number of links so the developer can select which is more suitable based on the case of the project at hand.

**Comment by almasaeed2010** [comment]
I tired to solve this several times. I can't figure out a solution! Any idea how to solve this problem?
