### ISSUE TITLE
Problem with displaying last Member box

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#287]
Hello
I am displaying the Last member list with label but I am having a strange problem here. When it reaches 7 (i take the information from my database) some of the members go down
![5](https://cloud.githubusercontent.com/assets/925132/6598744/a2759150-c7fd-11e4-8123-8b94dda0f798.png)

Please how to solve this ?

```
          
<li>
            

                    
                    
                    
                    <!-- Container for the img -->
<div class='img-container'>
<?php

$chat_between_generer =  hash('sha512',"Chat Between $id_ojm_peoples AND $id_de_l_autre");

?>

<a  href="messages_lire.php?id_message=<?php echo $id_message; ?>&id_de_l_autre=<?php echo $id_de_l_autre; ?>&chat_between=<?php echo $chat_between_generer;  ?>" title="<?php echo $nom_prenom; ?>">
  <img src="<?php echo $url_avantar_profile; ?>" alt="<?php echo $nom_prenom; ?>" class="img-circle"  height="50"/>
  </a>
  <!-- The label -->
  <?php
  if($nombre_message_lu_id_de_lautre>0)
  {
	?>
    <span class='label label-danger'><?php echo $nombre_message_lu_id_de_lautre; ?></span>
    <?php  
  }
  ?>
  
   
  
 <a class="users-list-name" href="messages_lire.php?id_message=<?php echo $id_message; ?>&id_de_l_autre=<?php echo $id_de_l_autre; ?>&chat_between=<?php echo $chat_between_generer;   ?>" title="<?php echo $nom_prenom; ?>">
 <?php echo $nom_prenom; ?>
 </a>

<span class="users-list-date"><?php echo time_ago($temps_envoye, $langue='en'); ?></span>
                                          
</div>

</li>
    

```

Is there something i am not doing right ?

**Comment by adaniello** [comment]
To debug it, you should inspect html output to see if it's right.
From image i see only a strange effect with image: they aren't "square" in origin (eg. 128x128px) and you are using a fix height.
From code, i see that your code is different from original
```
<li>
<img src="dist/img/user5-128x128.jpg" alt="User Image">
<a class="users-list-name" href="#">Sarah</a>
<span class="users-list-date">14 Jan</span>
</li>
```
because you added a div.img-container
Now i haven't time to try, but hope that this can help you.

**Comment by kressly** [comment]
Yes the images are rounded because i have added the class img-circle to it.

**Comment by andredp** [comment]
I think the problem lies here (I'd have to see your css to be sure...):
<span class="users-list-date"><?php echo time_ago($temps_envoye, $langue='en'); ?></span>

The problem is, when you print the time_ago() it can either have 1 line or more lines of text, messing with the <li> total height. 

You can give your <li>'s a fixed height and let them overflow down.

<li style="height: 100px"> (should prob. put this on your css files)
This should fix it, I guess.

**Comment by almasaeed2010** [comment]
Both of @adaniello and @andredp are right. First, the images must have a square size (n by n). Second, the text returned by the function ```time_ago()``` must not be too long. 

The quick and dirty fix
```css
/* In your css add */
.users-list-date {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.users-list-avatar {
  max-width: 125px;
  max-height: 125px;
}
```

In your php file, chenge this line to remove the height="50" property and add class="users-list-avatar".
```php
<img src="<?php echo $url_avantar_profile; ?>" alt="<?php echo $nom_prenom; ?>" class="img-circle users-list-avatar"/>
```

**Comment by almasaeed2010** [comment]
Just to give a complete answer. The proper fix would be to make sure that all uploaded images have the exact same size, which is easily accomplishable by using a crop image plugin like [this one](http://fengyuanchen.github.io/cropper/) and force a constraint on the user.

**Comment by kressly** [comment]
@adaniello  @andredp  @almasaeed2010 
Thanks to you all. However. When i remove the height and applied those fix it became worse. I reduce the text of my time_ago function, used a function to resize all my images to be displayed at 100 px maximum and then added the class by @almasaeed2010 and this is what i got
![6](https://cloud.githubusercontent.com/assets/925132/6618056/22142ae8-c8b7-11e4-9338-d70059e9096f.png)

I also removed the circle and i got approximately the same result
![7](https://cloud.githubusercontent.com/assets/925132/6618076/553297c0-c8b7-11e4-8e2d-027693193003.png)

**Comment by almasaeed2010** [comment]
Place a height property on the <li> tag then try again

**Comment by kressly** [comment]
@almasaeed2010 On which tag please ? The img ? That's what i did

**Comment by almasaeed2010** [comment]
Sorry was supposed to be the ```<li>```

**Comment by lenamtl** [comment]
Hi, is this fixed or you still need help?

**Comment by kressly** [comment]
@almasaeed2010 I don't understand. You said i should place a height On `<li>` is it ?
@lenamtl for now it seems to be working however i dont understand why unless i put height on the image it does not work with only css
