### ISSUE TITLE
Add a version with sass

### ISSUE THREAD

**Issue by stevenjlho** [almasaeed2010/AdminLTE#289]
I like sass than less. I hope that this project have a version with sass. Can to add this task to your todo list?

**Comment by almasaeed2010** [comment]
Hello,
Unfortunately I am not very familiar with the sass syntax. It would also make it harder for me to maintain the template when it comes to updates. I apologize for the inconvenience.

**Comment by stevenjlho** [comment]
I’m sorry to hear that. Anyway, thanks for your reply.
