### ISSUE TITLE
ionicons is not a dependency

### ISSUE THREAD

**Issue by Faryshta** [almasaeed2010/AdminLTE#290]
they are used a lot on the example pages, yet they are not mentioned in the bower.json file or the composer.json file

**Comment by almasaeed2010** [comment]
Ion icons and font awesome are loaded using CDN links. In future releases they might be added locally. 
Are you experiencing any problems with the icons?

**Comment by ifaniqbal** [comment]
It is confusing for me. I think you should not use ionicons in example pages if not needed. I've removed that from my site and everything is working and faster load time.

**Comment by Faryshta** [comment]
i agree with  @ifaniqbal.

if the example uses ion icons then the bower.json and composer.json file should add them as dependencies.
