### ISSUE TITLE
Button can't be clicked in a dynamic loaded DIV

### ISSUE THREAD

**Issue by myrfy001** [almasaeed2010/AdminLTE#291]
I put Collapsable Boxes in  DIVs ,and dynamic load these DIVs by JQuery's Load function. But the dynamic loaded DIVs can't be collapsed. I found the related javascript wasn't binded to these DIVs.

So, what should I do ? Should I bind these DIV's manually after I Loaded them? Which function should I call?

Thanks~

**Comment by almasaeed2010** [comment]
Hello,

If you are using jQuery.ajax then within the done method call 
```js
$.AdminLTE.boxWidget.activate();
```

Let me know if that works.

**Comment by myrfy001** [comment]
Wow~~ It really works! 
Thanks a lot~~

But I Hope this could be done automatically in the future~

**Comment by kressly** [comment]
@almasaeed2010 please where exactly to place that code ? Is it after the jquery load function ? I  am having the same issue .

**Comment by almasaeed2010** [comment]
```js
$.ajax(
  //Your code here
  success: function(data) {
    //Create the widget
    //...
    $.AdminLTE.boxWidget.activate();
  },
  //The rest of your code...
);
```

**Comment by kressly** [comment]
:+1:
Thank you @almasaeed2010

**Comment by gligoran** [comment]
@almasaeed2010 Thanks!

I was having the same problem with AngularJS views. For anyone having the same issues I solved it with this:

    $rootScope.$on("$viewContentLoaded", activateAdminLteBoxes);
    $rootScope.$on("$includeContentLoaded", activateAdminLteBoxes);
    
    function activateAdminLteBoxes()
    {
        $.AdminLTE.boxWidget.activate();
    }

I have this in a parent controller in relation to the current view's controller. Depending on usage, you might not need both events, but I use a few ```ng-includes``` to make my app more modular, but also have boxes in views that don't have any.

**Comment by CharmingYang0** [comment]
I encountered this issue with AdminLTE v2.4.18.
In Flask, uncertain amount of div will be generated which will be dynamically rendered via ajax success handling `$(div_id).html(data)`; after that as above mentioned, `$.AdminLTE.boxWidget.activate()` invoked.
But unfortunately, error popped up 

> TypeError: $.AdminLTE is undefined

.

Please let me know how to handle it in v2.4.18.
