### ISSUE TITLE
Layout options not displaying well on screen rotation on Windows 8.1

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#292]
Hello
I was re checking the demo at almasaeedstudio today but this time with a Nokia lumia 520 windows 8.1 and i noticed that the layout options do not appear correctly on screen rotation.

Here is a screen shoot 
![wp_ss_20150315_0003 1](https://cloud.githubusercontent.com/assets/925132/6658443/567ff3dc-cb61-11e4-89b5-dbe039b32dce.png)

As you can see when you flip the phone the layout option no more displays, unless you put the phone in a vertical alignement

**Comment by almasaeed2010** [comment]
The demo panel is not intended to be responsive. It is only viewable from larger screens. Thanks!

**Comment by kressly** [comment]
oh ok
