### ISSUE TITLE
Source Sans Pro alternative?

### ISSUE THREAD

**Issue by ivantcholakov** [almasaeed2010/AdminLTE#293]
As far as I know the font Source Sans Pro supports only the Roman letters, Cyrillic letters are not supported. As a result, the browser shows Roman and Cyrillic letters using different fonts, they differ visually in size.

Which letter richer font is close enough?

**Comment by lenamtl** [comment]
There is a pairing tab that may help
http://www.google.com/fonts/specimen/Source+Sans+Pro#pairings

I think Roboto can do the job
http://www.google.com/fonts/specimen/Roboto

**Comment by ivantcholakov** [comment]
I tried Roboto, yes, it is close enough. Also, I tried Open Sans, somehow I liked it more.

**Comment by easyest** [comment]
Source Sans Pro does support Cyrillic symbols. But not the one in google fonts. You can compile the font Yourself from source at https://github.com/adobe-fonts/source-sans-pro or google for already compiled version.

**Comment by ivantcholakov** [comment]
https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.010R-ro%2F1.065R-it
The release note claims that there is Cyrillic support, indeed.
