### ISSUE TITLE
Integrating Toastr notifications

### ISSUE THREAD

**Issue by nicolas-besnard** [almasaeed2010/AdminLTE#295]
Would you be ok to integrate [Toastr Notifications](https://github.com/CodeSeven/toastr) on this dashboard ?

**Comment by almasaeed2010** [comment]
We are not ready to add more plugins to the repository. For the time being, you can integrate the plugins you want locally. 

Thank you for the suggestion. It will be considered in a future release.

**Comment by almasaeed2010** [comment]
To keep you updated. This plugin is going to be added to the premium collection. Thanks!

**Comment by scottscreations** [comment]
sweet, i've been using the gritter one http://boedesign.com/demos/gritter/

any release date on the premium?

**Comment by almasaeed2010** [comment]
@scottscreations I saw gritter before and it is a really good plugin. However Toastr is more Bootstrap oriented and serves the same purpose, so I decided to go with it.

The premium version is in its early stages and I am not sure when I will be able to release. Hopefully soon though. I appreciate your patience.

**Comment by scottscreations** [comment]
@almasaeed2010 I agree, it looks nicer.

**Comment by scverano** [comment]
I think you can also considered Bootstrap Notify. I've found out that the animation are really nice. http://bootstrap-growl.remabledesigns.com/

**Comment by nicolas-besnard** [comment]
This template doesn't need to integrate a "default" notifications system,
as it will just be to add the Javascript file. Just add your favorite one :)

**Comment by almasaeed2010** [comment]
@nicolas-besnard is absolutely right. You can use any of these nice scripts. The one I am going to implement might have special style modifications to be consistent with AdminLTE. I still think Toastr is the best option.

**Comment by laudeco** [comment]
@almasaeed2010 any chance to get toastr in all versions ?

**Comment by nicolas-besnard** [comment]
You can easily integrate it just by adding the script on your pages. It
doesn't need to be included by default
