### ISSUE TITLE
How to add a search drop down to Adminlte

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#296]
First of all i really would like to thank his excellency president @almasaeed2010 of Adminlte for such a wonderful work. However i will "thank" him better when i am done with my project. What makes this community great is not just the awesome design but the fact that u know that the creator of this community and some nice people like @lenamtl will be there to help.

Now please how can i add a dropdown search menu as we see on facebook mobile. I can add the search Icon but how to make it dropdown like on facebook mobile or like on w3schools.com on mobile ?

Pl

**Comment by lenamtl** [comment]
Hi,

You can try to use this one from this Bootstrap template
http://www.bootstrapzero.com/bootstrap-template/facebook

**Comment by almasaeed2010** [comment]
Hello,

Do you mean you want a dropdown search menu in the navbar?

Thanks for the compliments! :+1:

**Comment by kressly** [comment]
@lenamtl  You deseve it. Thanks a lot
However how to add this to AdminLte
@almasaeed2010  You deserve it.

This is what i would like to add to Adminlte. Here is a screenshot of facebook on windows phone when i click the search button there is a dropdown menu that comes with the search field
![wp_ss_20150318_0001](https://cloud.githubusercontent.com/assets/925132/6720037/32c0d03a-cdb7-11e4-8fcb-d995b02c07ec.png)

Is there a way to make my search field drop down onclik like that ?

**Comment by almasaeed2010** [comment]
@kressly this is somewhat difficult to create. I could suggest a few things to get you started but I don't think I can really create something like that in a short period of time.

Here is what I would do. I would add a search icon to the navbar and make it display a dropdown menu. Within the dropdown menu I'd add a search text box and let a div under it (in its own ```<li>```) that displays the results. Overall, this is what should be put in the ```custom-navbar-menu``` section.
```html
<li class="dropdown">
   <!-- the search button -->
   <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
   <ul class="dropdown-menu">
     <li class="pad">
      <!-- the search text input -->
      <input type="text" class="form-control" name="search" id="search-input" />
    </li>
    <li>
      <div id='results'>
        <!-- results should be displayed here -->
      </div>
    </li>
  </ul>
</li>
``` 

The customizations you will have to do:
1- Disable closing the dropdown on click.
2- Listen key down event on the ```search-input``` text box.
3- Display results in the ```#results``` section.
4- Test against different browsers and screen sizes.

Of course, there are options to get a great search UI and more reliable without using the dropdown part. I would suggest a search modal that is fired when you click the search button in the navbar. Another really good example could be found [here](http://pages.revox.io/latest/).

I hope this helps a little.

**Comment by kressly** [comment]
Thanks @almasaeed2010 
But it does the drop down However when i click in the input field again, it disappears.

**Comment by almasaeed2010** [comment]
Hello @kressly 
I mentioned that you will run into this issue in point 1. You will need to use JS to override Bootstrap's close on click feature for that specific menu. Perhaps this might help 
http://stackoverflow.com/questions/11617048/stop-just-one-dropdown-toggle-from-closing-on-click

**Comment by kressly** [comment]
Ok Thanks a lot

**Comment by raj1109** [comment]
Hi almsaeed2010, sorry to extend the discussion on this link after long time.
Kindly help me. I am using adminLTE and I am trying to implement jquery "autocomplete". it is working in a normal aspx page. but when I use adminLTE, it is not working. Here is what I am trying to do.

<script src="Scripts/jquery-1.10.2.js"></script>
<script src="Scripts/jquery-ui.min.js"></script>
<link href="Content/jquery-ui.css" rel="stylesheet" />

    <script type="text/javascript">  
        $(document).ready(function() {  
            SearchText();  
        });  
        function SearchText() {  
            $("#txtItemCode").autocomplete({  
                source: function(request, response) {  
                    $.ajax({  
                        type: "POST",  
                        contentType: "application/json; charset=utf-8",  
                        url: "RetrieveItemCode.aspx/GetCode",  
                        data: "{'itemCode':'" + document.getElementById('txtItemCode').value + "'}",  
                        dataType: "json",  
                        success: function(data) {  
                            response(data.d);  
                        },  
                        error: function(result) {  
                            alert("No Results");  
                        }  
                    });  
                }  
            });  
        }  
    </script> 
<asp:TextBox ID="txtItemCode" runat="server" Width="160px" />  

This is working with in a normal aspx page. but not working when I am trying to use with adminLTE.

**Comment by lenamtl** [comment]
Hi, 

I suggest you to check the browser console (right click inspect) for errors.

Possible solution https://github.com/almasaeed2010/AdminLTE/issues?utf8=%E2%9C%93&q=autocomplete

You can also check the plugin issues forum on Github for autocomplete.

Keep in mind that AdminLte is a template, so  server side code is something we cannot help you with...

Please next time open your own question ;)

**Comment by raj1109** [comment]
Hi lenamtl,
Thanks for the reply.
ok I will check

Actually when I type in textbox, it is not even hitting the webmethod.

And I will open new question next time.
