### ISSUE TITLE
Feature Request: Tabbed pages

### ISSUE THREAD

**Issue by scottscreations** [almasaeed2010/AdminLTE#297]
AdminLTE is completely awesome. I ditched this themeforest theme i bought in favor of this because of the licensing, bootstrap and the nice features. I appreciate all the hard work that's being put into it. I watch the activity on this and its amazing how fast responses are.

The idea is tabbed pages, i know we have the bootstrap tabs, but adding and removing them is something different.

I plan to attempt this to see how it works in my system, might be cool to have a different page type and with links within the page to generate new tabs. My plan is to use them for searches, so my users can generate a search in a tab, and more searches in other new tabs and tab between results.

https://jeykeu.wordpress.com/2013/07/27/dynamically-add-remove-and-re-number-tabs-in-twitter-bootstrap/

Demo:
http://junaidqadir.com/backyard/bootstrap_add_rmove_tabs/

**Comment by almasaeed2010** [comment]
Hi,

That's a cool idea! This raises the question of what effect will that give to the user experience when using it on mobile device? We will need a fallback for small screens to enhance the user experience because I think Bootstrap tabs are not very mobile friendly when you generate so many tabs. Any ideas as to how to approach this?

**Comment by scottscreations** [comment]
Ok i thought about it a little. My system doesnt expect mobile usage, its geared for sys admins with 1920x monitors ;). I did try it on my note 3 phone and it worked fine but that's a note 3...

I wonder if we could make use of the bootstrap mobile classes and somehow turn the tabs into a bootstrap list for mobile users so like a sub nav list on the right side within the container.

[left nav] [container [list]]

I dunno, its a thought.

**Comment by scottscreations** [comment]
I tried this on my note 3 and it seemed to work, there would have to be a limit placed in using js or allow the dev to specify a limit. I mean too many tabs on anything can kill your system. I see sys admins that use chrome with like 20 tabs to 30 open and watch them navigate. Its like a kid on crack trying to find the right tab + its slow.

Maybe something like 5 tabs for mobile, 10-15 for big screens.

**Comment by almasaeed2010** [comment]
That idea is fine but it will conflict with the "right sidebar" that will be available in v2.1.0. Limiting the tabs could also work but that will limit the user which isn't something a developer should do. The best we can do is to enhance the bootstrap tabs to be horizontally scrollable. This could fix the many tabs issue on all devices and won't force the user to a specific limit. I will look for maintained plugins that might give us the ability to do this, so we don't "reinvent the wheel."

**Comment by almasaeed2010** [comment]
Of course, for the scope of this template, the functionality would be limited to adding and removing plugins while making them "pretty" and consistent with the design. This way they can be used for any purpose.

**Comment by scottscreations** [comment]
Yeah i wrote the first one on the right thinking wait that has nothing to do with the tabs......long day.

I like the horizontal idea, that could work but might be hard to make it look good.

**Comment by lenamtl** [comment]
There are some tab script that get transformed in accordion - toggle in small view.
This is the best way to my opinion to see tab info in small view.

This is one example 
https://github.com/jellekralt/Responsive-Tabs

**Comment by almasaeed2010** [comment]
That's also an option. Imagine, though, you are creating a search page with tabs as @scottscreations suggested, I don't think it will be good looking. The tabs-to-accordion idea solves many issues such as a page with static content that contains tabs. A more specific example would be a travel agency website where the user gets to view the features of a hotel room and gets to navigate through the sections of prices, public amenities, private amenities, and disability options. Just a thought.

**Comment by scottscreations** [comment]
@lenamtl that is cool to know i can do that kind of stuff.

I have another idea for this issue:

what if it went something like this, you have a small screen, fill it with tabs and when you run out of space you get a button with [ x ] being the number of tabs not in view. And maybe the X would have the 3 bar icon used for responsive layout menus, to indicate this is there because your screen is too small. so [threebars xnumber].

something like this
|      screen       |
|[tab1][tab2][ x ]|

**Comment by almasaeed2010** [comment]
I like the idea of custom tabs so I am gonna add it to the todo list but I it may take some time before it is ready since I have a few things on the list that has a higher priority. Thanks!

**Comment by NinjaLogs** [comment]
awesome can't wait! :), im currently migrating everything from 1.2 i think i was on to the latest...yay.

**Comment by YasserHassan** [comment]
For this requirement, converting tabs to accordion on small screens is not a good idea because it would take a lot of scrolling to click-open the next tab because of the big content, unless the currently open tab can be collapsed by clicking it again. Not a good approach though. Accordions are more suitable for small content. For large content, you need an always visible navigation.

A better approach is using something like [Tab Drop](http://www.eyecon.ro/bootstrap-tabdrop/). There are the following forks:
- [jschab's fork](https://github.com/jschab/bootstrap-tabdrop) adds an enhancement to display the selected tab name.
- [cloudmonkeypeng's fork](https://github.com/cloudmonkeypeng/bootstrap-tabimprove) from jschab's adds a feature for creating and deleting tabs.

The last fork could be a starting point for answering @scottscreations' requirement.

**Comment by lenamtl** [comment]
I like the tab drop idea, thanks for sharing this.

**Comment by scottscreations** [comment]
Yes, this would be perfect way to handle the excess tabs.
