### ISSUE TITLE
How to restrict tab opens in second row, if more tab opens?

### ISSUE THREAD

**Issue by ganthi** [almasaeed2010/AdminLTE#299]
I've include removable tab in bootstrap. 

In my design, if i open more tabs, it show in the second line.

![untitled1](https://cloud.githubusercontent.com/assets/8499105/6776786/dbea2b7a-d168-11e4-8415-28e0d6dabaac.png)

How can i show all the tabs in same line and to set navigation. Is it possible?

Thanks

**Comment by YasserHassan** [comment]
I think this is achievable using Tab Drop, check this comment https://github.com/almasaeed2010/AdminLTE/issues/297#issuecomment-83499513
Another option is implementing a mechanism for horizontal sliding but in my opinion the Tab Drop approach is better.
