### ISSUE TITLE
Creating a multilevel dropdown menu

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#3]
I had few requests to add multilevel dropdown menu to the sidebar menu. Well, good news! It's already included in the initial release and here is how to do it:

```
<li class="treeview">
    <a href="#">
        <i class="fa fa-folder"></i>  Multilevel Menu
        <i class="fa fa-angle-left pull-right"></i>
    </a>                            

    <ul class="treeview-menu">
        <li class="treeview">
            <a href="#">
                First level
                <i class="fa fa-angle-left pull-right"></i>
            </a>

            <ul class="treeview-menu">
                <li class="treeview">
                    <a href="#">
                        Second level
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>

                    <ul class="treeview-menu">
                        <li>
                            <a href="#">Third level</a>
                        </li>
                    </ul>
                </li><!-- /.third level-->
            </ul>
        </li><!-- /.second level-->
    </ul>
</li>
```

The javascript in the app.js file will automatically render the tree view! Enjoy :+1:

**Comment by gsalgadotoledo** [comment]
Nice!! Thank you very much!!

**Comment by wilmargiraldo** [comment]
How use it in JSF? I can not make it work... Please help. Thank you in advance.

**Comment by Longfld** [comment]
you can use jquery smartmenu 
https://github.com/vadikom/smartmenus, 
it is even devices friendly, here is my implementation under ng2:
http://plnkr.co/edit/wLqLUoBQYgcDwOgSoRfF?p=preview https://github.com/Longfld/DynamicaLoadMultiLevelDropDownMenu

**Comment by fw-it** [comment]
Very nice, but how can I do it if using the top navigation layout?

Thanks in advance

**Comment by pribeirojtm** [comment]
Hi. I have the exact question of @fw-it : how can I do it if using the top navigation layout? 
Can we use tree aswell in conjuction with downdown?
Thanks in advance
