### ISSUE TITLE
Separate implementation from AdminLTE class

### ISSUE THREAD

**Issue by Soullivaneuh** [almasaeed2010/AdminLTE#303]
Actually both AdminLTE class and [implementation](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L117-L123) are on the same file `app.js`.

It could be useful to separate this logic, for example:

 * `admin-lte.js` -> The AdminLTE class.
 * `app.js` -> The file which init and implement this class.

For example, in Ember, we have to manually implement functionality like this:

```coffee
App.ApplicationView = Ember.View.extend
  didInsertElement: ->
    # Admin LTE functionality insert
    o = $.AdminLTE.options

    $.AdminLTE.pushMenu o.sidebarToggleSelector
    $.AdminLTE.boxWidget.activate()
```

So the implementation logic currently base on `app.js` is not used.

Regards.

**Comment by almasaeed2010** [comment]
This seems like an interesting idea. However, this is considered a major change and thus requires a full version jump (from v2 to v3) and it is a bit early for that. I'd like to maintain backwards compatibility throughout the whole v2.x increments. Nonetheless, I will keep this in mind for the future.

Great advice. Thanks!

**Comment by Soullivaneuh** [comment]
You're welcome! ;)

For reducing BC breaks we could get this solution (arbitrary file names):

 * `admin-lte.js` -> The AdminLTE class.
 * `init.js` -> The file which init and implement this class.
 * `app.js` or/and `app.min.js` -> `admin-lte.js` and `init.js`

This solution will not brake `2.x` branch cause of no change on app file.

What do you think about that?

**Comment by Soullivaneuh** [comment]
BTW, I think options should be separated to with a little documentation for how to override it without modify the source code (for bower installation in example).

**Comment by MewesK** [comment]
:+1: I like this idea. Since I'm using a very custom gulpfile to build AdminLTE anyway I would love to merge the init logic with my own and save a couple KiB.

**Comment by Soullivaneuh** [comment]
So @almasaeed2010, what do you think of my second solution?

Could be feasible without any BC break, isn't it?

**Comment by almasaeed2010** [comment]
I implemented a new mechanism to extend or edit the AdminLTE object. The new method allows you to create a global object called AdminLTEOptions that would extend the main settings. The [documentation](https://almsaeedstudio.com/themes/AdminLTE-dev/documentation/index.html#adminlte-options) will cover the how-to in the" javascript options" section. This is hasn't been tested yet. However, if it works, it will allow us to edit and extend the options without affecting backwards compatibility.

**Comment by Soullivaneuh** [comment]
@almasaeed2010 great new feature but this solve not this issue at all.

The problem of this issue is that `app.js` have both options and auto-activation.

In an app like Ember, we have to activate those functionalities manually, it's why I proposed to separate the class with the app.

Can you please reopen this issue?

Thanks.

**Comment by almasaeed2010** [comment]
@Soullivaneuh I can't change the structure of the main files without causing issues with backwards compatibility. It is crucial that we maintain a semantic versioning. The solution I implemented solves half of the problem but that's how far we can go without causing issues to our users. I apologize that I couldn't provide any further help.

**Comment by Soullivaneuh** [comment]
> I can't change the structure of the main files without causing issues with backwards compatibility 

I understand that, but I think my proposition wouldn't do any BC breaks and could be implement on 2.x: https://github.com/almasaeed2010/AdminLTE/issues/303#issuecomment-85481930

> It is crucial that we maintain a semantic versioning.

Yes I completely agree with that. But in anyway this issue must still be opened in order to solve it later, on a new major version for example.

**Comment by almasaeed2010** [comment]
Creating multiple files of app.js, as you suggested in the comment you referred to, would cause trouble when upgrading from 2.0.x to 2.1.x which breaks the value of semantic versioning.

**Comment by Soullivaneuh** [comment]
Not sure to understand.

Actually, users include default `app.js` or `app.min.js` file, right?

With my method, `app[.min].js` is a concatenation of `admin-lte.js` and `init.js`. So it's finaly the same as the actual.

Where is the breaking here?

**Comment by almasaeed2010** [comment]
I may have misunderstood. Are you suggesting that the end user will be able to load only app.js instead of all 3 files? If so, how can you achieve this?

**Comment by Soullivaneuh** [comment]
> Are you suggesting that the end user will be able to load only app.js instead of all 3 files?

Excatly. :+1: 

> If so, how can you achieve this?

I think we could for example, give source code on `admin-lte.js` for the class and `init.js` and auto-packing those on `app[.min].js` with a grunt-task.

We this solution we just have to be aware to compile the `app.js` before pushing a new stable version.

It's a fair transition until bumping to new major version (e.g. 3.x). Then, we could remove the `app.js` logic and tell user to include files separately.

I'm not sure but I think this could be automatized with bower.

I could make you a quick PR to visualize how it will be done.
