### ISSUE TITLE
[Mailbox page] As a user I want to be able to hide folders or label on phone

### ISSUE THREAD

**Issue by laudeco** [almasaeed2010/AdminLTE#305]
Hello @almasaeed2010 ,

It could be useful for a user on a phone to collapse folders and/or labels on the mailbox page.
https://almsaeedstudio.com/themes/AdminLTE/pages/mailbox/mailbox.html

As you want I can implement it and request a PR.

**Comment by almasaeed2010** [comment]
I have a couple of ideas. I'll see if I can implement one.

**Comment by almasaeed2010** [comment]
Added the ability to collapse the box in all mailbox pages.
