### ISSUE TITLE
Add dataTable Responsive label:Suggestion

### ISSUE THREAD

**Issue by Nightbr** [almasaeed2010/AdminLTE#307]
Hi, 
It would be nice if you can add dataTable Responsive : https://datatables.net/extensions/responsive/
I have add it in my project and It's a great render.
![capture d ecran 2015-03-25 a 20 22 01](https://cloud.githubusercontent.com/assets/4228646/6833360/a1982b64-d32c-11e4-90aa-f0e93f06bf00.png)

Also, a little fix for the search input field in mobile view : 
Add in css file this : 

```css
.form-control.input-sm {
    width: 100%;
}
```
It will prevent the field from overflow the block in mobile view.

Thank you for your great work ;)

**Comment by almasaeed2010** [comment]
Will look into it for sure

**Comment by t0n1zz** [comment]
@Nightbr hi, i also want to integrated that feature too but i just can't get it work (tried other extension and working but not this one), can you tell me what should i do to make that work?

**Comment by Nightbr** [comment]
@t0n1zz Hi, i used Bower to include the plugin : 
You need to add this to you bower.json or use the command `bower install`

``` JSON
    "datatables-responsive": "~1.0.4",
    "datatables": "~1.10.5",
```

After link css and js asset to your html page : 

``` HTML
<link href="styles/vendor/AdminLTE/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet" type="text/css" />

<!-- boostrapdatatable -->
<script src="bower_components/datatables/media/js/jquery.dataTables.js"></script>
<script src="scripts/vendor/AdminLTE/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="bower_components/datatables-responsive/js/dataTables.responsive.js"></script>
```

And finally, create a table and attach the behavior with jQuery : 

``` Javascript
$('.dataTable').DataTable({
                        responsive: true,
                        autoWidth: false
                    });
```

``` HTML
 <table class="table table-bordered table-striped dataTable">
<thead>
 <tr>
   <th>...</th>
</tr>
</thead>
<tbody>
        <tr>
               <td>....</td>
        </tr>
</tbody>
</table>
```

That's it!! Enjoy your responsive DataTable!

**Comment by t0n1zz** [comment]
@Nightbr wow thank you... it works!! much more easier to understand then documentation they provided

**Comment by Nightbr** [comment]
@t0n1zz you're welcome ;) you can now close the issue #311 I think.

**Comment by almasaeed2010** [comment]
Added all extensions including responsive to our datatables plugin folder. Thanks!

**Comment by vaishnavkoka** [comment]
@Nightbr 
how did you add "is active": active label of bootstrap in the datatable, can you just let me know?
