### ISSUE TITLE
Multicolumn Autocomplete

### ISSUE THREAD

**Issue by musheerkhalid** [almasaeed2010/AdminLTE#308]
Does it have multicolumn autocomplete (Like Grid) or does anybody have suggestions?

Regards,
Musheer Khalid.

**Comment by kressly** [comment]
Please can you reformulate the question ? Personally i did not understand it well. I have searched for multicolumn autocomplete like Grid and i have found this

http://combogrid.justmybit.com/options/showon.php

If your question is that you want to do an autocomplete on a field, they are plenty script for that. @lenamtl spoke to me about Choosen, bootstrap-tokenfield...

Now if that is not your question, sorry

**Comment by musheerkhalid** [comment]
Thanx.

On Fri, Mar 27, 2015 at 7:42 PM, Max John <notifications@github.com> wrote:

> Please can you reformulate the question ? Personally i did not understand
> it well. I have searched for multicolumn autocomplete like Grid and i have
> found this
>
> http://combogrid.justmybit.com/options/showon.php
>
> If your question is that you want to do an autocomplete on a field, they
> are plenty script for that. @lenamtl <https://github.com/lenamtl> spoke
> to me about Choosen, bootstrap-tokenfield...
>
> Now if that is not your question, sorry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almasaeed2010/AdminLTE/issues/308#issuecomment-86952081>
> .
>



-- 
*Thanks and warm regards,*



*Musheer Khalid*


Z Info Solution (P) Limited
│A-6, First Floor│
│Sector-10, Noida (UP) 201301│Office +91-120-4120123│
│Mobile Delhi +91-9911611270│Mobile Lucknow +91-9161919925│
│E-Mail: mkhalid@zinfosolution.com│Website: www.zinfosolution.com│

**Comment by almasaeed2010** [comment]
I am planning on implementing [Select2](https://github.com/select2/select2). It should allow you to create a custom autocomplete menu. Thanks for the suggestion.

**Comment by musheerkhalid** [comment]
Please see the attached image & link for reference. 

http://www.jeasyui.com/demo/main/index.php?plugin=ComboGrid&theme=default&dir=ltr&pitem=

![combogrid](https://cloud.githubusercontent.com/assets/11671898/6882665/410bd938-d5b3-11e4-9ab1-73b61c58172d.png)

Thanx & Regards
