### ISSUE TITLE
AdminLTE problem with table

### ISSUE THREAD

**Issue by XinYiMan** [almasaeed2010/AdminLTE#309]
Hi, I'm trying the template AdminLTE, I must say it is very well done. My compliments. I have only one problem, I do I need to use some grids crud that when they have too many columns SFOR from the screen and I can not see them. Unfortunately I wont be able to use AdminLTE not only for this reason, so for this I ask your help. At this link you can find the source code modified by the insertion of the grid, you can find over the calendar:

www.lazaruspascal.it/download_personali/AdminLTE-master.zip

I think you need a box entry covering the horizontal scrollbar. But I do not know how!

Thank you

**Comment by almasaeed2010** [comment]
Hello @XinYiMan 
I am not sure I get what you mean. Could you please clarify a bit more? 
Thank you!

**Comment by XinYiMan** [comment]
Download the .zip file link. Then displays the index.html in a browser, scroll to the bottom of the page and you will see a grid with many columns that go to the right, you should see the column1 column10 instead see only until column3 because the columns are too many. How do I see all of them?

**Comment by almasaeed2010** [comment]
You have a few problems in your html markup.

Here is a guide as to how to fit that much data into a box:
```html
<!-- The box -->
<div class="box box-success">
  <div class="box-header">
    <h3 class="box-title">YOUR TITLE HERE</h3>
  </div><!-- /.box-header -->
  <div class="box-body">
    <!-- This is where you should put your content -->
    <!-- Lets add your table here and make it responsive -->
    <div class="table-responsive" style="overflow: auto">
      <table class="table">
        <!-- Get the table content and add them here -->
      </table>
    </div>
  </div><!-- /.box-body -->
</div><!-- /.box -->
```

**Comment by XinYiMan** [comment]
Thank you. You are an angel!

**Comment by almasaeed2010** [comment]
No problem. Did it work?

**Comment by XinYiMan** [comment]
Yessss

**Comment by almasaeed2010** [comment]
:+1:

**Comment by Naveed-anwar123** [comment]
I didn't work for me?
