### ISSUE TITLE
Datatables with horizontal scroll

### ISSUE THREAD

**Issue by t0n1zz** [almasaeed2010/AdminLTE#311]
Hi, 
i using datatables and adding horizontal scroll to my table since there is just to many column, it looks great with sidebar visible, but when i hide the sidebar it look like this,

![screenshot 5](https://cloud.githubusercontent.com/assets/6964548/6885135/206f7192-d63c-11e4-9d34-6b1e3934711a.png)

there is some space between the last column and box that contain the datatable, it just looks like when i enable horizontal scroll and hide the sidebar it only strech until there is no need for horizontal scroll

i don't know is this datatables problem or what, but maybe you can give me some advice?

**Comment by Nightbr** [comment]
@t0n1zz Hi, I am pretty sure it is because you have these tags in your HTML around the table:

``` HTML
<div class="table-responsive">
...
</div>
```

Remove it!

**Comment by t0n1zz** [comment]
no, it's only appear when i add

$(document).ready(function() {
        var table = $('#dataTables-example').dataTable({
                        scrollX : true,
                        scrollCollapse : true
                    });
    });

but if i remove scrollx and scrollcollapse it will strech like what it should be, but i need those horizontal scroll if my columns are to many to fit on box

**Comment by Nightbr** [comment]
okay... so use the plugin DataTable-Responsive ^^" look at issue #307

**Comment by t0n1zz** [comment]
@Nightbr yea i already prepared 2 plan to work this out, first responsive extension (that i asked to you) and another one is this...

but i got an issue when using responsive extension, like what you see on my screenshot, there is button in the very right column, and that use to call modals, but it just not working when this button in responsive position (place where we need to click (+) )

**Comment by Nightbr** [comment]
@t0n1zz do you use the listener `on` of jQuery to attach the event to the button ?
Add to that, I think you have a well-known problems:
Attach event to dynamic DOM content. Look at this: http://stackoverflow.com/questions/15090942/jquery-on-method-not-working-on-dynamic-content

It will resolve your problem and the modal event will be attach to the btn in responsive mode too.

**Comment by t0n1zz** [comment]
i'm using it like this

$('.modal4').on('click',function(){
	$('#modal4show').modal({
		show: true,
	})

	var myvalue = this.name;
	$('#modal4id').attr('value',myvalue);
});

**Comment by Nightbr** [comment]
Can you copy/paste here the html of your table ? 

For the responsiveness of the table, It is linked to the width of the table, so it is link to the sidebar too. Change the size of the sidebar and you will see that the dataTable will hide column.

**Comment by t0n1zz** [comment]
okay here is one of my table (not a big one but all my table have the same class just different in column count)

 <table class="table table-striped table-hover" id="dataTables-example">
                <thead>
                <tr>
                    <th>Urutan</th>
                    <th>Pengumuman </th>
                    <th>Tanggal</th>
                    <th>Hapus</th>
                </tr>
                </thead>
                <tbody>
                @foreach($pengumumans as $pengumuman)
                    <tr>
                        @if(!empty($pengumuman->urutan))
                            <td><a data-toggle="tooltip" data-placement="top"
                                   title="Tekan untuk mengubah urutan pengumuman ini"
                                   href="#" class="modal4" name={{ $pengumuman->id }}
                                        >{{ $pengumuman->urutan }}</a></td>
                        @else
                            <td><a data-toggle="tooltip" data-placement="top"
                                   title="Tekan untuk mengubah urutan pengumuman ini"
                                   href="#" class="modal4" name={{ $pengumuman->id }}
                                        >-</a></td>
                        @endif

                        @if(!empty($pengumuman->name))
                            <td><a data-toggle="tooltip" data-placement="top"
                                   title="Tekan untuk mengubah informasi pengumuman ini"
                                   href="#" class="modal3" name={{ $pengumuman->id }}
                                        >{{ $pengumuman->name }}</a></td>
                        @else
                            <td><a data-toggle="tooltip" data-placement="top"
                                   title="Tekan untuk mengubah informasi pengumuman ini"
                                   href="#" class="modal3" name={{ $pengumuman->id }}
                                        >-</a></td>
                        @endif

                        @if(!empty($pengumuman->created_at ))
                            <?php $date = new Date($pengumuman->created_at); ?>
                            <td><i hidden="true">{{$pengumuman->created_at}}</i> {{  $date->format('d-n-Y') }}</td>
                        @else
                            <td>-</td>
                        @endif

                        @if(!empty($pengumuman->id))
                            <td><button class="btn btn-danger modal2"
                                        name="{{ $pengumuman->id }}"
                                        data-toggle="tooltip" data-placement="top"
                                        title="Tekan untuk menghapus pengumuman ini" >
                                        <i class="fa fa-trash"></i></button></td>
                        @else
                            <td><button class="btn btn-danger modal2"
                                        name="{{ $pengumuman->id }}"
                                        data-toggle="tooltip" data-placement="top"
                                        title="Tekan untuk menghapus pengumuman ini" disabled>
                                        <i class="fa fa-trash"></i></button></td>
                        @endif
                    </tr>
                @endforeach

                </tbody>
            </table>

if that so, then why when i hide the sidebar the datatable not reveal hidden column but only strecth all the current column?
like this?

![screenshot 7](https://cloud.githubusercontent.com/assets/6964548/6914771/56decdae-d7b8-11e4-9a76-679b23ffc757.png)

**Comment by Nightbr** [comment]
For modals:
try this

``` JavaScript
$('#dataTables-example').on('click', '.modal4', function(){
$('#modal4show').modal({
        show: true,
    })

    var myvalue = this.name;
    $('#modal4id').attr('value',myvalue);
});
```

For the dataTable-responsive and the sidebar, you can't view the difference because it works with steps of width. And the sidebar is not large enought to view the difference. I think in the docs of DataTable-responsive, you can configure width-steps.

Look at here : https://datatables.net/extensions/responsive/classes
You will see the width-steps that they called Breakpoints.

**Comment by t0n1zz** [comment]
Oh i already tried it and it works but only for one button, and i have more than 1 button/<a> that execute modals, how to make it all works?

and i don't know if i need to open new issues or not 
but i currently experimenting with datatables and now i trying to adding fixedheader and it works fine when sidebar is visible, but when sidebar hidden there is like double header, the one is header that strecth when sidebar hidden, and the other one is header when sidebar still visible(fixed one)

![screenshot 9](https://cloud.githubusercontent.com/assets/6964548/6934056/fb0a5ccc-d858-11e4-85a7-ff7827018ab1.png)
