### ISSUE TITLE
Calendar not displaying in Master after download

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#312]
Hello
The calendar is not displaying in version 2 after downloading the master. This is what i get 
![1](https://cloud.githubusercontent.com/assets/925132/6886418/7fab9304-d635-11e4-89a4-2e5c39a78b46.png)

**Comment by kressly** [comment]
Does someone has a fix for that ?

**Comment by almasaeed2010** [comment]
make sure this line is correct in calendar.html before loading the calendar script.
```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
```

**Comment by kressly** [comment]
Yes I did that but still i am getting the same result. The calendar is not displaying

**Comment by almasaeed2010** [comment]
I downloaded the script on Github and ran it but couldn't find any issues. Is your version customized?
If not, download a new copy and replace your calendar page then try again.

**Comment by kressly** [comment]
Thanks
