### ISSUE TITLE
Setup a Gitter for the repo [Suggestion]

### ISSUE THREAD

**Issue by Nightbr** [almasaeed2010/AdminLTE#314]
Hi, 
it would be great if you could setup a Gitter Chat room for your repositorie. Look at https://gitter.im/
Thanks a lot.

Regards

**Comment by kressly** [comment]
Wow that's great :+1:  @Nightbr 
I hope Dr @almasaeed2010  will take it into consideration

**Comment by almasaeed2010** [comment]
Hello,

Our community isn't currently big enough to be responsive in such mediums. Perhaps in the future.

We appreciate your contribution and sorry for the inconvenience.
