### ISSUE TITLE
Content-header: header overlaps breadcrumbs

### ISSUE THREAD

**Issue by githubjeka** [almasaeed2010/AdminLTE#317]
![image](https://cloud.githubusercontent.com/assets/874234/6959560/14731238-d923-11e4-9038-0633a681bffe.png)

```html
<section class="content-header">
        <h1>LONG TEXT</h1>
        <Breadcrumbs>
</section>
```

**Comment by almasaeed2010** [comment]
This is because the breadcrumbs are positioned absolute. I didn't imagine anyone going full length with titles. If you need long length titles, then you should add the breadcrumbs within the content instead of the content-header.

**Comment by githubjeka** [comment]
May be use 
```
row 
col-md-8 Header
col-md-4 Breadcrumbs
```

**Comment by almasaeed2010** [comment]
I don't want to change the markup currently so I am gonna address this issue in a future release. Your suggestion works, no doubt. So if anyone encounters this issue with a need of long titles, please use the solution provided above. 

Thanks!

**Comment by githubjeka** [comment]
Ok, Thanks.
