### ISSUE TITLE
How to display the timeline body alone ?

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#318]
Hello
Please how to display the timeline alone instead of displaying the timeline and the icons.
Instead of this 
![01](https://cloud.githubusercontent.com/assets/925132/6974481/042f4910-d98b-11e4-9f5a-59dc99ec848b.png)

I would like to display this only without the things on the left on the previous image
![1](https://cloud.githubusercontent.com/assets/925132/6974494/2478b29c-d98b-11e4-8e77-c17a2f52994d.png)

Please how to get that done ?

**Comment by kressly** [comment]
Can someone help me with this ?

**Comment by adaniello** [comment]
Why not use simply a panel?

**Comment by almasaeed2010** [comment]
I agree with @adaniello. You should use a regular ```.box``` for that effect. What is it that you need replicated exactly? I might be able to help if you let me know what part do you want to replicate.

Try this:
```html
<div class='box box-solid'>
  <div class='box-header with-border'>
    <h3 class='box-title'>Title</h3>
  </div> 
  <div class='box-body'>
    Content
  </div>
</div>
```

**Comment by kressly** [comment]
Woo hoo it is working :+1: 
Thanks @adaniello  @almasaeed2010
