### ISSUE TITLE
Button with .pull-right outside of .box-body

### ISSUE THREAD

**Issue by dmaksimov** [almasaeed2010/AdminLTE#319]
When having a button with a class of .pull-right as the last element in a box-body, the button shows up outside of the box element. 

![screen shot 2015-04-03 at 12 25 51 am](https://cloud.githubusercontent.com/assets/497369/6978413/0c9000ba-d998-11e4-92a8-f15217dc327b.png)

Might be good to have "clear: both" after the .box-body like Bootstrap's .panel-body.

**Comment by almasaeed2010** [comment]
Since it is not always the case that you need a floating object within the box, you should add the class ```clearfix`` to the body. I will fix this in 2.1.0. Thank you for letting me know!

**Comment by almasaeed2010** [comment]
Fixed in v2.1.0
