### ISSUE TITLE
Embed boxes collapse

### ISSUE THREAD

**Issue by Ryxeuf** [almasaeed2010/AdminLTE#321]
When you have embed boxes that you can collapse, if you collapse a child, then collapse its parent, then expand the parent, th child is expanded too but with the fa-plus icon instead of fa-minus.

Expanding children could be an error. 
Instead of using .find() on line 442, using .children() fix that issue.

**Comment by almasaeed2010** [comment]
Could you please post the html for the embedded boxes. I will work on it soon. Thanks!

**Comment by Ryxeuf** [comment]
<code>
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">
                Scene 1
        </h3>
        <div class="box-tools pull-right">
            <button data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-minus"></i></button>
        </div>
    </div>
    <div class="box-body" style="display: block;">
        
    <div class="box box-success collapsed-box">
    <div class="box-header with-border">
        <h3 class="box-title">
                Plan 1
        </h3>
        <div class="box-tools pull-right">
            <button data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div class="box-body" style="display: none;">
            C'EST QUAND MEME plapla
    </div>
</div>
    <div class="box box-success collapsed-box">
    <div class="box-header with-border">
        <h3 class="box-title">
                Plan 2
        </h3>
        <div class="box-tools pull-right">
            <button data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-plus"></i></button>
        </div>
    </div>
    <div class="box-body" style="display: none;">
            C'EST QUAND MEME plapla
    </div>
</div>

    </div>
</div>
</code>

**Comment by Ryxeuf** [comment]
Don't know if it works for you to read the html

**Comment by almasaeed2010** [comment]
You have to put your code within three copies this symbol ``` ` ```. Review this link please:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by almasaeed2010** [comment]
I edited it for now to display the code.

**Comment by almasaeed2010** [comment]
Fixed in v2.1.0a
