### ISSUE TITLE
A suggestion, Latest Members widget: Make user photos clickable too, only the name is now.

### ISSUE THREAD

**Issue by ivantcholakov** [almasaeed2010/AdminLTE#323]
https://github.com/almasaeed2010/AdminLTE/blob/v2.0.5/index2.html#L876
It would be good the user photos to have the same links as the correspondent links below them without loosing styling.

**Comment by almasaeed2010** [comment]
Added in v2.1.0
Thanks for the suggestion. Changes will be committed and push to the repo shortly.

**Comment by ivantcholakov** [comment]
I tried it, thank you.
