### ISSUE TITLE
Problem with editablegrid 2 and AdminLTE

### ISSUE THREAD

**Issue by XinYiMan** [almasaeed2010/AdminLTE#324]
Hello, I have the following problem. I have a grid that does not make me see all the columns that should. A similar error I had already come across and almasaeed I had helped solve. But with the solution you gave me I do not work in this case. How so? In the attached file you can find an image of the grid should be seeing many more columns, for accuracy should be seeing these columns here:

ID
NOME
ABILITATO
COGNOME_UTENTE
LINGUA
LIVELLO
PATH_DB
IMG
action

I do not see the action column. And theoretically there were other columns not me see. Annex are also the source of the page. Explain to me where am I wrong? thanks a lot

Attachment link: www.lazaruspascal.it/download_personali/Allegato.zip

**Comment by almasaeed2010** [comment]
Hi,
This issue should be reported to the plugin's maintainer since it is not an AdminLTE issue. Thank you.
