### ISSUE TITLE
Is there a way to add a comment Box ?

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#326]
Hello
Is there a way of making a panel a comment box like facebook or at least a little beat different from the normal panel

For example 
![000 - 1 - tracking](https://cloud.githubusercontent.com/assets/925132/7012168/a131107a-dc9e-11e4-90a2-9cf2562e8382.png)

Is there a way for me to add a comment box to this ?

Thanks for helping

**Comment by almasaeed2010** [comment]
Hi,
AdminLTE doesn't provide a comments system but you can use [Bootstrap's media objects](http://getbootstrap.com/components/#media). I suggest adding them in a box footer.

**Comment by kressly** [comment]
Thanks

**Comment by MildaGeorge** [comment]
Admin Lte 3 treeview plug in activate throgh jquery like
$('ul').Treeview(options) not working
please suggest how to work with Treeview of side bar navigation work dynamically

**Comment by danny007in** [comment]
> 
> 
> Admin Lte 3 treeview plug in activate throgh jquery like
> $('ul').Treeview(options) not working
> please suggest how to work with Treeview of side bar navigation work dynamically

@MildaGeorge Please do not reply here because it not regarding this issue,
so make an new issue 😄
