### ISSUE TITLE
responsive test

### ISSUE THREAD

**Issue by merdj** [almasaeed2010/AdminLTE#327]
hello,

First off, thank you for your great admin program, nice one.
I am playing it right now and I found an issue which I would like you to check it.

I am testing it using responsivetest.net website, the site is self-explanatory.

http://responsivetest.net/#u=https://almsaeedstudio.com/preview|1024|768|1

when you try to rotate from 1024x768, it will become 768x1024 and clicking the off-canvas button it will not work. it is not clickable.

kindly check this issue please. thanks

**Comment by almasaeed2010** [comment]
Hello,
I tested it on the link you provided. I haven't found any issues. I think the text that the site puts on top of the template is what makes it unclickable. Try this [link instead](http://responsivetest.net/#u=https://almsaeedstudio.com/themes/AdminLTE/index2.html|1024|768|1).

**Comment by merdj** [comment]
Hi Abdullah,I tried the link you provided but it did work.going for the size of 1024x768 will play nicely,but when you rotate it,it will not work. the off-canvas button is not working.
I am using responsivetest.com as my testing for responsiveness of my app and it helps me a lot.
kindly look into it again please.
thank you so much. honestly, your work is great!

**Comment by almasaeed2010** [comment]
I tested with multiple responsive test sites but I haven't encountered the error. I also tested it with chrome development tools and got the same result. The website you provided creates an overlay over the template so it makes all links unclickable.

**Comment by merdj** [comment]
hello,
If that would be the case I will bypass this test using responsivetest.com. do you suggest any alternative?
I will close the ticket tomorrow.
thank you so much

**Comment by almasaeed2010** [comment]
[Responsinator](https://www.responsinator.com/) is a popular choice.

**Comment by almasaeed2010** [comment]
It would be better if you test this url instead of preview page almsaeedstudio.com/themes/AdminLTE/index2.html

**Comment by merdj** [comment]
hello again,
i tested with the link you provided responsinator,unfortunately it didnt work as expected.
goingto768x1024 remains the issue.

**Comment by almasaeed2010** [comment]
Which device did you choose?
Please list the the information about your browser. It might be unresponsive in a specific browser.

**Comment by merdj** [comment]
hello,
iPad portrait · width: 768px

i am testing it both using google and firefox. both is giving the same result.

**Comment by almasaeed2010** [comment]
I have an iPad at home. I'll test it on the actual device and get back to you.

**Comment by merdj** [comment]
ok than, consider it an issue at this moment,while solution is still pending
best regards,
need to sleep too

**Comment by almasaeed2010** [comment]
Tested on iPad 2, iPad mini, iPhone 5 and iPhone 6 in portrait and landscape modes, the error did not occur. I appreciate your concern but I couldn't replicate the error.
