### ISSUE TITLE
Dynamically adding options to sidebar

### ISSUE THREAD

**Issue by gremerritt** [almasaeed2010/AdminLTE#328]
Hi - first off I'm fairly new to both JS and jQuery so if this is something obvious, I apologize!

I'm trying to dynamically add items to the sidebar. My default menu is something like:
```html
<!-- Sidebar Menu -->
<ul class="sidebar-menu">
  <li id="trip1" class="treeview">
    <a href="#"><span>First Trip</span> <i class="fa fa-angle-left pull-right"></i></a>
    <ul class="treeview-menu">
      <li><a href="#">Details</a></li>
      <li><a href="#">Map</a></li>
    </ul>
  </li>
            
  <li class="addtotree"><a href="#"><span>+ Add Another Trip</span></a></li>
</ul><!-- /.sidebar-menu -->
```

Then I added the following to the app.js:
```javascript
$('.addtotree').click(function() {
  var $newTrip = $('<li class="treeview"></li>');
  var $tripDetails = $('<a href="#"><span>New Trip</span><i class="fa fa-angle-left pull-right"></i></a>');
  $newTrip.append($tripDetails);
	
  var $newTripDropdown = $('<ul class="treeview-menu"></ul>');
  var $details = $('<li><a href="#">Details</a></li>');
  var $map = $('<li><a href="#">Map</a></li>');
	
  $newTripDropdown.append($details);
  $newTripDropdown.append($map);
  $newTrip.append($newTripDropdown);
	
  $('ul[class="sidebar-menu"]').insertAt(-2, $newTrip);
	
  $.AdminLTE.tree('.sidebar');
})

jQuery.fn.insertAt = function(index, element) {
  var lastIndex = this.children().size()
  if (index < 0) {
    index = Math.max(0, lastIndex + 1 + index)
  }
  this.append(element)
  if (index < lastIndex) {
    this.children().eq(index).before(this.children().last())
  }
  return this;
}
```

This *almost* works... the newly created menu item ("New Trip") functions as I'd expect, (click it and it expands, click it again and it collapses.) However, the original menu item ("First Trip") doesn't. When I click it, it opens but then immediately closes again. I'm assuming this is happening because of my call to `$.AdminLTE.tree('.sidebar')` - I thought this was needed in order to enable to menu to expand, but clearly it has undesired consequences.

![In action...](http://g.recordit.co/3n4ExXmTFo.gif)

Any help would be appreciated - if there's an easier way of doing this I'm open to suggestions!

**Comment by almasaeed2010** [comment]
Hello,
You are right. This is an issue when you reactivate the tree object. I will provide a fix with v2.1.0. Thank you for reporting this.

**Comment by almasaeed2010** [comment]
I have fixed and pushed this to master. When AdminLTE 2.1.0 is released, your method will work. You will no longer need to recall ```$.AdminLTE.tree(".sidebar")```. Thanks and again.

**Comment by gremerritt** [comment]
great, thanks for the quick response, and also for all the development that's gone into this!

**Comment by mrkumarawanish** [comment]
Hi,

 * @Author  Almsaeed Studio
 * @Support <http://www.almsaeedstudio.com>
 * @Email   <support@almsaeedstudio.com>
 * @version 2.1.2

After adding the menu dynamically,  am getting the same problem for above version.  After calling the method $.AdminLTE.tree(".sidebar"), new created menu is working fine, however the original menu doesn't.

Details:
<li class="treeview hide"><a href="#"> <img src="${pageContext.request.contextPath}/component/app/img/menu_icon/sd.gif" /> <span >Pivot</span>
			</a>
				<ul class="treeview-menu" id="pivotSubMenuItemList" style="width: auto;">
					//dyanmically adding menu to pivotSubMenuItemList
				</ul></li>

**Comment by adityasoni1234** [comment]
Hi 
I admire you work very much .Can you please guide me with a method through which I can integrate a theme other than Admin LTE 2 with Cakephp3 because sometimes there is a need of some other theme than a theme with admin panel
Therefor I ask yo for helping me to integrate a certain random so that it could also work when I use bake functionality of cakephp3

Any help would be appreciated
