### ISSUE TITLE
Date Range Picker Not Working When Loaded Through Ajax

### ISSUE THREAD

**Issue by ronakjoshi90** [almasaeed2010/AdminLTE#330]
Hi Team,

Im trying to load the date range picker through ajax request, but sadly the same is not working, it works only when it is rendered on page load.

please help

**Comment by funyx** [comment]
you have to reinit the plugin:


//option defaults
var options = options || {};
        options.startDate = moment().startOf('day');
        options.endDate = moment().startOf('day');
        options.minDate = false;
        options.maxDate = false;
        options.dateLimit = false;

        options.showDropdowns = false;
        options.showWeekNumbers = false;
        options.timePicker = false;
        options.timePickerIncrement = 30;
        options.timePicker12Hour = true;
        options.ranges = {};
        options.opens = 'right';

        options.buttonClasses = ['btn', 'btn-small'];
        options.applyClass = 'btn-success';
        options.cancelClass = 'btn-default';

        options.format = 'MM/DD/YYYY';
        options.separator = ' - ';

        options.locale = {
            applyLabel: 'Apply',
            cancelLabel: 'Cancel',
            fromLabel: 'From',
            toLabel: 'To',
            weekLabel: 'W',
            customRangeLabel: 'Custom Range',
            daysOfWeek: moment()._lang._weekdaysMin.slice(),
            monthNames: moment()._lang._monthsShort.slice(),
            firstDay: 0
        };

var DateRangePicker = function (element, options, cb)

**Comment by ronakjoshi90** [comment]
hi,

i tried to initialize it on click of a button but now what is happening is that it doesnt open when we click for the first time after loading through ajax, on all subsequent click it works fine.

    $( '#abc' ).on( 'click', '.dateRangePicker', function (event) {
}

now is there any other way out ?

**Comment by funyx** [comment]
$.ajax({
url:'someurl',
data:'somedata',
success:function(response){
  //somecode
  //reinit the dateRangePicker
}
})

**Comment by ahmedfarag2010** [comment]
I have the same issue .. it this the best solution?
