### ISSUE TITLE
DateRangePicker and moment v 2.1.0

### ISSUE THREAD

**Issue by ThatCheck** [almasaeed2010/AdminLTE#331]
There is a big problem with the version of moment.js in daterangepicker plugin. We need to update it at least at 2.9 for the .locale() function by example because its resulting of some conflict if you use bootstrap daterange picker and moment.js in the same page. 

Or maybe use moment.js as a complete library in the theme.

**Comment by almasaeed2010** [comment]
moment.js is only used when the daterangepicker plugin is used so I don't think it would be beneficial to use it all over the template. However, I will update the version we are using to solve this issue. Thank you for reporting this. I will report back here once the updates have been made.

**Comment by almasaeed2010** [comment]
Updated daterangepicker plugin. Changes are now available in master.

**Comment by ThatCheck** [comment]
Thanks :+1: !
