### ISSUE TITLE
Fixed menu with boxed layout possible?

### ISSUE THREAD

**Issue by raistlinthewiz** [almasaeed2010/AdminLTE#333]
I want to able to use a fixed main menu with the boxed layout.

Is this even possible?

**Comment by almasaeed2010** [comment]
Unfortunately, you can't have fixed and boxed layouts mixed together. This is because when the sidebar is positioned as fixed, it tends not to respond to its container's relative position, which is the ```.wrapper``` in this case. I apologize for the inconvenience.

**Comment by raistlinthewiz** [comment]
Okay, too bad to hear as the navigation section really uses lots of default space :/
