### ISSUE TITLE
Publish npm version?

### ISSUE THREAD

**Issue by gabel** [almasaeed2010/AdminLTE#335]
Beside bower, composer a.s.o I'd like to see a npm version available. Could you publish it to npmjs?

It will take only those 2 steps just to make it available.

* [x] Adjust package.json (invalid name, ...)
* [x] ```npm publish```

**Comment by almasaeed2010** [comment]
I will look into this. Thanks for the suggestion.

**Comment by gabel** [comment]
It's quite easy and helps people working via npm only... ;)

**Comment by almasaeed2010** [comment]
I agree. I will do this soon.

**Comment by almasaeed2010** [comment]
Done.
