### ISSUE TITLE
why fixed and sidebar-mini can't used together

### ISSUE THREAD

**Issue by pakey** [almasaeed2010/AdminLTE#336]
when i used together,and sidebar change mini status，hover effect  can't trigger

**Comment by almasaeed2010** [comment]
The fixed layout uses ```overflow: hidden``` which prevents the sidebar mini from showing the links on hover. However, disable the use of SlimScroll and it should work.

**Comment by gabel** [comment]
The problem is, if I use the app.js via require directly from the admin lte repo the configuration is already loaded and admin lte is initialized. But I don't want to create a copy of app.js just to change a configuration parameter.

A build version of the JS parts would be awesome.

**Comment by almasaeed2010** [comment]
@gabel this issue is being addressed. I am trying to add a mechanism that will allow you to configure AdminLTE before loading the app.js

**Comment by gabel** [comment]
:+1:

**Comment by 93ramadan** [comment]
I found it! 

By removing the condition or commenting out the function in the below code, you can override the Expand on Hover feature when using Fixed and Sidebar Mini layouts together:

`//Enable expand on hover for sidebar mini`
`      if ($.AdminLTE.options.sidebarExpandOnHover`
`// Remove this condition`
`          || ($('body').hasClass('fixed')`
`          && $('body').hasClass('sidebar-mini'))) {`
`        this.expandOnHover(); //  Or comment this`
`      }`

This code begins at **Line 345** in **dist/js/app.js**

But the problem becomes, when hovering, the normal functionality of the Sidebar Mini does not trigger. *Challenge Accepted*

Thanks @almasaeed2010 for this amazing theme! Always grateful.

**Comment by niladam** [comment]
I'd love this too!

**Comment by heramerom** [comment]
Is this still not support?

**Comment by hdias2310** [comment]
Have you tried to use @93ramadan 's solution? It works very well for me.

**Comment by laedanthehuman** [comment]
Ater 1 or 2 hours reading the code and thinking about the problem that @93ramadan said about 
```
But the problem becomes, when hovering, the normal functionality of the Sidebar Mini does not trigger. Challenge Accepted
``` and @almasaeed2010  said that ```The fixed layout uses overflow: hidden which prevents the sidebar mini from showing the links on hover. However, disable the use of SlimScroll and it should work.```  i change the fixsidebar method, on this part

```js
 if (!$("body").hasClass("fixed")) {
        if (typeof $.fn.slimScroll != 'undefined') {
          $(".sidebar").slimScroll({destroy: true}).height("auto");
        }
        return;
      } else if (typeof $.fn.slimScroll == 'undefined' && window.console) {
        window.console.error("Error: the fixed layout requires the slimscroll plugin!");
      }
```
and removing the expand and collapse calls on expandOnHover method. I've got to sidebar-mini effect trigger the submenus

**Comment by zachpainter77** [comment]
I have a different approach... what I do is set the fixed class after the PushMenu has been initialized... I am allowing my users to store their personal settings via cookies and localStorage and then when the app loads restore their personal settings. (i.e. collapsed sidebar, fixed layout, expand on hover, etc... ) I load those settings from the localStorage. The skins I load from cookies. I am using .net mvc to build my pages. To remove the flicker of the default skin to preferred skin I read the user's cookie and then set the appropriate class with an inline razor script. however, if they have a fixed layout, I just wait until the push menu is initialized and then add the class "fixed" to the body tag manually. The result is sidebar mini with a fixed header and collapsed menu. This works, you just have to get around the race situation by calling the addClass funciton within a setTimeout. 

![image](https://user-images.githubusercontent.com/9939026/43614360-10971190-9668-11e8-9e51-f8defe0c86b6.png)

This shows the page scrolling with a fixed header and sidebar-mini working as expected.

I read the layout from local storage... Then check the check box in the control sidebar.
``` 
if (layout === 'fixed') {
        localStorage.setItem('Layout ', 'fixed');
        $('input[data-layout="fixed"]').iCheck('check');
}
```
And then have a handler for when the iCheck check box is checked that fires.. 
```
 $('input[data-layout="fixed"]').on('ifChecked', function () {
        $('input[data-layout="layout-boxed"]').iCheck('uncheck');
        localStorage.setItem('Layout', 'fixed');
        $.cookie("Layout", "fixed", { path: "/" });
        setTimeout(function () { $('body').addClass('fixed'); }, 1000); //notice setTimeout call 1 second is safe 
    });
```
This is a hacky solution but it is working for me...  ¯\_(ツ)_/¯

**Comment by zachpainter77** [comment]
I found an even better solution...

comment out the whole function body of the function "fixSidebar".

```
 Layout.prototype.fixSidebar = function () {
        // Make sure the body tag has the .fixed class
        //if (!$('body').hasClass(ClassName.fixed)) {
        //    if (typeof $.fn.slimScroll !== 'undefined') {
        //        $(Selector.sidebar).slimScroll({ destroy: true }).height('auto');
        //    }
        //    return;
        //}

        //// Enable slimscroll for fixed layout
        //if (this.options.slimscroll) {
        //    if (typeof $.fn.slimScroll !== 'undefined') {
        //        // Destroy if it exists
        //        // $(Selector.sidebar).slimScroll({ destroy: true }).height('auto')

        //        // Add slimscroll
        //        $(Selector.sidebar).slimScroll({
        //            height: ($(window).height() - $(Selector.mainHeader).height()) + 'px'
        //        });
        //    }
        //}
    };
```
Everything seems to work fine... this removes the need for any setTimeout calls... and seems like the simplest solution.  Seems like this slimScroll is the offending plugin screwing everything up here..

**Comment by BenasPaulikas** [comment]
``` if (this.options.expandOnHover
            //|| ($('body').is(Selector.mini + Selector.layoutFixed))
        ) {```

Why instead of un-commenting do && instead of ||

and developers will be able to choose what they want themselves without editing app.js ?
