### ISSUE TITLE
Problem with hover dropdown menu on AdminLte

### ISSUE THREAD

**Issue by marcus6431** [almasaeed2010/AdminLTE#339]
Hi, i'm currently using your AdminLte template which is a good template for a beginner like me. But i currently having an issue with the hover dropdown menu when i apply the fixed layout.

Here are the screenshot on the sidebar before i applied the fixed layout:
![1](https://cloud.githubusercontent.com/assets/11958254/7155133/0cfc4590-e311-11e4-977a-e140d7369889.png)

Here are the screenshot on the sidebar after i applied the fixed layout where the hover menu is been overlapped by the contain or something:

![2](https://cloud.githubusercontent.com/assets/11958254/7155140/1e9e06bc-e311-11e4-8f0b-e35b637f0eb9.png)

I had try to set z-index on every place that i can set, but still wont work. My side dropdown menu still hide behind the contain after i fixed the layout. May i know what is the problem cause that?

**Comment by almasaeed2010** [comment]
This looks like an invalid markup of you sidebar menu. Please post your code here.

Also, please keep in mind that AdminLTE 2.1.0 is not yet ready for production and many things might change which would make upgrading from alpha to a production ready release more difficult on you. I encourage you to always use the latest stable release which can be found in the [releases section](https://github.com/almasaeed2010/AdminLTE/releases).

**Comment by marcus6431** [comment]
Here are the css style code that i put on AdminLTE.css there in order to let my hover dropdown menu work.


/*3rd level sidebar menu */
ul{
    list-style: none;
}
.dropdown-menu{
    display: none;
}
.dropdown:hover{
    background-color: #00CCFF;
}
.dropdown:hover .dropdown-menu {
    display: block;
	left:217px;
	top:-2px;
}

Here are the html code for my dropdown menu:

 <aside class="left-side sidebar-offcanvas">
                
                <section class="sidebar">
                    
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="img/avatar3.png" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">

							<p>Hello, $login_session</p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
							<button onClick="location.href='logout.php'"> Log Out</button>
                        </div>
                    </div>
					<br/>
                    
                    
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="index.php">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i> 
								<span>Independent Upload</span>
								<i class="fa fa-angle-left pull-right"></i>
                            </a>
							<ul class="treeview-menu">
                                <li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Pahang</span>
									</a>
										<ul class="treeview-menu">
											<li class="dropdown"><a href="#" data-toggle="collapse" data-target="#sub1"><i class="fa fa-angle-double-right"></i> Kuantan</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
													<li><a href="chooseOption.php?kiosk=35&kedai=Kuantan&state=Pahang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.35</a></li>
												</ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> UTC Kuantan</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=36&kedai=UTC Kuantan&state=Pahang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.36</a></li>
											  </ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Temerloh</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=37&kedai=Temerloh&state=Pahang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.37</a></li>
											  </ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Bentong</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=6&kedai=Bentong&state=Pahang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.6</a></li>
											  </ul>
											</li>
											<hr/>
										</ul>
								</li>
							
								  <li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Perak</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#" data-toogle="collapse" data-target="#sub1"><i class="fa fa-angle-double-right"></i> Ipoh</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
													<li><a href="chooseOption.php?kiosk=38&kedai=Ipoh&state=Perak" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.38</a></li>
												</ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> UTC Ipoh</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=39&kedai=UTC Ipoh&state=Perak" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.39</a></li>
											  </ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Taiping</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=40&kedai=Taiping&state=Perak" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.40</a></li>
											  </ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Teluk Intan</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=41&kedai=Teluk Intan&state=Perak" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.41</a></li>
											  </ul>
											</li>
											<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Sri Manjung</a>
												<ul class="nav dropdown-menu" style="width:100px;height:30px">
												  <li><a href="chooseOption.php?kiosk=42&kedai=Sri Manjung&state=Perak" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.42</a></li>
											  </ul>
											</li>
										<hr/>
									</ul>
								</li>
								
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Perlis</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Kangar</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=52&kedai=Kangar&state=Perlis" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.52</a></li>
										  </ul>
										</li>	
										<hr/>
									</ul>
								</li>
								
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Putrajaya</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Putrajaya</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=24&kedai=Putrajaya&state=Putrajaya" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.24</a></li>
											</ul>
										</li>
										<hr/>							
									</ul>
								</li>
								
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Pulau Pinang</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Seberang Jaya</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=47&kedai=Seberang Jaya&state=Pulau Pinang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.47</a></li>
											</ul>
											</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Pulau Pinang</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=48&kedai=Pulau Pinang&state=Pulau Pinang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.48</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Nibong Tebal</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=49&kedai=Nibong Tebal&state=Pulau Pinang" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.49</a></li>
											</ul>
										</li>
										<hr/>
									</ul>
								</li>
								
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Negeri Sembilan</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Seremban</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=53&kedai=Seremban&state=Negeri Sembilan" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.53</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Nilai</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=54&kedai=Nilai&state=Negeri Sembilan" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.54</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Kuala Pilah</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=65&kedai=Kuala Pilah&state=Negeri Sembilan" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.65</a></li>
											</ul>
										</li>
										<hr/>
										
									</ul>
								</li>
								 
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Melaka</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Bandar Melaka</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=50&kedai=Bandar Melaka&state=Melaka" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.50</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> UTC Melaka</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=51&kedai=UTC Melaka&state=Melaka" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.51</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> TNB Jasin</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=25&kedai=TNB Jasin&state=Melaka" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.25</a></li>
											</ul>
										</li>
										<hr/>
										
									</ul>
								</li>
								 
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Kedah</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Alor Setar</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=43&kedai=Alor Setar&state=Kedah" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.43</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> UTC Alor Setar</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=44&kedai=UTC Alor Setar&state=Kedah" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.44</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Sungai Petani</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=45&kedai=Sungai Petani&state=Kedah" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.45</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Kulim</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=46&kedai=Kulim&state=Kedah" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.46</a></li>
											</ul>
										</li>
										<hr/>
									</ul>
								</li>
								  
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Kuala Lumpur</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Kepong</a>
											<ul class="nav dropdown-menu" >
											  <li><a href="chooseOption.php?kiosk=26&kedai=Kepong&state=Kuala Lumpur" style="margin-left:-20px;" >Kiosk No.26</a></li>
											  <li><a href="chooseOption.php?kiosk=27&kedai=Kepong&state=Kuala Lumpur" style="margin-left:-20px;" >Kiosk No.27</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Taman Melawati</a>
											<ul class="nav dropdown-menu">
											  <li><a href="chooseOption.php?kiosk=28&kedai=Taman Melawati&state=Kuala Lumpur" style="margin-left:-20px;" >Kiosk No.28</a></li>
											  <li><a href="chooseOption.php?kiosk=29&kedai=Taman Melawati&state=Kuala Lumpur" style="margin-left:-20px;" >Kiosk No.29</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> UTC Pudu</a>
											<ul class="nav dropdown-menu">
											  <li><a href="chooseOption.php?kiosk=30&kedai=UTC Pudu&state=Kuala Lumpur" style="margin-left:-20px;" >Kiosk No.30</a></li>
											  <li><a href="chooseOption.php?kiosk=31&kedai=UTC Pudu&state=Kuala Lumpur" style="margin-left:-20px;" >Kiosk No.31</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Dua Sentral</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=32&kedai=Dua Sentral&state=Kuala Lumpur" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.32</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Jalan Klang Lama</a>
											<ul class="nav dropdown-menu">
											  <li><a href="chooseOption.php?kiosk=33&kedai=Jalan Klang Lama&state=Kuala Lumpur" style="margin-left:-20px" >Kiosk No.33</a></li>
											  <li><a href="chooseOption.php?kiosk=34&kedai=Jalan Klang Lama&state=Kuala Lumpur" style="margin-left:-20px" >Kiosk No.34</a></li>
											</ul>
										</li>
										<hr/>
									</ul>
								</li>
								 
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Kelantan</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Kota Bahru</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=62&kedai=Kota Bahru&state=Kelantan" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.62</a></li>
											</ul>
										</li>
										<hr/>
									</ul>
								</li>
								  
								<li class="treeview" >
									<a href="#">
										<i class="fa fa-arrow-circle-o-down"></i>
										<span>Terengganu</span>
									</a>
									<ul class="treeview-menu">
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Terengganu</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=63&kedai=Terengganu&state=Terengganu" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.63</a></li>
											</ul>
										</li>
										<li class="dropdown"><a href="#"><i class="fa fa-angle-double-right"></i> Kemaman</a>
											<ul class="nav dropdown-menu" style="width:100px;height:30px">
											  <li><a href="chooseOption.php?kiosk=64&kedai=Kemaman&state=Terengganu" style="margin-left:-20px;margin-top:-13px;" >Kiosk No.64</a></li>
											</ul>
										</li>
										<hr/>
									</ul>
								</li>
								 
								<li class="treeview" >


Before i apply the fixed layout,everything is working find. Once i put "skin blue fixed" then my dropdown menu for the hover part is been overlap by the content

**Comment by almasaeed2010** [comment]
As I suspected, the markup is invalid. You are using ```nav dropdown``` when you should use ```treeview-menu``` and you shouldn't add ```<span>``` in your treeview submenu.

Here is an example of how it should look like:
```html
<!-- Sidebar Menu -->
<ul class="sidebar-menu">
  <li class="header">HEADER</li>
  <!-- Optionally, you can add icons to the links -->
  <li class="active"><a href="#"><i class='fa fa-link'></i> <span>Link</span></a></li>
  <li><a href="#"><i class='fa fa-link'></i> <span>Another Link</span></a></li>
  <li class="treeview">
    <a href="#"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
    <ul class="treeview-menu">
      <li><a href="#">Link in level 2</a></li>
      <li><a href="#">Link in level 2</a></li>
    </ul>
  </li>
</ul><!-- /.sidebar-menu -->
```

I assure you, if you fix those issues, it will work. Also, please keep in mind that you can't use ```sidebar-mini``` with ```fixed``` at the same time.

**Comment by almasaeed2010** [comment]
One more thing, if you use the fixed layout, your dropdown won't work because the fixed layout requires ```overflow: none```. This disables any elements that are supposed to pop out to the left as in your example in the very first image. Your best bet is to stick with treeview if you must use fixed. Otherwise, you will have to use the regular layout.

**Comment by marcus6431** [comment]
so what is the best way to use the sidebar-mini?

**Comment by almasaeed2010** [comment]
The best way is to use it without the ```fixed``` layout.

**Comment by marcus6431** [comment]
Okay, if i wanted to change the hover menu to like inside the treeview. What should i change? Example: I click Pahang then Hover to his child Kuantan, then it will show up dropdown menu of Kiosk 36?

**Comment by almasaeed2010** [comment]
Unfortunately, AdminLTE doesn't support that functionality. Sorry.

**Comment by marcus6431** [comment]
May i know if i change the sidebar to top nav , will it work for the dropdown?

**Comment by almasaeed2010** [comment]
If you have the code that provides a multilevel dropdown then yes. It should work because the top-nav is a regular Bootstrao navbar.

**Comment by marcus6431** [comment]
so if i using a regular sidebar but i set the position:fixed, how may i add a scrollbar inside the sidebar myself? i had try to put overflow-y:auto but it won't work, any clue?

**Comment by almasaeed2010** [comment]
You'll have to remove the SlimScroll plugin and implement your own mechanism to enable scrolling.

**Comment by almasaeed2010** [comment]
In a nut shell, you will have to set a specific height to the sidebar (probably using JS) and then add overflow: auto.

**Comment by marcus6431** [comment]
May i know where to remove the slimscroll plugin?

**Comment by marcus6431** [comment]
i can't implement the slimscroll on the sidebar if i manually fixed the position?

**Comment by almasaeed2010** [comment]
SlimScroll will prevent overflow all together and that's why you are having the issue

**Comment by marcus6431** [comment]
So where to remove the slimscroll?

**Comment by almasaeed2010** [comment]
In app.js you should disable anything that uses it and remove the slimscroll.js from your HTML

**Comment by marcus6431** [comment]
Tahsnk for the reply. But May i know where to change the height of the livechat box? because i had try to set the height of the livechat box,but it auto stractch back to it original size

**Comment by almasaeed2010** [comment]
If you mean the direct chat than it is customizable in AdminLTE.css. Find ```.direct-chart``` and customize it.

**Comment by t3-jo** [comment]
Hello,,,i have a problem about this template.
In sidebar my drop-down menu won't run, can you help me?
thanks :D

**Comment by marcus6431** [comment]
@t3-jo  ???

**Comment by marcus6431** [comment]
@almasaeed2010  Hi there, Good day to you.
I can't find the .direct-chart that u mention in AdminLTE.css there.

I wanted to change the height of this content, but everytime i try to change it alway auto scratch to its normal size.
![1](https://cloud.githubusercontent.com/assets/11958254/7341077/06bab502-ec50-11e4-9034-d7aea94a035a.PNG)

I need to change it become longer. Is that possible?

**Comment by vanireddy91** [comment]
Hi ,
In my 2 level dropdown, when I click on the orange arrow, it is closing my left nav bar.Below is my code:
  <li class="treeview"  id="a_parent" data-toggle="offcanvas">
              <a href="#">
                <i class="fa fa-pie-chart fa-2x"></i> <span id="a_text"  >Analysis Reports </span>
                <i  style="display:none;" class="fa fa-angle-left pull-right text-orange"></i>
              </a>
              <ul class="treeview-menu" style="width: 230px;">
                <li style="display:none;"><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
				
				<% for ( String p : reportModules ) {
					if(rolesList.contains(p.toLowerCase())) {
					%>
                <li><a href="#"> <%= p %> <i class="fa fa-angle-left pull-right text-orange"></i></a>
				  
                  <ul class="treeview-menu" style="width:250px;">
					<li style="display:none;" ><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
					
						 <% for ( String subR : subRepModules.get(p) ) { %>
					 <li>
                      <a href="javascript:Home.openRepositoryFile('/home/PERFDOWJONES-Shared/Analysis Reports/Sales/Sales Order Template.xanalyzer', 'run');" >
					  <i style="display:none;" class="fa fa-circle-o"></i>
					   <%= subR %></a>
                     </li>
					 <% } %>
                  </ul>
				  
				  
				  </li>
				  
					<%  }}%> 
                
              </ul>
            </li>

**Comment by vanireddy91** [comment]
I am using app.min.js of version 2.3.0

**Comment by iqrajabeen** [comment]
i am using adminlte theme on my desktop it works fine but when i press f12 to chk it on mobile resolution and i click on any link or button it logouts why i am facing this issue for a long time kindly tell me why it happens is desktop  theme works for mobile or not.

**Comment by iqrajabeen** [comment]
kindly reply me pleaseeeeeeeeee

**Comment by iqrajabeen** [comment]
i want to resolve this issue as soon as possible.
