### ISSUE TITLE
checkbox

### ISSUE THREAD

**Issue by alien3d** [almasaeed2010/AdminLTE#341]
You might add some extra code to sample email. 

$(".checkbox-toggle").click(function () {
 var clicks = $(this).data('clicks');
  if (clicks) {
   $("input[type='checkbox']", ".mailbox-messages").iCheck("uncheck");
   $("#checkboxIcon").removeClass().addClass("fa fa-square-o");
} else {
  $("input[type='checkbox']", ".mailbox-messages").iCheck("check");
  $("#checkboxIcon").removeClass().addClass("fa fa-check-square-o");
 }
 $(this).data("clicks", !clicks);
});

**Comment by almasaeed2010** [comment]
Thanks for the suggestion. Implemented in v2.1.0. Changes are available in master.
