### ISSUE TITLE
How to Remove Layout Options?

### ISSUE THREAD

**Issue by jplt001** [almasaeed2010/AdminLTE#343]
Guys how do remove Layout Option Settings?
Thank You in Advance, for those who can help me .. 
![ahahaha](https://cloud.githubusercontent.com/assets/11808322/7181059/1359ed1a-e47a-11e4-8f27-06c9cfc77e6c.png)

**Comment by yufieko** [comment]
delete <script src="dist/js/demo.js" type="text/javascript"></script>
