### ISSUE TITLE
I am not able to see User dropdown menu on header

### ISSUE THREAD

**Issue by venkatiiitb** [almasaeed2010/AdminLTE#344]
Hi Have integrated all the files in your blank.html file but still not able to see user drop down menu in the header and no errors in the console. May i know am i missing something.

**Comment by yufieko** [comment]
you can go to inspect element > network tab, refresh your page and see is there any error or missing file(s).

**Comment by almasaeed2010** [comment]
Do you mean the click doesn't work? Or you can't see it completely?
