### ISSUE TITLE
Issue with scroll spy

### ISSUE THREAD

**Issue by ber5ien** [almasaeed2010/AdminLTE#346]
Hi Guys,

I assume it's probably only my issue ;)

My navigate does not stame on the same link after the page is refresh any advise?

Am I missing something?

  <body class="skin-blue" data-spy="scroll" data-target="#scrollspy">
      <aside class="main-sidebar">       
        <div class="sidebar" id="scrollspy">

**Comment by almasaeed2010** [comment]
Hello,
You have to create a mechanism that will assign the active link the class ```active```. 
All active links must have this form:
```html
<li class='active'>
  <a href='#fake-link'>Active Link</a>
</li>
```

In case you are using treeview:
```html
<li class='treeview active'>
  <a href='#link'>Active</a>
  <ul class='treeview-menu'>
    <li class='active'>
      <a href='#fake-link'>Active Link</a>
    </li>
  </ul>
</li>

**Comment by ber5ien** [comment]
Many Thanks for info. I though that the scrollspy stuff will do this for me automatically. Should it?

<body class="skin-blue" data-spy="scroll" data-target="#scrollspy">
<div class="sidebar" id="scrollspy">

**Comment by almasaeed2010** [comment]
I use scrollspy in the documentation and I must say it is not convenient to create. It has many issues when integrated with AdminLTE.

Scrollspy works well if your app has only one page since it only detects elements that have an id attribute.

**Comment by ber5ien** [comment]
Many thanks for info. I know what i am doing now.

Rafal Zdziech
http://uk.linkedin.com/in/amionrails

**Comment by almasaeed2010** [comment]
:+1:
