### ISSUE TITLE
Layout options not working

### ISSUE THREAD

**Issue by dbd5** [almasaeed2010/AdminLTE#347]
Hello,

The documentation says as follows under Layout Options:
__
AdminLTE 2.0 provides a set of options to apply to your main layout. Each on of these classes can be added to the body tag to get the desired goal.

Fixed: use the class .fixed to get a fixed header and sidebar.
Collapsed Sidebar: use the class .collapsed-sidebar to have a collapsed sidebar upon loading.
Boxed Layout: use the class .layout-boxed to get a boxed layout that stretches only to 1250px.
Top Navigation use the class .layout-top-nav to remove the sidebar and have your links at the top navbar.
__

My preference is for the dashboard to start fixed with sidebar collapsed so I have changed the body tag as follows ```<body class="fixed collapsed-sidebar skin-black">``` but its not working (Angle braces reversed by me so the tag won't get removed). Please advice what I'm doing wrong.

Regards,

Adam

**Comment by almasaeed2010** [comment]
Change your body tag to:
```html
<body class='fixed sidebar-collapse skin-black'>
```
