### ISSUE TITLE
modal box does not work if you click off after open

### ISSUE THREAD

**Issue by Roseno** [almasaeed2010/AdminLTE#350]
use: data-toggle="modal" data-target="#open-modal" on a Open Modal

problem:
when the modal opens (```<div class = "modal fade" id = "include item-product-orc" tabindex = "- 1" role = "dialog" aria-hidden = "true">```) clicks outside the div's modal, (light gray part) ```<a her> opem modal </a>``` no longer works

**Comment by almasaeed2010** [comment]
Please post your full modal html without the content. Here is how it is supposed to look like:
```html
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body...</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
```

**Comment by Roseno** [comment]
perhaps the way I was calling the <div class = "modal fade" id="open-modal">
what is the best call to open the modal?
I open well
<a href="#"  data-toggle="modal" data-target="#iopen-modal">Open Modal</a>

recorded a video statement.
video: http://youtu.be/iMeQt-_qyEw    or    https://www.youtube.com/watch?v=iMeQt-_qyEw&feature=youtu.be&ab_channel=CarlosRoseno

**Comment by Roseno** [comment]
was missing this script
<script type="text/javascript">
  $(document).ready(function() {

	$('#btn-delete-trig).click(function(){
		$('#modal-delete').modal('show');
	});
  });
</script>
now worked, thanks
