### ISSUE TITLE
Invoice and print

### ISSUE THREAD

**Issue by MaticConradi** [almasaeed2010/AdminLTE#351]
Hi! First I have to say that this is really awesome template. Probably the best of it's kind I've ever had.
Now... I'm exploring "Invoice" page. When I click print and a print dialog comes up, a little preview comes up. I can see that header and footer are filled with: webpage title, date, URL and page number. I would like to remove those from the page or add my own header/footer. Where can I access the file with the print settings?

**Comment by almasaeed2010** [comment]
Hello,
Thanks for the compliment.
These are browser settings and cannot be controlled from the template. Depending on the browser and OS you are using, you can customize the settings to achieve your goal.
