### ISSUE TITLE
_all-skins.css is not included into bower.json main 

### ISSUE THREAD

**Issue by defyjoy** [almasaeed2010/AdminLTE#354]
Skins are important part of bower automation while using with gulp and minification . So I think _all-skins.css file should be included into the bower.json main files.

**Comment by almasaeed2010** [comment]
Hello

_all-skins.css is for demo purposes only. You should always pick your favorite skin and load that skin only.

**Comment by defyjoy** [comment]
Ok so any skin I want I should pick the specific skin itself ? anyway to automate this ?

**Comment by almasaeed2010** [comment]
Picking the skin you want will lessen the loading time on your page. I don't understand how can you automate this. Once you change it once, you don't have to change it again unless you want to use a different skin.
