### ISSUE TITLE
A suggestion: Make loading states possible on arbitrary blocks

### ISSUE THREAD

**Issue by ivantcholakov** [almasaeed2010/AdminLTE#355]
As I can understand from the LESS file and documentation, loading states can be applied only on boxes (.box class). It would be better a special class (.overlay-wrapper or something similar) to be defined, so loading states possibly to be shown on arbitrary block elements that have this class.

**Comment by ivantcholakov** [comment]
Overlay on the whole body might be useful too.

**Comment by almasaeed2010** [comment]
I will look into it. Thanks for the suggestion!

**Comment by almasaeed2010** [comment]
Done in master. Thanks again.
