### ISSUE TITLE
Add a div height:100% inside the #content div

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [almasaeed2010/AdminLTE#356]
I am Trying to use a leaflet map http://leafletjs.com/ in my content pane.

Please how can i get the map, or any div content to be 100% of the content pane?

**Comment by almasaeed2010** [comment]
Hi,

You will have to use javascript. Since the template depends on javascript to initiate the layout sizes, it won't be responsive to CSS. To have a div with a height of the window, you can use this code:

```js
var window_height = $(window).height(),
      header_height = $(".main-header").height();
$("#myDiv").css("height", window_height - header_height);
```

**Comment by ajaykorat** [comment]
Hi,

I doesn't find the listing view with <div> tag in AdminTLE please try to help me if you are getting my issue.

**Comment by almasaeed2010** [comment]
@ajaykorat I don't understand your issue. Please open a new issue with full explanation of the problem. Thanks.

**Comment by CharlesOkwuagwu** [comment]
Thanks, i have resolved it.
For anyone else having this issue u may try:

setTimeout(function () { map.invalidateSize() }, 500);

    <script type="text/javascript">
        $(document).ready(function () {
            var contentHeigh = $("body > #wrapper").height() - 100;
            $('#map').css("height", contentHeigh + "px");
        });
    </script>

**Comment by ivantcholakov** [comment]
http://www.labnol.org/internet/embed-responsive-google-maps/28333/
