### ISSUE TITLE
Fresh Install | UI is a Mess

### ISSUE THREAD

**Issue by jadubbz** [almasaeed2010/AdminLTE#359]
I just stumbled on your amazing software and installed it within a subfolder of my website. As I navigated to it, I found the Dashboard to be a mess. I searched around for similar problems, but found none. Any ideas or a link to point me in the right direction?
![screen shot 2015-04-22 at 9 02 23 am](https://cloud.githubusercontent.com/assets/12069120/7276357/aa9bb106-e8ce-11e4-85a0-a2289e07d3f6.png)

**Comment by almasaeed2010** [comment]
It looks like something wasn't loaded correctly. Please check your browser's console for errors. It might be necessary to use a local server to make it work.

**Comment by jadubbz** [comment]
Just FYI, I noticed I originally downloaded AdminLTE2.zip from https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html <https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html>

I went back and looked around some more and decided to redownload from https://almsaeedstudio.com <https://almsaeedstudio.com/> and found that it was version AdminLTE-2.0.4.zip

I uploaded the zip to my server, uncompressed it…went to the subfolder and still the same result. Refreshed, cleared cookies, etc…still a mess. I decided to test it in Firefox…WORKS PERFECT! Chrome? PERFECT!!! It’s just Safari Version 8.0.5 (10600.5.17) that is giving me fits. My computer model is iMac (27-inch, Late 2013), 3.5 GHz Intel Core i7, 32 GB 1600 MHz DDR3

If I can help debug this, please let me know. 

The errors being reported are:

Failed to load resource: the server responded with a status of 404 (Not Found)
/dash/bootstrap/js/bootstrap.min.js (I looked and it IS there)

Failed to load resource: the server responded with a status of 404 (Not Found)
/dash/bootstrap/css/bootstrap.min.css (I looked and it IS there)


The warnings being reported are:

Unexpected CSS token: : font-awesome.min.css:4
Unexpected CSS token: : 10AdminLTE.min.css:7

Invalid CSS property declaration at: * blue.css:6
Invalid CSS property declaration at: / jquery-jvectormap-1.2.2.css:22
Invalid CSS property declaration at: * datepicker3.css:780
Invalid CSS property declaration at: * datepicker3.css:781



On Apr 22, 2015, at 12:40 PM, Abdullah Almsaeed <notifications@github.com> wrote:

It looks like something wasn't loaded correctly. Please check your browser's console for errors. It might be necessary to use a local server to make it work.

**Comment by almasaeed2010** [comment]
This is odd. I downloaded the version you are using and it worked fine on Safari 8.0.5 (10600.5.17). Are you using MAMP, Vagarant or a different server? It should've worked out of the box simply by opening the index.html file. Try opening the starter.html file by double-clicking it. If it works fine on Safari, then the server you are using is somehow preventing these resources from loading. I'd appreciate it if you get back to me with the results.

![screen shot 2015-04-22 at 9 49 15 pm](https://cloud.githubusercontent.com/assets/1512664/7289111/78f15b68-e939-11e4-8ad3-77d927646572.png)

**Comment by tiipiik** [comment]
Hi,
Thanks for this really awsome theme !
I have the same problem here, on a local install in Laravel5 (runing with artisan serve). Got the same errors in Firefox but not in Chrome.
![capture d ecran 2015-04-23 a 11 39 47](https://cloud.githubusercontent.com/assets/3844253/7294513/591a78ae-e9ae-11e4-9295-f1d2527ef34b.png)

**Comment by almasaeed2010** [comment]
@jadubbz any updates?

@tiipiik I am using the template with Laravel 5 and Homestead and at first I faced a few problems. Here is how I solved them:
- Make sure that all of the AdminLTE assets are available and accessible by placing them in the public directory and checking that all file permissions are set properly.
- Check your html (or blade) and make sure that all the resources are linked to correctly. Some servers require that files are case sensitive, so ```app.js``` does not equal ```App.js```.

I am not sure why firefox would give such an error. "dead object"? What do you think that means?

**Comment by tiipiik** [comment]
@almasaeed2010 Don't really know. I just find this => https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/
So maybe your code is not responsible of this issue, but a Firefox extension is (or maybe is) !

I'll try to deactivate estensions one after the other and tell you if it changes something.

**Comment by almasaeed2010** [comment]
I tested FF again just to make sure if any errors show up on my end but I didn't get anything. I then installed it on homestead but it also worked fine there. No errors at all. Please let me know if you find the issue that's causing this in your end so we address it here in case it is an error from our end.

![screen shot 2015-04-23 at 10 18 24 am](https://cloud.githubusercontent.com/assets/1512664/7299155/3f39b2e4-e9a2-11e4-815c-5d38eabc8c8a.png)

**Comment by tiipiik** [comment]
Well, this is quite strange.
After I deactivate all extensions and then reactivate all one by one, errors just "disappear". I also renamed dist/css/AdminLTE.min.css to dist/css/admin-lte.min.css, but it seems not to change anything, as I rename files like originals and errors are still not here.

If other people who have the same issue can try to deactivate all extensions and tell if it make the same as for me it would be interesting !

**Comment by jadubbz** [comment]
I apologize…my email at work is not working correctly. Just checking this at home and found these messages. I’ll look at these when I get a chance this evening and get back with you. I apologize.

Jacob


On Apr 23, 2015, at 9:43 AM, Yohann Decharraud <notifications@github.com> wrote:

Well, this is quite strange.
After I deactivate all extensions and then reactivate all one by one, errors just "disappear". I also renamed dist/css/AdminLTE.min.css to dist/css/admin-lte.min.css, but it seems not to change anything, as I rename files like originals and errors are still not here.

If other people who have the same issue can try to deactivate all extensions and tell if it make the same as for me it would be interesting !

**Comment by jadubbz** [comment]
I apologize…my email at work is not working correctly. Just checking this at home and found these messages. I’ll look at these when I get a chance this evening and get back with you. I apologize.

Jacob


On Apr 23, 2015, at 4:47 AM, Yohann Decharraud <notifications@github.com> wrote:

Hi,
Thanks for this really awsome theme !
I have the same problem here, on a local install in Laravel5 (runing with artisan serve). Got the same errors in Firefox but not in Chrome.
 <https://cloud.githubusercontent.com/assets/3844253/7294513/591a78ae-e9ae-11e4-9295-f1d2527ef34b.png>

**Comment by almasaeed2010** [comment]
Tested on all browsers but couldn't replicate the issue yet. If there is no progress on this, I will have to close the post. Thank you.
