### ISSUE TITLE
The contents of a box when I collapse the menu does not fit the entire screen.

### ISSUE THREAD

**Issue by carlosabel125** [almasaeed2010/AdminLTE#363]
Hi, I am testing the AdminLTE2.0 template. In the area of work occupied a box in which I have defined a graph componet when I collapse the menu the box adjusts to the new size, however the graphic component does not fit the new size of the box .
How do I can get my graphic component fit the size of the box when I collapse the menu?
Thank you in advance ....
![1](https://cloud.githubusercontent.com/assets/12088787/7306533/8888faa8-e9cb-11e4-93f0-7b30a06d9345.png)
![2](https://cloud.githubusercontent.com/assets/12088787/7306534/888af9d4-e9cb-11e4-8b39-c62688ef10d5.png)

**Comment by almasaeed2010** [comment]
Hello,

Sorry for the delay. What kind of component is it? For example, is it a ```<table>``` or a ```<div>```? 

In general you need to set the width via CSS to 100% and it will automatically take the width of its container.
```CSS
.my-class {
  width: 100%;
}
```

**Comment by carlosabel125** [comment]
Hi thanks for answering :
I have a container that is a < div > I give the width: 100% ; div and it fits well , but within that div I have a DevExpress component and this no one ASPxDASBOARD adjusts itself to my container < div > . In the Safari browser if it fits me perfectly but the other is not adjusted.
Thank you very much friend and I hope I can help. regards

**Comment by almasaeed2010** [comment]
I am not sure if I can provide more help without access to the dashboard. It would be hard for me to analyze your implementation without inspecting it.
