### ISSUE TITLE
Hello, The contents of a box when I collapse the menu does not fit the entire screen.

### ISSUE THREAD

**Issue by carlosabel125** [almasaeed2010/AdminLTE#364]
Hi, I am testing the AdminLTE2.0 template. In the area of work occupied a box in which I have defined a graph componet when I collapse the menu the box adjusts to the new size, however the graphic component does not fit the new size of the box .
How do I can get my graphic component fit the size of the box when I collapse the menu?
Thank you in advance ....
![1](https://cloud.githubusercontent.com/assets/12088787/7308307/f1cfdede-e9d8-11e4-8058-2df4ac31f682.png)
![2](https://cloud.githubusercontent.com/assets/12088787/7308308/f1d31bbc-e9d8-11e4-9b41-d93893b25ece.png)

**Comment by almasaeed2010** [comment]
duplicate.
