### ISSUE TITLE
The contents of a box when I collapse the menu does not fit the entire screen

### ISSUE THREAD

**Issue by carlosabel125** [almasaeed2010/AdminLTE#365]
Hi, I am testing the AdminLTE2.0 template. In the area of work occupied a box in which I have defined a graph componet when I collapse the menu the box adjusts to the new size, however the graphic component does not fit the new size of the box .
How do I can get my graphic component fit the size of the box when I collapse the menu?
Thank you in advance ....
![1](https://cloud.githubusercontent.com/assets/12088787/7319611/586a2298-ea5c-11e4-88d7-167229779bc5.png)
![2](https://cloud.githubusercontent.com/assets/12088787/7319612/586e9e5e-ea5c-11e4-8e42-d12ffdab2094.png)

**Comment by almasaeed2010** [comment]
Duplicate.
