### ISSUE TITLE
[RELEASE] AdminLTE v3.2.0

### ISSUE THREAD

**Issue by danny007in** [almasaeed2010/AdminLTE#3687]
Major Priority to solve
- [x] https://github.com/ColorlibHQ/AdminLTE/issues/3599
- [x] https://github.com/ColorlibHQ/AdminLTE/issues/3649
- [x] https://github.com/ColorlibHQ/AdminLTE/issues/3570
- [x] https://github.com/ColorlibHQ/AdminLTE/issues/3604
- [ ] https://github.com/ColorlibHQ/AdminLTE/issues/3561

@REJack solve this bit fast, because it causing issue in AdminLTE v3.1
and
ill update docs and readme

**Comment by REJack** [comment]
👌🏻 I'll look over it later this evening or tomorrow

**Comment by develart-projects** [comment]
Hi guys, is there any ETA for this release, please ? #3599 is blocking bug, thank you.

**Comment by hersag** [comment]
any news on 3.2 release date please? thank you guys!

**Comment by REJack** [comment]
I've closed now all issues, I will release the v3.2.0-rc later (first I need some sleep 😄). If i missed any issue please mention me on it.

**Comment by hugith** [comment]
Will there be a 3.2.0 or should I set my sights on v4? Planning a new project and just picking out tech :)

**Comment by REJack** [comment]
IMHO that depends how fast you need to develop your project 😄

**Comment by REJack** [comment]
🥳🎉 v3.2 is live, incl. docs and our new website 🎉😄

**Comment by craph** [comment]
I think this issue can be closed 😄
