### ISSUE TITLE
AngularJS implementation

### ISSUE THREAD

**Issue by zvik2004** [almasaeed2010/AdminLTE#369]
Hi,
I really like the AdminLTE!
Are there any thoughts to have an AngularJS implementation for it?

Thanks,
Zvi

**Comment by almasaeed2010** [comment]
Hello,

Unfortunately I am not aware of an existing AngularJS implementation. I don't think it is hard to convert it to AngularJS if you really must. Thanks.

**Comment by raulrotundo** [comment]
What a shame that it won't be able to make possible the AngularJS's implementation... I think is better to get a starter angular template like ng-admin for example: https://github.com/marmelab/ng-admin
