### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by STCGroup** [almasaeed2010/AdminLTE#374]
Hello, 

I would like to use a theme template, but my question (is it support an RTL),  I need to build a dashboard for two language (RTL, LTR) and can i navigate between them .

Can you please add us a demo, or Let me know if this feature added into theme automatically when i use it , and can you share us a snapshot for that if available .

Best Regards,

**Comment by YasserHassan** [comment]
RTL is not officially supported in AdminLTE but @lxsameer is working on it in a fork and I think he has reached good results. You can refer to #23 and #313 for more details.

**Comment by almasaeed2010** [comment]
RTL is a work on progress and might be available officially with the next release. I can't promise any specific time frame or that I will for sure implement it. As @YasserHassan suggested, you may find different implementations of it around Github. Thanks.

**Comment by STCGroup** [comment]
Thank you .

**Comment by masteradhoc** [comment]
@STCGroup , @YasserHassan Take a Look at PR #489
