### ISSUE TITLE
Control sidebar on Safari causes horizontal scroll

### ISSUE THREAD

**Issue by almasaeed2010** [almasaeed2010/AdminLTE#377]
The control sidebar (right sidebar) causes horizontal scroll on Safari 8.0.5. All other browsers including IE9 function properly except for Safari.

This brings up two bugs that are only applicable to Safari 8.0.5. The first is the sidebar-mini issue #370. The second is this.

![screen shot 2015-04-29 at 8 15 30 pm](https://cloud.githubusercontent.com/assets/1512664/7404118/81caadd4-eeac-11e4-951d-482431492d91.png)

**Comment by iaesaudi** [comment]
This bug also happens on iOS safari (Tested on iOS 8.2)

**Comment by almasaeed2010** [comment]
It happens on all Safari browsers, unfortunately. I am still not sure what the issue is. How come the exact same strategy works for the left sidebar but not the right one? I don't understand!

**Comment by almasaeed2010** [comment]
Fixed.
