### ISSUE TITLE
AdminLTE Custom Tabs - First tab deactive problem

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#378]
Hello!

When using "AdminLTE Custom Tabs", the tab's title move to the right by 1px.

To reproduce the problem:

1: Find the "AdminLTE Custom Tabs" in "UI Elements > General"
2: Click on "Tab 2" (Tab 1 was in active mode)
3: "Tab 2" and "Dropdown" title will move to the right by 1px.

This problem appears in stable and 2.1-beta release.
This problem appears even without tab content (just UL and LI is enough).
This problem does not appears in default bootstrap nav-tab.

Using Chrome 42.

Best regards!

**Comment by almasaeed2010** [comment]
Confirmed.

Thank you for reporting this! Will get to it soon.

**Comment by almasaeed2010** [comment]
Fixed in master. Thanks again!

**Comment by persoomar** [comment]
test

**Comment by almasaeed2010** [comment]
What are you testing @persoomar? :)

**Comment by persoomar** [comment]
Lol
Sorry it was a mistake :)
Good night Abdallah .

**Comment by tangjun114** [comment]
where i can get the version with the customer tabs,  i need the change the right panel without refresh all page
