### ISSUE TITLE
Disable onClick auto close for nav menu

### ISSUE THREAD

**Issue by iaesaudi** [almasaeed2010/AdminLTE#379]
I just wanna ask about how to disable automatic close for dropdown menu on nav bar for specified menu item like below picture:
![autoclose-issue](https://cloud.githubusercontent.com/assets/11377260/7412556/a21d5f14-ef4c-11e4-8b24-bcf3aaf6c42a.jpg)

**Comment by almasaeed2010** [comment]
This is a Bootstrap related issue. The only way to do that is via javascript:
```js
$("#your-menu-id").on('click', function (e) {
  e.stopPropagation();
});
```

**Comment by iaesaudi** [comment]
Thanks for replying and help Abdullah :)

**Comment by almasaeed2010** [comment]
No problem. Did it work?

**Comment by iaesaudi** [comment]
Yeah it worked but the button group onside it not working since we disabled the event from running in the whole div :sweat_smile:.
I'm working on this [solution](http://stackoverflow.com/questions/25089297/twitter-bootstrap-avoid-dropdown-menu-close-on-click-inside#answer-25196101)

**Comment by almasaeed2010** [comment]
I am actually working on a custom mega menu for the premium collection. Thanks for sharing the solution!

![screen shot 2015-04-30 at 7 31 11 pm](https://cloud.githubusercontent.com/assets/1512664/7424523/3b68c1ae-ef70-11e4-9f02-6988fffbc1d1.png)
