### ISSUE TITLE
Ajax sidebar question

### ISSUE THREAD

**Issue by germansak** [almasaeed2010/AdminLTE#381]
Hi, first of all congratulations for this excelent framework! It´s awesome.
I have a multilevel treeview on my sidebar. Is it possible to load subtrees via Ajax when I click on a node? I made a lot of sql processing to build it and it affects performance when I load the page for the first time.

Any help or hint is very much appreciated

Thanx
German

**Comment by almasaeed2010** [comment]
Everything is possible. Please refer to issue #382. 

The best approach would be to let your server return a list of links and their titles and allow jQuery to render the information into HTML elements.

Example server response in json:
```json
{
  "link1": "/my/url",
  "link2": "/to/path"
}
```

Example jQuery render function:
```js
function renderLink(links) {
  $.each(links, function(title, link) {
    var li = $("<li />"),
        a = $("<a />", {href: link});
    li.html("<i class='fa fa-circle-o'></i> <span>" + title + "</span>");
    a.append(li);
    $(".sidebar-menu").append(li);
  });
```

You get the picture.

**Comment by germansak** [comment]
Awesome!! That's what I've been looking for. Thanks again Abdullah for your response and for this great framework
Cheers
Germán
