### ISSUE TITLE
Tooltip Ajax

### ISSUE THREAD

**Issue by peixinhu130** [almasaeed2010/AdminLTE#383]
Sorry for the English, I try to describe my suggestion. In version 2.1.0 app.js on line 167, use -
if (o.enableBSToppltip) {
    $ ('body'). tooltip ({
         selector: o.BSTooltipSelector
     });
}

to load tooltip for AJAX.

thank you

**Comment by almasaeed2010** [comment]
Done. Thanks for the suggestion.
