### ISSUE TITLE
Content in content view cut off

### ISSUE THREAD

**Issue by eothein** [almasaeed2010/AdminLTE#390]
Dear all

First and foremost what a great project! This makes making a front-end web site so much easier. I do have a question though:

I'm using the template with a side bar navigation, but the problem is that when the navigation is expanded, the right part of the content is cut off for some space. Collapsing the menu fixes this, but I want to be able to work correctly with the menu expanded. Is there a way to work around this?

Kind regards

Jens

**Comment by almasaeed2010** [comment]
Hello,

I don't understand the issue. Could you provide a screenshot of the problem please? 
Thanks.

**Comment by almasaeed2010** [comment]
@eothein have you resolved your issue?

**Comment by eothein** [comment]
Dear Almasaeed

I'm using Yii2 as the framework and  I had an extra <div> in which I generated my html code, but it seems this was not allowed and needed to only use the folowing code for content. 

<section class="content body">
                        <?= $content ?>
</section>

What happened was that when resizing the screen, and when using the navigation side bar, a part of the right side of the content got cut-off. I stil don't know why though.

Thanks for your help!

**Comment by YasserHassan** [comment]
@eothein just to make sure you are searching in the right place, if the original AdmiLTE version you downloaded is displayed properly as-is on your system then the problem is a result of fitting your code with it. You need to adjust your Yii2 application so it doesn't break the template.
