### ISSUE TITLE
AdminLTE latest - form didn't recieve input checkbox

### ISSUE THREAD

**Issue by digicp** [almasaeed2010/AdminLTE#394]
Hi there, is there a possibility that AdminLTE will not post this code:
<input type="checkbox" name="checkboxdata" value="1">

Input type text etc is posted and received:
<input type="text" name="textdata" value="value">

Is this a known problem?

**Comment by almasaeed2010** [comment]
Hello,

Post as in send the information to the server?

**Comment by digicp** [comment]
No, in a HTML form that submit's data to the database

**Comment by almasaeed2010** [comment]
AdminLTE doesn't deal with backend issues. If your server is not receiving data, it is possible that you setup your form incorrectly. If you post your form here, I may be able to check the markup.

**Comment by digicp** [comment]
I disabled iCheck and now it works fine...

$(function () {
    //iCheck for checkbox and radio inputs
    $('input[type="checkbox"]').iCheck({
      checkboxClass: 'icheckbox_minimal-blue',
      radioClass: 'iradio_minimal-blue'
    });

    //When unchecking the checkbox
    $("#check-all").on('ifUnchecked', function (event) {
      //Uncheck all checkboxes
      $("input[type='checkbox']", ".user_permissions_table").iCheck("uncheck");
    });
    //When checking the checkbox
    $("#check-all").on('ifChecked', function (event) {
      //Check all checkboxes
      $("input[type='checkbox']", ".user_permissions_table").iCheck("check");
    });
  });

**Comment by almasaeed2010** [comment]
iCheck deals with input a bit differently. Were you submitting your form via ajax?

**Comment by digicp** [comment]
I don't submit via ajax

**Comment by almasaeed2010** [comment]
I will look into the iCheck plugin soon. Thank you for reporting this!
