### ISSUE TITLE
Where are the .less files?

### ISSUE THREAD

**Issue by iamthestreets** [almasaeed2010/AdminLTE#395]
Hi - Forgive me if this is right in front of my face, but I do not see any of the less files. Where can I find these files?

**Comment by almasaeed2010** [comment]
Hi

They are in the build folder

**Comment by iamthestreets** [comment]
Awesome, thanks!

**Comment by iamthestreets** [comment]
Hi

If I wanted to modify the buttons, how would I do this? The less files are a little different than I'm used to.

**Comment by almasaeed2010** [comment]
Hello,
You can modify the buttons.less files or explore the variables.less file.
