### ISSUE TITLE
Print issues

### ISSUE THREAD

**Issue by SpawW** [almasaeed2010/AdminLTE#396]
Hi,

  Currently I are creating a GPL software using AdminLTE as base interface.
  I want to create a way to print all pages with a specific header and footer repated on every page.
  I try to make this using the examples and some online documentation... but not work. 
  Someone can help-me ?

**Comment by Reconix** [comment]
you could give this a try
https://docs.angularjs.org/api/ng/directive/ngInclude

**Comment by SpawW** [comment]
Reconix, tanks for answer... 
I look this url but not found info about print tips.

**Comment by ivantcholakov** [comment]
HTML (within the common template):

```
  <div id="custom_header_print">Header - Print Only ...</div>
  <div id="custom_footer_print">Footer - Print Only ...</div>
```

CSS:

```
    #custom_header_print, custom_footer_print {
        display: none;
    }
    @media print {
        #custom_header_print, custom_footer_print {
            display: block;
        }
    }
```

**Comment by SpawW** [comment]
Hi ivantcholakov, very thank you for you help.

  With this codes solve the problem... for the first page.
  When the page prints requires two A4 pages (for example) the header is not repeated. And I need it to recur every page (have a header on every page).

![captura de tela de 2015-05-05 17 38 52](https://cloud.githubusercontent.com/assets/3518964/7482409/9f93d750-f34d-11e4-8f8f-cab324b9a81d.png)
![captura de tela de 2015-05-05 17 38 48](https://cloud.githubusercontent.com/assets/3518964/7482410/9f97cc66-f34d-11e4-97a1-080735cdccad.png)

**Comment by ivantcholakov** [comment]
It is not that easy, indeed.

I've found two generalized ways:

* Using position: fixed; - Works more or less on Firefox, but not for WebKit-based browsers, it is not good eventually:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Print Test</title>

    <style>
    #custom_header_print, #custom_footer_print {
        display: none;
    }
    #body {
        margin-top: 0;
        margin-bottom: 0;
    }
    @media print {
        #custom_header_print {
            display: block;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 30px;
        }
        #custom_footer_print {
            display: block;
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 30px;
        }
        #body {
            margin-top: 30px;
            margin-bottom: 30px;
        }
    }
    </style>

</head>
<body>

  <div id="custom_header_print">Header - Print Only ...</div>

  <div id="body">

<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>
<p>Long text...</p>

  </div>

  <div id="custom_footer_print">Footer - Print Only ...</div>

</body>
</html>
```

* The second way - see this article http://www.smashingmagazine.com/2015/01/07/designing-for-print-with-css/ The specifications mentioned there allow what you want, but I have not checked browser support.

**Comment by ivantcholakov** [comment]
https://www.servoyforge.net/boards/2/topics/215?r=220

**Comment by SpawW** [comment]
Hi ivantcholakov,

   With the code works for first page. I try with the 2 first ways... and no one put the header to each page.

   The last one works but... if I use a tables instead DIV... I not will loose the responsive feature ?

**Comment by ivantcholakov** [comment]
I can't understand the last question.

**Comment by SpawW** [comment]
Ivan,
   The AdminLTE is responsible and use DIV tags (not TABLE tags). 
   So, if I use the last URL (https://www.servoyforge.net/boards/2/topics/215?r=220) will work with tables (because TR and TD) but, I think, not will work for DIVs :(.

**Comment by ivantcholakov** [comment]
You mean
```
@top-left { content: '<table><tr><td style="width:20%"><img src="logo.gif" /></td><td style="width:80%; text-align:right;" valign="top"><span class="titulogrande">Evaluación Comercial</span><br /><span class="titulomediano">Desde $fechaInicial Hasta $fechaFinal</span></td></tr></table>'; }
```
I think you can put there whatever HTML you want.

For printing maybe the grid should not be responsive. TODO for testing something like this:

```
media print {
    .container, .container-fluid {
        width: 1170px;
    }
}
```

I will play to make a good looking test page.

**Comment by SpawW** [comment]
Ivan,
  Maybe... If you want and can... I can give you access to my test page to you see what I are creating and what is the problem.
  I try to use your tips... but the browser simply not show the @top-left info.

**Comment by ivantcholakov** [comment]
Wait, I am working on a common demo.

**Comment by SpawW** [comment]
Ok Thanks.
(a sample working with header for tables) 
http://jsfiddle.net/jaap/7ZGVv/2/

**Comment by ivantcholakov** [comment]
Showing repetitive thead and tfoot of a table on printing is trivial. I want to print an arbitrary HTML content with repetitive header and footer this is the tricky thing.

**Comment by ivantcholakov** [comment]
@top-left and etc. is likely not supported by WebKit at the moment. http://en.wikipedia.org/wiki/Comparison_of_layout_engines_(Cascading_Style_Sheets)

Not good.

**Comment by ivantcholakov** [comment]
If it was supported, the good way would be this:

```
    <style type="text/css">

        @media print {

            /* We don't need a responsive grid while printing. */
            .container, .container-fluid {
                width: 1170px;
            }

            /* Get rid of the href values. */
            a[href]:after {
                content: none !important;
            }
        }

        @page {
            size: A4;
            margin: 25mm;
            @top-center {
                content: '<span style="color=red;">Printable Header</span>';
            };
            @bottom-center {
                content: '<span style="color=red;">Printable Footer</span>';
            }
        }

    </style>
```

It is not supported at the moment by Chrome, Firefox.

I tried other proposed tricks that I found, but none of them really worked.

There is one last option: http://welcome.totheinter.net/autocolumn/sample10.html
http://welcome.totheinter.net/columnizer-jquery-plugin/
but it seems to me complicated, I don't want to go there. You can try it, if you wish.

Mission impossible. :-)
