### ISSUE TITLE
Enhancement: Fix tabs in right sidebar

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#397]
Currently, the whole right sidebar tabs (tab headings and contents) are scrollable. This means when a tab with large contents is open and the sidebar is scrolled up, the tab headings become invisible and opening another tab requires the user needs to scroll down to show the hidden tabs first. It would be better for usability if the tab contents only are scrollable while the tab headings are fixed and always visible so opening other tabs would not require that extra scroll down step.
![adminlte 2 dashboard 2015-05-06 12-28-28](https://cloud.githubusercontent.com/assets/9349772/7491791/d3638294-f3f5-11e4-8116-64e186999489.png)

**Comment by almasaeed2010** [comment]
Hello,

What if the sidebar was used without tabs? The sidebar is shouldn't be limited tabs and should be able to deal with such situations where tabs are not used. Can you think of a way to make that possible? 
Thanks for the suggestion!

**Comment by YasserHassan** [comment]
Actually I believe there should be no conflict between the two situations. Currently the structure is as below (simplified):
```
<aside>
  <ul>
    <li>Tab Heading 1</li>
    <li>Tab Heading 2</li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane">Tab Body 1</div>
    <div class="tab-pane">Tab Body 2</div>
  </div>
</aside>
```
In fixed right sidebar mode, the scrolling is applied on the `<aside>` element level so all its contents become scrollable. That is, all the tabs are treated as a single scrollable element.

However, if the scrolling is applied on the `tab-pane` DIVs level instead, only the contents/bodies of each tab will be scrollable separately. If a developer needs to remove the tabs and display contents only, he can use only one `<div class="tab-pane">Content</div>` directly inside the `<aside>`, of course without the `tab-pane` class. Those DIVs would probably require a special class to use as a selector for applying scrolling as there could be different number of tabs or no tabs at all.

Please notice that in such case, it would be better to have a smaller/narrower scroll bar than the one currently used with the right sidebar.

It might be better to look at it as scrollable container elements rather than tabs. In such case, a new element/component/widget is introduced to AdminLTE that can display large contents inside a fixed size DIV/box that automatically adds scrolling if the contents are larger than the display size (slimScroll style). In that case, the scrolling feature would be applied to any element/container with such class (e.g. `class="scrollable-content"`) anywhere. The matter of scrolling the left sidebar tabs contents, or any contents in general, would then be applying that class to the tab panes. This could also affect the right sidebar implementation in fixed mode as it would be treated as any other element without special code to it. Whether it should be JavaScript/jQuery or CSS-based is another discussion but I'm more biased to jQuery because it would produce more appealing results such as that via slimScroll.

I hope this was helpful and let's discuss it further if required.
