### ISSUE TITLE
Has some problem with advanced data table

### ISSUE THREAD

**Issue by tejaswaroop51** [almasaeed2010/AdminLTE#398]
There are like 1925 entires in my data but when i load into datatable it is displaying only 1825 entries how to solve this please help me

**Comment by githubjeka** [comment]
What you mean ` like 1925 entires `? Please add screen.

**Comment by almasaeed2010** [comment]
I think this is a back-end issue. Are you sure that all records are loaded? If so, you might want to report the issue in the <a href="https://github.com/DataTables/DataTables">datatables</a> repository.
