### ISSUE TITLE
Demo not loading all content

### ISSUE THREAD

**Issue by blah73** [almasaeed2010/AdminLTE#402]
When I browser here:
https://almsaeedstudio.com/preview

Not all of the content loads.  This is due to the HTTPS and HTTP mixing of content loading.

It appears this has been fixed in the repo by loading ionicons.min.css over HTTPS.  However the demo page has not been updated to reflect that change.

**Comment by almasaeed2010** [comment]
I will fix this soon. Thank you for letting us know!

**Comment by almasaeed2010** [comment]
Fixed.
