### ISSUE TITLE
Left collapsed mini sidebar dont hide

### ISSUE THREAD

**Issue by ccarrionp** [almasaeed2010/AdminLTE#410]
if you scroll the mouse and leave collapsed mini sidebar, the content of sidebar still showing

**Comment by almasaeed2010** [comment]
Which browser are you using?

**Comment by ccarrionp** [comment]
Safari, on google chrome works well

**Comment by ccarrionp** [comment]
Tested on mac with safari the bugs works, tested on windows 8.1 with google chrome works fine.

**Comment by aoao** [comment]
safari 8.0.5 (10600.5.17) 
![bug](https://cloud.githubusercontent.com/assets/194267/7554809/5a28fa40-f769-11e4-96b7-542fa16dee07.png)

**Comment by aoao** [comment]
temp fix  
.sidebar-mini.sidebar-collapse .main-sidebar .user-panel > .info,
  .sidebar-mini.sidebar-collapse .sidebar-form,
  .sidebar-mini.sidebar-collapse .sidebar-menu > li > a > span,
  .sidebar-mini.sidebar-collapse .sidebar-menu > li > .treeview-menu,
  .sidebar-mini.sidebar-collapse .sidebar-menu > li > a > .pull-right,
  .sidebar-mini.sidebar-collapse .sidebar-menu li.header {
    display: none!important;
    `-webkit-transform: translateZ(0);`
  }

**Comment by almasaeed2010** [comment]
This problem keeps happening in Safari for some reason. I'll try the fix @aoao provided. Thanks.

**Comment by flibX0r** [comment]
The fix provided by @aoao works perfectly for me on multiple devices running iOS 8

**Comment by almasaeed2010** [comment]
Tested and fixed in Master.

**Comment by posillipo** [comment]
how can I Hide left panel permanetly?
please help me.
tanks
