### ISSUE TITLE
removal of bootstrap import in less

### ISSUE THREAD

**Issue by sniper7kills** [almasaeed2010/AdminLTE#413]
In the styles and in AdminLTE.less there are the following imports
    @import "../bootstrap-less/mixins.less";
    @import "../bootstrap-less/variables.less";

I would like to suggest creating an AdminLTE-example.less (or similar) that would have those two imports for your grunt task(s). Allowing the use of AdminLTE without having to edit your package to use a pre-existing bootstrap download

I.E. I have an admin.less; where base.less imports bootstrap and other site-wide less files.
    @import "base.less";
    @import "../vendor/admin-lte/build/less/AdminLTE.less";
    @import "../vendor/admin-lte/build/less/skins/_all-skins.less";

But for this to work, I had to remove those lines otherwise I run out of memory while compiling the less.

**Comment by kurtschindler** [comment]
I think these references simply can be updated to use the "(reference)" modifier as described here http://lesscss.org/features/#import-options-reference

Eg:
@import *(reference)* "../bootstrap-less/mixins.less";
@import *(reference)* "../bootstrap-less/variables.less";

**Comment by almasaeed2010** [comment]
@sniper7kills @kurtschindler Thanks for the suggestions. I added the changes to the local copy and I will push changes to master soon.

**Comment by devmark** [comment]
bower with bootstrap also get out of memory

**Comment by gfpacheco** [comment]
Hi, I just used Yeoman's `angular-fullstack` generator and added AdminLTE through bower and I'm facing the memory issue, even with the `(reference)` part.

My `app.less` file:
 ```less
@import '../bower_components/bootstrap/less/bootstrap.less';
@import '../bower_components/font-awesome/less/font-awesome.less';
@import '../bower_components/AdminLTE/build/less/AdminLTE.less';
...
```

What am I missing?

**Comment by austenc** [comment]
I'm late to the party, but also receiving the out of memory error with the latest version. Similar `.less` file to @gfpacheco -- removing the bootstrap import lines makes everything work fine. Would a pull request with an additional `AdminLTE-only.less` file be considered?
