### ISSUE TITLE
Showing right sidebar notification labels in minibar mode by default

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#415]
Currently the highlighted labels below are hidden in the minibar mode. Those labels are used for notification which means those notifications can be received by the user when the sidebar is expanded only. It would be great for usability to show them also in the minibar mode too by default in a way similar to the top menu notification labels.
![adminlte_icons](https://cloud.githubusercontent.com/assets/9349772/7554159/a6efbb28-f725-11e4-92c4-476b3efe0ebe.png)

**Comment by almasaeed2010** [comment]
I am aware of the issue but unfortunately the only fix for it is to change the markup. It should work with the current version if you place the labels in the ```<span>``` that contains the text. I will test and get back to you.

**Comment by YasserHassan** [comment]
This would be a good fix as displaying it in both expanded and mini mode should be the default in my opinion.

**Comment by YasserHassan** [comment]
I tried it, did not work. Probably a good alternative would be adding them over the icons the same way with the nav bar icons at the top instead of to the right of the text. This way it will keep the look consistent in both modes. I think this would be better.
