### ISSUE TITLE
Scroll bar overlap with main content in IE 10

### ISSUE THREAD

**Issue by sky3913** [almasaeed2010/AdminLTE#416]
Hi,
I'm using this template (starter.html) to design my admin layout. I create dummy data and display it in table. When I scroll down the page, this work fine for Chrome 42 and Firefox 37 but there is a problem in IE 10, as below: (see the red circles)
<img src="https://dl.dropboxusercontent.com/u/94697186/SSS.png" />

Mostly our users still using IE 10. How to fix this is problem?
Thank you.

**Comment by almasaeed2010** [comment]
That would be an IE issue. They chose to let the scrollbar to float over the content. I apologize but this is not an AdminLTE issue. 

AdminLTE offers a boxed layout that would deal with this if you find it an issue. Add the  ```layout-boxed``` class to the body tag and test.

Thank you.

**Comment by giaesp** [comment]
I can't see the attached image, but I think this is the same problem I had. 
You can add this line to the AdminLTE.css, for the body,html to make IE scrollbar behavior pretty "normal".

-ms-overflow-style: scrollbar;
