### ISSUE TITLE
Incorrenct Bower version

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#417]
The version mentioned in bower.json file says 2.1.0. This seems to be repeating so I'm evaluating if it's better to use the PHP Composer package instead as it seems to be more reliable in this area.

**Comment by YasserHassan** [comment]
@almasaeed2010 I am thinking of a way having some sort of automated version update from a single location that holds the current version as a string and triggered either automatically (on file update) or manually to update that version whenever required (e.g. HTML template, bower.json file) alone with anything else that may require repetitive manual update. This will make it consistent everywhere and also simplify the process. What do you think?

**Comment by almasaeed2010** [comment]
This is very annoying specially when releasing quick-fixes or patches. I seem to always miss to update the version in some file.

**Comment by YasserHassan** [comment]
Of course it'd be confusing to try to remember and keep track of those files. I'm thinking of two approaches to handle that. The first is a manual one by keeping a release checklist like:

Release List:
- Update version bower.json
- Update version in package.json
- Update version in index2.html
- ...etc

The other approach is using templates for those specific files. The checklist would be a very simple yet effective approach.

**Comment by almasaeed2010** [comment]
That's a good idea. Thank you for providing this. I will create a similar list to help me remember before I release next versions.

**Comment by YasserHassan** [comment]
@almasaeed2010 I am glad I could help.
