### ISSUE TITLE
preventDefaults issues when using template via AngularJS

### ISSUE THREAD

**Issue by P1X3** [almasaeed2010/AdminLTE#418]
This is menu that I generate using AngularJS

          <ul class="sidebar-menu" ng-controller="MenuCtrl">
            <li class="header">MAIN NAVIGATION</li>
            
            <li ng-repeat="menuItem in menuItems" ng-class="hasSubmenu(menuItem)">
              <a href="{{menuItem.url}}"><span ng-bind="menuItem.title"></span><i class="fa fa-angle-left pull-right" ng-show="menuItem.menu"></i></a>
              <ul class="treeview-menu" ng-show="menuItem.menu">
                <li ng-repeat="menuSubItem in menuItem.menu"><a href="{{menuSubItem.url}}" ng-bind="menuSubItem.title"></a></li>
              </ul>
            </li>
          </ul>

hasSubmenu method returns treeview if there are submenu items. Everything is displayed correctly, however, preventDefaults is called when any of the items without submenus is clicked.

I added another check to see if parent's class is treeview to the following snip and problem is fixed.

      //if this isn't a link, prevent the page from being redirected
      if (checkElement.is('.treeview-menu') && $this.parent("li").is('.treeview')) {
        e.preventDefault();
      }

Thought that maybe this is worth mentioning

**Comment by almasaeed2010** [comment]
Thank you for sharing this. I will look into it.
