### ISSUE TITLE
custom tree view sidebar

### ISSUE THREAD

**Issue by agstwn** [almasaeed2010/AdminLTE#419]
Hello,

In your javascript code there a function to find tag "li" has class active, so when in each page html when i click it will became active. what if i slice into tree part, header.php, body.php, and footer.php.
in header will contain header and sidebar. so i delete the class active.
is it possible to custom app.js? 
so when i click the tag "li" it will became active.

**Comment by josebailo** [comment]
Here explains how to edit app.js file.

https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#adminlte-options

**Comment by almasaeed2010** [comment]
This could easily be done using the following javascript:

```js
$(".sidebar-menu li").click(function(){
  $(this).toggleClass('active');
});
```

Is this what you are looking for?
