### ISSUE TITLE
Scrollable minibar in fixed layout

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#420]
Currently in fixed layout mode, the minibar is forced to expand on hover regardless of how the developer sets it. Usability-wise, this can be annoying when the application is used for a while, at least it would be good to have the option to avoid it. I believe this was done for technical reasons to handle long menus extending below the lower screen edge. Is it possible to make the minibar scrollable in the same manner as the expanded mode via slimscroll? It would be much better for usability.

**Comment by almasaeed2010** [comment]
The expand on hover mode is necessary if SlimScroll is used, and the fixed layout does not work without SlimScroll. the problem that SlimScroll causes is the inability to overflow content from the sidebar, which disallows the sidebar-mini from showing the links to begin with. Unfortunately, this is the only method I could come up with that solves this problem.

**Comment by YasserHassan** [comment]
Is it possible to use an alternative to slimScroll, maybe in a later version? It seems that there are several viable alternatives out there.

**Comment by almasaeed2010** [comment]
That's the plan. I am trying to create an easy transition from slimscroll to a different plugin.

**Comment by IrvingRodriguez** [comment]
I am using the fixed and sidebar-mini class  in my body tag, but I had the same problem as you did in the collapsing sidebar when I hovered over the menu.

**I have the code for this problem, you should find this line in app.js or adminlte.js**
` PushMenu.prototype.init = function () {
    if (this.options.expandOnHover
      || ($('body').is(Selector.mini + Selector.layoutFixed))) {
      this.expandOnHover()
      $('body').addClass(ClassName.expandFeature)
    }`

**Now you must comment these two lines codes**
   `  // this.expandOnHover()
     // $('body').addClass(ClassName.expandFeature)`

**I hope I can help you **
