### ISSUE TITLE
Option to hide minibar hover popup menu text

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#421]
It would be good to have an option to avoid showing the minibar icon names that pop up on hover. Such option can be used when the sidebar consists of single-level menus only. After using the application for a while, such text wouldn't be required by the user.

Note: The closest thing to I found to this was setting `enableBSToppltip` to `false` but did not work out.

![menu-text](https://cloud.githubusercontent.com/assets/9349772/7596735/9d01e0d0-f8f8-11e4-896f-8efdc076b1f7.png)

**Comment by nazarparuna** [comment]
@YasserHassan @almasaeed2010  So, are there any solution?
