### ISSUE TITLE
Simple table > Responsive Hover Table

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#422]
Good evening!

The "Responsive Hover Table" from "Simple table" page have a problem in the box-header.

Since the search input has a custom style (width 150), it is creating a invisible space above all the box header. You can see this problem by trying to select the box title.

To solve this little issue, transfer the custom style to the div above, like:

```html
<div class="input-group" style="width: 150px;">
```

Best regards.

**Comment by almasaeed2010** [comment]
Thanks for the suggestion. Fixed in master.
