### ISSUE TITLE
Unable to change the chat box height/width

### ISSUE THREAD

**Issue by marcus6431** [almasaeed2010/AdminLTE#423]
Hi, i currently having a problem to change the size of the chat box that have inside the adminLTe template. I'm trying to search for possible css file to resize it but failed to do so. May i know where is the exact place to change the css for the chat box size? Thanks

Here are my chat box :

![untitled](https://cloud.githubusercontent.com/assets/11958254/7607175/f1bc8082-f991-11e4-8dfa-e68da5de3672.png)

How can i make it longer? Thanks and best regards.

**Comment by Vorlif** [comment]
You must edit the AdminLTE.css. Search for the line: 
```
.direct-chat-messages {
  -webkit-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
  padding: 10px;
  height: 250px;
  overflow: auto;
}
```
and change the parameter ```height: 250px;``` to your favorit height. For a chat over the full length of the website delete the parameters ```height: 250px;``` and ```overflow: auto;```

Best regards.

**Comment by marcus6431** [comment]
Hi there, I cound't find any code that have .direct-chat-messages.

Mind to tell me which line is that at? 

Thanks

**Comment by Vorlif** [comment]
You use the last version of AdminLTE?
[Show Lines](https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/AdminLTE.css#L2599-L2607)

**Comment by marcus6431** [comment]
I think im using an old version of AdminLTe.

Anyway to replace with new version? As i currently having some page working on AdminLte already, i don't wish to replaced those pages. Or i just need to replace the css and js file from new version into my current version of AdminLte only? 

Thanks and best regards

**Comment by Vorlif** [comment]
Okay, 
I think you use the old branch. (Version < 2).
In this case you can to that. 

In the app.js you search for:
```var a = f.extend({width: "auto", height: "250px"...```
and edit the height to your favorit height.
If you use the dashboard.js it ist the same for:
```
    $('#chat-box').slimScroll({
        height: '500px'
    });
```

But I recommend you to switch to the new version. The code is cleaner, it have more features and it is still supported. An upgrade guide can you find in the [https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade](official documentation). Edit your HTML pages, as it stands there. Than you can delete all other files and copy the files from the new version into your folder.

**Comment by marcus6431** [comment]
Okay thanks, i will try that.
