### ISSUE TITLE
Can "collapse" widget default to collapsed state on load?

### ISSUE THREAD

**Issue by BK20** [almasaeed2010/AdminLTE#424]
For boxes that use the "collapse" widget, is there a way to default to the collapsed state (rather than defaulting to the expanded state) when the page is loaded?
Thanks!

              <div class="box box">
                <div class="box-header">
                  <h4 class="box-title">Title Here</h4>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                  </div>
                </div>
                
                <div class="box-body no-padding">
                  <ul>
                  <li><a href="#">Item 1</a></li>
                  <li><a href="#">Item 2</a></li>
                  <li><a href="#">Item 3</a></li>
                  <li><a href="#">Item 4</a></li>
                  </ul>
                  </div>
                  </div>

**Comment by BK20** [comment]
FYI - here is the solution that worked for me:

 
    <div class="box box-solid collapsed-box">
        <div class="box-header">
            <h3 class="box-title">Default Solid Box</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                <button class="btn btn-default btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div style="display: none;" class="box-body">
            Box class: <code>.box.box-solid</code>
            <p>bla bla</p>
        </div>
    </div>

**Comment by alvinmactal** [comment]
what's the solution here?

**Comment by REJack** [comment]
I dont know which version of AdminLTE you use, but in 2.3.x you can add `collapsed-box` to the box class and switch `fa-minus` with `fa-plus` this should work.

**Comment by NajwaLaabid** [comment]
I am not sure if things have changed since this issue was answered, but adding `collapsed-box` to the box class in my case somewhat disabled the toggle option (the box remained collapsed even when I click for it to open). Instead, I had to change the class of the collapsible element from `panel-collapse collapse in` to `panel-collapse collapse`.
