### ISSUE TITLE
Handling box pre/post remove events

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#425]
@almasaeed2010 is there currently a way to detect pre/post box removal (by clicking the remove icon) to perform related actions such as storing that state in a session or connecting to the server or prevent the removal if the update failed, or let the user confirm before the action box removal. Handling other events is also useful such as updating an initially collapsed box via Ajax when expanded but I believe this could be handled via jQuery events.

**Comment by almasaeed2010** [comment]
There isn't currently a way to do that through AdminLTE's app.js. However, I like the idea of adding before/afterRemove and Collapse handlers. I will have to look into it. Thanks for the suggestion.

**Comment by pbihler** [comment]
I submitted a pull request to trigger events after the action is completed.

It's not trivial to privde a stable `before-...` handler, so it's easier to overwrite the standard AdminLTE handler:
```js
var realBoxRemove = $.AdminLTE.boxWidget.remove;
$.AdminLTE.boxWidget.remove = function(element) {
  var box = element.parents(".box").first();
  // decide if to really remove the box, then:
  realBoxRemove.apply(this,arguments); // forward call to original handler
};
```

**Comment by RoelRoel** [comment]
This what I needed! Now an easy way to restore the states...
