### ISSUE TITLE
IE - menu & footer render issue on short pages

### ISSUE THREAD

**Issue by kurtschindler** [almasaeed2010/AdminLTE#431]
Screen cap of the demo site's blank page:

![adminlte-ie-footer](https://cloud.githubusercontent.com/assets/946993/7658676/aed4308c-fb01-11e4-8241-6515a8ed59ae.png)

Pages that are vertically taller & require a scroll bar appear normally.

**Comment by almasaeed2010** [comment]
Does this happen only in IE? If so, could you please provide the version of IE?

**Comment by kurtschindler** [comment]
Only in IE11 (Windows 8). With Dev Tools open, I can't repro it, so haven't gotten to compare against older emulated IE versions.

I can't seem to repro this right now w/ my version of AdminLTE - but I can on your demo site. 

This issue is not a concern to me, I was mainly just sharing in case you weren't aware and want to take a look at it.

**Comment by almasaeed2010** [comment]
Thanks for letting me know. I will try to see if I can get my hands on IE11 as soon as possible.

**Comment by MarkAPhillips** [comment]
Can this be reviewed as when I upgraded from 2.0.5 to 2.1.1 I also see this issue in Firefox and Chrome - before it did not stop at the content end but does now - thanks :-)

**Comment by MarkAPhillips** [comment]
I think its on the .wrapper class 

if you remove position: relative; this works as expected 

in the new version 

```
.wrapper {
    min-height: 100%;
    overflow: hidden !important;
    position: relative;
}
```

in the previous version

```
.wrapper {
    overflow: hidden;
    position: static;
}
```

**Comment by udaykiranreddy** [comment]
please use IE11,  it works better on IE11.

**Comment by MarkAPhillips** [comment]
the initial issue was with IE 11 .... 

I put a temp override on my css as follows:
```
.wrapper {
  position:static!important;
}
```
which works on IE11 , FF and Chrome - suggest you review and update accordingly
