### ISSUE TITLE
I am facing problem with datatable

### ISSUE THREAD

**Issue by pranavpari** [almasaeed2010/AdminLTE#433]
Hello,
there is date field in my datatable and when I am trying to re-order it, It ordering like string for example 
05-04-2015
08-05-2015
15-04-2015
is there any way to fix it?

Thank you

**Comment by almasaeed2010** [comment]
Datatables are provided by the [Datatables plugin](https://www.datatables.net/). Please review their documentation, or post your issue on their [repository](https://github.com/DataTables/DataTables). Sorry for the inconvenience.
