### ISSUE TITLE
Enable slimScroll for control-sidebar in fixed layout

### ISSUE THREAD

**Issue by HEm3R** [almasaeed2010/AdminLTE#434]
SlimScroll is not set for .control-sidebar. Moving the functionality from main sidebar is not possible because of different structure of control-sidebar.

**Comment by almasaeed2010** [comment]
The control sidebar is implemented for different purposes than that of the main sidebar. Thus, the structure of anything in the main sidebar is invalid in the control sidebar. 

If you want to enable slimscroll for the control sidebar, then you can do so by activating it manually using:
```js
$('.control-sidebar').slimscroll({
  //Add your options here
});
```

**Comment by HEm3R** [comment]
We may misunderstand each other, I will try to explain it better.

There is issue with control-sidebar for small screens and window resize. Because slimscroll is not applied  for .control-sidebar, common browser-based sidebar is shown for Fixed layout (and that is not so 'awesome'):

![control-sidebar-slimscroll-1](https://cloud.githubusercontent.com/assets/209931/7670610/5f7ea192-fcab-11e4-9585-bfb8eb768efe.png)

But it is not possible with current html/css for .control-sidebar to simply apply slimsroll in the same way like for sidebar menu (in app.js, fixSidebar() method). When applied, .control-sidebar is stretch to full width of screen:

![control-sdiebar-slimscroll-2](https://cloud.githubusercontent.com/assets/209931/7670636/8271dda8-fcac-11e4-9929-380a2833ddd7.png)

I think slimscroll should by applied for .control-sidebar by default.

**Comment by almasaeed2010** [comment]
It is possible when you define a specific width since SlimScroll requires one. The default width is 230px. 

SlimScroll has brought so much grief to the template and is not being maintained by its creator anymore. In a future release, I will replace this plugin with a more reasonable option. 

Let me know if you need more help in adding slimscroll to your control-sidebar.

**Comment by HEm3R** [comment]
Thank you, I can set it. Actually, I meant it as a feature request rather then a question.
