### ISSUE TITLE
Box containers beark responsive elments sequnce

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#437]
Currently boxes need to be included in containers such as `<div class="col-md-6"></div>` to render properly. This prevents the rearrangement of box elements when one of them is removed as in the shot below. It would be better if either:
- Make the boxes render properly without the need for containers by supporting `col-*-*` classes on the element level) or...
- Give an option to the developer to let the remove function optionally removes the container instead of the element itself.

Option 2 would be tricky though.

Note: I'd expect the remove function to actually remove the DOM element instead of hiding it.
![adminlte_remove](https://cloud.githubusercontent.com/assets/9349772/7669607/68964d50-fc85-11e4-9879-0b48a807fd84.png)

**Comment by almasaeed2010** [comment]
There are multiple ways to achieve this. Using the Bootstrap best practices guide prevents me from using  your first option. The second option won't work since the cols are placed within a ```.row```. The best way to achieve this is to use a layout similar to that of either Dashboard examples.

For e.g,
```html
<div class='row'>
  <div class='col-md-6'>
    <!-- Place elements of left column here -->
    <div class='box'><!-- First Box --></div>
    <div class='box'><!-- Second Box --></div>
    <div class='box'><!-- Third Box --></div>
  </div><!-- /.col -->
  <div class='col-md-6'>
    <!-- Place elements of right column here -->
    <div class='box'><!-- First Box --></div>
    <div class='box'><!-- Second Box --></div>
    <div class='box'><!-- Third Box --></div>
  </div><!-- /.col -->
</div><!-- /.row -->
```

**Comment by YasserHassan** [comment]
I agree on the importance on following the best practices especially in a standard template. It seems that Bootstrap was not designed with the possibility of removing and adding components dynamically with auto rearrangement in mind at the first place. I am evaluating other approaches to this.

**Comment by almasaeed2010** [comment]
I'd suggest a plugin such as Masonry to have the effect you are looking for while preserving responsiveness.

**Comment by YasserHassan** [comment]
Yes Masonry is one of the options. Thank you @almasaeed2010.

**Comment by imhubertj** [comment]
Hi any idea if there is any example on how masonry can be used for the box layout on this template? I not sure how can masonry be used with bootstrap as the column width needs to be define.
