### ISSUE TITLE
Deprecation: flag-icons-css has been renamed to flag-icons

### ISSUE THREAD

**Issue by equada-ew** [almasaeed2010/AdminLTE#4394]
**To Reproduce**
1. `npm i admin-lte@3.2`

**Screenshots**
![image](https://user-images.githubusercontent.com/81673782/162905296-e9de82de-433b-49b7-8658-8e8da98db9eb.png)

**Environment (please complete the following information):**
- AdminLTE Version: v3.2

**Comment by REJack** [comment]
I've updated it, release comes this night (CET)

**Comment by craph** [comment]
Hi @REJack , I think this issue can be closed now because the fix is already merged 😃
