### ISSUE TITLE
Copyright query.

### ISSUE THREAD

**Issue by andrewdartford** [almasaeed2010/AdminLTE#441]
Dear Sir,

I have opened this ticket as both your list email addresses are currently not receiving.

I am interested in your AdminLTE dashboard for a project I will be working on very shortly and have been reading its documentation. Can you please confirm that the copyright is to be included in with other licenses only as per your MIT licence, and that there is no requirement to 'show' the copyright on any web page.  In addition please confirm that you own the entire works including icons.
It is a great looking software and I eagerly await you response so that I can use it.

Kindest regards

Andrew Day

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE has two major resources, which are AdminLTE.css and app.js. Both of these files are created by me and licensed under MIT. Other resources such as plugins are properly licensed under multiple different open source licenses such as MIT, GNU GPL and Open Source Software. For each plugin, you may want to review its license. You can look for the plugins section within the documentation for a list of integrated plugins. Most of the plugins are licensed under MIT but not all of them. 

AdminLTE requires that you keep the copyright within the source code files that are bundled with the template. However, it does not require to keep the copyright notice in the footer of the template or any other visible elements.
