### ISSUE TITLE
Do not hide sidebar for small screens?

### ISSUE THREAD

**Issue by jamesmcm** [almasaeed2010/AdminLTE#442]
Is there anyway of not hiding the sidebar for small screens? As this makes it impossible to navigate the dashboard on mobiles, etc.

Ideally, the sidebar could be converted to another layout and moved to the bottom of the page in this case.

**Comment by jamesmcm** [comment]
Even something like this: http://www.bootply.com/128936# - with a toggle button on a small screen, would be useful but I couldn't get it to work with toggling sidebar-collapse.

**Comment by almasaeed2010** [comment]
AdminLTE implements a push menu for small screens. Similar to what you posted. The navigation is accessible through the sidebar-toggle button on the lower left corner of the navbar on small screens and next to the logo on large screens.
