### ISSUE TITLE
Triggering events on left/right sidebars show/hide/minimize

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#444]
In other words, any change in left and sidebar sizes. This would be useful where handling such events is needed.

**Comment by chuygb** [comment]
or provide a hook to insert our call to refresh other plugins like tableTools

**Comment by YasserHassan** [comment]
@almasaeed2010 do you have a naming convention for events? I want to name the events triggered when the left sidebar is expanded or collapsed and I'm thinking of using the event names `expanded.pushMenu` and `collapsed.pushMenu` respectively. What do you think? Notice that the same convention should be used later for the right sidebar.

**Comment by luicaps** [comment]
What about providing the very same events when the collapsing ends? Since `expanded.pushMenu` and `collapsed.pushMenu` are triggered on `addClass` and `removeClass` respectively, it doesn't wait for the toggle animation to end.
