### ISSUE TITLE
Triggering window resize event on resizing sidebars

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#445]
Some responsive features in some JavaScript libraries and jQuery plugins work by handling the `window` `resize` event. AdminLTE's sidebars are tricky in that they require the same responsive handling by page elements when the sidebars sizes change but the affected elements can not feel that. For this reason I'm suggesting triggering window resize events (e.g. `$(window).trigger('resize');`) when the states of the sidebars change as follows:
- Right sidebar is shown or hidden.
- Left sidebar is shown, hidden, or minimized to minibar.
Of course this does not apply to the minibar over state.

Note: This might overlap with issue #444.

**Comment by almasaeed2010** [comment]
I tested this just now and it caused major issue with some charts libraries and the layout construction in AdminLTE. 

Thanks for the suggestion.
