### ISSUE TITLE
AdminLTE on Laravel. Switching default Laravel Boilerplate/Scaffolding to adminLTE with adminlte-laravel package

### ISSUE THREAD

**Issue by acacha** [almasaeed2010/AdminLTE#447]
Hi all,

First of all congratulations @almasaeed2010 for this awesome template. Very impressive!

At:

https://github.com/acacha/adminlte-laravel

You can find my contribution, a Laravel package to install adminLTE on Laravel overwriting default auth  Laravel pages, home page and error pages in few steps:

First install Laravel (http://laravel.com/docs/5.0/installation) and then Create a new Laravel project:

<pre>
 $ laravel new laravel-with-admin-lte
 $ cd laravel-with-admin-lte
</pre>

Add admint-lte Laravel package with:

<pre>
 $ composer require "acacha/admin-lte-template-laravel:0.*"
</pre> 
 
Register ServiceProvider editing **config/app.php** file and adding to providers array:

<pre> 
 // AdminLTE template provider
 'Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider',
</pre>

Publish files with:

<pre>
 $ php artisan vendor:publish --force --provider="Acacha\AdminLTETemplateLaravel\app\Providers\AdminLTETemplateServiceProvider"
</pre> 

Kind regards,

Sergi Tur Badenas

**Comment by almasaeed2010** [comment]
This sounds interesting. I hope some us benefit of it. Thanks for sharing!
