### ISSUE TITLE
Sidebar-mini with fixed

### ISSUE THREAD

**Issue by AndrewLag** [almasaeed2010/AdminLTE#451]
Why is it not possibile to have the sidebar-mini (with no hover effect) and the fixed layout?

**Comment by SylvainSimon** [comment]
Yeah, good question, i agree this issue, why ?

**Comment by YasserHassan** [comment]
To avoid duplication, issue #420 addressed the same subject.

**Comment by AndrewLag** [comment]
@YasserHassan Sorry, didn't find that.

**Comment by almasaeed2010** [comment]
@YasserHassan thanks for providing the link.

@AndrewLag I hope you understand the issue I am facing with SlimScroll. Hopefully in a future release I'll be able to provide a solution. Thanks!
