### ISSUE TITLE
fastclick use with internet explorer

### ISSUE THREAD

**Issue by SylvainSimon** [almasaeed2010/AdminLTE#452]
On internet explorer (8, 9, 10 and last), fastclick.js are notification error in console.

![image](https://cloud.githubusercontent.com/assets/11244274/7747363/1309427e-ffba-11e4-9135-b9ec8d766420.png)

It's issue of adminLte or fastclick implementation ?

**Comment by almasaeed2010** [comment]
Hello,

This should be reported to the [FastClick repository](https://github.com/ftlabs/fastclick). 

Thanks!
