### ISSUE TITLE
jQueryUI wrong version?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#453]
Hello!

Is AdminLTE shipping an outdated version of jQueryUI in plugins/jQueryUI?

For example, index.html uses the following js:

> http://code.jquery.com/ui/1.11.2/jquery-ui.min.js

but AdminLTE has a local jQueryUI plugin copy using version 1.10.3.

My suggestions:
1: Remove plugins/jQueryUI from the project; or
2: Update the plugins/jQueryUI version, to match the index.html sample.

Thanks.

**Comment by almasaeed2010** [comment]
Hi,

The lack of use of jQueryUI in AdminLTE makes me forget updating it with every release.

I have decided to use bower in the future to avoid this issue from happening again. For now, I will update it manually.

**Comment by almasaeed2010** [comment]
Fixed in master.
