### ISSUE TITLE
JS Loading Errors on Homepage

### ISSUE THREAD

**Issue by LifeH2O** [almasaeed2010/AdminLTE#455]
Please see these errors
![adminlte](https://cloud.githubusercontent.com/assets/385283/7787801/352cf582-0238-11e5-8545-94d4ae0dd82e.png)

**Comment by LifeH2O** [comment]
This is probably solved by disabling protection
![adminlte2](https://cloud.githubusercontent.com/assets/385283/7787817/ee8cf090-0238-11e5-980e-a92c0c2a957e.png)

**Comment by emmerink** [comment]
I made a fix for it here:
https://github.com/gionnivaleriana/laravel-adminlte/pull/6

These cdn's can all be accessed over https, so they can be easily changed (no need to turn off security in that case).

**Comment by almasaeed2010** [comment]
Fixed in master and updated demo.
