### ISSUE TITLE
Increasing chart height when window is resized

### ISSUE THREAD

**Issue by dongperez** [almasaeed2010/AdminLTE#461]
Using the demo page (https://almsaeedstudio.com/themes/AdminLTE/index2.html), try to resize the current window by dragging the bottom of the window up and down for several times. The height of the chart (id="salesChart") increases, causing the chart to also increase its height.

**Comment by almasaeed2010** [comment]
That's an issue with the [CharJS](https://github.com/nnnick/Chart.js/) library. Please report this to their issues section.
