### ISSUE TITLE
Support for Internet explorer

### ISSUE THREAD

**Issue by eothein** [almasaeed2010/AdminLTE#462]
Dear Almasaeed

Again, I appreciate the template a lot. It works well for FireFox and for Chrome, but it seems the layout is completely destroyed when using Internet explorer. Is this a known issue? Or is there anything special which needs to be done to have support for this?

Kind regards

Jens Buysse

**Comment by rafael-renan-pacheco** [comment]
Hello eothein!

Can you provide some screenshot and your IE version?

In IE 8.0 the layout loads 90% correct, with some problems in jQuery.

Look for js errors after loading AdminLTE in IE.

**Comment by eothein** [comment]
Dear Rafael

Here is a screen shot. It just an application of the basic starter page in a Yii2 project. IN Chrome/firefox everything is fine but it seems IE is destroying the layout. (IE version 11.0.9600.17801 to be precise) 

![screenshot](https://cloud.githubusercontent.com/assets/7603307/7802575/cc1c8272-0338-11e5-8c53-15e27569f1d3.jpg)

**Comment by rafael-renan-pacheco** [comment]
Sorry, I don't have Windows 8.1 to try AdminLTE on IE11.

Have you tried to load AdminLTE out of the box, without using Yii2? If AdminLTE does work in IE11, than your app running on Yii2 is missing some references.

Just download the last release and open index.html on IE 11.

**Comment by eothein** [comment]
It seems there is a mistake loading the jQuery script. Debugging in IE stops and states that "addeventlistener is not a function" for line 

"// Use the handy event callback
			document.addEventListener( "DOMContentLoaded", completed, false );"

Then all the other javascript files (using jQuery) fail and probably that's why the layout flips. I'll look for a solution.

Jens

**Comment by almasaeed2010** [comment]
I tested the template on IE11 but it worked as expected. From the screenshot, it seems like there is either a markup error or a resource not found error. Please check that both of these issues don't exist.

**Comment by eothein** [comment]
My code seems to be the same as the example template, with the addition of Yii2 souce files. Could there be a problem there?

**Comment by rafael-renan-pacheco** [comment]
@eothein before testing things with Yii2, just try the default AdminLTE installation on IE 11. Download the package, and open the page on IE 11. If the page loads without bug, then you can start to search the bug in your Yii2 project.

**Comment by eothein** [comment]
@rafael-renan-pacheco @almasaeed2010 

When doing a clean test (without Yii2) there is indeed no problem in IE 11. When just copying the same code and adjusting the necessary parameters (Yii2 uses asset bundles to load css and js files) IE 11 completely messes up (while firefox and Chrome work perfectly). 

I'll upload a screenshot where you can see what goes wrong (beneaht). It is in dutch but I'll translate the red sentences:
- The method or property of evenlistener is not supported by this object
- jQuery is not defined
- Bootstrap's Javascript requires jQuery
- AdminLTE  requires jQuery

So it seems something is not correct with jQuery, alhought the file is loaded correctly. So I don't know where to fo from here.

I have put the code generated by Yii2 here: http://txs.io/sG3b 
![test](https://cloud.githubusercontent.com/assets/7603307/7944654/5b2ebd7a-096c-11e5-97e2-902598f71429.png)

**Comment by rafael-renan-pacheco** [comment]
Now compare the clean html with the Yii2 generated html.

**Comment by eothein** [comment]
As addition: I tried the template provided here https://github.com/dmstr/yii2-adminlte-asset

Even just a clean install (without any major changes) renders the same problems

**Comment by eothein** [comment]
@rafael-renan-pacheco A div with the clean html does not show any major differences...

**Comment by almasaeed2010** [comment]
@eothein I am not the developer of yii2-adminlte-asset, nor do I support it. Please refer back to the creator of the package to review the error. Since I tested the main AdminLTE on IE11 and it worked fine, then the problem must be in the implementation of the package you are using. I apologize for the inconvenience. 

I may be able to help if I have access to your base code. That way, I can analyze the produced HTML and point you to the issue. Thanks!

**Comment by rafael-renan-pacheco** [comment]
Hi @eothein, check if this solve your problem: #478 

UTF8+BOM crash some pages using php frameworks.

**Comment by eothein** [comment]
Dear all

thanks for the ideas. I will try to apply them during the week (now have to focus on another project :) 

I'll keep you posted!
