### ISSUE TITLE
Top nav-bar is occupying exta length

### ISSUE THREAD

**Issue by watoo** [almasaeed2010/AdminLTE#463]
![untitled](https://cloud.githubusercontent.com/assets/5346797/7814703/aeebe18a-0378-11e5-8bdb-1d91a6fa6ea0.png)
the top navigation bar (highlighted in red) is taking exta height. However its working fine in small size(col-xs-* and col-sm-*).If i resize it from css Pierce (name on right side of nav-bar) hides. I have spent four hours but cannot figure out why its not working properly.

**Comment by almasaeed2010** [comment]
Please all resources correctly first. By not loading the resources correctly, the layout is prone to multiple types of errors. Make sure the images exist and are reachable by the browser. If the issue persists with all resources loaded correctly, please let us know.

**Comment by watoo** [comment]
Problem was solved. Thanks.
