### ISSUE TITLE
Using sparkline inline graphs in collapsable items

### ISSUE THREAD

**Issue by kurtserP** [almasaeed2010/AdminLTE#466]
Hey,
Trying to implement sparkline inline graphs provided together with the packages, within items which are collapsable (tabs/accordions/etc), but it seem no to work.
When I place the "<span class="sparktristate">1,1,0,1,-1,-1,1,-1,0,0,1,1</span>" (or any other type) outside a collapsable item and call it via:

$('.sparktristate').sparkline('html', {
		type: 'tristate',
		tooltipFormat: '{{value:levels}}',
		tooltipValueLookups: {
        levels: $.range_map({ '-1': 'Incorrect', '0': 'Non responsive', '1': 'Correct' })
}});

it seems ok (running and plotting), but when inside of a collapsed item, when it is opened it just shows the "1,1,0,1,-1,-1,1,-1,0,0,1,1" without the graph. Any ideas how to fix this?

Thank you

**Comment by almasaeed2010** [comment]
This is a sparkline issue and should be reported to their [repository](https://github.com/gwatts/jquery.sparkline). 

The way I'd approach this as a quick fix is to attach a listener to the collapsible element. Once the element is expanded, I'd redraw the graph.

**Comment by kurtserP** [comment]
Thank you for your answer, will report there.
As for your suggestion, adding a listener does work, but unfortunately since sparkline uses the HTML within the tags, and replaces it, the listener can be used only once, or only for static graphs that are used once (not by class but by ID).
For future reference of whomever is searching - found a not so good solution for now (of keeping all tabs/accordions open until the graphs are loaded and then collapse all un-needed), but hope to get a better solution from sparkline. 
Thank you
