### ISSUE TITLE
Split View for the Email Page

### ISSUE THREAD

**Issue by murliatdure** [almasaeed2010/AdminLTE#468]
Similar to Syrena Admin bootstrap theme -or- Pages Theme (pages.revox.io)

![image](https://cloud.githubusercontent.com/assets/7137859/7886226/44924df8-0646-11e5-8031-b5a7e1bdfa52.png)

![image](https://cloud.githubusercontent.com/assets/7137859/7886238/57cb6eae-0646-11e5-8159-492336e1f1ad.png)

**Comment by almasaeed2010** [comment]
This does look nice and perhaps even more user friendly. However, I am not gonna be able to implement such a change at this time. This would be a great addition to AdminLTE when it reaches version 3.0, which I'll start to work on when Bootstrap 4 comes out. Thanks for the suggestion.
