### ISSUE TITLE
is there any chance for rtl.css, please ?

### ISSUE THREAD

**Issue by AMoktar** [almasaeed2010/AdminLTE#469]
First let me congratulate you for this great design & code.
I'm wondering if you will develop a rtl.css file to set direction and text-aligin and float and such properties for all page elements .
I think it will be great for some people including me.
Thanks

**Comment by YasserHassan** [comment]
@AMoktar you can refer to #23, #313, and #374 for details about this topic.

**Comment by almasaeed2010** [comment]
Unfortunately, I won't be able to create and maintain an RTL release. However, you may look for forks that have implemented this feature. This is one of them https://github.com/Yellowen/AdminLTE-rtl

Perhaps a Google search would provide more results.

**Comment by hooman-pro** [comment]
hi, thank you for your very good themeplate .
I have question. as https://github.com/Yellowen/AdminLTE-rtl is version 1.3 and in readme file you write that rtl support in to do list. i want know when next version with rtl support will release?

**Comment by almasaeed2010** [comment]
It is true that it is in the to-do list and that we plan to implement it. However, I am not sure when we will be able to do it. It may come as soon as with v2.2.0 or as far as v3.0.0. We have encountered multiple errors when using automated services to convert the template. This is mainly because Bootstrap doesn't support RTL to begin with. I apologize for the inconvenience.

**Comment by hooman-pro** [comment]
thank u. that's true bootstrap offically dosent support rtl. but there is rtl version of bootstrap in : https://github.com/morteza/bootstrap-rtl/releases
and as i know bootstrap will not support rtl offically until version 4
if rtl version of admin lte is in your plan you can use it: https://github.com/morteza/bootstrap-rtl/releases

**Comment by masteradhoc** [comment]
@hooman-pro @AMoktar Take a Look at PR #489
