### ISSUE TITLE
How to stay updated?

### ISSUE THREAD

**Issue by LifeH2O** [almasaeed2010/AdminLTE#470]
AdminLTE is being updated frequently on Github. What is the best way to keep my project up to date with bug fixes and new features (not major HTML structure changes)?

**Comment by SylvainSimon** [comment]
Composer ? Bower ?
![image](https://cloud.githubusercontent.com/assets/11244274/7901387/fe769960-0784-11e5-975c-e273f2d47016.png)

**Comment by almasaeed2010** [comment]
@LifeH2O You should never use the master repo in production. Best way to stay updated with latest releases when it comes to front-end assets is to use Bower. Once you set up your project and install AdminLTE via Bower, a simple ```bower update``` command will update all your resources to the latest stable release.
