### ISSUE TITLE
Simplifying CSS by avoiding functional class names

### ISSUE THREAD

**Issue by YasserHassan** [almasaeed2010/AdminLTE#471]
Many CSS classes are named after their functions which makes those names very specific and not ideal for extending their use from an organizational point of view. Sometimes that even bloats the CSS needlessly by creating many classes doing the same thing.

For example, the login page logo uses a class called `login-logo` and the registration page uses the class `register-logo` for the same element (which calls for a 3rd class for the password reminder page) while one neutral name such as `box-logo` would work well for them all. Same goes for classes like `register-page`/`login-page`, `login-box`/`register-box`, `messages-menu`, `notifications-menu`, ...etc.

Naming such classes according to their layout instead of function would make them more relevant when used in any project or function. For simplicity, neutral names could be classified such as `menu-a`, `menu-b`, and so on.

**Comment by almasaeed2010** [comment]
Hi,

I agree with you for the most part. I found it difficult using this convention to duplicate usage of the same class as you suggested. Since I can't change much right now, I am gonna keep this in mind for a future major release. Thank you!

**Comment by YasserHassan** [comment]
I second your opinion @almasaeed2010 that such enhancement should be kept for a major update later to avoid breaking things for current users. Thank you for your efforts.

**Comment by YasserHassan** [comment]
Reopening to keep this enhancements in the open ideas pool.

**Comment by Cryszon** [comment]
Changing the selectors in [dropdown.less](https://github.com/almasaeed2010/AdminLTE/blob/4cd707a49e7a8d9a7a740de9daffc23018844317/build/less/dropdown.less#L27-L30) to something like `.navbar-nav > .list-menu` would be a good start. As a quick fix, you could simply add one extra selector:
```
//Navbar custom dropdown menu
.navbar-nav > .notifications-menu,
.navbar-nav > .messages-menu,
.navbar-nav > .tasks-menu,
.navbar-nav > .list-menu {
```
The notifications, messages and tasks could also be modified to extend from `list-menu`.

This would allow us to define custom (list) menus that would be consistently styled with the default ones.
