### ISSUE TITLE
Left side bar doesn't collapse in IE8

### ISSUE THREAD

**Issue by steep2000** [almasaeed2010/AdminLTE#480]
Hi,

First, thank you for the great job you are doing guys :)

I have an issue with the template in IE8 when i press the toggle button, the sidebar doesn't collapse. What inside the content div, is resizing, but the sidebar stays displayed...

**Comment by masteradhoc** [comment]
HI @steep2000 

IE 8 is not Supported by AdminéLTE im afraid. See https://github.com/almasaeed2010/AdminLTE
<b>Browser Support (IE 9+)</b>

**Comment by steep2000** [comment]
@masteradhoc , Thanks for your answer, but all is working fine for what i did, except the sidebar not collapsing :(

**Comment by masteradhoc** [comment]
Maybe @almasaeed2010 is able to fix this, although its not supported :) Lets see!

**Comment by steep2000** [comment]
I hope !! thanks

**Comment by steep2000** [comment]
@almasaeed2010  @masteradhoc  No news, good news??

**Comment by almasaeed2010** [comment]
As mentioned by @masteradhoc, AdminLTE doesn't support IE8. It won't make sense to add code to support IE8 only to some elements. However, you can implement a custom code that does what you need.

```js
//Detect if browser is IE and return the version or false
function isIE () {
  var myNav = navigator.userAgent.toLowerCase();
  return (myNav.indexOf('msie') != -1) ? parseInt(myNav.split('msie')[1]) : false;
}

if(isIE == 8) {
  $('[data-toggle="offcanvas"]').on('click', function(e) {
    if($('body').is('sidebar-collapse')) {
      $('.main-sidebar').css('left', '230px');
    } else {
      $('.main-sidebar').css('left', '-230px');
    }
  });
}
```

I haven't tested the code since I don't have access to IE8 right now. I hope this gives an idea of how you can support IE8 for the sidebar.
