### ISSUE TITLE
AdminLTE.min.css typo

### ISSUE THREAD

**Issue by extinger** [almasaeed2010/AdminLTE#482]
.label-waring (.label-warNing right) in two places - col 65236,66000

**Comment by masteradhoc** [comment]
Attention. This definately goes deeper. Also found on Line 1295 at General.html!
Will take a look at this

**Comment by masteradhoc** [comment]
Please see incorrect pages below. Gonna greate a pull request now.

![waring_isfound](https://cloud.githubusercontent.com/assets/6242098/7935188/235091a4-092f-11e5-9d66-28c91e034728.png)

**Comment by masteradhoc** [comment]
This issue can be closed now, due the Pull Request #483

**Comment by almasaeed2010** [comment]
This is a serious bug. It's unfortunate that the convenient autocomplete would make you repeat the mistake this many times. Since Bootstrap provides the warning label by default, I think I can merge the pull request without affecting current users. 

Thanks for letting me know!
