### ISSUE TITLE
Select Multiple on Mac doesn't show scrollbar

### ISSUE THREAD

**Issue by jschwartz73** [almasaeed2010/AdminLTE#484]
On Yosemite (and probably Mavericks as well), the select's padding seems to be "pushing" the scrollbars off the rendered area of the select field.

You can see it on the demo here:
https://almsaeedstudio.com/themes/AdminLTE/pages/forms/general.html

Using the trackpad to scroll in the  "Select Multiple" - the scroll bars will never show up.  Additionally, when using the up/down arrow keys, the list will not scroll either.

There is a system preference on OSX to determine how scrollbars render.  The default is this:

System Preferences / General / Show scroll bars - Automatically based on mouse or trackpad

If you change this option to one of the other two options, then the scroll bars render as expected (although the arrow keys still do not work properly)

Any help or suggestions would be appreciated.

![screen shot 2015-06-02 at 10 00 01 pm](https://cloud.githubusercontent.com/assets/935550/7951206/c7c851c0-0972-11e5-96d5-06dc9834d77b.png)

**Comment by almasaeed2010** [comment]
I haven't changed or added to the multiselect menu. If this issue persists, it could be caused by Bootstrap. Any further help would be best acquired from the [Bootstrap issue tracker](https://github.com/twbs/bootstrap/issues). Thanks and I am sorry I apologize for the inconvenience.

**Comment by jschwartz73** [comment]
Thanks for the prompt response.

For reference this was already documented in Bootstrap here:
https://github.com/twbs/bootstrap/issues/12536

They are calling it a webkit bug and filed that here:
https://bugs.webkit.org/show_bug.cgi?id=128489

I'll close this issue.
