### ISSUE TITLE
Bug in footer?

### ISSUE THREAD

**Issue by 314parley** [almasaeed2010/AdminLTE#486]
I've been working on my imageboard management panel, and I have to say I'm very impressed. Unfortunatly though, when I started working on the page seen below, there's a rather unfortunate bug that is displayed. (the white background from the footer stretches into the content) I haven't seen this bug in building my other pages, and I'm wondering weather it was my HTML coding, or just a bug with the footer.
![screen shot 2015-06-03 at 10 14 54 am](https://cloud.githubusercontent.com/assets/1246441/7966517/76f88db6-09d9-11e5-9cad-d68234ecf7dc.png)

**Comment by almasaeed2010** [comment]
That's an HTML error on your part. Please make sure that all divs are properly closed and let me know if the issue persists.

**Comment by 314parley** [comment]
As far as I could check, all of my divs are closed. Could you [double check](https://gist.github.com/314parley/d8734d9fca9554c066f3) my code?

**Comment by 314parley** [comment]
Nevermind, I fixed it. Thanks!
