### ISSUE TITLE
When you will support RTL css in this Template?

### ISSUE THREAD

**Issue by ahmedgaduo1** [almasaeed2010/AdminLTE#487]

**Comment by almasaeed2010** [comment]
There isn't a specific timeline.

**Comment by ahmedgaduo1** [comment]
so is there any way to do that 
because i need it in my project

**Comment by almasaeed2010** [comment]
Please refer to issue #469 
It's not an easy task, unfortunately.

**Comment by masteradhoc** [comment]
@ahmedgaduo1 Take a Look at PR #489
