### ISSUE TITLE
The whell that enables us to choose skin

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#488]
Hi
Long time and thanks a lot to @almasaeed2010 and all the AdminLte community for the great work. @almasaeed2010 , YOU ARE A GENIUS. 

 I have just downloaded the latest version of this awesome template but i can no longer see the whell that enables us to choose the skin ?
What am i missing ?

Tks

**Comment by almasaeed2010** [comment]
Hello,

Thanks for the compliment. The skin chooser is placed in the right sidebar. By clicking the gears icon on the top-right corner of the navbar, you can show/hide the right sidebar.

**Comment by kressly** [comment]
Thanks man. You rock :+1:
