### ISSUE TITLE
CPU usage on Chrome

### ISSUE THREAD

**Issue by xsbr** [almasaeed2010/AdminLTE#490]
Testing a simple page like "pages/UI/general.html" locally on my PC Intel i5 with Chrome consumes 50% from CPU

I found this behavior in many other paid themes but It isn't accepted in a simple page without animations or legacy objects like Flash

![2015-06-05 21_24_49-new notification](https://cloud.githubusercontent.com/assets/214292/8017354/bcf37a96-0bc9-11e5-940c-1b6303f630f2.png)

Chrome Version 43.0.2357.81 32 bits - Windows 10 Preview

I tested it on Mozilla Firefox and CPU usage decreased to 4,5% and Internet Explorer about 4% too
I tested it too on an Incognito tab without extensions

**Comment by xsbr** [comment]
The problem seems to be from "" block

**Comment by xsbr** [comment]
It seems to be a problem with CSS3 Animations.

Bootstrap guys don't care about it, think that it's a browser problem
https://github.com/twbs/bootstrap/issues/4881
https://github.com/twbs/bootstrap/issues/5148

I found an issue in Chromium project:
https://code.google.com/p/chromium/issues/detail?id=429375

So for while if you don't want a high CPU, avoid `.active` with `.progress`

**Comment by almasaeed2010** [comment]
Thank you for providing this information. I am sure this will help many of our users.
