### ISSUE TITLE
Collapsable Box inside modal

### ISSUE THREAD

**Issue by fmobile** [almasaeed2010/AdminLTE#492]
Hi,

I am trying to use a collapsable box inside a modal but for some reason the collapse button doesn't work inside the modal. The modal's content is added dynamically with .load('content.html'), also in the documentation I found this information:
"If you inserted a box into the document after app.js was loaded, you have to activate the collapse/remove buttons explicitly by calling .activateBox()"
so I think that is the case but when I try to use .activateBox() function I get an error and it seems the functions doesn't exist, I also searched for the function in the project but I couldn't find it. 
Please if someone has an idea what could I be doing wrong or how can I use collapsable box inside a modal I'll really appreciate the help.

great project by the way,
thank you

**Comment by fmobile** [comment]
I was going through the library and found the activate function for AdminLTE so I actually made it work using:
 .load(content, function(){ $.AdminLTE.boxWidget.activate();});

so maybe that is the function that the documentation was referring to with .activateBox()?

thanks

**Comment by almasaeed2010** [comment]
Hi,

I mistakenly uploaded the documentation for a newer release that hasn't been fully tested yet. I will create the new release which supports the ```.activateBox()``` function as soon as it is fully tested. Hopefully this will be done soon and you will be able to update your code accordingly. Thank you for bringing this to my attention!

**Comment by fmobile** [comment]
Hi,

no problem and thank you for the reply and the great project you are sharing!

**Comment by almasaeed2010** [comment]
Updated docs and released newest changes. The function should properly work now.

**Comment by fmobile** [comment]
Thank you so much!

**Comment by nicojmb** [comment]
Hi, This not work for me i've modified this line and now work Ok.
<code>
// Listen for collapse event triggers
// $(_box).find(_this.selectors.collapse).on('click', function (e) {
$(document).on('click',_this.selectors.collapse, function (e) {
    e.preventDefault();
    _this.collapse($(this));
});
</code>

**Comment by fmobile** [comment]
It works for me as I did it before with  $.AdminLTE.boxWidget.activate(); and now I am using .activateBox(). One think I must say is that you have to call .activateBox() after the modal is created, in my case I was creating the modal and loading the content from a html file so I had to call .activateBox() in the callback function (when load is complete):
```
.load(content, function(){ 
    $('#boxID').activateBox(); 
});
```
If you are not loading your content from a html file then you just have to be sure your html content is ready and you can start using jquery and making references to the elements. This is one way to check your document is ready:
```
$(function(){//document ready
     $('#boxID').activateBox();
}
```
I hope this helps.

**Comment by nicojmb** [comment]
Hi, it's not works for me, i don't know the element ID.

i've a function to show modals dynamically

<pre>
// Modal AJAX Call
    $('body').on("click", ".modal-ajax", function (e) {
        var element = $(this);
        $.ajax({
            type: "POST",
            url: element.attr('data-url')
        }
        ).done(function (response) {
            $('section.content').append(response);
            $(element.attr('data-modal-id')).modal('show');
            $(element.attr('data-modal-id')).on('shown.bs.modal', function () {
                load_editor();
                load_select();
                load_datepickers();
                load_xeditables();
                load_auto_numeric();
                load_google_maps_modal($(this));
            });
            $(element.attr('data-modal-id')).on('hidden.bs.modal', function () {
                $(this).removeData('bs.modal');
                $(this).remove();
            });
        });
        e.preventDefault();
    });
</pre>

**Comment by fmobile** [comment]
Hi,

well, lets say you have a box inside your modal, for example:
```
<div class="box box-primary" id="boxID">
	<div class="box-header with-border">
	  <h3 class="box-title">Your title</h3>
	  <div class="box-tools">
	    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
	  </div>
	</div>
	<div class="box-body no-padding">
	  your body  
	</div>
</div>
```
If you are not using an ID for your box then one way to get your box could be:
```
$('.box')
```
or use whatever optimized selector you want to get you box (or boxes), so you can activate the collapsable element for that box like this:
```
.on('shown.bs.modal', function () {
   ...
   $('.box').activateBox();
}
```
just make sure that this function is actually been fired, maybe you can debug or even print in console  your box element to make sure you are getting the box (or boxes) you want to activate.

hope this helps.
