### ISSUE TITLE
Slimscroll + mini-sidebar and menu over the wrapper

### ISSUE THREAD

**Issue by Seiifer** [almasaeed2010/AdminLTE#496]
Hi,
first, thanks for this template you are providing to us.

I noticed that when we add the slimscroll to the `sidebar-menu` on the left, the menu is not showed anymore on hover on `sidebar-mini`.

So I tried to remove the `slimscroll` class to the `ul` it was initially affected to when the menu is becoming `sidebar-mini` but nothing changed.

Maybe I did something wrong, I read slimscroll plugin caused a few issues at this level. But shouldn't it work if we apply it only when the menu is expanded ?

Also is there a way/option to make the menu be expanded over the content of the page instead of moving the content to the right (a shift equals to the menu's width) ?

Regards.

**Comment by almasaeed2010** [comment]
Hello,

The fixed layout requires the slimscroll plugin for the sidebar to function. Removing the slimscroll plugin would not solve the problem and it will cause more issues. For the time being, you cannot have a fixed layout and sidebar mini mixed together. Sorry for the inconvenience.
