### ISSUE TITLE
Google fonts imported

### ISSUE THREAD

**Issue by samuel4x4** [almasaeed2010/AdminLTE#498]
Hello,

I just noticed in https://github.com/almasaeed2010/AdminLTE/blob/master/dist/css/AdminLTE.css

you import some external google fonts

@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);

Some applications we create are not designed to have any external internet access, so we're geting some issues there. 

I'm using https://github.com/sonata-project/SonataAdminBundle, it uses AdminLTE and we have an issue with external requests.

Do you think it's possible to put the sources of those fonts in some distinct .css files and use them from there, instead of trying to make internet requests?

Thanks a lot for your great job ;)

**Comment by samuel4x4** [comment]
https://github.com/sonata-project/SonataAdminBundle/issues/3040#issuecomment-110362144

Another good option can be to separate @import from main css file in order for any project that use it to make theirs rules inside.

**Comment by almasaeed2010** [comment]
It would be difficult to download and create all the requirements for the font to load properly without the Google Fonts CDN. I agree though that removing the ```@import``` from the CSS files and putting in the HTML files instead is a good idea. Also, it would be nice to have a LESS variable to define the font that user would like to use instead of forcing a certain font. 

If you need the font locally, you might want to look up how to download Google fonts because I am not sure how to do it.

Thanks for the suggestion!

**Comment by Soullivaneuh** [comment]
> putting in the HTML files instead is a good idea.

Please not css inline on HTML. :-)

Make a `fonts.[less|css]` file with the `@import` inside would be better. :+1:

**Comment by almasaeed2010** [comment]
@Soullivaneuh consider updating the template after changing your font. Your suggestion doesn't change the fact that the compiled CSS file has the ```@import``` statement. In reality, HTML files are not used as is and the layout is somewhat recreated in views to support metas and other tags that the user might define, which include fonts. This simplifies the updating process. However, it is not yet possible to do such a change until v2.2.0 comes out.

**Comment by Soullivaneuh** [comment]
> Your suggestion doesn't change the fact that the compiled CSS file

We could apply the same solution as I proposed for js files: https://github.com/almasaeed2010/AdminLTE/issues/303#issuecomment-85481930

**Comment by rafael-renan-pacheco** [comment]
I used www.localfont.com to download google fonts to my internetless (a.k.a full of firewall) project.

This site download the google fonts based on the types you select, and creates a CSS for multi-browser compatibily, the same CSS google cdn creates dynamically.

And if I remeber, I had to change some AdminLTE css to load the local font css, and not the cdn one.

**Comment by Soullivaneuh** [comment]
@rafael-renan-pacheco This is a solution but with that, we have to add vendor code onto ours git repositories.

A bower equivalent would be much better IMO.

**Comment by danielrsmith** [comment]
This seems like a niche request, and doesn't seem like something that the AdminLTE project should have to maintain.

**Comment by Soullivaneuh** [comment]
> This seems like a niche request

What do you mean?

**Comment by danielrsmith** [comment]
It's common for Google fonts to import them in this manner, and reduces the number of requested to the web server that the app is being hosted on.  Just my opinion, but I wouldn't vote to include the font files in the project.  Adding a separate fonts.css though sounds like a viable option to allow users to customize how font's are retrieved.

**Comment by alien3d** [comment]
vote+ . I also do manually cut from google request and replace to local version.  Most of admin panel will be used in local enviroment. No need to request round the world . Some intranet application might host internal and without internet connection..

**Comment by almasaeed2010** [comment]
I am not gonna download the font and maintain it manually. I am just gonna remove it from the CSS file and add it to the HTML pages.
