### ISSUE TITLE
plugin datepicker inside modal 

### ISSUE THREAD

**Issue by fmobile** [almasaeed2010/AdminLTE#500]
Hi,

I was trying to use the datepicker plugin inside a modal and noticed that is positioned under the modal and modal's black background so i found several fixes over the internet but this one worked for me:

in file AdminLTE/plugins/datepicker/datepicker3.css line 765 

.datepicker.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  (765) z-index: 1151 !important;   instead of z-index: 1000;
...

also in lines 780, 781 there is a '*' at the beginning of the lines

*border-right-width: 2px;
*border-bottom-width: 2px; 

I am commenting here because I searched for bootstrap-datepicker's github project and found that the file bootstrap-datepicker3.css doesn't have the .datepicker.dropdown-menu class so that is why I am commenting about it here.

I hope this is somehow useful,
thanks

**Comment by almasaeed2010** [comment]
Hi,

Did you try placing the dropdown in relatively positioned container? 

```html
<!-- In the model-body -->
<div style="position: relative;">
  <!-- Place dropdown here -->
</div>
```

Thanks.

**Comment by fmobile** [comment]
Hi,

I am sorry but  I think  don't get where to put the position: relative.
Here is the code to create the date input:
```
<div id="sandbox-container">
	<div class="input-group date">
		<input type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
	</div>
</div>
```
thank you!

**Comment by almasaeed2010** [comment]
Try this first:
```
<div id="sandbox-container" style="position: relative;">
	<div class="input-group date">
		<input type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
	</div>
</div>
```

If doesn't work, try to wrap that in a relatively positioned container:
```
<div class="position: relative;">
<div id="sandbox-container">
	<div class="input-group date">
		<input type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
	</div>
</div>
</div>
```

I hope this helps.

**Comment by fmobile** [comment]
Hi

I tried both but it didn't work, the datepicker still appears underneath the modal and the transparent background.
Maybe  it's not the best option but meanwhile in order to make it work I changed the z-index in the css file.

Thank you!
