### ISSUE TITLE
Allow late initialization

### ISSUE THREAD

**Issue by rjstanford** [almasaeed2010/AdminLTE#501]
I love the theme - thank you for licensing it so liberally.

I'm trying to incorporate it into a similarly MIT-licensed lightweight framework that I'm authoring, and was wondering if you'd be interested in a very minor tweak.  Since it deploys as a single-page app, themes flip between authenticated and public views.

I found a need to tweak the javascript by changing the "Implementation" function from a truly anonymous one to a named function, and then calling it with ```$(window.AdminLTEInit);``` immediately thereafter.  With this in place I can load the theme into the DOM dynamically and then get everything to work.

Its so clean that I'd really prefer to just include the JS unchanged.  Is this something that you feel that you could incorporate into your theme?

**Comment by rjstanford** [comment]
https://github.com/protea/protea-web-template is the project, in case you're curious.

**Comment by almasaeed2010** [comment]
That looks fine. I'll look into it and get back to you.

Thanks for the suggestion.

**Comment by sebyx07** [comment]
thanks a lot rjstanford, i really need that for my ember app :+1:

**Comment by wanglian** [comment]
+1 me too, thanks!
