### ISSUE TITLE
Treeview Child Class Active

### ISSUE THREAD

**Issue by tecnologiaterabyte** [almasaeed2010/AdminLTE#504]
Hi, please preview theme in https://almsaeedstudio.com/preview, for example selected:

Chart:
    Morris is Selected Class Active Work Fine.

Problem:

Its Open Other Option for example Dashboard, and come back again to  options chart, the selection (morris) is lost and have nothing selected.

The only option selected should only lose class active when another node is selected, I hope you understand me, excuse my bad English.

Thks,

Wilmer.

**Comment by almasaeed2010** [comment]
Hello,

This issue has been presented several times. I cannot yet fix it without changing the mechanism that the template uses for the sidebar accordion menu since it will affect current users. This will be fixed in v3.0. 

Thank you for the suggestion!

**Comment by ozanmuyes** [comment]
Hi,

It's good to hear the news about fix.

But there is also another problem; when I click active treeview menu ("active" classed sidebar-menu list item with "treeview" class) to close, the animation doesn't play for folding the sub-menu ("treeview-menu" unordered list). But right after instant folding, re-clicking the menu initiates both opening and folding animation respectively.

![adminlte 2 2 0 active submenu animation issiue](https://cloud.githubusercontent.com/assets/1537985/9024250/4bb5c39e-38cd-11e5-9fc6-cfba37f0f772.gif)

Issue encountered on Mozilla Firefox 39.0 and re-produced on Google Chrome 44.0.2403.125.

Thanks.
