### ISSUE TITLE
About layout.

### ISSUE THREAD

**Issue by oopetyffyx** [almasaeed2010/AdminLTE#505]
Whether can use the import way layout?I think the main title, sidebar, content, respectively on different pages

**Comment by almasaeed2010** [comment]
Are you asking if it is possible? If so, yes it is. Our blog gives an example of [integrating the template with Laravel 5](https://almsaeedstudio.com/blog/integrate-adminlte-with-laravel) and uses a similar method.

**Comment by oopetyffyx** [comment]
Yes,I successful.It's good methon by 'include()' in PHP.
