### ISSUE TITLE
The Right Control Sidebar Toggle Button it doesn't work in V 2.1.2

### ISSUE THREAD

**Issue by ahmedgaduo1** [almasaeed2010/AdminLTE#506]
Its removed from dashboard v2 and still just icon in the rest of template

**Comment by almasaeed2010** [comment]
I tested dashboard v2. The control sidebar works. The icon works in all pages. Make sure you loaded all of the scripts and there are no errors in the console.

**Comment by ahmedgaduo1** [comment]
yes its work.
Thank you
