### ISSUE TITLE
How can I make all the content right to left ?

### ISSUE THREAD

**Issue by PedramParsian** [almasaeed2010/AdminLTE#507]
Hello, I want to know How can I make the content right to left if I buy "INSPINIA" ?
Thanks.

**Comment by oopetyffyx** [comment]
You should read the AdminLTE.css  .
To found the key"content-wrapper" in AdminLTE.css

**Comment by almasaeed2010** [comment]
INSPINIA is not a template that I designed. Please refer to the designer for help.
