### ISSUE TITLE
Feature: set menu active dynamically

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#51]
Feature: set menu active dynamically

I had issue when embedding menu with active class
I realized that it is because the active menu is set on each page hardcoded and I thought it was set by the javascript.

**Comment by ymolinet** [comment]
http://stackoverflow.com/a/43945868/2073096

**Comment by lenamtl** [comment]
@ymolinet this is a very very old thread .....

check here if you need something for the latest menu & submenu
https://github.com/almasaeed2010/AdminLTE/issues/1482
