### ISSUE TITLE
JavaScript runtime error: Object doesn't support this action - fastclick.min.js

### ISSUE THREAD

**Issue by sparra1000** [almasaeed2010/AdminLTE#511]
Using IE 11, open developer tools (F12) 
load AdminLTE Dashboard index.html
debugger/console show this error in fastclick.min.js

File: fastclick.min.js, Line: 1, Column: 8605
function trigger(){document.dispatchEvent(new CustomEvent('o.DOMContentLoaded'))};

Unhandled exception at line 1, column 8605 in http://localhost:49390/plugins/fastclick/fastclick.min.js

**Comment by almasaeed2010** [comment]
This is an issue for the fastclick plugin. Please report it on their repository https://github.com/ftlabs/fastclick/issues

Thanks!
