### ISSUE TITLE
Do you have example of  how to loading page without refresh all page?

### ISSUE THREAD

**Issue by ozonenetwork** [almasaeed2010/AdminLTE#512]
Thank you for your free theme, I like it. I try to create page that when i click link on side bar , it will load page without refresh sidebar  just only load into content area. Do you have example code of it?
Thank you so much , sry for my poor english.

**Comment by almasaeed2010** [comment]
AdminLTE used to support [Pace](http://github.hubspot.com/pace/docs/welcome/), but it is now optional and can be downloaded and easily installed using the link provided earlier.

**Comment by YasserHassan** [comment]
I think @ozonenetwork is talking about single page applications which could be achieved using different technologies like AngularJS, Ember.js, ...etc.

**Comment by ozonenetwork** [comment]
Yes, I mean that @YasserHassan  says.  Thank you so much for your described.

**Comment by n3storm** [comment]
Dear @ozonenetwork , have a look at http://intercoolerjs.org/, it's a declarative ajax library over jquery and I am having very good results mixing AdminLTE and Intercooler together.
