### ISSUE TITLE
content-wrapper height problem in AdminLTE v.2.0

### ISSUE THREAD

**Issue by chrustygesang** [almasaeed2010/AdminLTE#514]
I'm using a codeigniter and AdminLTE 2.0 framework to build a project, 
I try to remove some menus from the sidebar then my form go overlap through the footer bar,
is there any way I can add my content-wrapper height,
I try using the min-height, but its not work properly
![capture](https://cloud.githubusercontent.com/assets/12948920/8226973/81c0b9a8-15cd-11e5-9100-bb502ab7ccbd.JPG)

**Comment by rafael-renan-pacheco** [comment]
Look like you missed some tag closing. Check and recheck the tags, and this problem will be solved.

**Comment by almasaeed2010** [comment]
As @rafael-renan-pacheco suggested, you should make sure that all your tags are closed properly. 

Thanks!

**Comment by chrustygesang** [comment]
i rewrite my code again, but there no open tag,
this only happen when i view my app at 768px height of screen
ill
attach my code here,
btw thanks guys for all your concern,

**Comment by chrustygesang** [comment]
<?php 
$this->load->view('template/head');
?>

<?php
$this->load->view('template/topbar');
$this->load->view('template/sidebar');
?>

<section class="content">
<section class="content-header">
    <h1>
        <strong>diberkas.in</strong> v.1.1
        <small>it all starts here</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Examples</a></li>
        <li class="active">Blank page</li>
    </ol>
</section>
<div class="col-md-6">
    <div class="box">
        <div class="box-header with border">
         <h2 class="box-title"><strong>Modul Administrasi Berkas</strong></h2>
        </div>
            <div class="box-box primary">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $type;?> BERKAS</h3>
                </div>
                <div class="box-body">
                    
                    <?php echo form_open('c_ruangberkas/post')?>
                        <?php if($type=="EDIT")
                        {
                            echo form_hidden('id_berkas',$this->input->get('berkas'));
                        }
                    ?>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nomor Pokok Wajib Pajak</label>
                        <input name="npwp" type="text" required lenght="15" class="form-control" id="exampleInputEmail1" placeholder="Nomor Pokok Wajib Pajak" value="<?php if ($type=="EDIT"){echo $berkas[0]->npwp;};?>">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nama Wajib Pajak</label>
                        <input name="nama_wp" type="text" class="form-control" id="exampleInputPassword1" placeholder="Nama Wajib Pajak" value="<?php if ($type=="EDIT"){echo $berkas[0]->nama_wp;};?>">
                    </div>
                    <div class="form-group">
                        <label>Tahun Pajak/Tahun Pemeriksaan</label>
                        <select name="tahun" class="form-control">
                            <option value="<?php if ($type=="EDIT"){if ($berkas['tahun']==2008){ echo 'selected';}}else{ echo '2008';}?>">2008</option>
                            <option value="2009">2009</option>
                            <option value="2010">2010</option>
                            <option value="2011">2011</option>
                            <option value="2012">2012</option>
                            <option value="2013">2013</option>
                            <option value="2014">2014</option>
                            <option value="2015">2015</option>
                        </select>
                    </div>
                    <div name="jenis_berkas" class="form-group">
                        <label>Jenis Dokumen</label>
                        <select class="form-control" name="jenis_berkas">
                            <option value="SPT">SPT Masa</option>
                            <option value="SKP">Berkas Pemeriksaan</option>
                            <option value="INDUK">Induk Berkas</option>
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-xs-3">
                            <label>Rak Berkas</label>
                            <select name="kode_rak" class="form-control">
                                <option value="A">A</option>
                                <option value="B">B</option>
                                <option value="C">C</option>
                                <option value="D">D</option>
                                <option value="E">E</option>
                                <option value="F">F</option>
                                <option value="G">G</option>
                                <option value="H">H</option>
                                <option value="I">I</option>
                                <option value="J">J</option>
                                <option value="K">K</option>
                                <option value="L">L</option>
                                <option value="M">M</option>
                                <option value="N">N</option>
                                <option value="O">O</option>
                                <option value="P">P</option>
                                <option value="Q">Q</option>   
                            </select>
                        </div>
                        <div class="col-xs-3">
                            <label>Kolom</label>
                            <select name="kolom" class="form-control">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="6">5</option>
                          </select>
                        </div>
                        <div class="col-xs-3">
                            <label>Baris</label>
                            <select name="baris" class="form-control">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                        <div class="col-xs-3">
                            <label>Kardus</label>
                            <select name="nomor_box" class="form-control">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="row" align="center">
                         <button name="simpan" align="center" type="submit" class="btn btn-primary" value="<?php echo $type;?>"><?php echo $type;?></button>
                    </div>
                </div>
                </form>
                
            </div>
    </div>
</div>
</section>

<?php 
$this->load->view('template/js');
?>

<?php
$this->load->view('template/foot');
?>
