### ISSUE TITLE
Change slimscroll height on resize

### ISSUE THREAD

**Issue by Seiifer** [almasaeed2010/AdminLTE#515]
Is there a way to change the slimscroll's height when we resize the page.
For example, if we start with a small window and then maximize it to full screen, the menu will keep scrollings until the previous height instead of going until the bottom of the page.

Adding the following code in `window.onresize` function did not change anything :
```javascript
$(".slimscroll").slimscroll({
        height: (window.innerHeight - 200) + "px",
    }).css("width", "100%");
```

**Comment by almasaeed2010** [comment]
That's a question to the SlimScroll community. I am not sure how to change the properties of SlimScroll after initiation. 

Thanks.
