### ISSUE TITLE
Automatical treeview arrows

### ISSUE THREAD

**Issue by dinymate** [almasaeed2010/AdminLTE#516]
I have a suggestion. I don't think it's good to create arrows one by one, so i put this code to AdminLTE.tree:
<code>
$(menu).find('.treeview-menu').parent("li").children("a").append('');
</code>
(insert the code of arrows into append, github doesn't show it)

**Comment by almasaeed2010** [comment]
Thank you for sharing. I will consider this approach in future releases.
