### ISSUE TITLE
Can't close modal box (from DEMO)

### ISSUE THREAD

**Issue by nbg12** [almasaeed2010/AdminLTE#517]
HEy Abdu,

great great great template...

just wonder why i can not use the close button, when i clicked on any modal close button nothing happened, but i included all required JS files i think.

i get the code from this page directly:

https://almsaeedstudio.com/themes/AdminLTE/pages/UI/modals.html

i copied these lines:

 
			<div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Modal Default</h4>
                  </div>
                  <div class="modal-body">
                    <p>One fine body…</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                  </div>
                </div>
              </div>

what i have to do to get logic into my modal box (i think i need a function like this right?)

$(function() {
					     $( "#print" ).dialog({
					      width: 900,
					      height: 600,
					      
					      show: {
					       effect: "blind",
					       duration: 200
					      },
					      
					      hide: {
					       effect: "explode",
					       duration: 1300
					      },
					      
					      open: function(event, ui){
					       //setTimeout("$('#print').dialog('close')",10000);
					       $('.ui-widget-overlay').live('click', function() {
							     $('#print').dialog( "close" );
							});
						   
						   $( "#dialog" ).bind('clickoutside',function(){
							    $( "#print" ).dialog('close');
							});
						   
					      }
					      
							
					     });
					    });

but it doesnt work

could you help me please!

Thanks

bye Rick

**Comment by Chico3001** [comment]
Use the code from the bootstrap offical page and it will work

http://getbootstrap.com/javascript/#modals


    
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Launch demo modal
    </button>

    
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

**Comment by nbg12** [comment]
Thx for your help ;)

But i want to Show My Modal box in an if / Else PHP Part without Clicking any Button!

And i think i still Need some Java Script Part right? 

Because this Code in your answer is also wihout js!

But i will try it ;)

**Comment by Chico3001** [comment]
I dont get what do you want to do..... can you explain yourself a bit better?

**Comment by nbg12** [comment]
I got a html Formular (POST) on My Site and After somebody clicked on The submit Button i want to Open My Modal Box automaticly!

So i Need My div Layer and this Word Fine! Modal Box comes up! ;)

BUT how can i close My Modal
Box! I alread have One "close" Button, but nothing Happens When i Click in it! Thats My problem!


Von meinem iPhone gesendet

**Comment by almasaeed2010** [comment]
@nbg12 you are using jQueryUI while you should be using Bootstrap.js. There is not dialog method in the Bootstrap Modals plugin. Please review the documntaion that @Chico3001 provided, and try again.

The Modal code with the close button:
```HTML
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <!-- CLOSE BUTTON 1 -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <!-- CLOSE BUTTON 2 -->
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by nbg12** [comment]
Hey again,

thx for your code, it works great BUT i dont need "Launch demo Modal" part

I want to display the modal box WITHOUTclicking anything...

and i\ve already got this....

This is my code:
![screen](https://cloud.githubusercontent.com/assets/12952205/8253216/ed9d4e5a-168d-11e5-871d-99b328c7093d.png)

		 			 

BUT i CAN NOT CLOSE this modal this is my problem it only comes up like a normal box, sorry for complicating ;)
![screen](https://cloud.githubusercontent.com/assets/12952205/8253251/4e677ba2-168e-11e5-87a4-e70b7a55c0c5.png)



but when i tried your code from your last post, it works fine.... so my javascript is fine and works great!!

**Comment by Chico3001** [comment]
First you need to add an ID to the modal and then using javascript you can start it

    
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">

            
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    <script>
    $(document).ready(function () {
        $('#myModal').modal('show');
	});
    </script>

**Comment by almasaeed2010** [comment]
To complete @Chico3001's answer, you can add your PHP condition as such:

```php
<? if( $myCondition ): ?>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">

        <!-- CLOSE BUTTON 1 -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <!-- CLOSE BUTTON 2 -->
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function () {
    $('#myModal').modal('show');
});
</script>
<? endif ?>
```

**Comment by ivantcholakov** [comment]
Offtopic: There is a project that is handy for modal dialogs, especially for this simple example: https://github.com/nakupanda/bootstrap3-dialog

**Comment by nbg12** [comment]
hey guys / hey Abdu...


sorry but this also doesnt work, bothing comes up, only the words "This is only a Test"
(I added these words to check if my PHP Condition works, but its really works)

you have maybe another hint why i cant see nothing of the modal box?

thanks!




<? if($_POST['action'] == "rechnung_drucken"){?>
								
								<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
								  <div class="modal-dialog" role="document">
								    <div class="modal-content">
								      <div class="modal-header">
								
								        
								        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
								
								        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
								      </div>
								      <div class="modal-body">
								        ...
								      </div>
								      <div class="modal-footer">
								        
								        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
								        <button type="button" class="btn btn-primary">Save changes</button>
								      </div>
								    </div>
								  </div>
								</div>
								<script>
									$(document).ready(function () {
									    $('#myModal').modal('show');
									});
								</script>
								
								THIS IS ONLY A TEST
						<? }?>

**Comment by almasaeed2010** [comment]
You need to place the javascript after loading Bootstrap.js
