### ISSUE TITLE
navbar button height margin on bootstrap 3.3.5

### ISSUE THREAD

**Issue by Chico3001** [almasaeed2010/AdminLTE#519]
It seems that Bootstrap 3.3.5 added margins on the btn elements of the navbar that increases the height and therefore misaligns the navbar, the fix is:

    .main-header > .navbar .navbar-btn {
    	/* Bootstrap 3.3.5  Fix */
    	margin-top: 0;
    	margin-bottom: 0;
    }

btw great theme!!!!

**Comment by almasaeed2010** [comment]
I'll look into it. 

Thanks!
