### ISSUE TITLE
Support img as info-box icon

### ISSUE THREAD

**Issue by fschaeffer** [almasaeed2010/AdminLTE#522]
I'd like to have the possibility to use real images instead of icons in the info box and as they should be limited to the boundaries of the icon I had to add a rule for them. Maybe that is of general interest, then I will prepare a PR:

```
.info-box-icon img {
    max-width: 100%;
}
```

**Comment by almasaeed2010** [comment]
In this case the images must be exactly 90x90 or such a square proportion for them to work properly. Could you provide a use case example? Perhaps a screenshot as to what this could be used with?

Thanks!

**Comment by fschaeffer** [comment]
Hello,

you're right, the images will have to be at least square or higher than wide so that the max-width would squeeze them into the icon-area of the info-box (by also adding a ```overflow:hidden``` to the .info-box-icon).

See screenshot (don't ask why I had to use rounded corners and a thick border, it's 2015 but ....)
![info_box_image](https://cloud.githubusercontent.com/assets/1931017/8277524/063dc268-18c4-11e5-8993-6c8b0063049b.png)

**Comment by almasaeed2010** [comment]
Added in master.

Thanks!

**Comment by fschaeffer** [comment]
Thanks
