### ISSUE TITLE
[Question] what is the release date of AdminLTE 4 since Bootstrap 4 have end of support since Jan 2023

### ISSUE THREAD

**Issue by songpr** [almasaeed2010/AdminLTE#5238]
[Question] what is the release date of AdminLTE 4 since Bootstrap 4 have end of support since Jan 2023.

We have to use Bootstrap 5 which is supoort in AdminLTE 4.

**Comment by rupalgohel** [comment]
I am also eager to know this, as I am about to start one of project

**Comment by danny007in** [comment]
Thanks for your support

check out https://github.com/ColorlibHQ/AdminLTE/issues/3692#issue-891364273
you can build compiled version and able to use

https://github.com/ColorlibHQ/AdminLTE/issues/3692 duplicate
