### ISSUE TITLE
admin-lte/dist/js/app.js not found

### ISSUE THREAD

**Issue by scorphus** [almasaeed2010/AdminLTE#525]
When I try to minify admin-lte my assets builder tells me `admin-lte/dist/js/app.js not found`. Can you please fix it?

**Comment by scorphus** [comment]
$ pwd
    /.../static/vendor/admin-lte

    $ lss
    total 200K
    drwxr-xr-x 15 user group  510 Jun 19 01:45 ./
    drwxr-xr-x  3 user group  102 Jun 19 01:45 ../
    -rw-r--r--  1 user group  885 Jun 19 01:45 .bower.json
    -rw-r--r--  1 user group 4.8K Jun 19 01:45 Gruntfile.js
    -rw-r--r--  1 user group 1.1K Jun 19 01:45 LICENSE
    -rw-r--r--  1 user group 6.5K Jun 19 01:45 README.md
    drwxr-xr-x  5 user group  170 Jun 19 01:45 bootstrap/
    -rw-r--r--  1 user group  621 Jun 19 01:45 bower.json
    -rw-r--r--  1 user group 2.3K Jun 19 01:45 changelog
    -rw-r--r--  1 user group  53K Jun 19 01:45 index.html
    -rw-r--r--  1 user group  66K Jun 19 01:45 index2.html
    -rw-r--r--  1 user group  431 Jun 19 01:45 package.json
    drwxr-xr-x 11 user group  374 Jun 19 01:45 pages/
    drwxr-xr-x 25 user group  850 Jun 19 01:45 plugins/
    -rw-r--r--  1 user group  37K Jun 19 01:45 starter.html

**Comment by almasaeed2010** [comment]
What are you using to install AdminLTE?

**Comment by scorphus** [comment]
bower

**Comment by scorphus** [comment]
$ grep app.js bower.json
    "dist/js/app.js",

**Comment by scorphus** [comment]
Thanks for the fast reply by the way!

**Comment by almasaeed2010** [comment]
A fresh install using Bower gets all the files.

```
~/Sites/test/bower_components/admin-lte ls dist/js
app.js     app.min.js demo.js    pages
```

**Comment by almasaeed2010** [comment]
Try to run
```
bower update
```

**Comment by scorphus** [comment]
I went the other way around.

    bower prune
    bower install admin-lte --save

And it amended my bower.json. It's working now.

Thanks so much!

**Comment by almasaeed2010** [comment]
:+1:

**Comment by nileshpal23** [comment]
I tried installing it using `npm install admin-lte --save`
 but still it is showing app.js does not exist.
