### ISSUE TITLE
ChartJS size increases on window resize

### ISSUE THREAD

**Issue by ankitsam** [almasaeed2010/AdminLTE#526]
Increasing/decreasing size of chrome developer toolbar results in zooming of all charts on the page.
Its limited to ChartJS page.
I have attached a video :)
Link: http://youtu.be/riI5YhMJTIE

**Comment by almasaeed2010** [comment]
This is an issue for the ChartJS plugin and should be reported on [their repository](https://github.com/nnnick/Chart.js/). We apologize for the inconvenience.

Thanks!

**Comment by ankitsam** [comment]
ok thanks. Yeh I tried to replicate on chartjs demo before posting here, but it didnt happened on their demo, so i thought maybe.
