### ISSUE TITLE
Add sample notifications and modal

### ISSUE THREAD

**Issue by GhaziTriki** [almasaeed2010/AdminLTE#529]
Hello,

Is it possible to add notifications add modal windows using JavaScript? It would be nice to have them.

**Comment by fschaeffer** [comment]
There was once a suggestion to add Toastr (https://github.com/CodeSeven/toastr) to AdminLTE, don't know the current state. IIRC it will be added to the premium version of AdminLTE.

**Comment by rafael-renan-pacheco** [comment]
I think the premium version already have toastr in it, based on the online preview.

For the free AdminLTE, you can just download Toastr and add in your app. Such easy, very beauty,

**Comment by almasaeed2010** [comment]
@GhaziTriki as suggested above you should use toaster which seamless integrates with AdminLTE without much effort.

Just FYI, the premium version components have been moved to AdminLTE-3.0.0-dev which will be released after Bootstrap 4 and will be available for free.

Thanks!

**Comment by GhaziTriki** [comment]
Thank you very much. I can't see the dev branch. Do you have any release date for it?

**Comment by almasaeed2010** [comment]
@GhaziTriki the development of AdminLTE 3.0.0 has not yet begun except for a few components that are not yet ready for even a beta release. subscribe to our [newsletter](https://almsaeedstudio.com/#subscribe) to stay informed when such major releases are ready. Thanks!
