### ISSUE TITLE
Sidebar Documentation broken link

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#531]
Hi!

The following steps leads to 404:

1: At the sidebar, expand "UI Elements"
2: Click on "Icons"
3: Click on "Documentation"

It will try to open "AdminLTE/pages/documentation/index.html", but the correct path is "AdminLTE/documentation/index.html".

Best regards,
Rafael Pacheco.

**Comment by almasaeed2010** [comment]
Fixed in master.

Thanks for sharing.
