### ISSUE TITLE
Button Dropdown issue when button is inside box positioned at right or right/bottom 

### ISSUE THREAD

**Issue by brettmeyerowitz** [almasaeed2010/AdminLTE#532]
Hi,

If you have a look at https://almsaeedstudio.com/themes/AdminLTE/pages/UI/buttons.html. Refer to "Horizontal Button Group" container, specifically to the Dropdown controls. When clicking the caret the contents of the dropdown are hidden outside the container and out of view. This results, in a horizontal scrollbar being added to the parent box.

**Comment by almasaeed2010** [comment]
Hello,

That's caused by the responsive table div. If you want to avoid that effect, don't use dropdowns within responsive tables. 

Thanks!

**Comment by brettmeyerowitz** [comment]
I have resolved it by doing this:

.box-body {
    overflow: visible !important;
}

**Comment by almasaeed2010** [comment]
You might want to check that code on Safari since it caused me trouble before.
