### ISSUE TITLE
how to use  bootstrap-tagsinput in this template ?

### ISSUE THREAD

**Issue by ahmedgaduo1** [almasaeed2010/AdminLTE#534]

**Comment by almasaeed2010** [comment]
Please describe your issue and how related it is to AdminLTE. 

Thanks!

**Comment by ahmedgaduo1** [comment]
I want to use bootstrap-tagsinput that is like the example in the link
http://timschlechter.github.io/bootstrap-tagsinput/examples/

and i try but i can't do any thing

**Comment by almasaeed2010** [comment]
You can use [Select2](https://select2.github.io/examples.html) "multiple select box". Select2 support is available in master and will be released as v2.1.3.
