### ISSUE TITLE
Poor sidebar performance on Android Webview

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#536]
Hello!

Maybe this is a huge offtopic issue, but I think it is for the best of AdminLTE template quality.

Today I compiled an Android Webview apk, to load my project which uses AdminLTE, and it has a fixed navbar layout. On API level 19+, Android will use the new Webview engine, which is based on Chromium, and so it should be very fast and responsive.

Well, not for all the template.

Scrolling the content page up and down was very fast, like a native app. So far so good. The problem came when I touched the sandwich to open the sidebar. It opened very smoothly as well, until I started scrolling the sidebar up and down. The scrolling of the sidebar went very bad, very laggy, very unresponsive (in speed and UX). When I touched to close the sidebar, and start to scroll the page content, It all returns to normal, very fast.

I tried to reproduce this problem using the Android Chrome Browser, but there were none of the problems I said before. It went 100% fast, the entire webpage. So this is a gap just in Webview, which I think has fewer resources than the browser itself. But the problem was just in the sidebar.

Since the problem was just in the sidebar, maybe there is a fix for that. I have no idea what could be the issue behind the sidebar. Maybe the touch events?

To ensure the Webview app was loading all css/js properly, Chrome (desktop) has a Mobile debug mode, which knows over android USB Debugging what the page is doing and loading on my device. Just like a desktop debug. The site loads perfectly, all js and css, and no clue on what is the cause of the sidebar lag.

To create a Webview app, it is very simple. Just check it out: http://developer.android.com/guide/webapps/webview.html

I think this issue should be investigated, to improve AdminLTE performance on mobile devices that are loading the template via app, not with the main browser.

Best regards,
Rafael Pacheco.

**Comment by almasaeed2010** [comment]
From your description, this is almost 100% a Slimscroll issue. To make certain about the cause, try using the normal layout instead of fixed and try again.

Thank you for sharing!
