### ISSUE TITLE
Date picker Missing

### ISSUE THREAD

**Issue by mahedreams** [almasaeed2010/AdminLTE#54]
Great Theme! Congrats.

I'm learning through your codes. 

My question is,
There is a date range picker. 
But if i want to select date only, then i could  not. 
AM i missing something or the date picker is not implemented.

thanks

**Comment by albyte** [comment]
In the current version , it seems to work.
```javascript
$(function(){
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
        timePicker: true,
        singleDatePicker: true, //<==HERE
    });
});
```

**Comment by Neeraj1005** [comment]
> In the current version , it seems to work.
> 
> ```js
> $(function(){
>     //Date range picker with time picker
>     $('#reservationtime').daterangepicker({
>         timePicker: true,
>         singleDatePicker: true, //<==HERE
>     });
> });
> ```

this one is working
