### ISSUE TITLE
ChartJS - All charts resize issue on every minimize and maximize action on all browsers

### ISSUE THREAD

**Issue by davdinesh** [almasaeed2010/AdminLTE#541]
Hi, 

The charts getting bigger and bigger whenever the window is resized. Could you please provide your suggestion to fix this? Thank you

**Comment by masteradhoc** [comment]
An Update to 1.0.2 could help! Just created some PullRequests: #553 and #552

**Comment by almasaeed2010** [comment]
Hi,

the update doesn't change that effect. I got this issue reported here several times while it should be reported at the [ChartJS repo](https://github.com/nnnick/Chart.js). Refer to #526 and #461.

Thanks.
