### ISSUE TITLE
Unable to use $(doucment.ready(function() and $.ajax

### ISSUE THREAD

**Issue by Itguts** [almasaeed2010/AdminLTE#542]
I am unable to use $(doucment.ready(function(){}); , as i am trying to use this on MVC5 ASp.net.
Also i am unable to use $.ajax() calls.
Please suggest.

**Comment by fschaeffer** [comment]
Open a  console and check for js errors. Also make sure that jquery is loaded. Type $ in console, you should get the jquery object.

**Comment by almasaeed2010** [comment]
Make sure you load the javascript files in the following order:
1- jQuery
2- Bootstrap.js
3- AdminLTE's app.js
4- Your own custom scripts.

**Comment by AndrewLag** [comment]
Check if you have written "doucment" instead of DOCUMENT. You flipped U and C letters.

**Comment by almasaeed2010** [comment]
$(document).ready(function(){});
