### ISSUE TITLE
How to use With yeoman angular-fullstack

### ISSUE THREAD

**Issue by Overseas634** [almasaeed2010/AdminLTE#545]
I have done basic app setup using Angular Yeoman app.
i have installed it using bower install admin-lte. i need help how use it in angular app
which js file need to be included cause i have passed admin-lte in app and added all js files under dist/js 
but still it shows error as admin-lte not found so not able to make use of it.
so please help me how can  i make use of it with yeoman angular-fullstack app setup

**Comment by almasaeed2010** [comment]
I am not very familiar with yeoman or angular. So, unfortunately, I am not the right person to ask. I apologize for the inconvenience.
