### ISSUE TITLE
asset and public directory

### ISSUE THREAD

**Issue by guil182** [almasaeed2010/AdminLTE#546]
hi,
I try to integrate AdminLTE in laravel.
but all the path are link to the public directory : 
<link href="{{ asset("/AdminLTE/bootstrap/css/bootstrap.min.css")
do : http://localhost:8888/laravel/public/AdminLTE/dist/css/AdminLTE.min.css

and it must do : http://localhost:8888/laravel/AdminLTE/dist/css/AdminLTE.min.css
how to solve it ? :/

thanks for your very nice job !

**Comment by adriandmitroca** [comment]
This is default Laravel behavior. You should place all your assets within `/public` directory.

**Comment by guil182** [comment]
Thanks you. that's it !
I'm really a newbies. I have a new question. I try to use Datatable.
So, in a index.blade.php, i include :
<script type="text/javascript">
        $(document).ready(function() {
            $('#example').dataTable();
        } );
    </script>

but it don't work :( ->ReferenceError: Can't find variable: $

do i must include something else ?

thank you very much

**Comment by ivantcholakov** [comment]
lQuery

**Comment by guil182** [comment]
Thank for your help.
here is my code
```javascript
<script src="{{ asset ("/AdminLTE/plugins/datatables/jquery.dataTables.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset ("/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js") }}" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#example').dataTable();
        } );
    </script>
```
and the result :(

![error](https://cloud.githubusercontent.com/assets/239505/8451437/a2621c40-1fe3-11e5-8740-7a22bc1c3218.jpg)

why it don't know $ ?

**Comment by adriandmitroca** [comment]
You have to load jQuery before DataTables.

**Comment by guil182** [comment]
```javascript
 <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="{{ asset ("/AdminLTE/plugins/datatables/jquery.dataTables.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset ("/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js") }}" type="text/javascript"></script>
   

    <script type="text/javascript">
        $(document).ready(function() {
            $('#example').dataTable();
        } );
    </script>
```
and the result :(

![error](https://cloud.githubusercontent.com/assets/239505/8451768/ff34b8b8-1fe5-11e5-8616-474664e9d6bc.jpg)

**Comment by ivantcholakov** [comment]
For a working example, have a look at these changes:
https://github.com/almasaeed2010/AdminLTE/pull/491
https://github.com/ivantcholakov/AdminLTE/commit/1e096c9eec7e5b1b024852196d28725490719689

**Comment by ivantcholakov** [comment]
And check whether DataTables related scripts are really loaded.

**Comment by guil182** [comment]
hi,

it work ... when i change like this

```javascript
<script type="text/javascript">
    jQuery(function($){
        $("#example").DataTable();

    });
</script>
```

It's not a problem but why ?
