### ISSUE TITLE
Bower update not including Select2

### ISSUE THREAD

**Issue by nokian125** [almasaeed2010/AdminLTE#547]
Select2 needs to be placed manually inside plugin's folder and its not loaded using bower updated.

**Comment by almasaeed2010** [comment]
That's because there is not an official release that supports select2 yet. A few tests need to be run to make sure that the styles work on all browsers before we release the feature.

Thanks!

**Comment by nokian125** [comment]
I was suspecting the same thing. Thanks for your speedy response mate.
