### ISSUE TITLE
AdminLTE for Ruby on Rails ?

### ISSUE THREAD

**Issue by MohamedBouasria777** [almasaeed2010/AdminLTE#550]
Hey, I wanted to add AdminLTE to my Rails App but I couldn't figure out how !
I'm a little bit new to this and I would really appreciate it you can help me with this matter.
Thanks.
PS: I'm using Rails 4.

**Comment by almasaeed2010** [comment]
Hi,
I am not really familiar with Rails. @shine60vn created a repo that supports AdminLTE 1.3.0 with Rails https://github.com/shine60vn/adminlte-rails. I would suggest that you check out how he did it. 

Thanks!

**Comment by MohamedBouasria777** [comment]
Thanks ... that was really nice of you!
