### ISSUE TITLE
'Upgrade' from Admin LTE to ISPINIA template

### ISSUE THREAD

**Issue by SGE66** [almasaeed2010/AdminLTE#557]
Hi,

we have been using the ADMIN LTE but we would like to use some design elemens from th ISPINIA template.
What does this mean for our current website ?

Can I just swap the AdminLTE-2.1.1 folder with the ISPINIA or is this too optimistic ?

**Comment by almasaeed2010** [comment]
Hello,

INSPINIA is designed by a different group of designers. It is not related to AdminLTE except on the fact that they are both based on Bootstrap 3. You can contact the designers directly using this [contact form](https://wrapbootstrap.com/user/WebAppLayers).

Thanks for your interest.
