### ISSUE TITLE
Input Type Number

### ISSUE THREAD

**Issue by masteradhoc** [almasaeed2010/AdminLTE#558]
Hi @almasaeed2010 
Would you be able to design a nice input field for type number?

**Comment by almasaeed2010** [comment]
Hello, 

Are you trying to have a field that accepts numbers only?

**Comment by masteradhoc** [comment]
Yes :) and that one should allow me to press one number up or down at the end :)

**Comment by YasserHassan** [comment]
[Bootstrap TouchSpin](http://www.virtuosoft.eu/code/bootstrap-touchspin/) is a good candidate.

**Comment by almasaeed2010** [comment]
@YasserHassan That looks good. I am gonna keep it in mind.

**Comment by masteradhoc** [comment]
Hi @almasaeed2010 - As you closed this.. Will you not add this one in the future?

**Comment by masteradhoc** [comment]
@almasaeed2010 please check comment on 27 jun
