### ISSUE TITLE
Bugs when using bootstrap-wysihtml5 plugin

### ISSUE THREAD

**Issue by webfreaks** [almasaeed2010/AdminLTE#559]
Your admin template was awesome,
But, there is a bug I found in textarea, when it's using bootstrap-wysihtml5.

You click **insert link**, 
type some link,  then click button **insert link**,
after that you click link that inserted before and will pop up modal of insert link.
When you click cancel button, the bugs will appeared.
Would you like to solve this one?

Thanks,

**Comment by almasaeed2010** [comment]
Hello,

Please report this on the plugin's repo https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

Thank you for sharing!
