### ISSUE TITLE
Bower update to use Select2

### ISSUE THREAD

**Issue by fmobile** [almasaeed2010/AdminLTE#562]
Hi,

I saw you added support for Select2, thank you! but I updated using 'bower update admin-lte' but it didn't update to the version with the Select2 library so was wondering if it is because the version didn't change or maybe I am doing something wrong I'll appreciate any suggestion about updating with bower.

Thank you!

**Comment by almasaeed2010** [comment]
Hi,

That was because there wasn't a released stable version that supports Select 2. The release that supports it is 2.2.0 and it has been released. Try updating with bower again and it should work. 

Thanks!

**Comment by fmobile** [comment]
oh ok, I'm so sorry for my mistake. I'll update then.
Thank you so much!
