### ISSUE TITLE
Slide over content for main sidebar

### ISSUE THREAD

**Issue by jlamer** [almasaeed2010/AdminLTE#565]
Is it possible to add slider over content choice for main sidebar? It is already implemented for control sidebar.

**Comment by almasaeed2010** [comment]
This feature is not yet available in the current AdminLTE version.

**Comment by jlamer** [comment]
It was more like a feature request. Do you plan to add something like that? Is it even possible you will implement it?

**Comment by grcgsite** [comment]
I hope it will fix as soon as possible thanks :)

**Comment by almasaeed2010** [comment]
It may be implemented in AdminLTE 3.0
