### ISSUE TITLE
active element in menu deactivates when closing menu

### ISSUE THREAD

**Issue by fmobile** [almasaeed2010/AdminLTE#566]
Hi,

this maybe is more a question than an issue. I've noticed in the menu that when I have a tree-menu open and a 'li' element active if I close the menu-tree and then open it again the 'li' element is not anymore selected is this the intended behaviour? So, if I would like for the element to remain selected is there a way to achieve this? 

Thank you!

**Comment by fmobile** [comment]
Also, I would like to comment something about the menu, I'm not sure if this is the right place but I hope is useful or If I am making a mistake please correct me. 
When closing a tree-menu the first time the slideUp animation is not performed and I found out that is because is not passing the .is(':visible') condition so to pass this condition I had to add ```style="display: block;``` so an open menu example would be like this :
```
<ul class="sidebar-menu">
    <li class="header">Menu</li>
    <li class="treeview active">
        <a href="#"><i class="fa fa-cogs"></i> <span>Configuration</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu menu-open" style="display: block;">
            <li id="rutasH" class="">
                <a href="#"><i class="fa fa-circle-o"></i> Option 1</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-circle-o"></i> Option 2</a>
            </li>                                                           
        </ul>
    </li>
</ul>
```

in this way the menu is animated also the first time closing it. 
I found out that in jQuery:  "Elements are considered visible if they consume space in the document" (http://api.jquery.com/visible-selector/).

Thanks!

**Comment by almasaeed2010** [comment]
Hello,

This is, in fact, an issue that was proposed several times. The solution that I came up with results in change of markup. If implemented, it would violate the semantic versioning we are trying to follow. It is put into consideration and should we find a different solution, it will be available in 2.x. 

The visible-selector observation is interesting and I will look further into it. 

Thanks for sharing.

**Comment by fmobile** [comment]
oh ok, It sounds good!
No problem, I'll be glad if my comments are somehow useful.

Thank you so much!

**Comment by gauthier-delacroix** [comment]
@almasaeed2010 Maybe changing the JS to bypass `active` class removal if another class, let's say `active-keep`, is present too could do the trick without involving any breaking change. Users not using `active-keep` will keep the current behavior.
