### ISSUE TITLE
Download link for latest 2.2.0

### ISSUE THREAD

**Issue by adminko-svk** [almasaeed2010/AdminLTE#568]
Hi, 
the link https://almsaeedstudio.com/download/AdminLTE-master contains only AdminLTE-2.1.1.zip and not the latest 2.2.0 version!

Where can I find / download the latest final version - 2.2.0?

Thank you.

**Comment by adminko-svk** [comment]
I found it here - https://github.com/almasaeed2010/AdminLTE/archive/v2.2.0.zip
So please update the "AdminLTE-master" link (for others) with the latest content from this archive (v2.2.0.zip).

**Comment by almasaeed2010** [comment]
Oh thanks for letting me know.
Gonna update the site now!
