### ISSUE TITLE
Select2 form element design broken when changing window size

### ISSUE THREAD

**Issue by david-hubner** [almasaeed2010/AdminLTE#569]
Select2 element has fixed size after page load and when you resize browser window it hold its size. It should properly resize as other form inputs.

Also select2 element is not properly sized when it is inside box which is hidden by default (tabs, etc.).

**Comment by almasaeed2010** [comment]
This is a select2 issue. Please report that at their repository 
https://github.com/select2/select2/issues

Thanks!

**Comment by almasaeed2010** [comment]
Please refer to issue #588 where a solution has been established. 

Thanks!
