### ISSUE TITLE
Adding nestable support

### ISSUE THREAD

**Issue by davihu** [almasaeed2010/AdminLTE#570]
It would be very nice to have nestable support with draggable handlers in your AdminLTE framework. I am using this plugin now http://dbushell.github.io/Nestable/ as extension.

**Comment by almasaeed2010** [comment]
Thanks for the suggestion! I will look into it.

**Comment by jlamer** [comment]
:+1:

**Comment by antonsofyan** [comment]
yes, I need nestable plugin on this AdminLTE

**Comment by antonsofyan** [comment]
:+1:
