### ISSUE TITLE
How to pick a skin with bower

### ISSUE THREAD

**Issue by mani47** [almasaeed2010/AdminLTE#572]
I used bower to install admin-lte:

    $ bower install admin-lte --save

installation generates this code in my html:

    
    
    <link rel="stylesheet" href="bower_components/admin-lte/dist/css/AdminLTE.css" />
    
    

I want to pick skin css but there is no way to choose which skin to include with bower, as you know this code gets generated automatically so If I add a skin file manually here like this:

    
    
    <link rel="stylesheet" href="bower_components/admin-lte/dist/css/AdminLTE.css" />
    <link rel="stylesheet" href="bower_components/admin-lte/dist/css/skins/skin-green.css" />
    
    

 it will get overwrite by next bower install. and If I include it anywhere else like this:

    
    
    <link rel="stylesheet" href="bower_components/admin-lte/dist/css/AdminLTE.css" />
    
    
    <link rel="stylesheet" href="bower_components/admin-lte/dist/css/skins/skin-green.css" />

It will not get picked up with grunt build task so It will not load in production. I ended up with copying skin-green.css content in my  main css file. Is there any cleaner way to pick up a skin file?

**Comment by kgoedert** [comment]
+1

**Comment by almasaeed2010** [comment]
I never used Bower in this way so I am not sure how does that code get generated. It is possible to use a grunt task that'd allow you to combine two stylesheets before you include them in the project. I am not sure if this is helpful but I would check out [Grunt Savvy](https://www.npmjs.com/package/grunt-savvy-js).
