### ISSUE TITLE
Change widgets per row

### ISSUE THREAD

**Issue by jjur** [almasaeed2010/AdminLTE#573]
Hi,
is possible to change number of widgets per row on page? If yes, how?
I need 3 widgets when ís left sidebar open
![need 3 widgets](https://cloud.githubusercontent.com/assets/13292381/8635196/e8ab150c-2818-11e5-94f1-85417f02e881.png)
and 4 widgets in line when is left sidebar closed, because i need bigger widgets.
![need 4 widgets](https://cloud.githubusercontent.com/assets/13292381/8635197/e8e18d9e-2818-11e5-965c-6d2964a0a454.png)
Thanks

**Comment by almasaeed2010** [comment]
I don't think this is possible without a plugin like Masonry or something similar. Bootstrap doesn't provide a way to do that. We apologize for the inconvenience.
