### ISSUE TITLE
Flexbox layout

### ISSUE THREAD

**Issue by frlinw** [almasaeed2010/AdminLTE#576]
Hi,

I just want to know if a flexbox version of adminlte is planned (bye bye tricky footer \o/) or if I have to leave the master branch :°(

Thanks

**Comment by YasserHassan** [comment]
I think this would be a good way to handle issue #437.

**Comment by almasaeed2010** [comment]
Hello,

AdminLTE depends on Bootstrap which provides a good grid system. Flexbox is only support by newer browsers (IE 11) while AdminLTE should support IE9+. What is the issue you are having? We may be able to help.

Thanks

**Comment by frlinw** [comment]
It wasn't about the grid system, bootstrap is fine for that, it was about the main structure : header / asides/ content / footer
I dreamed about a world where you can avoid float and where it's not necessary to use js to place the footer at the bottom of a page... Flexbox do that

I asked this question because I didn't want to custom adminlte file (overload a class doesn't work is this case) but if there is no other way...
