### ISSUE TITLE
use customized javascript

### ISSUE THREAD

**Issue by mayhem256** [almasaeed2010/AdminLTE#577]
hello and thanks for your wonderful theme. 
but i have 2 problems in yii2,
1-when i add javascript  to my papge doesn't load! my script is simple javascript between script cotations
2- when i include script src="plugins/jQuery/jQuery-2.1.4.min.js"></script to page its make problem to theme, for example side bar doesn't close!
i am waiting for your help!

**Comment by YasserHassan** [comment]
@mayhem256 did you integrate AdminLTE with Yii2 yourself or using a 3rd-party package?

**Comment by mayhem256** [comment]
yeah! and I've found the problem!
my problem was about the feature of yii2 script injector. so i have added this code to my assets\AppAsset.php.
public $jsOptions = array(
    'position' => \yii\web\View::POS_HEAD
);
