### ISSUE TITLE
Active class on top-nav layout nav elements not working

### ISSUE THREAD

**Issue by jlamer** [almasaeed2010/AdminLTE#578]
Class "active" is not working on neither demo: https://almsaeedstudio.com/themes/AdminLTE/pages/layout/top-nav.html nor when used in own work. 

I dont know if its bug or I am just missing something.

Tried on latest Chrome and Firefox.

**Comment by almasaeed2010** [comment]
Thanks for reporting the issue. I'll try to fix it soon.

**Comment by almasaeed2010** [comment]
Fixed
