### ISSUE TITLE
AdminLTE laravel

### ISSUE THREAD

**Issue by guil182** [almasaeed2010/AdminLTE#582]
Hi,

I would like to put a form text and a form checkbox on the same row 
```php
         <div class="row">
                        <div class="col-xs-8">
                            <div class="form-group">
                                {!! Form::label('nom', 'Nom') !!}
                                {!! Form::text('nom',null,array('required',
                                                'class'=>'form-control',
                                                'type'=>'text',
                                                'placeholder'=>'Entrez le nom de la banque'))
                                !!}
                            </div>
                        </div>

                        <div class="col-xs-4">
                            <div class="form-group">
                                {!! Form::label('default', 'Compte par défaut') !!}
                                {!! Form::hidden('default', 0) !!}
                                {!! Form::checkbox('default', 1) !!}
                            </div>
                        </div>
        </div>
```
And the result is very bad. how the align "compte par default" with the checkbox on the red line ?
![align](https://cloud.githubusercontent.com/assets/239505/8656646/196bfd10-2999-11e5-9b12-ef366edf7855.jpg)
Thank you

**Comment by fschaeffer** [comment]
This is barely an AdminLTE issue but more a Bootstrap thingy.

For checkboxes Bootstrap puts label and checkbox always in one line (see http://getbootstrap.com/css/#forms-controls). As the whole structure for displaying a checkbox component is different from input ot textarea (checkboxes need their input IN the label and is positioned absolute in the container) you will have to create a "label" by hand, meaning creating a style which mimics the design of a label and place this above the checkbox-component.

I don't know how Laravel creates these rows, in symfony itself the checkbox component will look something like this:
```html
<div class="checkbox">
  <label>
    <input type="checkbox" value="">
    Option one is this and that&mdash;be sure to include why it's great
  </label>
</div>
```
so it would be easy to add a
```html
<div class="checkbox-label">My label</div>
```
above the checkbox-component.

**Comment by guil182** [comment]
Hi,
I add this line 
```html
<p class="spacer">&nbsp;</p>
```
and it solve my problem :)
```html
<div class="col-xs-4">
                            <p class="spacer">&nbsp;</p>
                            <div class="form-group">

                                {!! Form::hidden('default', 0) !!}
                                {!! Form::checkbox('default', 1) !!}
                                &nbsp;&nbsp;
                                {!! Form::label('default', 'Compte par défaut') !!}
                            </div>
                        </div>
```
![align](https://cloud.githubusercontent.com/assets/239505/8668765/c6833458-2a0e-11e5-8a2c-fe6f158c3d31.jpg)

Thank you for your help and your time.

**Comment by acacha** [comment]
See https://github.com/acacha/adminlte-laravel
