### ISSUE TITLE
New to AdminLTE

### ISSUE THREAD

**Issue by yone920** [almasaeed2010/AdminLTE#583]
Hi, I am a newbie in web design. I have developed my first website and now I want to incorporate an admin page to my website so that it would be easy for my client to update the website. So where do I start i believe AdminLTE can serve my need but I do not know how to set it up with my website. The website is a simple website but since my customs does not have any coding experience so I am expecting he can easily modify his home page and about page contents with AdminLTE

**Comment by YasserHassan** [comment]
@yone920 you do not use AdminLTE to update your website's contents. AdminLTE is more on the concept side. It provides a professional design (look and feel) but not back-end functionality. There are different approaches to develop your website depending on your content type which is not clear from your message. For example is it a news-like website, e-commerce, ...etc?

**Comment by rafael-renan-pacheco** [comment]
@yone920 coding AdminLTE to work as CMS is reinventing the wheel.

In google, search for: "adding cms to existing website". You will find tons of top quality CMS, some of them even free. They are build to incorporate dynamic content to an existing website, and let the user manage content on them.

They also differ from CMS's like Wordpress, which are best suited to build a website from scratch. In your case you already have a website, so CMS's like Wordpress won't be the best option for you, tho you can still try to use it.
