### ISSUE TITLE
Right sidebar issue

### ISSUE THREAD

**Issue by Leon-O** [almasaeed2010/AdminLTE#584]
Sometimes, the settings sidebar breaks its layout on IE, Chrome and FF latest versions
![20150714-1](https://cloud.githubusercontent.com/assets/4379316/8675478/29f8e214-2a12-11e5-8cc3-09e7dbba9356.png)

To reproduce the issue:
1) Select boxed layout
2) Select fixed layout
3) Unselect fixed layout

**Comment by almasaeed2010** [comment]
I will look into that. Thanks!

**Comment by almasaeed2010** [comment]
Fixed in master.
