### ISSUE TITLE
Scroll in left menu was superb.

### ISSUE THREAD

**Issue by prashantidealittechno** [almasaeed2010/AdminLTE#586]
I was using previous admin-lte theme and it contain a scroll that was superb function in admin-lte  can you show how can i add the scroll again in new theme or any option to add or code to make it scroll again in new theme.

**Comment by almasaeed2010** [comment]
You might be looking for the fixed layout. It's the only option that activates SlimScroll in the sidebar. Add the "fixed" class to the body tag and make sure you load the SlimScroll plugin before loading app.js

**Comment by prashantidealittechno** [comment]
Hello I found that i have to pass only 'fixed' into <body> tag but i did not see the scroll that comes before can you help me more that i might be forge something.

**Comment by prashantidealittechno** [comment]
Yes i find the solution,the scroll bar is their its width is too small '3px' assign in app.js file and its color is close to transparent i just change from app.js and it works for me, thanks for your great help.

Answer: 
1. Pass fixed in ```<body>``` and 
2. Make customization in app.js according to your requirements for SlimScroll.
