### ISSUE TITLE
Collapsable widget box not working as it should be

### ISSUE THREAD

**Issue by pimduijst** [almasaeed2010/AdminLTE#587]
I am loading a modal content through ajax. The content contains some collapsable boxes. In some cases I want them to be open, in some cases collapsed which works fine. What only does not work is the collapsing itself when I click on the plus/minus sign.

Someone any idea what is causing this? I am running all the latest sources.

Kind regards,

Pim

**Comment by almasaeed2010** [comment]
If you inserted a box into the document after app.js was loaded, you have to activate the collapse/remove buttons explicitly by calling $(".box").activateBox()

**Comment by pimduijst** [comment]
Console says activateBox is not a function... :(

**Comment by almasaeed2010** [comment]
This should be fixed in master. Refer to issue #593.

**Comment by pimduijst** [comment]
Cool cool! Works fine now :)
