### ISSUE TITLE
select2 resize problem

### ISSUE THREAD

**Issue by ccarrionp** [almasaeed2010/AdminLTE#588]
If you resize the browser, select2 dont adjust like other inputs

https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html

**Comment by almasaeed2010** [comment]
This is select2 issue. Please report it at their repository. 
https://github.com/select2/select2

Thanks!

**Comment by fmobile** [comment]
Hi, 

I would like to comment that you need to put inline style with a percentage into the tag as indicated in select2 examples (https://select2.github.io/examples.html):
```
<select class="js-example-responsive" style="width: 50%"></select>
```
I used 100% to fill width of the closest container

**Comment by masteradhoc** [comment]
.@fmobile Thanks so much, fixed a Bug for me :)!

**Comment by fmobile** [comment]
@masteradhoc  no problem, I'm glad it worked!

**Comment by almasaeed2010** [comment]
Added to AdminLTE master. 

Thanks!
