### ISSUE TITLE
Select2 vs bootstrap-select

### ISSUE THREAD

**Issue by DiomedesDominguez** [almasaeed2010/AdminLTE#589]
Hi, I know that the new version of AdminLTE came with Select2's plugin, but anyone have experience using bootstrap-select? I found pretty more "issues-less" than select2 and I want to know there are any plans to use it in the future as part of AdminLTE template.

**Comment by laudeco** [comment]
AdminLTE comes with select2, but if you prefer bootstrap-select you can integrate it and why not writing a PR.

Now select2 is much more complete like ajax call,...

**Comment by almasaeed2010** [comment]
I might also add bootstrap-select as secondary resource. Thanks for the suggestion.

**Comment by Leon-O** [comment]
Thanks for considering. @laudeco there is an extension for Bootstrap-Select, https://github.com/truckingsim/Ajax-Bootstrap-Select. I'd like to see a benchmark of this too plugins (Select2 and Bootstrap-Select), but I'm short of time to build one :tongue:
