### ISSUE TITLE
adminLTE Select2 style for allowClear

### ISSUE THREAD

**Issue by fmobile** [almasaeed2010/AdminLTE#590]
Hi,

I am using the option allowClear for Select2 and when set to true it puts an "x" mark to clear the select, but the position of this element is over the arrow so I was thinking the problem was from the select2 library but I noticed that there is a select2.less with some styles changed specifically for adminLTE so comparing the original style with the modifications I was able to correct the position overriding some styles: 

```
.select2-container .select2-selection--single .select2-selection__rendered {
  padding-right: 10px;
}
```

If there is a better way to do that please tell me,

thank you!

**Comment by almasaeed2010** [comment]
I will try to fix that soon. Thanks for reporting the issue!

**Comment by fmobile** [comment]
Sure, no problem.

Thanks!
