### ISSUE TITLE
boxWidget: update event listening (from element to container)

### ISSUE THREAD

**Issue by FSou1** [almasaeed2010/AdminLTE#593]
There is a problem with current lines:

      //Listen for collapse event triggers
      $(_this.selectors.collapse).on('click', function (e) {
        e.preventDefault();
        _this.collapse($(this));
      });

      //Listen for remove event triggers
      $(_this.selectors.remove).on('click', function (e) {
        e.preventDefault();
        _this.remove($(this));
      });

If element loads with template after app.js, events listeners doesn't work (for example, it's very often behaviour with angularjs).

My offer to update it like this:

      //Listen for collapse event triggers
      $(document).on('click', _this.selectors.collapse, function (e) {
        e.preventDefault();
        _this.collapse($(this));
      });

      //Listen for remove event triggers
      $(document).on('click', _this.selectors.remove, function (e) {
        e.preventDefault();
        _this.remove($(this));
      });

**Comment by almasaeed2010** [comment]
That's why the issue is happening! I wasn't familiar with this syntax before and I meant to do it this way. I thought they meant the same thing. I will do that soon. Thanks for letting us know.

**Comment by almasaeed2010** [comment]
Fixed in master.

**Comment by jialbanc** [comment]
This fix isn´t in master. I found it inside dist/js/app.js into the branch "issue-668"

**Comment by plumpboy** [comment]
error: $(...).activateBox is not a function
i use vs 2.4.8
