### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by lookapanda** [almasaeed2010/AdminLTE#594]
I read that there are user profiles in the premium templates.
Is there any possibility to get a user profile template for AdminLTE aswell? I would even pay for it (as a plugin maybe)?

**Comment by almasaeed2010** [comment]
There is a plan to implement a user profile page. I am not sure when I will have the time for this feature but it will probably be available with AdminLTE 2.3.0.

**Comment by lookapanda** [comment]
Okay, cool. Thanks for replying.

**Comment by rafael-renan-pacheco** [comment]
:+1:

**Comment by herberthudson** [comment]
:+1:

**Comment by freezy-sk** [comment]
This issue was solved in v2.3.0 81aa879d3a4489213888e24975b073c7478f0447
