### ISSUE TITLE
How can i change these?

### ISSUE THREAD

**Issue by cRUSHER-ScriptBase** [almasaeed2010/AdminLTE#595]
Hello, i have split the boxed.html template to .tpl files and with a function i put them all together in the index.php but the dropdowns in the left side are not flush to the header. These you will see in the picture, anyone a idea how i can change it?
The pic: https://www.dropbox.com/s/6uxivpmk0tkpo39/Screenshot%202015-07-20%2022.41.11.png?dl=0

**Comment by almasaeed2010** [comment]
I am not sure what you mean by "dropdowns in the left side are not flush to the header". I'd appreciate a clearer explanation. Thanks.

**Comment by cRUSHER-ScriptBase** [comment]
Yes thats exactly what i mean. How i have already sayed to i have split the boxed.html file into 5 files. (headerlib, header, menu, footer, footerlib) and i load the files with a method in php. How can i flush the dropdowns to the header. Without php its working but i dont know / dont find a way to solve it. Has anyone a idea what can be the reason for that?

**Comment by cRUSHER-ScriptBase** [comment]
Can you give me pls an answer?

**Comment by YasserHassan** [comment]
@cRUSHER-ScriptBase your problem description is not clear but if you meant that the top drop down menus (e.g. bell icon) are not working, probably you haven't executed the JavaScript functions that activate the menus and make them work. Check that you have included `app.js` and use something like Firebug's Console tab to see if there are any errors when the page is loaded. Generally, compare your generated page with a similar one from AdminLTE and spot if there are major differences that are causing the problem. If this is not the problem, the same approach still could be used for fixing similar problems.

**Comment by cRUSHER-ScriptBase** [comment]
My problem is to the dropdown icon is moved up so it dont looks flush. The dropdown is working.

**Comment by YasserHassan** [comment]
What do you mean by "flush"? A screenshot can help here.

**Comment by Dennis14e** [comment]
I guess that you are German (URL)?
Weil ansonsten kann ich dir vielleicht helfen. Was genau ist dein Problem?
