### ISSUE TITLE
AJAX problems when trying to insert chat

### ISSUE THREAD

**Issue by khareland** [almasaeed2010/AdminLTE#596]
Hi, 

When trying to use an iframe on my site the footer is stretched up to under the iframe element.

and when trying to use javascript to insert the chat log im using into the page in a div it gives the same result, altho. when inserting a table with the same method nothing goes wrong.

also, when trying to use any other html tag like 
```html
<chat id="chatbox" style="width:100%; height:400; overflow:auto;"></chat>   
```
i get the same result... 

here is a screenshot: http://prntscr.com/7v5pey

I am using this to make a public chat box in the user area of my site, here is my JS code:
```js
function loadLog(){		

		$.ajax({
			url: "/assets/frames/chatlog/<?php echo $hour_day; ?>-log.html",
			cache: false,
			success: function(html){		
				$("#chatbox").html(html); 			
		  	},
		});
        
	}
	

	function loadLog(){		
		var oldscrollHeight = $("#chatbox").attr("scrollHeight") - 20; 
		$.ajax({
			url: "/assets/frames/chatlog/<?php echo $hour_day; ?>-log.html",
			cache: false,
			success: function(html){		
				$("#chatbox").html(html); 
				
				//Auto-scroll			
				var newscrollHeight = $("#chatbox").attr("scrollHeight") - 20; //Scroll height after the request
				if(newscrollHeight > oldscrollHeight){
					$("#chatbox").animate({ scrollTop: newscrollHeight }, 'normal'); //Autoscroll to bottom of div
				}				
		  	},
		});
        
	}
	setInterval (loadLog, 500);
```

**Comment by almasaeed2010** [comment]
Hello,

Could you provide access to that page? I can't find the problem given your description. We'll need either direct temporary access or the full html produced by your script.
