### ISSUE TITLE
"content-wrapper" has wrong "min-height" after resize

### ISSUE THREAD

**Issue by Schabrock** [almasaeed2010/AdminLTE#597]
Hi!

When i resize the window so the left navbar disappears and re-maximes the window again it looks like the footers height would change.

Only happens when the content-page isn't scrollable. (Tested on: https://almsaeedstudio.com/themes/AdminLTE/pages/examples/blank.html)

The misbehaviour only seems to appear in the latest und previous chrome version(44.0.2403.89).
When tried on latest Firefox and IE everything works just fine.

![01_pre_resize](https://cloud.githubusercontent.com/assets/13448464/8821239/80beb04c-305c-11e5-9cbc-6a0de547be58.png)
![02_resized](https://cloud.githubusercontent.com/assets/13448464/8821241/80c04ac4-305c-11e5-96ae-cbd968ea39f0.png)
![03_maximised](https://cloud.githubusercontent.com/assets/13448464/8821240/80c01798-305c-11e5-8dde-cc9ebd86e1e3.png)

**Comment by almasaeed2010** [comment]
I tried to replicate the issue but couldn't come up with the same result. Could it be an issue on Windows Chrome? I am using the same release of chrome on a mac but I could reproduce the bug.

**Comment by ivanpg** [comment]
I have the same problem when I resize in Chrome (ubuntu). When I resize and back to initial size, the footer is bigger.
![captura de pantalla de 2015-08-02 12 36 28](https://cloud.githubusercontent.com/assets/4881660/9025779/cfa8c7cc-3914-11e5-9305-354fb363d43b.png)
![captura de pantalla de 2015-08-02 12 37 51](https://cloud.githubusercontent.com/assets/4881660/9025780/d3019c8c-3914-11e5-9c82-5e257bcc3251.png)
![captura de pantalla de 2015-08-02 12 38 35](https://cloud.githubusercontent.com/assets/4881660/9025781/d5cf784e-3914-11e5-9051-68d155e72963.png)

**Comment by FalconDev91** [comment]
@ivanpg @Schabrock Did you guys fix it? I'm having the same problem.I've been trying to fix it for the past 6 hours and still no luck!

**Comment by riotbr** [comment]
How I solved this: taking off the "overflow: hidden" on the wrapper class.

```.wrapper {
min-height:100%;
position:relative;
/*overflow:hidden*/
}```

**Comment by riotbr** [comment]
@FalconDev91 , I had the same problem and solved right now with:

```css
/* Layout */
.wrapper {
  /*min-height: 100%;
  position: relative;
  overflow: hidden;*/
  width: 100%;
  min-height: 100%;
  height: auto !important;
  position: absolute;
}
```

**Comment by KrishnaPG** [comment]
@riotbr Somehow it is not working for me, still seeing the same problem.

**Comment by KrishnaPG** [comment]
The problem could be with css animations taking more and resize handler getting called *before* the css heights have settled.

Did not test this thoroughly, but in the initial testings it look like debouncing the resize handler looks like taking care of the size issues. (Besides, debouncing the resize handlers is also good for cpu). Below is the modified code (requires lodash):

````
      $(window, ".wrapper").resize(_.debounce(function () {
         _this.fix();
        _this.fixSidebar(); }, 150));
````
Line 245 in app.js

**Comment by KrishnaPG** [comment]
Also, combining this below additional css for min-height animation makes the footer-height transition looks smooth 
````

.content-wrapper {
    -webkit-transition: min-height 0.2s ease-in-out;
    -o-transition: min-height 0.2s ease-in-out;
    transition: min-height 0.2s ease-in-out;
}
````

**Comment by LeonardoGentile** [comment]
@KrishnaPG where have you modified the  `.content-wrapper {...}`? Have you modified the .less or directly the .css?

**Comment by KrishnaPG** [comment]
I modified in the AdminLTE.css and used it.

**Comment by LeonardoGentile** [comment]
@kkirsche  :+1: thanks also for the `_.debounce` I didn't know about it

**Comment by KrishnaPG** [comment]
With the `.content-wrapper` ease-in-out animations the re-sizing happens smoothly (animated), but there is small problem - initially the size may be off (until the animation kicks-in with some resizing). So, for now I am just using the *debouncer* without the `.content-wrapper` animations.

**Comment by gusgol** [comment]
Another thing you can do is to set a min-height to your .content-wrapper
```
.content-wrapper {
    min-height: 738px;
}
```

**Comment by patforg** [comment]
If you do not want to use `_.debouce()` you can simply use the following:

```
 $(window).load(function() {
    setTimeout(function() {
        $.AdminLTE.layout.fix();
        $.AdminLTE.layout.fixSidebar();
    }, 250);
});
```
It re-flows the layout 250ms after window on load.

**Comment by lifesound** [comment]
@riotbr  worked as magic thx

**Comment by keomaborges** [comment]
I got a simply solution:

```
<style>
    .content-wrapper {
      min-height: 0px !important;
    }
  </style>
```

**Comment by marisveide** [comment]
Strange is that $(window).height changes if window is resized horizontally only. This is really giving bad visual result on the contents.

**Comment by davidjsalazarmoreno** [comment]
@patforg solution works for me, thanks!

**Comment by meyacine** [comment]
I've added this on css
```
.wrapper {
    width: 100%;
    min-height: 100%;
    height: auto !important;
    position: absolute;
}
.content-wrapper{
    bottom: 50px;
    position: fixed;
    width: 100%;
    top: 50px;
}
.main-footer{
    bottom: 0px;
    position: fixed;
    width: 100%;
}
```

**Comment by RahulS2017** [comment]
what is the issue that dark blue color which i define in body that color overlapping of left side nav 
![footer coming on up](https://cloud.githubusercontent.com/assets/25035263/22419594/41f85218-e704-11e6-84d6-474280d5860c.png)

**Comment by wonk4rol** [comment]
thanks @meyacine, i have issue with org chart n solved now.

**Comment by renopaslah** [comment]
just insert <!DOCTYPE html> before tag <html>

**Comment by jswxwxf** [comment]
thanks @meyacine, your solution is the easiest one. :)

**Comment by szanellato93** [comment]
resolved with @keomaborges solution and add to html body the background color of the content-wrapper

**Comment by LaeraFelipe** [comment]
`ngOnInit() {
    $('body').layout('fix');
  }`

**Comment by asdiyanarisha** [comment]
@dovalgomes thanks its worked for me, i put that code in my js

**Comment by ipsosweb** [comment]
html,
body,
.wrapper {
  min-height: 100%;
}

.wrapper {
  position: relative;
}

.wrapper .content-wrapper {
  min-height: calc(100vh - 112px);
}

**Comment by haythemgalelem** [comment]
> I've added this on css
> 
> ```
> .wrapper {
>     width: 100%;
>     min-height: 100%;
>     height: auto !important;
>     position: absolute;
> }
> .content-wrapper{
>     bottom: 50px;
>     position: fixed;
>     width: 100%;
>     top: 50px;
> }
> .main-footer{
>     bottom: 0px;
>     position: fixed;
>     width: 100%;
> }
> ```
