### ISSUE TITLE
Input with autofocus makes "content-wrapper" slide

### ISSUE THREAD

**Issue by sabinejansen** [almasaeed2010/AdminLTE#598]
Hello,

I have a form in the "content-wrapper". When I add autofocus="true" to an input element the whole "content-wrapper" slides from the left side of the page (under the sidebar) to the correct position. I don't what to have it sliding when I just add an autofocus. Can this be fixed?

**Comment by almasaeed2010** [comment]
Hi,

I tested on the general form elements page but nothing happened. It worked as expected. Could you show a screenshot of the issue?

Thanks!

**Comment by sabinejansen** [comment]
Here is a screenshot, you see that the form is first behind the sidebard and then the next image it is on the correct spot. I have tested this in FF39 and Chrome 44

![slide](https://cloud.githubusercontent.com/assets/1378961/8900902/902a1a62-3444-11e5-8feb-99d32fa519d1.png)
![slide_done](https://cloud.githubusercontent.com/assets/1378961/8900903/904f5a2a-3444-11e5-9268-07bc9b9d6df6.png)

The code that I used: http://pastebin.com/eqpchBQ5

**Comment by almasaeed2010** [comment]
This looks like a markup issue. I'd be more able to help if I had the produced html.

I apologize for the long delay.

**Comment by sabinejansen** [comment]
Here is the HTML again http://pastebin.com/92SZUbDj and http://pastebin.com/gE1BNMym

**Comment by almasaeed2010** [comment]
You might not be aware of this, but your code is hot linking resources from my website, which is unethical! Please correct that issue.

You have multiple html markup issues, which you need to address in order for us to better help you. 

I tested the code after removing incorrect markup. The result, which isn't reproducing your issue, can be seen below.

<img width="1440" alt="screen shot 2015-08-16 at 8 57 29 pm" src="https://cloud.githubusercontent.com/assets/1512664/9296368/8dd319e2-4459-11e5-976f-c98764204c92.png">

**Comment by josebailo** [comment]
This still happens with firefox and it's caused by a [browser bug](https://bugzilla.mozilla.org/show_bug.cgi?id=630493).

I'm affraid that until firefox fixs this bug we will be suffering the sliding.
