### ISSUE TITLE
Navigation issue in pixeladmin 

### ISSUE THREAD

**Issue by akilanvit** [almasaeed2010/AdminLTE#599]
when i am going to change nav menu with  search input-group icon before user icon and 3 select box in top nav is not aligned properly

**Comment by almasaeed2010** [comment]
We didn't design Pixeladmin. Please refer to the creator through the contact form on this page::
https://wrapbootstrap.com/user/smnedelko
You could also add a comment on this page:
https://wrapbootstrap.com/theme/pixeladmin-premium-admin-theme-WB07403R9/comments

Sorry for the inconvenience.
