### ISSUE TITLE
Release/Tag request for the last commit

### ISSUE THREAD

**Issue by sikko** [almasaeed2010/AdminLTE#600]
Hi,
My local AdminLTE has a bug that has been fixed with this commit:
https://github.com/almasaeed2010/AdminLTE/commit/a8406b410253400a37af0f5dd837ba223da6bb42#diff-6672a264b309a708765687d346984692

But bower still resolves to version 2.2.0 which has the bug.
Can you please make a tag for this?
Thanks

**Comment by almasaeed2010** [comment]
Hi,

I am going to create a new release after tests are performed. I appreciate your patience.
