### ISSUE TITLE
jQuery UI Theme

### ISSUE THREAD

**Issue by Karmalakas** [almasaeed2010/AdminLTE#601]
Any chance there will be jQuery UI custom theme for AdminLTE?
It would be nice to see all UI elements blended in :) I believe it's even possible to make color switching by adding prefix class to theme

**Comment by almasaeed2010** [comment]
Hi,

This would require major effort and time. I am sorry for the inconvenience but I don't think I will be able to add this feature.

Thanks for the suggestion.
