### ISSUE TITLE
Use of demo.js on production

### ISSUE THREAD

**Issue by tom-njoroge** [almasaeed2010/AdminLTE#602]
Good work Almasaeed for Admin template.I am wondering why is not advisable to use demo.js on production yet it gives users options?

**Comment by almasaeed2010** [comment]
Demo.js is not made for production. It doesn't allow for saving any of the options you choose, nor does it provide any configuration for that matter. I am not sure if I will be able to make it production ready, but I certainly will consider it. 

Thanks for the compliments and the suggestion.
