### ISSUE TITLE
Dropdown menu javascript problem

### ISSUE THREAD

**Issue by kgoedert** [almasaeed2010/AdminLTE#603]
Hi,

I am using admin LTE installed with bower in an angular application. My side menu looks like this:

```html
<aside class="main-sidebar" ng-controller="SideMenuController as sideCtrl">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="header">MENU</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Dashboards </span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu" >
          <li><a ui-sref="dash_qa"><i class="fa fa-circle-o"></i> QA</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Dashboards</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu" ng-repeat="proj in sideCtrl.projects">
          <li class="active">
            <a ui-sref="dashbordProjeto({id: '{{proj.projectId}}' })">
              <i class="fa fa-circle-o"></i> {{proj.name}}
            </a>
          </li>
        </ul>
      </li>

      <li class="active treeview">
        <a href="#">
          <i class="fa fa-edit"></i> <span>Registration</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a ui-sref="projeto"><i class="fa fa-circle-o"></i> Projects</a></li>
        </ul>
      </li>
    </ul>
  </section>
</aside>
```

The menu is show but when I click on the arrows nothing happens. All the scripts appear to have been imported correctly on index.html. There are no errors on the browser console.

**Comment by almasaeed2010** [comment]
Try reactivating the sidebar treeview after all the links have loaded:

```js
$.AdminLTE.tree('.sidebar');
```

**Comment by kgoedert** [comment]
I tried it, and it did not work. Same behavior as before

**Comment by almasaeed2010** [comment]
Have you resolved the issue? If not, I may be able to help if you provide some kind of access to a page so I can view errors or markup mismatch. 

Thanks.

**Comment by AlexPachon** [comment]
Hello Abdullah.
Thank you very much for your AdminLTE template. I am an admirer of your work. I have a problem with the menu on the left (sidebar-menu) when reloaded the page, the menu disappears. You think is happening?.
![error](https://cloud.githubusercontent.com/assets/13852658/12360713/99b1d3ac-bb87-11e5-8414-52a01e8b091e.JPG)
