### ISSUE TITLE
How to Remove Left Side bar completely 

### ISSUE THREAD

**Issue by kennedymca** [almasaeed2010/AdminLTE#604]
i need to remove left side bar completely in  my project,
Above 768 screen resolution also

**Comment by almasaeed2010** [comment]
Hi,

Try using the ```layout-top-nav``` option. Documentation: https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#component-main-header

**Comment by kennedymca** [comment]
where i put this line "layout-top-nav"

**Comment by rafael-renan-pacheco** [comment]
Ctrl+f + "layout-top-nav"

"To use this main header instead of the regular one, you must add the layout-top-nav class to the body tag"

**Comment by almasaeed2010** [comment]
You should also make sure that you are using the correct HTML markup. This can be found in the [pages/layout/top-nav.html](https://github.com/almasaeed2010/AdminLTE/blob/master/pages/layout/top-nav.html).

**Comment by kennedymca** [comment]
thank u

**Comment by chung311096** [comment]
I have done it. thank you

**Comment by udornb** [comment]
to clarify : open file _Layout.csml //   todo step 
1. change <body class="hold-transition sidebar-mini"> to <body class="hold-transition layout-top-nav"> 
2. remove : @Html.Partial("_NavBar") 
2. remove : @Html.Partial("_SideBar")
