### ISSUE TITLE
Regarding your free control panel template

### ISSUE THREAD

**Issue by NivinDennison** [almasaeed2010/AdminLTE#605]
Great work people. I have certain clarifications. I saw one of your free control panel template from your official website. U have mentioned it as an open source product. 1. Can I use that template for my commercial purpose. 2. Do I have rights to modify the template according to my needs.

**Comment by exilod** [comment]
I am also interested in a response on this topic.

**Comment by n3storm** [comment]
At file README.md you can read that template is licensed under MIT lincense with a link to the text. Reading first paragraph will clarify your doubts.

**Comment by jlamer** [comment]
This software is licensed under MIT license. Check this link for summarization: https://tldrlegal.com/license/mit-license
