### ISSUE TITLE
Need to show fa-bars and nav bar list above 768 resolution in top-nav layout

### ISSUE THREAD

**Issue by kennedymca** [almasaeed2010/AdminLTE#606]
i am using top-nav layout from our adminLTE,
i need to show below image view in screen resolution above 768.

![test](https://cloud.githubusercontent.com/assets/6284528/8928111/d2c8f0aa-3539-11e5-8e97-b902695f96dc.png)

**Comment by almasaeed2010** [comment]
Are you familiar with LESS? If so, you will need to adjust the ```@grid-float-breakpoint``` variable in the bootstrap variable.less file. Then you need to recompile bootstrap and use the generated css file. 

Another way to do it is through here: http://getbootstrap.com/customize/#grid-system
Change the ```@grid-float-breakpoint``` value to the number you want and download the bootstrap.css custom file.
