### ISSUE TITLE
Padding on the top after customize paths on AdminLTE 2.2.0

### ISSUE THREAD

**Issue by JuKu** [almasaeed2010/AdminLTE#607]
Hi,

I had to customize adminlte 2.2.0 for my use.
The templates files are located in tpl/admin/ and not in the base dir / .
I have customized all paths in the index.html, but it doesnt works.
Currently you can access the code in the browser, if you call http://pizza-lieferante.chipbyte.de/shopsystem/admin/home .
Also some plugins like the visitor widget doesnt work.
Thanks for help!

![adminlte22](https://cloud.githubusercontent.com/assets/1138046/8931199/b5a1072e-3534-11e5-9ee9-b5e61c9b1f88.PNG)

**Comment by jlamer** [comment]
Check the developer console. Do you see any errors here?

Unfortunately, there is some PHP error on your page so I can't do it.

**Comment by JuKu** [comment]
Hi,

thanks for your answer!
I have resolved this issues.
No the padding isnt there anymore, but the widgets are already empty.

**Comment by jlamer** [comment]
Yes, I see, as I said, there is an error in the console:

```
http://pizza-lieferante.chipbyte.de/shopsystem/tpl/admin/https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

I think you rewrote path you shouldnt. As you can see, moment.js is loaded from cdn so there is no need to change anything. I am speaking about line 813 - daterangepicker. Just delete **http://pizza-lieferante.chipbyte.de/shopsystem/tpl/admin/**.

**Comment by JuKu** [comment]
Hi,

thank you!
Now it works.

![adminlte22](https://cloud.githubusercontent.com/assets/1138046/9021730/229ab17e-3853-11e5-89b0-838bbb9e16a6.PNG)

**Comment by jlamer** [comment]
Glad I could help :+1:
