### ISSUE TITLE
Autocomplete jQuery-ui in sidebar

### ISSUE THREAD

**Issue by lbc693** [almasaeed2010/AdminLTE#609]
Hi,
I have implemented the Autocomplete Widget of jQuery-ui, http://api.jqueryui.com/autocomplete/.
The list with autocomplete suggestions doesn't appear if I put it in sidebar. It has been verified to work in other locations of the page.
There is an example in http://jsfiddle.net/u4rvtdyv/1/.
Thanks for help!

**Comment by fschaeffer** [comment]
Most likely a css issue if it is working elsewhere. To check open dev tools and see whether a div is generated for the selection items. If yes try to increase the z-Index for this div...

**Comment by lbc693** [comment]
Thanks, I have fixed it adding

.ui-autocomplete {
    z-index:900 !important;
}
