### ISSUE TITLE
select2 input doesn't change height size!

### ISSUE THREAD

**Issue by douglasduartetb** [almasaeed2010/AdminLTE#612]
After select all input options and the elements exceeds the size of width, the select input break line but, the size of height continues intact.

http://i.imgur.com/hJCrwJB.png

**Comment by yajra** [comment]
Try adding select2 assets from this link. It works for me and might help you too. https://fk.github.io/select2-bootstrap-css/

**Comment by douglasduartetb** [comment]
I try, but nothing looks like work

**Comment by douglasduartetb** [comment]
I tried with another version of select2 (3.5.2), and works nicely. Now i just will wait for new versions, then i will test.
