### ISSUE TITLE
Horizontal Scroll Bar in Content

### ISSUE THREAD

**Issue by grcgsite** [almasaeed2010/AdminLTE#613]
How to use browser's horizontal scroll bar if the text overlap the width on the browser?
Thank you

**Comment by almasaeed2010** [comment]
Please clarify your question.

**Comment by rafael-renan-pacheco** [comment]
AdminLTE uses Bootstrap
Bootstrap is responsive
If your text tries to overlap the screen width, it will be wraped around.

In order to avoid this behavior, you may try to add custom css to your text container, like "overflow-x: scroll".

**Comment by IntegrityFoundation** [comment]
I am using yii2 basic.

I have installed Admin LTE and is working.

Now I have Employee CRUD. When admin views the view of particular employee, then the details are going out of the screen horizontally i.e, there is no horizontal scrollbar to scroll the page to view the details completely.

How to accomplish this?
