### ISSUE TITLE
How to update number of Message

### ISSUE THREAD

**Issue by merymaid** [almasaeed2010/AdminLTE#614]
![capture](https://cloud.githubusercontent.com/assets/12604366/9021193/d760578a-37ea-11e5-9a55-e55a0ed66a0e.JPG)
Hi All,

I'm working on an AngjularJS project.  I try to update the Number of Message on top layer.  I have setup a time clock.  But I can not automatic update the number of message and other.  Everytime flash whole page the number can be updated.  Any idea about this?  Thanks.

Best regards,
Bill

**Comment by merymaid** [comment]
I try to use viewbag to send update number.  But the result was not updated?  Any suggestion for automatic update result?

**Comment by almasaeed2010** [comment]
Hello,

You probably should ask this question at any AngularJS forum or at [stackOverflow](http://stackoverflow.com/).
