### ISSUE TITLE
Remove Cross domain glyphicon source

### ISSUE THREAD

**Issue by mdjaman** [almasaeed2010/AdminLTE#615]
Hi can you please replace this code in /css/boootstrap.min.css
```
src:url(http://almsaeedstudio.com/themes/AdminLTE/bootstrap/fonts/glyphicons-halflings-regular.eot);src:url(http://almsaeedstudio.com/themes/AdminLTE/bootstrap/fonts/glyphicons-halflings-regular.eot?#iefix)
```
by adding corresponding files in fonts/ directory

**Comment by almasaeed2010** [comment]
Hi,
I am not sure where you are using this line of code but it isn't in the AdminLTE.css file nor is it in the attached bootstrap.min.css file.
