### ISSUE TITLE
sidebar-mini state should be persistent

### ISSUE THREAD

**Issue by dschallert** [almasaeed2010/AdminLTE#617]
Currently when the sidebar is minimized (sidebar-mini) and the page is refreshed, the sidebar's state will not be restored, which means the sidebar is expanded again.

For persistance basically we just need an LSO or even a cookie to store the current state and restore it after a page was reload.

What do you think?

**Comment by YasserHassan** [comment]
You need to do that on the server side. Refer to #315.

**Comment by almasaeed2010** [comment]
As @YasserHassan said, this is a back-end issue. Doing that in the front-end would cause unwanted transitions to occur during reload. Thanks!
