### ISSUE TITLE
RTL Version

### ISSUE THREAD

**Issue by lxsameer** [almasaeed2010/AdminLTE#618]
Hey folks. It's been while since we're using AdminLTE in production, both LTR and RTL. But making RTL version from the vanilla one is a bit troublesome so we made a Ruby gem for it.

https://github.com/Yellowen/admin_lte-rails

This [gem](https://github.com/Yellowen/admin_lte-rails) created to be used with **Rails** and contains both LTR and RTL version with support for **SASS/SCSS** and autamatically convert LTR version to RTL. So it will keep up with the upstream version.

Generally I you're not a **Rails** user you can still take advantage of this gem by using **sprockets** or by just copy and paste the converted source into your project manually.

Please take a look at `app/assets` directory.

**Comment by almasaeed2010** [comment]
Thanks for sharing!

**Comment by yassermat** [comment]
Thanks for sharing, 
Can we have compiled versions as well, so that we don't go through learning what is gem and how to convert.
Many thanks

**Comment by lxsameer** [comment]
Hi, You can clone the repository and install the dependencies. After that by executing `rake convert`
inside the repository source tree it will fetch the latest AdminLTE code and convert it to RTL.

Then you'll have both LTR and RTL version with SCSS, for compilation you can use any minifier that you like inside your own project.

**Comment by yassermat** [comment]
I am really stuck at the last part:
http://stackoverflow.com/questions/34924952/convert-a-ruby-gem-to-be-used-as-template-in-asp-net

**Comment by lxsameer** [comment]
@yassermat you don't need to convert anything. Just clone the gem repository, install the dependencies, and convert the latest version of AdminLTE using `rake convert` command, and copy the result stylesheets and javascripts into you asp project.

**Comment by yassermat** [comment]
Thanks,
My email address is Yassermat [at] Gmail [dot] com
I copied those converted files, but the result was not good at all!
Did I miss any thing in the process, please check my SO post and tell me if I have done any thing wrong.
Many Thanks

**Comment by sandrobilbeisi** [comment]
after running `rake convert` the file the file at "admin_lte-rails-master/app/assets/stylesheets/admin_lte/rtlAdminLTE.scss"
gets zeroed (no content)
