### ISSUE TITLE
Table tools not showing correctly

### ISSUE THREAD

**Issue by FireFoxII** [almasaeed2010/AdminLTE#621]
Hi and sorry for my english

I'm using the 3 buttons of tabletools copy/print/save but this not showing correctly...

![ttols](https://cloud.githubusercontent.com/assets/4954095/9105512/c87557a2-3c18-11e5-9cb3-8878c3b1fafd.png)

It is not aligned to the right

Also on these 3 buttons, translations doesn't work

**Comment by Dennis14e** [comment]
Maybe [this page](http://www.datatables.net/release-datatables/extensions/TableTools/examples/bootstrap.html) helps you.
