### ISSUE TITLE
overflow-x and overflow-y

### ISSUE THREAD

**Issue by adminko-svk** [almasaeed2010/AdminLTE#623]
Hi Abdullah,
thank you for your great admin theme.
I have a quick question - why you need in CSS `overflow-x` and `overflow-y`?
Because I have `jQuery UI sortable table` and there cannot be used `overflow-x` and `overflow-y`.
Thank you.

**Comment by almasaeed2010** [comment]
Hello,
You can try removing them. This is just a way to guarantee unwanted horizontal scrolls.
