### ISSUE TITLE
Auto Re sizing Not working in Mobile Device

### ISSUE THREAD

**Issue by freebumba27** [almasaeed2010/AdminLTE#629]
I have implemented the website every thing fine in desktop but in mobile version it's not resisting automatically? 
To test this please run the preview in your android Chrome.(Make sure it's not in Desktop mode.) You might think it's giving perfect result http://responsivetest.net/ But you are wrong you should try in real device then only you can fill. 
Is there any way to enable it?

**Comment by almasaeed2010** [comment]
Hello,
What is the part that's not resizing correctly? 
The template is tested on Chrome on Android and iOS before every release. I'd appreciate some more description on the issue.

Thanks.

**Comment by freebumba27** [comment]
I just resolved the issue Problem was with meta tag I have added -
<meta name="viewport" content="width=device-width, initial-scale=1">

Result is here 
Before - 
![before](https://cloud.githubusercontent.com/assets/12707934/9234616/73954bae-4157-11e5-9bc2-468d61aadb9e.PNG)

After - 
![after](https://cloud.githubusercontent.com/assets/12707934/9234622/7a914ff2-4157-11e5-9813-ae2d1dd00142.PNG)

**Comment by almasaeed2010** [comment]
You may want to test the actual package through https://almsaeedstudio.com/themes/AdminLTE/index2.html instead of using the iFrame preview. You could also just remove the iframe via the "x" button at the top. Thanks for sharing this!
