### ISSUE TITLE
Hosting in IIS is not showing properly

### ISSUE THREAD

**Issue by savakar123** [almasaeed2010/AdminLTE#633]
I am using ADMIN LTE bootstrap in my MVC application. After publishing through file system its not showing properly. While testing under development environment using vs2013 its work perfect.

Can you please suggest anything I missed for publish through file system?

Thanks
Sachin

**Comment by almasaeed2010** [comment]
Hello,
What's not showing properly? You could provide a screenshot and the produced HTML markup. This will make it easier and faster for us to help you.

Thanks.

**Comment by lmz5428888** [comment]
![image 3](https://cloud.githubusercontent.com/assets/11496832/9405315/61904958-4829-11e5-81d8-4f1bddd6a2c9.png)

**Comment by lmz5428888** [comment]
it is work properly if you use Google Chrome, but IE browser. and if you use IP to open the website, it is  work properly. but not work in hostname.
Look forward to your help, thank you very much!!!

**Comment by almasaeed2010** [comment]
From the screenshot I can tell that there are multiple resources that have not been loaded properly. AdminLTE 1.x doesn't provide the proper protocols for the included resources. For example, to load the Font Awesome icons, you need to add ```https://``` in front of the CDN link in ```<head>```. The same goes for jQuery and any resources pulled from a CDN.

You can view the non-properly downloaded resources from the console.

By the way, why did you choose to use an old version of AdminLTE?

**Comment by lmz5428888** [comment]
@almasaeed2010 
Thanks for reply.
i will retry it Tomorrow. Now is the middle of the night.
Our country has restrictions on the network, We can not visit Facebook, youtube...
I just found this old version. so... 
AdminLTE is good thing. I am very excited to find it.

**Comment by almasaeed2010** [comment]
You can find the latest releases here https://github.com/almasaeed2010/AdminLTE/releases
