### ISSUE TITLE
Select2: multiple height problem

### ISSUE THREAD

**Issue by douglasduartetb** [almasaeed2010/AdminLTE#636]
I had some problems with select2 when i use with multiple attribute , but i used some crazy things(go-horse), that was fixed.

```javascript
$('.your-select-element').on('change', function(){
    var hgt = $(".select2-selection__rendered")[0].scrollHeight + 5;
    $('.select2-container--default .select2-selection--multiple').css('height', hgt + 'px');
});

var hgt = $(".select2-selection__rendered")[0].scrollHeight + 5;
$('.select2-container--default .select2-selection--multiple').css('height', hgt + 'px');
```
before:
http://prntscr.com/85gucs

after:
http://prntscr.com/85guds

;)

**Comment by almasaeed2010** [comment]
Hello,

The newest release corrects that problem. Try updating and let me know.

**Comment by douglasduartetb** [comment]
already updated to v 2.2.1, but the problem continues, with this fix i can prevent for a while

**Comment by almasaeed2010** [comment]
The fix could be in Master. I know we resolved this issue. I can't remember the issue number. The new release should be out tonight. I'd appreciate it if you try the upcoming release with this issue.

**Comment by douglasduartetb** [comment]
after release i'll test, thanks ;)

**Comment by douglasduartetb** [comment]
I tested master version and works perfectly , thanks ;)

**Comment by almasaeed2010** [comment]
I appreciate your patience. I just released the new version after being tested on the supported browsers. Be sure to checkout the new features.

Thanks!

**Comment by OliverYGM** [comment]
when would the new version be released?

**Comment by almasaeed2010** [comment]
@OliverYGM probably a few months after the release of BS4.
