### ISSUE TITLE
HTML linter for Bootstrap projects

### ISSUE THREAD

**Issue by Leftyx** [almasaeed2010/AdminLTE#638]
I always use the linter for Bootstrap in my twbs project.
This is the script to include in the body (before the closing tag of the body):

      <script type="text/javascript">
            (function(){var s=document.createElement("script");s.onload=function(){bootlint.showLintReportForCurrentDocument([],{problemFree:false});};s.src="https://maxcdn.bootstrapcdn.com/bootlint/latest/bootlint.min.js";document.body.appendChild(s)})();
      </script>

It seems there are a few problems with the validation.

I've noticed you don't use a container inside a navbar as suggested in the [documentation](http://getbootstrap.com/components/#navbar).

**Comment by almasaeed2010** [comment]
Hello @Leftyx,

That's a great suggestion and we will for sure consider it! I wonder if there is a grunt task for it though.

The container provides the needed paddings and margins in case the layout uses a specific width. It is also used to provide rows with the negative margins they need to properly fit the page. In our case, we added the margins to the necessary wrappers so there is no need to use a container.

**Comment by almasaeed2010** [comment]
Added

**Comment by kressly** [comment]
Has this been fixed ?

**Comment by almasaeed2010** [comment]
It's not really an issue. It's just guidelines

**Comment by kressly** [comment]
Ok thanks and Almasaeed u are still the best
