### ISSUE TITLE
Not working in laravel for large url address

### ISSUE THREAD

**Issue by salambdm** [almasaeed2010/AdminLTE#642]
I am new in laravel. I have tried to use adminLTE in laravel. It works fine for small route like-
example.dev/home
or, 
localhost/myapp/public/home.
or, route('/home')

But it's not working for the address like- 
example.dev/user/home 
or,
localhost/myapp/public/user/home
or, route('/user/home')
or, any large url.

I don't know why, please help me.

**Comment by almasaeed2010** [comment]
Hello @salambdm 
This is mainly a backend PHP issue. You may want to try our tutorial on Integrating [AdminLTE with Laravel](https://almsaeedstudio.com/blog/integrate-adminlte-with-laravel).

If you still encounter problems, please provide us with some more description, screenshots and code. 
Thanks!

**Comment by salambdm** [comment]
Thank you so much brother, for your response. 
I have installed a fresh laravel 5.1 sometimes ago.
Added  the downloaded copy of AdminLTE theme in public folder, then copy the html code from index.html of theme into laravel's welcome view page.
After that, I have tested the theme by changing the route and final results are same which I explained before.
It's maybe laravel's internal issue but I want to use your theme, because it's a great theme.

![1](https://cloud.githubusercontent.com/assets/13893798/9410598/e78aad46-4842-11e5-916c-af1efb0a0edd.png)
![2](https://cloud.githubusercontent.com/assets/13893798/9410606/efc1d85e-4842-11e5-8f82-a51a6e9c9ba5.png)
![3](https://cloud.githubusercontent.com/assets/13893798/9410611/f6bb5a22-4842-11e5-8e9c-d5cd209bb1e7.png)
![4](https://cloud.githubusercontent.com/assets/13893798/9410622/ffeb741a-4842-11e5-9783-527a0c5b651f.png)

**Comment by YasserHassan** [comment]
@salambdm you don't just copy and paste the static HTML code into Laravel to make it work. Using fixed hard-coded routes to asset files will most probably break it in a situation or another. You need to use Laravel's own way of referring to assets. Try something like `asset('img/photo.jpg')` as mentioned in http://laravel.com/docs/5.1/helpers#method-asset so assets locations are dynamically linked inside each page according to the page they are called in.

This is mainly a Laravel issue. As @almasaeed2010 mentioned, you better refer to the blog post he referred to or another resource for that.

**Comment by salambdm** [comment]
@YasserHassan, 
Thanks for your valuable suggestions, brother. My problem is solved. Yes, I have used asset('asset files') helpers and everything is ok now.
