### ISSUE TITLE
sidebar not till its full height

### ISSUE THREAD

**Issue by niks-codificador** [almasaeed2010/AdminLTE#643]
the sidebar is not getting displayed  to full height. 
![screenshot from 2015-08-20 16 24 33](https://cloud.githubusercontent.com/assets/8406899/9402455/45e8fcf0-47fb-11e5-9bbc-391ae16dd571.png)

**Comment by almasaeed2010** [comment]
Hello,
It may be easier for us to help you if you give us access to the page. I can't determine the issue just from a screenshot.

Thanks!

**Comment by FalconDev91** [comment]
I'm having the same problem.When I resize the window by double clicking the title bar the sidebar height is incorrect and I've been trying all day to fix it but still no luck!  :(
![image](https://cloud.githubusercontent.com/assets/13089930/9445471/f9b51312-4aa9-11e5-90bc-bec4ab1248bf.png)

**Comment by FalconDev91** [comment]
@niks-codificador Did you fix it?

**Comment by niks-codificador** [comment]
@FalconDev91 not yet. Even I banged my head to get it fixed.

**Comment by niks-codificador** [comment]
@FalconDev91 I figured the error out. Yeah it quite late, like after months. 
Put sidebar code in wrapper class. See below
<div class="wrapper">
<aside class="main-sidebar"></aside>
</div>
Hope it helps you. it helped me. Thanks @almasaeed2010  for this amazing template.

**Comment by Wirwing** [comment]
@niks-codificador could you please paste a code snippet on how to add this wrapper class? I'm having the same trouble with short-height sidebar. :(

**Comment by crazymao** [comment]
I'm still having this issue on 2.3.3, putting the sidebar in wrapper class does not work for me:

<img width="1279" alt="screen shot 2016-06-02 at 23 11 13" src="https://cloud.githubusercontent.com/assets/770255/15769329/5f493bc6-2917-11e6-8029-6b4f3b69accd.png">

**Comment by niks-codificador** [comment]
Share your code so that I could help you with!

**Comment by felipebest** [comment]
I managed to do it using jQuery. Simply get the height of the current document once it is loaded and then assign that height to the sidebar. 

`jQuery(document).ready(function($){
    $('.main-sidebar').height($(document).outerHeight());
});`

In my case the sidebar has a class of main-sidebar. You can change it to your value.

**Comment by andresabello** [comment]
I managed to do it using jQuery. Simply get the height of the current document once it is loaded and then assign that height to the sidebar.

jQuery(document).ready(function($){ $('.main-sidebar').height($(document).outerHeight()); });

In my case the sidebar has a class of main-sidebar. You can change it to your value.

**Comment by a1292717155** [comment]
@nikhilshirsath1993 did you fix it?

**Comment by faviocabral** [comment]
aside class="main-sidebar sidebar-dark-primary elevation-4" style="margin-top:0px;"

funciono para mi 

works for me.
![image](https://user-images.githubusercontent.com/17582277/81342949-19219180-9082-11ea-9ed1-2b7dd29f1f42.png)

**Comment by mohsinyaqoob** [comment]
> @FalconDev91 I figured the error out. Yeah it quite late, like after months.
> Put sidebar code in wrapper class. See below
> 
> Hope it helps you. it helped me. Thanks @almasaeed2010 for this amazing template.

Worked for me thanks ✅
