### ISSUE TITLE
No-one ever asked for a goto-top, floating bottom? (Fixed footer request)

### ISSUE THREAD

**Issue by andreabioli** [almasaeed2010/AdminLTE#644]
I couldn't find any request... :-)

**Comment by Leon-O** [comment]
is because that is a non-enterprise feature: almost every admin site has the length of the screen so you don't need to play with the scrollbars. Also, the goto-top is a feature for reading, no for administration.

**Comment by almasaeed2010** [comment]
Hello,

As @Leon-O suggested, it is not a very common use of goto-top buttons in admin templates. However, we are planning on implementing a fixed footer I get many requests over email for it.

By the way, you can easily implement a goto-top button like the one used in the documentation of AdminLTE. Here is the code we use to do that:

```js
$(function() {
var slideToTop = $("<div />");
  slideToTop.html('<i class="fa fa-chevron-up"></i>');
  slideToTop.css({
    position: 'fixed',
    bottom: '20px',
    right: '25px',
    width: '40px',
    height: '40px',
    color: '#eee',
    'font-size': '',
    'line-height': '40px',
    'text-align': 'center',
    'background-color': '#222d32',
    cursor: 'pointer',
    'border-radius': '5px',
    'z-index': '99999',
    opacity: '.7',
    'display': 'none'
  });
  slideToTop.on('mouseenter', function () {
    $(this).css('opacity', '1');
  });
  slideToTop.on('mouseout', function () {
    $(this).css('opacity', '.7');
  });
  $('.wrapper').append(slideToTop);
  $(window).scroll(function () {
    if ($(window).scrollTop() >= 150) {
      if (!$(slideToTop).is(':visible')) {
        $(slideToTop).fadeIn(500);
      }
    } else {
      $(slideToTop).fadeOut(500);
    }
  });
  $(slideToTop).click(function () {
    $("body").animate({
      scrollTop: 0
    }, 500);
  });
  $(".sidebar-menu li:not(.treeview) a").click(function () {
    var $this = $(this);
    var target = $this.attr("href");
    if (typeof target === 'string') {
      $("body").animate({
        scrollTop: ($(target).offset().top) + "px"
      }, 500);
    }
  });
});

**Comment by andreabioli** [comment]
Wonderful! And very very fast! :-) Thank you really very very much!
(The only thing that I don't agree upon is that this is not an enterprise feature... even in a site like this, you can end up with very long pages... like, for example, in the documentation!!! :-) I didn't see there was one just there! :-) )

**Comment by SirTom76** [comment]
There is a little mistakeat the end:

`$(slideToTop).click(function () {
    $("body").animate({
      scrollTop: 0
    }, 500);
  });
  $(".sidebar-menu li:not(.treeview) a").click(function () {
    var $this = $(this);
    var target = $this.attr("href");
    if (typeof target === 'string') {
      $("body").animate({
        scrollTop: ($(target).offset().top) + "px"
      }, 500);
    }
  });
});`

The right code is:

`$(slideToTop).click(function () {
    $("html. body").animate({
      scrollTop: 0
    }, 500);
  });
  $(".sidebar-menu li:not(.treeview) a").click(function () {
    var $this = $(this);
    var target = $this.attr("href");
    if (typeof target === 'string') {
      $("html, body").animate({
        scrollTop: ($(target).offset().top) + "px"
      }, 500);
    }
  });
});`

It is working perfect!
