### ISSUE TITLE
Treeview menus do not collapse when a user clicks on a non-tree view menu item

### ISSUE THREAD

**Issue by ciwolsey** [almasaeed2010/AdminLTE#646]
How to reproduce:

1) Click to expand a tree view menu on the side bar.
2) Click a menu item that is not a tree view (such as a regular menu item)

While the menu item under the tree menu loses its highlight the treeview itself does not.

Here is a screenshot: http://i.imgur.com/cdXbGX5.png

This is a result of expanding the "Applications" tree view, then immediately clicking on "Home". I'm left with two menu items highlighted when it should just be "Home". The menu should probably also collapse.

**Comment by almasaeed2010** [comment]
Thanks for reporting the issue. I'll get to it when I get a chance.

**Comment by iamgoodbytes** [comment]
@ciwolsey can you reproduce this behaviour in the adminlte preview https://almsaeedstudio.com/preview ? If I can reproduce it there, I'll take a look at it.

**Comment by ciwolsey** [comment]
My application is single page. So when a user visits a link only the content area of the page is refreshed. This differs from your multi-page example. The difference is the links on your pages actually cause page refreshes / reloads whereas my app only alters what's inside the content area. The bug doesn't exist in your preview because new requests are sent and the entire menu is reloaded whereas my menu just continues to exist.
