### ISSUE TITLE
Error in $(a.BSTooltipSelector).tooltip()

### ISSUE THREAD

**Issue by iaesaudi** [almasaeed2010/AdminLTE#649]
I got this error in console and some scripts after loading app.min.js script not working.

```
[Error] TypeError: undefined is not a function (evaluating '$(a.BSTooltipSelector).tooltip()')
	(anonymous function) (app.min.js, line 13:4249)
	j (datatables.min.js, line 14:27315)
	fireWith (datatables.min.js, line 14:55002)
	ready (datatables.min.js, line 14:29968)
	J (datatables.min.js, line 14:30328)
```

I'm Using AdminLTE 2.0.4
DataTables 1.10.8

**Comment by almasaeed2010** [comment]
Please make sure you have bootstrap.js loaded before loading app.min.js

**Comment by iaesaudi** [comment]
loaded in this sequence:
jQuery
Bootstrap
DataTables
FastClick
App

**Comment by iaesaudi** [comment]
I have updated to AdminLTE to latest version 2.3.0 and rearranged loading scripts as below:
-jQuery
-Bootstrap
-AdminLTE
-PACE
-FastClick
-SlimScroll
-DataTables
and I got this error:
```
[Error] TypeError: undefined is not an object (evaluating '$.AdminLTE.options')
	(anonymous function) (app.min.js, line 13:6646)
	j (jQuery-2.1.4.min.js, line 2:27195)
	fireWith (jQuery-2.1.4.min.js, line 2:28004)
	ready (jQuery-2.1.4.min.js, line 2:29808)
	I (jQuery-2.1.4.min.js, line 2:29993)
```

**Comment by almasaeed2010** [comment]
Are you using RequireJS or similar scripts?

**Comment by iaesaudi** [comment]
No, But this issue is related to DataTables new version.
If you updated the plugin, you will encounter the same issue.
