### ISSUE TITLE
Data Table With Full Features

### ISSUE THREAD

**Issue by kingramizy** [almasaeed2010/AdminLTE#650]
Hello everyone,
I fail to integrate into my site, the table given as example "Data Table With Full Features"
somebody already had this problem?
is it a problem of import javascript function?

**Comment by almasaeed2010** [comment]
Hi,

Please provide the errors you get in the browser's console.

**Comment by kingramizy** [comment]
I have only one error in the console and I do not think that a relationship with my problem:
"Unexpected CSS token: : "

**Comment by almasaeed2010** [comment]
What is the problem that you are having?

**Comment by kingramizy** [comment]
in the example, the table has a search form
displays 10 inputs and can be navigated between inputs
You can change the order of entries compared to a colone (with the button in the securities of colone)

I just have a table without any of the previously mentioned elements.

**Comment by almasaeed2010** [comment]
Did you activate the plugin?

**Comment by almasaeed2010** [comment]
```js
$('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
});
```

**Comment by kingramizy** [comment]
OH it works !!!!
I just have a problem position for research and page numbers

**Comment by almasaeed2010** [comment]
Provide a screenshot please

**Comment by kingramizy** [comment]
![capture d ecran 2015-08-25 a 01 24 21](https://cloud.githubusercontent.com/assets/9628047/9455104/16b3c99a-4ac8-11e5-9ddf-cd729bab5976.png)

**Comment by almasaeed2010** [comment]
That's odd
I am having dinner right now. I'll check it out later

Post the code for the HTML table please

**Comment by kingramizy** [comment]
My html code for table : 


```HTML
<div class="row">
   <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Indices</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <table id="example2" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>status</th>
                <th>Cours</th>
                <th>Variation</th>
              </tr>
            </thead>
            <tbody>
              <?php
                get_indices_info_tbl()
              ?>
            </tbody>
            <tfoot>
              <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>status</th>
                <th>Cours</th>
                <th>Variation</th>
              </tr>
            </tfoot>
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>
```

**Comment by jlamer** [comment]
The last time I had similiar issue it was caused by missing CSS file. Just check everything is linked and rules were applied in developer console.

**Comment by ahmadsayeed3** [comment]
i want to disable the sorting feature, because its change order from database query order.
i just want to disable sorting nothing else 
Thank you

**Comment by jlamer** [comment]
Please check https://datatables.net/reference/option/ordering ... you have to add ""ordering": false" to options when initializing and sorting will be disabled for whole datatable.

**Comment by ahmadsayeed3** [comment]
thank you for replay , added but still sorting

$("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false,
		"ordering": false
                });

**Comment by jlamer** [comment]
Why is "bSort": true? It should be false, right?

**Comment by ahmadsayeed3** [comment]
Still sorting in asc order 

$("#example1").dataTable();
$('#example2').dataTable({
"bPaginate": true,
"bLengthChange": false,
"bFilter": false,
"bSort": false,
"bInfo": false,
"bAutoWidth": false,
"ordering": false
});

**Comment by ahmadsayeed3** [comment]
worked sorry , that parameter works but in my case i stuck with browser cache , thank you
