### ISSUE TITLE
update npmjs to version 2.3.0

### ISSUE THREAD

**Issue by gabel** [almasaeed2010/AdminLTE#659]
Hi,

the package.json is up2date, but it have to published to npm.js (https://www.npmjs.com/package/admin-lte).

Simple:
```
npm adduser
npm publish
```
Done.

Thanks in advance..

**Comment by almasaeed2010** [comment]
Done. Thanks for reminding me.

**Comment by gabel** [comment]
np :+1:  thx

**Comment by gabel** [comment]
@almasaeed2010 to keep an eye on it you could add a badge to the readme.md

[![npm](https://img.shields.io/npm/v/admin-lte.svg)](https://www.npmjs.com/package/admin-lte)

Makdown: `[![npm](https://img.shields.io/npm/v/admin-lte.svg)](https://www.npmjs.com/package/admin-lte)`

**Comment by johnberberich** [comment]
@gabel, I just submitted a [pull request](https://github.com/almasaeed2010/AdminLTE/pull/991) to get Bower, NPM and Packagist version badges into the README.md.
