### ISSUE TITLE
Mini Sidebar + Fixed issue

### ISSUE THREAD

**Issue by iaesaudi** [almasaeed2010/AdminLTE#660]
Mini Sidebar works perfectly out of box like this:
<img width="1440" alt="issue_1" src="https://cloud.githubusercontent.com/assets/11377260/9478310/a1002fa0-4b7f-11e5-81cf-30536b195383.png">

But if I have enabled Fixed Navbar with Mini Sidebar it expands automatically on hover by mouse which makes a bad user experience like these:
<img width="1440" alt="issue_2" src="https://cloud.githubusercontent.com/assets/11377260/9478341/d9f51000-4b7f-11e5-9340-c11d8f53b13a.png">
<img width="1440" alt="issue_3" src="https://cloud.githubusercontent.com/assets/11377260/9478342/da529f72-4b7f-11e5-82e0-4473f88b75b8.png">

Can't I make Sidebar Mini & Fixed works together ?

**Comment by sanjusoftware** [comment]
I also have exactly same problem... as soon as I added fixed nav bar, the mini sidebar starts opening on hover automatically ... how should we get rid of it... the only 2 plugins that I have enabled are icheck.js and scrimscroll.js

One another problem that I have noticed with the combination is that the sidebar menu items give a flickering effect:

![image](https://cloud.githubusercontent.com/assets/232573/9562146/c8fc7474-4e80-11e5-8b0a-5a73a28ac972.png)

I could also see in the dev tools that the top level element 'aside' is being repainted continuously.
```
<aside class="main-sidebar">....</aside>
```
![image](https://cloud.githubusercontent.com/assets/232573/9562155/3423d35a-4e81-11e5-9dd4-e8636ebcf37e.png)

**Comment by almasaeed2010** [comment]
Unfortunately, you can't use the fixed layout with sidebar-mini for now due to complications with the scroll plugin. The only way to make it work was to add an expandOnHover option that would open the sidebar when a mouse hovers over it. Review #420.
