### ISSUE TITLE
Select2 v4 inside an horizontal form does not resize according to the column

### ISSUE THREAD

**Issue by Leftyx** [almasaeed2010/AdminLTE#661]
The select element is inside a column ```<div class="col-md-6">``` as you can see in the HTML below:

```
<form action="/" class="form-horizontal">
	<div class="form-group">
		<label class="control-label col-md-2" for="CallPriority">Priority</label>
		<div class="col-md-6">
			<select class="form-control input-sm" id="CallPriority" name="CallPriority">
				<option value="Low">Low</option>
				<option value="Medium">Medium</option>
				<option value="High">High</option>
			</select>
		</div>
	</div>
</form>
```
but it doesn't resize as all the other controls. 
The only way I've found to fix this is using this css:
```
.select2-container--default {
      display: block;
      width: 100% !important;
}
```

**Comment by lcguida** [comment]
select2 resizing only worked with me when I set the width directly on the element (`style="width: 100%;"`).

**Comment by enumag** [comment]
The `width: 100% !important;` may not fix all problems. There is an old issue related to this: https://github.com/select2/select2/issues/995

**Comment by mahesh-ziffi** [comment]
I'm also facing the same problem. Only solution worked for me is (style="width: 100%;").
