### ISSUE TITLE
Routing problem in laravel with AdminLTE

### ISSUE THREAD

**Issue by Raman16** [almasaeed2010/AdminLTE#662]
HI almasaeed,thanks for the great template,
I have issue when integrated with laravel,.In routing if i call Route::get('/editCountry/{id}','CountriesController@editCountry'); i couldnt see any CSS.JS effects...
when i call as Route::get('/editCountry','CountriesController@editCountry');  i.e without   /param i could get ..please provide a possible solution.....i m just new to this framework and template

**Comment by YasserHassan** [comment]
Refer to #642.

**Comment by Raman16** [comment]
Thanks you for your reply
