### ISSUE TITLE
support for bootstrap4

### ISSUE THREAD

**Issue by kk86bioinfo** [almasaeed2010/AdminLTE#665]
Any plan to continue support this project with bootstrap4 later?

**Comment by YasserHassan** [comment]
From #489:
>The other solution is with AdminLTE 3.0. Since it will use Bootstrap 4, many major changes will be made.

**Comment by almasaeed2010** [comment]
I am planning to create AdminLTE 3.0 based on Bootstrap 4. Of course, this would make us unable to maintain backwards compatibility. Upgrading to 3.0 will be more difficult than it was for upgrading form 1.x to 2.x.

**Comment by d4n1b** [comment]
Any update about this?

**Comment by d-knafo** [comment]
?

**Comment by almasaeed2010** [comment]
#710
