### ISSUE TITLE
Tab pages

### ISSUE THREAD

**Issue by Zahid-Ashiq** [almasaeed2010/AdminLTE#675]
Hi,

i didn't find any tab page in "AdminLTE". Anyone have idea where is?

Thanks

**Comment by almasaeed2010** [comment]
Hello,

Could you clarify what you mean by "tab page"? If you are looking for the tabs component, you can find it on the [General UI page](https://almsaeedstudio.com/themes/AdminLTE/pages/UI/general.html).

**Comment by Zahid-Ashiq** [comment]
Thanks
