### ISSUE TITLE
Control-sidebar visible on mobile view without clicking on configuration button

### ISSUE THREAD

**Issue by tangb** [almasaeed2010/AdminLTE#676]
On mobile view (chome, cm browser at least under android), the control-sidebar is visible when i scroll the page from right to left.
The panel is always visible, the div is just moved to the right to "hide" it from main content.
The side effect of that is on mobile view bootstrap modal takes more spaces than expected and force user to scroll to see full popup content.

You can test it directly on your website https://almsaeedstudio.com/themes/AdminLTE/index2.html

Thanks for your work, it is really nice!

**Comment by almasaeed2010** [comment]
Fixed. Tested on Safari (OS X Yosemite, iOS 8 & 9), Chrome, Opera and FireFox. Couldn't test on windows mobile.
