### ISSUE TITLE
Disable JS on Treeview in Sidebar for selective Items

### ISSUE THREAD

**Issue by gangofmumbai** [almasaeed2010/AdminLTE#677]
I have a sidebar with multiple TreeViews and I wish to disable the JS on one of the TreeView. Meaning I want the treeview-menu visible all the time.

Is there a way i can do it? I am not so expert in JS or Jquery.

Thanks,
Saurabh

**Comment by almasaeed2010** [comment]
Hello,

I don't think this is currently possible out of the box. However, you can remove the ```$.AdminLTE.treeview``` code from app.js. You will also need to add the following css:
```css
.treeview .active {
  display: block!important;
}
```

I hope this helps!
