### ISSUE TITLE
Move Treeview to the right.

### ISSUE THREAD

**Issue by 4D1L** [almasaeed2010/AdminLTE#682]
I was wondering how I can move the box that appears when I set my sidebar to collapse on page load up. http://prntscr.com/8fzjj1 I have increased the width of the ".sidebar-mini.sidebar-collapse .main-sidebar" class to 79px but the treeview hasn't moved with it.

**Comment by almasaeed2010** [comment]
You will also need to change the placement of the ```span``` and ```.treeview elements```. 

If you are using less, you will find the code in sidebar-mini.less. Otherwise, it will be in the AdminLTE.css file.
