### ISSUE TITLE
app.js crashes browser on boxed layout when resizing window

### ISSUE THREAD

**Issue by kspearrin** [almasaeed2010/AdminLTE#683]
See example here: http://s.codepen.io/kspearrin/debug/WQrERZ?

Using Firefox or Chrome, make your browser **not** full screen, then grab your window at the bottom right corner and drag it around a lot to make different sizes. The app.js script crashes the browser as it redraws the page.

Maybe related: https://github.com/almasaeed2010/AdminLTE/issues/502

**Comment by almasaeed2010** [comment]
Hello @kspearrin 

This issue only occurs with the boxed layout which is a bit odd. I'll look further into it. Thanks for letting me know.

The issue is replicable in this [demo page](https://almsaeedstudio.com/themes/AdminLTE/pages/layout/boxed.html)

**Comment by gusta21** [comment]
@kspearrin i had the same behaviour, and i don´t remember how i fixed, I think i only replace the layout-boxed in the js and put something else (layout-box, for example). Its working well.

**Comment by lanaguanifw** [comment]
layout-boxed is unusable due to this bug.

**Comment by iyurtsever** [comment]
Hello,
I am facing same issue. When do you think to fix it?

**Comment by lanaguanifw** [comment]
I have solved this way:
https://github.com/almasaeed2010/AdminLTE/compare/master...lanaguanifw:patch-1

But even untested, not if have other implications.

**Comment by iyurtsever** [comment]
@lanaguanifw , 
thanks for your help. I changed the js file and test it but unfortunately still it is crashing :(

**Comment by lanaguanifw** [comment]
I just found another solution of another user:
https://github.com/almasaeed2010/AdminLTE/pull/799/files

**Comment by iyurtsever** [comment]
@lanaguanifw 
I tried this solution as well, with no luck :(
some piece of code makes CPU top. Then screen becomes unresponsive :(

**Comment by by12** [comment]
@lanaguanifw try by adding the following code in activate function in js file. for example just paste it after line 464.

if ($("body").hasClass('layout-boxed')) {
        $(window).resize(function () {
          _this._fix(sidebar);
        });
      }

**Comment by kspearrin** [comment]
@almasaeed2010 Any update on looking into this?

**Comment by kspearrin** [comment]
There a reason why this was closed? Still an issue...

**Comment by almasaeed2010** [comment]
Please see https://github.com/almasaeed2010/AdminLTE/issues/1086

**Comment by almasaeed2010** [comment]
A temporary solution has been added based on @lanaguanifw's suggestion. It is imperfect in that when the page expands the height of the page will not get fixed. But this issue is lesser of the two evils. We will keep working on finding a solution to solve this problem permanently. Meanwhile, this should suffice.

**Comment by kspearrin** [comment]
What was wrong with this suggestion? https://github.com/almasaeed2010/AdminLTE/pull/799/files

This seems to work with window height adjustments after page load.

**Comment by almasaeed2010** [comment]
I tried the solution before but it didn't work. Have you tried it?

**Comment by kspearrin** [comment]
Yes, it worked fine for me.

**Comment by almasaeed2010** [comment]
Let me attempt one more time

**Comment by almasaeed2010** [comment]
Fixed permanently.

Thanks @kspearrin and everyone for your patience.
