### ISSUE TITLE
Question: Use AdminLTE with bower.

### ISSUE THREAD

**Issue by asimkt** [almasaeed2010/AdminLTE#684]
How can I use AdminLTE with bower. I have installed it as dev dependency. I scaffolded my project with yo and I am managing whole packages with bower. Simple bower install not doing anything. I want to use the styles and JS functionalities like in the documentation.

Simply I want to use AdminLTE like bootstrap. 
After installing  bootstrap as dependency I can use it anywhere in the app by starting the server. 
Similarly I want whole styles and components of AdminLTE have access from the app.

**Comment by kohenkatz** [comment]
The same way that you install Bootstrap using bower by running `bower install bootstrap`, you install AdminLTE using bower by running `bower install AdminLTE`.

**Comment by almasaeed2010** [comment]
```bower install admin-lte```

**Comment by asimkt** [comment]
Oh.. I did try it. But didn't work that time. I will give it one more. Thanks
