### ISSUE TITLE
advance  tabmenu function

### ISSUE THREAD

**Issue by crperlin** [almasaeed2010/AdminLTE#686]
my english is poor ;

this function preview : http://www.zi-han.net/theme/hplus/
 the position at top ; [首页] background is black ； when you click lef  sidebar menu_list , the top tabmenu add a tab , the can close and switch , my feel this function is very good!! ;

everybody , feeling ?

thankyou verymuch !!!

**Comment by adaniello** [comment]
+1

**Comment by almasaeed2010** [comment]
I am sorry. I am not sure I understand the request. The page you linked to uses INSPINIA template. Is that what you are looking for?

**Comment by crperlin** [comment]
I ask function like browser tab,…can switch and close  ……when open new sidebar link at top menu add tab and websiteNo refresh all page

**Comment by almasaeed2010** [comment]
Looks like a good idea. We will consider it for a future version of AdminLTE.

Thanks!
