### ISSUE TITLE
RTL version 

### ISSUE THREAD

**Issue by mmdsharifi** [almasaeed2010/AdminLTE#691]
Hi 
I recently created RTL version of awesome AdminLTE with Persian fonts. hope useful for RTL projects.
here is my repo:
https://github.com/mmdsharifi/AdminLTE-RTL

Demo : https://htmlpreview.github.io/?https://raw.githubusercontent.com/mmdsharifi/AdminLTE-RTL/master/index.html

**Comment by almasaeed2010** [comment]
Thanks for sharing this! 

I will add your repo to the documentation for reference.

**Comment by almasaeed2010** [comment]
Added to [docs](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#implementations).

**Comment by mmdsharifi** [comment]
you're welcome !

Thank you for adding and your awesome AdminLTE ;)
