### ISSUE TITLE
Flatpickr, a replacement for bootstrap-datepicker

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [almasaeed2010/AdminLTE#693]
Hello!

I would like to suggest a replacement for bootstrap-datepicker on AdminLTE.

On my website, I found some conflicts between bootstrap-datepicker and boostrap modal on the same page. The events got all messed up, making the datepicker useless. Also bootstrap-datepicker has a lot of unsolved issues (341 so far), and very slow releases and patches.

So I had to find another datepicker, and I found this: https://github.com/chmln/flatpickr

It's relative new, very clean, very lightweight, and have no conflicts with bootstrap.

Here is the demo page: http://chmln.github.io/flatpickr/

:+1:

**Comment by adaniello** [comment]
I like it, too.
But its features are still limited (no fast select for years and months, no time support).
At this stage of Flatpickr, i'm not agree

**Comment by rafael-renan-pacheco** [comment]
Agreed, if you use those features, flatpickr won't do the job. For me, I just use the datepicker as is, without using fast select for years and months. And I don't think bootstrap-datepicker support time selection.

**Comment by crperlin** [comment]
perfect... very  simplify;

but date plugin more than more , before myself  use date range picker ;

website .. http://www.daterangepicker.com/ ...

i feel the plugin very cool!

**Comment by rafael-renan-pacheco** [comment]
This topic is about datepicker plugin, not about daterangepicker. AdminLTE ships with both this plugins. My suggestion is the replacement of bootstrap-datepicker, not the replacement of daterangepicker.

@almasaeed2010 to avoid the replacement of bootstrap-datepicker on the template, maybe put a link to flatpickr on plugin doc page, or even an alternative sample for this plugin? If the user don't need fast month/year access, flatpickr will do the job with only 2.5kb.

**Comment by jlamer** [comment]
Looks very good, but it is relatively new plugin. It was not tested in real-life applications and there could be many bugs.

**Comment by almasaeed2010** [comment]
Looks interesting. I don't want to go over board with the number of plugins that do the same thing. I appreciate the suggestion! This might be a good idea for AdminLTE 3.0. Will look more into it. 

Thanks!
