### ISSUE TITLE
Migration on bootstrap 4

### ISSUE THREAD

**Issue by falexis77** [almasaeed2010/AdminLTE#694]
Hi,

We have now a alpha version of new Bootstrap.
Have y ou prepare the migration on the new version ? 
Thanks for your response.

**Comment by Dennis14e** [comment]
See #665

**Comment by hitalo07** [comment]
Cara vai ficar muito massa velho! Vai ficar <strong>incrivel</strong>...

**Comment by Debyiinha** [comment]
Encontrei um bem parecido, enquanto ele não disponibiliza o com bootstrap 4

http://wrapbootstrap.com/preview/WB0858DB6
