### ISSUE TITLE
Question :　why  no update all plugins on new version !

### ISSUE THREAD

**Issue by crperlin** [almasaeed2010/AdminLTE#695]
I found  plugin directory ; some plugin update a big version (eg: 2.4.4 > 2.5.2 );

new version plugin should be repair minor error and provide effective ??

Thanks ;

**Comment by YasserHassan** [comment]
The accompanying plugins are just examples. Real-world applications should have separate and template-independent package and asset management according to the language/framework you use. When done right, plugins will integrate seamlessly into AdminLTE's interface. Although it would be nice to have the latest plugin versions, practically that should make no difference as they will be overwritten anyway by your system. An exception to this is plugins that need special styles to blend right into the template. The power of AdminLTE is in fact in providing a professional and pleasing skeleton to house your application inside.

**Comment by crperlin** [comment]
thankyou

**Comment by almasaeed2010** [comment]
Some plugins can't be upgraded without affecting the current styling used by AdminLTE. Other, on the other hand, are perfectly fine to upgrade. So, we need to be careful when upgrading to versions of plugins. 

On that note, AdminLTE 3.0 will use bower to manage its dependencies. We will fully utilize the power of Bower.
