### ISSUE TITLE
js not working.

### ISSUE THREAD

**Issue by agnihotri7** [almasaeed2010/AdminLTE#7]
i downloaded it from github but its js functionalities are not working like sidebar , dropdown menus etc . 
any help?

**Comment by gauravpatil32** [comment]
Hi, I've downloaded the Admin LTE theme. Its Awesome. But I'm not able to use jQuery functionalities like $(document).ready(function() {}); and $ajax is not working with it. i don't know why it is happening. Could you please help me..

**Comment by parthcake** [comment]
Hi. almasaeed 
in AdminLTE admin template Ajax code is not working..pls help. thanks
