### ISSUE TITLE
Sidebar footer

### ISSUE THREAD

**Issue by kethomassen** [almasaeed2010/AdminLTE#700]
How do I keep a sticky footer in the main sidebar (in this case a text input)?
I want everything else to scroll underneath, but I want to the text input to always stay in the same place (static). Are there any helper classes in AdminLTE to achieve this?

![](http://puu.sh/kjPxI/77360f1e37.png)

Also: is there a way to make something in the sidebar hidden when it's minimized?

**Comment by rafael-renan-pacheco** [comment]
There is no helper out of the box that I remember.

You have to do that by yourself, and I think it is easy, with absolute positioning and bottom+left values in you css.

There should be a lot of sample code on google as well.

**Comment by jlamer** [comment]
I think it should be part of template. It is not that easy as you say @rafael-renan-pacheco ... :+1:

**Comment by almasaeed2010** [comment]
Fixed footer for both the sidebar and the main content is planned for a future version of AdminLTE. Thanks for the suggestion!

**Comment by kethomassen** [comment]
@rafael-renan-pacheco If it's so easy surely you can provide an example? :stuck_out_tongue_winking_eye:
