### ISSUE TITLE
Boostrap .table problem in Datatable AdminLTEv2

### ISSUE THREAD

**Issue by hdinata** [almasaeed2010/AdminLTE#703]
By using datatable from AdminLTE v2, the class .table, .table-hover, .table-bordered and .table-striped from Bootstrap are not working.

when I tried to re-link the bootstrap.cs twice;

...link rel="stylesheet" href=".../css/bootstrap.min.css"..
....
....
..link rel="stylesheet" href=".../plugins/datatables/dataTables.bootstrap.css"..
..link rel="stylesheet" href=".../css/bootstrap.min.css"..

now the border is appear, but the .table-hover and .table-striped still not working.

Does anyone know how to fix it?

**Comment by almasaeed2010** [comment]
Please check this page https://almsaeedstudio.com/themes/AdminLTE/pages/tables/simple.html

The problems you described are presented (as working) in the link above.

Thanks!

**Comment by hdinata** [comment]
The color, wow it's too light, almost no different with white color
I can't see the hover color, the border color and the strip color
I only can see the border if I re-link the "bootstrap.min.css" after "dataTables.bootstrap.css"

**Comment by jlamer** [comment]
You should probably adjust your monitor.

**Comment by almasaeed2010** [comment]
I agree with @hdinata. The colors aren't exactly the best choice with the new background of AdminLTE v2.0. It was a good choice with v1.0. It's time for an update.

**Comment by jlamer** [comment]
On all of my IPS panels I can see difference between colors without any problem. I cant try it on TN panel, though.

**Comment by almasaeed2010** [comment]
That's true but I am only suggesting that the colors could be better served to lower screen resolutions which we should consider if we want AdminLTE to be used by more people.

**Comment by jlamer** [comment]
absolutely :+1:
