### ISSUE TITLE
How to remove sidebar when acc was signout in the backend?

### ISSUE THREAD

**Issue by chlerog** [almasaeed2010/AdminLTE#707]

**Comment by rafael-renan-pacheco** [comment]
One way is to load the body with layout-top-nav class.

Here is the sample page to reach this behavior: https://almsaeedstudio.com/themes/AdminLTE/pages/layout/top-nav.html

Note that you need another changes as well.

**Comment by chlerog** [comment]
how to remove dashboard and redirect to backend/web/ login page when a user
signout from backend/web/ ?

**Comment by rafael-renan-pacheco** [comment]
AdminLTE is a template, no code behind, and this question is related to the framework behind your webapp.

You need to ask this question in your framework repo, forum, or google it.

Best regards.

**Comment by almasaeed2010** [comment]
I agree with @rafael-renan-pacheco. This is more of a back-end issue.

Sorry for the inconvenience.

**Comment by chlerog** [comment]
i mean how to hide the adminlte sidebar when i logged out from my backend
account?


On Sun, Sep 27, 2015 at 4:36 AM, Abdullah Almsaeed <notifications@github.com

**Comment by YasserHassan** [comment]
@chlerog practically you don't just hide the sidebar but detect guest users and show a login screen. If a guest user successfully logged in, you redirect him to the full application interface (AdminLTE). That detection, login, redirection, ...etc are server-side development as mentioned by @rafael-renan-pacheco and @almasaeed2010, not a template issue. It is related to the language/framework you are using so you better look there.
