### ISSUE TITLE
Why not create a full Laravel tutorial using AdminLTE?

### ISSUE THREAD

**Issue by ayimdomnic** [almasaeed2010/AdminLTE#708]
I am learning a lot in laravel using these tutorials, I cant say am guru enough but I do know am headed there. why did I make this issue? I figured learning laravel is easier when you use a template of repositories you're familiar with.. How about you come up with a full tutorial on Laravel where all the functionalities of the template are integrated into laravel both back-end and front-end? Thanks

**Comment by jlamer** [comment]
Why *you* dont do it? :) You are learning and you think you will soon be "guru". I think you could learn a lot trying to do it. Just make fork and play with it. If it will be good enough, people will start using it if not, well, at least you learned something.

**Comment by almasaeed2010** [comment]
There is already a tutorial on our website's blog. https://almsaeedstudio.com/blog

:+1:

**Comment by ayimdomnic** [comment]
@jlamer am working on one at the moment, though I restricted it to a Hotel management system, once done I will ail it for 'Gurus' like you to see @almasaeed2010 thanks let me check out your blog

**Comment by acacha** [comment]
See https://github.com/acacha/adminlte-laravel
