### ISSUE TITLE
Datatable column alignment

### ISSUE THREAD

**Issue by vinaychandra** [almasaeed2010/AdminLTE#711]
When trying to use alignment of columns for tables with datatables, it does not work. According to the datatables website, 
```javascript
$('#table_id').DataTable({
            "columnDefs": [
                {className: "dt-body-center", "targets": [2, 3]}
            ]
        });
```
should work. This is adding the class name as expected but failing to align the data. What should be done?

**Comment by almasaeed2010** [comment]
Make sure the plugin's css files are loaded.

**Comment by vinaychandra** [comment]
The following files are used in the page
    <link rel="stylesheet" href="/plugins/datatables/dataTables.bootstrap.css">
    <script src="/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/plugins/datatables/dataTables.bootstrap.min.js"></script>
This looks as if everything necessary is loaded. But still, the question remains

**Comment by Nganthoiba** [comment]
Use this one:
"columnDefs": [
                    { "className": "align-right", "targets": [your column index] }
                ]
Define your own css class:
<style type="text/css">
        .align-right{text-align:right;max-width:80px}
        .align-left{text-align:left;max-width:80px}
        .align-center{text-align:center;max-width:80px}
    </style>
