### ISSUE TITLE
Old version in bower

### ISSUE THREAD

**Issue by adiramardiani** [almasaeed2010/AdminLTE#714]
I install admin lte with bower why the version still 2.3.0 (currently 2.3.1)
code note : "admin-lte": "*" or "admin-lte": "~2.0"

**Comment by almasaeed2010** [comment]
Hello @adiramardiani 

Version 2.3.1 hasn't been released yet. We working on a couple of bugs before we release it. Once it is ready, it will be available on Bower. Thanks!
