### ISSUE TITLE
Admin Forms

### ISSUE THREAD

**Issue by mdixon18** [almasaeed2010/AdminLTE#715]
Not really an issue more 'support' I was curious to know what licensing you have for 'admin forms'. I really love this and want to be able to use it in all my projects.

**Comment by fschaeffer** [comment]
The feature Admin Forms is to my knowledge for another project called admindesigns (http://admindesigns.com/demos/admin/README/index.html), which is not AdminLTE.

**Comment by almasaeed2010** [comment]
@mdixon18 The forms are free and part of the MIT license covering AdminLTE, so feel free to use them.

@fschaeffer AdminLTE forms are created for AdminLTE from Bootstrap 3 which is what "admindesigns" also uses. However, AdminLTE and admindesigns are not affiliated with each other in any way.
