### ISSUE TITLE
Events firing twice or more

### ISSUE THREAD

**Issue by lxsameer** [almasaeed2010/AdminLTE#718]
I'm using Turbolinks jquery to with AdminLTE and after each request events handlers execute more than once. After some investigation I found out that you binds you `document` inside a `$(function())` block. This is not a good idea generally and should we should avoid such mistakes. For instance, this example below can be a common occurrence and should be avoided:

``` javascript
/* BAD: don't bind 'document' events while inside $()! */
$(function() {
  $(document).on('click', 'button', function() { ... })
});
```

You should be binding your events outside a `$(function())` block. This will ensure that your events will only ever be bound once.

``` javascript
/* Good: events are bound outside a $() wrapper. */
$(document).on('click', 'button', function() { ... })
```

**Comment by almasaeed2010** [comment]
Interesting observation. I will look into it as soon as I get a chance. Thanks for letting us know.

**Comment by lxsameer** [comment]
cool, If I find some free time I'll fix it too

**Comment by almasaeed2010** [comment]
How can we test that these events are really firing more than once?

**Comment by lxsameer** [comment]
It's a bit complicated but I can test it for you if you want .

**Comment by lxsameer** [comment]
@almasaeed2010 `dist/js/app.js` does not generate automatically from other js sources, right ?

**Comment by almasaeed2010** [comment]
Right
