### ISSUE TITLE
DataTable Sorting

### ISSUE THREAD

**Issue by Abhayman** [almasaeed2010/AdminLTE#720]
Hi,

When we try to color code the row in the Datatable and enable sort . Multiple rows gets colored . Here is the script to call the data :--

	<script>
        $(function () {
        
        $('#example2').DataTable({
		  "ajax": "../json/daily_status.json",
		  "fnRowCallback": function( nRow, aData, iDisplayIndex ) {
            /* All cells in 4th row will be bolded  */
            if ( iDisplayIndex == 9 ) {
                $('td', nRow).each(function(){
                               $(this).html( '<td bgcolor="#BE81F7"><b>'+$(this).text()+'</b><td>' );
                            });
            }
            return nRow;
        },
		  "scrollX": false,
		  "bSort": false,
		  "paging": false,
		  "info": false,	
		  "searching": false,
           dom: 'Bfrtip',
           buttons: [
                'excel'
                ]  		  
        });
      });
    </script>

HTML Section :-- 

<table id="example2" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                       <th>STATUS_CODE</th>
                       <th>Count</th>                       
                      </tr>
                    </thead>
                  </table>

Any idea  on how to get only the row containing 1st column name as Total colored ?

**Comment by Abhayman** [comment]
![sorting_color](https://cloud.githubusercontent.com/assets/8066748/10315526/7e18101a-6c78-11e5-9cfb-4132df1ef0c6.png)

**Comment by almasaeed2010** [comment]
Hello,

This is an issue for the Datatables plugin. You can raise your issue on their [repo](https://github.com/DataTables/DataTables/issues).
