### ISSUE TITLE
Why Select2 doesn't have highlight/focus?

### ISSUE THREAD

**Issue by MrLinDowsMac** [almasaeed2010/AdminLTE#722]
Hi, I was looking at the examples of select2 and I was wondering why those inputs doesn't have the typical bootstrap blue highlight or focus color. Is it customized like that?

**Comment by almasaeed2010** [comment]
Hello @MrLinDowsMac 

Select2 in AdminLTE is customized to fit the styling of AdminLTE not Bootstrap.

Thanks!
