### ISSUE TITLE
Tooltips on tables

### ISSUE THREAD

**Issue by vinaychandra** [almasaeed2010/AdminLTE#723]
When trying to use bootstrap tooltip on td elements(DataTables), the tooltip is creating a new column and pushing the data to right. This could be even an issue with dataTables but a google search said that dataTables generally work woth tooltips? What is the problem?

**Comment by iaesaudi** [comment]
use this option to work normally in table:
`container: 'body'`
or as data attr like this:
`data-container="body"`
