### ISSUE TITLE
Whole Wrapper div is pulled left when using pagination class on boxed

### ISSUE THREAD

**Issue by gusta21** [almasaeed2010/AdminLTE#724]
Hello. While using the boxed layout, in the pages i use div class="pagination" the whole wrapper is pulled to the left like 20px. The size in always the same, just is moved to the left some px. Is not a big deal but i would like to fix it...

Thanks!

**Comment by almasaeed2010** [comment]
Hello @gusta21, 

Could you provide a screenshot of the issue? According to what you are describing, it could be an issue with not closing the HTML tags properly because the box-layout works fine with the pagination component on my end. Thanks for reporting issues!

**Comment by gusta21** [comment]
Im very sorry. Was just google chrome scrollbar. When page is too large,
scrollbar appears and move the whole thing to the left. I fixed in css,
showing scrollbar ever.

**Comment by almasaeed2010** [comment]
No problem :+1:
