### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by TheDeadCode** [almasaeed2010/AdminLTE#725]
Hi! For some reason, I feel your example login page doesn't fit the beauty of the rest of the template. Will you redo it sometime?

**Comment by almasaeed2010** [comment]
Hello,

I appreciate your input but I feel that style and design is based on taste and personal opinion. The components of the login page use AdminLTE design tools which creates consistency. Of course, you are more than welcome to design a new page and submit a pull request. There is no harm in having two options for the login page.
