### ISSUE TITLE
Unable to see events on the datagrid

### ISSUE THREAD

**Issue by ppjaywant** [almasaeed2010/AdminLTE#727]
We have applied your Production-Ready theme (no LESS compiling) to the MVC5 application. The layout is of 'Fixed Type'. We are using Datatable with Full Features component in one of the view.

The layout and rendering of datagrid looks fine. But no events (such as Column Sort, Search, Pagination etc.) are getting fired on the table. The grid remains unresponsive.

Please let know if any basic configuration seems missing at our end. We have included hierarchy of all AdminLTE folders as mentioned in documentation into the project.

Thanks in advance for your insight and the help in resolving the issue.

Regards,

Prasad Jaywant

**Comment by almasaeed2010** [comment]
Hello @ppjaywant 

The Datatables plugin has its own set of plugins that you can find [here](https://datatables.net/plug-ins/). You need to include the JS files of any plugins you use. In your case, you may be missing the main datatables.js file which is located in ```AdminLTE/plugins/datatables/jquery.dataTables.min.js```.

**Comment by ppjaywant** [comment]
Dear Abdullah,

Thanks for writing to us on your suggestions.


We did have included all relevant source files including one below in your mail, in the .cshtml View page (attached for ready reference). Fyi, we are trying to call this View Page in Razor Engine of MVC5. It would be very helpful, if you could provide sample .cshtml (if you have any) depicting the code for running the datatable. The result at our end is still the same and we are exploring links given in your email.


Kindly let know if you observe anything disordered in the page code.

Thanks again for your kind attention,

Regards,


Prasad Jaywant


M:   +91 9833030348
Tel: +91 22 25881781


Website: www.sparkinfotech.co



---- On Sat, 17 Oct 2015 05:30:24 +0530 Abdullah Almsaeed&lt;notifications@github.com&gt; wrote ---- 

Hello @ppjaywant 
 The Datatables plugin has its own set of plugins that you can find here. You need to include the JS files of any plugins you use. In your case, you may be missing the main datatables.js file which is located in AdminLTE/plugins/datatables/jquery.dataTables.min.js.
