### ISSUE TITLE
How to Remove a tab of Layout Options?

### ISSUE THREAD

**Issue by V3rs10n** [almasaeed2010/AdminLTE#731]
Hi, how do remove a tab ofLayout Option Settings?

![image](https://cloud.githubusercontent.com/assets/15094802/10436580/e0697c54-70ec-11e5-8e0a-d6456f8385a7.png)

i wan only left configuration tab

**Comment by JeroenNoten** [comment]
In the navigation bar, remove the menu item (`<li>` element) with `data-toggle="control-sidebar"`.

And remove the full element `<aside class="control-sidebar control-sidebar-dark">` and the line with `<div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>`.

**Comment by V3rs10n** [comment]
Thanks, a more quest: how i can set the color in Layout Options???

for defect is black but i wan set white.

thanks again

**Comment by almasaeed2010** [comment]
Could you clarify your question please?

**Comment by V3rs10n** [comment]
hi almasaeed2010 

I would like to set a color window, if the user selected light that the next access the default color display

**Comment by almasaeed2010** [comment]
This is only achievable using server-side configuration. When a user selects a skin, you'll have to send an ajax request to the server to save the skin he chose. When the user accesses a page, your server should print the class of the skin into the body tag.

The other way to do this is via [HTML5 Localstorage](http://www.w3schools.com/html/html5_webstorage.asp). However, this approach will only work on one device a time. In other words, if the same user accesses the site from another device, the color will revert back to default skin.
