### ISSUE TITLE
can you update nuget admin-lte

### ISSUE THREAD

**Issue by Jesn** [almasaeed2010/AdminLTE#732]
nuget  admin-lte version is 2.0.1 ,lower than github version，can you update nuget admin-lte version？

**Comment by almasaeed2010** [comment]
Hello @Jesn 

Unfortunately, we do not provide support for ```nuget```. The person who decided to add AdminLTE to nuget is [mikeon](https://www.nuget.org/profiles/mikeon).

We apologize for the inconvenience.
