### ISSUE TITLE
Split buttons and scroll in Data Table

### ISSUE THREAD

**Issue by elv1ss** [almasaeed2010/AdminLTE#733]
Split button is covered by the property overflow: auto in Data Table with scrollX: true. How do I fix this?
![2015-10-13_1752](https://cloud.githubusercontent.com/assets/3382386/10458387/3c52cd04-71d3-11e5-9e3d-1ae2f0412a04.png)
Video: http://screencast.com/t/6K7uVKQx

**Comment by rifton007** [comment]
Hi, I have same bug with AdminLTE v3.0.-alpha2.
Thx,

**Comment by rifton007** [comment]
**Final fix**

Add `data-boundary="viewport"` to the button that toggles the dropdow
![image](https://user-images.githubusercontent.com/2601347/48312498-e04d4d00-e5af-11e8-9a06-e66e60b11244.png)

_AdminLTE v3.0.-alpha2 with Bootstrap 4.*_
