### ISSUE TITLE
How to set Right side bar in  pushes the content to make space for the sidebar

### ISSUE THREAD

**Issue by kennedymca** [almasaeed2010/AdminLTE#739]
hi ,
   how to create right sidebar looks like left side bar,when i click right side bar the content cannot moved,i need same left side bar option.

**Comment by almasaeed2010** [comment]
Hello,

In your javascript file disable control-sidebar slide option. This can be done either by adding the following code before loading AdminLTE's app.js file:
```js
AdminLTEOptions.controlSidebarOptions.slide = false;
```
Or by customizing the app.js file and modifying the following line:
```js
  controlSidebarOptions: {
    //Which button should trigger the open/close event
    toggleBtnSelector: "[data-toggle='control-sidebar']",
    //The sidebar selector
    selector: ".control-sidebar",
    //Enable slide over content
    slide: false /* SET THIS TO FALSE */
  },
```
