### ISSUE TITLE
Dropdown on nav bar is not showing

### ISSUE THREAD

**Issue by LeoYong95** [almasaeed2010/AdminLTE#743]
Hi Almasaeed

I am having trouble in implementing dropdown-menu function as shown in index.html 

Here is a very basic code I have written:
```
                  <li class="dropdown notification-menu"> 
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                     <span class="label label-warning">10</span>
                  </a>
                 <ul class="dropdown-menu">
               <li>Here is the menu</li>
         </ul>
      </li>
```
But when I compile it , the dropdown-menu did not appear although <code>aria-expended="true"</code>.

Thank you so much for your reply.

**Comment by almasaeed2010** [comment]
Hello,

```aria-expanded="true"``` does not control the open/close events of the dropdown. To implement any dropdown menus, refer to Bootstrap's [dropdown](http://getbootstrap.com/javascript/#dropdowns) documentation which explains how to handle the event. Thanks!

**Comment by LeoYong95** [comment]
Thank you so much for your reply.

I just found out the root of my problem is because I have included two different version of JQuery file in my script.

**Comment by ErSKS** [comment]
It may due to duplicate include of following files:
public $js = [        
        // '.../dist/jquery.min.js',
        // '.../dist/js/bootstrap.min.js',
];

**Comment by KobbyKnight** [comment]
That's True ErSKS. I've been wondering whats wrong with my code since...i took out bootstrap.min and it works fine. i'M SO GRATEFUL
