### ISSUE TITLE
Removed external server request

### ISSUE THREAD

**Issue by ghost** [almasaeed2010/AdminLTE#744]
Please  eliminate requests to external servers (eg. fonts.googleapis.com in CSS) and add the feature to local load.

Three reasons:
 - Security.
 - Privacy.
 - Speed.

Speed:
There is only performance improvement if the file is in the cache of the user, otherwise a new connection and a new DNS request is added. As the chances of another site using the same URL (eg. fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic) are very low, performance will be less in most cases.

Privacy:
Least sent the user IP address and the referer, the external server could monitor user views. Also, if the external server send a cookie could be illegal under European law.

Security:
All problems linked server, your site will have, the higher the number of servers, the greater the probability of failure, with the possibility that future vulnerabilities could reach your site by it is procedure.

**Comment by almasaeed2010** [comment]
Hello @FranBar,

GoolgeFonts are somewhat difficult to implement locally. What you are suggesting is true. However, I can't change any of these settings currently because it will cause backwards compatibility issues. I think even in future versions, AdminLTE will use Google Fonts to provide an example of font customizability. At the same time, it will allow developers to easily change that setting by adding the link to the HTML files instead of the  CSS file. This way, a simple change to the SASS variables and the link from which the developer chooses to load their fonts will change the dependency on Google fonts to local or other resources.

Thanks for the suggestion!

**Comment by FranBar** [comment]
If someone is interested:
http://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server
http://www.localfont.com/

I will continue using AdminLTE is one of the best templates, although I have to manually make these changes.

Thank you.

**Comment by jlamer** [comment]
> eg. fonts.googleapis.com .... the greater the probability of failure ...

Lets hope it never happens. If google servers were compromised that would be quite a disaster and font serving would concern me the least :) You cant do much with CSS declarations.

**Comment by douglasduartetb** [comment]
I suggest this https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro?subsets=latin

**Comment by ivantcholakov** [comment]
Quite thin fonts are barely visible on mobile devises.

**Comment by mirabilos** [comment]
Please fix this in AdminLTE upstream, do not suggest changing the AdminLTE configuration to the user.

Requesting a resource from an external server **by default** is **not** allowed in a production environment!

**Comment by mirabilos** [comment]
Please reopen, this is **not** fixed!

**Comment by durasj** [comment]
> Requesting a resource from an external server by default is not allowed in a production environment!

Not allowed by who? :) Take a look at what @almasaeed2010 wrote up there. I don't think there is great chance he will not implement your PR. I would not want [those changes](https://github.com/almasaeed2010/AdminLTE/commit/e599b187a76ab9315d60cc2c340ff862ec071ddf) neither.

**Comment by mirabilos** [comment]
If this is not fixed I’m afraid we’ll have to fork AdminLTE.

**Comment by durasj** [comment]
@mirabilos I personally don't think there is anything wrong with you forking. That's the best approach so you can keep up with the changes by merging from upstream while having that one line removed.
