### ISSUE TITLE
Qeustion: onclick sidebar link at `.content-wrapper` load content

### ISSUE THREAD

**Issue by crperlin** [almasaeed2010/AdminLTE#745]
I want to click on the sidebar at the right shows the contents ....
I do not want to use the iframe .. what can be achieved ... What seek advice and resentment;
Thank you!

![image](https://cloud.githubusercontent.com/assets/8272877/10557273/8e53d952-74d7-11e5-948e-05e0fb7d4a08.png)

**Comment by almasaeed2010** [comment]
I am not sure what you mean. But for the full preview, please visit the following link:

https://almsaeedstudio.com/themes/AdminLTE/index2.html
