### ISSUE TITLE
Request for datetimepicker

### ISSUE THREAD

**Issue by Code-ReaQtor** [almasaeed2010/AdminLTE#746]
Hi,

It seems there is no datetimepicker plugin available. There's datepicker and timepicker but they are separate plugins.

Datetimepicker plugin might be a good feature.

Regards,
Code-ReaQtor

**Comment by YasserHassan** [comment]
@almasaeed2010 has stopped adding features to AdminLTE v2.x as mentioned in #710:
>In other words, v2 will get bug fixes and patches but won't get new features.

However, you should be able to add any new plugin to your project by following its own instructions. Most of them will blend well with AdminLTE but you can ask for help if not.
