### ISSUE TITLE
Text in datatable td won't wrap if no spacing

### ISSUE THREAD

**Issue by howardhee** [almasaeed2010/AdminLTE#747]
Hi, 

I'm doing chat display system, someone entered the 500 char without spacing, then table width was out of the box. It only wrap the sentence with spacing. How to I solve it? Thanks

**Comment by iaesaudi** [comment]
try to use this css on your input:
`white-space: pre-wrap;
word-wrap: break-word;`

**Comment by howardhee** [comment]
I change the code as below, but still not working
<td style="white-space: pre-wrap; word-wrap: break-word;"> yoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo</td>

**Comment by iaesaudi** [comment]
Why you are using table to display chat ?
however you could use this:
`word-wrap: break-word;
word-break: break-all;
white-space: normal;`

**Comment by howardhee** [comment]
Is worked, Thank you very much
