### ISSUE TITLE
AdminLTE datatables JQ Dont Work...

### ISSUE THREAD

**Issue by kaptantr** [almasaeed2010/AdminLTE#748]
hi,
im using adminlte 2.3.0 version.
Currently having an issue with the jq datatables.

I want datatables into AdminLTE.
But 
"plugins/datatables/extensions/media/js/jquery.js"
with
"dist/js/app.min.js"
they prevent each other...

eventually:
left menu -> sidebar-toggle, dont work click event...

can you help me???

i very tried but dont...

![image](https://cloud.githubusercontent.com/assets/6266865/10574468/d7f80da2-765e-11e5-8e08-2eca71a34d54.png)

**Comment by almasaeed2010** [comment]
Hello @kaptantr 

You don't have to include ```plugins/datatables/extensions/media/js/jquery.js```. You only need to include ```plugins/jQuery/jQuery-2.1.4.min.js``` and it must be included before Bootstrap.js and app.js.

**Comment by kaptantr** [comment]
thanks for the reply
almasaeed2010...

i had to include from site "https://www.datatables.net/" full js librarys...
all works...

Thanks...
