### ISSUE TITLE
Non-blue skins are not working

### ISSUE THREAD

**Issue by PDelahanty** [almasaeed2010/AdminLTE#749]
When I change a skin from _all-skins.min.css to skin-yellow.min.css, it doesn't appear to be the same yellow as when I picked it from the right menu.  Seems broken.  Instead, it's all white with light blue text.

The same thing happens whenever I choose red, purple, green, or black.  Oddly enough, blue works.

To change the skin, I'm editing the stylesheet line in the header.  Is there something else I should also be changing?

**Comment by PDelahanty** [comment]
Nevermind.  I'm an idiot.  Forgot to change the class in the body tag.

**Comment by SirCrowley** [comment]
Hi, Please can you tell me the issue to used a skin,
i'have already add the stylesheet in header, add "skin-yellow" on the body's class and the button class too.

**Comment by imartinezgranados** [comment]
Hi, I have the same issue, over what directory you made the change, thanks
