### ISSUE TITLE
Sidebar toggle

### ISSUE THREAD

**Issue by yengtot** [almasaeed2010/AdminLTE#751]
Hi I've been configuring it all day my paths correct and plugins are fine I've been following your tutorial for the laravel integration but I can't make toggle the side bar what am I doing wrong?

**Comment by bedrop** [comment]
<script src="{{ asset ("/bower_components/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js") }}"></script>
NOT
<script src="{{ asset ("/bower_components/AdminLTE/plugins/jQuery/jQuery-2.1.3.min.js") }}"></script>

**Comment by MarkHartmann** [comment]
I have the same issue, use jQuery 2.1.4 already. Can't get the sidebar toggle button to work. Demos are running fine locally. Must be something odd with other css or js files.

**Comment by yengtot** [comment]
Mine's working already I forgot the greater than sign on one of my script paths:

before:
 <script src="{{ asset("/plugins/jQuery/jQuery-2.1.4.min.js")}}"</script>

after:
 <script src="{{ asset("/plugins/jQuery/jQuery-2.1.4.min.js")}}"></script>

**Comment by almasaeed2010** [comment]
If they are working locally then your server is case sensitive. Make sure all your files are included in a case-sensitive manner.

**Comment by Johnathon332** [comment]
I am getting a problem with this I have tried to incliude all the files necessary, here is how I have include them 


            <script src="~/plugins/jQuery/jQuery-2.1.4.min.js"></script>
            
            <script src="~/plugins/jQueryUI/jquery-ui.min.js"></script>
            
            <script>
                $.widget.bridge('uibutton', $.ui.button);
            </script>
            
            <script src="~/Scripts/bootstrap.min.js"></script>
            
            <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
            <script src="~/plugins/morris/morris.min.js"></script>
            
            <script src="~/plugins/sparkline/jquery.sparkline.min.js"></script>
            
            <script src="~/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
            <script src="~/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
            
            <script src="~/plugins/knob/jquery.knob.js"></script>
            
            <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
            <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
            
            <script src="~/plugins/datepicker/bootstrap-datepicker.js"></script>
            
            <script src="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
            
            <script src="~/plugins/slimScroll/jquery.slimscroll.min.js"></script>
            
            <script src="~/plugins/fastclick/fastclick.min.js"></script>
            
            <script src="~/dist/js/app.min.js"></script>
            
            <script src="~/dist/js/pages/dashboard.js"></script>
            
            <script src="~/dist/js/demo.js"></script>
