### ISSUE TITLE
Sidebar: Badge is not aligned to menu item

### ISSUE THREAD

**Issue by nqv** [almasaeed2010/AdminLTE#752]
Since v2.3.1 all badges are not aligned to menu items in sidebar.
Tested on Firefox 39.0.3 on MacOS X 10.10.3
![Screenshot](http://i.imgur.com/N7Dk4Nk.png)

**Comment by crperlin** [comment]
firefox 41 on window me too!!

**Comment by almasaeed2010** [comment]
Fixed in 2.3.2 (will be released soon)

Thanks for sharing this!
