### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by MaticConradi** [almasaeed2010/AdminLTE#753]
Is there a way to get date range picker (from-to) style date picker (single date)
![screen shot 2015-10-23 at 14 14 45](https://cloud.githubusercontent.com/assets/5693961/10692253/8167ca92-7990-11e5-9905-d3c03719515f.png)

**Comment by githubjeka** [comment]
See http://www.daterangepicker.com/#examples

**Comment by MaticConradi** [comment]
Thanks. I've fixed it.
