### ISSUE TITLE
Got 2 issues

### ISSUE THREAD

**Issue by Alex2k15** [almasaeed2010/AdminLTE#754]
1. I want to add a background image but when i try it still is gray. I just want the background for login and register to have the image background no other pages.....

2. How do i remove the error "@ is required". I want people to login with username not email

**Comment by jlamer** [comment]
I am not sure about the first one, but second can be solved by changing type of input from "email" to "text". It is just feature implemented in modern **browsers* and not AdminLTE itself.

How you tried to add image background? You should try to find CSS declaration with background color, for example with developer tools of some browser, and then change properties ralated to background.

**Comment by Alex2k15** [comment]
Yeah 
body {
    background: url("back.png") no-repeat center center fixed;
    background-size: cover; 
}

**Comment by jlamer** [comment]
If you look at source code of https://almsaeedstudio.com/themes/AdminLTE/pages/examples/login.html you see background is defined on element with class .login-page, .register-page ... your declarations are probably overwritten. Either use !important: background: url("back.png") no-repeat center center fixed !important; ... Or try to use more specific selector:

.login-page, .register-page {
  background: url("back.png") no-repeat center center fixed;
  background-size: cover; 
}

... that could do it.

**Comment by Alex2k15** [comment]
Thanks!

**Comment by jlamer** [comment]
No problem, glad I could help, please close issue if it was resolved.

**Comment by Alex2k15** [comment]
> How?

**Comment by kressly** [comment]
To close the issue, come back to this page. U will see a button close under the form or a button comment and close. Click on the button close or if u want to add a comment click on comment and close
