### ISSUE TITLE
Sidebar submenu arrow wrongly rendered in Firefox

### ISSUE THREAD

**Issue by syphernl** [almasaeed2010/AdminLTE#755]
With the latest AdminLTE it seems that the arrow of the submenu is being rendered wrong in Firefox 41.0.2, also on the [preview page](https://almsaeedstudio.com/themes/AdminLTE/index2.html):

Closed:
![adminlte_2_dashboard_-_2015-10-26_09 50 55](https://cloud.githubusercontent.com/assets/639906/10724747/16430f36-7bc7-11e5-809a-1cd84cae9cc7.png)

Open:
![adminlte_2_dashboard_-_2015-10-26_09 48 34](https://cloud.githubusercontent.com/assets/639906/10724721/e8998efc-7bc6-11e5-8ce3-2afdfe3db325.png)

In Chrome (46) it is working fine though.

**Comment by crperlin** [comment]
please update admin-lte v2.3.2; this version fix that bug ;

**Comment by syphernl** [comment]
Thanks, this resolved the issue indeed.
