### ISSUE TITLE
select2 input:focus border

### ISSUE THREAD

**Issue by githubjeka** [almasaeed2010/AdminLTE#756]
![image](https://cloud.githubusercontent.com/assets/874234/10726946/4650d1d4-7be7-11e5-9c16-2e923f5032f0.png)

**Comment by githubjeka** [comment]
Why is it closed?

**Comment by ajcastro** [comment]
Yeah not fixed. Same here.

![image](https://user-images.githubusercontent.com/4918318/27462267-16f98910-57f2-11e7-89fa-b4c7c1597bac.png)

**Comment by ajcastro** [comment]
Possible css fix, via chrome dev tools only to give you hints.

![image](https://user-images.githubusercontent.com/4918318/27462410-47a11fa0-57f3-11e7-84a7-0300b9a39e3b.png)

![image](https://user-images.githubusercontent.com/4918318/27462451-8b0b84f6-57f3-11e7-8e39-bf9bf40ee96e.png)
