### ISSUE TITLE
invoice print

### ISSUE THREAD

**Issue by paulop** [almasaeed2010/AdminLTE#757]
Hi
https://almsaeedstudio.com/themes/AdminLTE/pages/examples/invoice.html
I added this code before close section
```
<div class="row text-center">
        <small>Impresso em 26/10/2015 às 12:05:53 por Paulo 2</small>
    </div>

</section>"
```
![image](https://cloud.githubusercontent.com/assets/1051668/10737538/88687a0e-7bf1-11e5-9f1b-53c2c73c4cb9.png)

I want to add an invoice-footer class that is at the bottom of each page and fix sidebar witdh. how can I do it?
to print using Ctrl + p more easily.

**Comment by ahmedgaduo1** [comment]
I have same problem

**Comment by rafael-renan-pacheco** [comment]
Hi Paulo!

This is browser related. Look at the sidebar an option called "Margens: Padrão". If you change this option to margin none, the left padding will disappear. I guess you can't override this option with your web-app.

About the footer, does your html (non-print version) has the footer at the bottom? Try zoom out the page to see if the footer is sticked at the bottom. If not, then you first need to fix this in your non-print version. Search google for "css flex footer", or something about fixing the footer at the bottom of the page. This is a common issue regarding footers, which is solved easily with flex boxes.

Best regards,
Rafael.

**Comment by paulop** [comment]
Thanks for replying

I found this template, and it works by pressing Ctrl + P
http://192.185.228.226/projects/ma/1-5-1/jquery/invoice.html

but I do not know much about css.
the previous version of adminlte the sidebar was completely hidden and Ctrl + p worked well.

![adminlte 2 invoice - google chrome](https://cloud.githubusercontent.com/assets/1051668/10828310/696252c0-7e52-11e5-8f7b-b73adc0a2452.jpg)

![adminlte 2 invoice - google chrome_2](https://cloud.githubusercontent.com/assets/1051668/10828317/72875f44-7e52-11e5-8fd7-d0cb08300a37.jpg)
![prtscr capture](https://cloud.githubusercontent.com/assets/1051668/10828328/7effa02e-7e52-11e5-8a03-d37f1d8e9f6c.jpg)

about the footer, I will see how I will do

**Comment by rafael-renan-pacheco** [comment]
Wow, they handled the print margin very well.

Look for "@media print" css, it will aply css only on print mode. Try to understand how that admin template did that magic with media print css.

To simulate the @media print css on Chrome, enabling you to understand and inspect the elements, press F12, then click on the mobile icon (top-left). After, expand the footer console (press esc to show it), and click on the "Emulation" tab. On that tab, select "Media" on the navigation menu, check the "CSS media" checkbox, and select "print" on the dropdown. After that, Chrome will now render you html the "same" way Ctrl+P would do to generate your print version. This will allow you to investigate the elements and what they did with the css to achieve that result.

Best regards,
Rafael.

**Comment by ankitsam** [comment]
Just need to add this print media style to remove margin

    @media print {
        .content-wrapper, .right-side, .main-footer{
            margin-left:0;
            transition:none;
        }
    }
