### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by abuzubair** [almasaeed2010/AdminLTE#760]
Any JS or CSS problem. Please help me to solve it.

**Comment by Mythos** [comment]
To be able to help you, you should clearly add more information.

**Comment by almasaeed2010** [comment]
@abuzubair if you have an issue, briefly state the problem in the title and then add a full description of the issue. You can include screenshots, code or steps to replicate the issue. Once you have all of the information, open a new issue and we'll be happy to help.

Thanks,
Abdullah
