### ISSUE TITLE
How to get notifaction and inbox working?

### ISSUE THREAD

**Issue by Alex2k15** [almasaeed2010/AdminLTE#763]
Is there like a script i can usE?

**Comment by YasserHassan** [comment]
This is out of the scope of AdminLTE which is a front-end template only. You need to implement these features yourself.

**Comment by Alex2k15** [comment]
Is there somewhere i can get these scripts

**Comment by kressly** [comment]
No you have develop, create the kind of script u want to use for ur system. AdminLte is just a template, like a what some call a design. U have to now use that design and program whatever u want on it

**Comment by Alex2k15** [comment]
I have no idea how to..i just want a way where i can send my clients a notifaction and it closes when clicked on x. And certain notifactions for users on the dropdown notifaction s

**Comment by danielslim** [comment]
You can look into api services like Pusher but you do need to implement your web app like database to hold users notification message when they are off line and offset read message when they acknowledge, or if you prefer to do real time notification, more comprehensive but difficult using Nodejs and socketIO It's not some simple script you can find and blend into your web app.
