### ISSUE TITLE
Please update the colorpicker plugin

### ISSUE THREAD

**Issue by fera2k** [almasaeed2010/AdminLTE#764]
your version of colorpicker plugin is outdated. Many bugs have been fixed there.

**Comment by crperlin** [comment]
this version plugins haven't write into bower `--save-dev` , so can't  onekey upgrade ; bower manager depenice when admin-lte v3 ; you want upgrade plugins , need you operate

**Comment by fera2k** [comment]
Cool! Thanks for your answer. 
Thanks for your good work.
