### ISSUE TITLE
Reorder elements in a list

### ISSUE THREAD

**Issue by leonardop17** [almasaeed2010/AdminLTE#765]
Hello! You can add the management of a sortable list? ex. https://jqueryui.com/sortable/

Thank you in advance

**Comment by almasaeed2010** [comment]
Hi!

jQueryUI Sortable is already used in [index.html](https://github.com/almasaeed2010/AdminLTE/blob/master/index.html).

**Comment by leonardop17** [comment]
Sorry. The only page that I had not seen . Dashboard 2 is the default page
