### ISSUE TITLE
"Conflict" between embed-responsive and col-xs-6 class

### ISSUE THREAD

**Issue by FernandoGarcia** [almasaeed2010/AdminLTE#766]
Hi!

I have a problem when using an embed video and a box with knobs in a row.

When the window is smaller the video pull the box to down but the box isn't resized correctly.

See the images:
![conflict1](https://cloud.githubusercontent.com/assets/2778501/10800453/01d414cc-7d99-11e5-8072-43399c295ef3.PNG)

![conflict](https://cloud.githubusercontent.com/assets/2778501/10800456/0901d5a4-7d99-11e5-889c-48cc4481dd84.PNG)

Here my code:

		<div class="row">
			<div class="col-sm-6">
				<h3>IP camera</h3>
				<div class="embed-responsive embed-responsive-16by9">
					<iframe class="embed-responsive-item" src="//www.youtube.com/embed/DI4zEQ_9WnQ?autoplay=1"></iframe>
				</div>
			</div>
			<div class="col-xs-6">
                  <h3 class="box-title">LED power</h3>
                <div class="box-body">
                  <div class="row">
                    <div class="col-xs-4 text-center">
                      <input type="text" class="knob" value="100" data-min="0" data-readOnly=true data-width="120" data-height="120" data-fgColor="#FFFFFF">
                      <div class="knob-label">White</div>
                    </div>
                    <div class="col-xs-4 text-center">
                      <input type="text" class="knob" value="100" data-min="0" data-readOnly=true data-max="100" data-width="120" data-height="120" data-fgColor="#09B8FF">
                      <div class="knob-label">Blue</div>
                    </div>
                    <div class="col-xs-4 text-center">
                      <input type="text" class="knob" value="100" data-min="0" data-readOnly=true data-max="100" data-width="120" data-height="120" data-fgColor="#3A5FCD">
                      <div class="knob-label">Royal blue</div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-xs-6 text-center">
                      <input type="text" class="knob" value="100" data-min="0" data-readOnly=true data-max="100" data-width="120" data-height="120" data-fgColor="#FF0000">
                      <div class="knob-label">Red</div>
                    </div>
                    <div class="col-xs-6 text-center">
                      <input type="text" class="knob " value="100" data-min="0" data-readOnly=true data-max="100" data-width="120" data-height="120" data-fgColor="#E066FF">
                      <div class="knob-label">UV</div>
                    </div>
                  </div>
                </div>
            </div>
          </div>

Can you give some suggestion to solve this issue?

Sorry if it's very basic I'm a newbie.

Best regards.

**Comment by fschaeffer** [comment]
Hello,

you're mixing col-sm6 and col-xs-6 in your row. That means that even in the lowest resolution your second column will always have 1/2 of the available width. Add col-sm-6 and remove col-xs-6 from the second row and you're done.

**Comment by FernandoGarcia** [comment]
Hi!

Thank you very much!
Problem solved. :)
![solved](https://cloud.githubusercontent.com/assets/2778501/10845726/7c41c980-7ef1-11e5-9514-9b21f07189a5.PNG)
