### ISSUE TITLE
Burger Icon on the left

### ISSUE THREAD

**Issue by Mythos** [almasaeed2010/AdminLTE#767]
Hello,

is it somehow possible to place the burger icon on the left instead of the right side of the title?
Just placing it before the logo breaks it on phones.

Regards,
Stefan

**Comment by rafael-renan-pacheco** [comment]
Can you provide some screenshot of this issue?

**Comment by Mythos** [comment]
Of course.

**This is the normal burger icon placement:**
*Desktop*
![normal_burger_desktop](https://cloud.githubusercontent.com/assets/416568/10821793/82b3757c-7e54-11e5-98f0-f678265657e7.JPG)
*Mobile*
![normal_burger](https://cloud.githubusercontent.com/assets/416568/10821737/3631d6da-7e54-11e5-9a0d-17c11c8134cc.JPG)

**This is when I place it before the logo:**
*Desktop*
![messed_burger_desktop](https://cloud.githubusercontent.com/assets/416568/10821790/79602f92-7e54-11e5-8a3a-751f220078ec.jpg)
*Mobile*
![messed_burger](https://cloud.githubusercontent.com/assets/416568/10821738/364cbbbc-7e54-11e5-90e8-9533cf1446e2.jpg)


Our goal is to display the burger icon on the left on desktops/tablets. Mobile version is fine in the "original" state.

**Comment by almasaeed2010** [comment]
This could be achievable but will require a bit of work to override the ```.sidebar-toggle``` button/link and the ```.logo``` (logo part of the header). Unfortunately, I don't currently have time to experiment with this but I hope someone else will be able to help you.
