### ISSUE TITLE
Template behaves strangely in firefox browser.

### ISSUE THREAD

**Issue by ivlevdenis** [almasaeed2010/AdminLTE#768]
Elements sidebar pulled right has a large top margin.
![with white-space](http://storage7.static.itmages.com/i/15/1029/h_1446126126_8492423_4a92c4c284.png)

But if turn off **white-space** css param for **.sidebar-menu, .main-sidebar .user-panel, .sidebar-menu > li.header**, all work fine.
![with white-space](http://storage8.static.itmages.com/i/15/1029/h_1446126710_6399970_5dc026eb96.png)

FF 41.0.2.
In chrom* everything works fine.

**Comment by crperlin** [comment]
please upgrade  new version .new version fixed that BUG
