### ISSUE TITLE
print css, page break

### ISSUE THREAD

**Issue by lenamtl** [almasaeed2010/AdminLTE#77]
I'm trying to add page break between timeline with no luck.

 div.timeline-item  {
  page-break-after: always;
}

or 

div.timeline-item  {
  display: block; page-break-after: always;
}

Any clue?

I think that @media print css should be grouped and/or placed in other css file

It's look like that page-break doesn't work at all even in other element page
even if I use a reset
body \* { float: none !important; }

If possible I prefer keep float for better cosmetic printing 
Any suggestion?

**Comment by lenamtl** [comment]
I have posted my print.css 
#199

**Comment by kressly** [comment]
Thanks a lot
