### ISSUE TITLE
calendarDragAndDrop

### ISSUE THREAD

**Issue by bsnarayana** [almasaeed2010/AdminLTE#770]
Hi sir....
In full calendar.js plugin i want to add number of rows and columns(instead of 6x7)....but i unable to identify where can i write the coding to increase rows and columns...can u help where can i add that.

i will be eagerly waiting for your reply

thanking u...
bs narayana
![calendar](https://cloud.githubusercontent.com/assets/15378344/10839327/7e5c1886-7ef8-11e5-9510-0c48cbd21637.png)

**Comment by rafael-renan-pacheco** [comment]
If such feature does exists, you need to search on their repo/forum/site (http://fullcalendar.io/).

**Comment by almasaeed2010** [comment]
Hi!
As @rafael-renan-pacheco suggested, you should ask about this feature on the fullcallendar site. We apologize for the inconvenience!
