### ISSUE TITLE
Expand Collapse Problem in Page  Postback

### ISSUE THREAD

**Issue by RussellGit** [almasaeed2010/AdminLTE#773]
Hi,

I have used this AdminLTE template with asp.net mvc 5. 
But I’ve faced a problem. When I navigate different views, the menu has been collapsed. Which should be expand and keep active the current navigation menu. But it’s collapsed after each page postback.
what am I doing wrong?
Thank you

**Comment by almasaeed2010** [comment]
Please review this [comment](https://github.com/almasaeed2010/AdminLTE/issues/710#issuecomment-148343824) which addresses the issue of sidebar state persistence. The gist of it is that for now you are required to handle the state from your server side. A new feature for handling persistence may be implemented in v3.

Thanks and sorry for the inconvenience.
