### ISSUE TITLE
Skins are not changed in IE browsers 

### ISSUE THREAD

**Issue by subho1st** [almasaeed2010/AdminLTE#776]
I have faced a issue in IE browser, when I click on any skins from right panel but it is not effected in IE browser. But in all major browsers it is working fine.
![image](https://cloud.githubusercontent.com/assets/15646033/10931414/3017f2fa-82ed-11e5-970b-ec0c638e2531.png)

**Comment by crperlin** [comment]
this is effect write to  `demo.js`; you can open this file read !!

**Comment by subho1st** [comment]
Can you please clarify how to fix this issue for ie 10. I have checked
demo.js but what should I do or write for ie. Please help

On Wednesday, November 4, 2015, CRPER <notifications@github.com> wrote:

> this is effect write to demo.js; you can open this file read !!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almasaeed2010/AdminLTE/issues/776#issuecomment-153609267>
> .
>


-- 
Rajdeep Dey
Web/GraphicsDesigner

**Comment by subho1st** [comment]
I have read the file all values are set there as variable. But What should I do. In all major browser skin changing effect is working except IE. When I see from live demo it is working fine but whenever I download the zip file and run it from my local system it is not working. IE console shows error in localstorage in demo.js

**Comment by subho1st** [comment]
@crperlin can you please help me out from this problem

**Comment by crperlin** [comment]
@subho1st   work for me !! ie10~ie 11 ; you must run into server!!!can local server , but can't `file://path`!!! 

all component woking it!!!

![image](https://cloud.githubusercontent.com/assets/8272877/10938120/ae556d9c-8332-11e5-8356-e06e5fab590e.png)

**Comment by almasaeed2010** [comment]
@subho1st please make suer that your browser console shows no errors. For instructions on how to get the developer's tools, you may find them on [MSDN](https://msdn.microsoft.com/library/bg182326(v=vs.85)).

**Comment by subho1st** [comment]
thanks it is working fine now

On Wed, Nov 4, 2015 at 6:00 PM, CRPER <notifications@github.com> wrote:

> @subho1st <https://github.com/subho1st> work for me !! ie10~ie 11 ; you
> must run into server!!!can local server , but can't file://path!!!
>
> all component woking it!!!
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/8272877/10938120/ae556d9c-8332-11e5-8356-e06e5fab590e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almasaeed2010/AdminLTE/issues/776#issuecomment-153705985>
> .
>



-- 
Rajdeep Dey
Web/GraphicsDesigner
