### ISSUE TITLE
javascript parse data to modal issue

### ISSUE THREAD

**Issue by elsetsuna** [almasaeed2010/AdminLTE#777]
```javascript
  $(document).on( "click", '.edit_button',function() {

        var rno = $(this).data('rno');
        var rname = $(this).data('rname');
        var rpoint = $(this).data('rpoint');
        var rremarks = $(this).data('rremarks');
        var rewcreate = $(this).data('rewcreate');
        var rewupdate = $(this).data('rewupdate');

        $(".modal-body #rno").val(rno);
        $(".modal-body #rname").val(rname);
        $(".modal-body #rpoint").val(rpoint);
        $(".modal-body #rremarks").val(rremarks);
        $(".modal-body #rewcreate").val(rewcreate);
        $(".modal-body #rewupdate").val(rewupdate);
    });
```
```hyml
    <button class="btn btn-info edit_button" type="submit" name="submit" data-toggle="modal" data-target="#myModal" data-rno="'.$rno.'" data-rname="'.$rewname.'" data-rpoint="'.$rewpoint.'" data-rremarks="'.$rewremarks.'" data-rewcreate="'.$rewcreate.'" data-rewupdate="'.$rewupdate.'"></button>
```

i use the above method to parse data to modal... it works pretty well on other template...only in AdminLTE the script doesnt work..i've been googling for awhile but cant find a clue... can anyone point me to a proper direction where i can solve this issue?

**Comment by almasaeed2010** [comment]
Hello,

Could you provide the HTML code for your page?

**Comment by elsetsuna** [comment]
here you go... dont comment on my php skill..im quiet new in php 

http://pastebin.com/Ds2w5ERP

**Comment by almasaeed2010** [comment]
From the link you submitted, you forgot to add ```</script>```.

**Comment by elsetsuna** [comment]
ups sorry but after i put </script> it also not working...im using the clean bootstrap and its working but in your admin lte is not... im wondering if your other templates also like this? since i plan to get the premium template

**Comment by almasaeed2010** [comment]
This isn't a template problem. It's a bug in the code. Did you check the browser's console for any errors?

**Comment by elsetsuna** [comment]
![555](https://github-cloud.s3.amazonaws.com/assets%2F11795235%2F10958214%2F92a3fc8c-839e-11e5-9815-8cae5845f144.PNG)
i got this error in console...  the 1st error is the error in $(document) in the javascript
2nd one is from moment.js
3rd is from DataTables.js

**Comment by almasaeed2010** [comment]
This says you didn't load jQuery. Could make sure you have all the resources loaded?

**Comment by elsetsuna** [comment]
http://pastebin.com/HrbFVGzR
 
yup its loaded on the footer file :D

**Comment by elsetsuna** [comment]
okay...i solved it already... i included hte JQuery librabry once again on the top of the file... so i included twice once on the footer together with others and then on the top of the file

**Comment by almasaeed2010** [comment]
You should move all of your JavaScript code to the bottom of the file after loading jQuery. Also, you should wrap your code in an anonymous function or jQuery's document.ready() function.

Good luck!
