### ISSUE TITLE
Tag Inputs for AdminLTE

### ISSUE THREAD

**Issue by philxtian** [almasaeed2010/AdminLTE#782]
Any suggestions for tag input which I can use with AdminLTE template? I tried to search from google but this is the most closest I got.

ngTagsInput - http://mbenford.github.io/ngTagsInput/documentation/guides/bootstrap

I tried this but I still couldn't get the css style close to what we have in Select2 Multiple example from the link below.

https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html

Does Select2 support custom user input with tags multiple? Also seached from the repo and I think it is not.

**Comment by YasserHassan** [comment]
Try [Select2](https://select2.github.io/), [Selectize](http://brianreavis.github.io/selectize.js/), and [Chosen](https://harvesthq.github.io/chosen/).
