### ISSUE TITLE
jquery issue

### ISSUE THREAD

**Issue by athiragopan** [almasaeed2010/AdminLTE#783]
I have included
 "bootstrap/js/bootstrap.min.js" and "dist/js/app.min.js" at the footer. 
But i have ajax loaded page in which i use box collapse feature. so i need the above library to be in cluded in that page also(ajax loaded page).
now if i come back from this page without page refresh then my sidebar links are toggling.
what shall i do?

I have tried to include in header but the UI is affecting.

**Comment by almasaeed2010** [comment]
Which version of AdminLTE are you using?
please refer to: #302

**Comment by athiragopan** [comment]
@version 2.2.1

**Comment by athiragopan** [comment]
to which version should i change? should i change both bootstrap and app.js?

**Comment by almasaeed2010** [comment]
You should use the latest version [v2.3.2](https://github.com/almasaeed2010/AdminLTE/releases/tag/v2.3.2)
