### ISSUE TITLE
rtl - idea:  maybe to try cssjanus

### ISSUE THREAD

**Issue by shimondoodkin** [almasaeed2010/AdminLTE#785]
cssjanus is an automatic right to left converter.

https://github.com/cssjanus/grunt-cssjanus

https://www.npmjs.com/package/cssjanus

maybe create a copy of all files that is rtl inversed.

however its not that easy
i've already seen rtled templates with problems in scripts when menu is hidden by using left margin. and who made the rtl version changed only the css and forgot to edit the scripts.

also there might be problems of flipping the font icons  like arrows of menus

**Comment by lxsameer** [comment]
I already did, and created a gem which can be used in any project. It contains both RTL and LTR version in SASS and built automatically

checkout: `Yellowen/admin_lte-rails`

**Comment by shimondoodkin** [comment]
sounds very good
