### ISSUE TITLE
Question on transition and transform

### ISSUE THREAD

**Issue by LeonardoGentile** [almasaeed2010/AdminLTE#786]
Hello,
I could could not figure out this part of the code in `core.less` where transition and transform are used together.
```
/*
 * Content Wrapper - contains the main content
 * ```.right-side has been deprecated as of v2.0.0 in favor of .content-wrapper  ```
 */
.content-wrapper, 
.right-side,
.main-footer {    
  //Using disposable variable to join statements with a comma
  @transition-rule: @transition-speed @transition-fn,
                    margin @transition-speed @transition-fn;
  .transition-transform(@transition-rule);
 // ...
```
What are you actually doing with `@transition-rule: @transition-speed @transition-fn, margin @transition-speed @transition-fn;`? is it supposed to be a less trick for conditional assignment? The previous block is compiled into this
```
.content-wrapper,
.right-side,
.main-footer {
  -webkit-transition: -webkit-transform 0.3s ease-in-out, margin 0.3s ease-in-out;
  -moz-transition: -moz-transform 0.3s ease-in-out, margin 0.3s ease-in-out;
  -o-transition: -o-transform 0.3s ease-in-out, margin 0.3s ease-in-out;
  transition: transform 0.3s ease-in-out, margin 0.3s ease-in-out;
  margin-left: 230px;
  z-index: 820;
}
```
I'm not that proficient in css3 but are those commas supposed to be there or are they leftovers of the conditional assignments in less. Is this valid css?

Thanks

**Comment by almasaeed2010** [comment]
Hello,

LESS doesn't allow for commas in mixins. So we had to extract the argument into a destroyable variable and pass it to the mixin. The comma here is to tell the browser to watch for margin and transform changes for the elements. Any changes should be simulated with a transition. 

This is a valid CSS. All of our code is validated with code linters that prohibits us from using invalid code or non-best practices styles.

Thanks!

**Comment by LeonardoGentile** [comment]
:+1:  Thanks!
