### ISSUE TITLE
Multiple Select with select2 overlaps 

### ISSUE THREAD

**Issue by dexterb2992** [almasaeed2010/AdminLTE#787]
This is the screenshot on which the selected elements overlaps on the multiple select field
http://prntscr.com/913dup

**Comment by almasaeed2010** [comment]
Which AdminLTE version are you using?

**Comment by dexterb2992** [comment]
AdminLTE v2.1.2

**Comment by almasaeed2010** [comment]
Upgrade to the latest version. This issue is fixed there.

**Comment by dexterb2992** [comment]
ah, ok thanks!
