### ISSUE TITLE
ReactJS + Webpack Implementation

### ISSUE THREAD

**Issue by booleanhunter** [almasaeed2010/AdminLTE#788]
Hi

First of all, I would like to say that your project is nothing short of amazing, and thank you so much for this.

I have started a ReactJS + Webpack implementation of this project at https://github.com/ashwin01/ReactJS-AdminLTE. The widgets page is almost completed. Would love to hear your opinion on it.

Note: The widgets use [velocity.js](http://julian.com/research/velocity) for animations.

Thanks once again!

**Comment by crperlin** [comment]
@ashwin01 HI, how to use `velocity.js` replace `app.js` inner `animatie speed`; thanks

**Comment by ashwin01** [comment]
Hi @crperlin, to replace the animation speed, you can go to public/js/widgets/common-functions.js and change the duration there. Then you need to run webpack.

**Comment by crperlin** [comment]
@ashwin01  you use `RE` replace `animate`, if can't use webpack ,[on static website] can replace `velocity.js` into admin lte `app.js` duration , provide fast animate !!! thanks

**Comment by ashwin01** [comment]
I'm not sure I understood what you mean @crperlin. I'm writing the functions / variables from app.js in another file the AMD way, which later is bundled by webpack, to avoid variables / functions from getting exposed in the global namespace.

**Comment by crperlin** [comment]
@ashwin01 yes ...

**Comment by ashwin01** [comment]
@crperlin  I've submitted a [PR](https://github.com/almasaeed2010/AdminLTE/pull/790) for this, please have a look.

**Comment by almasaeed2010** [comment]
@ashwin01 nice work! I will add your implementation to our documentation. Please let us know when you have completed the pages. This looks promising :+1:

**Comment by ashwin01** [comment]
@almasaeed2010 Thanks a lot!!

**Comment by crperlin** [comment]
@ashwin01 thank you ! I have successfully replaced `app.js` inner , use `velocity.js` .. so fast!!

**Comment by ashwin01** [comment]
@crperlin Glad you found it useful. :)

**Comment by ivantcholakov** [comment]
@crperlin Could you publish somewhere a live demo?

**Comment by crperlin** [comment]
@ivantcholakov   yes ,, [look my demo](http://crperlin.github.io/S-NEXT/)

**Comment by ivantcholakov** [comment]
Thank you.

**Comment by ashwin01** [comment]
@almasaeed2010 The widgets page is ready...!
