### ISSUE TITLE
Like modal background effect for sidebar

### ISSUE THREAD

**Issue by yaniv14** [almasaeed2010/AdminLTE#789]
Hi,

It's not an issue but a request.
Is there an easy way of making a like modal background effect when opening the sidebar.
Putting lower opacity on the entire page beside the sidebar.

Thanks

**Comment by YasserHassan** [comment]
This is an overlay. You can find a lot of examples for it on the Web.

**Comment by almasaeed2010** [comment]
Hi,

Here is a tutorial on how to create an overlay http://tympanus.net/codrops/2013/11/07/css-overlay-techniques/

**Comment by yaniv14** [comment]
Thanks.
