### ISSUE TITLE
TypeError: $.AdminLTE is undefined

### ISSUE THREAD

**Issue by Johnathon332** [almasaeed2010/AdminLTE#791]
I am getting this error "TypeError: $.AdminLTE is undefined"  when trying to paste your HTML and linking all your javascript code in my MVC5 application, this happened in the app.min.js file and not sure why I am getting this.

Thanks
John

**Comment by Johnathon332** [comment]
Issue was with the placement of the reference to the script file

**Comment by jbitt12** [comment]
where did you need the reference to be? @Johnathon332  Getting same error. I'm referencing app.min.js in my javascript application file

**Comment by Lionqueen94** [comment]
I would love to know this too, I have some external js and that causes this error to occur making my page look worse... tried every location for defining that extra js but nothing is working
