### ISSUE TITLE
Expanded on page load?

### ISSUE THREAD

**Issue by dukesmash** [almasaeed2010/AdminLTE#793]
Currently by default the sidebar nav is applying the class .sidebar-collapse on page load. I am a javascript super-novice, so can anyone let me know how to make it so that the sidenav default state is expanded on desktop devices and collapsed on mobile devices?

Thanks in advance!

**Comment by almasaeed2010** [comment]
If you are using the demo.js file, please remove it. Otherwise, on your html file, remove the class ```sidebar-collapse``` from the ```body``` tag. That's it :+1:

**Comment by dukesmash** [comment]
That made too much sense lol. You do great work!

Thank you so much for the fast response.
