### ISSUE TITLE
Telerik radcontrols datepicker refusing to show in admin lte

### ISSUE THREAD

**Issue by cmsni** [almasaeed2010/AdminLTE#794]
I am using your theme in a asp.net masterpage driven scenraio and having a few issues one the popup under name is refuisng to load under sub pages and also teleriks raddatepicker is refusing to show on a page specifically the popup part of it.

**Comment by rafael-renan-pacheco** [comment]
Did you check for console errors when trying to open raddatepicker?

Also, telerik is a proprietary solution, try to ask on their forum. Will be hard for us to help you, unless someone already saw this issue before with telerik raddatepicker.

**Comment by cmsni** [comment]
I solved this its an awesome theme buddy. You should make a friendlist option and chat similar to facebook for the admin theme people would love it
