### ISSUE TITLE
How to integrate AdminLTE with AngularJS?

### ISSUE THREAD

**Issue by surajdalvi** [almasaeed2010/AdminLTE#795]
HI
I am new to AdminLTE. I want to integrate this theme with Angularjs please help me into this?

**Comment by githubjeka** [comment]
No way. AdminLTE dosen't support AngularJs.

**Comment by almasaeed2010** [comment]
Unfortunately, we do not support AngularJS in the current version. We apologize for the inconvenience.

**Comment by kanekesdotcom** [comment]
yes i've been try it. its cant working with angular

**Comment by dev01prishusoft** [comment]
Hi Guys, 

Here I would like to share very good blog which provides step by step instruction of "[How to Integrate AdminLTE theme to Angular Project"](https://www.prishusoft.com/blog/Integrate-AdminLTE-theme-to-Angular-Project.html)

https://www.prishusoft.com/blog/Integrate-AdminLTE-theme-to-Angular-Project.html
