### ISSUE TITLE
How to integrate AdminLTE with cakePHP 2.x

### ISSUE THREAD

**Issue by bhishmaRlx** [almasaeed2010/AdminLTE#796]
Hey, I am cakePHP developer, I want to integrate AdminLTE template with my cake version 2.x, but don't know how to integrate it.

**Comment by bhishmaRlx** [comment]
Hey, somebody who has integrated it with cakePHP please tell me.

**Comment by YasserHassan** [comment]
Check this https://github.com/SahilDude89ss/AdminLTE-CakePHP and this https://github.com/sherwinrobles/CakeAdminLTE

**Comment by bhishmaRlx** [comment]
Thank you Yasser.

**Comment by YasserHassan** [comment]
You can use those repos to have an idea to start with. This is more of a CakePHP issue than AdminLTE.

**Comment by bhishmaRlx** [comment]
Thanks @YasserHassan , I looked on repository structure of https://github.com/SahilDude89ss/AdminLTE-CakePHP  and made few changes, after few hours finally I achieve this goal.

I will share a link here after uploading the code to a repository for this.

**Comment by bhishmaRlx** [comment]
Solved:
https://github.com/bhishmaRlx/AdminLTE_CakePHP/
