### ISSUE TITLE
Blank space in toggled sidebar

### ISSUE THREAD

**Issue by llermaly** [almasaeed2010/AdminLTE#797]
I dont know why is this happening , I checked all css one by one and couldnt find the error,  I replaced the sidebar code with the original from AdminLTE and problem persists. Please Help!

http://i.stack.imgur.com/hLGnN.png

Problem is when I pass over the space the menu hides and I cant click tree options when toggled

**Comment by crperlin** [comment]
Hi, @llermaly ;
I'm work it; please upgrade new version!

look me create template for basic lte 

demo link : http://crperlin.github.io/S-NEXT/

**Comment by llermaly** [comment]
Hello @crperlin , I'm working with 2.3.2 version , and I cant figure out whats going on , but thanks for your help :+1:

**Comment by almasaeed2010** [comment]
@llermaly did you change the global font-size?

Unfortunately, AdminLTE 2 has a glitch in sidebar-mini when the font-size changes.
