### ISSUE TITLE
Feature : I made a live menu search

### ISSUE THREAD

**Issue by cjmling** [almasaeed2010/AdminLTE#798]
My menu end up with long list so I thought I shall use that search box to search menu. And may be someone find this useful too.

- 1. I added a class to the search box

```<input type="text" name="q" class="form-control search-menu-box" placeholder="Search...">```

- 2. Added this jQuery script

```
$(".search-menu-box").on('input', function() {
    var filter = $(this).val();
    $(".sidebar-menu > li").each(function(){
        if ($(this).text().search(new RegExp(filter, "i")) < 0) {
            $(this).hide();
        } else {
            $(this).show();
        }
    });
});
``` 

Based on the codes from this link  http://www.designchemical.com/blog/index.php/jquery/live-text-search-function-using-jquery/

**Comment by almasaeed2010** [comment]
Thank you @cjmling! We are currently not adding new features to AdminLTE v2. However, we are implementing a similar feature for AdminLTE 3.0.

:+1:

**Comment by raminassar** [comment]
@cjmling but how you make sure to expand parent treeview-menu as well??

**Comment by refaelyehuda** [comment]
You can use with this functions

`$.fn.openMenu = function () {
        var className = $(this).attr('class');
		if(className == "treeview"){
			$(this).addClass("active");
		}else if(className == "treeview-menu" ){
			$(this).addClass("menu-open");
			$(this).css({ display: "block" });
		}
};`

`$.fn.closeMenu = function () {
        var className = $(this).attr('class');
		var count = $(this).length;
		if(count > 1){
			$.each($(this), function( key, element ) {
				className = $(element).attr('class');
				if(className == "treeview active"){
					$(element).removeClass("active");
				}else if(className == "treeview-menu menu-open" ){
					$(element).removeClass("menu-open");
					$(element).css({ display: "none" });
				}
			});
		}else{
			if(className == "treeview active"){
				$(this).removeClass("active");
			}else if(className == "treeview-menu menu-open" ){
				$(this).removeClass("menu-open");
				$(this).css({ display: "none" });
			}
		}
};`

And call to the functions like that : 

`$(".search-menu-box").on('input', function() {
    var filter = $(this).val();
    $(".sidebar-menu > li").each(function(){
        if ($(this).text().search(new RegExp(filter, "i")) < 0) {
            $(this).hide();
        } else {
            $(this).show();
            $(this).parentsUntil(".treeview").openMenu();
        }
    });
});`

I hope it's help to you

**Comment by durairajkumarrk** [comment]
getting an error $(...).parentsUntil(...).openMenu is not a function. 

Thanks

**Comment by refaelyehuda** [comment]
You load Jquery and declared on these functions before call to this $(...).parentsUntil(...).openMenu line?

**Comment by iprastha** [comment]
If you would like the search to include child items, simply replace 
```
...
$(".sidebar-menu > li").each(function(){
...
```
to
```
...
$(".sidebar-menu li").each(function(){
...
```

**Comment by surferxo3** [comment]
Where is the closeMenu function being used?
