### ISSUE TITLE
about import css file

### ISSUE THREAD

**Issue by bubifengyun** [almasaeed2010/AdminLTE#803]
in your 
https://github.com/almasaeed2010/AdminLTE/blob/master/build/less/AdminLTE.less
>@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);

however, when used in local network, it can not reach that site.
A friend has collected the zip file in http://files.cnblogs.com/files/tekikesyo/LocalGoogleFont.zip

code like, OK?

```css
@import url('local.google.fonts.css');
```

ref: http://www.cnblogs.com/tekikesyo/p/4636412.html

**Comment by rafael-renan-pacheco** [comment]
#744
#498

**Comment by bubifengyun** [comment]
thank you very much. I see.
