### ISSUE TITLE
Collapse top menu and scroll left menu

### ISSUE THREAD

**Issue by RoyTerrazas** [almasaeed2010/AdminLTE#804]
Hi friends I have 2 questions, i will try to explain the best I can:
 Im using the dashboard version 1, in this version there are several icons on the top right menu, this icons include de user photo and name, notification, email, tasks, etc. 
1st question: In the previously described menu I added a drop down menu there too on the top, but when i resize the design this menu doesn rezise propertly, and it is badly exposed, how can I make this  menu to add a regular button with the regular icon that shows up when the size of the display is small.

![1](https://cloud.githubusercontent.com/assets/13825009/11374615/2b4b39f6-9294-11e5-81f1-0a2604f262d2.jpg)

2 question, in the same version 1 of the dash menu, you can see a button that when you click on it, it will hide the left menu, but i have noticed that if you have a lot of options un the left menu you are forced to close them in order to see the bottom one, this means it does not scroll down, how can i make this menu to scroll down according the quantity of options it has?
![2](https://cloud.githubusercontent.com/assets/13825009/11374672/7a1b9e36-9294-11e5-9fef-6fd8fe859f8b.jpg)

thanks for your help

**Comment by rafael-renan-pacheco** [comment]
Regarding question number 2, I think you need to add SlimScroll js plugin to your page.

If you open this sample: https://almsaeedstudio.com/themes/AdminLTE/pages/layout/fixed.html
you will see that you can scroll the overflowed menu.

Best regards,

**Comment by almasaeed2010** [comment]
Does @rafael-renan-pacheco's answer solves your issue?

Thanks!
