### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by Johnathon332** [almasaeed2010/AdminLTE#805]
My sliders are just showing up as input text boxes both the ion and bootstrap ones.  

I was also wondering if I wanted to use the bootstrap ones but with only one slider and not dual, how I go about doing that?

**Comment by almasaeed2010** [comment]
It seems like you didn't load the appropriate JS and CSS files. To use the range slider plugin you need the following files:
- plugins/ionslider/ion.rangeSlider.css
- plugins/ionslider/ion.rangeSlider.skinNice.css
- plugins/ionslider/ion.rangeSlider.min.js

For the bootstrap slider:
- plugins/bootstrap-slider/slider.css
- plugins/bootstrap-slider/bootstrap-slider.js

To create a bootstrap slider without the range selector option, you can review their documentation where you will find what you want as the very first example
http://seiyria.com/bootstrap-slider/

Thanks

**Comment by hansaliyad1** [comment]
My slider shows up but it does not work. I mean it does not slide left to right or right to left. It just shows up. Does nothing. I made sure that my slider.css is added in the head and even script bootstrap-slider.js at bottom in script sections. It does not show me any errors in browser console. Any idea what problem I am facing?
