### ISSUE TITLE
content within php tags won't show in adminlte elements

### ISSUE THREAD

**Issue by andyhughes73** [almasaeed2010/AdminLTE#807]
Hi, loving the admin theme, but i'm struggling with a few things. One in particular.

So I'm using the dashboard for the backend of an installation called PHPVMS, which is a flight simulation management platform. I am able to include shortcode php calls into one element on the dashboard but as soon as I try it on the "box" elements, it doesn't seem to process the script.

The code I am entering is:
```html
<!-- ******************************* -->
<div class="box box-primary">
                <div class="box-header">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">VA Central Status</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                <p class="lead">
                This is tester text
					<?php
                        echo $updateinfo;
                     ?>
                      <?php
						if(Config::Get('VACENTRAL_ENABLED') == true && $unexported_count > 0)
						{ ?>
							You have <strong><?php echo $unexported_count?></strong> PIREPS waiting for export to vaCentral.
							<a href="<?php echo adminurl('/vacentral/sendqueuedpireps'); ?>">Click here to send them</a>
						<?php
						} ?></p>
                </div>
              </div>
<!-- *******************************

But then what I'm seeing when I look at the source code from the page through xampp, this is what I see:

******************************* -->
<div class="box box-primary">
                <div class="box-header">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">VA Central Status</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                <p class="lead">
                This is tester text
					</p>
                </div>
              </div>

<!-- ********************************* -->
```

Is there anything weird acting on the elements, say in JS, that would be stopping the php script from processing?

I've tried it a bunch of ways and I just can't get it to output the content in the box element.

Would appreciate any suggestions or pointers.

Thanks
Andy

**Comment by almasaeed2010** [comment]
Hello @andyhughes73,

I am not sure what the issue is, but it is a backend problem not caused by the template. Test the following code to verify that it is a php issue:

```php
<div class="box box-primary">
  <div class="box-header">
    <i class="ion ion-clipboard"></i>
    <h3 class="box-title">VA Central Status</h3>
  </div><!-- /.box-header -->
  <div class="box-body">
    <p class="lead">
      This is tester text
       <?php
        $test = "Testing if php is rendering";
         echo $test;
       ?>
      </p>
  </div>
</div>
```

If the result doesn't shows up correctly, then your php is not being executed properly and you should check the error log.

Thanks!

**Comment by andyhughes73** [comment]
Hi almasaeed2010,

I tried the code you supplied and it does indeed echo the statement which means php is being executed.

**Comment by almasaeed2010** [comment]
Then it must be an error in the logic. Did you test your values by ```var_dump()```?

**Comment by andyhughes73** [comment]
Strangely enough, the flight management software that I am using, uses dynamic page content and when i paste the code into one php page that is called by the overall page layout, it doesn't work. However, if I copy the code into another php page section that is called by the same overall page layout, it works just fine. Really strange.

Anyways, it seems to be working now, although I still have no idea what was stopping it working in the first php file.

Thanks for responding.

**Comment by almasaeed2010** [comment]
Good to hear that it worked. 

Good luck!
