### ISSUE TITLE
Bootstrap tab overflow

### ISSUE THREAD

**Issue by cyberzilla** [almasaeed2010/AdminLTE#808]
how to fix bootstrap overflow in one line
before:
![before](https://cloud.githubusercontent.com/assets/1154922/11436305/a403faa4-951e-11e5-8df3-a521f3da907b.jpg)
after:
![after](https://cloud.githubusercontent.com/assets/1154922/11436310/b38bb584-951e-11e5-808d-02815b0f1ce0.jpg)
or like firefox tab:
![this](https://cloud.githubusercontent.com/assets/1154922/11436398/4bb84322-951f-11e5-8a5c-d9cdb1d61843.png)
i want to implement in my project (Admin LTE Base):
http://adminprototype.dedymiswar.com

need help

**Comment by rafael-renan-pacheco** [comment]
This is a generic issue, not related with AdminLTE.

You will have better luck if you ask this on stackoverflow, or search for an existing solution on google.

Best regards.

**Comment by YasserHassan** [comment]
Check #297 and #299.

**Comment by cyberzilla** [comment]
Jazakumullah brother
