### ISSUE TITLE
We're looking to hire someone expert with Admin LTE to help us improve our implemenation

### ISSUE THREAD

**Issue by APbrian** [almasaeed2010/AdminLTE#810]
We are using Admin LTE and are very impressed with it, however we are a team of coders and would like someone expert with Admin LTE to help us improve our implementation of it and our user experience. Abdullah, I would like to use you or your team, but I have been unable to reach you via multiple emails. Please lmk if you are available, otherwise others are welcome to reply or message.

Basically, review our version and provide a version that makes better use of the sections and functions included in the template as well as the bootstrap features. We will implement the code, we just need your eye and suggestions. Once you see, our version, it will be clear what we mean.

I can provide more details as needed.

Thanks!
Brian

**Comment by kikuyu1** [comment]
hey Brian, I have worked with Admin Lte for two years now, It is really a good Admin template. Please Email me if you need help with Admin LTE

**Comment by almasaeed2010** [comment]
Hello @APbrian,

We apologize for not responding to your emails. We just realized that our server is sending most emails to the junk mail. This issue has been fixed this morning.

I'd be happy to assist you with your implementation. It's currently exams period and time is limited. However, if you are flexible with deadlines, I could try to help.

Please email me again at abdullah@almsaeedstudio.com tif you'd like to discuss this further.

Thanks!
