### ISSUE TITLE
Style enchantment on file inputs

### ISSUE THREAD

**Issue by afbora** [almasaeed2010/AdminLTE#811]
I think, file inputs style should be enchant like that:

![Sample 1](http://veselov.sumy.ua/uploads/posts/2015-06/1433584772_untitled-1.png)

![Sample 2](http://www.abeautifulsite.net/wp-content/uploads/2014/08/bootstrap-file-input-example.png)

**Comment by almasaeed2010** [comment]
Hello,

Currently we are not adding new features to V2 since we are working on V3. We will consider this for the next release. 

Thanks!

**Comment by enumag** [comment]
@afbora Styling file inputs is not easy. I'm not sure if its even possible to achieve everything from your image. Or do you know of some way?

**Comment by ikhsan017** [comment]
In my experience, I use input[type=text] to act as a proxy to the real input[type=file]

- on input[type=text].click, trigger input[type=file].click
- on input['type=file].change, set value of input[type=text]

html part
```html
<div class="form-group">
    <label for="file_path" class="col-md-4">File:</label>
    <div class="col-md-8">
        <div class="input-group">
            <input type="text" id="file_path" class="form-control" placeholder="Browse...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" id="file_browser">
                <i class="fa fa-search"></i> Browse</button>
            </span>
        </div>
        <input type="file" class="hidden" id="file" name="file">
    </div>
</div>
```

javascript part

```javascript
$('#file_browser').click(function(e){
    e.preventDefault();
    $('#file').click();
});

$('#file').change(function(){
    $('#file_path').val($(this).val());
});

$('#file_path').click(function(){
    $('#file_browser').click();
});
```

**Comment by samayo** [comment]
This should be opened imho. In response to the request, @almasaeed2010 replied that he is working on V3. But that response was from over two years ago, and AdminLTE is still on v2.4 ..  Meaning, it could take more years to add this simple and important feature.
