### ISSUE TITLE
ASP.NET MVC Integration

### ISSUE THREAD

**Issue by volkanceylan** [almasaeed2010/AdminLTE#814]
Hello, thank you for this awesome template, and your hard work.

I have just implemented AdminLTE theme in my free ASP.NET MVC business application platform, Serenity. It made default template look much more professional, and prettier.

I couldn't find any other .NET implementations in docs, so wanted to let you know, for those who might look for .NET integration, 

### Github Repository
https://github.com/volkanceylan/Serenity

### Visual Studio Project Template (Serene)
https://visualstudiogallery.msdn.microsoft.com/559ec6fc-feef-4077-b6d5-5a99408a6681

Thanks again!

**Comment by almasaeed2010** [comment]
Thanks for sharing!
