### ISSUE TITLE
Blank Space for Sidebar in Print in Updated Chrome (Version 47)

### ISSUE THREAD

**Issue by gdespaux** [almasaeed2010/AdminLTE#826]
Since Chrome 47 Stable released (Dec 1 2015) the sidebar now impacts the layout for print. The sidebar is not shown but does push all content over as if it were still there. If you collapse the sidebar prior to printing, the issue is reduced but it appears the mini-sidebar still has a slight layout impact. I'm not sure what Chrome could have changed to cause this, but is this an issue we should work on or could they have introduced a CSS issue with this release? Thanks!

EDIT: It would *seem* that Chrome is not applying the `margin-left: 0!important;` CSS style on print

EDIT2: Chrome is indeed ignoring that line, temporary fix is to use JS and customPrint function:

    function customPrint() {
                var rightSide = document.getElementById("noMargin");
                var oldMargin = rightSide.style.marginLeft;
                rightSide.style.marginLeft = "0";
                window.print();
                rightSide.style.marginLeft = oldMargin;
            }

**Comment by almasaeed2010** [comment]
Hello,

We have been having this problem with chrome since I released AdminLTE 2.0. The CSS works fine on all browsers except chrome for some reason.

In your JS solution, it seems that you added an ID noMargin to the content-wrapper. Is that correct?

Thanks!

**Comment by gdespaux** [comment]
Hello! 

I added the ID to the div with the `right-side` class. This also happens using the provided example Invoice page, I am unsure as to whether it happens on any other pages (For us, it does not!)

Thank you!

**Comment by arjundas** [comment]
I am also having this issue since I updated to Chrome 47, @gdespaux's solution is working nice for a print button, but what about `Ctrl + p`, any idea?

**Comment by gdespaux** [comment]
@arjundas yes, this is implemented using a Print button on the page. With your comment, I've taken the code from [here](http://stackoverflow.com/a/11001012/4912716), modified it, and added the `customPrint()` function to it. Seems to work well! Let me know if this helps

-Glen D

**Comment by arjundas** [comment]
@gdespaux Thanks, this is works perfectly for both button as well as `Ctrl + p`. Thanks again :).

**Comment by imuller** [comment]
I've got a css-only solution.

app.less
`// Print chrome fix
.content-wrapper {
    margin-left: 0;
    padding-left: 230px;

    -webkit-transition: all 0.2s ease-in-out;
    -moz-transition: all 0.2s ease-in-out;
    -o-transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out;
}

body.sidebar-collapse {

    .content-wrapper {
        padding-left: 0;
    }
}

@media (max-width: 767px) {
    .wrapper {
        .content-wrapper {
            margin-left: -230px;
        }
    }
}`

print.less
`// Print chrome fix
.wrapper {
    .content-wrapper {
        padding-left: 0;

        .content {
            padding: 0;
        }
    }
}`

**Comment by arkgnan** [comment]
hi, have issue about sidebar collapse, wher i use sidebar-collapse class in body tag printing result of content-wrapper has a space (like in second pict) but it normal when i remove the class
![normal](https://cloud.githubusercontent.com/assets/17277219/13833510/1e4804f8-ec19-11e5-8c7e-8ac5dcfde089.png)
![bug](https://cloud.githubusercontent.com/assets/17277219/13833511/1e4fbb76-ec19-11e5-85e5-bdeb6ebfa766.png)

**Comment by gdespaux** [comment]
@arkgnan I have noticed this today also as we began using the collapsed sidebar. I will look into it tomorrow and post a fix as it is now a problem for us as well

**Comment by arkgnan** [comment]
ah for your information, this issue was happened in chrome, but i got same issue in firefox (above picture is result of firefox print). i use firefox 37. thanks

**Comment by gdespaux** [comment]
@arkgnan I have a temporary solution (again) changing the main AdminLTE.css file as below

     /*
     * Component: Sidebar Mini
     */
    @media (min-width: 768px) {
      .sidebar-mini.sidebar-collapse .content-wrapper,
      .sidebar-mini.sidebar-collapse .right-side,
      .sidebar-mini.sidebar-collapse .main-footer {
        margin-left: 50px; /* was marked as !important */
        z-index: 840;
      }

This is just a snippet of the Sidebar Mini CSS style for reference, please don't copy/paste it as it won't work. Remove/comment out the `!important` on the `margin-left` line and it works correctly again. I don't know of any adverse effects on the rest of the site, however if you notice any please let me know. Currently, it works for us.

-Glen D

**Comment by arkgnan** [comment]
ok it strange, it should be nothing wrong but it works for mee too. Thank you for the help
