### ISSUE TITLE
How can i get direct message widget into a popup

### ISSUE THREAD

**Issue by cmsni** [almasaeed2010/AdminLTE#828]
Is it possible to have direct message widget in a popup is their sample code also when I view the modals page like the demo their just flat dont look like popups at all even in demo.

Basically i want to have the main chat list you have on pic with mini and name and then they click that person name goto a direct message window. If was a small example on how to do this would be great.

Also in the bootstrap editor I need to add extra tool to add text to their editor is thier example of how to do this wihin a theme.

**Comment by almasaeed2010** [comment]
Hello,

This feature is not available in AdminLTE by default. We apologize for the inconvenience!

I am not sure what you mean by Bootstrap editor. Could you clarify?

Thanks!

**Comment by cmsni** [comment]
I need to place an icon in the WYSIWYG editor to allow them to select smart tags ie they will slected say player_number and it insert {player_number} into the text icon. Also is their any code you could share to allow the direct message in a popup
