### ISSUE TITLE
Any plan on keeping nuget package updated with latest version ?

### ISSUE THREAD

**Issue by OldTrain** [almasaeed2010/AdminLTE#832]
I was trying to install adminlte through nuget package but its outdated its 2.0.1 version, can't have the latest version through nuget package instead on direct download.

Appreciated

**Comment by almasaeed2010** [comment]
Hello,

We actually didn't create the NuGet package. Someone else decided to do that. However, we are considering supporting NuGet, NPM and Bower.

Thanks!
