### ISSUE TITLE
How to Extend app.js functionality

### ISSUE THREAD

**Issue by kavyashrees** [almasaeed2010/AdminLTE#834]
Hello,

I need to change the logic for remove widget fuction as per my requirement. i cant change it in app.js file. So how do i write my custom code to override this function.

**Comment by rafael-renan-pacheco** [comment]
Have you tried extending jquery?

I created this in my project:

```js
$(function () {
    $.fn.loading = function() {
        this.append("<div class='overlay'><i class='fa fa-refresh fa-spin'></i></div>");
    };
});
```

Then I call this loading extended function to activate the loading state in AdminLTE boxes, like:

```
$(".box").loading();
```
