### ISSUE TITLE
Keep sidebar minified across page

### ISSUE THREAD

**Issue by ikhsan017** [almasaeed2010/AdminLTE#836]
Hi @almasaeed2010 

Is there any plan to keep sidebar minimized or maximized across page request? I know it can be implemented by placing some cookies to track the information about sidebar position, I also don't mind to create pull request if anyone interested.

regards,
Ikhsan

**Comment by YasserHassan** [comment]
Refer to  #315, #322, and #617.

**Comment by namar00** [comment]
maximized across page request? I know it can be  about sidebar position,

**Comment by ikhsan017** [comment]
@YasserHassan thanks for pointing that out, will close this one :)
