### ISSUE TITLE
v2.3.2: sidebarExpandOnHover option does not work. Sidebar always expand on hover.

### ISSUE THREAD

**Issue by cywen** [almasaeed2010/AdminLTE#837]
I load a `custom.js` file before `app.min.js` to custom AdminLTEOptions.
below is the script content:

```javascript
var AdminLTEOptions = {
    //General animation speed for JS animated elements such as box collapse/expand and
    //sidebar treeview slide up/down. This options accepts an integer as milliseconds,
    //'fast', 'normal', or 'slow'
    animationSpeed: 'fast',
    sidebarExpandOnHover: false
};
```

But it does not work anyway. Even in the v2.3.2 's release package (I didn't modify any code in the package).

Browser: Chrome, Firefox ... 

How can I fix it ?
Thanks very much.

**Comment by cywen** [comment]
I just tested it again , and it happens only in Fixed-layout.

**Comment by stefan505** [comment]
This is by design it seems, but can it be changed? I would like to use fixed layout and have the sidebar not expand on hover.
