### ISSUE TITLE
Sticky footer AngularJS

### ISSUE THREAD

**Issue by chrisvel** [almasaeed2010/AdminLTE#838]
I know this is going to have issues with JQuery/AngularJS, but has anyone else witnessed a footer problem in window? Actually sticky footer works fine If I touch the browser window to resize and move even 1px to any direction, or If I just refresh the page. It doesn't work when navigating in my SPA application's pages. Any help is appreciated.

**Comment by almasaeed2010** [comment]
Have you made sure that your HTML is correct and that you included all the required css and js?

CSS to check:
- Bootstrap
- AdminLTE

JS:
- jQuery
- Bootstrap
- AdminLTE's app.js
In that order.

**Comment by chrisvel** [comment]
I have set ng-view with the class wrapper but I should have moved this class one step before ng-view in order to wrap propery,,,,
