### ISSUE TITLE
Stuttering scrolling on mobile/touch - solution available

### ISSUE THREAD

**Issue by ChristianWeyer** [almasaeed2010/AdminLTE#839]
Hey there,

is there any particular reason we could not add this to the wrapper?
.wrapper {
	overflow-y: scroll;
	-webkit-overflow-scrolling: touch;
}

With this scrolling (especially longer lists) is very smooth (and momentum-like) on mobile touch devices.

Thanks.

**Comment by almasaeed2010** [comment]
Hello,

This does not work on iOS 9.3 Safari. It completely freezes content. Please see https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

Thanks!

**Comment by ChristianWeyer** [comment]
Interesting. I just tried it on my iPhone 6 Plus with iOS 9.2 - within a Cordova app.
And it worked flawlessly.

Do you already have an early build of iOS 9.3?
