### ISSUE TITLE
/css/datepicker/datepicker3.css

### ISSUE THREAD

**Issue by diegobetto** [almasaeed2010/AdminLTE#84]
Hi, 
check  /css/datepicker/datepicker3.css inclusion in head. File is not found

**Comment by asawintun** [comment]
http://almsaeedstudio.com/AdminLTE/css/datepicker/datepicker3.css
http://almsaeedstudio.com/AdminLTE/js/plugins/datepicker/bootstrap-datepicker.js

those two link are die.. could you please re-upload again
