### ISSUE TITLE
Fixed sidebar without hover-to-expand feature

### ISSUE THREAD

**Issue by MaticConradi** [almasaeed2010/AdminLTE#840]
How can I get a fixed layout but without thet hover-to-expand feature? Is it possible? (I still want to keep this [look at the picture])
![screen shot 2015-12-10 at 12 41 52](https://cloud.githubusercontent.com/assets/5693961/11714569/68c45caa-9f3b-11e5-9f2e-8f7bb7ac22e0.png)

**Comment by almasaeed2010** [comment]
Please refer to #336
