### ISSUE TITLE
Bootstrap's Affix conflict with sidebar-collapse?

### ISSUE THREAD

**Issue by ChaIcuWo** [almasaeed2010/AdminLTE#841]
I am trying to use Bootstrap's [Affix plugin] (http://getbootstrap.com/javascript/#affix) to make my sidebar-menu visible regardless of page-length/scrolling. It behaves as expected when the sidebar is expanded, but when the sidebar is collapsed the affix plugin seems to have no effect (with no errors in Console).

I am using sidebar-mini layout. My app.js is v2.3.0, Bootstrap v3.3.4, jQuery 2.1.4.

My HTML is below. As you can see, I have added code mimicking .logo and .logo-mini/.logo-lg from the navbar. These are hidden on load, so only appear on the sidebar when the affix is triggered (i.e. when `sidebar.affix:not(affix-top)`).

```
<aside class="main-sidebar">
    <section class="sidebar" data-spy="affix" data-offset-top="40"> 
        <a href="#" class="logo">
	    <span class="logo-mini" style="display:none">
	        <img src="images/name-logo-50.png"  alt="logo">
            </span>
            <span class="logo-lg" style="display:none">
		<img src="images/name-logo2.png" alt="logo" border="0" align="left" />
	    </span>
        </a>
        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat">
                    <i class="fa fa-search"></i>
                    </button>
                </span> 
            </div>
        </form>
        <!-- /.search form --> 
    
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="treeview active""> 
                <a href="dashboard/"><i class="fa fa-tachometer fa-lg"></i>
                <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i> </a>
                <ul class="treeview-menu">
                    <li> <a href="dashboard/metrics"><span>Performance</span></a> </li>
                    <li> <a href="dashboard/activity"><span>Activity</span></a> </li>
                </ul>
            </li>
            . . . 
        </ul>
    </section>
</aside>
```
In trying to troubleshoot I have reduced my CSS down to the following:
```
.sidebar.affix {
    width: 230px;
    top: 0px;
}
```
I'm triggering this with data-* attributes, so I do not have any additional js triggering the affix behavior.

The above works fine for expanded, but has no effect when .sidebar-collapse is present. (This is true regardless of whether or not the page is loaded with the sidebar-collapsed or not).

I have tried using css selectors specifically related to `sidebar-mini.sidebar-collapse` with no luck. I am pretty well convinced that this is not a css issue and that it has to be some kind of conflict with App.js and Bootstrap's Affix.js. (I have no other local js running and, again, no console errors/warnings). But I'm at a loss as to where this might be coming from in App.js… the ``PushMenu()`` code (line 304) seems the logical place, but I'm just not seeing anything that would should cause a problem.

Has anyone else seen or dealt with this before? I searched but could not find any similar issues either here or on the bootstrap git. Is this a conflict or have I just missed something? And if it's a me-problem, any ideas on what I might do to fix it?

**Comment by almasaeed2010** [comment]
Hello,

Did you try to add the class ```fixed``` to the body? The fixed layout demo can be found here.
https://almsaeedstudio.com/themes/AdminLTE/pages/layout/fixed.html

Thanks!

**Comment by ChaIcuWo** [comment]
Well I feel like an idiot. Yeah, that worked. When I had previously used `fixed` it had created some alignment problems so I'd given up on that, but that was because of a lack of `content-wrapper` div. Anyways, thanks so much for your suggestion here, and for this AMAZING template.
