### ISSUE TITLE
[Suggestion]: Fixed header on mobile devices

### ISSUE THREAD

**Issue by iaesaudi** [almasaeed2010/AdminLTE#842]
Mobile devices screen is not that big to contain a lot of unnecessary data all the time you are surfing the website, like the website title.

in mobile view we have the fixed header as 2 x 50px containers.
What if we only made the 2nd container fixed and be sticky at top when scrolling down and leave the website title container at the top without fixing at the top of the screen.

I will try to provide some image to describe what I wrote here.

**Comment by almasaeed2010** [comment]
Hello,

I like the suggestion. We are implementing something similar for AdminLTE v3 wihtout compromising the title. Since we are currently not adding new features for V2. Will consider this for V3.

Thanks!

**Comment by iaesaudi** [comment]
Yeah, I was talking about the upcoming v3,
Could we do anything to help you in it ?
