### ISSUE TITLE
what is the use of bootstrap.js file ?

### ISSUE THREAD

**Issue by DinnuBuddy** [almasaeed2010/AdminLTE#844]
Hello all,

Can anyone tell the use of  "bootstrap.js" file in AdminLTE, Only one place I can see it in app.js, using it for tooltip. So is it possible that even if I don't have "bootstrap.js" file, it is damn sure that each and every functionality will work, Except tooltip.

--please do help.

Many thanks
Dinker

**Comment by almasaeed2010** [comment]
Bootstrap is used for dorpdown menus, tabs, tooltips, and other [plugins](http://getbootstrap.com/javascript/).

Thanks!

**Comment by DinnuBuddy** [comment]
yes, I agree with you.
satisfied :) 

Many Thanks,
Dinker
