### ISSUE TITLE
IE and font Helvetica Neue

### ISSUE THREAD

**Issue by gazouweb** [almasaeed2010/AdminLTE#845]
Hello,
Just to prevent the font "Helvetica Neue" IE browser crashes, whether in bootstrap.css or AdminLTE.css since I removed it no problem.
Perhaps it would be wise to remove it?
Best regards

**Comment by almasaeed2010** [comment]
Hi,

IE supports the font if you download it to the system. However, there is an automatic fall back to other appropriate fonts when a certain font is not available. Removing the font won't do any good.

Thanks!

**Comment by gazouweb** [comment]
Hi,
I agree with you, it works well with Chrome or Firefox, but in IE, the website is broke.
