### ISSUE TITLE
Menu cache item open

### ISSUE THREAD

**Issue by mtsys** [almasaeed2010/AdminLTE#846]
I saw in another Issues that the option of leaving open the menu after page refresh would not be made by AdminLTE component, but every programmer should implement your solution.

Then I ask, someone would have an example as records open menu item?

**Comment by gugahoi** [comment]
I did it using cookies

**Comment by kressly** [comment]
I think depending on the way u see and want to achieve it, u can either use cookies or even update ur visitor (who I guess is logged into ur system)'  menu with an update on ur database in such a way that the last state of the menu is updated in ur database when the visitor clicks on an event.

**Comment by rafael-renan-pacheco** [comment]
Examples here: #738

As said there, this is not related to AdminLTE. You have plenty options to achieve this using your favorite programming language. You can even search google for a general solution, and try to implement that on your AdminLTE + Framework.

In my Laravel project, each menu has a route. If the openned url is the same route as the menu item, I set its class with "active".

**Comment by ikhsan017** [comment]
On my project, I am using twig and create some cookie macro, the solution looks like this

```html
<body class="skin-purple hold-transition sidebar-mini {% if cookie('sidebar-collapse') == '1' %}sidebar-collapse{% endif %}">
```
