### ISSUE TITLE
`.content-wrapper` min-height and height properties and children's dynamic height

### ISSUE THREAD

**Issue by gugahoi** [almasaeed2010/AdminLTE#847]
I have noticed that the `min-height` property for the `.content-wrapper` div is set on load/window resize however the `height` property is not. This means I cannot dynamically reference height with it's children. Is there somehow another way I can actually set the `section.content` height dynamically?

**Comment by almasaeed2010** [comment]
You can get the current height of ```.content-wrapper``` using ```$('.content-wrapper').height();```.
