### ISSUE TITLE
Data Table is not responsive when i choose mobile device.

### ISSUE THREAD

**Issue by akbajwaakgec** [almasaeed2010/AdminLTE#848]
![issue](https://cloud.githubusercontent.com/assets/16353456/11902389/65853e68-a5d7-11e5-8b40-ada1c7f9b3bd.png)

**Comment by rafael-renan-pacheco** [comment]
You missed the "Responsive Hover Table" option.

Open: https://almsaeedstudio.com/themes/AdminLTE/pages/tables/simple.html

And as mobile device, look for "Responsive Hover Table".

This can be achieved with the following box-body helper: `<div class="box-body table-responsive no-padding">`

**Comment by akbajwaakgec** [comment]
Thanks

**Comment by djcasty** [comment]
i have this problem my table in admin lte is not responsive... help me
