### ISSUE TITLE
Using ajax to get predefined content in textarea: doesn't work

### ISSUE THREAD

**Issue by RaymondTebru** [almasaeed2010/AdminLTE#851]
Hi,

I'm trying to get predefined text into the textarea which can be selected through a dropdownmenu. I'm using this ajax script in the headsection: 

function showUser(str) {
    if (str == "") {
        document.getElementById("message").innerHTML = "";
        return;
    } else {
        if (window.XMLHttpRequest) {
            // code for IE7+, Firefox, Chrome, Opera, Safari
            xmlhttp = new XMLHttpRequest();
        } else {
            // code for IE6, IE5
            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                document.getElementById("message").innerHTML = xmlhttp.responseText;
            }
        };
        xmlhttp.open("GET","bpcontent.php?q="+str,true);
        xmlhttp.send();
    }
}

The dropdownmenu has onchange="showUser(this.value)" in it's tag, and the textarea has the id message. 

It works when i use a normal textarea, but when i define the class textarea into the textarea (to make it a bootstrap wysiwyg editor), it doesn't work anymore. Can anyone help me to get this working in the WYSIWYG editor?

Thanks.

**Comment by YasserHassan** [comment]
Is this a native feature of AdminLTE? Seems to me like a stackoverflow.com question.
