### ISSUE TITLE
Sorting, pagination not warking.

### ISSUE THREAD

**Issue by nnn85** [almasaeed2010/AdminLTE#853]
Hi there, 

I'm using AdminLTE for my project. Now I able to display my data into table but the sorting and pagination is not work. How should I do.

This is sample jquery on how i get the data:

    var $j = jQuery.noConflict();

    $j(document).ready(function(){
    $.ajax({
    type: 'POST',
    url:"scr1.php",    
    }).done(function(data){
    for(var i=0; i<data.length; i++){
        console.log(data[i]);

        var no = i+1;
        var oddEven="";
        if(no%2===0){
            oddEven="even";
        }
        else{
            oddEven="odd";
        }
        $table ="<tr class="+oddEven+" role='row'>";
        $table += "<td class='sorting_1'>"+no+ "</td>";
        $table += "<td>"+data[i].uid+ "</td>";
        $table += "<td>"+data[i].document_id+ "</td>";
        $table += "<td>"+data[i].activity+ "</td>";
         $table += "<td>"+data[i].date_time+ "</td>";
        $table +="</tr>";        
        $("#example1").append($table);
        }
    });});

This is for pagination

     <script>
      $(function () {
        $('#example1').DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>

What should I change. Sorry really don't know.....

**Comment by kressly** [comment]
Consider asking that on Stackoverflow
