### ISSUE TITLE
Can it be made Bower and RequireJS compatible?

### ISSUE THREAD

**Issue by DieterLi** [almasaeed2010/AdminLTE#859]
Currently, we can install this by Bower, but the Bower package contains everything need in it. It's great to one-click demonstration, but it also cause RequireJS optimisation failure, just because it contains everything as well, not by a package dependency structure.

Now we have to copy the required css and js manually to the development project.

If it can follow the dependency structure, it would be much better for automatic project dependency management and to CI.

**Comment by xrogers** [comment]
Hey @DieterLi, check out my pull request.
Hope you'll be satisfied :)
https://github.com/almasaeed2010/AdminLTE/pull/857
