### ISSUE TITLE
Width of modal

### ISSUE THREAD

**Issue by cmsni** [almasaeed2010/AdminLTE#860]
When I try to change the width of my modal in the style sheet of any page it doesnt work

        #myRegisterTorunament .modal-dialog
{
  width: 70%;
}
I am wanting to make the modal-dialog wider like the create torunament button does on battlefly http://battlefy.com/  Please tell me how I can change the width so that it is carried across I am using blank.html as a basis for my .net master pages.

**Comment by cmsni** [comment]
Another issue I am having is with the time picker I am trying to use it on a .net button but its not loading some reason 
   <script type="text/javascript">
        $(function () {
            $("#txtTime").timepicker({
                showInputs: true
            });
        })
</script>

       <div class="input-group bootstrap-timepicker timepicker">
    <asp:TextBox ID="txtTime" data-provide="timepicker" CssClass="form-control timepicker" runat="server"></asp:TextBox>
    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
</div>

I have made sure my references are in place for the time picker js and css and still nothing could you take a look to see what issue may be?

**Comment by ikhsan017** [comment]
for the modal width, maybe you can try to add ```modal-sm```, ```modal-md```, or ```modal-lg``` class in the modal-dialog div
