### ISSUE TITLE
Data Tables length in not responsive

### ISSUE THREAD

**Issue by hendisantika** [almasaeed2010/AdminLTE#862]
Hi, AdminLTE is the greatest template I ever used and I know.

But, I have an issue in Data Table.

When I view many columns in Data Tables, the table length is not well show.
It is out of the Table / form limit.

![gini](https://cloud.githubusercontent.com/assets/3713580/12131079/13865c0e-b442-11e5-97f8-84f1060e2547.png)

I've tried to add responsive css and JS to the page. But It does not make anything.
In fact the side bar can not be hitted.

How do I solve this?

Thanks.

**Comment by almasaeed2010** [comment]
Please review the following plugin: https://datatables.net/extensions/responsive/
