### ISSUE TITLE
CSS Styling 

### ISSUE THREAD

**Issue by basenetpaolo** [almasaeed2010/AdminLTE#863]
Hey,

I've used LTE for a long time and I've never had this problem before.
Simply, there is something wrong with the CSS all over the site.

If you see the attached screenshots, you'll notice the font is larger than what is normally styled for tables, the icons are not fitting in the box nicely, and the spacing in the tables is wrong.

I'm using laravel and I've broken it down into blade files but as far as I can see it's all as it should be.
The CSS styles are being applied from viewing the source but they're nor accurate. 

Any ideas at all?

![screenshot at jan 06 11-47-22](https://cloud.githubusercontent.com/assets/16153895/12141873/5ef2d31a-b46b-11e5-8624-94d4f1ea21e5.png)
![screenshot at jan 06 11-47-40](https://cloud.githubusercontent.com/assets/16153895/12141874/5ef37126-b46b-11e5-8eab-c2bf3cc30435.png)

Thanks in advance!
Paolo

**Comment by YasserHassan** [comment]
Is the original unmodified source rendered correctly after downloading before using converting it to Blade templates?

**Comment by basenetpaolo** [comment]
Hey, It's not. I have moved it line by line 3 times over to be sure I'm do it correctly, but it's still giving me the same problem.

**Comment by adaniello** [comment]
You should share html code to inspect on it: can css inspector help you?

**Comment by basenetpaolo** [comment]
I've just spotted the most obvious mistake, <!DOCTYPE html> somehow got deleted!
Thanks everyone.
