### ISSUE TITLE
[HELP] Installing out of preview mode.

### ISSUE THREAD

**Issue by SnowyWolfy** [almasaeed2010/AdminLTE#864]
Hello,
My name is Wolfy. Please excuse any formatting / grammar knowledge issues please.

For the past six hours I have been trying with my CEO to install many of these bootstrapper themes/templates. Using composer / bower / etc.

I manage to get the hole thing installed but for some reason I cannot get this out of preview mode. Is there any way that someone can show me how to get it out? 

Please excuse anything I'm missing.
I have installed
Apache web server.
MySQL.
AdminLTE
Bootstrapper.

We have tried on a Linux web server & a Windows web server.
Any Ideas.?

Thank you, ~Wolfy

**Comment by vjandrea** [comment]
Wolfy, the package comes as a demo, as you can see from the source code, i.e. https://github.com/almasaeed2010/AdminLTE/blob/master/pages/calendar.html
It's up to you to code the components you want to render.

**Comment by SnowyWolfy** [comment]
Okay thank you very much, Didn't really see that clearly enough thank you. <3
