### ISSUE TITLE
Color picker doesn't work on Safari Mobile

### ISSUE THREAD

**Issue by nuthinking** [almasaeed2010/AdminLTE#867]
The "advanced form elements" section in the preview app doesn't work properly on my iPhone, in particular the color picker. Bootstrap Colorpicker 2.3, which seems the same used, works fine on their website.

Is it something broken in the demo app?

**Comment by almasaeed2010** [comment]
Hi,

This is working on my iphone. Which browser are you using?
 
![img_5614](https://cloud.githubusercontent.com/assets/1512664/12373212/e0a69370-bc3f-11e5-9927-1a00bed3b00c.PNG)

**Comment by nuthinking** [comment]
The popover comes out but can you change the color? On my iphone (6s with latest iOS) is not really usable neither in Safari nor Chrome.
