### ISSUE TITLE
Bootstrap WYSIHTML5 - Create Link Modal

### ISSUE THREAD

**Issue by ilgityildirim** [almasaeed2010/AdminLTE#868]
Once you add a link and click on it to edit the link (or click on "link" button in toolbar), it behaves very strangely.

If you press **ESC** or **Close** link it closes modal and re-opens it again and again. It also adds modal background overlay every single time.

Only **x** on the top right side of the modal works as expected.

Also, if you some manage to close the modal, next time you try to edit it, it doesn't display the link and the text in editor looks like as if it is not a link. However when you try to add a link, it shows a blank input within create link modal.

You can test it here; https://almsaeedstudio.com/themes/AdminLTE/pages/forms/editors.html

**Comment by almasaeed2010** [comment]
Hello @ilgityildirim,

I tested the plugin and it worked as expected. I couldn't find your issue. However, if the issue persists, you may want to contact the [creators of WYSIHTML5](https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg/issues)
