### ISSUE TITLE
editor not outputting formatting.

### ISSUE THREAD

**Issue by Wazez** [almasaeed2010/AdminLTE#870]
We use a editor for our documentation called CKEditor and I've set it up. However when we submit the changes, it doesn't output the formatting (such as bold, underlines, colors, etc)

We previously had wysibb instead of CKeditor (wysibb is a bbcode editor). But that also did not work.

Here is an example, see the world Puush is meant to be bold, but it outputs: http://puu.sh/mu7sV/eb473c0b74.png 
In the CKEditor it displays as so: http://puu.sh/mu7u3/51a95ae032.png. This is also saved and when I refresh or visit the editor page later, it is still formated as I want it. It's just the output.

Thanks

**Comment by vjandrea** [comment]
Please check if you're using {{ $string }} or {!!  $string !!}  to output the field on the page: the first escapes all html code so maybe that's why you see the tags in plain text.

**Comment by almasaeed2010** [comment]
Hello,

This question should be asked on the CKEditor repo. They will be able to help you better. http://ckeditor.com/support

Thanks!
