### ISSUE TITLE
Newbie question creating sidebar links

### ISSUE THREAD

**Issue by dk4210** [almasaeed2010/AdminLTE#871]
Hello,
I'm trying to figure out how to create links in the sidebar then once the link is clicked on it should load the content in the center. Please advise.

Thanks,
Dan

**Comment by vjandrea** [comment]
@dk4210 this is just a template, how did you code the content loading? Are you using a framework?
Please post an example on gist so we can get a look.

**Comment by almasaeed2010** [comment]
Hi,

This is a very broad question and difficult to answer. There are multiple ways to do this and it all depends on your preference. To get you started, you may want to check out [AJAX](http://www.w3schools.com/ajax/).

Thanks!

**Comment by dk4210** [comment]
Actually I'm using Ajax. Thanks
