### ISSUE TITLE
Why not a sass version

### ISSUE THREAD

**Issue by gaea44** [almasaeed2010/AdminLTE#872]
Hello,

thanks for your awesome theme.

Knowing next major version of bootstrap will be sass only (at least on the alpha : http://v4-alpha.getbootstrap.com/), why not a sass/scss version ?

I know there is a fork (https://github.com/aguegu/AdminLTE) but its not up to date.

**Comment by enumag** [comment]
Next version od AdminLTE will probably use both Bootstrap 4 and SCSS.

**Comment by almasaeed2010** [comment]
@enumag is right.

**Comment by DeeJaVu** [comment]
some users need sass with bootstrap 3 not 4
