### ISSUE TITLE
toggle control-sidebar with jquery

### ISSUE THREAD

**Issue by 22ivan22** [almasaeed2010/AdminLTE#873]
Hi,

how can I toggle control sidebar with jquery without clicking on something. I want after success close the control sidebar

**Comment by YasserHassan** [comment]
To collapse the control sidebar, remove the CSS class `control-sidebar-open` from its `<aside>` container.

**Comment by SebaSOFT** [comment]
`$($.AdminLTE.options.sidebarToggleSelector).click();`

**Comment by ArunEdathadan** [comment]
$("body").addClass("sidebar-collapse").trigger("collapsed.pushMenu");
        $(".content,.content-header>h1,.main-header>.navbar").addClass("margin-50");
        $(".sidebar-menu>li .label,.fa-angle-left").hide();
