### ISSUE TITLE
Remove the hover effect from the Toggle Navigation button

### ISSUE THREAD

**Issue by mauro269** [almasaeed2010/AdminLTE#874]
Hi, how can I remove the hover effect from the Toggle Navigation button? I'm not able to find the code to modify in the bootstrap.min.css.
Thanks

**Comment by YasserHassan** [comment]
What do you mean by "Toggle Navigation button"?

**Comment by mauro269** [comment]
The 3 horizontal lines.

![schermata 2016-01-16 alle 11 47 47](https://cloud.githubusercontent.com/assets/8449241/12371990/0f56602c-bc47-11e5-9fa4-fd433ff8eaf1.png)

**Comment by YasserHassan** [comment]
It's the line `background: @hover-bg;` in the file `mixins.less` as shown below:
```
//Add color to the sidebar toggle button
.sidebar-toggle {
  color: @font-color;
  &:hover {
    color: @hover-color;
    background: @hover-bg;
  }
}
```
You should not modify the original Bootstrap or AdminLTE files. Instead, override what you want to modify with your own CSS files. A good practice is is to create your own LESS file(s) and then compile it (and optionally compact it) to generate your CSS file. There are a lot of tutorials and examples on the web for that.

**Comment by mauro269** [comment]
I've tried to modify the mixins.less that I've found inside the build/less/ path just for a test and nothing happened.

**Comment by YasserHassan** [comment]
It seems you haven't complied your LESS file to CSS. Whatever your approach, make sure that the final custom CSS file comes after the original one in the loading sequence in your HTML page (check the find source inside the browser). Also make sure your CSS is not cached in the browser.

**Comment by mauro269** [comment]
My custom.css is after the original. My trouble is that I've never worked with LESS files. I really don't know what's the correct approach. If it's not a disturb for you, could you please link me to a source that you trust from which I can study this methodology? Thanks again for your support, I really appreciate it.

**Comment by almasaeed2010** [comment]
@mauro269 you should consider reading about [LESS](http://lesscss.org/).

Thanks!

**Comment by mauro269** [comment]
@almasaeed2010 I'll do for sure. Thanks!
