### ISSUE TITLE
Why the AdminLTE.min.css and bootstrap.min.css are written on a single row?

### ISSUE THREAD

**Issue by mauro269** [almasaeed2010/AdminLTE#875]
Hello,
I don't understand if this is just my issue or if it's a common problem. I don't understand why these two important files are completely on a single row. It's really impossible to read theme and understand some structures... :(

**Comment by almasaeed2010** [comment]
Hello @mauro269,

This is a method of speeding up loading time of the page. The original non-minified resources are available (AdminLTE.css is the same as adminlte.min.css). 

Read https://developers.google.com/speed/docs/insights/MinifyResources?hl=en

Thanks!

**Comment by mauro269** [comment]
Hello @almasaeed2010, I didn't know this!
Thanks a lot for your reply and support.
