### ISSUE TITLE
How can I make sure every page has a full height content-wrapper?

### ISSUE THREAD

**Issue by Soulfire86** [almasaeed2010/AdminLTE#876]
Some pages start full height like they should, but others are short...showing background below the footer, but I think they become full height after resizing the browser. What could I be doing wrong?

![notfullheight](https://cloud.githubusercontent.com/assets/234468/12373424/19615f04-bc47-11e5-9710-746633854cb6.png)
![fullheight](https://cloud.githubusercontent.com/assets/234468/12373423/195ffb78-bc47-11e5-95aa-19a7a18a85e2.png)

**Comment by almasaeed2010** [comment]
In your first screenshot, it seems like there is an html error. Make sure all your tags are closed properly.

**Comment by Soulfire86** [comment]
I could not find an HTML error, but I think I figured it out. I didn't have proper <div class="row"> around things appropriately. Adding those in fixed it. Thanks!
