### ISSUE TITLE
Left Sidebar content is hidden by Header

### ISSUE THREAD

**Issue by leovipin1** [almasaeed2010/AdminLTE#878]
Hi,

Firstly I love your dashboard design. Its awesome.

I am building a web application using your template, the issue is that I got the header and nav bar fine with logo and everything, but when I start adding the left sidebar content it hides under the header nav bar and doesn't show on the screen. When I find the content of the sidebar using Ctrl+F then it shows that it is under navbar. I am adding only css and js files which are required for my app. Can you let me know which are the minimum required files to be included to get the dashboard working.

I have not made any changes to any css, js or plugin files.

When I directly open the downloaded index.html file it works fine that means I am missing something. 
Can you help me out here?

I have downloaded the latest version of AdminLTE from Github

P.S. I even tried the starter.html page but no luck.

Regards,
Vipin

**Comment by almasaeed2010** [comment]
Can you attach a screenshot and your code please?

**Comment by leovipin1** [comment]
The issue has been resolved. it was my mistake that I implementing the content div. Thanks.
