### ISSUE TITLE
Miss two things from the best admin theme

### ISSUE THREAD

**Issue by onigetoc** [almasaeed2010/AdminLTE#879]
Miss two things from the best admin theme.

1 - Option or exemple with fixed top navbar.
2 - Option to make the sidebar affix.
3 - the two together

**Comment by ikhsan017** [comment]
you can add ```fixed``` class to the body if you want a fixed top navbar

**Comment by almasaeed2010** [comment]
The fixed layout combines both those options. Unfortunately, it isn't possible to do one of them only. 

Thanks!

**Comment by onigetoc** [comment]
i did try but these but need some twiks to do to work well. and it should work with a affix left menu too.
