### ISSUE TITLE
Changing Control Sidebar Width

### ISSUE THREAD

**Issue by yusto** [almasaeed2010/AdminLTE#882]
I'm having trouble changing the width of the control sidebar.
I found the control-sidebar-width variable in build/less/variables.less and changed it, but it has no effect on the width of the control bar itself. Please help!!

**Comment by YasserHassan** [comment]
Are you sure you compiled the LESS file to CSS? Also it is recommended not to modify the original source files, you'll lose your settings when you update to a newer AdminLTE version. Add your own LESS/CSS files and override the original settings instead.

**Comment by almasaeed2010** [comment]
As @YasserHassan said, please verify that you have compiled the LESS file.

The command you need: ([LESS documentation](http://lesscss.org))
```bash
lessc build/less/AdminLTE.less > dist/css/AdminLTE_custom.css
```

Make sure you include the custom css in your html files.

Thanks!
