### ISSUE TITLE
main-header broken in v3

### ISSUE THREAD

**Issue by DerPapst** [almasaeed2010/AdminLTE#885]
Hey :-) First of all thanks for this awesome template!

I've checked out your v3 branch. Right now it seems that the main-header is pretty much broken in v3 mostly because of the changes in c6667c6bcaf4343f5f503454ec9848e0a5657943 to _header.scss.
Also some of the theme files contain commented out code that remove the colour from the main-header.

![adminlte_screenshot](https://cloud.githubusercontent.com/assets/2511615/12458304/77bf7044-bfa9-11e5-8231-f3d44077b6f3.png)

Oh and the demo html files still use a pre-compiled version of bootstrap v3 and AdminLTE 2 ;-)

**Comment by almasaeed2010** [comment]
Hello @DerPapst 

AdminLTE 3 is underdevelopment. In no means should use it until an official release comes out. We appreciate your interest in V3, but it will be long before it is ready for production.

Thanks!
