### ISSUE TITLE
Help needed | tutorials

### ISSUE THREAD

**Issue by sensioair** [almasaeed2010/AdminLTE#887]
Hello thanks for an awesome template, I'm a complete noob here and I was wondering what were good tutorials to follow in order to be able to edit and customize this template.

thank you!

**Comment by almasaeed2010** [comment]
Hello @sensioair 

Firstly, you are welcome! 

I realize that you'd like to start this exciting path as quickly as possible. However, it is gonna take time and effort to reach the ability to customize your templates and implement them within a system. To get you started, you need to learn the basic web technologies:
1. [HTML](http://www.w3schools.com/html/default.asp)
2. [CSS](http://www.w3schools.com/css/default.asp)
3. [JavaScript](http://www.w3schools.com/js/default.asp)

Once you understand the basics, you will easily be able to customize any html template or even create your own.

Thanks!

**Comment by sensioair** [comment]
Thank you for your quick reply, I have done quite a few tutorials with html/css/ JS but somehow i don't know how to put it all together to be able to edit this! any other pointers will help

thank you

**Comment by almasaeed2010** [comment]
This is one of the best tutorials I could find about putting all of these languages together and it is free:
https://www.codecademy.com/courses/html-javascript-css/0/1
