### ISSUE TITLE
can't working with angular

### ISSUE THREAD

**Issue by markstock7** [almasaeed2010/AdminLTE#890]
i put example code in <div ui-view></div>, then some button not working ,like treeview and 
control-sidebar, how to figure it out?

**Comment by YasserHassan** [comment]
Refer to #795 and the following projects:
https://github.com/ahmadalibaloch/Angular-AdminLTE
https://github.com/sarahhenderson/admin-lte-angular
https://github.com/eyolas/angular-adminlte

**Comment by hiepnm** [comment]
I have met the same problem with control-sidebar
