### ISSUE TITLE
Suggestion for AdminLTE 3.0

### ISSUE THREAD

**Issue by mauro269** [almasaeed2010/AdminLTE#895]
Hello,
I would like to suggest some modifies to implement in the AdminLTE 3.0:

- It could be great to have the top-navigation menu also in the others Layout Options. Currently, if I use the the top-navigation layout, it has an header that is different from that of the other layouts;

- The top-navigation layout is a good solution, especially to design homepages; the trouble is that, as I said in the previous sentence, top-navigation layout and the others layouts have different headers. A little request is to have an unique header.

Thanks

**Comment by judodan** [comment]
Another thing that would be nice for 3.0 would be an upload widget that could chunk uploading large files.
