### ISSUE TITLE
Remember Main sidebar collapsed state

### ISSUE THREAD

**Issue by etsandig** [almasaeed2010/AdminLTE#896]
When collapsing the main left sidebar on a given page, how can the collapse state be 'remembered' for the other pages when they are loaded?
Removing the collapse class in the `<body>` tag works, but shows first open then quickly closed, which is less than ideal.

**Comment by alexgalletti** [comment]
I've recently had to use AdminLTE for a project and came across this but could not find a solid front-end solution. The closest I got was disabling CSS animations temporarily and then applying the `.sidebar-collapse` class to the body. My solution is below. Note that this only works with localStorage!

```html
<!-- Custom styles to disable animation temporarily (inlined for show) -->
<style>
/* Probably doesn't need all these prefixes but oh well */
.disable-animations, .disable-animations * {
  /* CSS transitions */
  -o-transition-property: none !important;
  -moz-transition-property: none !important;
  -webkit-transition-property: none !important;
  transition-property: none !important;
  /* CSS transforms */
  -o-transform: none !important;
  -moz-transform: none !important;
  -webkit-transform: none !important;
  transform: none !important;
  /* CSS animations */
  -webkit-animation: none !important;
  -moz-animation: none !important;
  -o-animation: none !important;
  animation: none !important;
}
</style>

<!-- AdminLTE JavaScript -->
<script src="AdminLTE/dist/js/app.js"></script>

<!-- Custom scripts loaded AFTER AdminLTE JavaScript (inlined for show) -->
<script>
$(function ($) {
  var $body = $('body');
  // On click, capture state and save it in localStorage
  $($.AdminLTE.options.sidebarToggleSelector).click(function () {
    localStorage.setItem('sidebar', $body.hasClass('sidebar-collapse') ? 1 : 0);
  });

  // On ready, read the set state and collapse if needed
  if (localStorage.getItem('sidebar') === '0') {
    $body.addClass('disable-animations sidebar-collapse');
    requestAnimationFrame(function () {
      $body.removeClass('disable-animations');
    });
  }
});
</script>
```

**Comment by etsandig** [comment]
Interesting approach! I didn't think of going the CSS route. The following is a javascript based solution in case somebody may find it useful.

Basically I went to the original `<body class="hold-transition skin-blue sidebar-mini sidebar-collapse">
` tag from the template and added the 'sidebar-collapse' class, so the sidebar will always load collapsed by default.  Next I added the following script snippet to each web page, just before the `$(document).ready()` if there is one (but not inside of it).

This takes care of the jittery animation, since it now expands when necessary, providing for a reasonably natural feel.

```javascript
<script>
  if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
    $("body").removeClass('sidebar-collapse')
  }

  $('.sidebar-toggle').click(function() {
    event.preventDefault();
    if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
      sessionStorage.setItem("sidebar-toggle-collapsed", "");
    } else {
      sessionStorage.setItem("sidebar-toggle-collapsed", "1");
    }
  });

  $(document).ready(function() {
    // Document ready code here
  }
</script>
```

**Comment by lenamtl** [comment]
Hi, I have tried both solutions and both have the animation on page refresh that is not natural.

For example 

Using css solution when the sidebar = 0  and hit refresh F5 
we can see a very quick animation mini go to full then get back to mini


Using javascript solution when the sidebar-toggle-collapsed =1 and hit refresh F5 
we can see a smooth animation full go to mini then go back to full 

Is there a way not to see an animation on refresh?

Thanks

**Comment by KLuka** [comment]
Hi, and thanks for this. I used your idea with session storage and came up with this code that doesn't display animations. Trick is to handle `sidebar-collapse` very early, just after the body tag is loaded. This way there is no need to use CSS tricks...

```html
<body class="skin-black sidebar-mini">

  <script>
    (function () {
      if (Boolean(sessionStorage.getItem('sidebar-toggle-collapsed'))) {
        var body = document.getElementsByTagName('body')[0];
        body.className = body.className + ' sidebar-collapse';
      }
    })();
  </script>
  ...
```

**Comment by lenamtl** [comment]
@KLuka  I'm using your solution with Localstorage and this is working fine. Thanks

**Comment by ajcastro** [comment]
You can perform an ajax to the server and save a session of the sidebar state... then render it on the body tag via php

**Comment by REJack** [comment]
You can hide this ugly transition with add the class `hold-transition` and remove it after its done 😄 

@ajcastro not every one use php and sometimes its easier to use localstorage.

**Comment by ajcastro** [comment]
Thanks for the info! 
Yeah that solution is only for those who use php or server-side rendering.

**Comment by lenamtl** [comment]
@REJack  could you point us where to add and remove the `hold-transition`
Thanks

**Comment by REJack** [comment]
I've created already a fully working script look at [#1240 (comment)](https://github.com/almasaeed2010/AdminLTE/issues/1240#issuecomment-258836748)

regards REJack

**Comment by lenamtl** [comment]
Thanks I will try to adapt to @KLuka version because I do prefer to use LocalStorage
