### ISSUE TITLE
i can't change the adminLTE skin

### ISSUE THREAD

**Issue by SirCrowley** [almasaeed2010/AdminLTE#899]
Hi, Please can you tell me the issue to used a skin,
i'have already add the stylesheet in header, add "skin-yellow" on the body's class and the button class too.

**Comment by almasaeed2010** [comment]
If you did all of that correctly, then you should get the skin you chose. Make sure you remove the old skin class from the body tag.

**Comment by duythang** [comment]
@almasaeed2010 : Hi, i also met same issue with 2.3.11 version. i changed from skin-blue to skin-red in body tag. However, sidebar did not change color.

Can you help us check it ? Thank you

**Comment by REJack** [comment]
I've tested it in my project and it works correctly.

@duythang which color your mean with "sidebar did not change color.", the active state or the whole background?

**Comment by KyoBerthold** [comment]
$(document).ready(function (){
    $("#skin-yellow").click(function () {
      $("body").removeClass("skin-blue").addClass("skin-yellow");
      ajax({
      });
    });
});        

This is the javascript code to change the skin colour in adminlte. Iam able to change the colour .. but iam not able to save the changes. It goes to default colour settings when the page is loaded or when we log in again. I need help with the step by step code to solve this using laravel.
