### ISSUE TITLE
Feature Request: add responsive plugin to DataTables, for mobile devices

### ISSUE THREAD

**Issue by DiMono** [almasaeed2010/AdminLTE#901]
If you load up a table on a mobile device in this theme, the table is cut off on the right, because tables are not mobile-friendly. However, since the theme prevents mobile users from scrolling left-to-right, there is no way for them to see the cut-off information. ikhsan017's reply, below, points out there is a responsive plugin for DataTables that solves this problem. Can it be added to the theme by default?
![adminlte_scrolling](https://cloud.githubusercontent.com/assets/2582393/12666309/6931e45c-c60d-11e5-8857-c19534bc9beb.png)
[original request, preserved here for accountability: Can you allow left-right scrolling on mobile devices so they can see such table data?]

**Comment by ikhsan017** [comment]
You can enable the datatable responsive plugin to make the table responsive https://datatables.net/extensions/responsive/

**Comment by DiMono** [comment]
That is actually a very good solution, and I'd love to see it included in the theme by default. Thank you for directing me to it.

Developers, can this be added to the theme by default?

**Comment by almasaeed2010** [comment]
This plugin is already available within the template by default. We didn't add an example yet though. However, you will find the extension in ```plugins/datatables/extensions/responsive```.

Thanks!
