### ISSUE TITLE
How do i run AdminLTE?

### ISSUE THREAD

**Issue by sarment0** [almasaeed2010/AdminLTE#905]
I just downloaded, read all the documentation and guides, and i didn't found any information about this.

Tried, grunt serve, grunt, npm start. 
Nothing works.

What i have to do???

**Comment by 93ramadan** [comment]
You can always download the compiled version and use that I suppose ...

**Comment by sarment0** [comment]
@93ramadan I thought the objective of the template is to use as a template and create my own content and features. I forked and cloned the project. 
It's not supposed to run just running a command line?
