### ISSUE TITLE
Window footer height BUG

### ISSUE THREAD

**Issue by sarment0** [almasaeed2010/AdminLTE#906]
I'm having a curious bug using this template.
When open the inspect tool in the browser it automatically shrinks the window height, and it nevers go back to the initial state. 
But worse, when you refresh it, it stills with the same behavior, and the same small height (without the inspect tool opened), also it cover the rest of the menu.

Screenshot: [http://postimg.org/image/kjgbzjjah/](http://postimg.org/image/kjgbzjjah/)

Is this normal? How do i fix?
I'm using the default page (starter.html).

**Comment by PKriwin** [comment]
I have the same issue, how did you fix it?

**Comment by hfishere** [comment]
@sarment0  why you close this thread? I have same issues, if you done with it. Please share to us dude..
