### ISSUE TITLE
Left Nav Expand and footer Issue

### ISSUE THREAD

**Issue by DawoudIO** [almasaeed2010/AdminLTE#915]
Hi, 

I love this AdminLTE system, and we are using it for a [ChurchCRM ](https://github.com/ChurchCRM/CRM) system. I got the following issue where when the left nav folders expand, it does not update the page height.

see https://github.com/ChurchCRM/CRM/issues/272

Any ideas?
Thanks in advance.

**Comment by almasaeed2010** [comment]
Hello,

I am not sure why the issue happens. In most cases, this issue occurs when there is a missing html tag. I suggest you check your html and try again.

Thanks!

**Comment by DawoudIO** [comment]
OK i think i fixed it in the following [commit  ](https://github.com/ChurchCRM/CRM/commit/f0e3382fd750835ecd534fac8778854d9e2a881e)it was due to using `<aside class="right-side">`  for the main content vs  `<div class="content-wrapper">` but please note, this is step 3 in the [upgrade doc](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade)

> Change the .right-side class to .content-wrapper <div class="content-wrapper">
