### ISSUE TITLE
Problem with angular and app.js initialization

### ISSUE THREAD

**Issue by TobiasKoller** [almasaeed2010/AdminLTE#916]
I'm using angular-js with your admin lte-theme. 
Now I'm facing an issue when i add the app.js of the theme directly to my index.html.

it seems that the outerHeight() of the main-footer is null on init...

here is my Workaround.
would be nice to have this fixed without my Workaround ;)

     angular.element(document).ready(function () {
       
        function checkMainFooter() {
            var height = $(".main-footer").outerHeight();
            console.log(height);
            if (height == null) {
                setTimeout(checkMainFooter, 100);
                return;
            } else {
                $.ajax({
                    url: "assets/adminlte/js/app.min.js",
                    dataType: "script",
                    success: () => {
                    }
                });
            }
            
        }

        checkMainFooter();
    });

**Comment by almasaeed2010** [comment]
Depends on you implementation with Angular. The ```.outterHieght()``` function is used multiple times within the script. So if it isn't working only on the footer, then there is something interfering with the footer while the code loading. 

Check the console for errors.

Thanks!
