### ISSUE TITLE
sidebar-wrapper

### ISSUE THREAD

**Issue by LeonardoGentile** [almasaeed2010/AdminLTE#919]
In the layout section of the docs I've read that 
> Sidebar `.sidebar-wrapper`. Contains the user panel and sidebar menu.

but I couldn't find any reference to this class. In fact in the examples it seems that a class `.main-sidebar` is always used as the sidebar wrapper.

Which one is the correct one, maybe the docs are not in sync?

**Comment by almasaeed2010** [comment]
It should be ```.main-sidebar```. I will fix that soon.


Thanks!

**Comment by LeonardoGentile** [comment]
:+1:
