### ISSUE TITLE
Side bar menu will not collapse with iPad and iPad Mini

### ISSUE THREAD

**Issue by mooret1979** [almasaeed2010/AdminLTE#920]
I cannot for the life of me figure out how to get the side bar (Left Side Column) menu to collapse when you view it on an iPad or iPad Mini when it is in portrait view.   When in landscape I want to appear as it does normally with the left side open.

Please help me with this I driving my self nuts!!!!

**Comment by mooret1979** [comment]
I see this is closed.  How can I fix this.   The side menu bar is still not collapsing on iPad.

**Comment by almasaeed2010** [comment]
We apologize for not addressing the issue. We closed it since it has been open for too long without activity.

AdminLTE uses the predefined LESS screen-(size) variables that Bootstrap provide to set the sidebar's collapse state. To customize those, you will need to recompile AdminLTE.less with values of your choosing. The variables that might interest you are ```$screen-xs``` and ```$screen-sm```.

**Comment by mooret1979** [comment]
ok.   Is that the pixel size?  Like 767?    How do I recompile it?   I am currently using Dreamweaver CC 2015.    Would I be able to send you my file or can you send me one for ipad settings?

**Comment by almasaeed2010** [comment]
Yes that would be the screen size in pixels. To compile it, you need to use the LESS compiler that you can get here: http://lesscss.org/

I apologize but I don't currently do custom work. In our opinion, the current settings work nicely with the screen sizes we have. You may want to experiment with different sizes if you like. 

Thanks!

**Comment by mooret1979** [comment]
ok.  I am looking through the less files and not seeing the max or minimum width for collapsing the side-bar.   I found this in the sidebar.less but not sure what to change?   Just give me a little direction on what the value/variable should look like in these files and i am sure i can find it.

`.main-sidebar,
.left-side {
  position: absolute;
  top: 0;
  left: 0;
  padding-top: 50px;
  min-height: 100%;
  width: @sidebar-width;
  z-index: 810;
  //z-index originally 810
  //Using disposable variable to join statements with a comma
  @transition-rule: @transition-speed @transition-fn,
    width @transition-speed @transition-fn;
  .transition-transform(@transition-rule);
  @media (max-width: @screen-header-collapse) {
      padding-top: 100px;
  }
  @media (max-width: @screen-xs-max) {
    .translate(-@sidebar-width, 0);
  }
  .sidebar-collapse & {
    @media (min-width: @screen-sm) {
      .translate(-@sidebar-width, 0);
    }
  }
  .sidebar-open & {
    @media (max-width: @screen-xs-max) {
      .translate(0, 0);
    }
  }
}`

**Comment by almasaeed2010** [comment]
The bootstrap variables you are looking for are available at build/bootstrap-less/variables.less.

**Comment by mooret1979** [comment]
ok.  I think i found it.    Trying to modify as needed.   If I cannot figure it out I may need to contract someone to do it.  

Thanks



 `//== Media queries breakpoints
//
//## Define the breakpoints at which your layout will change, adapting to different screen sizes.

// Extra small screen / phone
//** Deprecated `@screen-xs` as of v3.0.1
@screen-xs:                  480px;
//** Deprecated `@screen-xs-min` as of v3.2.0
@screen-xs-min:              @screen-xs;
//** Deprecated `@screen-phone` as of v3.0.1
@screen-phone:               @screen-xs-min;

// Small screen 768 / tablet
//** Deprecated `@screen-sm` as of v3.0.1
@screen-sm:                  768px;
@screen-sm-min:              @screen-sm;
//** Deprecated `@screen-tablet` as of v3.0.1
@screen-tablet:              @screen-sm-min;

// Medium screen / desktop
//** Deprecated `@screen-md` as of v3.0.1
@screen-md:                  992px;
@screen-md-min:              @screen-md;
//** Deprecated `@screen-desktop` as of v3.0.1
@screen-desktop:             @screen-md-min;
`

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (410/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:54057 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMN-000af0-Uk
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:01 +0100
Date: Sun, 13 Mar 2016 17:41:52 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457916112;
	bh=BDxZmlsZKivsiAxB/Q+/xNyxqXXdukLW4OghBVx5LQE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=KxXD8lV0WKZg1kLl3YA8JZ5ykzft8h+efIa4WcNRQNUPBOwiVouQLmYKRxS8d6b40
	 23qo6HMclqdmUA4hlwe9BLrUyMHW4ebOQvgrogWzrl5cHTOzozXOgDrRg4NjBfCPg4
	 wjdvTJVXqP893GheQf8WXiN0Bpo+xI6UDrF2Q5Tk=

**Comment by timoteo7** [comment]
in adminlte.js has default option =
> collapseScreenSize   : 767

#1720
