### ISSUE TITLE
support rtl ?

### ISSUE THREAD

**Issue by ghost** [almasaeed2010/AdminLTE#921]
hi this project support rtl ?

other fork rtl is not work and not responsive

**Comment by lxsameer** [comment]
@mohammadninja you can take a look at #618 and also you can use Yellowen/admin_lte-rails gem

**Comment by mohammadninja** [comment]
@lxsameer i want to use for php code

**Comment by lxsameer** [comment]
@mohammadninja doesn't matter you can still build the gem and use the resulted SASS/SCSS and javascript files in your project
