### ISSUE TITLE
ckeditor is out of date

### ISSUE THREAD

**Issue by donaldinho** [almasaeed2010/AdminLTE#922]
Version included with AdminLTE is over two years old. version included with AdminLTE is 4.3.1 and the current version of CKEditor 4.5.7

**Comment by judodan** [comment]
I noticed this too, then I noticed that the demo is linking to CKEditor via CDN, like so:

<script src="https://cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>

but still an old version, using 4.4.3.  You can, obviously, change that easily. But it begs the question...  Why include it in the distro if you are linking to the CDN?

(Awesome theme, tho!)

**Comment by almasaeed2010** [comment]
Updated.

Sorry for the (very long!) delay.
