### ISSUE TITLE
How to set Visiter couter in Visiter map 

### ISSUE THREAD

**Issue by Asifkhangithub** [almasaeed2010/AdminLTE#927]
on index.html page there is one visitors map 
i want to know where the number comes from ??
like India:800 New visitors 
the "800 New Visitor" comes from ???

**Comment by almasaeed2010** [comment]
Please check the dahboard.js file under dist/js/pages/.

**Comment by Asifkhangithub** [comment]
Thanks for reply bt i had solved that
