### ISSUE TITLE
Location of DataTables sort images

### ISSUE THREAD

**Issue by chetcuti** [almasaeed2010/AdminLTE#928]
I'm trying to replicate the look of the table listed under "Data Table With Full Features", but the sort images aren't displaying. I tried to find the CSS where the images are referenced, or the images themselves, but I can't find either. I've looked through all of the CSS files and the images aren't referenced, and I've searched the entire AdminLTE folder and the images don't seem to be there either. I feel like I'm losing my mind, it should be such a simple fix. I even downloaded the archive again in case something happened to mine, but I had the same result.

Which CSS files contain the images, and what's the absolute path of the images?

I'm not sure if it'll help, but this is my setup...

I'm including (CSS):
**dataTables.bootstrap.css**

And (JS):
**jquery.dataTables.js** (The "Data Table With Full Features" example doesn't use jquery.dataTables.js, however if I don't it just doesn't work at all.)
**dataTables.bootstrap.js**

My table:
`<table id="segments" class="table table-bordered table-striped">`

Page footer:
    $('#segments').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });

**Comment by almasaeed2010** [comment]
DataTables uses Bootstrap Glyphicons, which are included by default with Bootstrap 3.
