### ISSUE TITLE
datatable seems not working

### ISSUE THREAD

**Issue by wandiong** [almasaeed2010/AdminLTE#929]
Hi
I got a problem, 
I've tried to pulling data table plugin out. but it returns

> Uncaught TypeError: $(...).dataTable is not a function

can I know why?

note : I'm already tried DataTable instead, but also not working

code

[css.blade.zip](https://github.com/almasaeed2010/AdminLTE/files/135573/css.blade.zip)

**Comment by judodan** [comment]
Easiest is to use something like Chrome dev tools when you load your site.  Ensure that the datatable files are loaded.

**Comment by wandiong** [comment]
hi @judodan 
its solved
the root cause is because I calling jquery link twice, n ended code conflicting so it will return that error

thanks for helping me :+1:
