### ISSUE TITLE
Search box appears to be broken on Android when using the fixed layout

### ISSUE THREAD

**Issue by chetcuti** [almasaeed2010/AdminLTE#932]
As the title says, I think the search box may be broken on Android when using the fixed layout. When I click on the search box the keyboard pops up, but it almost instantly disappears and the focus is no longer on the search box. I've tried this with other layouts and it works fine, it's just the fixed layout that has this issue.

I thought maybe it was something odd in my own code so I tried a default AdminLTE install and had the same result.

I also tried this on two different iPhone versions and it worked fine, so it seems to be Android-specific.

**Comment by Patrick-Berg** [comment]
We noticed the same issue on Android devices but also on the iPad mini. Don't know about other iPads. Seems to work on iPhone.

**Comment by kirrabelete** [comment]
I also have the same problem on all android browsers with the search box. Fyi it works if you tap on the search box three or more times.

**Comment by almasaeed2010** [comment]
#949

**Comment by chetcuti** [comment]
I'm a bit confused by this issue being marked as closed. The only other issue it references is one posting the same problem, but neither of them have a response regarding the actual bug or a resolution.
