### ISSUE TITLE
Tricky box CSS adjustment AdminLTE+highcharts heatmap

### ISSUE THREAD

**Issue by llermaly** [almasaeed2010/AdminLTE#933]
Hello, first of all thanks for this nice template!! , and sorry for my english, it is not my native language.

I'm using adminLTE boxes with a Highcharts Heatmap chart and I'm having this problem : 

https://i.gyazo.com/df37ba1722a54c3be8a6cce0d43ffdfa.png

As im fixing the divs height the box is not adjusting to this height , this is the div : 

`<div id="chart_heatmap" style="height: 1000px; min-width: 500px; max-width: 900px; margin: 0 auto"></div>
`

And this is how it looks without height parameter 

https://i.gyazo.com/0753f160e53ffcd2c239b533bee39641.png

I want first picture look but inside the box as 2nd picture.

Any help is really appreciated.

JSFIDDLE : https://jsfiddle.net/llermaly/pay7pe9u/

REGARDS

**Comment by iaesaudi** [comment]
why not just give more height to the inner cells so it stretch well in the theme and still responsive ?
