### ISSUE TITLE
"active" class in sidebar menus

### ISSUE THREAD

**Issue by serghei-topor** [almasaeed2010/AdminLTE#934]
Hi, Abdullah.
Your framework is great. I use it in all my projects. There is one bug(feature?) that is very important for me - the behavior of class "active" in sidebar. Let pretend we have single sidebar item A(which is active) and collapsible tree menu B. When you collapse/expand menu B, menu A will lose class "active".
Thanks in advance

**Comment by Eco012390** [comment]
please fix it T_T

**Comment by almasaeed2010** [comment]
Hello,

This has been addressed several times with the conclusion that this would be fixed in version 3.0. We apologize for the inconvenience.
