### ISSUE TITLE
Usage of the name AdminLTE

### ISSUE THREAD

**Issue by nook24** [almasaeed2010/AdminLTE#937]
Hi @almasaeed2010,

I found your AdminLTE theme a few day a go and like to use it for my open source project https://github.com/nook24/statusengine.

My question, can i use the name "AdminLTE" in my theme select box where the user can switch the style and on my project page so that people know what the need to google for if they are interested in your theme?

Additionally like to create a link "Powered by AdminLTE" to your github repository on my project page.

PS: Really nice and powerful theme, thanks a lot :)

Best regards,

Daniel

**Comment by almasaeed2010** [comment]
Hello @nook24 

That's fine to do as long as your product itself is not called AdminLTE :)

Thanks!

**Comment by nook24** [comment]
Many thanks for your fast reply.
I will close the issue :)
