### ISSUE TITLE
Your file contains a virus

### ISSUE THREAD

**Issue by ardianzack** [almasaeed2010/AdminLTE#939]
I trying upload zip file to hosting and the result is fail uploading

Error message:
_**The file you uploaded, AdminLTE-master.zip, contains a virus so the upload was canceled: Zip.Suspect.MacroDoubleExtension-zippwd FOUND**_

**Comment by gbaudoin** [comment]
Must be false positive from ClamAV: [VirusTotal analysis: 1/55](https://www.virustotal.com/fr/file/e75396fb1dce2e7e7419804035456a93828d300216d5f89ddf49ca10e6fe3673/analysis/1456391166/)

This file comes from Github download as zip feature. The [.zip file available in Downloads](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#download) also brings the [same result from VirusTotal (1/55)](https://www.virustotal.com/fr/file/137f99e112d81d40a89a1729f69bf0e9ff5646ac158ad0e491d91a01130dfdd7/analysis/1456391484/)
