### ISSUE TITLE
Update plugin

### ISSUE THREAD

**Issue by tiagojavaman** [almasaeed2010/AdminLTE#940]
Hello,
It is Possible to update the jquery- inputMask template plugin? The version attached the template is quite outdated.

Congratulations on the template , tks

**Comment by johnitvn** [comment]
Just download and replace file plugins/input-mask/jquery.inputmask.js
So easy


==========================================================
[Free download wordpress theme](http://w3deep.com/wordpress-theme/)
[Free download html template](http://w3deep.com/html-template/)

**Comment by tiagojavaman** [comment]
johnitvn , I did it . Only suggest upgrading to improve the quality of the template and demos. tks

**Comment by paulodealmeida** [comment]
@johnitvn I made a PR but I did not have any response about it. I don't know if it is ok, or if it is wrong. I am very disappointed about this project.

**Comment by laudeco** [comment]
@paulodealmeida can you link the ticket to the PR please :)

**Comment by paulodealmeida** [comment]
@laudeco 
https://github.com/almasaeed2010/AdminLTE/pull/911

**Comment by laudeco** [comment]
Thanks :D
