### ISSUE TITLE
how to add a scroll bar in the left sidebar

### ISSUE THREAD

**Issue by paul3333** [almasaeed2010/AdminLTE#946]
hi, can i ask how to add a scroll bar in the left sidebar, and with width option
i captured a screen
![how to add a scroll bar](https://cloud.githubusercontent.com/assets/17485651/13339919/3182621e-dc67-11e5-8d5a-2f1dadd6ecd0.jpg)

thx

**Comment by almasaeed2010** [comment]
You can attempt using ```slimscroll``` 
https://github.com/rochal/jQuery-slimScroll

Thanks!
