### ISSUE TITLE
Search box doesnt work on android brawsers with fixed layout

### ISSUE THREAD

**Issue by kirrabelete** [almasaeed2010/AdminLTE#949]
Hey guys, great work on this theme.

I have a problem with the search box on the side-nav. When the layout is on fixed mode the search input box doesnt work on android brawsers.
What happens is when you try to type on the search box the keypad of the phone disappears immediately.  I really want to use the fixed layout.

Thanx.

**Comment by almasaeed2010** [comment]
#932

**Comment by kirrabelete** [comment]
hey guys the issue you referenced this with is also closed with out being resolved. it would be great if you give us a reason why those issues are closed. tnx
