### ISSUE TITLE
Unable to update color for current/active pagination button

### ISSUE THREAD

**Issue by chetcuti** [almasaeed2010/AdminLTE#951]
I'm using the AdminLTE red theme but the current/active pagination button is blue, so I'm trying to update it to mesh with the red theme a bit more. I have found the CSS where the datatables site says this is to be updated, however changes don't seem to do anything. I would imagine this is because the AdminLTE implementation is more customized, and this colour is getting picked up from somewhere else, however I just can't find where to update it.

The code that the datatables site says to update is, but changing the colors doesn't change the current/active button color:

```
.dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
  color: #333 !important;
  border: 1px solid #cacaca;
  background-color: white;
  background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, white), color-stop(100%, #dcdcdc));
  /* Chrome,Safari4+ */
  background: -webkit-linear-gradient(top, white 0%, #dcdcdc 100%);
  /* Chrome10+,Safari5.1+ */
  background: -moz-linear-gradient(top, white 0%, #dcdcdc 100%);
  /* FF3.6+ */
  background: -ms-linear-gradient(top, white 0%, #dcdcdc 100%);
  /* IE10+ */
  background: -o-linear-gradient(top, white 0%, #dcdcdc 100%);
  /* Opera 11.10+ */
  background: linear-gradient(to bottom, white 0%, #dcdcdc 100%);
  /* W3C */
}
```

The button I'm referring to/trying to change from blue is: http://i.imgur.com/bMtoBdp.png

Does anyone have any idea where to update this?

**Comment by chetcuti** [comment]
For anyone else trying to figure this out, it's located in bootstrap.min.css. Just search for the following code:

`.pagination>.active>span:hover{z-index:3;color:#fff;cursor:default;background-color:#337ab7`

**Comment by cenxun** [comment]
I think this feature need be added  @almasaeed2010
