### ISSUE TITLE
Best way to locate HTML pages in boxes

### ISSUE THREAD

**Issue by yigaloz** [almasaeed2010/AdminLTE#955]
Hi,

First, TNX a lot for your great work!
I just downloaded the theme and started playing with it. I have 2 quite "basic" questions:

1) I want to customize the boxes at the index page and locate there some data tables [for instance]. In addition, I would like to use other HTML page for that (In order to reduce the code at the index page).
What is the best practice for that (Use an iframe maybe?) Do you have an example?

2) I noticed that every time I choose one of the options in the side bar, it refreshes all page. What is the best way to prevent it?

TNX,
Yigal.

**Comment by almasaeed2010** [comment]
Hello,

1) The best way to reduce lines of code on a file is to a backend language to include your partial code. For example, using PHP you can say ```include "visitors_box.php"```.

2) There are multiple ways to do that, all of them use AJAX. You may consider libraries such as AngularJS or pjax.

Thanks!
