### ISSUE TITLE
App.js Slimscroll not changing 

### ISSUE THREAD

**Issue by kressly** [almasaeed2010/AdminLTE#956]
Hello
I downloaded the new theme and I am trying to modify it and make slimscroll bigger on the menu like in the precedent version. So I added this
```

if (o.navbarMenuSlimscroll && typeof $.fn.slimscroll != 'undefined') {
    $(".navbar .menu").slimscroll({
     height: "200px",
        alwaysVisible: true,
        size: "15px",
		
		color : "#0073b7", 
       
		railVisible: true
    }).css("width", "100%");
  }

```
But nothing is changing. Can you help me figure out what is not right here ?

Thanks

**Comment by almasaeed2010** [comment]
In app.js you can configure the size of slimscroll for the sidebar as shown in the screenshot below.

<img width="584" alt="screen shot 2016-03-13 at 8 38 05 pm" src="https://cloud.githubusercontent.com/assets/1512664/13732539/84412c50-e95b-11e5-8617-009782bf4265.png">

Thanks!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (403/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:49570 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLe-000aXF-NV
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:37:21 +0100
Date: Sun, 13 Mar 2016 17:39:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457915950;
	bh=GOYivIo1DmPqa+I6qJaTE6OcB4syFb1k+bSksWnzVr0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Bajx2QB5gf8gDQjMlEIXX8De9njMFBC8ype3eLuAaCIu1d5AhxqAB1een4MKSpgKL
	 1+bQ7fy0tWcZknoDB9JVbkLkhQWBTlKC0cJ+FXvDcZ6LNJ+GFtKqIp4nQRKl8ayT+J
	 QErsLfyvadf1cRWiveU+JvOj1c1EV4MALlysj4Fs=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (428/400 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:57436 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNH-000atD-LM
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:57 +0100
Date: Sun, 13 Mar 2016 17:39:17 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457915957;
	bh=4z2JzlgbzgkwVMsMK7+r1GA8TthTGWO/vw/zZf8Hbg4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=AV59rCweAg1+V2sNGb9yMgx4FIscvv95izOUkMIWU5WjBql+vuFjl4Puu++MdcM8+
	 SOmlDwHI0jGuoFNz/8iaiO2a40GHD8FwSYlprqQjUQJn1WtA6U7jNM2Ou6Bcb4lrIp
	 1/z9bZio+Dkd5p1K3lusBgQLbEsiZR0PBKf3HEOA=
