### ISSUE TITLE
Pace doesn't show on Black Skin

### ISSUE THREAD

**Issue by AdenFraser** [almasaeed2010/AdminLTE#957]

**Comment by almasaeed2010** [comment]
That would be because it's color is white. We will try to fix that soon. 

Thanks for letting us know!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (406/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:48298 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLl-000aY8-4M
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:37:29 +0100
Date: Sun, 13 Mar 2016 17:39:52 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457915992;
	bh=UjUrDpy+8gSgZ6UQ5OePOcWhbdg4BEW5mYEu4hQ0LrA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OMZiH+knJx1wKNoxyQgZc3h+8x1OMyBNb/rphwq/VO6XzXcFLESujYkBEaI4JxemV
	 5nxkDqmfCGUK+8dxlY3M6N8xmJGYeUuCk95uXrRBw28/CLlg7KwKJoGJePVZR3L/81
	 wgplNvjX5zc9ozuAF6TKrzL7Ct1ceIqTrfbld9S0=
