### ISSUE TITLE
Hide left panel 

### ISSUE THREAD

**Issue by tanvan81** [almasaeed2010/AdminLTE#959]
i use all the default (AdminLTE main-header and Left Sidebar) for a Admin panel

but if i want to make a layout is for normal visitors :
1. when user open page, left panel alway hide

please, see attach file

First: http://imgur.com/k8xBguv

And I want to change

http://imgur.com/VlACVoE

**Comment by paul3333** [comment]
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect

SKINS :
skin-blue
skin-black
skin-purple
skin-yellow
skin-red
skin-green

LAYOUT OPTIONS :
fixed
layout-boxed
layout-top-nav
sidebar-collapse
sidebar-mini

add the sidebar-collapse to body tag
`
<body class="hold-transition skin-blue sidebar-collapse sidebar-mini fixed">
`

**Comment by tanvan81** [comment]
tks for support, i will try

**Comment by posillipo** [comment]
I have the same problem but the example is not suitable. the left sidebar does not remain hidden. 
how can you solve?
thank you
