### ISSUE TITLE
Sidebar Expands to whole screen when I Refresh

### ISSUE THREAD

**Issue by pdctpa** [almasaeed2010/AdminLTE#960]
I checked on your demo site, it does not happen as its happening on my site. When ever I click on refresh, the whole sidebar expands to the whole screen and the user profile image covers the top screen. After refresh, it comes back to normal. Could anyone guide me where I am going wrong please?
![screenshot_1](https://cloud.githubusercontent.com/assets/12509947/13652802/5376330c-e674-11e5-881f-47bd33ce0359.png)

**Comment by almasaeed2010** [comment]
Please make sure that you have included all the required files. It seems like you are missing some CSS files. Check your console to make sure you have loaded them successfully.

**Comment by pdctpa** [comment]
I checked each every bit of code. And included all your files but still not able to resolve. Even when I checked your demo site on pace example page, it also reloads like this especially footer area
