### ISSUE TITLE
Sidebars Toggling

### ISSUE THREAD

**Issue by DoctorsOpinion** [almasaeed2010/AdminLTE#961]
Hello Sir,
We are using AdminLTE v2.1 theme. Left Navigation Sidebar and Right Control Sidebar are not toggling sometimes. After page refresh or postback they are working again perfectly. Why this is happening so? We have created pages as per the documentation provided along with it but still facing this issue.
Thanks and Regards.

**Comment by almasaeed2010** [comment]
Hello,

Please update the css and js files to v2.3.

**Comment by DoctorsOpinion** [comment]
Hello Sir,

Thank you for your prompt reply. As per your suggestion we have updated all the important css and js files to v2.3 as per mentioned in up-gradation guide. We have created  jQuery onclick function through which we are toggling body tag css class. Its working perfectly for resolution starting from **768x1280** onward. But toggling not working for **mobile devices** below that resolution.

**jQuery code snippet:**
<script type="text/javascript">
        $('#righttoggle').click(function () {
            $("body").toggleClass("sidebar-collapse");
        });
    </script>

**Sidebar Issue Screenshot:**
![toggle issue](https://cloud.githubusercontent.com/assets/17758406/13769781/51e03a5a-eaa8-11e5-993b-9e6410af073c.png)

Thanks and Regards.
