### ISSUE TITLE
How to integrate AdminLTE with Meteor JS?

### ISSUE THREAD

**Issue by thearabbit** [almasaeed2010/AdminLTE#965]
I would like to integrate `AdminLTE` whit `Meteor JS`, but have problem with `any event handler` such as `data-toggle=offcanvas, content-wrapper, ...`.
So I need to split these event in `Meteor Template Event`
```js
Template.myAdminLTE.events({
'click [data-toggle=offcanvas]':............
..............
any event
})
```
Please help me to complete these.

**Comment by timsvoice** [comment]
Hey @thearabbit, have you looked at the the two Atmosphere packages for this?

https://atmospherejs.com/yogiben/admin (iron router)
https://atmospherejs.com/sach/flow-db-admin (flow router)

There appear to be some issues with the Meteor 1.3-beta releases but they work great with 1.2

**Comment by thearabbit** [comment]
I used to try, it use package `'mfactory:admin-lte`.
And then I try add to my project, but have problem with page footer

![2016-03-13_16-07-02](https://cloud.githubusercontent.com/assets/4495160/13732926/3dc0edb6-e9be-11e5-9d07-1300d178fb86.png)

**Comment by marrullas** [comment]
I have the same problem too @thearabbit the solved?

**Comment by thearabbit** [comment]
still the same problem with `large  sidebar`.
