### ISSUE TITLE
Question - Getting Started?

### ISSUE THREAD

**Issue by wdhodges** [almasaeed2010/AdminLTE#966]
I'm trying to find a getting started on the AdminLTE. I'm using the Serenity Platform and would like to put the AdminLTE in it but have no where to start. I'm sorta new ish to website design, coming fresh over from WPF.NET

**Comment by c9n** [comment]
https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html

**Comment by wdhodges** [comment]
That's true, but what I'm wondering is how do I get the Direct Chat to actually work, or the To-Do list to actually work, the email to actually work etc etc. 

Thanks for your help!

**Comment by janhaa** [comment]
This is out of scope of this project I guess.

**Comment by almasaeed2010** [comment]
Hi,

You need to learn a back-end language such as PHP or ASP.NET. From there you can implement all of the features of AdminLTE. This is not a fast nor easy process but it is the right one.

Best of luck!

**Comment by wdhodges** [comment]
Thank you guys!! Asp.net it is!
