### ISSUE TITLE
sidebar treeview get collpase

### ISSUE THREAD

**Issue by akshay12345vin** [almasaeed2010/AdminLTE#967]
when i click on new page li in sidebar treeview 

treeview get collapse but in downloaded theme treeview is working fine why?

**Comment by almasaeed2010** [comment]
Could you please clarify your question? Screenshots can help a lot.

Thanks!

**Comment by akshay12345vin** [comment]
i mean in your demo when i click li in treeview for next page treeview stay open and show me where i am but in my website it dost show me where i am it just collapse that treeview are you get my question now?

**Comment by pdctpa** [comment]
You need to use active class for the current page.

**Comment by akshay12345vin** [comment]
it dost working please help with code

**Comment by Dragnucs** [comment]
Please ensure your <body> dosn't have a `sidebar-collapse` class.

**Comment by pdctpa** [comment]
@akshay12345vin, share your code, we'll know the issue.

**Comment by akshay12345vin** [comment]
my body have these three classes
"hold-transition skin-black sidebar-mini"


my sidebar code

 <aside class="main-sidebar">

        
        <section class="sidebar">
          
          <div class="user-panel">
              <img src="dist/img/Restocaptainlogo.png" class="img-responsive" alt="User Image">
            
          </div>

          
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          

          
          <ul class="sidebar-menu">
            <li class="header">HEADER</li>
            
            <li class="active">
              <a href="#"><i class="fa fa-home"></i> <span>HOME</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="dashboard.html">DASHBOARD</a></li>
              </ul>    
            </li>
            <li>
              <a href="#"><i class="fa fa-book"></i> <span>MASTERS</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="menu_option.html"><i class="fa fa-circle-o"></i>MENU OPTIONS</a></li>
                <li><a href="item.html"><i class="fa fa-circle-o"></i>ITEM</a></li>
                <li><a href="table.html"><i class="fa fa-circle-o"></i>TABLE</a></li>
                <li><a href="user.html"><i class="fa fa-circle-o"></i>USER</a></li>
              </ul> 

            </li>
            <li class="treeview">
              <a href="#"><i class="fa fa-calendar-o"></i> <span>ORDER</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="order.html"><i class="fa fa-circle-o"></i>ORDER</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#"><i class="fa fa-trello"></i> <span>REPORTS</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i>DAILY COLLECTION</a></li>
                <li><a href="waiter_report.html"><i class="fa fa-circle-o"></i>Waiter Report</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#"><i class="fa fa-gear"></i> <span>SETTINGS</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="tax_billing.html"><i class="fa fa-circle-o"></i>TAX BILLING</a></li>
                 <li><a href="tax_item.html"><i class="fa fa-circle-o"></i>TAX ITEM</a></li>
                <li><a href="resto_info.html"><i class="fa fa-circle-o"></i>RESTAURANT INFO</a></li>
                <li><a href="tax_group_item.html"><i class="fa fa-circle-o"></i>TAX GROUP ITEM</a></li>
                <li><a href="#"><i class="fa fa-circle-o"></i>SMS</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#"><i class="fa fa-umbrella"></i> <span>HELP</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i>HELP</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#"><i class="fa fa-money"></i> <span>OFFER ZONE</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="offer_zone.html"><i class="fa fa-circle-o"></i>MANAGE OFFER</a></li>
              </ul>
            </li>
          </ul>
        </section>
      </aside>

**Comment by akshay12345vin** [comment]
1) default look before clicking
2) now i open the treeview and click on menu option link
3) i go to that page and sidebar reset to dashboard and also the tree view collapse 

![before any click](https://cloud.githubusercontent.com/assets/10510889/14274599/f48163aa-fb2f-11e5-83bc-33ed10559574.png)
![it only shows the page but treeview is closed now](https://cloud.githubusercontent.com/assets/10510889/14274600/f49f23b8-fb2f-11e5-901a-34d6aa376254.png)
![when click on newpage in treeview](https://cloud.githubusercontent.com/assets/10510889/14274601/f4a1264a-fb2f-11e5-8719-5128e50b2e29.png)

**Comment by Dragnucs** [comment]
Dismiss my previous post, I thought you were talking about the whole sidebar. The simplest way to solve your problem is to click on the link you want and inspect it. Just see where `active` class is and reproduce them in your destination page.

For example:
```html
<ul class="sidebar-menu">
	<li class="active treeview">
        <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
            <li><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
            <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
        </ul>
    </li>
</ul>
```

**Comment by akshay12345vin** [comment]
Perfect thanks issue fixed and topic closed
