### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by sicarpv** [almasaeed2010/AdminLTE#968]
I need active all menus on my sidebar, but I don't how to do.

**Comment by almasaeed2010** [comment]
Could you please elaborate on your issue please?

**Comment by sicarpv** [comment]
I need active all sidebar-menu, but how to do? because actuality I dont not. I need add class for explained all menu

**Comment by almasaeed2010** [comment]
Any menu can be "active" by adding the ```active``` class on the ```li``` element. 

Here is an example:
```html
<li class="active">
  <a href="link.php">Link title</a>
</li>
```

**Comment by sicarpv** [comment]
I have this: 
```
<ul>
<li>
 <ul>
  <li></li>
</ul>
</li> 
</ul>
```

is necessary add class='active' for all `<li></li>` in the tree

**Comment by almasaeed2010** [comment]
Yes.

**Comment by sicarpv** [comment]
Thks, working right now...
See you.
