### ISSUE TITLE
Help with menu, how to quit collapse

### ISSUE THREAD

**Issue by sicarpv** [almasaeed2010/AdminLTE#969]
How to quit the collapse in sidebar-menu, Only need the links for create sub-menu
Exam:

-Menu
-- Sub-Menu
---Sub-Sub-Menu

But I dont not collapse went click any menu, all active all time.
Thks.

**Comment by almasaeed2010** [comment]
I don't think that's possible without disabling javascript. To do that, remove app.js (or comment it out).

**Comment by sicarpv** [comment]
Ok, thks.

On Mon, Mar 14, 2016 at 2:55 PM, Abdullah Almsaeed <notifications@github.com
> wrote:

> I don't think that's possible without disabling javascript. To do that,
> remove app.js (or comment it out).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almasaeed2010/AdminLTE/issues/969#issuecomment-196517555>
> .
>



-- 

*--*
*SICAR Punto de Venta*
*Tel:* 01 (317) 382 6696
*WhatsApp:* (317) 103-3714
*Email:* info@sicar.mx
*Web:* www.sicar.mx
