### ISSUE TITLE
Data Table With Full Features and PHP/MySQL

### ISSUE THREAD

**Issue by FMaynard** [almasaeed2010/AdminLTE#972]
Hi, I used the table shown in "Data Table With Full Features" example (class="table table-bordered table-striped") with data loaded by a PHP/MySQL loop and the and Search box, Show N entries, and Pagination disappeared.
What am I doing wrong?
Thanks in advanced

Regards, Felipe

**Comment by 93ramadan** [comment]
Hey Felipe,

If your using PHP, then you should only use it to print out HTML records as "tr" with all the data and etc.

And then at the end of your page, you would have to write the JavaScript code needed to initialize your DataTable based on the ID given to the element, not the class name (or you can do that too but it's not recommended).

The JavaScript Code to initialize your DataTable can be found in this sample page:
[Data Tables Sample Page in AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/pages/tables/data.html)

Hope this helps,

**Comment by FMaynard** [comment]
Thanks, it worked.
