### ISSUE TITLE
Mini the main sidebar as default

### ISSUE THREAD

**Issue by xchliu** [almasaeed2010/AdminLTE#979]
I use the .sidebar-mini and I want to make the sidebar on the left be mini as default.  I try to call a click action on the button, but doesn't work.
`$('#offcanvas').click();
`
Thanks for any help .

**Comment by almasaeed2010** [comment]
You should add the ```sidebar-collapse``` collapse class to the body tag to save the state. You don't need any javascript to do that.

Thanks.
