### ISSUE TITLE
AdminLTE in commertial web site

### ISSUE THREAD

**Issue by tester10** [almasaeed2010/AdminLTE#982]
Hy,
I wanna know if I have the right to use your free template in my web site and deleting your copyright ... knowing that my web site is a e-commerce website which mean that not every functionality on it is for free.
kind regard.

**Comment by Stoakes** [comment]
As it is said in the License : 

> AdminLTE is an open source project by Almsaeed Studio that is licensed under [MIT](https://opensource.org/licenses/MIT).

And  MIT license states : 

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions [..]

In other terms : yes you can.

**Comment by tester10** [comment]
okey, thank you so much.

**Comment by almasaeed2010** [comment]
Thanks @Stoakes
