### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by AdenFraser** [almasaeed2010/AdminLTE#985]
The changelog is out of date and i'm curious what the changes have been in the last two minor/patch versions?

**Comment by almasaeed2010** [comment]
We are going to remove the changelog that is, frankly, gonna get ginormous very quickly. And add release notes to each release. 

You can view the most recent relese note here: https://github.com/almasaeed2010/AdminLTE/releases/tag/v2.3.3

**Comment by AdenFraser** [comment]
Much more awesome, cheers!
